Chromium Omnibox: SuggestionAnswer::TextField Class Reference
SuggestionAnswer::TextField Class Reference
#include <suggestion_answer.h>
Public Member Functions
TextField ()
~TextField ()
TextField (const TextField &)
TextField (TextField &&) noexcept
TextField & operator= (const TextField &)
TextField & operator= (TextField &&) noexcept
const std::u16string & text () const
int type () const
TextStyle style () const
void set_style (TextStyle style)
bool has_num_lines () const
int num_lines () const
bool Equals (const TextField &field) const
size_t EstimateMemoryUsage () const
Static Public Member Functions
static bool ParseTextField (const base::Value &field_json, TextField *text_field)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest, DifferentValuesAreUnequal)
Private Attributes
std::u16string text_
int type_ = -1
bool has_num_lines_ = false
int num_lines_ = 1
TextStyle style_ = TextStyle::NONE
Constructor & Destructor Documentation
TextField() [1/3]
SuggestionAnswer::TextField::TextField () default
~TextField()
SuggestionAnswer::TextField::~TextField () default
TextField() [2/3]
SuggestionAnswer::TextField::TextField (const TextField &) default
TextField() [3/3]
SuggestionAnswer::TextField::TextField (TextField &&) default noexcept
Member Function Documentation
Equals()
bool SuggestionAnswer::TextField::Equals (const TextField & field) const
References has_num_lines_, num_lines_, text_, and type_.
EstimateMemoryUsage()
size_t SuggestionAnswer::TextField::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage().
FRIEND_TEST_ALL_PREFIXES()
SuggestionAnswer::TextField::FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest , DifferentValuesAreUnequal) private
has_num_lines()
bool SuggestionAnswer::TextField::has_num_lines () const inline
References has_num_lines_.
Referenced by SuggestionAnswer::ImageLine::ParseImageLine(), and OmniboxTextView::SetTextWithStyling().
num_lines()
int SuggestionAnswer::TextField::num_lines () const inline
References num_lines_.
Referenced by SuggestionAnswer::ImageLine::ParseImageLine(), and OmniboxTextView::SetTextWithStyling().
operator=() [1/2]
SuggestionAnswer::TextField & SuggestionAnswer::TextField::operator= (const TextField &) default
operator=() [2/2]
SuggestionAnswer::TextField & SuggestionAnswer::TextField::operator= (TextField &&) default noexcept
ParseTextField()
bool SuggestionAnswer::TextField::ParseTextField (const base::Value & field_json, TextField * text_field) static
References type_.
Referenced by SuggestionAnswer::ImageLine::ParseImageLine().
set_style()
void SuggestionAnswer::TextField::set_style (TextStyle style) inline
References style(), and style_.
style()
TextStyle SuggestionAnswer::TextField::style () const inline
References style_.
Referenced by OmniboxTextView::AppendText(), and set_style().
text()
const std::u16string& SuggestionAnswer::TextField::text () const inline
References text_.
Referenced by OmniboxTextView::AppendText().
type()
int SuggestionAnswer::TextField::type () const inline
References type_.
Member Data Documentation
has_num_lines_
bool SuggestionAnswer::TextField::has_num_lines_ = false private
Referenced by Equals(), and has_num_lines().
num_lines_
int SuggestionAnswer::TextField::num_lines_ = 1 private
Referenced by Equals(), and num_lines().
style_
TextStyle SuggestionAnswer::TextField::style_ = TextStyle::NONE private
Referenced by set_style(), and style().
text_
std::u16string SuggestionAnswer::TextField::text_ private
Referenced by Equals(), and text().
type_
int SuggestionAnswer::TextField::type_ = -1 private
Referenced by Equals(), ParseTextField(), and type().
The documentation for this class was generated from the following files:
components/omnibox/browser/suggestion_answer.h
components/omnibox/browser/suggestion_answer.cc