Chromium Omnibox: InMemoryURLIndex Class Reference
InMemoryURLIndex Class Reference
#include <in_memory_url_index.h>
Classes
class RebuildPrivateDataFromHistoryDBTask
class RestoreCacheObserver
class SaveCacheObserver
Public Member Functions
InMemoryURLIndex (bookmarks::BookmarkModel *bookmark_model, history::HistoryService *history_service, TemplateURLService *template_url_service, const base::FilePath &history_dir, const SchemeSet &client_schemes_to_allowlist)
~InMemoryURLIndex () override
InMemoryURLIndex (const InMemoryURLIndex &)=delete
InMemoryURLIndex & operator= (const InMemoryURLIndex &)=delete
void Init ()
ScoredHistoryMatches HistoryItemsForTerms (const std::u16string &term_string, size_t cursor_position, size_t max_matches)
void DeleteURL (const GURL &url)
void set_restore_cache_observer (RestoreCacheObserver *restore_cache_observer)
void set_save_cache_observer (SaveCacheObserver *save_cache_observer)
bool restored () const
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, ExpireRow)
FRIEND_TEST_ALL_PREFIXES (LimitedInMemoryURLIndexTest, Initialization)
void ClearPrivateData ()
bool GetCacheFilePath (base::FilePath *file_path)
void PostRestoreFromCacheFileTask ()
void ScheduleRebuildFromHistory ()
void DoneRebuildingPrivateDataFromHistoryDB (bool succeeded, scoped_refptr< URLIndexPrivateData > private_data)
void RebuildFromHistory (history::HistoryDatabase *history_db)
void OnCacheLoadDone (scoped_refptr< URLIndexPrivateData > private_data_ptr)
void OnCacheRestored (URLIndexPrivateData *private_data)
void PostSaveToCacheFileTask ()
void DoSaveToCacheFile (const base::FilePath &path)
void OnCacheSaveDone (bool succeeded)
void Shutdown () override
void OnURLVisited (history::HistoryService *history_service, ui::PageTransition transition, const history::URLRow &row, const history::RedirectList &redirects, base::Time visit_time) override
void OnURLsModified (history::HistoryService *history_service, const history::URLRows &changed_urls) override
void OnURLsDeleted (history::HistoryService *history_service, const history::DeletionInfo &deletion_info) override
void OnHistoryServiceLoaded (history::HistoryService *history_service) override
bool OnMemoryDump (const base::trace_event::MemoryDumpArgs &args, base::trace_event::ProcessMemoryDump *process_memory_dump) override
void set_history_dir (const base::FilePath &dir_path)
URLIndexPrivateData * private_data ()
base::CancelableTaskTracker * private_data_tracker ()
const SchemeSet & scheme_allowlist ()
Private Attributes
bookmarks::BookmarkModel * bookmark_model_
history::HistoryService * history_service_
TemplateURLService * template_url_service_
base::FilePath history_dir_
SchemeSet scheme_allowlist_
scoped_refptr< URLIndexPrivateData > private_data_
RestoreCacheObserver * restore_cache_observer_
SaveCacheObserver * save_cache_observer_
const scoped_refptr< base::SequencedTaskRunner > task_runner_
base::CancelableTaskTracker private_data_tracker_
base::CancelableTaskTracker cache_reader_tracker_
bool shutdown_
bool restored_
bool needs_to_be_cached_
bool listen_to_history_service_loaded_
base::ScopedObservation< history::HistoryService, history::HistoryServiceObserver > history_service_observation_ {this}
base::ThreadChecker thread_checker_
Friends
class ::FakeAutocompleteProviderClient
class ::HistoryQuickProviderTest
class history::HQPPerfTestOnePopularURL
class InMemoryURLIndexTest
class InMemoryURLIndexCacheTest
Constructor & Destructor Documentation
InMemoryURLIndex() [1/2]
InMemoryURLIndex::InMemoryURLIndex (bookmarks::BookmarkModel * bookmark_model, history::HistoryService * history_service, TemplateURLService * template_url_service, const base::FilePath & history_dir, const SchemeSet & client_schemes_to_allowlist)
Referenced by FakeAutocompleteProviderClient::FakeAutocompleteProviderClient().
~InMemoryURLIndex()
InMemoryURLIndex::~InMemoryURLIndex () override
References history_dir_, history_service_, needs_to_be_cached_, and shutdown_.
InMemoryURLIndex() [2/2]
InMemoryURLIndex::InMemoryURLIndex (const InMemoryURLIndex &) delete
Member Function Documentation
ClearPrivateData()
void InMemoryURLIndex::ClearPrivateData () private
References private_data_.
Referenced by OnURLsDeleted().
DeleteURL()
void InMemoryURLIndex::DeleteURL (const GURL & url)
References private_data_.
DoneRebuildingPrivateDataFromHistoryDB()
void InMemoryURLIndex::DoneRebuildingPrivateDataFromHistoryDB (bool succeeded, scoped_refptr< URLIndexPrivateData > private_data) private
References InMemoryURLIndex::RestoreCacheObserver::OnCacheRestoreFinished(), PostSaveToCacheFileTask(), private_data(), private_data_, private_data_tracker_, restore_cache_observer_, restored_, and thread_checker_.
DoSaveToCacheFile()
void InMemoryURLIndex::DoSaveToCacheFile (const base::FilePath & path) private
FRIEND_TEST_ALL_PREFIXES() [1/2]
InMemoryURLIndex::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , ExpireRow) private
FRIEND_TEST_ALL_PREFIXES() [2/2]
InMemoryURLIndex::FRIEND_TEST_ALL_PREFIXES (LimitedInMemoryURLIndexTest , Initialization) private
GetCacheFilePath()
bool InMemoryURLIndex::GetCacheFilePath (base::FilePath * file_path) private
References history_dir_.
Referenced by OnCacheLoadDone(), OnURLsDeleted(), PostRestoreFromCacheFileTask(), PostSaveToCacheFileTask(), and Shutdown().
HistoryItemsForTerms()
ScoredHistoryMatches InMemoryURLIndex::HistoryItemsForTerms (const std::u16string & term_string, size_t cursor_position, size_t max_matches)
References bookmark_model_, private_data_, and template_url_service_.
Referenced by HistoryQuickProvider::DoAutocomplete().
Init()
void InMemoryURLIndex::Init ()
References PostRestoreFromCacheFileTask().
OnCacheLoadDone()
void InMemoryURLIndex::OnCacheLoadDone (scoped_refptr< URLIndexPrivateData > private_data_ptr) private
References URLIndexPrivateData::Empty(), GetCacheFilePath(), history_service_, listen_to_history_service_loaded_, InMemoryURLIndex::RestoreCacheObserver::OnCacheRestoreFinished(), private_data(), private_data_, private_data_tracker_, restore_cache_observer_, restored_, ScheduleRebuildFromHistory(), shutdown_, and task_runner_.
Referenced by PostRestoreFromCacheFileTask().
OnCacheRestored()
void InMemoryURLIndex::OnCacheRestored (URLIndexPrivateData * private_data) private
OnCacheSaveDone()
void InMemoryURLIndex::OnCacheSaveDone (bool succeeded) private
References InMemoryURLIndex::SaveCacheObserver::OnCacheSaveFinished(), and save_cache_observer_.
Referenced by PostSaveToCacheFileTask().
OnHistoryServiceLoaded()
void InMemoryURLIndex::OnHistoryServiceLoaded (history::HistoryService * history_service) override private
References listen_to_history_service_loaded_, and ScheduleRebuildFromHistory().
OnMemoryDump()
bool InMemoryURLIndex::OnMemoryDump (const base::trace_event::MemoryDumpArgs & args, base::trace_event::ProcessMemoryDump * process_memory_dump) override private
References base::trace_event::EstimateMemoryUsage(), private_data_, and scheme_allowlist_.
OnURLsDeleted()
void InMemoryURLIndex::OnURLsDeleted (history::HistoryService * history_service, const history::DeletionInfo & deletion_info) override private
References ClearPrivateData(), GetCacheFilePath(), needs_to_be_cached_, private_data_, and task_runner_.
OnURLsModified()
void InMemoryURLIndex::OnURLsModified (history::HistoryService * history_service, const history::URLRows & changed_urls) override private
References history_service_, needs_to_be_cached_, private_data_, private_data_tracker_, and scheme_allowlist_.
OnURLVisited()
void InMemoryURLIndex::OnURLVisited (history::HistoryService * history_service, ui::PageTransition transition, const history::URLRow & row, const history::RedirectList & redirects, base::Time visit_time) override private
References history_service_, needs_to_be_cached_, private_data_, private_data_tracker_, and scheme_allowlist_.
operator=()
InMemoryURLIndex& InMemoryURLIndex::operator= (const InMemoryURLIndex &) delete
PostRestoreFromCacheFileTask()
void InMemoryURLIndex::PostRestoreFromCacheFileTask () private
References GetCacheFilePath(), omnibox::kHistoryQuickProviderAblateInMemoryURLIndexCacheFile, OnCacheLoadDone(), InMemoryURLIndex::RestoreCacheObserver::OnCacheRestoreFinished(), restore_cache_observer_, restored_, URLIndexPrivateData::RestoreFromFile(), shutdown_, task_runner_, and thread_checker_.
Referenced by Init().
PostSaveToCacheFileTask()
void InMemoryURLIndex::PostSaveToCacheFileTask () private
References GetCacheFilePath(), omnibox::kHistoryQuickProviderAblateInMemoryURLIndexCacheFile, OnCacheSaveDone(), private_data_, task_runner_, and URLIndexPrivateData::WritePrivateDataToCacheFileTask().
Referenced by DoneRebuildingPrivateDataFromHistoryDB().
private_data()
URLIndexPrivateData* InMemoryURLIndex::private_data () inline private
References private_data_.
Referenced by DoneRebuildingPrivateDataFromHistoryDB(), and OnCacheLoadDone().
private_data_tracker()
base::CancelableTaskTracker* InMemoryURLIndex::private_data_tracker () inline private
References private_data_tracker_.
RebuildFromHistory()
void InMemoryURLIndex::RebuildFromHistory (history::HistoryDatabase * history_db) private
References private_data_, private_data_tracker_, URLIndexPrivateData::RebuildFromHistory(), and scheme_allowlist_.
restored()
bool InMemoryURLIndex::restored () const inline
References restored_.
ScheduleRebuildFromHistory()
void InMemoryURLIndex::ScheduleRebuildFromHistory () private
References cache_reader_tracker_, history_service_, and scheme_allowlist_.
Referenced by OnCacheLoadDone(), and OnHistoryServiceLoaded().
scheme_allowlist()
const SchemeSet& InMemoryURLIndex::scheme_allowlist () inline private
References scheme_allowlist_.
set_history_dir()
void InMemoryURLIndex::set_history_dir (const base::FilePath & dir_path) inline private
References history_dir_.
set_restore_cache_observer()
void InMemoryURLIndex::set_restore_cache_observer (RestoreCacheObserver * restore_cache_observer) inline
References restore_cache_observer_.
set_save_cache_observer()
void InMemoryURLIndex::set_save_cache_observer (SaveCacheObserver * save_cache_observer) inline
References save_cache_observer_.
Shutdown()
void InMemoryURLIndex::Shutdown () override private
References cache_reader_tracker_, GetCacheFilePath(), history_service_, history_service_observation_, omnibox::kHistoryQuickProviderAblateInMemoryURLIndexCacheFile, needs_to_be_cached_, private_data_, private_data_tracker_, shutdown_, task_runner_, and URLIndexPrivateData::WritePrivateDataToCacheFileTask().
Referenced by FakeAutocompleteProviderClient::~FakeAutocompleteProviderClient().
Friends And Related Function Documentation
::FakeAutocompleteProviderClient
friend class ::FakeAutocompleteProviderClient friend
::HistoryQuickProviderTest
friend class ::HistoryQuickProviderTest friend
history::HQPPerfTestOnePopularURL
friend class history::HQPPerfTestOnePopularURL friend
InMemoryURLIndexCacheTest
friend class InMemoryURLIndexCacheTest friend
InMemoryURLIndexTest
friend class InMemoryURLIndexTest friend
Member Data Documentation
bookmark_model_
bookmarks::BookmarkModel* InMemoryURLIndex::bookmark_model_ private
Referenced by HistoryItemsForTerms().
cache_reader_tracker_
base::CancelableTaskTracker InMemoryURLIndex::cache_reader_tracker_ private
Referenced by ScheduleRebuildFromHistory(), and Shutdown().
history_dir_
base::FilePath InMemoryURLIndex::history_dir_ private
Referenced by GetCacheFilePath(), set_history_dir(), and ~InMemoryURLIndex().
history_service_
history::HistoryService* InMemoryURLIndex::history_service_ private
Referenced by OnCacheLoadDone(), OnURLsModified(), OnURLVisited(), ScheduleRebuildFromHistory(), Shutdown(), and ~InMemoryURLIndex().
history_service_observation_
base::ScopedObservation<history::HistoryService, history::HistoryServiceObserver> InMemoryURLIndex::history_service_observation_ {this} private
Referenced by Shutdown().
listen_to_history_service_loaded_
bool InMemoryURLIndex::listen_to_history_service_loaded_ private
Referenced by OnCacheLoadDone(), and OnHistoryServiceLoaded().
needs_to_be_cached_
bool InMemoryURLIndex::needs_to_be_cached_ private
Referenced by OnURLsDeleted(), OnURLsModified(), OnURLVisited(), Shutdown(), and ~InMemoryURLIndex().
private_data_
scoped_refptr<URLIndexPrivateData> InMemoryURLIndex::private_data_ private
Referenced by ClearPrivateData(), DeleteURL(), DoneRebuildingPrivateDataFromHistoryDB(), HistoryItemsForTerms(), OnCacheLoadDone(), OnMemoryDump(), OnURLsDeleted(), OnURLsModified(), OnURLVisited(), PostSaveToCacheFileTask(), private_data(), RebuildFromHistory(), and Shutdown().
private_data_tracker_
base::CancelableTaskTracker InMemoryURLIndex::private_data_tracker_ private
Referenced by DoneRebuildingPrivateDataFromHistoryDB(), OnCacheLoadDone(), OnURLsModified(), OnURLVisited(), private_data_tracker(), RebuildFromHistory(), and Shutdown().
restore_cache_observer_
RestoreCacheObserver* InMemoryURLIndex::restore_cache_observer_ private
Referenced by DoneRebuildingPrivateDataFromHistoryDB(), OnCacheLoadDone(), PostRestoreFromCacheFileTask(), and set_restore_cache_observer().
restored_
bool InMemoryURLIndex::restored_ private
Referenced by DoneRebuildingPrivateDataFromHistoryDB(), OnCacheLoadDone(), PostRestoreFromCacheFileTask(), and restored().
save_cache_observer_
SaveCacheObserver* InMemoryURLIndex::save_cache_observer_ private
Referenced by OnCacheSaveDone(), and set_save_cache_observer().
scheme_allowlist_
SchemeSet InMemoryURLIndex::scheme_allowlist_ private
Referenced by OnMemoryDump(), OnURLsModified(), OnURLVisited(), RebuildFromHistory(), InMemoryURLIndex::RebuildPrivateDataFromHistoryDBTask::RunOnDBThread(), ScheduleRebuildFromHistory(), and scheme_allowlist().
shutdown_
bool InMemoryURLIndex::shutdown_ private
Referenced by OnCacheLoadDone(), PostRestoreFromCacheFileTask(), Shutdown(), and ~InMemoryURLIndex().
task_runner_
const scoped_refptr<base::SequencedTaskRunner> InMemoryURLIndex::task_runner_ private
Referenced by OnCacheLoadDone(), OnURLsDeleted(), PostRestoreFromCacheFileTask(), PostSaveToCacheFileTask(), and Shutdown().
template_url_service_
TemplateURLService* InMemoryURLIndex::template_url_service_ private
Referenced by HistoryItemsForTerms().
thread_checker_
base::ThreadChecker InMemoryURLIndex::thread_checker_ private
Referenced by DoneRebuildingPrivateDataFromHistoryDB(), and PostRestoreFromCacheFileTask().
The documentation for this class was generated from the following files:
components/omnibox/browser/in_memory_url_index.h
components/omnibox/browser/in_memory_url_index.cc