Chromium Omnibox: OmniboxAction::Client Struct Reference
OmniboxAction::Client Struct Reference abstract
#include <omnibox_action.h>
Public Member Functions
virtual void NewIncognitoWindow ()=0
virtual void OpenIncognitoClearBrowsingDataDialog ()=0
virtual void CloseIncognitoWindows ()=0
virtual void PromptPageTranslation ()=0
Member Function Documentation
CloseIncognitoWindows()
virtual void OmniboxAction::Client::CloseIncognitoWindows () pure virtual
Implemented in OmniboxClient, and ChromeOmniboxClient.
Referenced by OmniboxPedalCloseIncognitoWindows::Execute().
NewIncognitoWindow()
virtual void OmniboxAction::Client::NewIncognitoWindow () pure virtual
Implemented in OmniboxClient, and ChromeOmniboxClient.
Referenced by OmniboxPedalLaunchIncognito::Execute().
OpenIncognitoClearBrowsingDataDialog()
virtual void OmniboxAction::Client::OpenIncognitoClearBrowsingDataDialog () pure virtual
Implemented in OmniboxClient, and ChromeOmniboxClient.
Referenced by OmniboxPedalClearBrowsingData::Execute().
PromptPageTranslation()
virtual void OmniboxAction::Client::PromptPageTranslation () pure virtual
Implemented in OmniboxClient, and ChromeOmniboxClient.
Referenced by OmniboxPedalTranslate::Execute().
The documentation for this struct was generated from the following file:
components/omnibox/browser/actions/omnibox_action.h