Chromium Omnibox: OmniboxMetricsProvider Class Reference
OmniboxMetricsProvider Class Reference
#include <omnibox_metrics_provider.h>
Public Member Functions
OmniboxMetricsProvider ()
~OmniboxMetricsProvider () override
OmniboxMetricsProvider (const OmniboxMetricsProvider &)=delete
OmniboxMetricsProvider & operator= (const OmniboxMetricsProvider &)=delete
void OnRecordingEnabled () override
void OnRecordingDisabled () override
void ProvideCurrentSessionData (metrics::ChromeUserMetricsExtension *uma_proto) override
Private Member Functions
void OnURLOpenedFromOmnibox (OmniboxLog *log)
void RecordOmniboxOpenedURL (const OmniboxLog &log)
Private Attributes
base::CallbackListSubscription subscription_
metrics::ChromeUserMetricsExtension omnibox_events_cache
Constructor & Destructor Documentation
OmniboxMetricsProvider() [1/2]
OmniboxMetricsProvider::OmniboxMetricsProvider ()
~OmniboxMetricsProvider()
OmniboxMetricsProvider::~OmniboxMetricsProvider () override
OmniboxMetricsProvider() [2/2]
OmniboxMetricsProvider::OmniboxMetricsProvider (const OmniboxMetricsProvider &) delete
Member Function Documentation
OnRecordingDisabled()
void OmniboxMetricsProvider::OnRecordingDisabled () override
References subscription_.
OnRecordingEnabled()
void OmniboxMetricsProvider::OnRecordingEnabled () override
References OmniboxEventGlobalTracker::GetInstance(), OnURLOpenedFromOmnibox(), OmniboxEventGlobalTracker::RegisterCallback(), and subscription_.
OnURLOpenedFromOmnibox()
void OmniboxMetricsProvider::OnURLOpenedFromOmnibox (OmniboxLog * log) private
References RecordOmniboxOpenedURL().
Referenced by OnRecordingEnabled().
operator=()
OmniboxMetricsProvider& OmniboxMetricsProvider::operator= (const OmniboxMetricsProvider &) delete
ProvideCurrentSessionData()
void OmniboxMetricsProvider::ProvideCurrentSessionData (metrics::ChromeUserMetricsExtension * uma_proto) override
References omnibox_events_cache.
RecordOmniboxOpenedURL()
void OmniboxMetricsProvider::RecordOmniboxOpenedURL (const OmniboxLog & log) private
References AutocompleteResult::begin(), OmniboxLog::completed_length, OmniboxLog::current_page_classification, OmniboxLog::disposition, OmniboxLog::elapsed_time_since_last_change_to_default_match, OmniboxLog::elapsed_time_since_user_first_modified_omnibox, AutocompleteResult::end(), OmniboxLog::feature_triggered_in_session, OmniboxLog::in_keyword_mode, OmniboxLog::input_type, OmniboxLog::is_paste_and_go, OmniboxLog::is_popup_open, OmniboxLog::is_query_started_from_tile, OmniboxLog::just_deleted_text, OmniboxLog::keyword_mode_entry_method, omnibox_events_cache, OmniboxLog::providers_info, OmniboxLog::result, OmniboxLog::selected_index, OmniboxLog::tab_id, and OmniboxLog::text.
Referenced by OnURLOpenedFromOmnibox().
Member Data Documentation
omnibox_events_cache
metrics::ChromeUserMetricsExtension OmniboxMetricsProvider::omnibox_events_cache private
Referenced by ProvideCurrentSessionData(), and RecordOmniboxOpenedURL().
subscription_
base::CallbackListSubscription OmniboxMetricsProvider::subscription_ private
Referenced by OnRecordingDisabled(), and OnRecordingEnabled().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_metrics_provider.h
components/omnibox/browser/omnibox_metrics_provider.cc