Chromium Omnibox: WebUIOmniboxPopupView Class Reference
WebUIOmniboxPopupView Class Reference
#include <webui_omnibox_popup_view.h>
Public Member Functions
METADATA_HEADER (WebUIOmniboxPopupView)
WebUIOmniboxPopupView (content::BrowserContext *browser_context)
WebUIOmniboxPopupView (const WebUIOmniboxPopupView &)=delete
WebUIOmniboxPopupView & operator= (const WebUIOmniboxPopupView &)=delete
~WebUIOmniboxPopupView () override=default
OmniboxPopupHandler * GetWebUIHandler ()
Constructor & Destructor Documentation
WebUIOmniboxPopupView() [1/2]
WebUIOmniboxPopupView::WebUIOmniboxPopupView (content::BrowserContext * browser_context) explicit
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
WebUIOmniboxPopupView() [2/2]
WebUIOmniboxPopupView::WebUIOmniboxPopupView (const WebUIOmniboxPopupView &) delete
~WebUIOmniboxPopupView()
WebUIOmniboxPopupView::~WebUIOmniboxPopupView () override default
Member Function Documentation
GetWebUIHandler()
OmniboxPopupHandler * WebUIOmniboxPopupView::GetWebUIHandler ()
Referenced by OmniboxPopupContentsView::InvalidateLine(), and OmniboxPopupContentsView::OnSelectionChanged().
METADATA_HEADER()
WebUIOmniboxPopupView::METADATA_HEADER (WebUIOmniboxPopupView)
operator=()
WebUIOmniboxPopupView& WebUIOmniboxPopupView::operator= (const WebUIOmniboxPopupView &) delete
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/webui_omnibox_popup_view.h
chrome/browser/ui/views/omnibox/webui_omnibox_popup_view.cc