Chromium Omnibox: AutocompleteProviderClient Class Reference
AutocompleteProviderClient Class Reference abstract
#include <autocomplete_provider_client.h>
Public Member Functions
virtual ~AutocompleteProviderClient ()
virtual scoped_refptr< network::SharedURLLoaderFactory > GetURLLoaderFactory ()=0
virtual PrefService * GetPrefs () const =0
virtual PrefService * GetLocalState ()=0
virtual const AutocompleteSchemeClassifier & GetSchemeClassifier () const =0
virtual AutocompleteClassifier * GetAutocompleteClassifier ()=0
virtual history::HistoryService * GetHistoryService ()=0
virtual history_clusters::HistoryClustersService * GetHistoryClustersService ()
virtual scoped_refptr< history::TopSites > GetTopSites ()=0
virtual ntp_tiles::MostVisitedSites * GetNtpMostVisitedSites ()
virtual bookmarks::BookmarkModel * GetBookmarkModel ()=0
virtual history::URLDatabase * GetInMemoryDatabase ()=0
virtual InMemoryURLIndex * GetInMemoryURLIndex ()=0
virtual TemplateURLService * GetTemplateURLService ()=0
virtual const TemplateURLService * GetTemplateURLService () const =0
virtual RemoteSuggestionsService * GetRemoteSuggestionsService (bool create_if_necessary) const =0
virtual DocumentSuggestionsService * GetDocumentSuggestionsService (bool create_if_necessary) const =0
virtual OmniboxPedalProvider * GetPedalProvider () const =0
virtual scoped_refptr< ShortcutsBackend > GetShortcutsBackend ()=0
virtual scoped_refptr< ShortcutsBackend > GetShortcutsBackendIfExists ()=0
virtual std::unique_ptr< KeywordExtensionsDelegate > GetKeywordExtensionsDelegate (KeywordProvider *keyword_provider)=0
virtual query_tiles::TileService * GetQueryTileService () const =0
virtual OmniboxTriggeredFeatureService * GetOmniboxTriggeredFeatureService () const =0
virtual std::string GetAcceptLanguages () const =0
virtual std::string GetEmbedderRepresentationOfAboutScheme () const =0
virtual std::vector< std::u16string > GetBuiltinURLs ()=0
virtual std::vector< std::u16string > GetBuiltinsToProvideAsUserTypes ()=0
virtual component_updater::ComponentUpdateService * GetComponentUpdateService ()=0
virtual signin::IdentityManager * GetIdentityManager () const =0
virtual bool IsOffTheRecord () const =0
virtual bool SearchSuggestEnabled () const =0
virtual bool AllowDeletingBrowserHistory () const
virtual bool IsPersonalizedUrlDataCollectionActive () const =0
virtual bool IsAuthenticated () const =0
virtual bool IsSyncActive () const =0
virtual std::string ProfileUserName () const
virtual void Classify (const std::u16string &text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch *match, GURL *alternate_nav_url)=0
virtual void DeleteMatchingURLsForKeywordFromHistory (history::KeywordID keyword_id, const std::u16string &term)=0
virtual void PrefetchImage (const GURL &url)=0
virtual void StartServiceWorker (const GURL &destination_url)
virtual void OnAutocompleteControllerResultReady (AutocompleteController *controller)
virtual void ConfigureKeywordProvider (KeywordProvider *keyword_provider)
virtual bool IsTabOpenWithURL (const GURL &url, const AutocompleteInput *input)=0
virtual bool IsIncognitoModeAvailable () const
virtual bool IsSharingHubAvailable () const
Public Member Functions inherited from OmniboxAction::Client
virtual void OpenSharingHub ()=0
virtual void NewIncognitoWindow ()=0
virtual void OpenIncognitoClearBrowsingDataDialog ()=0
virtual void CloseIncognitoWindows ()=0
virtual void PromptPageTranslation ()=0
Constructor & Destructor Documentation
~AutocompleteProviderClient()
virtual AutocompleteProviderClient::~AutocompleteProviderClient () inline virtual
Member Function Documentation
AllowDeletingBrowserHistory()
bool AutocompleteProviderClient::AllowDeletingBrowserHistory () const virtual
Referenced by HistoryURLProvider::HistoryMatchToACMatch(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), and HistoryQuickProvider::QuickMatchToACMatch().
Classify()
virtual void AutocompleteProviderClient::Classify (const std::u16string & text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch * match, GURL * alternate_nav_url) pure virtual
Referenced by SearchProvider::ScoreHistoryResultsHelper(), and VerbatimMatchForURL().
ConfigureKeywordProvider()
virtual void AutocompleteProviderClient::ConfigureKeywordProvider (KeywordProvider * keyword_provider) inline virtual
DeleteMatchingURLsForKeywordFromHistory()
virtual void AutocompleteProviderClient::DeleteMatchingURLsForKeywordFromHistory (history::KeywordID keyword_id, const std::u16string & term) pure virtual
Referenced by BaseSearchProvider::DeleteMatch().
GetAcceptLanguages()
virtual std::string AutocompleteProviderClient::GetAcceptLanguages () const pure virtual
GetAutocompleteClassifier()
virtual AutocompleteClassifier* AutocompleteProviderClient::GetAutocompleteClassifier () pure virtual
GetBookmarkModel()
virtual bookmarks::BookmarkModel* AutocompleteProviderClient::GetBookmarkModel () pure virtual
Referenced by HistoryProvider::DeleteMatchFromMatches().
GetBuiltinsToProvideAsUserTypes()
virtual std::vector<std::u16string> AutocompleteProviderClient::GetBuiltinsToProvideAsUserTypes () pure virtual
Referenced by BuiltinProvider::Start().
GetBuiltinURLs()
virtual std::vector<std::u16string> AutocompleteProviderClient::GetBuiltinURLs () pure virtual
Referenced by BuiltinProvider::BuiltinProvider().
GetComponentUpdateService()
virtual component_updater::ComponentUpdateService* AutocompleteProviderClient::GetComponentUpdateService () pure virtual
GetDocumentSuggestionsService()
virtual DocumentSuggestionsService* AutocompleteProviderClient::GetDocumentSuggestionsService (bool create_if_necessary) const pure virtual
Referenced by DocumentProvider::Run(), and DocumentProvider::Stop().
GetEmbedderRepresentationOfAboutScheme()
virtual std::string AutocompleteProviderClient::GetEmbedderRepresentationOfAboutScheme () const pure virtual
Referenced by MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), QueryTileProvider::AllowQueryTileSuggestions(), OmniboxPedalTranslate::IsReadyToTrigger(), BuiltinProvider::Start(), and ZeroSuggestVerbatimMatchProvider::Start().
GetHistoryClustersService()
history_clusters::HistoryClustersService * AutocompleteProviderClient::GetHistoryClustersService () virtual
GetHistoryService()
virtual history::HistoryService* AutocompleteProviderClient::GetHistoryService () pure virtual
Referenced by HistoryProvider::DeleteMatch(), LocalHistoryZeroSuggestProvider::DeleteMatch(), ShortcutsProvider::DeleteMatch(), HistoryQuickProvider::FindMaxMatchScore(), LocalHistoryZeroSuggestProvider::OnHistoryQueryResults(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), and HistoryURLProvider::Start().
GetIdentityManager()
virtual signin::IdentityManager* AutocompleteProviderClient::GetIdentityManager () const pure virtual
GetInMemoryDatabase()
virtual history::URLDatabase* AutocompleteProviderClient::GetInMemoryDatabase () pure virtual
Referenced by SearchProvider::DoHistoryQuery().
GetInMemoryURLIndex()
virtual InMemoryURLIndex* AutocompleteProviderClient::GetInMemoryURLIndex () pure virtual
GetKeywordExtensionsDelegate()
virtual std::unique_ptr<KeywordExtensionsDelegate> AutocompleteProviderClient::GetKeywordExtensionsDelegate (KeywordProvider * keyword_provider) pure virtual
GetLocalState()
virtual PrefService* AutocompleteProviderClient::GetLocalState () pure virtual
Referenced by AutocompleteResult::ComputeAlternateNavUrl().
GetNtpMostVisitedSites()
ntp_tiles::MostVisitedSites * AutocompleteProviderClient::GetNtpMostVisitedSites () virtual
Referenced by MostVisitedSitesProvider::StartFetchNTPTiles().
GetOmniboxTriggeredFeatureService()
virtual OmniboxTriggeredFeatureService* AutocompleteProviderClient::GetOmniboxTriggeredFeatureService () const pure virtual
Referenced by BookmarkProvider::GetMatchesWithBookmarkPaths(), and BookmarkProvider::GetMatchingAlgorithm().
GetPedalProvider()
virtual OmniboxPedalProvider* AutocompleteProviderClient::GetPedalProvider () const pure virtual
Referenced by AutocompleteResult::AttachPedalsToMatches().
GetPrefs()
virtual PrefService* AutocompleteProviderClient::GetPrefs () const pure virtual
Referenced by ZeroSuggestProvider::DeleteMatch(), OmniboxEditModel::GetPrefService(), DocumentProvider::IsDocumentProviderAllowed(), OmniboxPedalPlayChromeDinoGame::IsReadyToTrigger(), ZeroSuggestProvider::MaybeUseCachedSuggestions(), and ZeroSuggestProvider::UpdateResults().
GetQueryTileService()
virtual query_tiles::TileService* AutocompleteProviderClient::GetQueryTileService () const pure virtual
GetRemoteSuggestionsService()
virtual RemoteSuggestionsService* AutocompleteProviderClient::GetRemoteSuggestionsService (bool create_if_necessary) const pure virtual
Referenced by ZeroSuggestProvider::Start().
GetSchemeClassifier()
virtual const AutocompleteSchemeClassifier& AutocompleteProviderClient::GetSchemeClassifier () const pure virtual
Referenced by BookmarkProvider::DoAutocomplete(), BaseSearchProvider::ParseSuggestResults(), ClipboardProvider::UpdateClipboardURLContent(), and VerbatimMatchForInput().
GetShortcutsBackend()
virtual scoped_refptr<ShortcutsBackend> AutocompleteProviderClient::GetShortcutsBackend () pure virtual
Referenced by ShortcutsProvider::ShortcutsProvider().
GetShortcutsBackendIfExists()
virtual scoped_refptr<ShortcutsBackend> AutocompleteProviderClient::GetShortcutsBackendIfExists () pure virtual
Referenced by ShortcutsProvider::DeleteMatch(), ShortcutsProvider::GetMatches(), and ShortcutsProvider::~ShortcutsProvider().
GetTemplateURLService() [1/2]
virtual const TemplateURLService* AutocompleteProviderClient::GetTemplateURLService () const pure virtual
GetTemplateURLService() [2/2]
virtual TemplateURLService* AutocompleteProviderClient::GetTemplateURLService () pure virtual
Referenced by BaseSearchProvider::AddMatchToMap(), QueryTileProvider::AllowQueryTileSuggestions(), ClipboardProvider::ConstructImageMatchCallback(), ZeroSuggestProvider::ConvertResultsToAutocompleteMatches(), SearchProvider::CreateSuggestLoader(), BaseSearchProvider::DeleteMatch(), LocalHistoryZeroSuggestProvider::DeleteMatch(), ShortcutsProvider::GetMatches(), VoiceSuggestProvider::GetTemplateURL(), ZeroSuggestProvider::GetTemplateURL(), DocumentProvider::IsDocumentProviderAllowed(), LocalHistoryZeroSuggestProvider::OnHistoryQueryResults(), SearchProvider::OnTemplateURLServiceChanged(), DocumentProvider::ParseDocumentSearchResults(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), OnDeviceHeadProvider::SearchDone(), SearchProvider::SearchProvider(), BaseSearchProvider::SetDeletionURL(), ShortcutsProvider::ShortcutToACMatch(), HistoryURLProvider::Start(), LocalHistoryZeroSuggestProvider::Start(), SearchProvider::Start(), ClipboardProvider::TemplateURLSupportsImageSearch(), ClipboardProvider::TemplateURLSupportsTextSearch(), ZeroSuggestProvider::TypeOfResultToRun(), ClipboardProvider::UpdateClipboardTextContent(), VerbatimMatchForInput(), and ZeroSuggestProvider::ZeroSuggestProvider().
GetTopSites()
virtual scoped_refptr<history::TopSites> AutocompleteProviderClient::GetTopSites () pure virtual
Referenced by MostVisitedSitesProvider::StartFetchTopSites().
GetURLLoaderFactory()
virtual scoped_refptr<network::SharedURLLoaderFactory> AutocompleteProviderClient::GetURLLoaderFactory () pure virtual
Referenced by SuggestionDeletionHandler::SuggestionDeletionHandler().
IsAuthenticated()
virtual bool AutocompleteProviderClient::IsAuthenticated () const pure virtual
Referenced by DocumentProvider::IsDocumentProviderAllowed(), OmniboxPedalAuthRequired::IsReadyToTrigger(), and LocalHistoryZeroSuggestProvider::QueryURLDatabase().
IsIncognitoModeAvailable()
bool AutocompleteProviderClient::IsIncognitoModeAvailable () const virtual
Referenced by OmniboxPedalLaunchIncognito::IsReadyToTrigger().
IsOffTheRecord()
virtual bool AutocompleteProviderClient::IsOffTheRecord () const pure virtual
Referenced by MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), QueryTileProvider::AllowQueryTileSuggestions(), BaseSearchProvider::CanSendURL(), DocumentProvider::IsDocumentProviderAllowed(), SearchProvider::IsQuerySuitableForSuggest(), DocumentProvider::Run(), LocalHistoryZeroSuggestProvider::Start(), and SuggestionDeletionHandler::SuggestionDeletionHandler().
IsPersonalizedUrlDataCollectionActive()
virtual bool AutocompleteProviderClient::IsPersonalizedUrlDataCollectionActive () const pure virtual
Referenced by BaseSearchProvider::CanSendURL().
IsSharingHubAvailable()
bool AutocompleteProviderClient::IsSharingHubAvailable () const virtual
Referenced by OmniboxPedalShareThisPage::IsReadyToTrigger().
IsSyncActive()
virtual bool AutocompleteProviderClient::IsSyncActive () const pure virtual
Referenced by DocumentProvider::IsDocumentProviderAllowed().
IsTabOpenWithURL()
virtual bool AutocompleteProviderClient::IsTabOpenWithURL (const GURL & url, const AutocompleteInput * input) pure virtual
Referenced by AutocompleteResult::ConvertOpenTabMatches().
OnAutocompleteControllerResultReady()
virtual void AutocompleteProviderClient::OnAutocompleteControllerResultReady (AutocompleteController * controller) inline virtual
PrefetchImage()
virtual void AutocompleteProviderClient::PrefetchImage (const GURL & url) pure virtual
Referenced by SearchProvider::PrefetchImages().
ProfileUserName()
std::string AutocompleteProviderClient::ProfileUserName () const virtual
Referenced by DocumentProvider::ParseDocumentSearchResults().
SearchSuggestEnabled()
virtual bool AutocompleteProviderClient::SearchSuggestEnabled () const pure virtual
Referenced by QueryTileProvider::AllowQueryTileSuggestions(), BaseSearchProvider::CanSendURL(), DocumentProvider::IsDocumentProviderAllowed(), and SearchProvider::IsQuerySuitableForSuggest().
StartServiceWorker()
virtual void AutocompleteProviderClient::StartServiceWorker (const GURL & destination_url) inline virtual
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_provider_client.h
components/omnibox/browser/autocomplete_provider_client.cc