Chromium Omnibox: components/omnibox/browser/actions/omnibox_pedal_implementations.cc File Reference
omnibox_pedal_implementations.cc File Reference
#include "components/omnibox/browser/actions/omnibox_pedal_implementations.h"
#include "base/metrics/histogram_functions.h"
#include "base/strings/utf_string_conversions.h"
#include "build/build_config.h"
#include "components/omnibox/browser/actions/omnibox_pedal.h"
#include "components/omnibox/browser/autocomplete_input.h"
#include "components/omnibox/browser/autocomplete_provider_client.h"
#include "components/omnibox/browser/buildflags.h"
#include "components/omnibox/browser/omnibox_client.h"
#include "components/omnibox/browser/omnibox_field_trial.h"
#include "components/omnibox/common/omnibox_features.h"
#include "components/omnibox/resources/grit/omnibox_pedal_synonyms.h"
#include "components/prefs/pref_service.h"
#include "components/strings/grit/components_strings.h"
#include "components/omnibox/browser/vector_icons.h"
#include "components/vector_icons/vector_icons.h"
Classes
class OmniboxPedalClearBrowsingData
class OmniboxPedalManagePasswords
class OmniboxPedalUpdateCreditCard
class OmniboxPedalLaunchIncognito
class OmniboxPedalTranslate
class OmniboxPedalUpdateChrome
class OmniboxPedalRunChromeSafetyCheck
class OmniboxPedalManageSecuritySettings
class OmniboxPedalManageCookies
class OmniboxPedalManageAddresses
class OmniboxPedalManageSync
class OmniboxPedalManageSiteSettings
class OmniboxPedalAuthRequired
class OmniboxPedalCreateGoogleDoc
class OmniboxPedalCreateGoogleSheet
class OmniboxPedalCreateGoogleSlide
class OmniboxPedalCreateGoogleCalendarEvent
class OmniboxPedalCreateGoogleSite
class OmniboxPedalCreateGoogleKeepNote
class OmniboxPedalCreateGoogleForm
class OmniboxPedalSeeChromeTips
class OmniboxPedalManageGoogleAccount
class OmniboxPedalChangeGooglePassword
class OmniboxPedalCloseIncognitoWindows
class OmniboxPedalPlayChromeDinoGame
class OmniboxPedalFindMyPhone
class OmniboxPedalManageGooglePrivacy
class OmniboxPedalManageChromeSettings
class OmniboxPedalManageChromeDownloads
class OmniboxPedalViewChromeHistory
class OmniboxPedalShareThisPage
class OmniboxPedalManageChromeAccessibility
class OmniboxPedalManageChromeOSAccessibility
class OmniboxPedalCustomizeChromeFonts
class OmniboxPedalManageChromeThemes
class OmniboxPedalCustomizeSearchEngines
Macros
#define SUPPORTS_DESKTOP_ICONS 1
Functions
std::unordered_map< OmniboxPedalId, scoped_refptr< OmniboxPedal > > GetPedalImplementations (bool with_branding, bool incognito)
Variables
constexpr SkColor kChromePagesBlue = SkColorSetARGB(255, 60, 115, 229)
Macro Definition Documentation
SUPPORTS_DESKTOP_ICONS
#define SUPPORTS_DESKTOP_ICONS 1
Function Documentation
GetPedalImplementations()
std::unordered_map<OmniboxPedalId, scoped_refptr<OmniboxPedal> > GetPedalImplementations (bool with_branding, bool incognito)
References OmniboxFieldTrial::IsPedalsBatch3Enabled().
Variable Documentation
kChromePagesBlue
constexpr SkColor kChromePagesBlue = SkColorSetARGB(255, 60, 115, 229) constexpr
Referenced by OmniboxPedalManageChromeSettings::GetVectorIconColor(), OmniboxPedalManageChromeDownloads::GetVectorIconColor(), OmniboxPedalViewChromeHistory::GetVectorIconColor(), OmniboxPedalManageChromeAccessibility::GetVectorIconColor(), and OmniboxPedalManageChromeOSAccessibility::GetVectorIconColor().