Chromium Omnibox: SplitAutocompletion Struct Reference
SplitAutocompletion Struct Reference
#include <autocomplete_match.h>
Public Member Functions
SplitAutocompletion (std::u16string display_text, std::vector< gfx::Range > selections)
SplitAutocompletion ()
SplitAutocompletion (const SplitAutocompletion &copy)
SplitAutocompletion (SplitAutocompletion &&) noexcept
SplitAutocompletion & operator= (const SplitAutocompletion &)
SplitAutocompletion & operator= (SplitAutocompletion &&) noexcept
~SplitAutocompletion ()
bool Empty () const
void Clear ()
Public Attributes
std::u16string display_text
std::vector< gfx::Range > selections
Constructor & Destructor Documentation
SplitAutocompletion() [1/4]
SplitAutocompletion::SplitAutocompletion (std::u16string display_text, std::vector< gfx::Range > selections)
SplitAutocompletion() [2/4]
SplitAutocompletion::SplitAutocompletion () default
SplitAutocompletion() [3/4]
SplitAutocompletion::SplitAutocompletion (const SplitAutocompletion & copy) default
SplitAutocompletion() [4/4]
SplitAutocompletion::SplitAutocompletion (SplitAutocompletion &&) default noexcept
~SplitAutocompletion()
SplitAutocompletion::~SplitAutocompletion () default
Member Function Documentation
Clear()
void SplitAutocompletion::Clear ()
References selections.
Referenced by OmniboxEditModel::InternalSetUserText(), and OmniboxEditModel::OnPopupDataChanged().
Empty()
bool SplitAutocompletion::Empty () const
Referenced by AutocompleteMatch::IsEmptyAutocompletion(), OmniboxEditModel::OnAfterPossibleChange(), OmniboxEditModel::OnPopupDataChanged(), and OmniboxEditModel::StartAutocomplete().
operator=() [1/2]
SplitAutocompletion & SplitAutocompletion::operator= (const SplitAutocompletion &) default
operator=() [2/2]
SplitAutocompletion & SplitAutocompletion::operator= (SplitAutocompletion &&) default noexcept
Member Data Documentation
display_text
std::u16string SplitAutocompletion::display_text
Referenced by OmniboxEditModel::OnPopupDataChanged().
selections
std::vector<gfx::Range> SplitAutocompletion::selections
Referenced by Clear(), and OmniboxEditModel::OnPopupDataChanged().
The documentation for this struct was generated from the following files:
components/omnibox/browser/autocomplete_match.h
components/omnibox/browser/autocomplete_match.cc