Chromium Omnibox: OmniboxRowView Class Reference
OmniboxRowView Class Reference
#include <omnibox_row_view.h>
Classes
class HeaderView
Public Member Functions
METADATA_HEADER (OmniboxRowView)
OmniboxRowView (size_t line, OmniboxPopupModel *popup_model, std::unique_ptr< OmniboxResultView > result_view, PrefService *pref_service)
void ShowHeader (int suggestion_group_id, const std::u16string &header_text)
void HideHeader ()
OmniboxResultView * result_view () const
void OnSelectionStateChanged ()
views::View * GetActiveAuxiliaryButtonForAccessibility () const
gfx::Insets GetInsets () const override
Private Attributes
const size_t line_
OmniboxPopupModel *const popup_model_
HeaderView * header_view_ = nullptr
OmniboxResultView * result_view_
PrefService *const pref_service_
Constructor & Destructor Documentation
OmniboxRowView()
END_METADATA OmniboxRowView::OmniboxRowView (size_t line, OmniboxPopupModel * popup_model, std::unique_ptr< OmniboxResultView > result_view, PrefService * pref_service)
References result_view(), and result_view_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
Member Function Documentation
GetActiveAuxiliaryButtonForAccessibility()
views::View * OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility () const
References OmniboxPopupModel::FOCUSED_BUTTON_HEADER, OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxRowView::HeaderView::header_toggle_button(), header_view_, OmniboxPopupModel::Selection::IsButtonFocused(), popup_model_, result_view_, OmniboxPopupModel::selected_line_state(), and OmniboxPopupModel::selection().
GetInsets()
gfx::Insets OmniboxRowView::GetInsets () const override
References header_view_, and line_.
HideHeader()
void OmniboxRowView::HideHeader ()
References header_view_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
METADATA_HEADER()
OmniboxRowView::METADATA_HEADER (OmniboxRowView)
OnSelectionStateChanged()
void OmniboxRowView::OnSelectionStateChanged ()
References header_view_, OmniboxResultView::OnSelectionStateChanged(), result_view_, and OmniboxRowView::HeaderView::UpdateUI().
result_view()
OmniboxResultView* OmniboxRowView::result_view () const inline
References result_view_.
Referenced by OmniboxRowView(), and OmniboxPopupContentsView::UpdatePopupAppearance().
ShowHeader()
void OmniboxRowView::ShowHeader (int suggestion_group_id, const std::u16string & header_text)
References header_view_, OmniboxRowView::HeaderView::HeaderView(), and OmniboxRowView::HeaderView::SetHeader().
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
Member Data Documentation
header_view_
HeaderView* OmniboxRowView::header_view_ = nullptr private
Referenced by GetActiveAuxiliaryButtonForAccessibility(), GetInsets(), HideHeader(), OnSelectionStateChanged(), and ShowHeader().
line_
const size_t OmniboxRowView::line_ private
Referenced by OmniboxRowView::HeaderView::GetHeaderSelection(), and GetInsets().
popup_model_
OmniboxPopupModel* const OmniboxRowView::popup_model_ private
Referenced by GetActiveAuxiliaryButtonForAccessibility(), OmniboxRowView::HeaderView::HeaderToggleButtonPressed(), OmniboxRowView::HeaderView::HeaderView(), OmniboxRowView::HeaderView::OnMouseReleased(), OmniboxRowView::HeaderView::OnPrefChanged(), OmniboxRowView::HeaderView::SetHeader(), and OmniboxRowView::HeaderView::UpdateUI().
pref_service_
PrefService* const OmniboxRowView::pref_service_ private
Referenced by OmniboxRowView::HeaderView::HeaderView(), OmniboxRowView::HeaderView::OnPrefChanged(), and OmniboxRowView::HeaderView::SetHeader().
result_view_
OmniboxResultView* OmniboxRowView::result_view_ private
Referenced by GetActiveAuxiliaryButtonForAccessibility(), OmniboxRowView(), OnSelectionStateChanged(), and result_view().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_row_view.h
chrome/browser/ui/views/omnibox/omnibox_row_view.cc