Chromium Omnibox: URLPrefix Struct Reference
URLPrefix Struct Reference
#include <url_prefix.h>
Public Member Functions
URLPrefix (const std::u16string &prefix, size_t num_components)
Static Public Member Functions
static const URLPrefixes & GetURLPrefixes ()
static const URLPrefix * BestURLPrefix (const std::u16string &text, const std::u16string &prefix_suffix)
static size_t GetInlineAutocompleteOffset (const std::u16string &input, const std::u16string &fixed_up_input, const bool allow_www_prefix_without_scheme, const std::u16string &text)
Public Attributes
std::u16string prefix
size_t num_components
Constructor & Destructor Documentation
URLPrefix()
URLPrefix::URLPrefix (const std::u16string & prefix, size_t num_components)
Referenced by GetURLPrefixes().
Member Function Documentation
BestURLPrefix()
const URLPrefix * URLPrefix::BestURLPrefix (const std::u16string & text, const std::u16string & prefix_suffix) static
Referenced by HistoryURLProvider::DoAutocomplete(), SearchProvider::NavigationToMatch(), and ScoredHistoryMatch::ScoredHistoryMatch().
GetInlineAutocompleteOffset()
size_t URLPrefix::GetInlineAutocompleteOffset (const std::u16string & input, const std::u16string & fixed_up_input, const bool allow_www_prefix_without_scheme, const std::u16string & text) static
References prefix.
Referenced by HistoryQuickProvider::QuickMatchToACMatch(), ShortcutsProvider::ShortcutToACMatch(), and bookmarks::TitledUrlMatchToAutocompleteMatch().
GetURLPrefixes()
const URLPrefixes & URLPrefix::GetURLPrefixes () static
References URLPrefix().
Referenced by HistoryURLProvider::DoAutocomplete(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
Member Data Documentation
num_components
size_t URLPrefix::num_components
Referenced by HistoryURLProvider::DoAutocomplete(), and ScoredHistoryMatch::ScoredHistoryMatch().
prefix
std::u16string URLPrefix::prefix
Referenced by GetInlineAutocompleteOffset(), SearchProvider::NavigationToMatch(), and ScoredHistoryMatch::ScoredHistoryMatch().
The documentation for this struct was generated from the following files:
components/omnibox/browser/url_prefix.h
components/omnibox/browser/url_prefix.cc