Chromium Omnibox: components/omnibox/browser/in_memory_url_index_types.h File Reference
in_memory_url_index_types.h File Reference
#include <stddef.h>
#include <map>
#include <string>
#include <unordered_map>
#include <vector>
#include "base/containers/flat_set.h"
#include "components/history/core/browser/history_types.h"
#include "url/gurl.h"
Classes
struct TermMatch
struct HistoryInfoMapValue
struct RowWordStarts
Typedefs
typedef std::vector< std::u16string > String16Vector
typedef base::flat_set< std::u16string > String16Set
typedef base::flat_set< char16_t > Char16Set
typedef std::vector< char16_t > Char16Vector
typedef std::vector< size_t > WordStarts
typedef std::vector< TermMatch > TermMatches
typedef size_t WordID
typedef std::map< std::u16string, WordID > WordMap
typedef base::flat_set< WordID > WordIDSet
typedef std::map< char16_t, WordIDSet > CharWordIDMap
typedef history::URLID HistoryID
typedef base::flat_set< HistoryID > HistoryIDSet
typedef std::vector< HistoryID > HistoryIDVector
typedef std::map< WordID, HistoryIDSet > WordIDHistoryMap
typedef std::map< HistoryID, WordIDSet > HistoryIDWordMap
typedef std::vector< history::VisitInfo > VisitInfoVector
typedef std::unordered_map< HistoryID, HistoryInfoMapValue > HistoryInfoMap
typedef std::map< HistoryID, RowWordStarts > WordStartsMap
Functions
TermMatches MatchTermsInString (const String16Vector &terms, const std::u16string &cleaned_string)
TermMatches MatchTermInString (const std::u16string &term, const std::u16string &cleaned_string, int term_num)
TermMatches SortMatches (const TermMatches &matches)
TermMatches DeoverlapMatches (const TermMatches &sorted_matches)
std::vector< size_t > OffsetsFromTermMatches (const TermMatches &matches)
TermMatches ReplaceOffsetsInTermMatches (const TermMatches &matches, const std::vector< size_t > &offsets)
String16Set String16SetFromString16 (const std::u16string &cleaned_uni_string, WordStarts *word_starts)
String16Vector String16VectorFromString16 (const std::u16string &cleaned_uni_string, bool break_on_space, WordStarts *word_starts)
Char16Set Char16SetFromString16 (const std::u16string &uni_word)
Typedef Documentation
Char16Set
typedef base::flat_set<char16_t> Char16Set
Char16Vector
typedef std::vector<char16_t> Char16Vector
CharWordIDMap
typedef std::map<char16_t, WordIDSet> CharWordIDMap
HistoryID
typedef history::URLID HistoryID
HistoryIDSet
typedef base::flat_set<HistoryID> HistoryIDSet
HistoryIDVector
typedef std::vector<HistoryID> HistoryIDVector
HistoryIDWordMap
typedef std::map<HistoryID, WordIDSet> HistoryIDWordMap
HistoryInfoMap
typedef std::unordered_map<HistoryID, HistoryInfoMapValue> HistoryInfoMap
String16Set
typedef base::flat_set<std::u16string> String16Set
String16Vector
typedef std::vector<std::u16string> String16Vector
TermMatches
typedef std::vector<TermMatch> TermMatches
VisitInfoVector
typedef std::vector<history::VisitInfo> VisitInfoVector
WordID
typedef size_t WordID
WordIDHistoryMap
typedef std::map<WordID, HistoryIDSet> WordIDHistoryMap
WordIDSet
typedef base::flat_set<WordID> WordIDSet
WordMap
typedef std::map<std::u16string, WordID> WordMap
WordStarts
typedef std::vector<size_t> WordStarts
WordStartsMap
typedef std::map<HistoryID, RowWordStarts> WordStartsMap
Function Documentation
Char16SetFromString16()
Char16Set Char16SetFromString16 (const std::u16string & uni_word)
Referenced by URLIndexPrivateData::AddWordToIndex(), URLIndexPrivateData::HistoryIDsForTerm(), and URLIndexPrivateData::RemoveRowWordsFromIndex().
DeoverlapMatches()
TermMatches DeoverlapMatches (const TermMatches & sorted_matches)
Referenced by FindTermMatches(), and ScoredHistoryMatch::ScoredHistoryMatch().
MatchTermInString()
TermMatches MatchTermInString (const std::u16string & term, const std::u16string & cleaned_string, int term_num)
Referenced by MatchTermsInString(), and ScoredHistoryMatch::ScoredHistoryMatch().
MatchTermsInString()
TermMatches MatchTermsInString (const String16Vector & terms, const std::u16string & cleaned_string)
References MatchTermInString().
Referenced by FindTermMatches().
OffsetsFromTermMatches()
std::vector<size_t> OffsetsFromTermMatches (const TermMatches & matches)
Referenced by ScoredHistoryMatch::ScoredHistoryMatch().
ReplaceOffsetsInTermMatches()
TermMatches ReplaceOffsetsInTermMatches (const TermMatches & matches, const std::vector< size_t > & offsets)
References TermMatch::length, and TermMatch::offset.
Referenced by ScoredHistoryMatch::ScoredHistoryMatch().
SortMatches()
TermMatches SortMatches (const TermMatches & matches)
References SortMatchComparator().
Referenced by FindTermMatches(), and ScoredHistoryMatch::ScoredHistoryMatch().
String16SetFromString16()
String16Set String16SetFromString16 (const std::u16string & cleaned_uni_string, WordStarts * word_starts)
References String16VectorFromString16().
Referenced by URLIndexPrivateData::AddRowWordsToIndex().
String16VectorFromString16()
String16Vector String16VectorFromString16 (const std::u16string & cleaned_uni_string, bool break_on_space, WordStarts * word_starts)
References TailoredWordBreakIterator::Advance(), TailoredWordBreakIterator::GetString(), TailoredWordBreakIterator::IsWord(), and TailoredWordBreakIterator::prev().
Referenced by FindAtWordbreak(), FindTermMatches(), FindWordsSequentiallyAtWordbreak(), URLIndexPrivateData::HistoryItemsForTerms(), URLIndexPrivateData::RestoreWordStartsMap(), and String16SetFromString16().