Chromium Omnibox: chrome/browser/ui/omnibox/omnibox_theme.cc File Reference
omnibox_theme.cc File Reference
#include "chrome/browser/ui/omnibox/omnibox_theme.h"
#include "base/notreached.h"
#include "build/build_config.h"
#include "chrome/browser/themes/theme_properties.h"
#include "components/omnibox/browser/omnibox_field_trial.h"
#include "ui/base/theme_provider.h"
#include "ui/gfx/color_palette.h"
Typedefs
using TP = ThemeProperties
Functions
SkColor GetOmniboxColor (const ui::ThemeProvider *theme_provider, OmniboxPart part, OmniboxPartState state)
SkColor GetOmniboxSecurityChipColor (const ui::ThemeProvider *theme_provider, security_state::SecurityLevel security_level)
float GetOmniboxStateOpacity (OmniboxPartState state)
Typedef Documentation
TP
using TP = ThemeProperties
Function Documentation
GetOmniboxColor()
SkColor GetOmniboxColor (const ui::ThemeProvider * theme_provider, OmniboxPart part, OmniboxPartState state)
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxResultView::GetColor(), GetOmniboxSecurityChipColor(), OmniboxResultView::GetPopupCellBackground(), OmniboxSuggestionRowButton::OnThemeChanged(), OmniboxViewViews::OnThemeChanged(), OmniboxViewViews::SetEmphasis(), OmniboxSuggestionRowButton::UpdateBackgroundColor(), and OmniboxRowView::HeaderView::UpdateUI().
GetOmniboxSecurityChipColor()
SkColor GetOmniboxSecurityChipColor (const ui::ThemeProvider * theme_provider, security_state::SecurityLevel security_level)
References GetOmniboxColor(), and LOCATION_BAR_TEXT_DIMMED.
GetOmniboxStateOpacity()
float GetOmniboxStateOpacity (OmniboxPartState state)
Referenced by OmniboxSuggestionRowButton::OmniboxSuggestionRowButton().