Chromium Omnibox: OmniboxEditModel Class Reference
OmniboxEditModel Class Reference
#include <omnibox_edit_model.h>
Classes
struct State
Public Member Functions
OmniboxEditModel (OmniboxView *view, OmniboxEditController *controller, std::unique_ptr< OmniboxClient > client)
virtual ~OmniboxEditModel ()
OmniboxEditModel (const OmniboxEditModel &)=delete
OmniboxEditModel & operator= (const OmniboxEditModel &)=delete
AutocompleteController * autocomplete_controller () const
void set_popup_view (OmniboxPopupView *popup_view)
OmniboxPopupView * get_popup_view ()
OmniboxEditController * controller () const
OmniboxClient * client () const
metrics::OmniboxEventProto::PageClassification GetPageClassification () const
State GetStateForTabSwitch () const
void RestoreState (const State *state)
virtual AutocompleteMatch CurrentMatch (GURL *alternate_nav_url) const
void GetDataForURLExport (GURL *url, std::u16string *title, gfx::Image *favicon)
bool CurrentTextIsURL () const
void AdjustTextForCopy (int sel_min, std::u16string *text, GURL *url_from_text, bool *write_url)
bool user_input_in_progress () const
bool ShouldShowCurrentPageIcon () const
void SetInputInProgress (bool in_progress)
void UpdateInput (bool has_selected_text, bool prevent_inline_autocomplete)
bool ResetDisplayTexts ()
std::u16string GetPermanentDisplayText () const
void SetUserText (const std::u16string &text)
bool Unelide ()
void OnChanged ()
void Revert ()
void StartAutocomplete (bool has_selected_text, bool prevent_inline_autocomplete)
void StopAutocomplete ()
bool CanPasteAndGo (const std::u16string &text) const
void PasteAndGo (const std::u16string &text, base::TimeTicks match_selection_timestamp=base::TimeTicks())
void ClassifyString (const std::u16string &text, AutocompleteMatch *match, GURL *alternate_nav_url) const
void AcceptInput (WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp=base::TimeTicks())
void ExecuteAction (const AutocompleteMatch &match, size_t match_position, base::TimeTicks match_selection_timestamp, WindowOpenDisposition disposition)
void OpenMatch (AutocompleteMatch match, WindowOpenDisposition disposition, const GURL &alternate_nav_url, const std::u16string &pasted_text, size_t index, base::TimeTicks match_selection_timestamp=base::TimeTicks())
OmniboxFocusState focus_state () const
bool has_focus () const
bool is_caret_visible () const
OmniboxFocusSource focus_source () const
void set_focus_source (OmniboxFocusSource focus_source)
const std::u16string & keyword () const
bool is_keyword_hint () const
bool is_keyword_selected () const
bool InExplicitExperimentalKeywordMode ()
bool AcceptKeyword (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method)
void EnterKeywordModeForDefaultSearchProvider (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method)
void AcceptTemporaryTextAsUserText ()
void ClearKeyword ()
void ClearAdditionalText ()
const AutocompleteResult & result () const
void OnSetFocus (bool control_down)
void StartZeroSuggestRequest (bool user_clobbered_permanent_text=false)
void SetCaretVisibility (bool visible)
void ConsumeCtrlKey ()
void OnWillKillFocus ()
void OnKillFocus ()
bool WillHandleEscapeKey () const
bool OnEscapeKeyPressed ()
void OnControlKeyChanged (bool pressed)
void OnPaste ()
bool is_pasting () const
virtual void OnUpOrDownKeyPressed (int count)
bool MaybeStartQueryForPopup ()
virtual void OnPopupDataChanged (const std::u16string &temporary_text, bool is_temporary_text, const std::u16string &inline_autocompletion, const std::u16string &prefix_autocompletion, const SplitAutocompletion &split_autocompletion, const std::u16string &keyword, bool is_keyword_hint, const std::u16string &additional_text)
bool OnAfterPossibleChange (const OmniboxView::StateChanges &state_changes, bool allow_keyword_ui_change)
void OnCurrentMatchChanged ()
std::u16string GetUserTextForTesting () const
void SetAccessibilityLabel (const AutocompleteMatch &match)
void RevertTemporaryTextAndPopup ()
bool ShouldPreventElision () const
bool IsStarredMatch (const AutocompleteMatch &match) const
gfx::Image GetMatchIcon (const AutocompleteMatch &match, SkColor vector_icon_color)
virtual bool PopupIsOpen () const
void ResetPopupToInitialState ()
OmniboxPopupSelection GetPopupSelection () const
void SetPopupSelection (OmniboxPopupSelection new_selection, bool reset_to_default=false, bool force_update_ui=false)
OmniboxPopupSelection StepPopupSelection (OmniboxPopupSelection::Direction direction, OmniboxPopupSelection::Step step)
bool IsPopupSelectionOnInitialLine () const
bool IsPopupControlPresentOnMatch (OmniboxPopupSelection selection) const
bool TriggerPopupSelectionAction (OmniboxPopupSelection selection, base::TimeTicks timestamp=base::TimeTicks(), WindowOpenDisposition disposition=WindowOpenDisposition::CURRENT_TAB)
void TryDeletingPopupLine (size_t line)
std::u16string GetPopupAccessibilityLabelForCurrentSelection (const std::u16string &match_text, bool include_positional_info, int *label_prefix_length=nullptr)
void OnPopupResultChanged ()
const SkBitmap * GetPopupRichSuggestionBitmap (int result_index) const
void SetPopupRichSuggestionBitmap (int result_index, const SkBitmap &bitmap)
Static Public Attributes
static const char kCutOrCopyAllTextHistogram []
Protected Member Functions
virtual PrefService * GetPrefService () const
Private Types
enum PasteState { NONE , PASTING , PASTED }
enum ControlKeyState { UP , DOWN , DOWN_AND_CONSUMED }
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest, ConsumeCtrlKey)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest, ConsumeCtrlKeyOnRequestFocus)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest, ConsumeCtrlKeyOnCtrlAction)
bool query_in_progress () const
void InternalSetUserText (const std::u16string &text)
std::u16string MaybeStripKeyword (const std::u16string &text) const
std::u16string MaybePrependKeyword (const std::u16string &text) const
void GetInfoForCurrentText (AutocompleteMatch *match, GURL *alternate_nav_url) const
bool AllowKeywordSpaceTriggering () const
bool MaybeAcceptKeywordBySpace (const std::u16string &new_text)
bool CreatedKeywordSearchByInsertingSpaceInMiddle (const std::u16string &old_text, const std::u16string &new_text, size_t caret_position) const
bool SetInputInProgressNoNotify (bool in_progress)
void NotifyObserversInputInProgress (bool in_progress)
void SetFocusState (OmniboxFocusState state, OmniboxFocusChangeReason reason)
void OnFaviconFetched (const GURL &page_url, const gfx::Image &icon)
Static Private Member Functions
static bool IsSpaceCharForAcceptingKeyword (wchar_t c)
Private Attributes
std::unique_ptr< OmniboxClient > client_
std::unique_ptr< OmniboxController > omnibox_controller_
OmniboxView * view_
OmniboxEditController * controller_
OmniboxFocusState focus_state_
OmniboxFocusSource focus_source_ = OmniboxFocusSource::INVALID
std::u16string display_text_
std::u16string url_for_editing_
bool user_input_in_progress_
std::u16string user_text_
base::TimeTicks last_omnibox_focus_
bool user_input_since_focus_
bool focus_resulted_in_navigation_
base::TimeTicks time_user_first_modified_omnibox_
std::u16string url_for_remembered_user_selection_
bool just_deleted_text_
std::u16string inline_autocompletion_
std::u16string prefix_autocompletion_
SplitAutocompletion split_autocompletion_
bool has_temporary_text_
std::u16string original_user_text_with_keyword_
PasteState paste_state_
ControlKeyState control_key_state_
std::u16string keyword_
bool is_keyword_hint_
metrics::OmniboxEventProto::KeywordModeEntryMethod keyword_mode_entry_method_
bool in_revert_
bool allow_exact_keyword_match_
AutocompleteInput input_
std::map< int, SkBitmap > rich_suggestion_bitmaps_
OmniboxPopupView * popup_view_ = nullptr
OmniboxPopupSelection popup_selection_
GURL old_focused_url_
base::WeakPtrFactory< OmniboxEditModel > weak_factory_ {this}
Friends
class OmniboxControllerTest
Member Enumeration Documentation
ControlKeyState
enum OmniboxEditModel::ControlKeyState private
Enumerator
UP
DOWN
DOWN_AND_CONSUMED
PasteState
enum OmniboxEditModel::PasteState private
Enumerator
NONE
PASTING
PASTED
Constructor & Destructor Documentation
OmniboxEditModel() [1/2]
OmniboxEditModel::OmniboxEditModel (OmniboxView * view, OmniboxEditController * controller, std::unique_ptr< OmniboxClient > client)
References client_, omnibox_controller_, and OmniboxController::OmniboxController().
Referenced by OmniboxView::OmniboxView().
~OmniboxEditModel()
OmniboxEditModel::~OmniboxEditModel () virtual
OmniboxEditModel() [2/2]
OmniboxEditModel::OmniboxEditModel (const OmniboxEditModel &) delete
Member Function Documentation
AcceptInput()
void OmniboxEditModel::AcceptInput (WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp = base::TimeTicks())
References AutocompleteInput::allow_exact_keyword_match(), autocomplete_controller(), AutocompleteInput::canonicalized_url(), client_, control_key_state_, controller(), AutocompleteInput::current_page_classification(), CurrentMatch(), AutocompleteInput::cursor_position(), AutocompleteMatch::destination_url, DOWN, AutocompleteInput::focus_type(), GetPopupSelection(), OmniboxView::GetText(), has_temporary_text_, input_, is_keyword_selected(), AutocompleteInput::keyword_mode_entry_method(), NONE, OmniboxView::OpenMatch(), paste_state_, popup_view_, AutocompleteInput::prefer_keyword(), AutocompleteInput::prevent_inline_autocomplete(), AutocompleteInput::set_allow_exact_keyword_match(), AutocompleteInput::set_focus_type(), AutocompleteInput::set_keyword_mode_entry_method(), AutocompleteInput::set_prefer_keyword(), AutocompleteInput::set_prevent_inline_autocomplete(), AutocompleteInput::set_want_asynchronous_matches(), AutocompleteInput::text(), AutocompleteMatch::transition, AutocompleteMatch::type, url_for_editing_, AutocompleteMatchType::URL_WHAT_YOU_TYPED, user_input_in_progress(), VerbatimMatchForInput(), view_, and AutocompleteInput::want_asynchronous_matches().
Referenced by OmniboxViewViews::HandleKeyEvent().
AcceptKeyword()
bool OmniboxEditModel::AcceptKeyword (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method)
References autocomplete_controller(), CurrentMatch(), AutocompleteMatch::fill_into_edit, GetPopupSelection(), has_temporary_text_, is_keyword_hint_, OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), keyword_, OmniboxPopupSelection::KEYWORD_MODE, keyword_mode_entry_method_, MaybeStripKeyword(), OmniboxView::OnTemporaryTextMaybeChanged(), original_user_text_with_keyword_, PopupIsOpen(), SetPopupSelection(), StartAutocomplete(), OmniboxPopupSelection::state, AutocompleteController::Stop(), OmniboxView::UpdatePopup(), user_text_, and view_.
Referenced by OmniboxSuggestionButtonRowView::ButtonPressed(), MaybeAcceptKeywordBySpace(), and StepPopupSelection().
AcceptTemporaryTextAsUserText()
void OmniboxEditModel::AcceptTemporaryTextAsUserText ()
References client_, OmniboxView::GetText(), has_temporary_text_, in_revert_, InternalSetUserText(), user_input_in_progress_, and view_.
Referenced by OmniboxController::OnResultChanged().
AdjustTextForCopy()
void OmniboxEditModel::AdjustTextForCopy (int sel_min, std::u16string * text, GURL * url_from_text, bool * write_url)
References client_, controller(), CurrentMatch(), AutocompleteMatch::destination_url, display_text_, OmniboxEditController::GetLocationBarModel(), GetPageClassification(), LocationBarModel::GetURL(), is_keyword_selected(), AutocompleteMatch::IsSearchType(), PopupIsOpen(), AutocompleteMatch::type, url_for_editing_, and user_input_in_progress_.
Referenced by OmniboxViewViews::OnAfterCutOrCopy(), OmniboxViewViews::OnGetDragOperationsForTextfield(), and OmniboxViewViews::OnWriteDragData().
AllowKeywordSpaceTriggering()
bool OmniboxEditModel::AllowKeywordSpaceTriggering () const private
References GetPrefService(), omnibox::kKeywordSpaceTriggeringEnabled, and omnibox::kKeywordSpaceTriggeringSetting.
Referenced by MaybeAcceptKeywordBySpace(), and OnAfterPossibleChange().
autocomplete_controller()
AutocompleteController* OmniboxEditModel::autocomplete_controller () const inline
References omnibox_controller_.
Referenced by AcceptInput(), AcceptKeyword(), ClearKeyword(), CreatedKeywordSearchByInsertingSpaceInMiddle(), EnterKeywordModeForDefaultSearchProvider(), ExecuteAction(), GetPrefService(), OpenMatch(), query_in_progress(), SetInputInProgressNoNotify(), SetPopupSelection(), StartZeroSuggestRequest(), StopAutocomplete(), TryDeletingPopupLine(), and OmniboxPopupContentsView::UpdatePopupAppearance().
CanPasteAndGo()
bool OmniboxEditModel::CanPasteAndGo (const std::u16string & text) const
References ClassifyString(), client_, and AutocompleteMatch::destination_url.
Referenced by OmniboxViewViews::IsCommandIdEnabled(), and PasteAndGo().
ClassifyString()
void OmniboxEditModel::ClassifyString (const std::u16string & text, AutocompleteMatch * match, GURL * alternate_nav_url) const
References client_, and GetPageClassification().
Referenced by CanPasteAndGo(), OmniboxViewViews::GetLabelForCommandId(), PasteAndGo(), and OmniboxViewViews::UnapplySteadyStateElisions().
ClearAdditionalText()
void OmniboxEditModel::ClearAdditionalText ()
References OmniboxView::SetAdditionalText(), and view_.
Referenced by OmniboxController::OnResultChanged().
ClearKeyword()
void OmniboxEditModel::ClearKeyword ()
References autocomplete_controller(), GetPopupSelection(), OmniboxView::GetText(), is_keyword_hint_, is_keyword_selected(), keyword_, OmniboxPopupSelection::KEYWORD_MODE, keyword_mode_entry_method_, omnibox_controller_, OmniboxView::OnAfterPossibleChange(), OmniboxView::OnBeforePossibleChange(), popup_view_, OmniboxView::SetWindowTextAndCaretPos(), OmniboxPopupSelection::state, AutocompleteController::Stop(), and view_.
Referenced by OmniboxViewViews::HandleKeyEvent(), OmniboxViewViews::SetFocus(), and StepPopupSelection().
client()
OmniboxClient* OmniboxEditModel::client () const inline
References client_.
Referenced by GetMatchIcon(), OmniboxViewViews::InstallPlaceholderText(), IsStarredMatch(), SetPopupSelection(), and OmniboxSuggestionButtonRowView::UpdateFromModel().
ConsumeCtrlKey()
void OmniboxEditModel::ConsumeCtrlKey ()
References control_key_state_, DOWN, and DOWN_AND_CONSUMED.
Referenced by OnAfterPossibleChange(), OnPopupDataChanged(), and OmniboxViewViews::SetFocus().
controller()
OmniboxEditController* OmniboxEditModel::controller () const inline
References controller_.
Referenced by AcceptInput(), AdjustTextForCopy(), GetPageClassification(), OnPopupResultChanged(), ResetDisplayTexts(), ShouldPreventElision(), and Unelide().
CreatedKeywordSearchByInsertingSpaceInMiddle()
bool OmniboxEditModel::CreatedKeywordSearchByInsertingSpaceInMiddle (const std::u16string & old_text, const std::u16string & new_text, size_t caret_position) const private
References autocomplete_controller(), IsSpaceCharForAcceptingKeyword(), keyword(), AutocompleteController::keyword_provider(), NONE, and paste_state_.
Referenced by OnAfterPossibleChange().
CurrentMatch()
AutocompleteMatch OmniboxEditModel::CurrentMatch (GURL * alternate_nav_url) const virtual
References client_, AutocompleteResult::ComputeAlternateNavUrl(), AutocompleteMatch::destination_url, GetInfoForCurrentText(), input_, and omnibox_controller_.
Referenced by AcceptInput(), AcceptKeyword(), AdjustTextForCopy(), CurrentTextIsURL(), GetDataForURLExport(), OnChanged(), OnPopupDataChanged(), and RevertTemporaryTextAndPopup().
CurrentTextIsURL()
bool OmniboxEditModel::CurrentTextIsURL () const
References CurrentMatch(), AutocompleteMatch::IsSearchType(), and user_input_in_progress_.
Referenced by OmniboxViewViews::EmphasizeURLComponents().
EnterKeywordModeForDefaultSearchProvider()
void OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method)
References autocomplete_controller(), client_, OmniboxView::GetText(), InternalSetUserText(), is_keyword_hint_, keyword_, keyword_mode_entry_method_, OmniboxView::SelectAll(), OmniboxView::SetWindowTextAndCaretPos(), AutocompleteController::Stop(), user_input_in_progress_, and view_.
Referenced by OmniboxViewViews::EnterKeywordModeForDefaultSearchProvider(), and OnAfterPossibleChange().
ExecuteAction()
void OmniboxEditModel::ExecuteAction (const AutocompleteMatch & match, size_t match_position, base::TimeTicks match_selection_timestamp, WindowOpenDisposition disposition)
References AutocompleteMatch::action, autocomplete_controller(), controller_, in_revert_, OmniboxEditController::OnAutocompleteAccept(), result(), OmniboxView::RevertAll(), and view_.
Referenced by TriggerPopupSelectionAction().
focus_source()
OmniboxFocusSource OmniboxEditModel::focus_source () const inline
References focus_source_.
Referenced by set_focus_source().
focus_state()
OmniboxFocusState OmniboxEditModel::focus_state () const inline
References focus_state_.
Referenced by OmniboxViewViews::OnMousePressed().
FRIEND_TEST_ALL_PREFIXES() [1/3]
OmniboxEditModel::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest , ConsumeCtrlKey) private
FRIEND_TEST_ALL_PREFIXES() [2/3]
OmniboxEditModel::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest , ConsumeCtrlKeyOnCtrlAction) private
FRIEND_TEST_ALL_PREFIXES() [3/3]
OmniboxEditModel::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelTest , ConsumeCtrlKeyOnRequestFocus) private
get_popup_view()
OmniboxPopupView * OmniboxEditModel::get_popup_view ()
References popup_view_.
Referenced by ResetPopupToInitialState().
GetDataForURLExport()
void OmniboxEditModel::GetDataForURLExport (GURL * url, std::u16string * title, gfx::Image * favicon)
References client_, CurrentMatch(), and AutocompleteMatch::destination_url.
Referenced by OmniboxViewViews::OnWriteDragData().
GetInfoForCurrentText()
void OmniboxEditModel::GetInfoForCurrentText (AutocompleteMatch * match, GURL * alternate_nav_url) const private
References AutocompleteMatch::associated_keyword, client_, AutocompleteResult::ComputeAlternateNavUrl(), AutocompleteResult::default_match(), GetPageClassification(), GetPopupSelection(), OmniboxView::GetText(), input_, is_keyword_selected(), IsPopupSelectionOnInitialLine(), OmniboxPopupSelection::KEYWORD_MODE, OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, AutocompleteResult::match_at(), MaybePrependKeyword(), popup_view_, PopupIsOpen(), query_in_progress(), result(), OmniboxPopupSelection::state, url_for_editing_, user_input_in_progress(), and view_.
Referenced by CurrentMatch().
GetMatchIcon()
gfx::Image OmniboxEditModel::GetMatchIcon (const AutocompleteMatch & match, SkColor vector_icon_color)
References client(), AutocompleteMatch::destination_url, AutocompleteMatchType::DOCUMENT_SUGGESTION, OmniboxClient::GetFaviconForPageUrl(), OmniboxClient::GetIconIfExtensionMatch(), OmniboxClient::GetSizedIcon(), AutocompleteMatch::GetVectorIcon(), AutocompleteMatch::IsSearchType(), IsStarredMatch(), OnFaviconFetched(), AutocompleteMatch::type, and weak_factory_.
Referenced by OmniboxPopupContentsView::GetMatchIcon().
GetPageClassification()
metrics::OmniboxEventProto::PageClassification OmniboxEditModel::GetPageClassification () const
References controller(), focus_source_, OmniboxEditController::GetLocationBarModel(), and LocationBarModel::GetPageClassification().
Referenced by AdjustTextForCopy(), ClassifyString(), GetInfoForCurrentText(), OpenMatch(), StartAutocomplete(), and StartZeroSuggestRequest().
GetPermanentDisplayText()
std::u16string OmniboxEditModel::GetPermanentDisplayText () const
References display_text_.
Referenced by ResetDisplayTexts(), and Revert().
GetPopupAccessibilityLabelForCurrentSelection()
std::u16string OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection (const std::u16string & match_text, bool include_positional_info, int * label_prefix_length = nullptr)
References AutocompleteMatch::action, OmniboxPopupSelection::FOCUSED_BUTTON_ACTION, OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, OmniboxPopupSelection::FOCUSED_BUTTON_REMOVE_SUGGESTION, OmniboxPopupSelection::FOCUSED_BUTTON_TAB_SWITCH, GetPrefService(), OmniboxPopupSelection::IsButtonFocused(), AutocompleteResult::IsSuggestionGroupIdHidden(), OmniboxPopupSelection::KEYWORD_MODE, OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, OmniboxPopupSelection::LINE_STATE_MAX_VALUE, AutocompleteResult::match_at(), OmniboxPopupSelection::NORMAL, popup_selection_, popup_view_, result(), AutocompleteResult::size(), OmniboxPopupSelection::state, AutocompleteMatch::suggestion_group_id, and AutocompleteMatchType::ToAccessibilityLabel().
Referenced by OmniboxResultView::GetAccessibleNodeData(), and OmniboxViewViews::SetAccessibilityLabel().
GetPopupRichSuggestionBitmap()
const SkBitmap * OmniboxEditModel::GetPopupRichSuggestionBitmap (int result_index) const
References popup_view_, and rich_suggestion_bitmaps_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
GetPopupSelection()
OmniboxPopupSelection OmniboxEditModel::GetPopupSelection () const
References popup_selection_, and popup_view_.
Referenced by AcceptInput(), AcceptKeyword(), ClearKeyword(), OmniboxController::ClearPopupKeywordMode(), OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility(), GetInfoForCurrentText(), OmniboxPopupContentsView::GetSelection(), OmniboxViewViews::HandleKeyEvent(), OmniboxRowView::HeaderView::HeaderView(), IsPopupSelectionOnInitialLine(), OmniboxViewViews::OnMousePressed(), OnPopupResultChanged(), SetPopupSelection(), StepPopupSelection(), TriggerPopupSelectionAction(), TryDeletingPopupLine(), OmniboxPopupContentsView::UnselectButton(), and OmniboxRowView::HeaderView::UpdateUI().
GetPrefService()
PrefService * OmniboxEditModel::GetPrefService () const protected virtual
References autocomplete_controller(), AutocompleteController::autocomplete_provider_client(), and AutocompleteProviderClient::GetPrefs().
Referenced by AllowKeywordSpaceTriggering(), GetPopupAccessibilityLabelForCurrentSelection(), IsPopupControlPresentOnMatch(), OnUpOrDownKeyPressed(), StepPopupSelection(), and TriggerPopupSelectionAction().
GetStateForTabSwitch()
OmniboxEditModel::State OmniboxEditModel::GetStateForTabSwitch () const
References focus_source_, focus_state_, OmniboxView::GetText(), input_, is_keyword_hint_, keyword_, keyword_mode_entry_method_, MaybePrependKeyword(), user_input_in_progress_, user_text_, and view_.
Referenced by OmniboxViewViews::SaveStateToTab().
GetUserTextForTesting()
std::u16string OmniboxEditModel::GetUserTextForTesting () const inline
References user_text_.
has_focus()
bool OmniboxEditModel::has_focus () const inline
References focus_state_, and OMNIBOX_FOCUS_NONE.
Referenced by OnChanged(), ResetDisplayTexts(), and UpdateInput().
InExplicitExperimentalKeywordMode()
bool OmniboxEditModel::InExplicitExperimentalKeywordMode ()
References AutocompleteProvider::InExplicitExperimentalKeywordMode(), input_, and keyword_.
Referenced by OmniboxPopupContentsView::InExplicitExperimentalKeywordMode().
InternalSetUserText()
void OmniboxEditModel::InternalSetUserText (const std::u16string & text) private
References SplitAutocompletion::Clear(), inline_autocompletion_, just_deleted_text_, OmniboxView::OnInlineAutocompleteTextCleared(), original_user_text_with_keyword_, prefix_autocompletion_, split_autocompletion_, user_text_, and view_.
Referenced by AcceptTemporaryTextAsUserText(), EnterKeywordModeForDefaultSearchProvider(), MaybeStartQueryForPopup(), OnAfterPossibleChange(), RestoreState(), Revert(), SetUserText(), and Unelide().
is_caret_visible()
bool OmniboxEditModel::is_caret_visible () const inline
References focus_state_, and OMNIBOX_FOCUS_VISIBLE.
Referenced by SetFocusState(), and OmniboxViewViews::ShouldShowPlaceholderText().
is_keyword_hint()
bool OmniboxEditModel::is_keyword_hint () const inline
References is_keyword_hint_.
Referenced by OmniboxSuggestionButtonRowView::ButtonPressed(), OnCurrentMatchChanged(), OnPopupDataChanged(), and SetPopupSelection().
is_keyword_selected()
bool OmniboxEditModel::is_keyword_selected () const inline
References is_keyword_hint_, and keyword_.
Referenced by AcceptInput(), AdjustTextForCopy(), ClearKeyword(), GetInfoForCurrentText(), OmniboxView::GetState(), MaybePrependKeyword(), MaybeStripKeyword(), OnAfterPossibleChange(), OnCurrentMatchChanged(), OnPopupDataChanged(), OpenMatch(), OmniboxViewViews::ShouldShowPlaceholderText(), StartAutocomplete(), and UpdateInput().
is_pasting()
bool OmniboxEditModel::is_pasting () const inline
References paste_state_, and PASTING.
IsPopupControlPresentOnMatch()
bool OmniboxEditModel::IsPopupControlPresentOnMatch (OmniboxPopupSelection selection) const
References GetPrefService(), OmniboxPopupSelection::IsControlPresentOnMatch(), popup_view_, and result().
Referenced by OmniboxSuggestionButtonRowView::SetPillButtonVisibility(), and OmniboxResultView::UpdateRemoveSuggestionVisibility().
IsPopupSelectionOnInitialLine()
bool OmniboxEditModel::IsPopupSelectionOnInitialLine () const
References AutocompleteResult::default_match(), GetPopupSelection(), OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, popup_view_, and result().
Referenced by GetInfoForCurrentText().
IsSpaceCharForAcceptingKeyword()
bool OmniboxEditModel::IsSpaceCharForAcceptingKeyword (wchar_t c) static private
Referenced by CreatedKeywordSearchByInsertingSpaceInMiddle(), and MaybeAcceptKeywordBySpace().
IsStarredMatch()
bool OmniboxEditModel::IsStarredMatch (const AutocompleteMatch & match) const
References client(), AutocompleteMatch::destination_url, and OmniboxClient::GetBookmarkModel().
Referenced by GetMatchIcon().
keyword()
const std::u16string& OmniboxEditModel::keyword () const inline
References keyword_.
Referenced by CreatedKeywordSearchByInsertingSpaceInMiddle(), OmniboxView::GetState(), OnCurrentMatchChanged(), OnPopupDataChanged(), and SetPopupSelection().
MaybeAcceptKeywordBySpace()
bool OmniboxEditModel::MaybeAcceptKeywordBySpace (const std::u16string & new_text) private
References AcceptKeyword(), AllowKeywordSpaceTriggering(), is_keyword_hint_, IsSpaceCharForAcceptingKeyword(), and keyword_.
Referenced by OnAfterPossibleChange().
MaybePrependKeyword()
std::u16string OmniboxEditModel::MaybePrependKeyword (const std::u16string & text) const private
References is_keyword_selected(), and keyword_.
Referenced by GetInfoForCurrentText(), GetStateForTabSwitch(), and StartAutocomplete().
MaybeStartQueryForPopup()
bool OmniboxEditModel::MaybeStartQueryForPopup ()
References InternalSetUserText(), PopupIsOpen(), query_in_progress(), OmniboxView::UpdatePopup(), url_for_editing_, user_input_in_progress_, and view_.
Referenced by OnUpOrDownKeyPressed().
MaybeStripKeyword()
std::u16string OmniboxEditModel::MaybeStripKeyword (const std::u16string & text) const private
References is_keyword_selected(), and KeywordProvider::SplitReplacementStringFromInput().
Referenced by AcceptKeyword(), and OnPopupDataChanged().
NotifyObserversInputInProgress()
void OmniboxEditModel::NotifyObserversInputInProgress (bool in_progress) private
References client_, controller_, in_revert_, OmniboxEditController::OnInputInProgress(), and user_input_in_progress_.
Referenced by SetInputInProgress(), and UpdateInput().
OnAfterPossibleChange()
bool OmniboxEditModel::OnAfterPossibleChange (const OmniboxView::StateChanges & state_changes, bool allow_keyword_ui_change)
References allow_exact_keyword_match_, AllowKeywordSpaceTriggering(), ConsumeCtrlKey(), CreatedKeywordSearchByInsertingSpaceInMiddle(), SplitAutocompletion::Empty(), EnterKeywordModeForDefaultSearchProvider(), FAKEBOX, focus_source_, focus_state_, has_temporary_text_, inline_autocompletion_, InternalSetUserText(), INVALID, is_keyword_selected(), OmniboxView::StateChanges::just_deleted_text, just_deleted_text_, OmniboxView::StateChanges::keyword_differs, keyword_mode_entry_method_, MaybeAcceptKeywordBySpace(), OmniboxView::StateChanges::new_sel_end, OmniboxView::StateChanges::new_sel_start, OmniboxView::StateChanges::new_text, NONE, OmniboxView::StateChanges::old_text, OMNIBOX, OMNIBOX_FOCUS_CHANGE_TYPING, OMNIBOX_FOCUS_INVISIBLE, OMNIBOX_FOCUS_VISIBLE, paste_state_, PASTED, PASTING, prefix_autocompletion_, OmniboxView::StateChanges::selection_differs, SetFocusState(), split_autocompletion_, OmniboxView::StateChanges::text_differs, OmniboxView::UpdatePopup(), user_text_, and view_.
Referenced by OmniboxViewViews::OnAfterPossibleChange().
OnChanged()
void OmniboxEditModel::OnChanged ()
References client_, controller_, CurrentMatch(), has_focus(), OmniboxEditController::OnChanged(), result(), user_input_in_progress_, and user_text_.
Referenced by OnPopupDataChanged().
OnControlKeyChanged()
void OmniboxEditModel::OnControlKeyChanged (bool pressed)
References control_key_state_, DOWN, and UP.
Referenced by OmniboxViewViews::HandleKeyEvent().
OnCurrentMatchChanged()
void OmniboxEditModel::OnCurrentMatchChanged ()
References AutocompleteMatch::additional_text, client_, AutocompleteMatch::GetKeywordUIState(), has_temporary_text_, AutocompleteMatch::inline_autocompletion, is_keyword_hint(), is_keyword_selected(), keyword(), omnibox_controller_, OnPopupDataChanged(), OnPopupResultChanged(), original_user_text_with_keyword_, AutocompleteMatch::prefix_autocompletion, AutocompleteMatch::split_autocompletion, KeywordProvider::SplitReplacementStringFromInput(), and user_text_.
Referenced by OmniboxController::OnResultChanged().
OnEscapeKeyPressed()
bool OmniboxEditModel::OnEscapeKeyPressed ()
References client_, has_temporary_text_, OmniboxView::RevertAll(), RevertTemporaryTextAndPopup(), OmniboxView::SelectAll(), OmniboxView::Update(), user_input_in_progress_, and view_.
Referenced by OmniboxViewViews::HandleKeyEvent().
OnFaviconFetched()
void OmniboxEditModel::OnFaviconFetched (const GURL & page_url, const gfx::Image & icon) private
References AutocompleteMatch::IsSearchType(), AutocompleteResult::match_at(), OmniboxPopupView::OnMatchIconUpdated(), popup_view_, PopupIsOpen(), result(), and AutocompleteResult::size().
Referenced by GetMatchIcon().
OnKillFocus()
void OmniboxEditModel::OnKillFocus ()
References control_key_state_, focus_resulted_in_navigation_, focus_source_, OmniboxView::HideImeIfNeeded(), INVALID, last_omnibox_focus_, NONE, OMNIBOX_FOCUS_CHANGE_EXPLICIT, OMNIBOX_FOCUS_NONE, paste_state_, SetFocusState(), UP, and view_.
Referenced by OmniboxViewViews::OnBlur().
OnPaste()
void OmniboxEditModel::OnPaste ()
References paste_state_, and PASTING.
Referenced by OmniboxViewViews::OnOmniboxPaste().
OnPopupDataChanged()
void OmniboxEditModel::OnPopupDataChanged (const std::u16string & temporary_text, bool is_temporary_text, const std::u16string & inline_autocompletion, const std::u16string & prefix_autocompletion, const SplitAutocompletion & split_autocompletion, const std::u16string & keyword, bool is_keyword_hint, const std::u16string & additional_text) virtual
References SplitAutocompletion::Clear(), ConsumeCtrlKey(), CurrentMatch(), SplitAutocompletion::display_text, SplitAutocompletion::Empty(), has_temporary_text_, inline_autocompletion_, input_, is_keyword_hint(), is_keyword_hint_, is_keyword_selected(), keyword(), keyword_, keyword_mode_entry_method_, MaybeStripKeyword(), omnibox_controller_, OnChanged(), OmniboxView::OnInlineAutocompleteTextCleared(), OmniboxView::OnInlineAutocompleteTextMaybeChanged(), OmniboxView::OnTemporaryTextMaybeChanged(), original_user_text_with_keyword_, prefix_autocompletion_, SplitAutocompletion::selections, OmniboxView::SetAdditionalText(), OmniboxView::SetWindowTextAndCaretPos(), split_autocompletion_, AutocompleteInput::text(), user_input_in_progress_, user_text_, and view_.
Referenced by OnCurrentMatchChanged(), OmniboxController::OnResultChanged(), and SetPopupSelection().
OnPopupResultChanged()
void OmniboxEditModel::OnPopupResultChanged ()
References controller(), AutocompleteResult::default_match(), AutocompleteMatch::destination_url, OmniboxPopupSelection::FOCUSED_BUTTON_TAB_SWITCH, GetPopupSelection(), AutocompleteMatch::has_tab_match, OmniboxPopupView::IsOpen(), OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, AutocompleteResult::match_at(), OmniboxPopupSelection::NORMAL, old_focused_url_, OmniboxEditController::OnPopupVisibilityChanged(), popup_selection_, popup_view_, result(), rich_suggestion_bitmaps_, OmniboxPopupSelection::state, and OmniboxPopupView::UpdatePopupAppearance().
Referenced by OnCurrentMatchChanged(), and OmniboxController::OnResultChanged().
OnSetFocus()
void OmniboxEditModel::OnSetFocus (bool control_down)
References client_, control_key_state_, DOWN_AND_CONSUMED, focus_resulted_in_navigation_, in_revert_, last_omnibox_focus_, OMNIBOX_FOCUS_CHANGE_EXPLICIT, OMNIBOX_FOCUS_VISIBLE, SetFocusState(), UP, user_input_in_progress_, and user_input_since_focus_.
Referenced by OmniboxViewViews::OnFocus().
OnUpOrDownKeyPressed()
void OmniboxEditModel::OnUpOrDownKeyPressed (int count) virtual
References OmniboxPopupSelection::GetNextSelection(), GetPrefService(), has_temporary_text_, OmniboxPopupSelection::kBackward, OmniboxPopupSelection::kForward, OmniboxPopupSelection::kWholeLine, OmniboxPopupSelection::line, MaybeStartQueryForPopup(), popup_selection_, PopupIsOpen(), result(), RevertTemporaryTextAndPopup(), SetPopupSelection(), and user_input_in_progress_.
Referenced by OmniboxViewViews::ExecuteTextEditCommand().
OnWillKillFocus()
void OmniboxEditModel::OnWillKillFocus ()
References client_, in_revert_, and user_input_in_progress_.
Referenced by OmniboxViewViews::OnBlur().
OpenMatch()
void OmniboxEditModel::OpenMatch (AutocompleteMatch match, WindowOpenDisposition disposition, const GURL & alternate_nav_url, const std::u16string & pasted_text, size_t index, base::TimeTicks match_selection_timestamp = base::TimeTicks())
References AutocompleteInput::added_default_scheme_to_typed_url(), AutocompleteController::AddProviderAndTriggeringLogs(), AutocompleteMatch::allowed_to_be_default_match, AutocompleteMatch::answer, AutocompleteResult::AppendMatches(), autocomplete_controller(), client_, controller_, omnibox::DEFAULT, AutocompleteMatch::destination_url, OmniboxLog::elapsed_time_since_last_change_to_default_match, OmniboxLog::elapsed_time_since_user_first_modified_omnibox, focus_resulted_in_navigation_, AutocompleteInput::focus_type(), OmniboxEventGlobalTracker::GetInstance(), GetPageClassification(), AutocompleteMatch::GetTemplateURL(), in_revert_, AutocompleteMatch::inline_autocompletion, input_, is_keyword_selected(), just_deleted_text_, keyword_mode_entry_method_, last_omnibox_focus_, SuggestionAnswer::LogAnswerUsed(), AutocompleteMatch::LogSearchEngineUsed(), OmniboxEditController::OnAutocompleteAccept(), OmniboxEventGlobalTracker::OnURLOpened(), PopupIsOpen(), AutocompleteMatch::post_content, AutocompleteMatch::provider, result(), OmniboxView::RevertAll(), AutocompleteInput::set_current_title(), AutocompleteInput::set_current_url(), AutocompleteResult::size(), OmniboxLog::tab_id, time_user_first_modified_omnibox_, AutocompleteMatch::transition, AutocompleteInput::type(), AutocompleteMatch::type, AutocompleteController::UpdateMatchDestinationURLWithAdditionalAssistedQueryStats(), url_for_editing_, user_input_in_progress_, user_text_, VerbatimMatchForInput(), and view_.
Referenced by TriggerPopupSelectionAction().
operator=()
OmniboxEditModel& OmniboxEditModel::operator= (const OmniboxEditModel &) delete
PasteAndGo()
void OmniboxEditModel::PasteAndGo (const std::u16string & text, base::TimeTicks match_selection_timestamp = base::TimeTicks())
References CanPasteAndGo(), ClassifyString(), client_, AutocompleteMatch::destination_url, input_, OmniboxPopupSelection::kNoMatch, OmniboxView::OpenMatch(), OmniboxView::RevertAll(), AutocompleteInput::set_added_default_scheme_to_typed_url(), AutocompleteInput::ShouldUpgradeToHttps(), AutocompleteMatch::type, AutocompleteMatchType::URL_WHAT_YOU_TYPED, and view_.
Referenced by OmniboxViewViews::ExecuteCommand().
PopupIsOpen()
bool OmniboxEditModel::PopupIsOpen () const virtual
References OmniboxPopupView::IsOpen(), and popup_view_.
Referenced by AcceptKeyword(), AdjustTextForCopy(), OmniboxController::ClearPopupKeywordMode(), GetInfoForCurrentText(), MaybeStartQueryForPopup(), OnFaviconFetched(), OmniboxController::OnResultChanged(), OnUpOrDownKeyPressed(), OpenMatch(), ResetDisplayTexts(), ShouldShowCurrentPageIcon(), and StartZeroSuggestRequest().
query_in_progress()
bool OmniboxEditModel::query_in_progress () const inline private
References autocomplete_controller(), and AutocompleteController::done().
Referenced by GetInfoForCurrentText(), MaybeStartQueryForPopup(), and StartZeroSuggestRequest().
ResetDisplayTexts()
bool OmniboxEditModel::ResetDisplayTexts ()
References controller(), display_text_, OmniboxEditController::GetLocationBarModel(), GetPermanentDisplayText(), has_focus(), PopupIsOpen(), url_for_editing_, and user_input_in_progress_.
Referenced by OmniboxViewViews::OnFocus(), and RestoreState().
ResetPopupToInitialState()
void OmniboxEditModel::ResetPopupToInitialState ()
References AutocompleteResult::default_match(), get_popup_view(), OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::NORMAL, OmniboxPopupView::OnDragCanceled(), popup_view_, result(), and SetPopupSelection().
Referenced by RevertTemporaryTextAndPopup().
RestoreState()
void OmniboxEditModel::RestoreState (const State * state)
References OmniboxEditModel::State::autocomplete_input, OmniboxEditModel::State::focus_source, focus_source_, OmniboxEditModel::State::focus_state, focus_state_, input_, InternalSetUserText(), OmniboxEditModel::State::is_keyword_hint, is_keyword_hint_, OmniboxEditModel::State::keyword, keyword_, OmniboxEditModel::State::keyword_mode_entry_method, keyword_mode_entry_method_, OMNIBOX_FOCUS_CHANGE_TAB_SWITCH, OMNIBOX_FOCUS_NONE, OMNIBOX_FOCUS_VISIBLE, ResetDisplayTexts(), OmniboxView::RevertAll(), SetFocusState(), OmniboxView::SetUserText(), OmniboxView::SetWindowTextAndCaretPos(), OmniboxEditModel::State::user_input_in_progress, OmniboxEditModel::State::user_text, and view_.
Referenced by OmniboxViewViews::OnTabChanged().
result()
const AutocompleteResult& OmniboxEditModel::result () const inline
References omnibox_controller_.
Referenced by ExecuteAction(), OmniboxResultView::GetAccessibleNodeData(), OmniboxPopupContentsView::GetIndexForPoint(), GetInfoForCurrentText(), OmniboxPopupContentsView::GetMatchAtIndex(), GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupContentsView::GetTargetBounds(), OmniboxPopupContentsView::HasMatchAt(), IsPopupControlPresentOnMatch(), IsPopupSelectionOnInitialLine(), OmniboxSuggestionButtonRowView::match(), OnChanged(), OnFaviconFetched(), OnPopupResultChanged(), OmniboxRowView::HeaderView::OnPrefChanged(), OmniboxPopupContentsView::OnSuggestionGroupVisibilityUpdate(), OnUpOrDownKeyPressed(), OpenMatch(), OmniboxPopupContentsView::OpenMatch(), ResetPopupToInitialState(), RevertTemporaryTextAndPopup(), OmniboxRowView::HeaderView::SetHeader(), SetPopupSelection(), StepPopupSelection(), TriggerPopupSelectionAction(), TryDeletingPopupLine(), and OmniboxPopupContentsView::UpdatePopupAppearance().
Revert()
void OmniboxEditModel::Revert ()
References AutocompleteInput::Clear(), client_, GetPermanentDisplayText(), OmniboxView::GetSelectionBounds(), has_temporary_text_, input_, InternalSetUserText(), is_keyword_hint_, keyword_, keyword_mode_entry_method_, NONE, paste_state_, OmniboxView::SetCaretPos(), SetInputInProgress(), OmniboxView::SetWindowTextAndCaretPos(), and view_.
RevertTemporaryTextAndPopup()
void OmniboxEditModel::RevertTemporaryTextAndPopup ()
References CurrentMatch(), AutocompleteMatch::fill_into_edit, has_temporary_text_, input_, just_deleted_text_, OmniboxView::OnRevertTemporaryText(), ResetPopupToInitialState(), result(), OmniboxView::SetWindowTextAndCaretPos(), AutocompleteInput::text(), user_input_in_progress_, and view_.
Referenced by OnEscapeKeyPressed(), and OnUpOrDownKeyPressed().
set_focus_source()
void OmniboxEditModel::set_focus_source (OmniboxFocusSource focus_source) inline
References focus_source(), and focus_source_.
set_popup_view()
void OmniboxEditModel::set_popup_view (OmniboxPopupView * popup_view)
References OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::NORMAL, old_focused_url_, popup_selection_, popup_view_, and rich_suggestion_bitmaps_.
Referenced by OmniboxPopupContentsView::OmniboxPopupContentsView(), and OmniboxPopupContentsView::~OmniboxPopupContentsView().
SetAccessibilityLabel()
void OmniboxEditModel::SetAccessibilityLabel (const AutocompleteMatch & match)
References OmniboxView::GetText(), OmniboxView::SetAccessibilityLabel(), and view_.
Referenced by SetPopupSelection().
SetCaretVisibility()
void OmniboxEditModel::SetCaretVisibility (bool visible)
References focus_state_, OMNIBOX_FOCUS_CHANGE_EXPLICIT, OMNIBOX_FOCUS_INVISIBLE, OMNIBOX_FOCUS_NONE, OMNIBOX_FOCUS_VISIBLE, and SetFocusState().
Referenced by OmniboxViewViews::OnMousePressed(), and OmniboxViewViews::SetFocus().
SetFocusState()
void OmniboxEditModel::SetFocusState (OmniboxFocusState state, OmniboxFocusChangeReason reason) private
References OmniboxView::ApplyCaretVisibility(), client_, focus_state_, is_caret_visible(), OMNIBOX_FOCUS_NONE, and view_.
Referenced by OnAfterPossibleChange(), OnKillFocus(), OnSetFocus(), RestoreState(), and SetCaretVisibility().
SetInputInProgress()
void OmniboxEditModel::SetInputInProgress (bool in_progress)
References NotifyObserversInputInProgress(), and SetInputInProgressNoNotify().
Referenced by OmniboxViewViews::HandleAccessibleAction(), Revert(), and SetUserText().
SetInputInProgressNoNotify()
bool OmniboxEditModel::SetInputInProgressNoNotify (bool in_progress) private
References autocomplete_controller(), last_omnibox_focus_, AutocompleteController::ResetSession(), time_user_first_modified_omnibox_, user_input_in_progress_, and user_input_since_focus_.
Referenced by SetInputInProgress(), and UpdateInput().
SetPopupRichSuggestionBitmap()
void OmniboxEditModel::SetPopupRichSuggestionBitmap (int result_index, const SkBitmap & bitmap)
References popup_view_, rich_suggestion_bitmaps_, and OmniboxPopupView::UpdatePopupAppearance().
Referenced by OmniboxController::SetRichSuggestionBitmap().
SetPopupSelection()
void OmniboxEditModel::SetPopupSelection (OmniboxPopupSelection new_selection, bool reset_to_default = false, bool force_update_ui = false)
References AutocompleteMatch::additional_text, AutocompleteMatch::associated_keyword, autocomplete_controller(), client(), AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, AutocompleteMatch::GetKeywordUIState(), GetPopupSelection(), OmniboxClient::GetTemplateURLService(), AutocompleteMatch::inline_autocompletion, is_keyword_hint(), OmniboxPopupSelection::IsButtonFocused(), keyword(), OmniboxPopupSelection::KEYWORD_MODE, OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, AutocompleteResult::match_at(), old_focused_url_, OnPopupDataChanged(), OmniboxPopupView::OnSelectionChanged(), popup_selection_, popup_view_, AutocompleteMatch::prefix_autocompletion, OmniboxPopupView::ProvideButtonFocusHint(), result(), SetAccessibilityLabel(), AutocompleteMatch::split_autocompletion, OmniboxPopupSelection::state, and AutocompleteController::Stop().
Referenced by AcceptKeyword(), OmniboxSuggestionButtonRowView::ButtonPressed(), OmniboxController::ClearPopupKeywordMode(), OmniboxViewViews::OnMousePressed(), OnUpOrDownKeyPressed(), ResetPopupToInitialState(), OmniboxPopupContentsView::SetSelectedIndex(), StepPopupSelection(), TryDeletingPopupLine(), and OmniboxPopupContentsView::UnselectButton().
SetUserText()
void OmniboxEditModel::SetUserText (const std::u16string & text)
References has_temporary_text_, InternalSetUserText(), is_keyword_hint_, keyword_, keyword_mode_entry_method_, NONE, omnibox_controller_, paste_state_, and SetInputInProgress().
ShouldPreventElision()
bool OmniboxEditModel::ShouldPreventElision () const
References controller(), OmniboxEditController::GetLocationBarModel(), and LocationBarModel::ShouldPreventElision().
ShouldShowCurrentPageIcon()
bool OmniboxEditModel::ShouldShowCurrentPageIcon () const
References display_text_, OmniboxView::GetText(), PopupIsOpen(), url_for_editing_, user_input_in_progress(), and view_.
StartAutocomplete()
void OmniboxEditModel::StartAutocomplete (bool has_selected_text, bool prevent_inline_autocomplete)
References allow_exact_keyword_match_, client_, SplitAutocompletion::Empty(), GetPageClassification(), OmniboxView::GetSelectionBounds(), inline_autocompletion_, input_, is_keyword_selected(), just_deleted_text_, keyword_mode_entry_method_, MaybePrependKeyword(), NONE, omnibox_controller_, paste_state_, prefix_autocompletion_, AutocompleteInput::set_allow_exact_keyword_match(), AutocompleteInput::set_current_title(), AutocompleteInput::set_current_url(), AutocompleteInput::set_keyword_mode_entry_method(), AutocompleteInput::set_prefer_keyword(), AutocompleteInput::set_prevent_inline_autocomplete(), split_autocompletion_, user_text_, and view_.
Referenced by AcceptKeyword(), and UpdateInput().
StartZeroSuggestRequest()
void OmniboxEditModel::StartZeroSuggestRequest (bool user_clobbered_permanent_text = false)
References autocomplete_controller(), client_, GetPageClassification(), OmniboxView::GetText(), input_, PopupIsOpen(), query_in_progress(), AutocompleteInput::set_current_title(), AutocompleteInput::set_current_url(), AutocompleteInput::set_focus_type(), AutocompleteController::Start(), user_input_in_progress_, and view_.
Referenced by OmniboxViewViews::OnGestureEvent(), OmniboxViewViews::OnMousePressed(), OmniboxViewViews::SetFocus(), and UpdateInput().
StepPopupSelection()
OmniboxPopupSelection OmniboxEditModel::StepPopupSelection (OmniboxPopupSelection::Direction direction, OmniboxPopupSelection::Step step)
References AcceptKeyword(), ClearKeyword(), GetPopupSelection(), GetPrefService(), popup_selection_, popup_view_, result(), and SetPopupSelection().
Referenced by OmniboxViewViews::HandleEarlyTabActions(), and OmniboxViewViews::HandleKeyEvent().
StopAutocomplete()
void OmniboxEditModel::StopAutocomplete ()
References autocomplete_controller(), and AutocompleteController::Stop().
TriggerPopupSelectionAction()
bool OmniboxEditModel::TriggerPopupSelectionAction (OmniboxPopupSelection selection, base::TimeTicks timestamp = base::TimeTicks(), WindowOpenDisposition disposition = WindowOpenDisposition::CURRENT_TAB)
References ExecuteAction(), OmniboxPopupSelection::FOCUSED_BUTTON_ACTION, OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, OmniboxPopupSelection::FOCUSED_BUTTON_REMOVE_SUGGESTION, OmniboxPopupSelection::FOCUSED_BUTTON_TAB_SWITCH, GetPopupSelection(), GetPrefService(), omnibox::HIDDEN, AutocompleteResult::IsSuggestionGroupIdHidden(), OmniboxPopupSelection::line, AutocompleteResult::match_at(), OpenMatch(), popup_view_, result(), omnibox::SetSuggestionGroupVisibility(), omnibox::SHOWN, OmniboxPopupSelection::state, and TryDeletingPopupLine().
Referenced by OmniboxResultView::ButtonPressed(), OmniboxSuggestionButtonRowView::ButtonPressed(), OmniboxRowView::HeaderView::HeaderToggleButtonPressed(), and OmniboxRowView::HeaderView::OnMouseReleased().
TryDeletingPopupLine()
void OmniboxEditModel::TryDeletingPopupLine (size_t line)
References autocomplete_controller(), AutocompleteController::DeleteMatch(), GetPopupSelection(), OmniboxPopupSelection::kNoMatch, OmniboxPopupSelection::line, AutocompleteResult::match_at(), OmniboxPopupSelection::NORMAL, popup_view_, result(), SetPopupSelection(), AutocompleteController::Stop(), and AutocompleteMatch::SupportsDeletion().
Referenced by OmniboxViewViews::HandleKeyEvent(), and TriggerPopupSelectionAction().
Unelide()
bool OmniboxEditModel::Unelide ()
References controller(), OmniboxEditController::GetLocationBarModel(), OmniboxView::GetText(), InternalSetUserText(), OmniboxView::SelectAll(), OmniboxView::SetWindowTextAndCaretPos(), url_for_editing_, user_input_in_progress(), and view_.
Referenced by OmniboxViewViews::SetFocus().
UpdateInput()
void OmniboxEditModel::UpdateInput (bool has_selected_text, bool prevent_inline_autocomplete)
References has_focus(), is_keyword_selected(), NotifyObserversInputInProgress(), SetInputInProgressNoNotify(), StartAutocomplete(), StartZeroSuggestRequest(), and user_text_.
Referenced by OmniboxViewViews::UpdatePopup().
user_input_in_progress()
bool OmniboxEditModel::user_input_in_progress () const inline
References user_input_in_progress_.
Referenced by AcceptInput(), GetInfoForCurrentText(), ShouldShowCurrentPageIcon(), and Unelide().
WillHandleEscapeKey()
bool OmniboxEditModel::WillHandleEscapeKey () const
References has_temporary_text_, and user_input_in_progress_.
Referenced by OmniboxViewViews::SkipDefaultKeyEventProcessing().
Friends And Related Function Documentation
OmniboxControllerTest
friend class OmniboxControllerTest friend
Member Data Documentation
allow_exact_keyword_match_
bool OmniboxEditModel::allow_exact_keyword_match_ private
Referenced by OnAfterPossibleChange(), and StartAutocomplete().
client_
std::unique_ptr<OmniboxClient> OmniboxEditModel::client_ private
Referenced by AcceptInput(), AcceptTemporaryTextAsUserText(), AdjustTextForCopy(), CanPasteAndGo(), ClassifyString(), client(), CurrentMatch(), EnterKeywordModeForDefaultSearchProvider(), GetDataForURLExport(), GetInfoForCurrentText(), NotifyObserversInputInProgress(), OmniboxEditModel(), OnChanged(), OnCurrentMatchChanged(), OnEscapeKeyPressed(), OnSetFocus(), OnWillKillFocus(), OpenMatch(), PasteAndGo(), Revert(), SetFocusState(), StartAutocomplete(), and StartZeroSuggestRequest().
control_key_state_
ControlKeyState OmniboxEditModel::control_key_state_ private
Referenced by AcceptInput(), ConsumeCtrlKey(), OnControlKeyChanged(), OnKillFocus(), and OnSetFocus().
controller_
OmniboxEditController* OmniboxEditModel::controller_ private
Referenced by controller(), ExecuteAction(), NotifyObserversInputInProgress(), OnChanged(), and OpenMatch().
display_text_
std::u16string OmniboxEditModel::display_text_ private
Referenced by AdjustTextForCopy(), GetPermanentDisplayText(), ResetDisplayTexts(), and ShouldShowCurrentPageIcon().
focus_resulted_in_navigation_
bool OmniboxEditModel::focus_resulted_in_navigation_ private
Referenced by OnKillFocus(), OnSetFocus(), and OpenMatch().
focus_source_
OmniboxFocusSource OmniboxEditModel::focus_source_ = OmniboxFocusSource::INVALID private
Referenced by focus_source(), GetPageClassification(), GetStateForTabSwitch(), OnAfterPossibleChange(), OnKillFocus(), RestoreState(), and set_focus_source().
focus_state_
OmniboxFocusState OmniboxEditModel::focus_state_ private
Referenced by focus_state(), GetStateForTabSwitch(), has_focus(), is_caret_visible(), OnAfterPossibleChange(), RestoreState(), SetCaretVisibility(), and SetFocusState().
has_temporary_text_
bool OmniboxEditModel::has_temporary_text_ private
Referenced by AcceptInput(), AcceptKeyword(), AcceptTemporaryTextAsUserText(), OnAfterPossibleChange(), OnCurrentMatchChanged(), OnEscapeKeyPressed(), OnPopupDataChanged(), OnUpOrDownKeyPressed(), Revert(), RevertTemporaryTextAndPopup(), SetUserText(), and WillHandleEscapeKey().
in_revert_
bool OmniboxEditModel::in_revert_ private
Referenced by AcceptTemporaryTextAsUserText(), ExecuteAction(), NotifyObserversInputInProgress(), OnSetFocus(), OnWillKillFocus(), and OpenMatch().
inline_autocompletion_
std::u16string OmniboxEditModel::inline_autocompletion_ private
Referenced by InternalSetUserText(), OnAfterPossibleChange(), OnPopupDataChanged(), and StartAutocomplete().
input_
AutocompleteInput OmniboxEditModel::input_ private
Referenced by AcceptInput(), CurrentMatch(), GetInfoForCurrentText(), GetStateForTabSwitch(), InExplicitExperimentalKeywordMode(), OnPopupDataChanged(), OpenMatch(), PasteAndGo(), RestoreState(), Revert(), RevertTemporaryTextAndPopup(), StartAutocomplete(), and StartZeroSuggestRequest().
is_keyword_hint_
bool OmniboxEditModel::is_keyword_hint_ private
Referenced by AcceptKeyword(), ClearKeyword(), EnterKeywordModeForDefaultSearchProvider(), GetStateForTabSwitch(), is_keyword_hint(), is_keyword_selected(), MaybeAcceptKeywordBySpace(), OnPopupDataChanged(), RestoreState(), Revert(), and SetUserText().
just_deleted_text_
bool OmniboxEditModel::just_deleted_text_ private
Referenced by InternalSetUserText(), OnAfterPossibleChange(), OpenMatch(), RevertTemporaryTextAndPopup(), and StartAutocomplete().
kCutOrCopyAllTextHistogram
const char OmniboxEditModel::kCutOrCopyAllTextHistogram static
Initial value:
=
    "Omnibox.CutOrCopyAllText"
Referenced by OmniboxViewViews::OnAfterCutOrCopy().
keyword_
std::u16string OmniboxEditModel::keyword_ private
Referenced by AcceptKeyword(), ClearKeyword(), EnterKeywordModeForDefaultSearchProvider(), GetStateForTabSwitch(), InExplicitExperimentalKeywordMode(), is_keyword_selected(), keyword(), MaybeAcceptKeywordBySpace(), MaybePrependKeyword(), OnPopupDataChanged(), RestoreState(), Revert(), and SetUserText().
keyword_mode_entry_method_
metrics::OmniboxEventProto::KeywordModeEntryMethod OmniboxEditModel::keyword_mode_entry_method_ private
Referenced by AcceptKeyword(), ClearKeyword(), EnterKeywordModeForDefaultSearchProvider(), GetStateForTabSwitch(), OnAfterPossibleChange(), OnPopupDataChanged(), OpenMatch(), RestoreState(), Revert(), SetUserText(), and StartAutocomplete().
last_omnibox_focus_
base::TimeTicks OmniboxEditModel::last_omnibox_focus_ private
Referenced by OnKillFocus(), OnSetFocus(), OpenMatch(), and SetInputInProgressNoNotify().
old_focused_url_
GURL OmniboxEditModel::old_focused_url_ private
Referenced by OnPopupResultChanged(), set_popup_view(), and SetPopupSelection().
omnibox_controller_
std::unique_ptr<OmniboxController> OmniboxEditModel::omnibox_controller_ private
Referenced by autocomplete_controller(), ClearKeyword(), CurrentMatch(), OmniboxEditModel(), OnCurrentMatchChanged(), OnPopupDataChanged(), result(), SetUserText(), and StartAutocomplete().
original_user_text_with_keyword_
std::u16string OmniboxEditModel::original_user_text_with_keyword_ private
Referenced by AcceptKeyword(), InternalSetUserText(), OnCurrentMatchChanged(), and OnPopupDataChanged().
paste_state_
PasteState OmniboxEditModel::paste_state_ private
Referenced by AcceptInput(), CreatedKeywordSearchByInsertingSpaceInMiddle(), is_pasting(), OnAfterPossibleChange(), OnKillFocus(), OnPaste(), Revert(), SetUserText(), and StartAutocomplete().
popup_selection_
OmniboxPopupSelection OmniboxEditModel::popup_selection_ private
Initial value:
=
      OmniboxPopupSelection(OmniboxPopupSelection::kNoMatch,
                            OmniboxPopupSelection::NORMAL)
Referenced by GetPopupAccessibilityLabelForCurrentSelection(), GetPopupSelection(), OnPopupResultChanged(), OnUpOrDownKeyPressed(), set_popup_view(), SetPopupSelection(), and StepPopupSelection().
popup_view_
OmniboxPopupView* OmniboxEditModel::popup_view_ = nullptr private
Referenced by AcceptInput(), ClearKeyword(), get_popup_view(), GetInfoForCurrentText(), GetPopupAccessibilityLabelForCurrentSelection(), GetPopupRichSuggestionBitmap(), GetPopupSelection(), IsPopupControlPresentOnMatch(), IsPopupSelectionOnInitialLine(), OnFaviconFetched(), OnPopupResultChanged(), PopupIsOpen(), ResetPopupToInitialState(), set_popup_view(), SetPopupRichSuggestionBitmap(), SetPopupSelection(), StepPopupSelection(), TriggerPopupSelectionAction(), and TryDeletingPopupLine().
prefix_autocompletion_
std::u16string OmniboxEditModel::prefix_autocompletion_ private
Referenced by InternalSetUserText(), OnAfterPossibleChange(), OnPopupDataChanged(), and StartAutocomplete().
rich_suggestion_bitmaps_
std::map<int, SkBitmap> OmniboxEditModel::rich_suggestion_bitmaps_ private
Referenced by GetPopupRichSuggestionBitmap(), OnPopupResultChanged(), set_popup_view(), and SetPopupRichSuggestionBitmap().
split_autocompletion_
SplitAutocompletion OmniboxEditModel::split_autocompletion_ private
Referenced by InternalSetUserText(), OnAfterPossibleChange(), OnPopupDataChanged(), and StartAutocomplete().
time_user_first_modified_omnibox_
base::TimeTicks OmniboxEditModel::time_user_first_modified_omnibox_ private
Referenced by OpenMatch(), and SetInputInProgressNoNotify().
url_for_editing_
std::u16string OmniboxEditModel::url_for_editing_ private
Referenced by AcceptInput(), AdjustTextForCopy(), GetInfoForCurrentText(), MaybeStartQueryForPopup(), OpenMatch(), ResetDisplayTexts(), ShouldShowCurrentPageIcon(), and Unelide().
url_for_remembered_user_selection_
std::u16string OmniboxEditModel::url_for_remembered_user_selection_ private
user_input_in_progress_
bool OmniboxEditModel::user_input_in_progress_ private
Referenced by AcceptTemporaryTextAsUserText(), AdjustTextForCopy(), CurrentTextIsURL(), EnterKeywordModeForDefaultSearchProvider(), GetStateForTabSwitch(), MaybeStartQueryForPopup(), NotifyObserversInputInProgress(), OnChanged(), OnEscapeKeyPressed(), OnPopupDataChanged(), OnSetFocus(), OnUpOrDownKeyPressed(), OnWillKillFocus(), OpenMatch(), ResetDisplayTexts(), RevertTemporaryTextAndPopup(), SetInputInProgressNoNotify(), StartZeroSuggestRequest(), user_input_in_progress(), and WillHandleEscapeKey().
user_input_since_focus_
bool OmniboxEditModel::user_input_since_focus_ private
Referenced by OnSetFocus(), and SetInputInProgressNoNotify().
user_text_
std::u16string OmniboxEditModel::user_text_ private
Referenced by AcceptKeyword(), GetStateForTabSwitch(), GetUserTextForTesting(), InternalSetUserText(), OnAfterPossibleChange(), OnChanged(), OnCurrentMatchChanged(), OnPopupDataChanged(), OpenMatch(), StartAutocomplete(), and UpdateInput().
view_
OmniboxView* OmniboxEditModel::view_ private
Referenced by AcceptInput(), AcceptKeyword(), AcceptTemporaryTextAsUserText(), ClearAdditionalText(), ClearKeyword(), EnterKeywordModeForDefaultSearchProvider(), ExecuteAction(), GetInfoForCurrentText(), GetStateForTabSwitch(), InternalSetUserText(), MaybeStartQueryForPopup(), OnAfterPossibleChange(), OnEscapeKeyPressed(), OnKillFocus(), OnPopupDataChanged(), OpenMatch(), PasteAndGo(), RestoreState(), Revert(), RevertTemporaryTextAndPopup(), SetAccessibilityLabel(), SetFocusState(), ShouldShowCurrentPageIcon(), StartAutocomplete(), StartZeroSuggestRequest(), and Unelide().
weak_factory_
base::WeakPtrFactory<OmniboxEditModel> OmniboxEditModel::weak_factory_ {this} private
Referenced by GetMatchIcon().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_edit_model.h
components/omnibox/browser/omnibox_edit_model.cc