Chromium Omnibox: OmniboxView Class Reference
OmniboxView Class Reference abstract
#include <omnibox_view.h>
Classes
struct State
struct StateChanges
Public Types
using IconFetchedCallback = base::OnceCallback< void(const gfx::Image &icon)>
Public Member Functions
virtual ~OmniboxView ()
OmniboxView (const OmniboxView &)=delete
OmniboxView & operator= (const OmniboxView &)=delete
OmniboxEditModel * model ()
const OmniboxEditModel * model () const
virtual void Update ()=0
virtual void OpenMatch (const AutocompleteMatch &match, WindowOpenDisposition disposition, const GURL &alternate_nav_url, const std::u16string &pasted_text, size_t selected_line, base::TimeTicks match_selection_timestamp)
virtual std::u16string GetText () const =0
bool IsEditingOrEmpty () const
ui::ImageModel GetIcon (int dip_size, SkColor color, IconFetchedCallback on_icon_fetched) const
void SetUserText (const std::u16string &text)
virtual void SetUserText (const std::u16string &text, bool update_popup)
virtual void SetWindowTextAndCaretPos (const std::u16string &text, size_t caret_pos, bool update_popup, bool notify_text_changed)=0
virtual void SetCaretPos (size_t caret_pos)=0
virtual void SetAdditionalText (const std::u16string &text)=0
virtual void EnterKeywordModeForDefaultSearchProvider ()=0
virtual bool IsSelectAll () const =0
virtual void GetSelectionBounds (size_t *start, size_t *end) const =0
virtual size_t GetAllSelectionsLength () const =0
virtual void SelectAll (bool reversed)=0
virtual void RevertAll ()
virtual void UpdatePopup ()=0
virtual void CloseOmniboxPopup ()
virtual void SetFocus (bool is_user_initiated)=0
virtual void ApplyCaretVisibility ()=0
virtual void SetAccessibilityLabel (const std::u16string &display_text, const AutocompleteMatch &match, bool notify_text_changed)
virtual void OnTemporaryTextMaybeChanged (const std::u16string &display_text, const AutocompleteMatch &match, bool save_original_selection, bool notify_text_changed)=0
virtual void OnInlineAutocompleteTextMaybeChanged (const std::u16string &display_text, std::vector< gfx::Range > selections, const std::u16string &prefix_autocompletion, const std::u16string &inline_autocompletion)=0
virtual void OnInlineAutocompleteTextCleared ()=0
virtual void OnRevertTemporaryText (const std::u16string &display_text, const AutocompleteMatch &match)=0
virtual void OnBeforePossibleChange ()=0
virtual bool OnAfterPossibleChange (bool allow_keyword_ui_change)=0
virtual gfx::NativeView GetNativeView () const =0
virtual gfx::NativeView GetRelativeWindowForPopup () const =0
virtual bool IsImeComposing () const =0
virtual bool IsImeShowingPopup () const
virtual void ShowVirtualKeyboardIfEnabled ()
virtual void HideImeIfNeeded ()
virtual bool IsIndicatingQueryRefinement () const
Static Public Member Functions
static std::u16string StripJavascriptSchemas (const std::u16string &text)
static std::u16string SanitizeTextForPaste (const std::u16string &text)
Protected Member Functions
OmniboxView (OmniboxEditController *controller, std::unique_ptr< OmniboxClient > client)
void GetState (State *state)
StateChanges GetStateChanges (const State &before, const State &after)
virtual void TextChanged ()
virtual int GetOmniboxTextLength () const =0
virtual void EmphasizeURLComponents ()=0
OmniboxEditController * controller ()
const OmniboxEditController * controller () const
virtual void SetEmphasis (bool emphasize, const gfx::Range &range)=0
virtual void UpdateSchemeStyle (const gfx::Range &range)=0
void UpdateTextStyle (const std::u16string &display_text, const bool text_is_url, const AutocompleteSchemeClassifier &classifier)
Private Attributes
std::unique_ptr< OmniboxEditModel > model_
OmniboxEditController * controller_
Friends
class OmniboxViewMacTest
class TestOmniboxView
Member Typedef Documentation
IconFetchedCallback
using OmniboxView::IconFetchedCallback = base::OnceCallback<void(const gfx::Image& icon)>
Constructor & Destructor Documentation
~OmniboxView()
OmniboxView::~OmniboxView () virtual default
OmniboxView() [1/2]
OmniboxView::OmniboxView (const OmniboxView &) delete
OmniboxView() [2/2]
OmniboxView::OmniboxView (OmniboxEditController * controller, std::unique_ptr< OmniboxClient > client) protected
References controller(), model_, and OmniboxEditModel::OmniboxEditModel().
Member Function Documentation
ApplyCaretVisibility()
virtual void OmniboxView::ApplyCaretVisibility () pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::SetFocusState().
CloseOmniboxPopup()
void OmniboxView::CloseOmniboxPopup () virtual
References model_.
Referenced by OmniboxViewViews::OnBlur(), OmniboxViewViews::OnMouseDragged(), and RevertAll().
controller() [1/2]
OmniboxEditController* OmniboxView::controller () inline protected
References controller_.
Referenced by OmniboxView(), OmniboxViewViews::OnMousePressed(), and OmniboxViewViews::UpdateSchemeStyle().
controller() [2/2]
const OmniboxEditController* OmniboxView::controller () const inline protected
References controller_.
EmphasizeURLComponents()
virtual void OmniboxView::EmphasizeURLComponents () protected pure virtual
Implemented in OmniboxViewViews.
Referenced by TextChanged().
EnterKeywordModeForDefaultSearchProvider()
virtual void OmniboxView::EnterKeywordModeForDefaultSearchProvider () pure virtual
Implemented in OmniboxViewViews.
GetAllSelectionsLength()
virtual size_t OmniboxView::GetAllSelectionsLength () const pure virtual
Implemented in OmniboxViewViews.
Referenced by GetState().
GetIcon()
ui::ImageModel OmniboxView::GetIcon (int dip_size, SkColor color, IconFetchedCallback on_icon_fetched) const
References controller_, AutocompleteMatch::destination_url, OmniboxEditController::GetLocationBarModel(), AutocompleteMatch::GetVectorIcon(), AutocompleteMatch::IsSearchType(), model_, AutocompleteMatch::type, and AutocompleteMatchType::URL_WHAT_YOU_TYPED.
GetNativeView()
virtual gfx::NativeView OmniboxView::GetNativeView () const pure virtual
Implemented in OmniboxViewViews.
GetOmniboxTextLength()
virtual int OmniboxView::GetOmniboxTextLength () const protected pure virtual
Implemented in OmniboxViewViews.
Referenced by IsEditingOrEmpty().
GetRelativeWindowForPopup()
virtual gfx::NativeView OmniboxView::GetRelativeWindowForPopup () const pure virtual
Implemented in OmniboxViewViews.
GetSelectionBounds()
virtual void OmniboxView::GetSelectionBounds (size_t * start, size_t * end) const pure virtual
Referenced by GetState(), OmniboxEditModel::Revert(), and OmniboxEditModel::StartAutocomplete().
GetState()
void OmniboxView::GetState (State * state) protected
References OmniboxView::State::all_sel_length, GetAllSelectionsLength(), GetSelectionBounds(), GetText(), OmniboxEditModel::is_keyword_selected(), OmniboxView::State::is_keyword_selected, OmniboxEditModel::keyword(), OmniboxView::State::keyword, model(), OmniboxView::State::sel_end, OmniboxView::State::sel_start, and OmniboxView::State::text.
Referenced by OmniboxViewViews::OnAfterPossibleChange(), and OmniboxViewViews::OnBeforePossibleChange().
GetStateChanges()
OmniboxView::StateChanges OmniboxView::GetStateChanges (const State & before, const State & after) protected
References OmniboxView::State::all_sel_length, OmniboxView::State::is_keyword_selected, OmniboxView::StateChanges::just_deleted_text, OmniboxView::State::keyword, OmniboxView::StateChanges::keyword_differs, OmniboxView::StateChanges::new_sel_end, OmniboxView::StateChanges::new_sel_start, OmniboxView::StateChanges::new_text, OmniboxView::StateChanges::old_text, OmniboxView::State::sel_end, OmniboxView::State::sel_start, OmniboxView::StateChanges::selection_differs, OmniboxView::State::text, and OmniboxView::StateChanges::text_differs.
Referenced by OmniboxViewViews::OnAfterPossibleChange().
GetText()
virtual std::u16string OmniboxView::GetText () const pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::AcceptInput(), OmniboxEditModel::AcceptTemporaryTextAsUserText(), OmniboxEditModel::ClearKeyword(), OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider(), OmniboxEditModel::GetInfoForCurrentText(), GetState(), OmniboxEditModel::GetStateForTabSwitch(), OmniboxEditModel::SetAccessibilityLabel(), OmniboxEditModel::ShouldShowCurrentPageIcon(), OmniboxEditModel::StartZeroSuggestRequest(), and OmniboxEditModel::Unelide().
HideImeIfNeeded()
void OmniboxView::HideImeIfNeeded () virtual
Reimplemented in OmniboxViewViews.
Referenced by OmniboxEditModel::OnKillFocus().
IsEditingOrEmpty()
bool OmniboxView::IsEditingOrEmpty () const
References GetOmniboxTextLength(), and model_.
IsImeComposing()
virtual bool OmniboxView::IsImeComposing () const pure virtual
Implemented in OmniboxViewViews.
IsImeShowingPopup()
bool OmniboxView::IsImeShowingPopup () const virtual
Reimplemented in OmniboxViewViews.
IsIndicatingQueryRefinement()
bool OmniboxView::IsIndicatingQueryRefinement () const virtual
IsSelectAll()
virtual bool OmniboxView::IsSelectAll () const pure virtual
Implemented in OmniboxViewViews.
model() [1/2]
OmniboxEditModel* OmniboxView::model () inline
References model_.
Referenced by OmniboxViewViews::ApplyCaretVisibility(), OmniboxViewViews::DoInsertChar(), OmniboxViewViews::EmphasizeURLComponents(), OmniboxViewViews::EnterKeywordModeForDefaultSearchProvider(), OmniboxViewViews::ExecuteCommand(), OmniboxViewViews::ExecuteTextEditCommand(), OmniboxViewViews::GetAccessibleNodeData(), OmniboxViewViews::GetLabelForCommandId(), GetState(), OmniboxViewViews::HandleAccessibleAction(), OmniboxViewViews::HandleEarlyTabActions(), OmniboxViewViews::HandleKeyEvent(), OmniboxViewViews::Init(), OmniboxViewViews::InstallPlaceholderText(), OmniboxViewViews::IsCommandIdEnabled(), OmniboxViewViews::OnAfterCutOrCopy(), OmniboxViewViews::OnAfterPossibleChange(), OmniboxViewViews::OnBlur(), OmniboxViewViews::OnFocus(), OmniboxViewViews::OnGestureEvent(), OmniboxViewViews::OnGetDragOperationsForTextfield(), OmniboxViewViews::OnMousePressed(), OmniboxViewViews::OnOmniboxPaste(), OmniboxViewViews::OnTabChanged(), OmniboxViewViews::OnWriteDragData(), OmniboxViewViews::SaveStateToTab(), OmniboxViewViews::SetAccessibilityLabel(), OmniboxViewViews::SetFocus(), OmniboxViewViews::ShouldShowPlaceholderText(), OmniboxViewViews::SkipDefaultKeyEventProcessing(), OmniboxViewViews::UnapplySteadyStateElisions(), OmniboxViewViews::Update(), OmniboxViewViews::UpdatePopup(), OmniboxViewViews::UpdateSchemeStyle(), and UpdateTextStyle().
model() [2/2]
const OmniboxEditModel* OmniboxView::model () const inline
References model_.
OnAfterPossibleChange()
virtual bool OmniboxView::OnAfterPossibleChange (bool allow_keyword_ui_change) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::ClearKeyword().
OnBeforePossibleChange()
virtual void OmniboxView::OnBeforePossibleChange () pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::ClearKeyword().
OnInlineAutocompleteTextCleared()
virtual void OmniboxView::OnInlineAutocompleteTextCleared () pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::InternalSetUserText(), and OmniboxEditModel::OnPopupDataChanged().
OnInlineAutocompleteTextMaybeChanged()
virtual void OmniboxView::OnInlineAutocompleteTextMaybeChanged (const std::u16string & display_text, std::vector< gfx::Range > selections, const std::u16string & prefix_autocompletion, const std::u16string & inline_autocompletion) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::OnPopupDataChanged().
OnRevertTemporaryText()
virtual void OmniboxView::OnRevertTemporaryText (const std::u16string & display_text, const AutocompleteMatch & match) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::RevertTemporaryTextAndPopup().
OnTemporaryTextMaybeChanged()
virtual void OmniboxView::OnTemporaryTextMaybeChanged (const std::u16string & display_text, const AutocompleteMatch & match, bool save_original_selection, bool notify_text_changed) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::AcceptKeyword(), and OmniboxEditModel::OnPopupDataChanged().
OpenMatch()
void OmniboxView::OpenMatch (const AutocompleteMatch & match, WindowOpenDisposition disposition, const GURL & alternate_nav_url, const std::u16string & pasted_text, size_t selected_line, base::TimeTicks match_selection_timestamp) virtual
References AutocompleteMatch::destination_url, and model_.
Referenced by OmniboxEditModel::AcceptInput(), OmniboxPopupContentsView::OpenMatch(), and OmniboxEditModel::PasteAndGo().
operator=()
OmniboxView& OmniboxView::operator= (const OmniboxView &) delete
RevertAll()
void OmniboxView::RevertAll () virtual
Reimplemented in OmniboxViewViews.
References CloseOmniboxPopup(), model_, and TextChanged().
Referenced by OmniboxEditModel::ExecuteAction(), OmniboxEditModel::OnEscapeKeyPressed(), OmniboxEditModel::OpenMatch(), OmniboxEditModel::PasteAndGo(), OmniboxEditModel::RestoreState(), and OmniboxViewViews::RevertAll().
SanitizeTextForPaste()
std::u16string OmniboxView::SanitizeTextForPaste (const std::u16string & text) static
Referenced by GetClipboardText(), OmniboxViewViews::GetSelectionClipboardText(), and LLVMFuzzerTestOneInput().
SelectAll()
virtual void OmniboxView::SelectAll (bool reversed) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider(), OmniboxEditModel::OnEscapeKeyPressed(), and OmniboxEditModel::Unelide().
SetAccessibilityLabel()
virtual void OmniboxView::SetAccessibilityLabel (const std::u16string & display_text, const AutocompleteMatch & match, bool notify_text_changed) inline virtual
Reimplemented in OmniboxViewViews.
Referenced by OmniboxEditModel::SetAccessibilityLabel().
SetAdditionalText()
virtual void OmniboxView::SetAdditionalText (const std::u16string & text) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::ClearAdditionalText(), and OmniboxEditModel::OnPopupDataChanged().
SetCaretPos()
virtual void OmniboxView::SetCaretPos (size_t caret_pos) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::Revert().
SetEmphasis()
virtual void OmniboxView::SetEmphasis (bool emphasize, const gfx::Range & range) protected pure virtual
Implemented in OmniboxViewViews.
Referenced by UpdateTextStyle().
SetFocus()
virtual void OmniboxView::SetFocus (bool is_user_initiated) pure virtual
Implemented in OmniboxViewViews.
SetUserText() [1/2]
void OmniboxView::SetUserText (const std::u16string & text)
Referenced by OmniboxEditModel::RestoreState(), and OmniboxViewViews::SetUserText().
SetUserText() [2/2]
void OmniboxView::SetUserText (const std::u16string & text, bool update_popup) virtual
Reimplemented in OmniboxViewViews.
References model_, and SetWindowTextAndCaretPos().
SetWindowTextAndCaretPos()
virtual void OmniboxView::SetWindowTextAndCaretPos (const std::u16string & text, size_t caret_pos, bool update_popup, bool notify_text_changed) pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::ClearKeyword(), OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider(), OmniboxEditModel::OnPopupDataChanged(), OmniboxEditModel::RestoreState(), OmniboxEditModel::Revert(), OmniboxEditModel::RevertTemporaryTextAndPopup(), SetUserText(), and OmniboxEditModel::Unelide().
ShowVirtualKeyboardIfEnabled()
void OmniboxView::ShowVirtualKeyboardIfEnabled () virtual
Reimplemented in OmniboxViewViews.
StripJavascriptSchemas()
std::u16string OmniboxView::StripJavascriptSchemas (const std::u16string & text) static
Referenced by GetClipboardText(), and OmniboxViewViews::PerformDrop().
TextChanged()
void OmniboxView::TextChanged () protected virtual
References EmphasizeURLComponents(), and model_.
Referenced by OmniboxViewViews::HandleAccessibleAction(), OmniboxViewViews::HandleKeyEvent(), OmniboxViewViews::OnAfterPossibleChange(), OmniboxViewViews::OnMousePressed(), OmniboxViewViews::OnMouseReleased(), RevertAll(), and OmniboxViewViews::SetWindowTextAndCaretPos().
Update()
virtual void OmniboxView::Update () pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::OnEscapeKeyPressed().
UpdatePopup()
virtual void OmniboxView::UpdatePopup () pure virtual
Implemented in OmniboxViewViews.
Referenced by OmniboxEditModel::AcceptKeyword(), OmniboxEditModel::MaybeStartQueryForPopup(), and OmniboxEditModel::OnAfterPossibleChange().
UpdateSchemeStyle()
virtual void OmniboxView::UpdateSchemeStyle (const gfx::Range & range) protected pure virtual
Implemented in OmniboxViewViews.
Referenced by UpdateTextStyle().
UpdateTextStyle()
void OmniboxView::UpdateTextStyle (const std::u16string & display_text, const bool text_is_url, const AutocompleteSchemeClassifier & classifier) protected
References model(), AutocompleteInput::ParseForEmphasizeComponents(), SetEmphasis(), and UpdateSchemeStyle().
Referenced by OmniboxViewViews::EmphasizeURLComponents().
Friends And Related Function Documentation
OmniboxViewMacTest
friend class OmniboxViewMacTest friend
TestOmniboxView
friend class TestOmniboxView friend
Member Data Documentation
controller_
OmniboxEditController* OmniboxView::controller_ private
Referenced by controller(), and GetIcon().
model_
std::unique_ptr<OmniboxEditModel> OmniboxView::model_ private
Referenced by CloseOmniboxPopup(), GetIcon(), IsEditingOrEmpty(), model(), OmniboxView(), OpenMatch(), RevertAll(), SetUserText(), and TextChanged().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_view.h
components/omnibox/browser/omnibox_view.cc