Chromium Omnibox: AutocompleteProviderListener Class Reference
AutocompleteProviderListener Class Reference abstract
#include <autocomplete_provider_listener.h>
Public Member Functions
virtual void OnProviderUpdate (bool updated_matches)=0
Protected Member Functions
virtual ~AutocompleteProviderListener ()
Constructor & Destructor Documentation
~AutocompleteProviderListener()
virtual AutocompleteProviderListener::~AutocompleteProviderListener () inline protected virtual
Member Function Documentation
OnProviderUpdate()
virtual void AutocompleteProviderListener::OnProviderUpdate (bool updated_matches) pure virtual
Implemented in AutocompleteController.
Referenced by ClipboardProvider::AddImageMatchCallback(), QueryTileProvider::BuildSuggestion(), MostVisitedSitesProvider::OnMostVisitedUrlsAvailable(), ClipboardProvider::OnReceiveClipboardContent(), SearchProvider::OnTemplateURLServiceChanged(), DocumentProvider::OnURLLoadComplete(), SearchProvider::OnURLLoadComplete(), ZeroSuggestProvider::OnURLLoadComplete(), MostVisitedSitesProvider::OnURLsAvailable(), HistoryURLProvider::QueryComplete(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), SearchProvider::Run(), and OnDeviceHeadProvider::SearchDone().
The documentation for this class was generated from the following file:
components/omnibox/browser/autocomplete_provider_listener.h