Chromium Omnibox: HistoryQuickProvider Class Reference
HistoryQuickProvider Class Reference
#include <history_quick_provider.h>
Public Member Functions
HistoryQuickProvider (AutocompleteProviderClient *client)
HistoryQuickProvider (const HistoryQuickProvider &)=delete
HistoryQuickProvider & operator= (const HistoryQuickProvider &)=delete
void Start (const AutocompleteInput &input, bool minimal_changes) override
size_t EstimateMemoryUsage () const override
Public Member Functions inherited from HistoryProvider
void DeleteMatch (const AutocompleteMatch &match) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static void set_disabled (bool disabled)
Static Public Member Functions inherited from HistoryProvider
static ACMatchClassifications SpansFromTermMatch (const TermMatches &matches, size_t text_length, bool is_url)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, Spans)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, Relevance)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, DoTrimHttpScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, DontTrimHttpSchemeIfInputHasScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, DontTrimHttpSchemeIfInputMatches)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, DontTrimHttpsSchemeIfInputHasScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, DoTrimHttpsScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest, CorrectAutocompleteWithTrailingSlash)
~HistoryQuickProvider () override
void DoAutocomplete ()
int FindMaxMatchScore (const ScoredHistoryMatches &matches)
AutocompleteMatch QuickMatchToACMatch (const ScoredHistoryMatch &history_match, int score)
Private Attributes
AutocompleteInput autocomplete_input_
InMemoryURLIndex * in_memory_url_index_
Static Private Attributes
static bool disabled_ = false
Friends
class HistoryQuickProviderTest
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from HistoryProvider
HistoryProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
~HistoryProvider () override
HistoryProvider (const HistoryProvider &)=delete
HistoryProvider & operator= (const HistoryProvider &)=delete
void DeleteMatchFromMatches (const AutocompleteMatch &match)
AutocompleteProviderClient * client () const
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
HistoryQuickProvider() [1/2]
HistoryQuickProvider::HistoryQuickProvider (AutocompleteProviderClient * client) explicit
HistoryQuickProvider() [2/2]
HistoryQuickProvider::HistoryQuickProvider (const HistoryQuickProvider &) delete
~HistoryQuickProvider()
HistoryQuickProvider::~HistoryQuickProvider () override private
Member Function Documentation
DoAutocomplete()
void HistoryQuickProvider::DoAutocomplete () private
References autocomplete_input_, AutocompleteInput::cursor_position(), FindMaxMatchScore(), InMemoryURLIndex::HistoryItemsForTerms(), in_memory_url_index_, AutocompleteProvider::matches(), AutocompleteProvider::matches_, AutocompleteProvider::provider_max_matches_, QuickMatchToACMatch(), ScoredHistoryMatch::raw_score, and AutocompleteInput::text().
Referenced by Start().
EstimateMemoryUsage()
size_t HistoryQuickProvider::EstimateMemoryUsage () const override virtual
Reimplemented from AutocompleteProvider.
References autocomplete_input_, AutocompleteProvider::EstimateMemoryUsage(), and base::trace_event::EstimateMemoryUsage().
FindMaxMatchScore()
int HistoryQuickProvider::FindMaxMatchScore (const ScoredHistoryMatches & matches) private
References autocomplete_input_, AutocompleteInput::canonicalized_url(), HistoryProvider::client(), AutocompleteProviderClient::GetHistoryService(), HistoryURLProvider::kScoreForBestInlineableResult, HistoryURLProvider::kScoreForUnvisitedIntranetResult, HistoryURLProvider::kScoreForWhatYouTypedResult, AutocompleteProvider::matches(), AutocompleteInput::parts(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by DoAutocomplete().
FRIEND_TEST_ALL_PREFIXES() [1/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , CorrectAutocompleteWithTrailingSlash) private
FRIEND_TEST_ALL_PREFIXES() [2/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , DontTrimHttpSchemeIfInputHasScheme) private
FRIEND_TEST_ALL_PREFIXES() [3/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , DontTrimHttpSchemeIfInputMatches) private
FRIEND_TEST_ALL_PREFIXES() [4/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , DontTrimHttpsSchemeIfInputHasScheme) private
FRIEND_TEST_ALL_PREFIXES() [5/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , DoTrimHttpScheme) private
FRIEND_TEST_ALL_PREFIXES() [6/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , DoTrimHttpsScheme) private
FRIEND_TEST_ALL_PREFIXES() [7/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , Relevance) private
FRIEND_TEST_ALL_PREFIXES() [8/8]
HistoryQuickProvider::FRIEND_TEST_ALL_PREFIXES (HistoryQuickProviderTest , Spans) private
operator=()
HistoryQuickProvider& HistoryQuickProvider::operator= (const HistoryQuickProvider &) delete
QuickMatchToACMatch()
AutocompleteMatch HistoryQuickProvider::QuickMatchToACMatch (const ScoredHistoryMatch & history_match, int score) private
References AutocompleteProviderClient::AllowDeletingBrowserHistory(), autocomplete_input_, ClassifyTermMatches(), HistoryProvider::client(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, FindTermMatches(), AutocompleteProvider::FixupUserInput(), AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::GetFormatTypes(), URLPrefix::GetInlineAutocompleteOffset(), AutocompleteMatchType::HISTORY_TITLE, AutocompleteMatchType::HISTORY_URL, AutocompleteMatch::inline_autocompletion, AutocompleteMatch::ACMatchClassification::MATCH, history::HistoryMatch::match_in_scheme, history::HistoryMatch::match_in_subdomain, AutocompleteMatch::ACMatchClassification::NONE, AutocompleteInput::parts(), AutocompleteMatch::RecordAdditionalInfo(), AutocompleteMatch::SetAllowedToBeDefault(), AutocompleteInput::text(), AutocompleteMatch::TryRichAutocompletion(), AutocompleteMatch::typed_count, AutocompleteMatch::ACMatchClassification::URL, history::HistoryMatch::url_info, and ScoredHistoryMatch::url_matches.
Referenced by DoAutocomplete().
set_disabled()
static void HistoryQuickProvider::set_disabled (bool disabled) inline static
References disabled_.
Start()
void HistoryQuickProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References autocomplete_input_, omnibox::DEFAULT, disabled_, DoAutocomplete(), AutocompleteInput::focus_type(), in_memory_url_index_, AutocompleteProvider::matches_, and AutocompleteInput::type().
Friends And Related Function Documentation
HistoryQuickProviderTest
friend class HistoryQuickProviderTest friend
Member Data Documentation
autocomplete_input_
AutocompleteInput HistoryQuickProvider::autocomplete_input_ private
Referenced by DoAutocomplete(), EstimateMemoryUsage(), FindMaxMatchScore(), QuickMatchToACMatch(), and Start().
disabled_
bool HistoryQuickProvider::disabled_ = false static private
Referenced by set_disabled(), and Start().
in_memory_url_index_
InMemoryURLIndex* HistoryQuickProvider::in_memory_url_index_ private
Referenced by DoAutocomplete(), and Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/history_quick_provider.h
components/omnibox/browser/history_quick_provider.cc