Chromium Omnibox: HistoryURLProvider Class Reference
HistoryURLProvider Class Reference
#include <history_url_provider.h>
Classes
class VisitClassifier
Public Member Functions
HistoryURLProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
HistoryURLProvider (const HistoryURLProvider &)=delete
HistoryURLProvider & operator= (const HistoryURLProvider &)=delete
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
size_t EstimateMemoryUsage () const override
void ExecuteWithDB (HistoryURLProviderParams *params, history::HistoryBackend *backend, history::URLDatabase *db)
Public Member Functions inherited from HistoryProvider
void DeleteMatch (const AutocompleteMatch &match) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Attributes
static const int kScoreForBestInlineableResult = 1413
static const int kScoreForUnvisitedIntranetResult = 1403
static const int kScoreForWhatYouTypedResult = 1203
static const int kBaseScoreForNonInlineableResult = 900
Private Types
enum MatchType { NORMAL , WHAT_YOU_TYPED , INLINE_AUTOCOMPLETE , UNVISITED_INTRANET }
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, HUPScoringExperiment)
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, DoTrimHttpScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, DontTrimHttpSchemeIfInputHasScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, DontTrimHttpSchemeIfInputMatchesInScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, DontTrimHttpsSchemeIfInputMatchesInScheme)
FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest, DoTrimHttpsScheme)
~HistoryURLProvider () override
void DoAutocomplete (history::HistoryBackend *backend, history::URLDatabase *db, HistoryURLProviderParams *params)
void PromoteMatchesIfNecessary (const HistoryURLProviderParams &params)
void QueryComplete (HistoryURLProviderParams *params_gets_deleted)
bool FixupExactSuggestion (history::URLDatabase *db, const VisitClassifier &classifier, HistoryURLProviderParams *params) const
GURL AsKnownIntranetURL (history::URLDatabase *db, const AutocompleteInput &input) const
bool PromoteOrCreateShorterSuggestion (history::URLDatabase *db, HistoryURLProviderParams *params)
void CullPoorMatches (HistoryURLProviderParams *params) const
void CullRedirects (history::HistoryBackend *backend, history::HistoryMatches *matches, size_t max_results) const
size_t RemoveSubsequentMatchesOf (history::HistoryMatches *matches, size_t source_index, const std::vector< GURL > &remove) const
AutocompleteMatch HistoryMatchToACMatch (const HistoryURLProviderParams &params, size_t match_number, int relevance)
Static Private Member Functions
static int CalculateRelevance (MatchType match_type, int match_number)
static ACMatchClassifications ClassifyDescription (const std::u16string &input_text, const std::u16string &description)
Private Attributes
AutocompleteProviderListener * listener_
HistoryURLProviderParams * params_
bool search_url_database_
HUPScoringParams scoring_params_
base::ThreadChecker thread_checker_
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from HistoryProvider
static ACMatchClassifications SpansFromTermMatch (const TermMatches &matches, size_t text_length, bool is_url)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from HistoryProvider
HistoryProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
~HistoryProvider () override
HistoryProvider (const HistoryProvider &)=delete
HistoryProvider & operator= (const HistoryProvider &)=delete
void DeleteMatchFromMatches (const AutocompleteMatch &match)
AutocompleteProviderClient * client () const
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Member Enumeration Documentation
MatchType
enum HistoryURLProvider::MatchType private
Enumerator
NORMAL
WHAT_YOU_TYPED
INLINE_AUTOCOMPLETE
UNVISITED_INTRANET
Constructor & Destructor Documentation
HistoryURLProvider() [1/2]
HistoryURLProvider::HistoryURLProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener)
References OmniboxFieldTrial::GetDefaultHUPScoringParams(), OmniboxFieldTrial::GetExperimentalHUPScoringParams(), and scoring_params_.
HistoryURLProvider() [2/2]
HistoryURLProvider::HistoryURLProvider (const HistoryURLProvider &) delete
~HistoryURLProvider()
HistoryURLProvider::~HistoryURLProvider () override private
Member Function Documentation
AsKnownIntranetURL()
GURL HistoryURLProvider::AsKnownIntranetURL (history::URLDatabase * db, const AutocompleteInput & input) const private
References AutocompleteInput::canonicalized_url(), AutocompleteInput::parts(), AutocompleteInput::scheme(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by FixupExactSuggestion(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
CalculateRelevance()
int HistoryURLProvider::CalculateRelevance (MatchType match_type, int match_number) static private
References INLINE_AUTOCOMPLETE, kBaseScoreForNonInlineableResult, kScoreForBestInlineableResult, kScoreForUnvisitedIntranetResult, kScoreForWhatYouTypedResult, UNVISITED_INTRANET, and WHAT_YOU_TYPED.
Referenced by FixupExactSuggestion(), PromoteMatchesIfNecessary(), QueryComplete(), and Start().
ClassifyDescription()
ACMatchClassifications HistoryURLProvider::ClassifyDescription (const std::u16string & input_text, const std::u16string & description) static private
References ClassifyTermMatches(), FindTermMatches(), AutocompleteMatch::ACMatchClassification::MATCH, and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by FixupExactSuggestion(), and HistoryMatchToACMatch().
CullPoorMatches()
void HistoryURLProvider::CullPoorMatches (HistoryURLProviderParams * params) const private
References HistoryURLProviderParams::default_search_provider, HistoryURLProviderParams::matches, and HistoryURLProviderParams::search_terms_data.
Referenced by DoAutocomplete().
CullRedirects()
void HistoryURLProvider::CullRedirects (history::HistoryBackend * backend, history::HistoryMatches * matches, size_t max_results) const private
References AutocompleteProvider::matches(), and RemoveSubsequentMatchesOf().
Referenced by DoAutocomplete().
DoAutocomplete()
void HistoryURLProvider::DoAutocomplete (history::HistoryBackend * backend, history::URLDatabase * db, HistoryURLProviderParams * params) private
References URLPrefix::BestURLPrefix(), HistoryURLProviderParams::cancel_flag, CullPoorMatches(), CullRedirects(), HistoryURLProviderParams::default_search_provider, AutocompleteMatch::destination_url, HistoryURLProviderParams::exact_suggestion_is_in_history, FixupExactSuggestion(), HistoryURLProviderParams::FRONT_HISTORY_MATCH, AutocompleteMatch::GetMatchComponents(), URLPrefix::GetURLPrefixes(), HistoryURLProviderParams::have_what_you_typed_match, history::HistoryMatch::innermost_match, HistoryURLProviderParams::input, history::HistoryMatch::input_location, history::HistoryMatch::match_in_scheme, history::HistoryMatch::match_in_subdomain, HistoryURLProviderParams::matches, HistoryURLProviderParams::NEITHER, URLPrefix::num_components, AutocompleteInput::NumNonHostComponents(), AutocompleteInput::parts(), HistoryURLProviderParams::promote_type, PromoteOrCreateShorterSuggestion(), AutocompleteProvider::provider_max_matches_, search_url_database_, AutocompleteInput::text(), HistoryURLProviderParams::trim_http, AutocompleteInput::type(), HistoryURLProvider::VisitClassifier::type(), HistoryURLProvider::VisitClassifier::UNVISITED_INTRANET, history::HistoryMatch::url_info, HistoryURLProviderParams::WHAT_YOU_TYPED_MATCH, and HistoryURLProviderParams::what_you_typed_match.
Referenced by ExecuteWithDB(), and Start().
EstimateMemoryUsage()
size_t HistoryURLProvider::EstimateMemoryUsage () const override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::EstimateMemoryUsage(), base::trace_event::EstimateMemoryUsage(), params_, and scoring_params_.
ExecuteWithDB()
void HistoryURLProvider::ExecuteWithDB (HistoryURLProviderParams * params, history::HistoryBackend * backend, history::URLDatabase * db)
References HistoryURLProviderParams::cancel_flag, DoAutocomplete(), HistoryURLProviderParams::failed, HistoryURLProviderParams::origin_task_runner, and QueryComplete().
Referenced by Start().
FixupExactSuggestion()
bool HistoryURLProvider::FixupExactSuggestion (history::URLDatabase * db, const VisitClassifier & classifier, HistoryURLProviderParams * params) const private
References HistoryURLProviderParams::allow_deleting_browser_history, AutocompleteMatch::allowed_to_be_default_match, AsKnownIntranetURL(), CalculateRelevance(), ClassifyDescription(), AutocompleteMatch::deletable, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::destination_url, INLINE_AUTOCOMPLETE, HistoryURLProviderParams::input, HistoryURLProvider::VisitClassifier::INVALID, HistoryURLProviderParams::matches, AutocompleteMatch::relevance, AutocompleteInput::text(), AutocompleteInput::type(), AutocompleteProvider::type(), HistoryURLProvider::VisitClassifier::type(), HistoryURLProvider::VisitClassifier::UNVISITED_INTRANET, UNVISITED_INTRANET, HistoryURLProvider::VisitClassifier::url_row(), HistoryURLProvider::VisitClassifier::VISITED, WHAT_YOU_TYPED, and HistoryURLProviderParams::what_you_typed_match.
Referenced by DoAutocomplete().
FRIEND_TEST_ALL_PREFIXES() [1/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , DontTrimHttpSchemeIfInputHasScheme) private
FRIEND_TEST_ALL_PREFIXES() [2/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , DontTrimHttpSchemeIfInputMatchesInScheme) private
FRIEND_TEST_ALL_PREFIXES() [3/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , DontTrimHttpsSchemeIfInputMatchesInScheme) private
FRIEND_TEST_ALL_PREFIXES() [4/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , DoTrimHttpScheme) private
FRIEND_TEST_ALL_PREFIXES() [5/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , DoTrimHttpsScheme) private
FRIEND_TEST_ALL_PREFIXES() [6/6]
HistoryURLProvider::FRIEND_TEST_ALL_PREFIXES (HistoryURLProviderTest , HUPScoringExperiment) private
HistoryMatchToACMatch()
AutocompleteMatch HistoryURLProvider::HistoryMatchToACMatch (const HistoryURLProviderParams & params, size_t match_number, int relevance) private
References AutocompleteProviderClient::AllowDeletingBrowserHistory(), ClassifyDescription(), ClassifyTermMatches(), HistoryProvider::client(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, FindTermMatches(), AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::GetFormatTypes(), AutocompleteMatchType::HISTORY_URL, AutocompleteMatch::inline_autocompletion, HistoryURLProviderParams::input, HistoryURLProviderParams::input_before_fixup, history::HistoryMatch::input_location, AutocompleteMatch::ACMatchClassification::MATCH, history::HistoryMatch::match_in_scheme, history::HistoryMatch::match_in_subdomain, HistoryURLProviderParams::matches, AutocompleteInput::parts(), AutocompleteMatch::SetAllowedToBeDefault(), AutocompleteInput::text(), thread_checker_, HistoryURLProviderParams::trim_http, AutocompleteMatch::TryRichAutocompletion(), AutocompleteMatch::typed_count, AutocompleteMatch::ACMatchClassification::URL, and history::HistoryMatch::url_info.
Referenced by PromoteMatchesIfNecessary(), and QueryComplete().
operator=()
HistoryURLProvider& HistoryURLProvider::operator= (const HistoryURLProvider &) delete
PromoteMatchesIfNecessary()
void HistoryURLProvider::PromoteMatchesIfNecessary (const HistoryURLProviderParams & params) private
References CalculateRelevance(), HistoryURLProviderParams::FRONT_HISTORY_MATCH, HistoryURLProviderParams::have_what_you_typed_match, HistoryMatchToACMatch(), INLINE_AUTOCOMPLETE, AutocompleteProvider::matches_, HistoryURLProviderParams::NEITHER, HistoryURLProviderParams::promote_type, HistoryURLProviderParams::WHAT_YOU_TYPED_MATCH, and HistoryURLProviderParams::what_you_typed_match.
Referenced by QueryComplete(), and Start().
PromoteOrCreateShorterSuggestion()
bool HistoryURLProvider::PromoteOrCreateShorterSuggestion (history::URLDatabase * db, HistoryURLProviderParams * params) private
References AutocompleteMatch::destination_url, HistoryURLProviderParams::have_what_you_typed_match, HistoryURLProviderParams::input, history::HistoryMatch::input_location, HistoryURLProviderParams::matches, AutocompleteInput::text(), history::HistoryMatch::url_info, and HistoryURLProviderParams::what_you_typed_match.
Referenced by DoAutocomplete().
QueryComplete()
void HistoryURLProvider::QueryComplete (HistoryURLProviderParams * params_gets_deleted) private
References CalculateRelevance(), AutocompleteProvider::done_, HistoryURLProviderParams::FRONT_HISTORY_MATCH, HistoryMatchToACMatch(), listener_, AutocompleteProvider::matches_, NORMAL, AutocompleteProviderListener::OnProviderUpdate(), params_, PromoteMatchesIfNecessary(), and scoring_params_.
Referenced by ExecuteWithDB().
RemoveSubsequentMatchesOf()
size_t HistoryURLProvider::RemoveSubsequentMatchesOf (history::HistoryMatches * matches, size_t source_index, const std::vector< GURL > & remove) const private
References history::HistoryMatch::EqualsGURL(), and AutocompleteProvider::matches().
Referenced by CullRedirects().
Start()
void HistoryURLProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References CalculateRelevance(), AutocompleteInput::canonicalized_url(), HistoryProvider::client(), AutocompleteMatch::contents_class, omnibox::DEFAULT, DoAutocomplete(), AutocompleteProvider::done_, ExecuteWithDB(), AutocompleteMatch::fill_into_edit, AutocompleteProvider::FixupUserInput(), AutocompleteInput::focus_type(), AutocompleteProviderClient::GetHistoryService(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteInput::HasHTTPScheme(), AutocompleteMatch::inline_autocompletion, AutocompleteProvider::matches_, params_, AutocompleteInput::prevent_inline_autocomplete(), PromoteMatchesIfNecessary(), AutocompleteMatch::relevance, search_url_database_, Stop(), AutocompleteInput::text(), AutocompleteInput::type(), AutocompleteInput::UpdateText(), AutocompleteMatch::ACMatchClassification::URL, VerbatimMatchForInput(), AutocompleteInput::want_asynchronous_matches(), and WHAT_YOU_TYPED.
Stop()
void HistoryURLProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References HistoryURLProviderParams::cancel_flag, AutocompleteProvider::done_, and params_.
Referenced by Start().
Member Data Documentation
kBaseScoreForNonInlineableResult
const int HistoryURLProvider::kBaseScoreForNonInlineableResult = 900 static
Referenced by CalculateRelevance(), and ScoredHistoryMatch::ScoredHistoryMatch().
kScoreForBestInlineableResult
const int HistoryURLProvider::kScoreForBestInlineableResult = 1413 static
Referenced by CalculateRelevance(), HistoryQuickProvider::FindMaxMatchScore(), and ScoredHistoryMatch::ScoredHistoryMatch().
kScoreForUnvisitedIntranetResult
const int HistoryURLProvider::kScoreForUnvisitedIntranetResult = 1403 static
Referenced by CalculateRelevance(), and HistoryQuickProvider::FindMaxMatchScore().
kScoreForWhatYouTypedResult
const int HistoryURLProvider::kScoreForWhatYouTypedResult = 1203 static
Referenced by CalculateRelevance(), and HistoryQuickProvider::FindMaxMatchScore().
listener_
AutocompleteProviderListener* HistoryURLProvider::listener_ private
Referenced by QueryComplete().
params_
HistoryURLProviderParams* HistoryURLProvider::params_ private
Referenced by EstimateMemoryUsage(), QueryComplete(), Start(), and Stop().
scoring_params_
HUPScoringParams HistoryURLProvider::scoring_params_ private
Referenced by EstimateMemoryUsage(), HistoryURLProvider(), and QueryComplete().
search_url_database_
bool HistoryURLProvider::search_url_database_ private
Referenced by DoAutocomplete(), and Start().
thread_checker_
base::ThreadChecker HistoryURLProvider::thread_checker_ private
Referenced by HistoryMatchToACMatch().
The documentation for this class was generated from the following files:
components/omnibox/browser/history_url_provider.h
components/omnibox/browser/history_url_provider.cc