Chromium Omnibox: BookmarkProvider Class Reference
BookmarkProvider Class Reference
#include <bookmark_provider.h>
Public Member Functions
BookmarkProvider (AutocompleteProviderClient *client)
BookmarkProvider (const BookmarkProvider &)=delete
BookmarkProvider & operator= (const BookmarkProvider &)=delete
void Start (const AutocompleteInput &input, bool minimal_changes) override
void set_bookmark_model_for_testing (bookmarks::BookmarkModel *bookmark_model)
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
~BookmarkProvider () override
void DoAutocomplete (const AutocompleteInput &input)
std::vector< bookmarks::TitledUrlMatch > GetMatchesWithBookmarkPaths (const AutocompleteInput &input, size_t kMaxBookmarkMatches)
query_parser::MatchingAlgorithm GetMatchingAlgorithm (AutocompleteInput input)
int CalculateBookmarkMatchRelevance (const bookmarks::TitledUrlMatch &match) const
void RemoveQueryParamKeyMatches (bookmarks::TitledUrlMatch &match)
Private Attributes
AutocompleteProviderClient * client_
bookmarks::BookmarkModel * bookmark_model_
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
BookmarkProvider() [1/2]
BookmarkProvider::BookmarkProvider (AutocompleteProviderClient * client) explicit
BookmarkProvider() [2/2]
BookmarkProvider::BookmarkProvider (const BookmarkProvider &) delete
~BookmarkProvider()
BookmarkProvider::~BookmarkProvider () override private
Member Function Documentation
CalculateBookmarkMatchRelevance()
int BookmarkProvider::CalculateBookmarkMatchRelevance (const bookmarks::TitledUrlMatch & match) const private
References bookmark_model_.
Referenced by DoAutocomplete().
DoAutocomplete()
void BookmarkProvider::DoAutocomplete (const AutocompleteInput & input) private
References bookmark_model_, AutocompleteMatchType::BOOKMARK_TITLE, CalculateBookmarkMatchRelevance(), client_, AutocompleteProvider::FixupUserInput(), GetMatchesWithBookmarkPaths(), AutocompleteProviderClient::GetSchemeClassifier(), AutocompleteProvider::matches(), AutocompleteProvider::matches_, AutocompleteMatch::MoreRelevant(), AutocompleteProvider::provider_max_matches_, RemoveQueryParamKeyMatches(), OmniboxFieldTrial::ShouldDisableCGIParamMatching(), and bookmarks::TitledUrlMatchToAutocompleteMatch().
Referenced by Start().
FRIEND_TEST_ALL_PREFIXES()
BookmarkProvider::FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest , InlineAutocompletion) private
GetMatchesWithBookmarkPaths()
std::vector< TitledUrlMatch > BookmarkProvider::GetMatchesWithBookmarkPaths (const AutocompleteInput & input, size_t kMaxBookmarkMatches) private
References bookmark_model_, client_, GetMatchingAlgorithm(), AutocompleteProviderClient::GetOmniboxTriggeredFeatureService(), OmniboxTriggeredFeatureService::kBookmarkPaths, omnibox::kBookmarkPaths, OmniboxFieldTrial::kBookmarkPathsCounterfactual, AutocompleteInput::text(), and OmniboxTriggeredFeatureService::TriggerFeature().
Referenced by DoAutocomplete().
GetMatchingAlgorithm()
query_parser::MatchingAlgorithm BookmarkProvider::GetMatchingAlgorithm (AutocompleteInput input) private
References client_, omnibox::DEFAULT, AutocompleteProviderClient::GetOmniboxTriggeredFeatureService(), OmniboxFieldTrial::IsShortBookmarkSuggestionsByTotalInputLengthEnabled(), OmniboxFieldTrial::IsShortBookmarkSuggestionsEnabled(), omnibox::kShortBookmarkSuggestionsByTotalInputLength, OmniboxFieldTrial::ShortBookmarkSuggestionsByTotalInputLengthThreshold(), AutocompleteInput::text(), and OmniboxTriggeredFeatureService::TriggerFeature().
Referenced by GetMatchesWithBookmarkPaths().
operator=()
BookmarkProvider& BookmarkProvider::operator= (const BookmarkProvider &) delete
RemoveQueryParamKeyMatches()
void BookmarkProvider::RemoveQueryParamKeyMatches (bookmarks::TitledUrlMatch & match) private
Referenced by DoAutocomplete().
set_bookmark_model_for_testing()
void BookmarkProvider::set_bookmark_model_for_testing (bookmarks::BookmarkModel * bookmark_model) inline
References bookmark_model_.
Start()
void BookmarkProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References omnibox::DEFAULT, DoAutocomplete(), AutocompleteInput::focus_type(), AutocompleteProvider::matches_, and AutocompleteInput::text().
Member Data Documentation
bookmark_model_
bookmarks::BookmarkModel* BookmarkProvider::bookmark_model_ private
Referenced by CalculateBookmarkMatchRelevance(), DoAutocomplete(), GetMatchesWithBookmarkPaths(), and set_bookmark_model_for_testing().
client_
AutocompleteProviderClient* BookmarkProvider::client_ private
Referenced by DoAutocomplete(), GetMatchesWithBookmarkPaths(), and GetMatchingAlgorithm().
The documentation for this class was generated from the following files:
components/omnibox/browser/bookmark_provider.h
components/omnibox/browser/bookmark_provider.cc