Chromium Omnibox: FaviconCache Class Reference
FaviconCache Class Reference
#include <favicon_cache.h>
Classes
struct Request
Public Member Functions
FaviconCache (favicon::FaviconService *favicon_service, history::HistoryService *history_service)
~FaviconCache () override
FaviconCache (const FaviconCache &)=delete
FaviconCache & operator= (const FaviconCache &)=delete
gfx::Image GetFaviconForPageUrl (const GURL &page_url, FaviconFetchedCallback on_favicon_fetched)
gfx::Image GetLargestFaviconForPageUrl (const GURL &page_url, FaviconFetchedCallback on_favicon_fetched)
gfx::Image GetFaviconForIconUrl (const GURL &icon_url, FaviconFetchedCallback on_favicon_fetched)
Private Types
enum class RequestType { BY_PAGE_URL , BY_ICON_URL , RAW_BY_PAGE_URL }
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest, ClearIconsWithHistoryDeletions)
FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest, ExpireNullFaviconsByHistory)
FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest, ObserveFaviconsChanged)
gfx::Image GetFaviconInternal (const Request &request, FaviconFetchedCallback on_favicon_fetched)
void OnFaviconFetched (const Request &request, const favicon_base::FaviconImageResult &result)
void OnFaviconRawBitmapFetched (const Request &request, const favicon_base::FaviconRawBitmapResult &bitmap_result)
void InvokeRequestCallbackWithFavicon (const Request &request, const gfx::Image &image)
void InvalidateCachedRequests (const Request &request)
void OnURLVisited (history::HistoryService *history_service, ui::PageTransition transition, const history::URLRow &row, const history::RedirectList &redirects, base::Time visit_time) override
void OnURLsDeleted (history::HistoryService *history_service, const history::DeletionInfo &deletion_info) override
void OnFaviconsChanged (const std::set< GURL > &page_urls, const GURL &icon_url)
Private Attributes
favicon::FaviconService * favicon_service_
base::ScopedObservation< history::HistoryService, history::HistoryServiceObserver > history_observation_ {this}
base::CancelableTaskTracker task_tracker_
std::map< Request, std::list< FaviconFetchedCallback > > pending_requests_
base::MRUCache< Request, gfx::Image > mru_cache_
base::MRUCache< Request, bool > responses_without_favicons_
base::CallbackListSubscription favicons_changed_subscription_
base::WeakPtrFactory< FaviconCache > weak_factory_ {this}
Member Enumeration Documentation
RequestType
enum FaviconCache::RequestType strong private
Enumerator
BY_PAGE_URL
BY_ICON_URL
RAW_BY_PAGE_URL
Constructor & Destructor Documentation
FaviconCache() [1/2]
FaviconCache::FaviconCache (favicon::FaviconService * favicon_service, history::HistoryService * history_service)
References favicons_changed_subscription_, history_observation_, OnFaviconsChanged(), and weak_factory_.
~FaviconCache()
FaviconCache::~FaviconCache () override
FaviconCache() [2/2]
FaviconCache::FaviconCache (const FaviconCache &) delete
Member Function Documentation
FRIEND_TEST_ALL_PREFIXES() [1/3]
FaviconCache::FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest , ClearIconsWithHistoryDeletions) private
FRIEND_TEST_ALL_PREFIXES() [2/3]
FaviconCache::FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest , ExpireNullFaviconsByHistory) private
FRIEND_TEST_ALL_PREFIXES() [3/3]
FaviconCache::FRIEND_TEST_ALL_PREFIXES (FaviconCacheTest , ObserveFaviconsChanged) private
GetFaviconForIconUrl()
gfx::Image FaviconCache::GetFaviconForIconUrl (const GURL & icon_url, FaviconFetchedCallback on_favicon_fetched)
References BY_ICON_URL, and GetFaviconInternal().
Referenced by ChromeOmniboxClient::GetFaviconForDefaultSearchProvider(), and ChromeOmniboxClient::GetFaviconForKeywordSearchProvider().
GetFaviconForPageUrl()
gfx::Image FaviconCache::GetFaviconForPageUrl (const GURL & page_url, FaviconFetchedCallback on_favicon_fetched)
References BY_PAGE_URL, and GetFaviconInternal().
Referenced by ChromeOmniboxClient::GetFaviconForPageUrl().
GetFaviconInternal()
gfx::Image FaviconCache::GetFaviconInternal (const Request & request, FaviconFetchedCallback on_favicon_fetched) private
References BY_ICON_URL, BY_PAGE_URL, favicon_service_, mru_cache_, OnFaviconFetched(), OnFaviconRawBitmapFetched(), pending_requests_, RAW_BY_PAGE_URL, responses_without_favicons_, task_tracker_, FaviconCache::Request::type, FaviconCache::Request::url, and weak_factory_.
Referenced by GetFaviconForIconUrl(), GetFaviconForPageUrl(), and GetLargestFaviconForPageUrl().
GetLargestFaviconForPageUrl()
gfx::Image FaviconCache::GetLargestFaviconForPageUrl (const GURL & page_url, FaviconFetchedCallback on_favicon_fetched)
References GetFaviconInternal(), and RAW_BY_PAGE_URL.
InvalidateCachedRequests()
void FaviconCache::InvalidateCachedRequests (const Request & request) private
References mru_cache_, and responses_without_favicons_.
Referenced by OnFaviconsChanged(), and OnURLsDeleted().
InvokeRequestCallbackWithFavicon()
void FaviconCache::InvokeRequestCallbackWithFavicon (const Request & request, const gfx::Image & image) private
References mru_cache_, and pending_requests_.
Referenced by OnFaviconFetched(), and OnFaviconRawBitmapFetched().
OnFaviconFetched()
void FaviconCache::OnFaviconFetched (const Request & request, const favicon_base::FaviconImageResult & result) private
References InvokeRequestCallbackWithFavicon(), pending_requests_, and responses_without_favicons_.
Referenced by GetFaviconInternal().
OnFaviconRawBitmapFetched()
void FaviconCache::OnFaviconRawBitmapFetched (const Request & request, const favicon_base::FaviconRawBitmapResult & bitmap_result) private
References InvokeRequestCallbackWithFavicon(), pending_requests_, and responses_without_favicons_.
Referenced by GetFaviconInternal().
OnFaviconsChanged()
void FaviconCache::OnFaviconsChanged (const std::set< GURL > & page_urls, const GURL & icon_url) private
References BY_ICON_URL, BY_PAGE_URL, and InvalidateCachedRequests().
Referenced by FaviconCache().
OnURLsDeleted()
void FaviconCache::OnURLsDeleted (history::HistoryService * history_service, const history::DeletionInfo & deletion_info) override private
References BY_PAGE_URL, InvalidateCachedRequests(), mru_cache_, and responses_without_favicons_.
OnURLVisited()
void FaviconCache::OnURLVisited (history::HistoryService * history_service, ui::PageTransition transition, const history::URLRow & row, const history::RedirectList & redirects, base::Time visit_time) override private
References BY_PAGE_URL, and responses_without_favicons_.
operator=()
FaviconCache& FaviconCache::operator= (const FaviconCache &) delete
Member Data Documentation
favicon_service_
favicon::FaviconService* FaviconCache::favicon_service_ private
Referenced by GetFaviconInternal().
favicons_changed_subscription_
base::CallbackListSubscription FaviconCache::favicons_changed_subscription_ private
Referenced by FaviconCache().
history_observation_
base::ScopedObservation<history::HistoryService, history::HistoryServiceObserver> FaviconCache::history_observation_ {this} private
Referenced by FaviconCache().
mru_cache_
base::MRUCache<Request, gfx::Image> FaviconCache::mru_cache_ private
Referenced by GetFaviconInternal(), InvalidateCachedRequests(), InvokeRequestCallbackWithFavicon(), and OnURLsDeleted().
pending_requests_
std::map<Request, std::list<FaviconFetchedCallback> > FaviconCache::pending_requests_ private
Referenced by GetFaviconInternal(), InvokeRequestCallbackWithFavicon(), OnFaviconFetched(), and OnFaviconRawBitmapFetched().
responses_without_favicons_
base::MRUCache<Request, bool> FaviconCache::responses_without_favicons_ private
Referenced by GetFaviconInternal(), InvalidateCachedRequests(), OnFaviconFetched(), OnFaviconRawBitmapFetched(), OnURLsDeleted(), and OnURLVisited().
task_tracker_
base::CancelableTaskTracker FaviconCache::task_tracker_ private
Referenced by GetFaviconInternal().
weak_factory_
base::WeakPtrFactory<FaviconCache> FaviconCache::weak_factory_ {this} private
Referenced by FaviconCache(), and GetFaviconInternal().
The documentation for this class was generated from the following files:
components/omnibox/browser/favicon_cache.h
components/omnibox/browser/favicon_cache.cc