Chromium Omnibox: OmniboxClient Class Reference
OmniboxClient Class Reference abstract
#include <omnibox_client.h>
Public Member Functions
virtual ~OmniboxClient ()
virtual std::unique_ptr< AutocompleteProviderClient > CreateAutocompleteProviderClient ()=0
virtual bool CurrentPageExists () const
virtual const GURL & GetURL () const
virtual const std::u16string & GetTitle () const
virtual gfx::Image GetFavicon () const
virtual bool IsLoading () const
virtual bool IsPasteAndGoEnabled () const
virtual bool IsDefaultSearchProviderEnabled () const
virtual const SessionID & GetSessionID () const =0
virtual bookmarks::BookmarkModel * GetBookmarkModel ()
virtual OmniboxControllerEmitter * GetOmniboxControllerEmitter ()
virtual TemplateURLService * GetTemplateURLService ()
virtual const AutocompleteSchemeClassifier & GetSchemeClassifier () const =0
virtual AutocompleteClassifier * GetAutocompleteClassifier ()
virtual bool ShouldDefaultTypedNavigationsToHttps () const =0
virtual int GetHttpsPortForTesting () const =0
virtual gfx::Image GetIconIfExtensionMatch (const AutocompleteMatch &match) const
virtual gfx::Image GetSizedIcon (const gfx::VectorIcon &vector_icon_type, SkColor vector_icon_color) const
virtual gfx::Image GetSizedIcon (const gfx::Image &icon) const
virtual bool ProcessExtensionKeyword (const std::u16string &text, const TemplateURL *template_url, const AutocompleteMatch &match, WindowOpenDisposition disposition)
virtual void OnInputStateChanged ()
virtual void OnFocusChanged (OmniboxFocusState state, OmniboxFocusChangeReason reason)
virtual void OnResultChanged (const AutocompleteResult &result, bool default_match_changed, const BitmapFetchedCallback &on_bitmap_fetched)
virtual gfx::Image GetFaviconForPageUrl (const GURL &page_url, FaviconFetchedCallback on_favicon_fetched)
virtual gfx::Image GetFaviconForDefaultSearchProvider (FaviconFetchedCallback on_favicon_fetched)
virtual gfx::Image GetFaviconForKeywordSearchProvider (const TemplateURL *template_url, FaviconFetchedCallback on_favicon_fetched)
virtual void OnTextChanged (const AutocompleteMatch &current_match, bool user_input_in_progress, const std::u16string &user_text, const AutocompleteResult &result, bool has_focus)
virtual void OnInputAccepted (const AutocompleteMatch &match)
virtual void OnRevert ()
virtual void OnURLOpenedFromOmnibox (OmniboxLog *log)
virtual void OnBookmarkLaunched ()
virtual void DiscardNonCommittedNavigations ()
virtual void OpenUpdateChromeDialog ()
Constructor & Destructor Documentation
~OmniboxClient()
virtual OmniboxClient::~OmniboxClient () inline virtual
Member Function Documentation
CreateAutocompleteProviderClient()
virtual std::unique_ptr<AutocompleteProviderClient> OmniboxClient::CreateAutocompleteProviderClient () pure virtual
Implemented in ChromeOmniboxClient.
CurrentPageExists()
bool OmniboxClient::CurrentPageExists () const virtual
Reimplemented in ChromeOmniboxClient.
DiscardNonCommittedNavigations()
virtual void OmniboxClient::DiscardNonCommittedNavigations () inline virtual
Reimplemented in ChromeOmniboxClient.
GetAutocompleteClassifier()
AutocompleteClassifier * OmniboxClient::GetAutocompleteClassifier () virtual
Reimplemented in ChromeOmniboxClient.
GetBookmarkModel()
bookmarks::BookmarkModel * OmniboxClient::GetBookmarkModel () virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxEditModel::IsStarredMatch().
GetFavicon()
gfx::Image OmniboxClient::GetFavicon () const virtual
Reimplemented in ChromeOmniboxClient.
GetFaviconForDefaultSearchProvider()
gfx::Image OmniboxClient::GetFaviconForDefaultSearchProvider (FaviconFetchedCallback on_favicon_fetched) virtual
Reimplemented in ChromeOmniboxClient.
GetFaviconForKeywordSearchProvider()
gfx::Image OmniboxClient::GetFaviconForKeywordSearchProvider (const TemplateURL * template_url, FaviconFetchedCallback on_favicon_fetched) virtual
Reimplemented in ChromeOmniboxClient.
GetFaviconForPageUrl()
gfx::Image OmniboxClient::GetFaviconForPageUrl (const GURL & page_url, FaviconFetchedCallback on_favicon_fetched) virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxEditModel::GetMatchIcon().
GetHttpsPortForTesting()
int OmniboxClient::GetHttpsPortForTesting () const pure virtual
Implemented in ChromeOmniboxClient.
GetIconIfExtensionMatch()
gfx::Image OmniboxClient::GetIconIfExtensionMatch (const AutocompleteMatch & match) const virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxEditModel::GetMatchIcon().
GetOmniboxControllerEmitter()
OmniboxControllerEmitter * OmniboxClient::GetOmniboxControllerEmitter () virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxController::OmniboxController().
GetSchemeClassifier()
virtual const AutocompleteSchemeClassifier& OmniboxClient::GetSchemeClassifier () const pure virtual
Implemented in ChromeOmniboxClient.
GetSessionID()
virtual const SessionID& OmniboxClient::GetSessionID () const pure virtual
Implemented in ChromeOmniboxClient.
GetSizedIcon() [1/2]
gfx::Image OmniboxClient::GetSizedIcon (const gfx::Image & icon) const virtual
Reimplemented in ChromeOmniboxClient.
GetSizedIcon() [2/2]
gfx::Image OmniboxClient::GetSizedIcon (const gfx::VectorIcon & vector_icon_type, SkColor vector_icon_color) const virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxEditModel::GetMatchIcon().
GetTemplateURLService()
TemplateURLService * OmniboxClient::GetTemplateURLService () virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxViewViews::InstallPlaceholderText(), OmniboxEditModel::SetPopupSelection(), and OmniboxSuggestionButtonRowView::UpdateFromModel().
GetTitle()
const std::u16string & OmniboxClient::GetTitle () const virtual
Reimplemented in ChromeOmniboxClient.
GetURL()
const GURL & OmniboxClient::GetURL () const virtual
Reimplemented in ChromeOmniboxClient.
IsDefaultSearchProviderEnabled()
bool OmniboxClient::IsDefaultSearchProviderEnabled () const virtual
Reimplemented in ChromeOmniboxClient.
IsLoading()
bool OmniboxClient::IsLoading () const virtual
Reimplemented in ChromeOmniboxClient.
IsPasteAndGoEnabled()
bool OmniboxClient::IsPasteAndGoEnabled () const virtual
Reimplemented in ChromeOmniboxClient.
OnBookmarkLaunched()
virtual void OmniboxClient::OnBookmarkLaunched () inline virtual
Reimplemented in ChromeOmniboxClient.
OnFocusChanged()
virtual void OmniboxClient::OnFocusChanged (OmniboxFocusState state, OmniboxFocusChangeReason reason) inline virtual
Reimplemented in ChromeOmniboxClient.
OnInputAccepted()
virtual void OmniboxClient::OnInputAccepted (const AutocompleteMatch & match) inline virtual
OnInputStateChanged()
virtual void OmniboxClient::OnInputStateChanged () inline virtual
Reimplemented in ChromeOmniboxClient.
OnResultChanged()
virtual void OmniboxClient::OnResultChanged (const AutocompleteResult & result, bool default_match_changed, const BitmapFetchedCallback & on_bitmap_fetched) inline virtual
Reimplemented in ChromeOmniboxClient.
Referenced by OmniboxController::OnResultChanged().
OnRevert()
virtual void OmniboxClient::OnRevert () inline virtual
Reimplemented in ChromeOmniboxClient.
OnTextChanged()
virtual void OmniboxClient::OnTextChanged (const AutocompleteMatch & current_match, bool user_input_in_progress, const std::u16string & user_text, const AutocompleteResult & result, bool has_focus) inline virtual
Reimplemented in ChromeOmniboxClient.
OnURLOpenedFromOmnibox()
virtual void OmniboxClient::OnURLOpenedFromOmnibox (OmniboxLog * log) inline virtual
Reimplemented in ChromeOmniboxClient.
OpenUpdateChromeDialog()
virtual void OmniboxClient::OpenUpdateChromeDialog () inline virtual
Reimplemented in ChromeOmniboxClient.
ProcessExtensionKeyword()
bool OmniboxClient::ProcessExtensionKeyword (const std::u16string & text, const TemplateURL * template_url, const AutocompleteMatch & match, WindowOpenDisposition disposition) virtual
Reimplemented in ChromeOmniboxClient.
ShouldDefaultTypedNavigationsToHttps()
bool OmniboxClient::ShouldDefaultTypedNavigationsToHttps () const pure virtual
Implemented in ChromeOmniboxClient.
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_client.h
components/omnibox/browser/omnibox_client.cc