Chromium Omnibox: components/omnibox/browser/autocomplete_match_classification.h File Reference
autocomplete_match_classification.h File Reference
#include "components/omnibox/browser/autocomplete_match.h"
#include "components/omnibox/browser/in_memory_url_index_types.h"
Functions
TermMatches FindTermMatches (std::u16string find_text, std::u16string text, bool allow_prefix_matching=true, bool allow_mid_word_matching=false)
ACMatchClassifications ClassifyTermMatches (TermMatches matches, size_t text_length, int match_style, int non_match_style)
Function Documentation
ClassifyTermMatches()
ACMatchClassifications ClassifyTermMatches (TermMatches matches, size_t text_length, int match_style, int non_match_style)
Referenced by SearchSuggestionParser::NavigationResult::CalculateAndClassifyMatchContents(), DocumentProvider::Classify(), AutocompleteProvider::ClassifyAllMatchesInString(), SearchSuggestionParser::NavigationResult::ClassifyDescription(), HistoryURLProvider::ClassifyDescription(), HistoryURLProvider::HistoryMatchToACMatch(), ZeroSuggestProvider::NavigationToMatch(), HistoryQuickProvider::QuickMatchToACMatch(), HistoryProvider::SpansFromTermMatch(), BuiltinProvider::Start(), bookmarks::TitledUrlMatchToAutocompleteMatch(), and VerbatimMatchForInput().
FindTermMatches()
TermMatches FindTermMatches (std::u16string find_text, std::u16string text, bool allow_prefix_matching = true, bool allow_mid_word_matching = false)
References DeoverlapMatches(), ScoredHistoryMatch::FilterTermMatchesByWordStarts(), MatchTermsInString(), SortMatches(), and String16VectorFromString16().
Referenced by SearchSuggestionParser::NavigationResult::CalculateAndClassifyMatchContents(), DocumentProvider::Classify(), AutocompleteProvider::ClassifyAllMatchesInString(), SearchSuggestionParser::NavigationResult::ClassifyDescription(), HistoryURLProvider::ClassifyDescription(), HistoryURLProvider::HistoryMatchToACMatch(), HistoryQuickProvider::QuickMatchToACMatch(), and bookmarks::TitledUrlMatchToAutocompleteMatch().