Chromium Omnibox: base::trace_event Namespace Reference
base::trace_event Namespace Reference
Functions
size_t EstimateMemoryUsage (const OmniboxAction::LabelStrings &self)
Function Documentation
EstimateMemoryUsage()
size_t base::trace_event::EstimateMemoryUsage (const OmniboxAction::LabelStrings & self)
Referenced by OmniboxAction::EstimateMemoryUsage(), OmniboxPedal::TokenSequence::EstimateMemoryUsage(), OmniboxPedal::SynonymGroup::EstimateMemoryUsage(), OmniboxPedalProvider::EstimateMemoryUsage(), AutocompleteInput::EstimateMemoryUsage(), AutocompleteMatch::EstimateMemoryUsage(), AutocompleteProvider::EstimateMemoryUsage(), AutocompleteResult::EstimateMemoryUsage(), history::HistoryMatch::EstimateMemoryUsage(), HistoryURLProviderParams::EstimateMemoryUsage(), HistoryInfoMapValue::EstimateMemoryUsage(), RowWordStarts::EstimateMemoryUsage(), HUPScoringParams::ScoreBuckets::EstimateMemoryUsage(), HUPScoringParams::EstimateMemoryUsage(), SuggestionAnswer::TextField::EstimateMemoryUsage(), SuggestionAnswer::ImageLine::EstimateMemoryUsage(), SuggestionAnswer::EstimateMemoryUsage(), URLIndexPrivateData::EstimateMemoryUsage(), URLIndexPrivateData::SearchTermCacheItem::EstimateMemoryUsage(), OmniboxPedal::EstimateMemoryUsage(), HistoryQuickProvider::EstimateMemoryUsage(), SearchTermsDataSnapshot::EstimateMemoryUsage(), HistoryURLProvider::EstimateMemoryUsage(), and InMemoryURLIndex::OnMemoryDump().