Chromium Omnibox: TailoredWordBreakIterator Class Reference
TailoredWordBreakIterator Class Reference
#include <tailored_word_break_iterator.h>
Public Member Functions
TailoredWordBreakIterator (const base::StringPiece16 &str, base::i18n::BreakIterator::BreakType break_type)
~TailoredWordBreakIterator ()
TailoredWordBreakIterator (const TailoredWordBreakIterator &)=delete
TailoredWordBreakIterator & operator= (const TailoredWordBreakIterator &)=delete
bool Advance ()
bool IsWord () const
base::StringPiece16 GetStringPiece () const
std::u16string GetString () const
size_t prev () const
size_t pos () const
Private Member Functions
bool HasUnderscoreWord () const
void AdvanceInUnderscoreWord ()
Private Attributes
size_t prev_
size_t pos_
base::StringPiece16 underscore_word_
Constructor & Destructor Documentation
TailoredWordBreakIterator() [1/2]
TailoredWordBreakIterator::TailoredWordBreakIterator (const base::StringPiece16 & str, base::i18n::BreakIterator::BreakType break_type)
~TailoredWordBreakIterator()
TailoredWordBreakIterator::~TailoredWordBreakIterator ()
TailoredWordBreakIterator() [2/2]
TailoredWordBreakIterator::TailoredWordBreakIterator (const TailoredWordBreakIterator &) delete
Member Function Documentation
Advance()
bool TailoredWordBreakIterator::Advance ()
References AdvanceInUnderscoreWord(), HasUnderscoreWord(), IsWord(), pos_, prev_, and underscore_word_.
Referenced by URLIndexPrivateData::CalculateWordStartsOffsets(), and String16VectorFromString16().
AdvanceInUnderscoreWord()
void TailoredWordBreakIterator::AdvanceInUnderscoreWord () private
References pos_, prev_, and underscore_word_.
Referenced by Advance().
GetString()
std::u16string TailoredWordBreakIterator::GetString () const
References GetStringPiece().
Referenced by String16VectorFromString16().
GetStringPiece()
base::StringPiece16 TailoredWordBreakIterator::GetStringPiece () const
References pos_, prev_, and underscore_word_.
Referenced by GetString(), and IsWord().
HasUnderscoreWord()
bool TailoredWordBreakIterator::HasUnderscoreWord () const private
References pos_, and underscore_word_.
Referenced by Advance(), and IsWord().
IsWord()
bool TailoredWordBreakIterator::IsWord () const
References GetStringPiece(), and HasUnderscoreWord().
Referenced by Advance(), URLIndexPrivateData::CalculateWordStartsOffsets(), and String16VectorFromString16().
operator=()
TailoredWordBreakIterator& TailoredWordBreakIterator::operator= (const TailoredWordBreakIterator &) delete
pos()
size_t TailoredWordBreakIterator::pos () const
References pos_.
prev()
size_t TailoredWordBreakIterator::prev () const
References prev_.
Referenced by URLIndexPrivateData::CalculateWordStartsOffsets(), and String16VectorFromString16().
Member Data Documentation
pos_
size_t TailoredWordBreakIterator::pos_ private
Referenced by Advance(), AdvanceInUnderscoreWord(), GetStringPiece(), HasUnderscoreWord(), and pos().
prev_
size_t TailoredWordBreakIterator::prev_ private
Referenced by Advance(), AdvanceInUnderscoreWord(), GetStringPiece(), and prev().
underscore_word_
base::StringPiece16 TailoredWordBreakIterator::underscore_word_ private
Referenced by Advance(), AdvanceInUnderscoreWord(), GetStringPiece(), and HasUnderscoreWord().
The documentation for this class was generated from the following files:
components/omnibox/browser/tailored_word_break_iterator.h
components/omnibox/browser/tailored_word_break_iterator.cc