Chromium Omnibox: SuggestionAnswer Class Reference
SuggestionAnswer Class Reference
#include <suggestion_answer.h>
Classes
class ImageLine
class TextField
Public Types
enum AnswerType {
ANSWER_TYPE_INVALID = 0 , ANSWER_TYPE_DICTIONARY = 1 , ANSWER_TYPE_FINANCE = 2 , ANSWER_TYPE_KNOWLEDGE_GRAPH = 3 ,
ANSWER_TYPE_LOCAL = 4 , ANSWER_TYPE_SPORTS = 5 , ANSWER_TYPE_SUNRISE = 6 , ANSWER_TYPE_TRANSLATION = 7 ,
ANSWER_TYPE_WEATHER = 8 , ANSWER_TYPE_WHEN_IS = 9 , ANSWER_TYPE_CURRENCY = 10 , ANSWER_TYPE_LOCAL_TIME = 11 ,
ANSWER_TYPE_PLAY_INSTALL = 12 , ANSWER_TYPE_TOTAL_COUNT
}
enum TextType {
TOP_ALIGNED = 3 , DESCRIPTION_NEGATIVE = 5 , DESCRIPTION_POSITIVE = 6 , SUGGESTION = 8 ,
PERSONALIZED_SUGGESTION = 13 , ANSWER_TEXT_MEDIUM = 17 , ANSWER_TEXT_LARGE = 18 , SUGGESTION_SECONDARY_TEXT_SMALL = 19 ,
SUGGESTION_SECONDARY_TEXT_MEDIUM = 20
}
enum class TextStyle {
NONE = 0 , NORMAL , NORMAL_DIM , SECONDARY ,
BOLD , POSITIVE , NEGATIVE , SUPERIOR
}
typedef std::vector< TextField > TextFields
typedef std::vector< GURL > URLs
Public Member Functions
SuggestionAnswer ()
SuggestionAnswer (const SuggestionAnswer &answer)
SuggestionAnswer (SuggestionAnswer &&) noexcept
SuggestionAnswer & operator= (const SuggestionAnswer &answer)
SuggestionAnswer & operator= (SuggestionAnswer &&) noexcept
~SuggestionAnswer ()
const GURL & image_url () const
const ImageLine & first_line () const
const ImageLine & second_line () const
int type () const
void set_type (int type)
bool Equals (const SuggestionAnswer &answer) const
void AddImageURLsTo (URLs *urls) const
size_t EstimateMemoryUsage () const
void InterpretTextTypes ()
bool IsExceptedFromLineReversal () const
Static Public Member Functions
static bool ParseAnswer (const base::Value &answer_json, const std::u16string &answer_type_str, SuggestionAnswer *answer)
static void LogAnswerUsed (const absl::optional< SuggestionAnswer > &answer)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest, DifferentValuesAreUnequal)
FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest, LogAnswerUsed)
Private Attributes
GURL image_url_
ImageLine first_line_
ImageLine second_line_
int type_ = -1
Static Private Attributes
static const char kAnswerUsedUmaHistogramName []
Member Typedef Documentation
TextFields
typedef std::vector<TextField> SuggestionAnswer::TextFields
URLs
typedef std::vector<GURL> SuggestionAnswer::URLs
Member Enumeration Documentation
AnswerType
enum SuggestionAnswer::AnswerType
Enumerator
ANSWER_TYPE_INVALID
ANSWER_TYPE_DICTIONARY
ANSWER_TYPE_FINANCE
ANSWER_TYPE_KNOWLEDGE_GRAPH
ANSWER_TYPE_LOCAL
ANSWER_TYPE_SPORTS
ANSWER_TYPE_SUNRISE
ANSWER_TYPE_TRANSLATION
ANSWER_TYPE_WEATHER
ANSWER_TYPE_WHEN_IS
ANSWER_TYPE_CURRENCY
ANSWER_TYPE_LOCAL_TIME
ANSWER_TYPE_PLAY_INSTALL
ANSWER_TYPE_TOTAL_COUNT
TextStyle
enum SuggestionAnswer::TextStyle strong
Enumerator
NONE
NORMAL
NORMAL_DIM
SECONDARY
BOLD
POSITIVE
NEGATIVE
SUPERIOR
TextType
enum SuggestionAnswer::TextType
Enumerator
TOP_ALIGNED
DESCRIPTION_NEGATIVE
DESCRIPTION_POSITIVE
SUGGESTION
PERSONALIZED_SUGGESTION
ANSWER_TEXT_MEDIUM
ANSWER_TEXT_LARGE
SUGGESTION_SECONDARY_TEXT_SMALL
SUGGESTION_SECONDARY_TEXT_MEDIUM
Constructor & Destructor Documentation
SuggestionAnswer() [1/3]
SuggestionAnswer::SuggestionAnswer () default
SuggestionAnswer() [2/3]
SuggestionAnswer::SuggestionAnswer (const SuggestionAnswer & answer) default
SuggestionAnswer() [3/3]
SuggestionAnswer::SuggestionAnswer (SuggestionAnswer &&) default noexcept
~SuggestionAnswer()
SuggestionAnswer::~SuggestionAnswer () default
Member Function Documentation
AddImageURLsTo()
void SuggestionAnswer::AddImageURLsTo (URLs * urls) const
References SuggestionAnswer::ImageLine::image_url(), image_url_, and second_line_.
Equals()
bool SuggestionAnswer::Equals (const SuggestionAnswer & answer) const
References SuggestionAnswer::ImageLine::Equals(), first_line_, image_url_, second_line_, and type_.
Referenced by SuggestionAnswer::ImageLine::Equals().
EstimateMemoryUsage()
size_t SuggestionAnswer::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage(), first_line_, image_url_, and second_line_.
first_line()
const ImageLine& SuggestionAnswer::first_line () const inline
References first_line_.
FRIEND_TEST_ALL_PREFIXES() [1/2]
SuggestionAnswer::FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest , DifferentValuesAreUnequal) private
FRIEND_TEST_ALL_PREFIXES() [2/2]
SuggestionAnswer::FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest , LogAnswerUsed) private
image_url()
const GURL& SuggestionAnswer::image_url () const inline
References image_url_.
Referenced by ParseAnswer().
InterpretTextTypes()
void SuggestionAnswer::InterpretTextTypes ()
References ANSWER_TYPE_FINANCE, ANSWER_TYPE_WEATHER, DESCRIPTION_NEGATIVE, DESCRIPTION_POSITIVE, first_line_, IsExceptedFromLineReversal(), NEGATIVE, NORMAL, NORMAL_DIM, POSITIVE, second_line_, SECONDARY, SuggestionAnswer::ImageLine::SetTextStyles(), SUGGESTION_SECONDARY_TEXT_SMALL, SUPERIOR, TOP_ALIGNED, and type().
IsExceptedFromLineReversal()
bool SuggestionAnswer::IsExceptedFromLineReversal () const
References ANSWER_TYPE_DICTIONARY, and type().
Referenced by InterpretTextTypes().
LogAnswerUsed()
void SuggestionAnswer::LogAnswerUsed (const absl::optional< SuggestionAnswer > & answer) static
References ANSWER_TYPE_INVALID, ANSWER_TYPE_TOTAL_COUNT, and kAnswerUsedUmaHistogramName.
Referenced by OmniboxEditModel::OpenMatch().
operator=() [1/2]
SuggestionAnswer & SuggestionAnswer::operator= (const SuggestionAnswer & answer) default
operator=() [2/2]
SuggestionAnswer & SuggestionAnswer::operator= (SuggestionAnswer &&) default noexcept
ParseAnswer()
bool SuggestionAnswer::ParseAnswer (const base::Value & answer_json, const std::u16string & answer_type_str, SuggestionAnswer * answer) static
References image_url(), and SuggestionAnswer::ImageLine::ParseImageLine().
Referenced by SearchSuggestionParser::ParseSuggestResults().
second_line()
const ImageLine& SuggestionAnswer::second_line () const inline
References second_line_.
set_type()
void SuggestionAnswer::set_type (int type) inline
References type(), and type_.
type()
int SuggestionAnswer::type () const inline
References type_.
Referenced by InterpretTextTypes(), IsExceptedFromLineReversal(), SearchSuggestionParser::ParseSuggestResults(), and set_type().
Member Data Documentation
first_line_
ImageLine SuggestionAnswer::first_line_ private
Referenced by Equals(), EstimateMemoryUsage(), first_line(), and InterpretTextTypes().
image_url_
GURL SuggestionAnswer::image_url_ private
Referenced by AddImageURLsTo(), SuggestionAnswer::ImageLine::Equals(), Equals(), SuggestionAnswer::ImageLine::EstimateMemoryUsage(), EstimateMemoryUsage(), and image_url().
kAnswerUsedUmaHistogramName
const char SuggestionAnswer::kAnswerUsedUmaHistogramName static private
Initial value:
=
    "Omnibox.SuggestionUsed.AnswerInSuggest"
Referenced by LogAnswerUsed().
second_line_
ImageLine SuggestionAnswer::second_line_ private
Referenced by AddImageURLsTo(), Equals(), EstimateMemoryUsage(), InterpretTextTypes(), and second_line().
type_
int SuggestionAnswer::type_ = -1 private
Referenced by Equals(), set_type(), and type().
The documentation for this class was generated from the following files:
components/omnibox/browser/suggestion_answer.h
components/omnibox/browser/suggestion_answer.cc