Chromium Omnibox: LocationBarModelImpl Class Reference
LocationBarModelImpl Class Reference
#include <location_bar_model_impl.h>
Public Member Functions
LocationBarModelImpl (LocationBarModelDelegate *delegate, size_t max_url_display_chars)
~LocationBarModelImpl () override
std::u16string GetFormattedFullURL () const override
std::u16string GetURLForDisplay () const override
GURL GetURL () const override
security_state::SecurityLevel GetSecurityLevel () const override
net::CertStatus GetCertStatus () const override
metrics::OmniboxEventProto::PageClassification GetPageClassification (OmniboxFocusSource focus_source) override
const gfx::VectorIcon & GetVectorIcon () const override
std::u16string GetSecureDisplayText () const override
std::u16string GetSecureAccessibilityText () const override
bool ShouldDisplayURL () const override
bool IsOfflinePage () const override
bool ShouldPreventElision () const override
Public Member Functions inherited from LocationBarModel
virtual ~LocationBarModel ()=default
Private Member Functions
std::u16string GetFormattedURL (url_formatter::FormatUrlTypes format_types) const
DISALLOW_IMPLICIT_CONSTRUCTORS (LocationBarModelImpl)
Private Attributes
LocationBarModelDelegate * delegate_
const size_t max_url_display_chars_
Additional Inherited Members
Protected Member Functions inherited from LocationBarModel
LocationBarModel ()=default
LocationBarModel (const LocationBarModel &)=delete
LocationBarModel & operator= (const LocationBarModel &)=delete
Constructor & Destructor Documentation
LocationBarModelImpl()
LocationBarModelImpl::LocationBarModelImpl (LocationBarModelDelegate * delegate, size_t max_url_display_chars)
References delegate_.
~LocationBarModelImpl()
LocationBarModelImpl::~LocationBarModelImpl () override
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
LocationBarModelImpl::DISALLOW_IMPLICIT_CONSTRUCTORS (LocationBarModelImpl) private
GetCertStatus()
net::CertStatus LocationBarModelImpl::GetCertStatus () const override virtual
Implements LocationBarModel.
References delegate_, LocationBarModelDelegate::GetCertStatus(), and ShouldDisplayURL().
GetFormattedFullURL()
std::u16string LocationBarModelImpl::GetFormattedFullURL () const override virtual
Implements LocationBarModel.
References GetFormattedURL().
GetFormattedURL()
std::u16string LocationBarModelImpl::GetFormattedURL (url_formatter::FormatUrlTypes format_types) const private
References delegate_, LocationBarModelDelegate::FormattedStringWithEquivalentMeaning(), GetURL(), max_url_display_chars_, ShouldDisplayURL(), and LocationBarModelDelegate::ShouldPreventElision().
Referenced by GetFormattedFullURL(), and GetURLForDisplay().
GetPageClassification()
OmniboxEventProto::PageClassification LocationBarModelImpl::GetPageClassification (OmniboxFocusSource focus_source) override virtual
Implements LocationBarModel.
References delegate_, FAKEBOX, LocationBarModelDelegate::GetTemplateURLService(), LocationBarModelDelegate::GetURL(), LocationBarModelDelegate::IsHomePage(), LocationBarModelDelegate::IsNewTabPage(), and LocationBarModelDelegate::IsNewTabPageURL().
GetSecureAccessibilityText()
std::u16string LocationBarModelImpl::GetSecureAccessibilityText () const override virtual
Implements LocationBarModel.
References GetSecureDisplayText(), and GetSecurityLevel().
GetSecureDisplayText()
std::u16string LocationBarModelImpl::GetSecureDisplayText () const override virtual
Implements LocationBarModel.
References delegate_, GetSecurityLevel(), LocationBarModelDelegate::GetVisibleSecurityState(), and IsOfflinePage().
Referenced by GetSecureAccessibilityText().
GetSecurityLevel()
security_state::SecurityLevel LocationBarModelImpl::GetSecurityLevel () const override virtual
Implements LocationBarModel.
References delegate_, LocationBarModelDelegate::GetSecurityLevel(), and ShouldDisplayURL().
Referenced by GetSecureAccessibilityText(), GetSecureDisplayText(), and GetVectorIcon().
GetURL()
GURL LocationBarModelImpl::GetURL () const override virtual
Implements LocationBarModel.
References delegate_, LocationBarModelDelegate::GetURL(), and ShouldDisplayURL().
Referenced by GetFormattedURL(), and GetURLForDisplay().
GetURLForDisplay()
std::u16string LocationBarModelImpl::GetURLForDisplay () const override virtual
Implements LocationBarModel.
References delegate_, GetFormattedURL(), GetURL(), and LocationBarModelDelegate::ShouldTrimDisplayUrlAfterHostName().
GetVectorIcon()
const gfx::VectorIcon & LocationBarModelImpl::GetVectorIcon () const override virtual
Implements LocationBarModel.
References delegate_, GetSecurityLevel(), location_bar_model::GetSecurityVectorIcon(), LocationBarModelDelegate::GetVectorIconOverride(), IsOfflinePage(), and LocationBarModelDelegate::ShouldUseUpdatedConnectionSecurityIndicators().
IsOfflinePage()
bool LocationBarModelImpl::IsOfflinePage () const override virtual
Implements LocationBarModel.
References delegate_, and LocationBarModelDelegate::IsOfflinePage().
Referenced by GetSecureDisplayText(), and GetVectorIcon().
ShouldDisplayURL()
bool LocationBarModelImpl::ShouldDisplayURL () const override virtual
Implements LocationBarModel.
References delegate_, and LocationBarModelDelegate::ShouldDisplayURL().
Referenced by GetCertStatus(), GetFormattedURL(), GetSecurityLevel(), and GetURL().
ShouldPreventElision()
bool LocationBarModelImpl::ShouldPreventElision () const override virtual
Implements LocationBarModel.
References delegate_, and LocationBarModelDelegate::ShouldPreventElision().
Member Data Documentation
delegate_
LocationBarModelDelegate* LocationBarModelImpl::delegate_ private
Referenced by GetCertStatus(), GetFormattedURL(), GetPageClassification(), GetSecureDisplayText(), GetSecurityLevel(), GetURL(), GetURLForDisplay(), GetVectorIcon(), IsOfflinePage(), LocationBarModelImpl(), ShouldDisplayURL(), and ShouldPreventElision().
max_url_display_chars_
const size_t LocationBarModelImpl::max_url_display_chars_ private
Referenced by GetFormattedURL().
The documentation for this class was generated from the following files:
components/omnibox/browser/location_bar_model_impl.h
components/omnibox/browser/location_bar_model_impl.cc