Chromium Omnibox: chrome/browser/ui/omnibox/omnibox_theme.h File Reference
omnibox_theme.h File Reference
#include "components/security_state/core/security_state.h"
#include "third_party/skia/include/core/SkColor.h"
Namespaces
ui
Enumerations
enum class OmniboxPart {
LOCATION_BAR_BACKGROUND , LOCATION_BAR_CLEAR_ALL , LOCATION_BAR_SELECTED_KEYWORD , LOCATION_BAR_TEXT_DEFAULT ,
LOCATION_BAR_TEXT_DIMMED , LOCATION_BAR_BUBBLE_OUTLINE , RESULTS_BACKGROUND , RESULTS_ICON ,
RESULTS_TEXT_DEFAULT , RESULTS_TEXT_DIMMED , RESULTS_TEXT_URL , RESULTS_BUTTON_BORDER
}
enum class OmniboxPartState { NORMAL , HOVERED , SELECTED }
Functions
SkColor GetOmniboxColor (const ui::ThemeProvider *theme_provider, OmniboxPart part, OmniboxPartState state=OmniboxPartState::NORMAL)
SkColor GetOmniboxSecurityChipColor (const ui::ThemeProvider *theme_provider, security_state::SecurityLevel security_level)
float GetOmniboxStateOpacity (OmniboxPartState state)
Enumeration Type Documentation
OmniboxPart
enum OmniboxPart strong
Enumerator
LOCATION_BAR_BACKGROUND
LOCATION_BAR_CLEAR_ALL
LOCATION_BAR_SELECTED_KEYWORD
LOCATION_BAR_TEXT_DEFAULT
LOCATION_BAR_TEXT_DIMMED
LOCATION_BAR_BUBBLE_OUTLINE
RESULTS_BACKGROUND
RESULTS_ICON
RESULTS_TEXT_DEFAULT
RESULTS_TEXT_DIMMED
RESULTS_TEXT_URL
RESULTS_BUTTON_BORDER
OmniboxPartState
enum OmniboxPartState strong
Enumerator
NORMAL
HOVERED
SELECTED
Function Documentation
GetOmniboxColor()
SkColor GetOmniboxColor (const ui::ThemeProvider * theme_provider, OmniboxPart part, OmniboxPartState state = OmniboxPartState::NORMAL)
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxResultView::GetColor(), GetOmniboxSecurityChipColor(), OmniboxResultView::GetPopupCellBackground(), OmniboxSuggestionRowButton::OnThemeChanged(), OmniboxViewViews::OnThemeChanged(), OmniboxViewViews::SetEmphasis(), OmniboxSuggestionRowButton::UpdateBackgroundColor(), and OmniboxRowView::HeaderView::UpdateUI().
GetOmniboxSecurityChipColor()
SkColor GetOmniboxSecurityChipColor (const ui::ThemeProvider * theme_provider, security_state::SecurityLevel security_level)
References GetOmniboxColor(), and LOCATION_BAR_TEXT_DIMMED.
GetOmniboxStateOpacity()
float GetOmniboxStateOpacity (OmniboxPartState state)
Referenced by OmniboxSuggestionRowButton::OmniboxSuggestionRowButton().