Chromium Omnibox: MockAutocompleteProviderClient Class Reference
MockAutocompleteProviderClient Class Reference
#include <mock_autocomplete_provider_client.h>
Public Member Functions
MockAutocompleteProviderClient ()
~MockAutocompleteProviderClient ()
MockAutocompleteProviderClient (const MockAutocompleteProviderClient &)=delete
MockAutocompleteProviderClient & operator= (const MockAutocompleteProviderClient &)=delete
MOCK_CONST_METHOD0 (GetPrefs, PrefService *())
MOCK_METHOD0 (GetLocalState, PrefService *())
MOCK_CONST_METHOD0 (GetSchemeClassifier, const AutocompleteSchemeClassifier &())
MOCK_METHOD0 (GetAutocompleteClassifier, AutocompleteClassifier *())
MOCK_METHOD0 (GetHistoryService, history::HistoryService *())
scoped_refptr< network::SharedURLLoaderFactory > GetURLLoaderFactory () override
scoped_refptr< history::TopSites > GetTopSites () override
MOCK_METHOD0 (GetBookmarkModel, bookmarks::BookmarkModel *())
MOCK_METHOD0 (GetInMemoryDatabase, history::URLDatabase *())
MOCK_METHOD0 (GetInMemoryURLIndex, InMemoryURLIndex *())
TemplateURLService * GetTemplateURLService () override
const TemplateURLService * GetTemplateURLService () const override
RemoteSuggestionsService * GetRemoteSuggestionsService (bool create_if_necessary) const override
DocumentSuggestionsService * GetDocumentSuggestionsService (bool create_if_necessary) const override
OmniboxPedalProvider * GetPedalProvider () const override
scoped_refptr< ShortcutsBackend > GetShortcutsBackend () override
scoped_refptr< ShortcutsBackend > GetShortcutsBackendIfExists () override
std::unique_ptr< KeywordExtensionsDelegate > GetKeywordExtensionsDelegate (KeywordProvider *keyword_provider) override
query_tiles::TileService * GetQueryTileService () const override
OmniboxTriggeredFeatureService * GetOmniboxTriggeredFeatureService () const override
component_updater::ComponentUpdateService * GetComponentUpdateService () override
signin::IdentityManager * GetIdentityManager () const override
MOCK_CONST_METHOD0 (GetAcceptLanguages, std::string())
MOCK_CONST_METHOD0 (GetEmbedderRepresentationOfAboutScheme, std::string())
MOCK_METHOD0 (GetBuiltinURLs, std::vector< std::u16string >())
MOCK_METHOD0 (GetBuiltinsToProvideAsUserTypes, std::vector< std::u16string >())
MOCK_CONST_METHOD0 (IsOffTheRecord, bool())
MOCK_CONST_METHOD0 (SearchSuggestEnabled, bool())
MOCK_CONST_METHOD0 (IsPersonalizedUrlDataCollectionActive, bool())
MOCK_CONST_METHOD0 (IsAuthenticated, bool())
MOCK_CONST_METHOD0 (IsSyncActive, bool())
MOCK_METHOD6 (Classify, void(const std::u16string &text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch *match, GURL *alternate_nav_url))
MOCK_METHOD2 (DeleteMatchingURLsForKeywordFromHistory, void(history::KeywordID keyword_id, const std::u16string &term))
MOCK_METHOD1 (PrefetchImage, void(const GURL &url))
bool IsTabOpenWithURL (const GURL &url, const AutocompleteInput *input) override
void set_template_url_service (std::unique_ptr< TemplateURLService > service)
void set_identity_manager (signin::IdentityManager *identity_manager)
network::TestURLLoaderFactory * test_url_loader_factory ()
Private Attributes
network::TestURLLoaderFactory test_url_loader_factory_
scoped_refptr< network::SharedURLLoaderFactory > shared_factory_
std::unique_ptr< TemplateURLService > template_url_service_
std::unique_ptr< RemoteSuggestionsService > remote_suggestions_service_
std::unique_ptr< DocumentSuggestionsService > document_suggestions_service_
std::unique_ptr< OmniboxPedalProvider > pedal_provider_
std::unique_ptr< OmniboxTriggeredFeatureService > omnibox_triggered_feature_service_
signin::IdentityManager * identity_manager_ = nullptr
Constructor & Destructor Documentation
MockAutocompleteProviderClient() [1/2]
MockAutocompleteProviderClient::MockAutocompleteProviderClient ()
References document_suggestions_service_, DocumentSuggestionsService::DocumentSuggestionsService(), GetURLLoaderFactory(), omnibox_triggered_feature_service_, OmniboxPedalProvider::OmniboxPedalProvider(), OmniboxTriggeredFeatureService::OmniboxTriggeredFeatureService(), pedal_provider_, remote_suggestions_service_, RemoteSuggestionsService::RemoteSuggestionsService(), shared_factory_, and test_url_loader_factory_.
~MockAutocompleteProviderClient()
MockAutocompleteProviderClient::~MockAutocompleteProviderClient ()
MockAutocompleteProviderClient() [2/2]
MockAutocompleteProviderClient::MockAutocompleteProviderClient (const MockAutocompleteProviderClient &) delete
Member Function Documentation
GetComponentUpdateService()
component_updater::ComponentUpdateService* MockAutocompleteProviderClient::GetComponentUpdateService () inline override
GetDocumentSuggestionsService()
DocumentSuggestionsService* MockAutocompleteProviderClient::GetDocumentSuggestionsService (bool create_if_necessary) const inline override
References document_suggestions_service_.
GetIdentityManager()
signin::IdentityManager* MockAutocompleteProviderClient::GetIdentityManager () const inline override
References identity_manager_.
GetKeywordExtensionsDelegate()
std::unique_ptr<KeywordExtensionsDelegate> MockAutocompleteProviderClient::GetKeywordExtensionsDelegate (KeywordProvider * keyword_provider) inline override
GetOmniboxTriggeredFeatureService()
OmniboxTriggeredFeatureService* MockAutocompleteProviderClient::GetOmniboxTriggeredFeatureService () const inline override
References omnibox_triggered_feature_service_.
GetPedalProvider()
OmniboxPedalProvider* MockAutocompleteProviderClient::GetPedalProvider () const inline override
References pedal_provider_.
GetQueryTileService()
query_tiles::TileService* MockAutocompleteProviderClient::GetQueryTileService () const inline override
GetRemoteSuggestionsService()
RemoteSuggestionsService* MockAutocompleteProviderClient::GetRemoteSuggestionsService (bool create_if_necessary) const inline override
References remote_suggestions_service_.
GetShortcutsBackend()
scoped_refptr<ShortcutsBackend> MockAutocompleteProviderClient::GetShortcutsBackend () inline override
GetShortcutsBackendIfExists()
scoped_refptr<ShortcutsBackend> MockAutocompleteProviderClient::GetShortcutsBackendIfExists () inline override
GetTemplateURLService() [1/2]
const TemplateURLService* MockAutocompleteProviderClient::GetTemplateURLService () const inline override
References template_url_service_.
GetTemplateURLService() [2/2]
TemplateURLService* MockAutocompleteProviderClient::GetTemplateURLService () inline override
References template_url_service_.
Referenced by FakeAutocompleteProviderClient::FakeAutocompleteProviderClient().
GetTopSites()
scoped_refptr<history::TopSites> MockAutocompleteProviderClient::GetTopSites () inline override
GetURLLoaderFactory()
scoped_refptr<network::SharedURLLoaderFactory> MockAutocompleteProviderClient::GetURLLoaderFactory () inline override
References shared_factory_.
Referenced by MockAutocompleteProviderClient().
IsTabOpenWithURL()
bool MockAutocompleteProviderClient::IsTabOpenWithURL (const GURL & url, const AutocompleteInput * input) inline override
MOCK_CONST_METHOD0() [1/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (GetAcceptLanguages , std::string())
MOCK_CONST_METHOD0() [2/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (GetEmbedderRepresentationOfAboutScheme , std::string())
MOCK_CONST_METHOD0() [3/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (GetPrefs , PrefService * ())
MOCK_CONST_METHOD0() [4/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (GetSchemeClassifier , const AutocompleteSchemeClassifier & ())
MOCK_CONST_METHOD0() [5/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (IsAuthenticated , bool())
MOCK_CONST_METHOD0() [6/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (IsOffTheRecord , bool())
MOCK_CONST_METHOD0() [7/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (IsPersonalizedUrlDataCollectionActive , bool())
MOCK_CONST_METHOD0() [8/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (IsSyncActive , bool())
MOCK_CONST_METHOD0() [9/9]
MockAutocompleteProviderClient::MOCK_CONST_METHOD0 (SearchSuggestEnabled , bool())
MOCK_METHOD0() [1/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetAutocompleteClassifier , AutocompleteClassifier * ())
MOCK_METHOD0() [2/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetBookmarkModel , bookmarks::BookmarkModel * ())
MOCK_METHOD0() [3/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetBuiltinsToProvideAsUserTypes , std::vector< std::u16string > ())
MOCK_METHOD0() [4/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetBuiltinURLs , std::vector< std::u16string > ())
MOCK_METHOD0() [5/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetHistoryService , history::HistoryService * ())
MOCK_METHOD0() [6/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetInMemoryDatabase , history::URLDatabase * ())
MOCK_METHOD0() [7/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetInMemoryURLIndex , InMemoryURLIndex * ())
MOCK_METHOD0() [8/8]
MockAutocompleteProviderClient::MOCK_METHOD0 (GetLocalState , PrefService * ())
MOCK_METHOD1()
MockAutocompleteProviderClient::MOCK_METHOD1 (PrefetchImage , void(const GURL &url))
MOCK_METHOD2()
MockAutocompleteProviderClient::MOCK_METHOD2 (DeleteMatchingURLsForKeywordFromHistory , void(history::KeywordID keyword_id, const std::u16string &term))
MOCK_METHOD6()
MockAutocompleteProviderClient::MOCK_METHOD6 (Classify , void(const std::u16string &text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch *match, GURL *alternate_nav_url))
operator=()
MockAutocompleteProviderClient& MockAutocompleteProviderClient::operator= (const MockAutocompleteProviderClient &) delete
set_identity_manager()
void MockAutocompleteProviderClient::set_identity_manager (signin::IdentityManager * identity_manager) inline
References identity_manager_.
set_template_url_service()
void MockAutocompleteProviderClient::set_template_url_service (std::unique_ptr< TemplateURLService > service) inline
References template_url_service_.
Referenced by FakeAutocompleteProviderClient::FakeAutocompleteProviderClient().
test_url_loader_factory()
network::TestURLLoaderFactory* MockAutocompleteProviderClient::test_url_loader_factory () inline
References test_url_loader_factory_.
Member Data Documentation
document_suggestions_service_
std::unique_ptr<DocumentSuggestionsService> MockAutocompleteProviderClient::document_suggestions_service_ private
Referenced by GetDocumentSuggestionsService(), and MockAutocompleteProviderClient().
identity_manager_
signin::IdentityManager* MockAutocompleteProviderClient::identity_manager_ = nullptr private
Referenced by GetIdentityManager(), and set_identity_manager().
omnibox_triggered_feature_service_
std::unique_ptr<OmniboxTriggeredFeatureService> MockAutocompleteProviderClient::omnibox_triggered_feature_service_ private
Referenced by GetOmniboxTriggeredFeatureService(), and MockAutocompleteProviderClient().
pedal_provider_
std::unique_ptr<OmniboxPedalProvider> MockAutocompleteProviderClient::pedal_provider_ private
Referenced by GetPedalProvider(), and MockAutocompleteProviderClient().
remote_suggestions_service_
std::unique_ptr<RemoteSuggestionsService> MockAutocompleteProviderClient::remote_suggestions_service_ private
Referenced by GetRemoteSuggestionsService(), and MockAutocompleteProviderClient().
shared_factory_
scoped_refptr<network::SharedURLLoaderFactory> MockAutocompleteProviderClient::shared_factory_ private
Referenced by GetURLLoaderFactory(), and MockAutocompleteProviderClient().
template_url_service_
std::unique_ptr<TemplateURLService> MockAutocompleteProviderClient::template_url_service_ private
Referenced by GetTemplateURLService(), and set_template_url_service().
test_url_loader_factory_
network::TestURLLoaderFactory MockAutocompleteProviderClient::test_url_loader_factory_ private
Referenced by MockAutocompleteProviderClient(), and test_url_loader_factory().
The documentation for this class was generated from the following files:
components/omnibox/browser/mock_autocomplete_provider_client.h
components/omnibox/browser/mock_autocomplete_provider_client.cc