Chromium Omnibox: OmniboxAction Class Reference
OmniboxAction Class Reference
#include <omnibox_action.h>
Classes
struct Client
class ExecutionContext
struct LabelStrings
Public Member Functions
OmniboxAction (LabelStrings strings, GURL url)
const LabelStrings & GetLabelStrings () const
virtual void RecordActionShown (size_t position) const
virtual void RecordActionExecuted (size_t position) const
virtual void Execute (ExecutionContext &context) const
virtual bool IsReadyToTrigger (const AutocompleteInput &input, const AutocompleteProviderClient &client) const
virtual const gfx::VectorIcon & GetVectorIcon () const
virtual SkColor GetVectorIconColor () const
virtual size_t EstimateMemoryUsage () const
virtual int32_t GetID () const
Protected Member Functions
virtual ~OmniboxAction ()
void OpenURL (ExecutionContext &context, const GURL &url) const
Protected Attributes
LabelStrings strings_
GURL url_
Friends
class base::RefCounted< OmniboxAction >
Constructor & Destructor Documentation
OmniboxAction()
OmniboxAction::OmniboxAction (LabelStrings strings, GURL url)
~OmniboxAction()
OmniboxAction::~OmniboxAction () protected virtual default
Member Function Documentation
EstimateMemoryUsage()
size_t OmniboxAction::EstimateMemoryUsage () const virtual
Reimplemented in OmniboxPedal.
References base::trace_event::EstimateMemoryUsage(), strings_, and url_.
Referenced by OmniboxPedal::EstimateMemoryUsage().
Execute()
void OmniboxAction::Execute (OmniboxAction::ExecutionContext & context) const virtual
Reimplemented in OmniboxPedalShareThisPage, OmniboxPedalCloseIncognitoWindows, OmniboxPedalTranslate, OmniboxPedalLaunchIncognito, and OmniboxPedalClearBrowsingData.
References OpenURL(), and url_.
Referenced by OmniboxPedalClearBrowsingData::Execute().
GetID()
int32_t OmniboxAction::GetID () const virtual
Reimplemented in OmniboxPedal.
GetLabelStrings()
const OmniboxAction::LabelStrings & OmniboxAction::GetLabelStrings () const
References strings_.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
GetVectorIcon()
const gfx::VectorIcon & OmniboxAction::GetVectorIcon () const virtual
Reimplemented in OmniboxPedalManageChromeOSAccessibility, OmniboxPedalManageChromeAccessibility, OmniboxPedalShareThisPage, OmniboxPedalViewChromeHistory, OmniboxPedalManageChromeDownloads, OmniboxPedalManageChromeSettings, OmniboxPedalManageGooglePrivacy, OmniboxPedalFindMyPhone, OmniboxPedalPlayChromeDinoGame, OmniboxPedalCloseIncognitoWindows, OmniboxPedalChangeGooglePassword, OmniboxPedalManageGoogleAccount, OmniboxPedalCreateGoogleForm, OmniboxPedalCreateGoogleKeepNote, OmniboxPedalCreateGoogleSite, OmniboxPedalCreateGoogleCalendarEvent, OmniboxPedalCreateGoogleSlide, OmniboxPedalCreateGoogleSheet, OmniboxPedalCreateGoogleDoc, and OmniboxPedal.
GetVectorIconColor()
SkColor OmniboxAction::GetVectorIconColor () const virtual
Reimplemented in OmniboxPedalManageChromeOSAccessibility, OmniboxPedalManageChromeAccessibility, OmniboxPedalViewChromeHistory, OmniboxPedalManageChromeDownloads, and OmniboxPedalManageChromeSettings.
IsReadyToTrigger()
bool OmniboxAction::IsReadyToTrigger (const AutocompleteInput & input, const AutocompleteProviderClient & client) const virtual
Reimplemented in OmniboxPedalShareThisPage, OmniboxPedalPlayChromeDinoGame, OmniboxPedalAuthRequired, OmniboxPedalTranslate, and OmniboxPedalLaunchIncognito.
Referenced by OmniboxPedalProvider::FindReadyPedalMatch().
OpenURL()
void OmniboxAction::OpenURL (OmniboxAction::ExecutionContext & context, const GURL & url) const protected
References OmniboxAction::ExecutionContext::disposition_, OmniboxAction::ExecutionContext::match_selection_timestamp_, OmniboxAction::ExecutionContext::open_url_callback_, and AutocompleteMatchType::URL_WHAT_YOU_TYPED.
Referenced by Execute().
RecordActionExecuted()
virtual void OmniboxAction::RecordActionExecuted (size_t position) const inline virtual
Reimplemented in OmniboxPedal.
RecordActionShown()
virtual void OmniboxAction::RecordActionShown (size_t position) const inline virtual
Reimplemented in OmniboxPedal.
Friends And Related Function Documentation
base::RefCounted< OmniboxAction >
friend class base::RefCounted< OmniboxAction > friend
Member Data Documentation
strings_
LabelStrings OmniboxAction::strings_ protected
Referenced by EstimateMemoryUsage(), GetLabelStrings(), and OmniboxPedal::SetLabelStrings().
url_
GURL OmniboxAction::url_ protected
Referenced by EstimateMemoryUsage(), Execute(), and OmniboxPedal::SetNavigationUrl().
The documentation for this class was generated from the following files:
components/omnibox/browser/actions/omnibox_action.h
components/omnibox/browser/actions/omnibox_action.cc