Chromium Omnibox: OmniboxPopupContentsView::AutocompletePopupWidget Class Reference
OmniboxPopupContentsView::AutocompletePopupWidget Class Reference
Public Member Functions
AutocompletePopupWidget (views::Widget *role_model)
AutocompletePopupWidget (const AutocompletePopupWidget &)=delete
AutocompletePopupWidget & operator= (const AutocompletePopupWidget &)=delete
~AutocompletePopupWidget () override
void InitOmniboxPopup (views::Widget *parent_widget)
void SetPopupContentsView (OmniboxPopupContentsView *contents)
void SetTargetBounds (const gfx::Rect &bounds)
void ShowAnimated ()
void CloseAnimated ()
void OnNativeWidgetDestroying () override
void OnMouseEvent (ui::MouseEvent *event) override
void OnGestureEvent (ui::GestureEvent *event) override
bool is_setting_popup_bounds () const
Private Member Functions
std::unique_ptr< ui::ScopedLayerAnimationSettings > GetScopedAnimationSettings ()
Private Attributes
bool is_animating_closed_ = false
bool is_setting_popup_bounds_ = false
Constructor & Destructor Documentation
AutocompletePopupWidget() [1/2]
OmniboxPopupContentsView::AutocompletePopupWidget::AutocompletePopupWidget (views::Widget * role_model) inline explicit
AutocompletePopupWidget() [2/2]
OmniboxPopupContentsView::AutocompletePopupWidget::AutocompletePopupWidget (const AutocompletePopupWidget &) delete
~AutocompletePopupWidget()
OmniboxPopupContentsView::AutocompletePopupWidget::~AutocompletePopupWidget () inline override
Member Function Documentation
CloseAnimated()
void OmniboxPopupContentsView::AutocompletePopupWidget::CloseAnimated () inline
References GetScopedAnimationSettings(), and is_animating_closed_.
GetScopedAnimationSettings()
std::unique_ptr<ui::ScopedLayerAnimationSettings> OmniboxPopupContentsView::AutocompletePopupWidget::GetScopedAnimationSettings () inline private
Referenced by CloseAnimated(), and ShowAnimated().
InitOmniboxPopup()
void OmniboxPopupContentsView::AutocompletePopupWidget::InitOmniboxPopup (views::Widget * parent_widget) inline
References RoundedOmniboxResultsFrame::OnBeforeWidgetInit().
is_setting_popup_bounds()
bool OmniboxPopupContentsView::AutocompletePopupWidget::is_setting_popup_bounds () const inline
References is_setting_popup_bounds_.
OnGestureEvent()
void OmniboxPopupContentsView::AutocompletePopupWidget::OnGestureEvent (ui::GestureEvent * event) inline override
References is_animating_closed_.
OnMouseEvent()
void OmniboxPopupContentsView::AutocompletePopupWidget::OnMouseEvent (ui::MouseEvent * event) inline override
References is_animating_closed_.
OnNativeWidgetDestroying()
void OmniboxPopupContentsView::AutocompletePopupWidget::OnNativeWidgetDestroying () inline override
operator=()
AutocompletePopupWidget& OmniboxPopupContentsView::AutocompletePopupWidget::operator= (const AutocompletePopupWidget &) delete
SetPopupContentsView()
void OmniboxPopupContentsView::AutocompletePopupWidget::SetPopupContentsView (OmniboxPopupContentsView * contents) inline
References OmniboxPopupContentsView::location_bar_view_, and RoundedOmniboxResultsFrame::RoundedOmniboxResultsFrame().
SetTargetBounds()
void OmniboxPopupContentsView::AutocompletePopupWidget::SetTargetBounds (const gfx::Rect & bounds) inline
References is_setting_popup_bounds_.
ShowAnimated()
void OmniboxPopupContentsView::AutocompletePopupWidget::ShowAnimated () inline
References GetScopedAnimationSettings().
Member Data Documentation
is_animating_closed_
bool OmniboxPopupContentsView::AutocompletePopupWidget::is_animating_closed_ = false private
Referenced by CloseAnimated(), OnGestureEvent(), and OnMouseEvent().
is_setting_popup_bounds_
bool OmniboxPopupContentsView::AutocompletePopupWidget::is_setting_popup_bounds_ = false private
Referenced by is_setting_popup_bounds(), and SetTargetBounds().
The documentation for this class was generated from the following file:
chrome/browser/ui/views/omnibox/omnibox_popup_contents_view.cc