Chromium Omnibox: OmniboxPopupModel Class Reference
OmniboxPopupModel Class Reference
#include <omnibox_popup_model.h>
Classes
struct Selection
Public Types
enum Direction { kForward , kBackward }
enum Step { kWholeLine , kStateOrLine , kAllLines }
enum LineState {
FOCUSED_BUTTON_HEADER = 0 , NORMAL = 1 , KEYWORD_MODE = 2 , FOCUSED_BUTTON_TAB_SWITCH = 3 ,
FOCUSED_BUTTON_ACTION = 4 , FOCUSED_BUTTON_REMOVE_SUGGESTION = 5 , LINE_STATE_MAX_VALUE
}
Public Member Functions
OmniboxPopupModel (OmniboxPopupView *popup_view, OmniboxEditModel *edit_model, PrefService *pref_service)
~OmniboxPopupModel ()
OmniboxPopupModel (const OmniboxPopupModel &)=delete
OmniboxPopupModel & operator= (const OmniboxPopupModel &)=delete
bool IsOpen () const
OmniboxPopupView * view () const
OmniboxEditModel * edit_model () const
AutocompleteController * autocomplete_controller () const
const AutocompleteResult & result () const
Selection selection () const
size_t selected_line () const
LineState selected_line_state () const
void SetSelection (Selection new_selection, bool reset_to_default=false, bool force_update_ui=false)
void SetSelectedLineState (LineState new_state)
void ResetToInitialState ()
void TryDeletingLine (size_t line)
bool IsStarredMatch (const AutocompleteMatch &match) const
bool SelectionOnInitialLine () const
void OnResultChanged ()
const SkBitmap * RichSuggestionBitmapAt (int result_index) const
void SetRichSuggestionBitmap (int result_index, const SkBitmap &bitmap)
gfx::Image GetMatchIcon (const AutocompleteMatch &match, SkColor vector_icon_color)
OmniboxEditModel * edit_model ()
std::vector< Selection > GetAllAvailableSelectionsSorted (Direction direction, Step step) const
Selection GetNextSelection (Direction direction, Step step) const
Selection StepSelection (Direction direction, Step step)
bool IsControlPresentOnMatch (Selection selection) const
bool TriggerSelectionAction (Selection selection, base::TimeTicks timestamp=base::TimeTicks())
std::u16string GetAccessibilityLabelForCurrentSelection (const std::u16string &match_text, bool include_positional_info, int *label_prefix_length=nullptr)
Static Public Attributes
static const size_t kNoMatch = static_cast<size_t>(-1)
Private Member Functions
void OnFaviconFetched (const GURL &page_url, const gfx::Image &icon)
Private Attributes
std::map< int, SkBitmap > rich_suggestion_bitmaps_
OmniboxPopupView * view_
OmniboxEditModel * edit_model_
PrefService *const pref_service_
Selection selection_
GURL old_focused_url_
base::WeakPtrFactory< OmniboxPopupModel > weak_factory_ {this}
Member Enumeration Documentation
Direction
enum OmniboxPopupModel::Direction
Enumerator
kForward
kBackward
LineState
enum OmniboxPopupModel::LineState
Enumerator
FOCUSED_BUTTON_HEADER
NORMAL
KEYWORD_MODE
FOCUSED_BUTTON_TAB_SWITCH
FOCUSED_BUTTON_ACTION
FOCUSED_BUTTON_REMOVE_SUGGESTION
LINE_STATE_MAX_VALUE
Step
enum OmniboxPopupModel::Step
Enumerator
kWholeLine
kStateOrLine
kAllLines
Constructor & Destructor Documentation
OmniboxPopupModel() [1/2]
OmniboxPopupModel::OmniboxPopupModel (OmniboxPopupView * popup_view, OmniboxEditModel * edit_model, PrefService * pref_service)
Referenced by OmniboxPopupContentsView::OmniboxPopupContentsView().
~OmniboxPopupModel()
OmniboxPopupModel::~OmniboxPopupModel () default
OmniboxPopupModel() [2/2]
OmniboxPopupModel::OmniboxPopupModel (const OmniboxPopupModel &) delete
Member Function Documentation
autocomplete_controller()
AutocompleteController* OmniboxPopupModel::autocomplete_controller () const inline
References OmniboxEditModel::autocomplete_controller(), and edit_model_.
Referenced by result(), SetSelection(), TryDeletingLine(), and OmniboxPopupContentsView::UpdatePopupAppearance().
edit_model() [1/2]
OmniboxEditModel* OmniboxPopupModel::edit_model () inline
References edit_model_.
edit_model() [2/2]
OmniboxEditModel* OmniboxPopupModel::edit_model () const inline
References edit_model_.
Referenced by OmniboxSuggestionButtonRowView::ButtonPressed(), StepSelection(), TriggerSelectionAction(), and OmniboxSuggestionButtonRowView::UpdateFromModel().
GetAccessibilityLabelForCurrentSelection()
std::u16string OmniboxPopupModel::GetAccessibilityLabelForCurrentSelection (const std::u16string & match_text, bool include_positional_info, int * label_prefix_length = nullptr)
References AutocompleteMatch::action, FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, OmniboxPopupModel::Selection::IsButtonFocused(), IsControlPresentOnMatch(), AutocompleteResult::IsSuggestionGroupIdHidden(), KEYWORD_MODE, kNoMatch, OmniboxPopupModel::Selection::line, LINE_STATE_MAX_VALUE, AutocompleteResult::match_at(), NORMAL, pref_service_, result(), selection_, AutocompleteResult::size(), OmniboxPopupModel::Selection::state, AutocompleteMatch::suggestion_group_id, and AutocompleteMatchType::ToAccessibilityLabel().
Referenced by OmniboxResultView::GetAccessibleNodeData(), and OmniboxViewViews::SetAccessibilityLabel().
GetAllAvailableSelectionsSorted()
std::vector< OmniboxPopupModel::Selection > OmniboxPopupModel::GetAllAvailableSelectionsSorted (Direction direction, Step step) const
References FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, IsControlPresentOnMatch(), OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), kAllLines, KEYWORD_MODE, kForward, kStateOrLine, kWholeLine, NORMAL, result(), selection(), and AutocompleteResult::size().
Referenced by GetNextSelection().
GetMatchIcon()
gfx::Image OmniboxPopupModel::GetMatchIcon (const AutocompleteMatch & match, SkColor vector_icon_color)
References OmniboxEditModel::client(), AutocompleteMatch::destination_url, AutocompleteMatchType::DOCUMENT_SUGGESTION, edit_model_, OmniboxClient::GetFaviconForPageUrl(), OmniboxClient::GetIconIfExtensionMatch(), OmniboxClient::GetSizedIcon(), AutocompleteMatch::GetVectorIcon(), AutocompleteMatch::IsSearchType(), IsStarredMatch(), OnFaviconFetched(), AutocompleteMatch::type, and weak_factory_.
Referenced by OmniboxPopupContentsView::GetMatchIcon().
GetNextSelection()
OmniboxPopupModel::Selection OmniboxPopupModel::GetNextSelection (Direction direction, Step step) const
References GetAllAvailableSelectionsSorted(), kAllLines, kBackward, kForward, result(), and selection_.
Referenced by OmniboxEditModel::OnUpOrDownKeyPressed(), and StepSelection().
IsControlPresentOnMatch()
bool OmniboxPopupModel::IsControlPresentOnMatch (Selection selection) const
References FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), KEYWORD_MODE, OmniboxPopupModel::Selection::line, AutocompleteResult::match_at(), NORMAL, pref_service_, result(), selection(), OmniboxPopupModel::Selection::state, and AutocompleteMatch::suggestion_group_id.
Referenced by GetAccessibilityLabelForCurrentSelection(), GetAllAvailableSelectionsSorted(), and OmniboxResultView::UpdateRemoveSuggestionVisibility().
IsOpen()
bool OmniboxPopupModel::IsOpen () const
References OmniboxPopupView::IsOpen(), and view_.
Referenced by OmniboxController::ClearPopupKeywordMode(), OmniboxViewViews::OnBlur(), OmniboxController::OnResultChanged(), and OmniboxEditModel::PopupIsOpen().
IsStarredMatch()
bool OmniboxPopupModel::IsStarredMatch (const AutocompleteMatch & match) const
References OmniboxEditModel::client(), AutocompleteMatch::destination_url, edit_model_, and OmniboxClient::GetBookmarkModel().
Referenced by GetMatchIcon().
OnFaviconFetched()
void OmniboxPopupModel::OnFaviconFetched (const GURL & page_url, const gfx::Image & icon) private
References OmniboxPopupView::IsOpen(), AutocompleteMatch::IsSearchType(), AutocompleteResult::match_at(), OmniboxPopupView::OnMatchIconUpdated(), result(), AutocompleteResult::size(), and view_.
Referenced by GetMatchIcon().
OnResultChanged()
void OmniboxPopupModel::OnResultChanged ()
References OmniboxEditModel::controller(), AutocompleteResult::default_match(), AutocompleteMatch::destination_url, edit_model_, FOCUSED_BUTTON_TAB_SWITCH, AutocompleteMatch::has_tab_match, OmniboxPopupView::IsOpen(), kNoMatch, OmniboxPopupModel::Selection::line, AutocompleteResult::match_at(), NORMAL, old_focused_url_, OmniboxEditController::OnPopupVisibilityChanged(), result(), rich_suggestion_bitmaps_, selected_line(), selected_line_state(), selection(), selection_, OmniboxPopupModel::Selection::state, OmniboxPopupView::UpdatePopupAppearance(), and view_.
Referenced by OmniboxEditModel::OnCurrentMatchChanged(), and OmniboxController::OnResultChanged().
operator=()
OmniboxPopupModel& OmniboxPopupModel::operator= (const OmniboxPopupModel &) delete
ResetToInitialState()
void OmniboxPopupModel::ResetToInitialState ()
References AutocompleteResult::default_match(), kNoMatch, NORMAL, OmniboxPopupView::OnDragCanceled(), result(), SetSelection(), and view_.
Referenced by OmniboxEditModel::RevertTemporaryTextAndPopup().
result()
const AutocompleteResult& OmniboxPopupModel::result () const inline
References autocomplete_controller(), and AutocompleteController::result().
Referenced by GetAccessibilityLabelForCurrentSelection(), OmniboxResultView::GetAccessibleNodeData(), GetAllAvailableSelectionsSorted(), OmniboxPopupContentsView::GetIndexForPoint(), OmniboxPopupContentsView::GetMatchAtIndex(), GetNextSelection(), OmniboxPopupContentsView::HasMatchAt(), IsControlPresentOnMatch(), OmniboxSuggestionButtonRowView::match(), OnFaviconFetched(), OmniboxRowView::HeaderView::OnPrefChanged(), OnResultChanged(), OmniboxPopupContentsView::OnSuggestionGroupVisibilityUpdate(), ResetToInitialState(), SelectionOnInitialLine(), OmniboxRowView::HeaderView::SetHeader(), SetSelection(), TriggerSelectionAction(), TryDeletingLine(), and OmniboxPopupContentsView::UpdatePopupAppearance().
RichSuggestionBitmapAt()
const SkBitmap * OmniboxPopupModel::RichSuggestionBitmapAt (int result_index) const
References rich_suggestion_bitmaps_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
selected_line()
size_t OmniboxPopupModel::selected_line () const inline
References OmniboxPopupModel::Selection::line, and selection_.
Referenced by OmniboxPopupContentsView::GetSelectedIndex(), OmniboxPopupContentsView::GetSelectedResultView(), OnResultChanged(), SelectionOnInitialLine(), SetSelectedLineState(), SetSelection(), TriggerSelectionAction(), and TryDeletingLine().
selected_line_state()
LineState OmniboxPopupModel::selected_line_state () const inline
References selection_, and OmniboxPopupModel::Selection::state.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxEditModel::ClearKeyword(), OmniboxController::ClearPopupKeywordMode(), OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxResultView::GetMatchSelected(), OmniboxResultView::OmniboxResultView(), and OnResultChanged().
selection()
Selection OmniboxPopupModel::selection () const inline
References selection_.
Referenced by OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility(), GetAllAvailableSelectionsSorted(), OmniboxViewViews::HandleKeyEvent(), OmniboxRowView::HeaderView::HeaderView(), IsControlPresentOnMatch(), OmniboxSuggestionRowButton::OmniboxSuggestionRowButton(), OnResultChanged(), OmniboxResultView::OnSelectionStateChanged(), StepSelection(), TriggerSelectionAction(), and OmniboxRowView::HeaderView::UpdateUI().
SelectionOnInitialLine()
bool OmniboxPopupModel::SelectionOnInitialLine () const
References AutocompleteResult::default_match(), kNoMatch, result(), and selected_line().
SetRichSuggestionBitmap()
void OmniboxPopupModel::SetRichSuggestionBitmap (int result_index, const SkBitmap & bitmap)
References rich_suggestion_bitmaps_, OmniboxPopupView::UpdatePopupAppearance(), and view_.
Referenced by OmniboxController::SetRichSuggestionBitmap().
SetSelectedLineState()
void OmniboxPopupModel::SetSelectedLineState (LineState new_state) inline
References selected_line(), and SetSelection().
Referenced by OmniboxEditModel::AcceptKeyword(), OmniboxController::ClearPopupKeywordMode(), OmniboxViewViews::OnMousePressed(), and OmniboxPopupContentsView::UnselectButton().
SetSelection()
void OmniboxPopupModel::SetSelection (Selection new_selection, bool reset_to_default = false, bool force_update_ui = false)
References AutocompleteMatch::additional_text, AutocompleteMatch::associated_keyword, autocomplete_controller(), OmniboxEditModel::client(), AutocompleteMatch::destination_url, edit_model_, AutocompleteMatch::fill_into_edit, FOCUSED_BUTTON_HEADER, AutocompleteMatch::GetKeywordUIState(), OmniboxClient::GetTemplateURLService(), AutocompleteMatch::inline_autocompletion, OmniboxPopupModel::Selection::IsButtonFocused(), KEYWORD_MODE, kNoMatch, OmniboxPopupModel::Selection::line, AutocompleteResult::match_at(), old_focused_url_, OmniboxEditModel::OnPopupDataChanged(), OmniboxPopupView::OnSelectionChanged(), AutocompleteMatch::prefix_autocompletion, OmniboxPopupView::ProvideButtonFocusHint(), result(), selected_line(), selection_, OmniboxEditModel::SetAccessibilityLabel(), AutocompleteMatch::split_autocompletion, OmniboxPopupModel::Selection::state, AutocompleteController::Stop(), and view_.
Referenced by OmniboxSuggestionButtonRowView::ButtonPressed(), OmniboxEditModel::OnUpOrDownKeyPressed(), ResetToInitialState(), OmniboxPopupContentsView::SetSelectedIndex(), SetSelectedLineState(), StepSelection(), and TryDeletingLine().
StepSelection()
OmniboxPopupModel::Selection OmniboxPopupModel::StepSelection (Direction direction, Step step)
References OmniboxEditModel::AcceptKeyword(), OmniboxEditModel::ClearKeyword(), edit_model(), GetNextSelection(), selection(), selection_, and SetSelection().
Referenced by OmniboxViewViews::HandleEarlyTabActions(), and OmniboxViewViews::HandleKeyEvent().
TriggerSelectionAction()
bool OmniboxPopupModel::TriggerSelectionAction (Selection selection, base::TimeTicks timestamp = base::TimeTicks())
References edit_model(), OmniboxEditModel::ExecuteAction(), FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, omnibox::HIDDEN, AutocompleteResult::IsSuggestionGroupIdHidden(), OmniboxPopupModel::Selection::line, AutocompleteResult::match_at(), OmniboxEditModel::OpenMatch(), pref_service_, result(), selected_line(), selection(), omnibox::SetSuggestionGroupVisibility(), omnibox::SHOWN, OmniboxPopupModel::Selection::state, and TryDeletingLine().
Referenced by OmniboxResultView::ButtonPressed(), OmniboxSuggestionButtonRowView::ButtonPressed(), OmniboxViewViews::HandleKeyEvent(), OmniboxRowView::HeaderView::HeaderToggleButtonPressed(), and OmniboxRowView::HeaderView::OnMouseReleased().
TryDeletingLine()
void OmniboxPopupModel::TryDeletingLine (size_t line)
References autocomplete_controller(), AutocompleteController::DeleteMatch(), kNoMatch, AutocompleteResult::match_at(), NORMAL, result(), selected_line(), SetSelection(), AutocompleteController::Stop(), and AutocompleteMatch::SupportsDeletion().
Referenced by OmniboxViewViews::HandleKeyEvent(), and TriggerSelectionAction().
view()
OmniboxPopupView* OmniboxPopupModel::view () const inline
References view_.
Member Data Documentation
edit_model_
OmniboxEditModel* OmniboxPopupModel::edit_model_ private
Referenced by autocomplete_controller(), edit_model(), GetMatchIcon(), IsStarredMatch(), OnResultChanged(), and SetSelection().
kNoMatch
const size_t OmniboxPopupModel::kNoMatch = static_cast<size_t>(-1) static
Referenced by GetAccessibilityLabelForCurrentSelection(), OmniboxPopupContentsView::GetIndexForPoint(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxPopupContentsView::GetSelectedResultView(), OnResultChanged(), OmniboxPopupContentsView::OnSelectionChanged(), OmniboxEditModel::PasteAndGo(), ResetToInitialState(), SelectionOnInitialLine(), OmniboxViewViews::SetAccessibilityLabel(), SetSelection(), AutocompleteMatchType::ToAccessibilityLabel(), and TryDeletingLine().
old_focused_url_
GURL OmniboxPopupModel::old_focused_url_ private
Referenced by OnResultChanged(), and SetSelection().
pref_service_
PrefService* const OmniboxPopupModel::pref_service_ private
Referenced by GetAccessibilityLabelForCurrentSelection(), IsControlPresentOnMatch(), and TriggerSelectionAction().
rich_suggestion_bitmaps_
std::map<int, SkBitmap> OmniboxPopupModel::rich_suggestion_bitmaps_ private
Referenced by OnResultChanged(), RichSuggestionBitmapAt(), and SetRichSuggestionBitmap().
selection_
Selection OmniboxPopupModel::selection_ private
Referenced by GetAccessibilityLabelForCurrentSelection(), GetNextSelection(), OnResultChanged(), selected_line(), selected_line_state(), selection(), SetSelection(), and StepSelection().
view_
OmniboxPopupView* OmniboxPopupModel::view_ private
Referenced by IsOpen(), OnFaviconFetched(), OnResultChanged(), ResetToInitialState(), SetRichSuggestionBitmap(), SetSelection(), and view().
weak_factory_
base::WeakPtrFactory<OmniboxPopupModel> OmniboxPopupModel::weak_factory_ {this} private
Referenced by GetMatchIcon().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_popup_model.h
components/omnibox/browser/omnibox_popup_model.cc