Chromium Omnibox: MostVisitedSitesProvider Class Reference
MostVisitedSitesProvider Class Reference
#include <most_visited_sites_provider.h>
Public Member Functions
MostVisitedSitesProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (MostVisitedSitesProviderTest, AllowMostVisitedSitesSuggestions)
~MostVisitedSitesProvider () override
void StartFetchTopSites ()
void StartFetchNTPTiles ()
void OnMostVisitedUrlsAvailable (const history::MostVisitedURLList &urls)
bool AllowMostVisitedSitesSuggestions (const AutocompleteInput &input) const
void OnURLsAvailable (const std::map< ntp_tiles::SectionType, ntp_tiles::NTPTilesVector > &sections) override
void OnIconMadeAvailable (const GURL &site_url) override
Private Attributes
ntp_tiles::MostVisitedSites * most_visited_sites_ {}
AutocompleteProviderClient *const client_
AutocompleteProviderListener *const listener_
base::WeakPtrFactory< MostVisitedSitesProvider > request_weak_ptr_factory_
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
MostVisitedSitesProvider()
MostVisitedSitesProvider::MostVisitedSitesProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener)
~MostVisitedSitesProvider()
MostVisitedSitesProvider::~MostVisitedSitesProvider () override private default
Member Function Documentation
AllowMostVisitedSitesSuggestions()
bool MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions (const AutocompleteInput & input) const private
References client_, AutocompleteInput::current_page_classification(), AutocompleteInput::current_url(), omnibox::DEFAULT, AutocompleteInput::focus_type(), AutocompleteProviderClient::GetEmbedderRepresentationOfAboutScheme(), AutocompleteProviderClient::IsOffTheRecord(), and AutocompleteInput::type().
Referenced by Start().
FRIEND_TEST_ALL_PREFIXES()
MostVisitedSitesProvider::FRIEND_TEST_ALL_PREFIXES (MostVisitedSitesProviderTest , AllowMostVisitedSitesSuggestions) private
OnIconMadeAvailable()
void MostVisitedSitesProvider::OnIconMadeAvailable (const GURL & site_url) override private
OnMostVisitedUrlsAvailable()
void MostVisitedSitesProvider::OnMostVisitedUrlsAvailable (const history::MostVisitedURLList & urls) private
References client_, listener_, AutocompleteProvider::matches_, and AutocompleteProviderListener::OnProviderUpdate().
Referenced by StartFetchTopSites().
OnURLsAvailable()
void MostVisitedSitesProvider::OnURLsAvailable (const std::map< ntp_tiles::SectionType, ntp_tiles::NTPTilesVector > & sections) override private
References client_, listener_, AutocompleteProvider::matches_, and AutocompleteProviderListener::OnProviderUpdate().
Start()
void MostVisitedSitesProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References AllowMostVisitedSitesSuggestions(), AutocompleteInput::current_page_classification(), StartFetchNTPTiles(), StartFetchTopSites(), and Stop().
StartFetchNTPTiles()
void MostVisitedSitesProvider::StartFetchNTPTiles () private
References client_, AutocompleteProviderClient::GetNtpMostVisitedSites(), and most_visited_sites_.
Referenced by Start().
StartFetchTopSites()
void MostVisitedSitesProvider::StartFetchTopSites () private
References client_, AutocompleteProviderClient::GetTopSites(), OnMostVisitedUrlsAvailable(), and request_weak_ptr_factory_.
Referenced by Start().
Stop()
void MostVisitedSitesProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::matches_, most_visited_sites_, and request_weak_ptr_factory_.
Referenced by Start().
Member Data Documentation
client_
AutocompleteProviderClient* const MostVisitedSitesProvider::client_ private
Referenced by AllowMostVisitedSitesSuggestions(), OnMostVisitedUrlsAvailable(), OnURLsAvailable(), StartFetchNTPTiles(), and StartFetchTopSites().
listener_
AutocompleteProviderListener* const MostVisitedSitesProvider::listener_ private
Referenced by OnMostVisitedUrlsAvailable(), and OnURLsAvailable().
most_visited_sites_
ntp_tiles::MostVisitedSites* MostVisitedSitesProvider::most_visited_sites_ {} private
Referenced by StartFetchNTPTiles(), and Stop().
request_weak_ptr_factory_
base::WeakPtrFactory<MostVisitedSitesProvider> MostVisitedSitesProvider::request_weak_ptr_factory_ private
Initial value:
{
      this}
Referenced by StartFetchTopSites(), and Stop().
The documentation for this class was generated from the following files:
components/omnibox/browser/most_visited_sites_provider.h
components/omnibox/browser/most_visited_sites_provider.cc