Chromium Omnibox: OnDeviceModelUpdateListener Class Reference
OnDeviceModelUpdateListener Class Reference
#include <on_device_model_update_listener.h>
Public Member Functions
void OnModelUpdate (const base::FilePath &model_dir)
std::string model_filename () const
Static Public Member Functions
static OnDeviceModelUpdateListener * GetInstance ()
Private Member Functions
void ResetListenerForTest ()
OnDeviceModelUpdateListener ()
~OnDeviceModelUpdateListener ()
OnDeviceModelUpdateListener (const OnDeviceModelUpdateListener &)=delete
OnDeviceModelUpdateListener & operator= (const OnDeviceModelUpdateListener &)=delete
THREAD_CHECKER (thread_checker_)
Private Attributes
base::FilePath model_dir_
std::string model_filename_
Friends
class base::NoDestructor< OnDeviceModelUpdateListener >
class OnDeviceHeadProviderTest
Constructor & Destructor Documentation
OnDeviceModelUpdateListener() [1/2]
OnDeviceModelUpdateListener::OnDeviceModelUpdateListener () private default
~OnDeviceModelUpdateListener()
OnDeviceModelUpdateListener::~OnDeviceModelUpdateListener () private default
OnDeviceModelUpdateListener() [2/2]
OnDeviceModelUpdateListener::OnDeviceModelUpdateListener (const OnDeviceModelUpdateListener &) private delete
Member Function Documentation
GetInstance()
OnDeviceModelUpdateListener * OnDeviceModelUpdateListener::GetInstance () static
Referenced by OnDeviceHeadProvider::GetOnDeviceHeadModelFilename(), and OnModelUpdate().
model_filename()
std::string OnDeviceModelUpdateListener::model_filename () const
References model_filename_.
OnModelUpdate()
void OnDeviceModelUpdateListener::OnModelUpdate (const base::FilePath & model_dir)
References GetInstance(), model_dir_, and model_filename_.
operator=()
OnDeviceModelUpdateListener& OnDeviceModelUpdateListener::operator= (const OnDeviceModelUpdateListener &) private delete
ResetListenerForTest()
void OnDeviceModelUpdateListener::ResetListenerForTest () private
References model_dir_, and model_filename_.
THREAD_CHECKER()
OnDeviceModelUpdateListener::THREAD_CHECKER (thread_checker_) private
Friends And Related Function Documentation
base::NoDestructor< OnDeviceModelUpdateListener >
friend class base::NoDestructor< OnDeviceModelUpdateListener > friend
OnDeviceHeadProviderTest
friend class OnDeviceHeadProviderTest friend
Member Data Documentation
model_dir_
base::FilePath OnDeviceModelUpdateListener::model_dir_ private
Referenced by OnModelUpdate(), and ResetListenerForTest().
model_filename_
std::string OnDeviceModelUpdateListener::model_filename_ private
Referenced by model_filename(), OnModelUpdate(), and ResetListenerForTest().
The documentation for this class was generated from the following files:
components/omnibox/browser/on_device_model_update_listener.h
components/omnibox/browser/on_device_model_update_listener.cc