Chromium Omnibox: ChromeOmniboxEditController Class Reference
ChromeOmniboxEditController Class Reference
#include <chrome_omnibox_edit_controller.h>
Public Member Functions
ChromeOmniboxEditController (const ChromeOmniboxEditController &)=delete
ChromeOmniboxEditController & operator= (const ChromeOmniboxEditController &)=delete
void OnAutocompleteAccept (const GURL &destination_url, TemplateURLRef::PostContent *post_content, WindowOpenDisposition disposition, ui::PageTransition transition, AutocompleteMatchType::Type type, base::TimeTicks match_selection_timestamp, bool destination_url_entered_without_scheme, const std::u16string &text, const AutocompleteMatch &match, const AutocompleteMatch &alternative_nav_match) override
void OnInputInProgress (bool in_progress) override
virtual content::WebContents * GetWebContents ()
virtual void UpdateWithoutTabRestore ()
CommandUpdater * command_updater ()
const CommandUpdater * command_updater () const
Public Member Functions inherited from OmniboxEditController
virtual void OnChanged ()
virtual void OnPopupVisibilityChanged ()
virtual LocationBarModel * GetLocationBarModel ()=0
virtual const LocationBarModel * GetLocationBarModel () const =0
Protected Member Functions
ChromeOmniboxEditController (Browser *browser, Profile *profile, CommandUpdater *command_updater)
~ChromeOmniboxEditController () override
Protected Member Functions inherited from OmniboxEditController
OmniboxEditController ()
virtual ~OmniboxEditController ()
OmniboxEditController (const OmniboxEditController &)=delete
OmniboxEditController & operator= (const OmniboxEditController &)=delete
GURL destination_url () const
TemplateURLRef::PostContent * post_content () const
WindowOpenDisposition disposition () const
ui::PageTransition transition () const
base::TimeTicks match_selection_timestamp () const
bool destination_url_entered_without_scheme () const
Private Attributes
Browser *const browser_
Profile *const profile_
CommandUpdater *const command_updater_
Constructor & Destructor Documentation
ChromeOmniboxEditController() [1/2]
ChromeOmniboxEditController::ChromeOmniboxEditController (const ChromeOmniboxEditController &) delete
ChromeOmniboxEditController() [2/2]
ChromeOmniboxEditController::ChromeOmniboxEditController (Browser * browser, Profile * profile, CommandUpdater * command_updater) protected
~ChromeOmniboxEditController()
ChromeOmniboxEditController::~ChromeOmniboxEditController () override protected
Member Function Documentation
command_updater() [1/2]
CommandUpdater* ChromeOmniboxEditController::command_updater () inline
References command_updater_.
Referenced by ChromeOmniboxClient::IsPasteAndGoEnabled().
command_updater() [2/2]
const CommandUpdater* ChromeOmniboxEditController::command_updater () const inline
References command_updater_.
GetWebContents()
content::WebContents * ChromeOmniboxEditController::GetWebContents () virtual
Referenced by ChromeOmniboxClient::CurrentPageExists(), ChromeOmniboxClient::DiscardNonCommittedNavigations(), ChromeOmniboxClient::DoPrerender(), ChromeOmniboxClient::GetFavicon(), ChromeOmniboxClient::GetSessionID(), ChromeOmniboxClient::GetTitle(), ChromeOmniboxClient::GetURL(), ChromeOmniboxClient::IsLoading(), OnAutocompleteAccept(), ChromeOmniboxClient::OnFocusChanged(), ChromeOmniboxClient::OnInputStateChanged(), ChromeOmniboxClient::OpenUpdateChromeDialog(), and ChromeOmniboxClient::ProcessExtensionKeyword().
OnAutocompleteAccept()
void ChromeOmniboxEditController::OnAutocompleteAccept (const GURL & destination_url, TemplateURLRef::PostContent * post_content, WindowOpenDisposition disposition, ui::PageTransition transition, AutocompleteMatchType::Type type, base::TimeTicks match_selection_timestamp, bool destination_url_entered_without_scheme, const std::u16string & text, const AutocompleteMatch & match, const AutocompleteMatch & alternative_nav_match) override virtual
Reimplemented from OmniboxEditController.
References browser_, ChromeOmniboxNavigationObserver::Create(), AutocompleteMatch::destination_url, OmniboxEditController::destination_url(), OmniboxEditController::destination_url_entered_without_scheme(), OmniboxEditController::disposition(), GetWebContents(), OmniboxEditController::match_selection_timestamp(), OmniboxEditController::OnAutocompleteAccept(), OmniboxEditController::post_content(), profile_, and OmniboxEditController::transition().
OnInputInProgress()
void ChromeOmniboxEditController::OnInputInProgress (bool in_progress) override virtual
Reimplemented from OmniboxEditController.
References UpdateWithoutTabRestore().
operator=()
ChromeOmniboxEditController& ChromeOmniboxEditController::operator= (const ChromeOmniboxEditController &) delete
UpdateWithoutTabRestore()
void ChromeOmniboxEditController::UpdateWithoutTabRestore () virtual
Referenced by OnInputInProgress().
Member Data Documentation
browser_
Browser* const ChromeOmniboxEditController::browser_ private
Referenced by OnAutocompleteAccept().
command_updater_
CommandUpdater* const ChromeOmniboxEditController::command_updater_ private
Referenced by command_updater().
profile_
Profile* const ChromeOmniboxEditController::profile_ private
Referenced by OnAutocompleteAccept().
The documentation for this class was generated from the following files:
chrome/browser/ui/omnibox/chrome_omnibox_edit_controller.h
chrome/browser/ui/omnibox/chrome_omnibox_edit_controller.cc