Chromium Omnibox: CompareWithDemoteByType< Match > Class Template Reference
CompareWithDemoteByType< Match > Class Template Reference
#include <match_compare.h>
Public Member Functions
CompareWithDemoteByType (PageClassification page_classification)
int GetDemotedRelevance (const Match &match) const
bool operator() (const Match &elem1, const Match &elem2)
Private Attributes
OmniboxFieldTrial::DemotionMultipliers demotions_
Constructor & Destructor Documentation
CompareWithDemoteByType()
template<class Match > CompareWithDemoteByType< Match >::CompareWithDemoteByType (PageClassification page_classification) inline
References CompareWithDemoteByType< Match >::demotions_, and OmniboxFieldTrial::GetDemotionsByType().
Member Function Documentation
GetDemotedRelevance()
template<class Match > int CompareWithDemoteByType< Match >::GetDemotedRelevance (const Match & match) const inline
References CompareWithDemoteByType< Match >::demotions_.
Referenced by AutocompleteResult::CalculateNumMatches(), AutocompleteResult::CalculateNumMatchesPerUrlCount(), AutocompleteResult::MaybeCullTailSuggestions(), and CompareWithDemoteByType< Match >::operator()().
operator()()
template<class Match > bool CompareWithDemoteByType< Match >::operator() (const Match & elem1, const Match & elem2) inline
References CompareWithDemoteByType< Match >::GetDemotedRelevance().
Member Data Documentation
demotions_
template<class Match > OmniboxFieldTrial::DemotionMultipliers CompareWithDemoteByType< Match >::demotions_ private
Referenced by CompareWithDemoteByType< Match >::CompareWithDemoteByType(), and CompareWithDemoteByType< Match >::GetDemotedRelevance().
The documentation for this class was generated from the following file:
components/omnibox/browser/match_compare.h