Chromium Omnibox: HistoryProvider Class Reference
HistoryProvider Class Reference
#include <history_provider.h>
Public Member Functions
void DeleteMatch (const AutocompleteMatch &match) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Start (const AutocompleteInput &input, bool minimal_changes)=0
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static ACMatchClassifications SpansFromTermMatch (const TermMatches &matches, size_t text_length, bool is_url)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Member Functions
HistoryProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
~HistoryProvider () override
HistoryProvider (const HistoryProvider &)=delete
HistoryProvider & operator= (const HistoryProvider &)=delete
void DeleteMatchFromMatches (const AutocompleteMatch &match)
AutocompleteProviderClient * client () const
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Private Attributes
AutocompleteProviderClient * client_
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
HistoryProvider() [1/2]
HistoryProvider::HistoryProvider (AutocompleteProvider::Type type, AutocompleteProviderClient * client) protected
~HistoryProvider()
HistoryProvider::~HistoryProvider () override protected
HistoryProvider() [2/2]
HistoryProvider::HistoryProvider (const HistoryProvider &) protected delete
Member Function Documentation
client()
AutocompleteProviderClient* HistoryProvider::client () const inline protected
References client_.
Referenced by HistoryQuickProvider::FindMaxMatchScore(), HistoryURLProvider::HistoryMatchToACMatch(), HistoryQuickProvider::QuickMatchToACMatch(), and HistoryURLProvider::Start().
DeleteMatch()
void HistoryProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
References client_, AutocompleteMatch::deletable, DeleteMatchFromMatches(), AutocompleteMatch::destination_url, AutocompleteProvider::done_, and AutocompleteProviderClient::GetHistoryService().
DeleteMatchFromMatches()
void HistoryProvider::DeleteMatchFromMatches (const AutocompleteMatch & match) protected
References client_, AutocompleteMatch::destination_url, AutocompleteProviderClient::GetBookmarkModel(), AutocompleteProvider::matches_, AutocompleteMatch::type, and AutocompleteMatchType::URL_WHAT_YOU_TYPED.
Referenced by DeleteMatch().
operator=()
HistoryProvider& HistoryProvider::operator= (const HistoryProvider &) protected delete
SpansFromTermMatch()
ACMatchClassifications HistoryProvider::SpansFromTermMatch (const TermMatches & matches, size_t text_length, bool is_url) static
References ClassifyTermMatches(), AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteProvider::matches(), AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatch::ACMatchClassification::URL.
Member Data Documentation
client_
AutocompleteProviderClient* HistoryProvider::client_ private
Referenced by client(), DeleteMatch(), and DeleteMatchFromMatches().
The documentation for this class was generated from the following files:
components/omnibox/browser/history_provider.h
components/omnibox/browser/history_provider.cc