Chromium Omnibox: SearchSuggestionParser Class Reference
SearchSuggestionParser Class Reference
#include <search_suggestion_parser.h>
Classes
class NavigationResult
class Result
struct Results
class SuggestResult
Public Types
typedef std::map< int, std::u16string > HeadersMap
typedef std::vector< SuggestResult > SuggestResults
typedef std::vector< NavigationResult > NavigationResults
typedef std::vector< base::Value > ExperimentStats
Public Member Functions
SearchSuggestionParser ()=delete
SearchSuggestionParser (const SearchSuggestionParser &)=delete
SearchSuggestionParser & operator= (const SearchSuggestionParser &)=delete
Static Public Member Functions
static std::string ExtractJsonData (const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)
static std::unique_ptr< base::Value > DeserializeJsonData (base::StringPiece json_data)
static bool ParseSuggestResults (const base::Value &root_val, const AutocompleteInput &input, const AutocompleteSchemeClassifier &scheme_classifier, int default_result_relevance, bool is_keyword_result, Results *results)
Static Public Attributes
static const int kNoSuggestionGroupId = -1
Member Typedef Documentation
ExperimentStats
typedef std::vector<base::Value> SearchSuggestionParser::ExperimentStats
HeadersMap
typedef std::map<int, std::u16string> SearchSuggestionParser::HeadersMap
NavigationResults
typedef std::vector<NavigationResult> SearchSuggestionParser::NavigationResults
SuggestResults
typedef std::vector<SuggestResult> SearchSuggestionParser::SuggestResults
Constructor & Destructor Documentation
SearchSuggestionParser() [1/2]
SearchSuggestionParser::SearchSuggestionParser () delete
SearchSuggestionParser() [2/2]
SearchSuggestionParser::SearchSuggestionParser (const SearchSuggestionParser &) delete
Member Function Documentation
DeserializeJsonData()
std::unique_ptr< base::Value > SearchSuggestionParser::DeserializeJsonData (base::StringPiece json_data) static
Referenced by LLVMFuzzerTestOneInput(), ZeroSuggestProvider::MaybeUseCachedSuggestions(), SearchProvider::OnURLLoadComplete(), and ZeroSuggestProvider::UpdateResults().
ExtractJsonData()
std::string SearchSuggestionParser::ExtractJsonData (const network::SimpleURLLoader * source, std::unique_ptr< std::string > response_body) static
Referenced by LLVMFuzzerTestOneInput(), DocumentProvider::OnURLLoadComplete(), SearchProvider::OnURLLoadComplete(), and ZeroSuggestProvider::OnURLLoadComplete().
operator=()
SearchSuggestionParser& SearchSuggestionParser::operator= (const SearchSuggestionParser &) delete
ParseSuggestResults()
bool SearchSuggestionParser::ParseSuggestResults (const base::Value & root_val, const AutocompleteInput & input, const AutocompleteSchemeClassifier & scheme_classifier, int default_result_relevance, bool is_keyword_result, Results * results) static
References AutocompleteMatchType::CALCULATOR, SearchSuggestionParser::Results::experiment_stats, SearchSuggestionParser::Results::field_trial_triggered, SearchSuggestionParser::Results::headers_map, SearchSuggestionParser::Results::hidden_group_ids, SearchSuggestionParser::Results::metadata, SearchSuggestionParser::Results::navigation_results, AutocompleteMatchType::NAVSUGGEST, AutocompleteMatchType::NAVSUGGEST_PERSONALIZED, SuggestionAnswer::ParseAnswer(), SearchSuggestionParser::Results::relevances_from_server, AutocompleteMatchType::SEARCH_SUGGEST, SearchSuggestionParser::Results::suggest_results, AutocompleteInput::text(), SuggestionAnswer::type(), and SearchSuggestionParser::Results::verbatim_relevance.
Referenced by LLVMFuzzerTestOneInput(), and BaseSearchProvider::ParseSuggestResults().
Member Data Documentation
kNoSuggestionGroupId
const int SearchSuggestionParser::kNoSuggestionGroupId = -1 static
The documentation for this class was generated from the following files:
components/omnibox/browser/search_suggestion_parser.h
components/omnibox/browser/search_suggestion_parser.cc