Chromium Omnibox: AutocompleteResult Class Reference
AutocompleteResult Class Reference
#include <autocomplete_result.h>
Public Types
typedef ACMatches::const_iterator const_iterator
typedef ACMatches::iterator iterator
using MatchDedupComparator = std::pair< GURL, bool >
Public Member Functions
AutocompleteResult ()
~AutocompleteResult ()
AutocompleteResult (const AutocompleteResult &)=delete
AutocompleteResult & operator= (const AutocompleteResult &)=delete
void TransferOldMatches (const AutocompleteInput &input, AutocompleteResult *old_matches, TemplateURLService *template_url_service)
void AppendMatches (const AutocompleteInput &input, const ACMatches &matches)
void SortAndCull (const AutocompleteInput &input, TemplateURLService *template_url_service, const AutocompleteMatch *preserve_default_match=nullptr)
void GroupAndDemoteMatchesWithHeaders ()
void AttachPedalsToMatches (const AutocompleteInput &input, const AutocompleteProviderClient &client)
void ConvertOpenTabMatches (AutocompleteProviderClient *client, const AutocompleteInput *input)
bool HasCopiedMatches () const
size_t size () const
bool empty () const
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const AutocompleteMatch & match_at (size_t index) const
AutocompleteMatch * match_at (size_t index)
const AutocompleteMatch * default_match () const
const SearchSuggestionParser::HeadersMap & headers_map () const
const std::set< int > & hidden_group_ids () const
void Reset ()
void Swap (AutocompleteResult *other)
void CopyFrom (const AutocompleteResult &other)
void InlineTailPrefixes ()
size_t EstimateMemoryUsage () const
std::vector< MatchDedupComparator > GetMatchDedupComparators () const
std::u16string GetHeaderForGroupId (int suggestion_group_id) const
bool IsSuggestionGroupIdHidden (PrefService *prefs, int suggestion_group_id) const
void MergeHeadersMap (const SearchSuggestionParser::HeadersMap &headers_map)
void MergeHiddenGroupIds (const std::vector< int > &hidden_group_ids)
Static Public Member Functions
static size_t GetMaxMatches (bool is_zero_suggest=false)
static size_t GetDynamicMaxMatches ()
static ACMatches::const_iterator FindTopMatch (const AutocompleteInput &input, const ACMatches &matches)
static ACMatches::iterator FindTopMatch (const AutocompleteInput &input, ACMatches *matches)
static void DiscourageTopMatchFromBeingSearchEntity (ACMatches *matches)
static size_t CalculateNumMatches (bool is_zero_suggest, const ACMatches &matches, const CompareWithDemoteByType< AutocompleteMatch > &comparing_object)
static size_t CalculateNumMatchesPerUrlCount (const ACMatches &matches, const CompareWithDemoteByType< AutocompleteMatch > &comparing_object)
static GURL ComputeAlternateNavUrl (const AutocompleteInput &input, const AutocompleteMatch &match, AutocompleteProviderClient *provider_client)
static void LogAsynchronousUpdateMetrics (const std::vector< MatchDedupComparator > &old_result, const AutocompleteResult &new_result)
Static Public Attributes
static constexpr size_t kMaxAutocompletePositionValue = 30
Private Types
typedef std::map< AutocompleteProvider *, ACMatches > ProviderToMatches
typedef ACMatches::iterator::difference_type matches_difference_type
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, GroupSuggestionsBySearchVsURLHonorsProtectedSuggestions)
void BuildProviderToMatchesCopy (ProviderToMatches *provider_to_matches) const
void BuildProviderToMatchesMove (ProviderToMatches *provider_to_matches)
void MergeMatchesByProvider (ACMatches *old_matches, const ACMatches &new_matches)
void LimitNumberOfURLsShown (size_t max_matches, size_t max_url_count, const CompareWithDemoteByType< AutocompleteMatch > &comparing_object)
void DemoteOnDeviceSearchSuggestions ()
Static Private Member Functions
static void DeduplicateMatches (ACMatches *matches)
static bool HasMatchByDestination (const AutocompleteMatch &match, const ACMatches &matches)
static void MaybeCullTailSuggestions (ACMatches *matches, const CompareWithDemoteByType< AutocompleteMatch > &comparing_object)
static MatchDedupComparator GetMatchComparisonFields (const AutocompleteMatch &match)
static void GroupSuggestionsBySearchVsURL (iterator begin, iterator end)
Private Attributes
ACMatches matches_
SearchSuggestionParser::HeadersMap headers_map_
std::set< int > hidden_group_ids_
Friends
class HistoryURLProviderTest
Member Typedef Documentation
const_iterator
typedef ACMatches::const_iterator AutocompleteResult::const_iterator
iterator
typedef ACMatches::iterator AutocompleteResult::iterator
MatchDedupComparator
using AutocompleteResult::MatchDedupComparator = std::pair<GURL, bool>
matches_difference_type
typedef ACMatches::iterator::difference_type AutocompleteResult::matches_difference_type private
ProviderToMatches
typedef std::map<AutocompleteProvider*, ACMatches> AutocompleteResult::ProviderToMatches private
Constructor & Destructor Documentation
AutocompleteResult() [1/2]
AutocompleteResult::AutocompleteResult ()
References GetMaxMatches(), and matches_.
~AutocompleteResult()
AutocompleteResult::~AutocompleteResult ()
AutocompleteResult() [2/2]
AutocompleteResult::AutocompleteResult (const AutocompleteResult &) delete
Member Function Documentation
AppendMatches()
void AutocompleteResult::AppendMatches (const AutocompleteInput & input, const ACMatches & matches)
References AutocompleteMatchType::DOCUMENT_SUGGESTION, AutocompleteMatch::IsSearchType(), matches_, and AutocompleteMatch::SanitizeString().
Referenced by OmniboxEditModel::OpenMatch(), and AutocompleteController::UpdateResult().
AttachPedalsToMatches()
void AutocompleteResult::AttachPedalsToMatches (const AutocompleteInput & input, const AutocompleteProviderClient & client)
References OmniboxPedalProvider::FindReadyPedalMatch(), AutocompleteProviderClient::GetPedalProvider(), AutocompleteMatch::IsActionCompatibleType(), matches_, and OmniboxPedalProvider::set_field_trial_triggered().
Referenced by AutocompleteController::UpdateResult().
begin() [1/2]
AutocompleteResult::iterator AutocompleteResult::begin ()
References matches_.
begin() [2/2]
AutocompleteResult::const_iterator AutocompleteResult::begin () const
References matches_.
Referenced by default_match(), GroupSuggestionsBySearchVsURL(), HasCopiedMatches(), OmniboxMetricsProvider::RecordOmniboxOpenedURL(), SearchProvider::RegisterDisplayedAnswers(), TransferOldMatches(), AutocompleteController::UpdateAssociatedKeywords(), and AutocompleteController::UpdateKeywordDescriptions().
BuildProviderToMatchesCopy()
void AutocompleteResult::BuildProviderToMatchesCopy (ProviderToMatches * provider_to_matches) const private
Referenced by TransferOldMatches().
BuildProviderToMatchesMove()
void AutocompleteResult::BuildProviderToMatchesMove (ProviderToMatches * provider_to_matches) private
Referenced by TransferOldMatches().
CalculateNumMatches()
size_t AutocompleteResult::CalculateNumMatches (bool is_zero_suggest, const ACMatches & matches, const CompareWithDemoteByType< AutocompleteMatch > & comparing_object) static
References CalculateNumMatchesPerUrlCount(), CompareWithDemoteByType< Match >::GetDemotedRelevance(), GetMaxMatches(), and omnibox::kDynamicMaxAutocomplete.
Referenced by SortAndCull().
CalculateNumMatchesPerUrlCount()
size_t AutocompleteResult::CalculateNumMatchesPerUrlCount (const ACMatches & matches, const CompareWithDemoteByType< AutocompleteMatch > & comparing_object) static
References CompareWithDemoteByType< Match >::GetDemotedRelevance(), GetDynamicMaxMatches(), GetMaxMatches(), AutocompleteMatch::IsSearchType(), omnibox::kDynamicMaxAutocomplete, and OmniboxFieldTrial::kDynamicMaxAutocompleteUrlCutoffParam.
Referenced by CalculateNumMatches().
ComputeAlternateNavUrl()
GURL AutocompleteResult::ComputeAlternateNavUrl (const AutocompleteInput & input, const AutocompleteMatch & match, AutocompleteProviderClient * provider_client) static
References AutocompleteInput::canonicalized_url(), AutocompleteMatch::destination_url, omnibox::ENABLE_INTERCEPTION_CHECKS_AND_INFOBARS, omnibox::GetInterceptionChecksBehavior(), AutocompleteProviderClient::GetLocalState(), AutocompleteMatch::IsSearchType(), AutocompleteMatch::transition, AutocompleteInput::type(), and AutocompleteMatch::type.
Referenced by AutocompleteClassifier::Classify(), OmniboxEditModel::CurrentMatch(), and OmniboxEditModel::GetInfoForCurrentText().
ConvertOpenTabMatches()
void AutocompleteResult::ConvertOpenTabMatches (AutocompleteProviderClient * client, const AutocompleteInput * input)
References AutocompleteProviderClient::IsTabOpenWithURL(), and matches_.
Referenced by AutocompleteController::UpdateResult().
CopyFrom()
void AutocompleteResult::CopyFrom (const AutocompleteResult & other)
References matches_.
DeduplicateMatches()
void AutocompleteResult::DeduplicateMatches (ACMatches * matches) static private
References AutocompleteMatch::BetterDuplicateByIterator(), AutocompleteMatch::duplicate_matches, GetMatchComparisonFields(), AutocompleteMatch::stripped_destination_url, and AutocompleteMatch::UpgradeMatchWithPropertiesFrom().
Referenced by SortAndCull().
default_match()
const AutocompleteMatch * AutocompleteResult::default_match () const
References begin(), and end().
Referenced by OmniboxEditModel::GetInfoForCurrentText(), OmniboxEditModel::IsPopupSelectionOnInitialLine(), OmniboxEditModel::OnPopupResultChanged(), OmniboxEditModel::ResetPopupToInitialState(), SortAndCull(), AutocompleteController::Start(), and AutocompleteController::UpdateResult().
DemoteOnDeviceSearchSuggestions()
void AutocompleteResult::DemoteOnDeviceSearchSuggestions () private
References matches_, and OmniboxFieldTrial::OnDeviceHeadSuggestDemoteMode().
Referenced by SortAndCull().
DiscourageTopMatchFromBeingSearchEntity()
void AutocompleteResult::DiscourageTopMatchFromBeingSearchEntity (ACMatches * matches) static
References AutocompleteMatch::duplicate_matches, AutocompleteMatch::IsSearchType(), and AutocompleteMatchType::SEARCH_SUGGEST_ENTITY.
Referenced by SortAndCull().
empty()
bool AutocompleteResult::empty () const
References matches_.
Referenced by OmniboxPopupSelection::GetNextSelection(), SearchProvider::RegisterDisplayedAnswers(), AutocompleteController::StopHelper(), TransferOldMatches(), AutocompleteController::UpdateAssistedQueryStats(), and OmniboxPopupContentsView::UpdatePopupAppearance().
end() [1/2]
AutocompleteResult::iterator AutocompleteResult::end ()
References matches_.
end() [2/2]
AutocompleteResult::const_iterator AutocompleteResult::end () const
References matches_.
Referenced by default_match(), GroupSuggestionsBySearchVsURL(), HasCopiedMatches(), OmniboxMetricsProvider::RecordOmniboxOpenedURL(), TransferOldMatches(), AutocompleteController::UpdateAssociatedKeywords(), and AutocompleteController::UpdateKeywordDescriptions().
EstimateMemoryUsage()
size_t AutocompleteResult::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage(), and matches_.
Referenced by AutocompleteController::OnMemoryDump().
FindTopMatch() [1/2]
ACMatches::iterator AutocompleteResult::FindTopMatch (const AutocompleteInput & input, ACMatches * matches) static
References AutocompleteInput::current_page_classification(), AutocompleteMatch::MoreRelevant(), and AutocompleteInput::type().
FindTopMatch() [2/2]
ACMatches::const_iterator AutocompleteResult::FindTopMatch (const AutocompleteInput & input, const ACMatches & matches) static
Referenced by SearchProvider::ConvertResultsToAutocompleteMatches(), SearchProvider::EnforceConstraints(), SearchProvider::IsTopMatchSearchWithURLInput(), SearchProvider::RecordTopSuggestion(), and SortAndCull().
FRIEND_TEST_ALL_PREFIXES() [1/2]
AutocompleteResult::FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest , DemoteOnDeviceSearchSuggestions) private
FRIEND_TEST_ALL_PREFIXES() [2/2]
AutocompleteResult::FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest , GroupSuggestionsBySearchVsURLHonorsProtectedSuggestions) private
GetDynamicMaxMatches()
size_t AutocompleteResult::GetDynamicMaxMatches () static
References GetMaxMatches(), omnibox::kDynamicMaxAutocomplete, and OmniboxFieldTrial::kDynamicMaxAutocompleteIncreasedLimitParam.
Referenced by CalculateNumMatchesPerUrlCount(), SearchProvider::ConvertResultsToAutocompleteMatches(), and SearchProvider::PrefetchImages().
GetHeaderForGroupId()
std::u16string AutocompleteResult::GetHeaderForGroupId (int suggestion_group_id) const
References headers_map_.
Referenced by GroupAndDemoteMatchesWithHeaders(), and OmniboxPopupContentsView::UpdatePopupAppearance().
GetMatchComparisonFields()
std::pair< GURL, bool > AutocompleteResult::GetMatchComparisonFields (const AutocompleteMatch & match) static private
References AutocompleteMatchType::CALCULATOR, AutocompleteMatch::stripped_destination_url, and AutocompleteMatch::type.
Referenced by DeduplicateMatches(), GetMatchDedupComparators(), LogAsynchronousUpdateMetrics(), and SortAndCull().
GetMatchDedupComparators()
std::vector< AutocompleteResult::MatchDedupComparator > AutocompleteResult::GetMatchDedupComparators () const
References GetMatchComparisonFields().
Referenced by AutocompleteController::UpdateResult().
GetMaxMatches()
size_t AutocompleteResult::GetMaxMatches (bool is_zero_suggest = false) static
References kMaxAutocompletePositionValue, omnibox::kMaxZeroSuggestMatches, OmniboxFieldTrial::kMaxZeroSuggestMatchesParam, omnibox::kUIExperimentMaxAutocompleteMatches, and OmniboxFieldTrial::kUIMaxAutocompleteMatchesParam.
Referenced by AutocompleteResult(), CalculateNumMatches(), CalculateNumMatchesPerUrlCount(), GetDynamicMaxMatches(), and SortAndCull().
GroupAndDemoteMatchesWithHeaders()
void AutocompleteResult::GroupAndDemoteMatchesWithHeaders ()
References GetHeaderForGroupId(), and matches_.
Referenced by SortAndCull().
GroupSuggestionsBySearchVsURL()
void AutocompleteResult::GroupSuggestionsBySearchVsURL (iterator begin, iterator end) static private
References begin(), end(), AutocompleteMatch::IsSearchType(), AutocompleteMatch::ShouldBeSkippedForGroupBySearchVsUrl(), and AutocompleteMatch::type.
Referenced by SortAndCull().
HasCopiedMatches()
bool AutocompleteResult::HasCopiedMatches () const
References begin(), and end().
Referenced by AutocompleteController::StartExpireTimer().
HasMatchByDestination()
bool AutocompleteResult::HasMatchByDestination (const AutocompleteMatch & match, const ACMatches & matches) static private
References AutocompleteMatch::destination_url.
Referenced by MergeMatchesByProvider().
headers_map()
const SearchSuggestionParser::HeadersMap& AutocompleteResult::headers_map () const inline
References headers_map_.
Referenced by MergeHeadersMap().
hidden_group_ids()
const std::set<int>& AutocompleteResult::hidden_group_ids () const inline
References hidden_group_ids_.
Referenced by MergeHiddenGroupIds().
InlineTailPrefixes()
void AutocompleteResult::InlineTailPrefixes ()
References kACMatchPropertyContentsStartIndex, kACMatchPropertySuggestionText, matches_, and AutocompleteMatchType::SEARCH_SUGGEST_TAIL.
Referenced by AutocompleteController::InlineTailPrefixes().
IsSuggestionGroupIdHidden()
bool AutocompleteResult::IsSuggestionGroupIdHidden (PrefService * prefs, int suggestion_group_id) const
References omnibox::DEFAULT, omnibox::GetUserPreferenceForSuggestionGroupVisibility(), omnibox::HIDDEN, hidden_group_ids_, and omnibox::SHOWN.
Referenced by OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupSelection::IsControlPresentOnMatch(), OmniboxRowView::HeaderView::OnPrefChanged(), OmniboxPopupContentsView::OnSuggestionGroupVisibilityUpdate(), OmniboxRowView::HeaderView::SetHeader(), OmniboxEditModel::TriggerPopupSelectionAction(), and OmniboxPopupContentsView::UpdatePopupAppearance().
LimitNumberOfURLsShown()
void AutocompleteResult::LimitNumberOfURLsShown (size_t max_matches, size_t max_url_count, const CompareWithDemoteByType< AutocompleteMatch > & comparing_object) private
References matches_.
Referenced by SortAndCull().
LogAsynchronousUpdateMetrics()
void AutocompleteResult::LogAsynchronousUpdateMetrics (const std::vector< MatchDedupComparator > & old_result, const AutocompleteResult & new_result) static
References GetMatchComparisonFields(), kMaxAutocompletePositionValue, match_at(), and size().
Referenced by AutocompleteController::UpdateResult().
match_at() [1/2]
AutocompleteMatch * AutocompleteResult::match_at (size_t index)
References matches_.
match_at() [2/2]
const AutocompleteMatch & AutocompleteResult::match_at (size_t index) const
References matches_.
Referenced by OmniboxResultView::GetAccessibleNodeData(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxPopupContentsView::GetMatchAtIndex(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupSelection::IsControlPresentOnMatch(), LogAsynchronousUpdateMetrics(), OmniboxSuggestionButtonRowView::match(), OmniboxEditModel::OnFaviconFetched(), OmniboxEditModel::OnPopupResultChanged(), OmniboxPopupContentsView::OnSuggestionGroupVisibilityUpdate(), OmniboxPopupContentsView::OpenMatch(), OmniboxEditModel::SetPopupSelection(), OmniboxEditModel::TriggerPopupSelectionAction(), OmniboxEditModel::TryDeletingPopupLine(), and AutocompleteController::UpdateAssistedQueryStats().
MaybeCullTailSuggestions()
void AutocompleteResult::MaybeCullTailSuggestions (ACMatches * matches, const CompareWithDemoteByType< AutocompleteMatch > & comparing_object) static private
References CompareWithDemoteByType< Match >::GetDemotedRelevance(), and AutocompleteMatchType::SEARCH_SUGGEST_TAIL.
Referenced by SortAndCull().
MergeHeadersMap()
void AutocompleteResult::MergeHeadersMap (const SearchSuggestionParser::HeadersMap & headers_map)
References headers_map(), and headers_map_.
Referenced by AutocompleteController::UpdateHeaderInfoFromZeroSuggestProvider().
MergeHiddenGroupIds()
void AutocompleteResult::MergeHiddenGroupIds (const std::vector< int > & hidden_group_ids)
References hidden_group_ids(), and hidden_group_ids_.
Referenced by AutocompleteController::UpdateHeaderInfoFromZeroSuggestProvider().
MergeMatchesByProvider()
void AutocompleteResult::MergeMatchesByProvider (ACMatches * old_matches, const ACMatches & new_matches) private
References HasMatchByDestination(), and matches_.
Referenced by TransferOldMatches().
operator=()
AutocompleteResult& AutocompleteResult::operator= (const AutocompleteResult &) delete
Reset()
void AutocompleteResult::Reset ()
References headers_map_, hidden_group_ids_, and matches_.
Referenced by AutocompleteController::StopHelper(), Swap(), AutocompleteController::UpdateResult(), and AutocompleteController::~AutocompleteController().
size()
size_t AutocompleteResult::size () const
References matches_.
Referenced by OmniboxResultView::GetAccessibleNodeData(), OmniboxPopupSelection::GetAllAvailableSelectionsSorted(), OmniboxPopupContentsView::GetIndexForPoint(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupContentsView::GetTargetBounds(), OmniboxPopupContentsView::HasMatchAt(), OmniboxPopupSelection::IsControlPresentOnMatch(), LogAsynchronousUpdateMetrics(), OmniboxLog::OmniboxLog(), OmniboxEditModel::OnFaviconFetched(), OmniboxEditModel::OpenMatch(), SearchProvider::RegisterDisplayedAnswers(), AutocompleteController::UpdateAssistedQueryStats(), and OmniboxPopupContentsView::UpdatePopupAppearance().
SortAndCull()
void AutocompleteResult::SortAndCull (const AutocompleteInput & input, TemplateURLService * template_url_service, const AutocompleteMatch * preserve_default_match = nullptr)
References CalculateNumMatches(), AutocompleteInput::current_page_classification(), DeduplicateMatches(), omnibox::DEFAULT, default_match(), DemoteOnDeviceSearchSuggestions(), AutocompleteMatch::destination_url, DiscourageTopMatchFromBeingSearchEntity(), AutocompleteMatch::fill_into_edit, FindTopMatch(), AutocompleteInput::focus_type(), GetMatchComparisonFields(), GetMaxMatches(), OmniboxFieldTrial::GetMaxURLMatches(), AutocompleteProvider::GetName(), GroupAndDemoteMatchesWithHeaders(), GroupSuggestionsBySearchVsURL(), OmniboxFieldTrial::IsMaxURLMatchesFeatureEnabled(), AutocompleteMatch::IsSearchType(), omnibox::kAdaptiveSuggestionsCount, LimitNumberOfURLsShown(), matches_, MaybeCullTailSuggestions(), AutocompleteInput::parts(), AutocompleteMatch::provider, AutocompleteInput::scheme(), AutocompleteInput::text(), AutocompleteInput::type(), and AutocompleteMatch::type.
Referenced by TransferOldMatches(), and AutocompleteController::UpdateResult().
Swap()
void AutocompleteResult::Swap (AutocompleteResult * other)
References matches_, and Reset().
Referenced by TransferOldMatches(), and AutocompleteController::UpdateResult().
TransferOldMatches()
void AutocompleteResult::TransferOldMatches (const AutocompleteInput & input, AutocompleteResult * old_matches, TemplateURLService * template_url_service)
References begin(), BuildProviderToMatchesCopy(), BuildProviderToMatchesMove(), empty(), end(), matches_, MergeMatchesByProvider(), AutocompleteInput::prevent_inline_autocomplete(), SortAndCull(), and Swap().
Referenced by AutocompleteController::UpdateResult().
Friends And Related Function Documentation
HistoryURLProviderTest
friend class HistoryURLProviderTest friend
Member Data Documentation
headers_map_
SearchSuggestionParser::HeadersMap AutocompleteResult::headers_map_ private
Referenced by GetHeaderForGroupId(), headers_map(), MergeHeadersMap(), and Reset().
hidden_group_ids_
std::set<int> AutocompleteResult::hidden_group_ids_ private
Referenced by hidden_group_ids(), IsSuggestionGroupIdHidden(), MergeHiddenGroupIds(), and Reset().
kMaxAutocompletePositionValue
constexpr size_t AutocompleteResult::kMaxAutocompletePositionValue = 30 static constexpr
Referenced by GetMaxMatches(), LogAsynchronousUpdateMetrics(), and SearchProvider::PrefetchImages().
matches_
ACMatches AutocompleteResult::matches_ private
Referenced by AppendMatches(), AttachPedalsToMatches(), AutocompleteResult(), begin(), ConvertOpenTabMatches(), CopyFrom(), DemoteOnDeviceSearchSuggestions(), empty(), end(), EstimateMemoryUsage(), GroupAndDemoteMatchesWithHeaders(), InlineTailPrefixes(), LimitNumberOfURLsShown(), match_at(), MergeMatchesByProvider(), Reset(), size(), SortAndCull(), Swap(), and TransferOldMatches().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_result.h
components/omnibox/browser/autocomplete_result.cc
components/omnibox/browser/autocomplete_result_android.cc