Chromium Omnibox: RemoteSuggestionsService Class Reference
RemoteSuggestionsService Class Reference
#include <remote_suggestions_service.h>
Public Types
using StartCallback = base::OnceCallback< void(std::unique_ptr< network::SimpleURLLoader > loader)>
using CompletionCallback = base::OnceCallback< void(const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)>
Public Member Functions
RemoteSuggestionsService (scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory)
~RemoteSuggestionsService () override
RemoteSuggestionsService (const RemoteSuggestionsService &)=delete
RemoteSuggestionsService & operator= (const RemoteSuggestionsService &)=delete
void CreateSuggestionsRequest (const TemplateURLRef::SearchTermsArgs &search_terms_args, const TemplateURLService *template_url_service, StartCallback start_callback, CompletionCallback completion_callback)
Static Public Member Functions
static GURL EndpointUrl (TemplateURLRef::SearchTermsArgs search_terms_args, const TemplateURLService *template_url_service)
Private Member Functions
void StartDownloadAndTransferLoader (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback)
Private Attributes
scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory_
Member Typedef Documentation
CompletionCallback
using RemoteSuggestionsService::CompletionCallback = base::OnceCallback<void(const network::SimpleURLLoader* source, std::unique_ptr<std::string> response_body)>
StartCallback
using RemoteSuggestionsService::StartCallback = base::OnceCallback<void(std::unique_ptr<network::SimpleURLLoader> loader)>
Constructor & Destructor Documentation
RemoteSuggestionsService() [1/2]
RemoteSuggestionsService::RemoteSuggestionsService (scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory) explicit
Referenced by MockAutocompleteProviderClient::MockAutocompleteProviderClient().
~RemoteSuggestionsService()
RemoteSuggestionsService::~RemoteSuggestionsService () override
RemoteSuggestionsService() [2/2]
RemoteSuggestionsService::RemoteSuggestionsService (const RemoteSuggestionsService &) delete
Member Function Documentation
CreateSuggestionsRequest()
void RemoteSuggestionsService::CreateSuggestionsRequest (const TemplateURLRef::SearchTermsArgs & search_terms_args, const TemplateURLService * template_url_service, StartCallback start_callback, CompletionCallback completion_callback)
References EndpointUrl(), and StartDownloadAndTransferLoader().
Referenced by ZeroSuggestProvider::Start().
EndpointUrl()
GURL RemoteSuggestionsService::EndpointUrl (TemplateURLRef::SearchTermsArgs search_terms_args, const TemplateURLService * template_url_service) static
References BaseSearchProvider::AppendSuggestClientToAdditionalQueryParams().
Referenced by CreateSuggestionsRequest(), ZeroSuggestProvider::Start(), and ZeroSuggestProvider::ZeroSuggestProvider().
operator=()
RemoteSuggestionsService& RemoteSuggestionsService::operator= (const RemoteSuggestionsService &) delete
StartDownloadAndTransferLoader()
void RemoteSuggestionsService::StartDownloadAndTransferLoader (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback) private
References url_loader_factory_.
Referenced by CreateSuggestionsRequest().
Member Data Documentation
url_loader_factory_
scoped_refptr<network::SharedURLLoaderFactory> RemoteSuggestionsService::url_loader_factory_ private
Referenced by StartDownloadAndTransferLoader().
The documentation for this class was generated from the following files:
components/omnibox/browser/remote_suggestions_service.h
components/omnibox/browser/remote_suggestions_service.cc