Chromium Omnibox: ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader Class Reference
ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader Class Reference
Public Member Functions
AlternativeNavigationURLLoader (const GURL &destination_url, scoped_refptr< ChromeOmniboxNavigationObserver > navigation_observer, base::OnceCallback< void(bool)> on_complete, network::mojom::URLLoaderFactory *loader_factory)
void OnRedirect (const net::RedirectInfo &redirect_info, const network::mojom::URLResponseHead &response_head, std::vector< std::string > *to_be_removed_headers)
void OnURLLoadComplete (std::unique_ptr< std::string > body)
void OnDoneWithURL (bool success)
Private Attributes
const GURL destination_url_
scoped_refptr< ChromeOmniboxNavigationObserver > navigation_observer_
base::OnceCallback< void(bool)> on_complete_
std::unique_ptr< network::SimpleURLLoader > loader_
Constructor & Destructor Documentation
AlternativeNavigationURLLoader()
ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::AlternativeNavigationURLLoader (const GURL & destination_url, scoped_refptr< ChromeOmniboxNavigationObserver > navigation_observer, base::OnceCallback< void(bool)> on_complete, network::mojom::URLLoaderFactory * loader_factory) inline
References loader_, OnRedirect(), and OnURLLoadComplete().
Referenced by ChromeOmniboxNavigationObserver::ChromeOmniboxNavigationObserver().
Member Function Documentation
OnDoneWithURL()
void ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::OnDoneWithURL (bool success) inline
References on_complete_.
Referenced by OnRedirect(), and OnURLLoadComplete().
OnRedirect()
void ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::OnRedirect (const net::RedirectInfo & redirect_info, const network::mojom::URLResponseHead & response_head, std::vector< std::string > * to_be_removed_headers) inline
References destination_url_, and OnDoneWithURL().
Referenced by AlternativeNavigationURLLoader().
OnURLLoadComplete()
void ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::OnURLLoadComplete (std::unique_ptr< std::string > body) inline
References loader_, and OnDoneWithURL().
Referenced by AlternativeNavigationURLLoader().
Member Data Documentation
destination_url_
const GURL ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::destination_url_ private
Referenced by OnRedirect().
loader_
std::unique_ptr<network::SimpleURLLoader> ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::loader_ private
Referenced by AlternativeNavigationURLLoader(), and OnURLLoadComplete().
navigation_observer_
scoped_refptr<ChromeOmniboxNavigationObserver> ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::navigation_observer_ private
on_complete_
base::OnceCallback<void(bool)> ChromeOmniboxNavigationObserver::AlternativeNavigationURLLoader::on_complete_ private
Referenced by OnDoneWithURL().
The documentation for this class was generated from the following file:
chrome/browser/ui/omnibox/chrome_omnibox_navigation_observer.cc