Chromium Omnibox: SearchProvider::Providers Class Reference
SearchProvider::Providers Class Reference
Public Member Functions
Providers (TemplateURLService *template_url_service)
Providers (const Providers &)=delete
Providers & operator= (const Providers &)=delete
bool equal (const std::u16string &default_provider, const std::u16string &keyword_provider) const
void set (const std::u16string &default_provider, const std::u16string &keyword_provider)
const std::u16string & default_provider () const
const std::u16string & keyword_provider () const
const TemplateURL * GetDefaultProviderURL () const
const TemplateURL * GetKeywordProviderURL () const
bool has_keyword_provider () const
Private Attributes
TemplateURLService * template_url_service_
std::u16string default_provider_
std::u16string keyword_provider_
Constructor & Destructor Documentation
Providers() [1/2]
SearchProvider::Providers::Providers (TemplateURLService * template_url_service) explicit
Providers() [2/2]
SearchProvider::Providers::Providers (const Providers &) delete
Member Function Documentation
default_provider()
const std::u16string& SearchProvider::Providers::default_provider () const inline
References default_provider_.
Referenced by equal(), SearchProvider::OnTemplateURLServiceChanged(), set(), SearchProvider::ShouldAppendExtraParams(), and SearchProvider::Start().
equal()
bool SearchProvider::Providers::equal (const std::u16string & default_provider, const std::u16string & keyword_provider) const inline
References default_provider(), default_provider_, keyword_provider(), and keyword_provider_.
Referenced by SearchProvider::Start().
GetDefaultProviderURL()
const TemplateURL * SearchProvider::Providers::GetDefaultProviderURL () const
Referenced by SearchProvider::DoHistoryQuery(), SearchProvider::GetTemplateURL(), SearchProvider::IsQuerySuitableForSuggest(), SearchProvider::LogLoadComplete(), SearchProvider::OnTemplateURLServiceChanged(), and SearchProvider::Run().
GetKeywordProviderURL()
const TemplateURL * SearchProvider::Providers::GetKeywordProviderURL () const
Referenced by SearchProvider::AddSuggestResultsToMap(), SearchProvider::AddTransformedHistoryResultsToMap(), SearchProvider::ConvertResultsToAutocompleteMatches(), SearchProvider::DoHistoryQuery(), SearchProvider::EnforceConstraints(), SearchProvider::GetTemplateURL(), SearchProvider::IsQuerySuitableForSuggest(), SearchProvider::NavigationToMatch(), SearchProvider::OnTemplateURLServiceChanged(), SearchProvider::PersistTopSuggestions(), and SearchProvider::Run().
has_keyword_provider()
bool SearchProvider::Providers::has_keyword_provider () const inline
References keyword_provider_.
Referenced by SearchProvider::ApplyCalculatedNavigationRelevance(), SearchProvider::ApplyCalculatedSuggestRelevance(), SearchProvider::CalculateRelevanceForHistory(), and SearchProvider::ShouldCurbDefaultSuggestions().
keyword_provider()
const std::u16string& SearchProvider::Providers::keyword_provider () const inline
References keyword_provider_.
Referenced by SearchProvider::CalculateRelevanceForVerbatim(), equal(), SearchProvider::OnTemplateURLServiceChanged(), set(), SearchProvider::ShouldCurbDefaultSuggestions(), and SearchProvider::SortResults().
operator=()
Providers& SearchProvider::Providers::operator= (const Providers &) delete
set()
void SearchProvider::Providers::set (const std::u16string & default_provider, const std::u16string & keyword_provider) inline
References default_provider(), default_provider_, keyword_provider(), and keyword_provider_.
Referenced by SearchProvider::OnTemplateURLServiceChanged(), and SearchProvider::Start().
Member Data Documentation
default_provider_
std::u16string SearchProvider::Providers::default_provider_ private
Referenced by default_provider(), equal(), and set().
keyword_provider_
std::u16string SearchProvider::Providers::keyword_provider_ private
Referenced by equal(), has_keyword_provider(), keyword_provider(), and set().
template_url_service_
TemplateURLService* SearchProvider::Providers::template_url_service_ private
The documentation for this class was generated from the following files:
components/omnibox/browser/search_provider.h
components/omnibox/browser/search_provider.cc