Chromium Omnibox: ShortcutsProvider Class Reference
ShortcutsProvider Class Reference
#include <shortcuts_provider.h>
Public Member Functions
ShortcutsProvider (AutocompleteProviderClient *client)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void DeleteMatch (const AutocompleteMatch &match) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Public Member Functions inherited from ShortcutsBackend::ShortcutsBackendObserver
virtual void OnShortcutsChanged ()
Private Member Functions
~ShortcutsProvider () override
void OnShortcutsLoaded () override
void GetMatches (const AutocompleteInput &input)
AutocompleteMatch ShortcutToACMatch (const ShortcutsDatabase::Shortcut &shortcut, int relevance, const AutocompleteInput &input, const std::u16string &fixed_up_input_text, const std::u16string term_string)
ShortcutsBackend::ShortcutMap::const_iterator FindFirstMatch (const std::u16string &keyword, ShortcutsBackend *backend)
int CalculateScore (const std::u16string &terms, const ShortcutsDatabase::Shortcut &shortcut, int max_relevance)
Private Attributes
AutocompleteProviderClient * client_
bool initialized_
Static Private Attributes
static const int kShortcutsProviderDefaultMaxRelevance = 1199
Friends
class ClassifyTest
class ShortcutsProviderExtensionTest
class ShortcutsProviderTest
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Protected Member Functions inherited from ShortcutsBackend::ShortcutsBackendObserver
virtual ~ShortcutsBackendObserver ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
ShortcutsProvider()
ShortcutsProvider::ShortcutsProvider (AutocompleteProviderClient * client) explicit
References client_, AutocompleteProviderClient::GetShortcutsBackend(), and initialized_.
~ShortcutsProvider()
ShortcutsProvider::~ShortcutsProvider () override private
References client_, and AutocompleteProviderClient::GetShortcutsBackendIfExists().
Member Function Documentation
CalculateScore()
int ShortcutsProvider::CalculateScore (const std::u16string & terms, const ShortcutsDatabase::Shortcut & shortcut, int max_relevance) private
References omnibox::kPreserveLongerShortcutsText, ShortcutsDatabase::Shortcut::last_access_time, ShortcutsDatabase::Shortcut::number_of_hits, and ShortcutsDatabase::Shortcut::text.
Referenced by GetMatches().
DeleteMatch()
void ShortcutsProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
References client_, AutocompleteMatch::destination_url, AutocompleteProviderClient::GetHistoryService(), AutocompleteProviderClient::GetShortcutsBackendIfExists(), and AutocompleteProvider::matches_.
FindFirstMatch()
ShortcutsBackend::ShortcutMap::const_iterator ShortcutsProvider::FindFirstMatch (const std::u16string & keyword, ShortcutsBackend * backend) private
References ShortcutsBackend::shortcuts_map().
Referenced by GetMatches().
GetMatches()
void ShortcutsProvider::GetMatches (const AutocompleteInput & input) private
References CalculateScore(), client_, AutocompleteInput::current_page_classification(), ShortcutsDatabase::Shortcut::MatchCore::destination_url, FindFirstMatch(), AutocompleteProvider::FixupUserInput(), AutocompleteProviderClient::GetShortcutsBackendIfExists(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteMatch::GURLToStrippedGURL(), ShortcutsDatabase::Shortcut::MatchCore::keyword, kShortcutsProviderDefaultMaxRelevance, ShortcutsDatabase::Shortcut::match_core, AutocompleteProvider::matches_, AutocompleteProvider::provider_max_matches_, OmniboxFieldTrial::ShortcutsScoringMaxRelevance(), ShortcutToACMatch(), and AutocompleteInput::text().
Referenced by Start().
OnShortcutsLoaded()
void ShortcutsProvider::OnShortcutsLoaded () override private virtual
Implements ShortcutsBackend::ShortcutsBackendObserver.
References initialized_.
ShortcutToACMatch()
AutocompleteMatch ShortcutsProvider::ShortcutToACMatch (const ShortcutsDatabase::Shortcut & shortcut, int relevance, const AutocompleteInput & input, const std::u16string & fixed_up_input_text, const std::u16string term_string) private
References AutocompleteMatch::allowed_to_be_default_match, AutocompleteMatch::ClassificationsFromString(), AutocompleteProvider::ClassifyAllMatchesInString(), client_, AutocompleteMatch::contents, ShortcutsDatabase::Shortcut::MatchCore::contents, AutocompleteMatch::contents_class, ShortcutsDatabase::Shortcut::MatchCore::contents_class, AutocompleteMatch::deletable, AutocompleteMatch::description, ShortcutsDatabase::Shortcut::MatchCore::description, AutocompleteMatch::description_class, ShortcutsDatabase::Shortcut::MatchCore::description_class, AutocompleteMatch::destination_url, ShortcutsDatabase::Shortcut::MatchCore::destination_url, AutocompleteMatch::document_type, ShortcutsDatabase::Shortcut::MatchCore::document_type, AutocompleteMatch::fill_into_edit, ShortcutsDatabase::Shortcut::MatchCore::fill_into_edit, AutocompleteMatch::from_keyword, URLPrefix::GetInlineAutocompleteOffset(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteMatch::inline_autocompletion, AutocompleteMatch::IsSearchType(), AutocompleteMatch::keyword, ShortcutsDatabase::Shortcut::MatchCore::keyword, ShortcutsDatabase::Shortcut::last_access_time, ShortcutsDatabase::Shortcut::match_core, ShortcutsDatabase::Shortcut::number_of_hits, AutocompleteInput::prefer_keyword(), AutocompleteInput::prevent_inline_autocomplete(), AutocompleteMatch::provider, AutocompleteMatch::RecordAdditionalInfo(), AutocompleteMatch::relevance, AutocompleteMatch::SetAllowedToBeDefault(), AutocompleteInput::text(), ShortcutsDatabase::Shortcut::text, AutocompleteMatch::transition, ShortcutsDatabase::Shortcut::MatchCore::transition, AutocompleteMatch::TryRichAutocompletion(), AutocompleteMatch::type, and ShortcutsDatabase::Shortcut::MatchCore::type.
Referenced by GetMatches().
Start()
void ShortcutsProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References omnibox::DEFAULT, AutocompleteInput::focus_type(), GetMatches(), initialized_, AutocompleteProvider::matches_, AutocompleteInput::text(), and AutocompleteInput::type().
Friends And Related Function Documentation
ClassifyTest
friend class ClassifyTest friend
ShortcutsProviderExtensionTest
friend class ShortcutsProviderExtensionTest friend
ShortcutsProviderTest
friend class ShortcutsProviderTest friend
Member Data Documentation
client_
AutocompleteProviderClient* ShortcutsProvider::client_ private
Referenced by DeleteMatch(), GetMatches(), ShortcutsProvider(), ShortcutToACMatch(), and ~ShortcutsProvider().
initialized_
bool ShortcutsProvider::initialized_ private
Referenced by OnShortcutsLoaded(), ShortcutsProvider(), and Start().
kShortcutsProviderDefaultMaxRelevance
const int ShortcutsProvider::kShortcutsProviderDefaultMaxRelevance = 1199 static private
Referenced by GetMatches().
The documentation for this class was generated from the following files:
components/omnibox/browser/shortcuts_provider.h
components/omnibox/browser/shortcuts_provider.cc