Chromium Omnibox: URLIndexPrivateData Class Reference
URLIndexPrivateData Class Reference
#include <url_index_private_data.h>
Classes
class HistoryItemFactorGreater
struct SearchTermCacheItem
Public Member Functions
URLIndexPrivateData ()
ScoredHistoryMatches HistoryItemsForTerms (std::u16string term_string, size_t cursor_position, size_t max_matches, bookmarks::BookmarkModel *bookmark_model, TemplateURLService *template_url_service)
bool UpdateURL (history::HistoryService *history_service, const history::URLRow &row, const std::set< std::string > &scheme_allowlist, base::CancelableTaskTracker *tracker)
void UpdateRecentVisits (history::URLID url_id, const history::VisitVector &recent_visits)
void ScheduleUpdateRecentVisits (history::HistoryService *history_service, history::URLID url_id, base::CancelableTaskTracker *tracker)
bool DeleteURL (const GURL &url)
scoped_refptr< URLIndexPrivateData > Duplicate () const
bool Empty () const
void Clear ()
size_t EstimateMemoryUsage () const
Static Public Member Functions
static scoped_refptr< URLIndexPrivateData > RestoreFromFile (const base::FilePath &path)
static scoped_refptr< URLIndexPrivateData > RebuildFromHistory (history::HistoryDatabase *history_db, const std::set< std::string > &scheme_allowlist)
static bool WritePrivateDataToCacheFileTask (scoped_refptr< URLIndexPrivateData > private_data, const base::FilePath &file_path)
Static Public Attributes
static constexpr size_t kMaxVisitsToStoreInCache = 10
Private Types
typedef std::map< std::u16string, SearchTermCacheItem > SearchTermCacheMap
Private Member Functions
~URLIndexPrivateData ()
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, CacheSaveRestore)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, CalculateWordStartsOffsets)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, CalculateWordStartsOffsetsUnderscore)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, HugeResultSet)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, ReadVisitsFromHistory)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, RebuildFromHistoryIfCacheOld)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, Scoring)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, TitleSearch)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, TrimHistoryIds)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, TypedCharacterCaching)
FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest, AllowlistedURLs)
FRIEND_TEST_ALL_PREFIXES (LimitedInMemoryURLIndexTest, Initialization)
HistoryIDVector HistoryIDsFromWords (const String16Vector &unsorted_words)
bool TrimHistoryIdsPool (HistoryIDVector *history_ids) const
HistoryIDSet HistoryIDsForTerm (const std::u16string &term)
WordIDSet WordIDSetForTermChars (const Char16Set &term_chars)
void HistoryIdsToScoredMatches (HistoryIDVector history_ids, const std::u16string &lower_raw_string, const TemplateURLService *template_url_service, bookmarks::BookmarkModel *bookmark_model, ScoredHistoryMatches *scored_items) const
bool IndexRow (history::HistoryDatabase *history_db, history::HistoryService *history_service, const history::URLRow &row, const std::set< std::string > &scheme_allowlist, base::CancelableTaskTracker *tracker)
void AddRowWordsToIndex (const history::URLRow &row, RowWordStarts *word_starts)
void AddWordToIndex (const std::u16string &uni_word, HistoryID history_id)
WordID AddNewWordToWordList (const std::u16string &term)
void RemoveRowFromIndex (const history::URLRow &row)
void RemoveRowWordsFromIndex (const history::URLRow &row)
void ResetSearchTermCache ()
bool SaveToFile (const base::FilePath &file_path)
void SavePrivateData (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveWordList (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveWordMap (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveCharWordMap (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveWordIDHistoryMap (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveHistoryInfoMap (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
void SaveWordStartsMap (in_memory_url_index::InMemoryURLIndexCacheItem *cache) const
bool RestorePrivateData (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreWordList (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreWordMap (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreCharWordMap (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreWordIDHistoryMap (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreHistoryInfoMap (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool RestoreWordStartsMap (const in_memory_url_index::InMemoryURLIndexCacheItem &cache)
bool ShouldFilter (const HistoryID history_id, const TemplateURLService *template_url_service) const
Static Private Member Functions
static void CalculateWordStartsOffsets (const String16Vector &terms, WordStarts *terms_to_word_starts_offsets)
static bool URLSchemeIsAllowlisted (const GURL &gurl, const std::set< std::string > &allowlist)
Private Attributes
SearchTermCacheMap search_term_cache_
int restored_cache_version_
base::Time last_time_rebuilt_from_history_
String16Vector word_list_
base::stack< WordID > available_words_
WordMap word_map_
CharWordIDMap char_word_map_
WordIDHistoryMap word_id_history_map_
HistoryIDWordMap history_id_word_map_
HistoryInfoMap history_info_map_
WordStartsMap word_starts_map_
int saved_cache_version_
Friends
class base::RefCountedThreadSafe< URLIndexPrivateData >
class ::HistoryQuickProviderTest
class InMemoryURLIndexTest
Member Typedef Documentation
SearchTermCacheMap
typedef std::map<std::u16string, SearchTermCacheItem> URLIndexPrivateData::SearchTermCacheMap private
Constructor & Destructor Documentation
URLIndexPrivateData()
URLIndexPrivateData::URLIndexPrivateData ()
Referenced by Duplicate().
~URLIndexPrivateData()
URLIndexPrivateData::~URLIndexPrivateData () private default
Member Function Documentation
AddNewWordToWordList()
WordID URLIndexPrivateData::AddNewWordToWordList (const std::u16string & term) private
References available_words_, and word_list_.
Referenced by AddWordToIndex().
AddRowWordsToIndex()
void URLIndexPrivateData::AddRowWordsToIndex (const history::URLRow & row, RowWordStarts * word_starts) private
References AddWordToIndex(), search_term_cache_, String16SetFromString16(), RowWordStarts::title_word_starts_, and RowWordStarts::url_word_starts_.
Referenced by IndexRow(), and UpdateURL().
AddWordToIndex()
void URLIndexPrivateData::AddWordToIndex (const std::u16string & uni_word, HistoryID history_id) private
References AddNewWordToWordList(), Char16SetFromString16(), char_word_map_, history_id_word_map_, word_id_history_map_, and word_map_.
Referenced by AddRowWordsToIndex().
CalculateWordStartsOffsets()
void URLIndexPrivateData::CalculateWordStartsOffsets (const String16Vector & terms, WordStarts * terms_to_word_starts_offsets) static private
References TailoredWordBreakIterator::Advance(), TailoredWordBreakIterator::IsWord(), and TailoredWordBreakIterator::prev().
Referenced by HistoryIdsToScoredMatches().
Clear()
void URLIndexPrivateData::Clear ()
References available_words_, char_word_map_, history_id_word_map_, history_info_map_, last_time_rebuilt_from_history_, word_id_history_map_, word_list_, word_map_, and word_starts_map_.
DeleteURL()
bool URLIndexPrivateData::DeleteURL (const GURL & url)
References history_info_map_, RemoveRowFromIndex(), and search_term_cache_.
Duplicate()
scoped_refptr< URLIndexPrivateData > URLIndexPrivateData::Duplicate () const
References available_words_, char_word_map_, history_id_word_map_, history_info_map_, last_time_rebuilt_from_history_, URLIndexPrivateData(), word_id_history_map_, word_list_, word_map_, and word_starts_map_.
Empty()
bool URLIndexPrivateData::Empty () const
References history_info_map_.
Referenced by InMemoryURLIndex::OnCacheLoadDone().
EstimateMemoryUsage()
size_t URLIndexPrivateData::EstimateMemoryUsage () const
References available_words_, char_word_map_, base::trace_event::EstimateMemoryUsage(), history_id_word_map_, history_info_map_, search_term_cache_, word_id_history_map_, word_list_, word_map_, and word_starts_map_.
FRIEND_TEST_ALL_PREFIXES() [1/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , AllowlistedURLs) private
FRIEND_TEST_ALL_PREFIXES() [2/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , CacheSaveRestore) private
FRIEND_TEST_ALL_PREFIXES() [3/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , CalculateWordStartsOffsets) private
FRIEND_TEST_ALL_PREFIXES() [4/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , CalculateWordStartsOffsetsUnderscore) private
FRIEND_TEST_ALL_PREFIXES() [5/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , HugeResultSet) private
FRIEND_TEST_ALL_PREFIXES() [6/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , ReadVisitsFromHistory) private
FRIEND_TEST_ALL_PREFIXES() [7/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , RebuildFromHistoryIfCacheOld) private
FRIEND_TEST_ALL_PREFIXES() [8/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , Scoring) private
FRIEND_TEST_ALL_PREFIXES() [9/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , TitleSearch) private
FRIEND_TEST_ALL_PREFIXES() [10/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , TrimHistoryIds) private
FRIEND_TEST_ALL_PREFIXES() [11/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (InMemoryURLIndexTest , TypedCharacterCaching) private
FRIEND_TEST_ALL_PREFIXES() [12/12]
URLIndexPrivateData::FRIEND_TEST_ALL_PREFIXES (LimitedInMemoryURLIndexTest , Initialization) private
HistoryIDsForTerm()
HistoryIDSet URLIndexPrivateData::HistoryIDsForTerm (const std::u16string & term) private
References Char16SetFromString16(), search_term_cache_, word_id_history_map_, word_list_, and WordIDSetForTermChars().
Referenced by HistoryIDsFromWords().
HistoryIDsFromWords()
HistoryIDVector URLIndexPrivateData::HistoryIDsFromWords (const String16Vector & unsorted_words) private
References HistoryIDsForTerm().
Referenced by HistoryItemsForTerms().
HistoryIdsToScoredMatches()
void URLIndexPrivateData::HistoryIdsToScoredMatches (HistoryIDVector history_ids, const std::u16string & lower_raw_string, const TemplateURLService * template_url_service, bookmarks::BookmarkModel * bookmark_model, ScoredHistoryMatches * scored_items) const private
References CalculateWordStartsOffsets(), history_info_map_, ScoredHistoryMatch::raw_score, ShouldFilter(), and word_starts_map_.
Referenced by HistoryItemsForTerms().
HistoryItemsForTerms()
ScoredHistoryMatches URLIndexPrivateData::HistoryItemsForTerms (std::u16string term_string, size_t cursor_position, size_t max_matches, bookmarks::BookmarkModel * bookmark_model, TemplateURLService * template_url_service)
References HistoryIDsFromWords(), HistoryIdsToScoredMatches(), ScoredHistoryMatch::MatchScoreGreater(), ResetSearchTermCache(), search_term_cache_, String16VectorFromString16(), TrimHistoryIdsPool(), and word_list_.
IndexRow()
bool URLIndexPrivateData::IndexRow (history::HistoryDatabase * history_db, history::HistoryService * history_service, const history::URLRow & row, const std::set< std::string > & scheme_allowlist, base::CancelableTaskTracker * tracker) private
References AddRowWordsToIndex(), history_info_map_, kMaxVisitsToStoreInCache, ScheduleUpdateRecentVisits(), UpdateRecentVisits(), URLSchemeIsAllowlisted(), and word_starts_map_.
Referenced by UpdateURL().
RebuildFromHistory()
scoped_refptr< URLIndexPrivateData > URLIndexPrivateData::RebuildFromHistory (history::HistoryDatabase * history_db, const std::set< std::string > & scheme_allowlist) static
References OmniboxFieldTrial::MaxNumHQPUrlsIndexedAtStartup().
Referenced by InMemoryURLIndex::RebuildFromHistory(), and InMemoryURLIndex::RebuildPrivateDataFromHistoryDBTask::RunOnDBThread().
RemoveRowFromIndex()
void URLIndexPrivateData::RemoveRowFromIndex (const history::URLRow & row) private
References history_info_map_, RemoveRowWordsFromIndex(), and word_starts_map_.
Referenced by DeleteURL(), and UpdateURL().
RemoveRowWordsFromIndex()
void URLIndexPrivateData::RemoveRowWordsFromIndex (const history::URLRow & row) private
References available_words_, Char16SetFromString16(), char_word_map_, history_id_word_map_, word_id_history_map_, word_list_, and word_map_.
Referenced by RemoveRowFromIndex(), and UpdateURL().
ResetSearchTermCache()
void URLIndexPrivateData::ResetSearchTermCache () private
References search_term_cache_.
Referenced by HistoryItemsForTerms().
RestoreCharWordMap()
bool URLIndexPrivateData::RestoreCharWordMap (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References char_word_map_.
Referenced by RestorePrivateData().
RestoreFromFile()
scoped_refptr< URLIndexPrivateData > URLIndexPrivateData::RestoreFromFile (const base::FilePath & path) static
Referenced by InMemoryURLIndex::PostRestoreFromCacheFileTask().
RestoreHistoryInfoMap()
bool URLIndexPrivateData::RestoreHistoryInfoMap (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References history_info_map_.
Referenced by RestorePrivateData().
RestorePrivateData()
bool URLIndexPrivateData::RestorePrivateData (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References kCurrentCacheFileVersion, last_time_rebuilt_from_history_, RestoreCharWordMap(), restored_cache_version_, RestoreHistoryInfoMap(), RestoreWordIDHistoryMap(), RestoreWordList(), RestoreWordMap(), and RestoreWordStartsMap().
RestoreWordIDHistoryMap()
bool URLIndexPrivateData::RestoreWordIDHistoryMap (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References history_id_word_map_, and word_id_history_map_.
Referenced by RestorePrivateData().
RestoreWordList()
bool URLIndexPrivateData::RestoreWordList (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References word_list_.
Referenced by RestorePrivateData().
RestoreWordMap()
bool URLIndexPrivateData::RestoreWordMap (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References word_map_.
Referenced by RestorePrivateData().
RestoreWordStartsMap()
bool URLIndexPrivateData::RestoreWordStartsMap (const in_memory_url_index::InMemoryURLIndexCacheItem & cache) private
References history_info_map_, String16VectorFromString16(), RowWordStarts::title_word_starts_, RowWordStarts::url_word_starts_, and word_starts_map_.
Referenced by RestorePrivateData().
SaveCharWordMap()
void URLIndexPrivateData::SaveCharWordMap (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References char_word_map_.
Referenced by SavePrivateData().
SaveHistoryInfoMap()
void URLIndexPrivateData::SaveHistoryInfoMap (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References history_info_map_.
Referenced by SavePrivateData().
SavePrivateData()
void URLIndexPrivateData::SavePrivateData (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References last_time_rebuilt_from_history_, SaveCharWordMap(), saved_cache_version_, SaveHistoryInfoMap(), SaveWordIDHistoryMap(), SaveWordList(), SaveWordMap(), and SaveWordStartsMap().
Referenced by SaveToFile().
SaveToFile()
bool URLIndexPrivateData::SaveToFile (const base::FilePath & file_path) private
References SavePrivateData().
SaveWordIDHistoryMap()
void URLIndexPrivateData::SaveWordIDHistoryMap (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References word_id_history_map_.
Referenced by SavePrivateData().
SaveWordList()
void URLIndexPrivateData::SaveWordList (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References word_list_.
Referenced by SavePrivateData().
SaveWordMap()
void URLIndexPrivateData::SaveWordMap (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References word_map_.
Referenced by SavePrivateData().
SaveWordStartsMap()
void URLIndexPrivateData::SaveWordStartsMap (in_memory_url_index::InMemoryURLIndexCacheItem * cache) const private
References saved_cache_version_, RowWordStarts::title_word_starts_, RowWordStarts::url_word_starts_, and word_starts_map_.
Referenced by SavePrivateData().
ScheduleUpdateRecentVisits()
void URLIndexPrivateData::ScheduleUpdateRecentVisits (history::HistoryService * history_service, history::URLID url_id, base::CancelableTaskTracker * tracker)
Referenced by IndexRow(), and UpdateURL().
ShouldFilter()
bool URLIndexPrivateData::ShouldFilter (const HistoryID history_id, const TemplateURLService * template_url_service) const private
References history_info_map_.
Referenced by HistoryIdsToScoredMatches().
TrimHistoryIdsPool()
bool URLIndexPrivateData::TrimHistoryIdsPool (HistoryIDVector * history_ids) const private
References history_info_map_.
Referenced by HistoryItemsForTerms().
UpdateRecentVisits()
void URLIndexPrivateData::UpdateRecentVisits (history::URLID url_id, const history::VisitVector & recent_visits)
References history_info_map_, and kMaxVisitsToStoreInCache.
Referenced by UpdateRecentVisitsFromHistoryDBTask::DoneRunOnMainThread(), and IndexRow().
UpdateURL()
bool URLIndexPrivateData::UpdateURL (history::HistoryService * history_service, const history::URLRow & row, const std::set< std::string > & scheme_allowlist, base::CancelableTaskTracker * tracker)
References AddRowWordsToIndex(), history_info_map_, IndexRow(), RemoveRowFromIndex(), RemoveRowWordsFromIndex(), ScheduleUpdateRecentVisits(), search_term_cache_, and word_starts_map_.
URLSchemeIsAllowlisted()
bool URLIndexPrivateData::URLSchemeIsAllowlisted (const GURL & gurl, const std::set< std::string > & allowlist) static private
Referenced by IndexRow().
WordIDSetForTermChars()
WordIDSet URLIndexPrivateData::WordIDSetForTermChars (const Char16Set & term_chars) private
References char_word_map_.
Referenced by HistoryIDsForTerm().
WritePrivateDataToCacheFileTask()
bool URLIndexPrivateData::WritePrivateDataToCacheFileTask (scoped_refptr< URLIndexPrivateData > private_data, const base::FilePath & file_path) static
Referenced by InMemoryURLIndex::PostSaveToCacheFileTask(), and InMemoryURLIndex::Shutdown().
Friends And Related Function Documentation
::HistoryQuickProviderTest
friend class ::HistoryQuickProviderTest friend
base::RefCountedThreadSafe< URLIndexPrivateData >
friend class base::RefCountedThreadSafe< URLIndexPrivateData > friend
InMemoryURLIndexTest
friend class InMemoryURLIndexTest friend
Member Data Documentation
available_words_
base::stack<WordID> URLIndexPrivateData::available_words_ private
Referenced by AddNewWordToWordList(), Clear(), Duplicate(), EstimateMemoryUsage(), and RemoveRowWordsFromIndex().
char_word_map_
CharWordIDMap URLIndexPrivateData::char_word_map_ private
Referenced by AddWordToIndex(), Clear(), Duplicate(), EstimateMemoryUsage(), RemoveRowWordsFromIndex(), RestoreCharWordMap(), SaveCharWordMap(), and WordIDSetForTermChars().
history_id_word_map_
HistoryIDWordMap URLIndexPrivateData::history_id_word_map_ private
Referenced by AddWordToIndex(), Clear(), Duplicate(), EstimateMemoryUsage(), RemoveRowWordsFromIndex(), and RestoreWordIDHistoryMap().
history_info_map_
HistoryInfoMap URLIndexPrivateData::history_info_map_ private
Referenced by Clear(), DeleteURL(), Duplicate(), Empty(), EstimateMemoryUsage(), HistoryIdsToScoredMatches(), IndexRow(), URLIndexPrivateData::HistoryItemFactorGreater::operator()(), RemoveRowFromIndex(), RestoreHistoryInfoMap(), RestoreWordStartsMap(), SaveHistoryInfoMap(), ShouldFilter(), TrimHistoryIdsPool(), UpdateRecentVisits(), and UpdateURL().
kMaxVisitsToStoreInCache
constexpr size_t URLIndexPrivateData::kMaxVisitsToStoreInCache = 10 static constexpr
Referenced by OmniboxFieldTrial::HQPMaxVisitsToScore(), IndexRow(), UpdateRecentVisitsFromHistoryDBTask::RunOnDBThread(), and UpdateRecentVisits().
last_time_rebuilt_from_history_
base::Time URLIndexPrivateData::last_time_rebuilt_from_history_ private
Referenced by Clear(), Duplicate(), RestorePrivateData(), and SavePrivateData().
restored_cache_version_
int URLIndexPrivateData::restored_cache_version_ private
Referenced by RestorePrivateData().
saved_cache_version_
int URLIndexPrivateData::saved_cache_version_ private
Referenced by SavePrivateData(), and SaveWordStartsMap().
search_term_cache_
SearchTermCacheMap URLIndexPrivateData::search_term_cache_ private
Referenced by AddRowWordsToIndex(), DeleteURL(), EstimateMemoryUsage(), HistoryIDsForTerm(), HistoryItemsForTerms(), ResetSearchTermCache(), and UpdateURL().
word_id_history_map_
WordIDHistoryMap URLIndexPrivateData::word_id_history_map_ private
Referenced by AddWordToIndex(), Clear(), Duplicate(), EstimateMemoryUsage(), HistoryIDsForTerm(), RemoveRowWordsFromIndex(), RestoreWordIDHistoryMap(), and SaveWordIDHistoryMap().
word_list_
String16Vector URLIndexPrivateData::word_list_ private
Referenced by AddNewWordToWordList(), Clear(), Duplicate(), EstimateMemoryUsage(), HistoryIDsForTerm(), HistoryItemsForTerms(), RemoveRowWordsFromIndex(), RestoreWordList(), and SaveWordList().
word_map_
WordMap URLIndexPrivateData::word_map_ private
Referenced by AddWordToIndex(), Clear(), Duplicate(), EstimateMemoryUsage(), RemoveRowWordsFromIndex(), RestoreWordMap(), and SaveWordMap().
word_starts_map_
WordStartsMap URLIndexPrivateData::word_starts_map_ private
Referenced by Clear(), Duplicate(), EstimateMemoryUsage(), HistoryIdsToScoredMatches(), IndexRow(), RemoveRowFromIndex(), RestoreWordStartsMap(), SaveWordStartsMap(), and UpdateURL().
The documentation for this class was generated from the following files:
components/omnibox/browser/url_index_private_data.h
components/omnibox/browser/url_index_private_data.cc