Chromium Omnibox: ShortcutsBackend Class Reference
ShortcutsBackend Class Reference
#include <shortcuts_backend.h>
Classes
class ShortcutsBackendObserver
Public Types
typedef std::multimap< std::u16string, const ShortcutsDatabase::Shortcut > ShortcutMap
Public Member Functions
ShortcutsBackend (TemplateURLService *template_url_service, std::unique_ptr< SearchTermsData > search_terms_data, history::HistoryService *history_service, base::FilePath database_path, bool suppress_db)
ShortcutsBackend (const ShortcutsBackend &)=delete
ShortcutsBackend & operator= (const ShortcutsBackend &)=delete
bool Init ()
bool initialized () const
const ShortcutMap & shortcuts_map () const
bool DeleteShortcutsWithURL (const GURL &shortcut_url)
bool DeleteShortcutsBeginningWithURL (const GURL &shortcut_url)
void AddObserver (ShortcutsBackendObserver *obs)
void RemoveObserver (ShortcutsBackendObserver *obs)
void AddOrUpdateShortcut (const std::u16string &text, const AutocompleteMatch &match)
Private Types
enum CurrentState { NOT_INITIALIZED , INITIALIZING , INITIALIZED }
typedef std::map< std::string, ShortcutMap::iterator > GuidMap
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ShortcutsBackendTest, EntitySuggestionTest)
FRIEND_TEST_ALL_PREFIXES (ShortcutsBackendTest, MatchCoreDescriptionTest)
~ShortcutsBackend () override
void ShutdownOnUIThread () override
void OnURLsDeleted (history::HistoryService *history_service, const history::DeletionInfo &deletion_info) override
void InitInternal ()
void InitCompleted ()
bool AddShortcut (const ShortcutsDatabase::Shortcut &shortcut)
bool UpdateShortcut (const ShortcutsDatabase::Shortcut &shortcut)
bool DeleteShortcutsWithIDs (const ShortcutsDatabase::ShortcutIDs &shortcut_ids)
bool DeleteShortcutsWithURL (const GURL &url, bool exact_match)
bool DeleteAllShortcuts ()
Static Private Member Functions
static ShortcutsDatabase::Shortcut::MatchCore MatchToMatchCore (const AutocompleteMatch &match, TemplateURLService *template_url_service, SearchTermsData *search_terms_data)
Private Attributes
TemplateURLService * template_url_service_
std::unique_ptr< SearchTermsData > search_terms_data_
CurrentState current_state_
base::ObserverList< ShortcutsBackendObserver >::Unchecked observer_list_
scoped_refptr< ShortcutsDatabase > db_
std::unique_ptr< ShortcutMap > temp_shortcuts_map_
std::unique_ptr< GuidMap > temp_guid_map_
ShortcutMap shortcuts_map_
GuidMap guid_map_
base::ScopedObservation< history::HistoryService, history::HistoryServiceObserver > history_service_observation_ {this}
scoped_refptr< base::SequencedTaskRunner > main_runner_
scoped_refptr< base::SequencedTaskRunner > db_runner_
bool no_db_access_
Friends
class base::RefCountedThreadSafe< ShortcutsBackend >
class ShortcutsBackendTest
void PopulateShortcutsBackendWithTestData (scoped_refptr< ShortcutsBackend > backend, TestShortcutData *db, size_t db_size)
Member Typedef Documentation
GuidMap
typedef std::map<std::string, ShortcutMap::iterator> ShortcutsBackend::GuidMap private
ShortcutMap
typedef std::multimap<std::u16string, const ShortcutsDatabase::Shortcut> ShortcutsBackend::ShortcutMap
Member Enumeration Documentation
CurrentState
enum ShortcutsBackend::CurrentState private
Enumerator
NOT_INITIALIZED
INITIALIZING
INITIALIZED
Constructor & Destructor Documentation
ShortcutsBackend() [1/2]
ShortcutsBackend::ShortcutsBackend (TemplateURLService * template_url_service, std::unique_ptr< SearchTermsData > search_terms_data, history::HistoryService * history_service, base::FilePath database_path, bool suppress_db)
ShortcutsBackend() [2/2]
ShortcutsBackend::ShortcutsBackend (const ShortcutsBackend &) delete
~ShortcutsBackend()
ShortcutsBackend::~ShortcutsBackend () override private
References db_, and db_runner_.
Member Function Documentation
AddObserver()
void ShortcutsBackend::AddObserver (ShortcutsBackendObserver * obs)
References observer_list_.
AddOrUpdateShortcut()
void ShortcutsBackend::AddOrUpdateShortcut (const std::u16string & text, const AutocompleteMatch & match)
References AddShortcut(), AutocompleteMatch::destination_url, omnibox::kPreserveLongerShortcutsText, MatchToMatchCore(), search_terms_data_, shortcuts_map_, template_url_service_, and UpdateShortcut().
AddShortcut()
bool ShortcutsBackend::AddShortcut (const ShortcutsDatabase::Shortcut & shortcut) private
References ShortcutsDatabase::AddShortcut(), db_, db_runner_, guid_map_, ShortcutsDatabase::Shortcut::id, initialized(), no_db_access_, observer_list_, shortcuts_map_, and ShortcutsDatabase::Shortcut::text.
Referenced by AddOrUpdateShortcut().
DeleteAllShortcuts()
bool ShortcutsBackend::DeleteAllShortcuts () private
References db_, db_runner_, ShortcutsDatabase::DeleteAllShortcuts(), guid_map_, initialized(), no_db_access_, observer_list_, and shortcuts_map_.
Referenced by OnURLsDeleted().
DeleteShortcutsBeginningWithURL()
bool ShortcutsBackend::DeleteShortcutsBeginningWithURL (const GURL & shortcut_url)
References DeleteShortcutsWithURL(), and initialized().
DeleteShortcutsWithIDs()
bool ShortcutsBackend::DeleteShortcutsWithIDs (const ShortcutsDatabase::ShortcutIDs & shortcut_ids) private
References db_, db_runner_, ShortcutsDatabase::DeleteShortcutsWithIDs(), guid_map_, initialized(), no_db_access_, observer_list_, and shortcuts_map_.
Referenced by OnURLsDeleted().
DeleteShortcutsWithURL() [1/2]
bool ShortcutsBackend::DeleteShortcutsWithURL (const GURL & shortcut_url)
References initialized().
Referenced by DeleteShortcutsBeginningWithURL().
DeleteShortcutsWithURL() [2/2]
bool ShortcutsBackend::DeleteShortcutsWithURL (const GURL & url, bool exact_match) private
References db_, db_runner_, ShortcutsDatabase::DeleteShortcutsWithURL(), guid_map_, no_db_access_, observer_list_, and shortcuts_map_.
FRIEND_TEST_ALL_PREFIXES() [1/2]
ShortcutsBackend::FRIEND_TEST_ALL_PREFIXES (ShortcutsBackendTest , EntitySuggestionTest) private
FRIEND_TEST_ALL_PREFIXES() [2/2]
ShortcutsBackend::FRIEND_TEST_ALL_PREFIXES (ShortcutsBackendTest , MatchCoreDescriptionTest) private
Init()
bool ShortcutsBackend::Init ()
References current_state_, db_runner_, INITIALIZED, INITIALIZING, InitInternal(), no_db_access_, and NOT_INITIALIZED.
InitCompleted()
void ShortcutsBackend::InitCompleted () private
References current_state_, guid_map_, INITIALIZED, observer_list_, shortcuts_map_, temp_guid_map_, and temp_shortcuts_map_.
Referenced by InitInternal().
initialized()
bool ShortcutsBackend::initialized () const inline
References current_state_, and INITIALIZED.
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsBeginningWithURL(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), OnURLsDeleted(), and UpdateShortcut().
InitInternal()
void ShortcutsBackend::InitInternal () private
References current_state_, db_, InitCompleted(), INITIALIZING, main_runner_, temp_guid_map_, and temp_shortcuts_map_.
Referenced by Init().
MatchToMatchCore()
ShortcutsDatabase::Shortcut::MatchCore ShortcutsBackend::MatchToMatchCore (const AutocompleteMatch & match, TemplateURLService * template_url_service, SearchTermsData * search_terms_data) static private
References AutocompleteMatch::contents, AutocompleteMatch::contents_class, BaseSearchProvider::CreateSearchSuggestion(), AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::description_class_for_shortcuts, AutocompleteMatch::description_for_shortcuts, AutocompleteMatch::destination_url, AutocompleteMatch::document_type, AutocompleteMatch::fill_into_edit, AutocompleteMatch::GetTemplateURL(), AutocompleteMatch::IsSpecializedSearchType(), AutocompleteMatch::keyword, AutocompleteMatch::search_terms_args, AutocompleteMatch::transition, and AutocompleteMatch::type.
Referenced by AddOrUpdateShortcut().
OnURLsDeleted()
void ShortcutsBackend::OnURLsDeleted (history::HistoryService * history_service, const history::DeletionInfo & deletion_info) override private
References DeleteAllShortcuts(), DeleteShortcutsWithIDs(), guid_map_, and initialized().
operator=()
ShortcutsBackend& ShortcutsBackend::operator= (const ShortcutsBackend &) delete
RemoveObserver()
void ShortcutsBackend::RemoveObserver (ShortcutsBackendObserver * obs)
References observer_list_.
shortcuts_map()
const ShortcutMap& ShortcutsBackend::shortcuts_map () const inline
References shortcuts_map_.
Referenced by ShortcutsProvider::FindFirstMatch().
ShutdownOnUIThread()
void ShortcutsBackend::ShutdownOnUIThread () override private
References history_service_observation_.
UpdateShortcut()
bool ShortcutsBackend::UpdateShortcut (const ShortcutsDatabase::Shortcut & shortcut) private
References db_, db_runner_, guid_map_, ShortcutsDatabase::Shortcut::id, initialized(), no_db_access_, observer_list_, shortcuts_map_, ShortcutsDatabase::Shortcut::text, and ShortcutsDatabase::UpdateShortcut().
Referenced by AddOrUpdateShortcut().
Friends And Related Function Documentation
base::RefCountedThreadSafe< ShortcutsBackend >
friend class base::RefCountedThreadSafe< ShortcutsBackend > friend
PopulateShortcutsBackendWithTestData
void PopulateShortcutsBackendWithTestData (scoped_refptr< ShortcutsBackend > backend, TestShortcutData * db, size_t db_size) friend
ShortcutsBackendTest
friend class ShortcutsBackendTest friend
Member Data Documentation
current_state_
CurrentState ShortcutsBackend::current_state_ private
Referenced by Init(), InitCompleted(), initialized(), and InitInternal().
db_
scoped_refptr<ShortcutsDatabase> ShortcutsBackend::db_ private
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), InitInternal(), UpdateShortcut(), and ~ShortcutsBackend().
db_runner_
scoped_refptr<base::SequencedTaskRunner> ShortcutsBackend::db_runner_ private
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), Init(), UpdateShortcut(), and ~ShortcutsBackend().
guid_map_
GuidMap ShortcutsBackend::guid_map_ private
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), InitCompleted(), OnURLsDeleted(), and UpdateShortcut().
history_service_observation_
base::ScopedObservation<history::HistoryService, history::HistoryServiceObserver> ShortcutsBackend::history_service_observation_ {this} private
Referenced by ShutdownOnUIThread().
main_runner_
scoped_refptr<base::SequencedTaskRunner> ShortcutsBackend::main_runner_ private
Referenced by InitInternal().
no_db_access_
bool ShortcutsBackend::no_db_access_ private
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), Init(), and UpdateShortcut().
observer_list_
base::ObserverList<ShortcutsBackendObserver>::Unchecked ShortcutsBackend::observer_list_ private
Referenced by AddObserver(), AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), InitCompleted(), RemoveObserver(), and UpdateShortcut().
search_terms_data_
std::unique_ptr<SearchTermsData> ShortcutsBackend::search_terms_data_ private
Referenced by AddOrUpdateShortcut().
shortcuts_map_
ShortcutMap ShortcutsBackend::shortcuts_map_ private
Referenced by AddOrUpdateShortcut(), AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), InitCompleted(), shortcuts_map(), and UpdateShortcut().
temp_guid_map_
std::unique_ptr<GuidMap> ShortcutsBackend::temp_guid_map_ private
Referenced by InitCompleted(), and InitInternal().
temp_shortcuts_map_
std::unique_ptr<ShortcutMap> ShortcutsBackend::temp_shortcuts_map_ private
Referenced by InitCompleted(), and InitInternal().
template_url_service_
TemplateURLService* ShortcutsBackend::template_url_service_ private
Referenced by AddOrUpdateShortcut().
The documentation for this class was generated from the following files:
components/omnibox/browser/shortcuts_backend.h
components/omnibox/browser/shortcuts_backend.cc