Chromium Omnibox: KeywordProvider Class Reference
KeywordProvider Class Reference
#include <keyword_provider.h>
Public Member Functions
KeywordProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
KeywordProvider (const KeywordProvider &)=delete
KeywordProvider & operator= (const KeywordProvider &)=delete
std::u16string GetKeywordForText (const std::u16string &text) const
AutocompleteMatch CreateVerbatimMatch (const std::u16string &text, const std::u16string &keyword, const AutocompleteInput &input)
void DeleteMatch (const AutocompleteMatch &match) override
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static std::u16string SplitKeywordFromInput (const std::u16string &input, bool trim_leading_whitespace, std::u16string *remaining_input)
static std::u16string SplitReplacementStringFromInput (const std::u16string &input, bool trim_leading_whitespace)
static const TemplateURL * GetSubstitutingTemplateURLForInput (TemplateURLService *model, AutocompleteInput *input)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Member Functions
~KeywordProvider () override
AutocompleteMatch CreateAutocompleteMatch (const TemplateURL *template_url, const size_t meaningful_keyword_length, const AutocompleteInput &input, size_t prefix_length, const std::u16string &remaining_input, bool allowed_to_be_default_match, int relevance, bool deletable)
void FillInURLAndContents (const std::u16string &remaining_input, const TemplateURL *element, AutocompleteMatch *match) const
TemplateURLService * GetTemplateURLService () const
Static Private Member Functions
static bool ExtractKeywordFromInput (const AutocompleteInput &input, const TemplateURLService *template_url_service, std::u16string *keyword, std::u16string *remaining_input)
static int CalculateRelevance (metrics::OmniboxInputType type, bool complete, bool sufficiently_complete, bool support_replacement, bool prefer_keyword, bool allow_exact_keyword_match)
static std::u16string CleanUserInputKeyword (const TemplateURLService *template_url_service, const std::u16string &keyword)
Private Attributes
AutocompleteProviderListener * listener_
AutocompleteInput keyword_input_
TemplateURLService * model_
std::unique_ptr< KeywordExtensionsDelegate > extensions_delegate_
Friends
class KeywordExtensionsDelegateImpl
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
KeywordProvider() [1/2]
KeywordProvider::KeywordProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener)
KeywordProvider() [2/2]
KeywordProvider::KeywordProvider (const KeywordProvider &) delete
~KeywordProvider()
KeywordProvider::~KeywordProvider () override private
Member Function Documentation
CalculateRelevance()
int KeywordProvider::CalculateRelevance (metrics::OmniboxInputType type, bool complete, bool sufficiently_complete, bool support_replacement, bool prefer_keyword, bool allow_exact_keyword_match) static private
References SearchProvider::CalculateRelevanceForKeywordVerbatim(), OmniboxFieldTrial::KeywordScoreForSufficientlyCompleteMatch(), and AutocompleteProvider::type().
Referenced by CreateAutocompleteMatch().
CleanUserInputKeyword()
std::u16string KeywordProvider::CleanUserInputKeyword (const TemplateURLService * template_url_service, const std::u16string & keyword) static private
Referenced by ExtractKeywordFromInput(), and GetKeywordForText().
CreateAutocompleteMatch()
AutocompleteMatch KeywordProvider::CreateAutocompleteMatch (const TemplateURL * template_url, const size_t meaningful_keyword_length, const AutocompleteInput & input, size_t prefix_length, const std::u16string & remaining_input, bool allowed_to_be_default_match, int relevance, bool deletable) private
References AutocompleteInput::allow_exact_keyword_match(), AutocompleteMatch::allowed_to_be_default_match, CalculateRelevance(), AutocompleteMatch::fill_into_edit, FillInURLAndContents(), AutocompleteMatch::from_keyword, GetTemplateURLService(), AutocompleteMatchType::HISTORY_KEYWORD, AutocompleteMatch::keyword, AutocompleteInput::prefer_keyword(), AutocompleteMatchType::SEARCH_OTHER_ENGINE, AutocompleteMatch::transition, and AutocompleteInput::type().
Referenced by CreateVerbatimMatch(), and Start().
CreateVerbatimMatch()
AutocompleteMatch KeywordProvider::CreateVerbatimMatch (const std::u16string & text, const std::u16string & keyword, const AutocompleteInput & input)
References AutocompleteInput::allow_exact_keyword_match(), CreateAutocompleteMatch(), GetTemplateURLService(), and SplitReplacementStringFromInput().
Referenced by AutocompleteController::UpdateAssociatedKeywords().
DeleteMatch()
void KeywordProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteMatch::contents, extensions_delegate_, ExtractKeywordFromInput(), AutocompleteMatch::fill_into_edit, GetTemplateURLService(), AutocompleteMatch::keyword, keyword_input_, and AutocompleteProvider::matches_.
ExtractKeywordFromInput()
bool KeywordProvider::ExtractKeywordFromInput (const AutocompleteInput & input, const TemplateURLService * template_url_service, std::u16string * keyword, std::u16string * remaining_input) static private
References CleanUserInputKeyword(), SplitKeywordFromInput(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by DeleteMatch(), GetSubstitutingTemplateURLForInput(), and Start().
FillInURLAndContents()
void KeywordProvider::FillInURLAndContents (const std::u16string & remaining_input, const TemplateURL * element, AutocompleteMatch * match) const private
References AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::destination_url, AutocompleteMatch::ACMatchClassification::DIM, GetTemplateURLService(), AutocompleteMatch::ACMatchClassification::MATCH, and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by CreateAutocompleteMatch().
GetKeywordForText()
std::u16string KeywordProvider::GetKeywordForText (const std::u16string & text) const
References CleanUserInputKeyword(), extensions_delegate_, GetTemplateURLService(), OmniboxFieldTrial::IsActiveSearchEnginesEnabled(), OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), and SplitKeywordFromInput().
Referenced by AutocompleteController::UpdateAssociatedKeywords().
GetSubstitutingTemplateURLForInput()
const TemplateURL * KeywordProvider::GetSubstitutingTemplateURLForInput (TemplateURLService * model, AutocompleteInput * input) static
References AutocompleteInput::allow_exact_keyword_match(), AutocompleteInput::cursor_position(), ExtractKeywordFromInput(), AutocompleteInput::parts(), AutocompleteInput::text(), and AutocompleteInput::UpdateText().
Referenced by DocumentProvider::IsDocumentProviderAllowed(), and SearchProvider::Start().
GetTemplateURLService()
TemplateURLService * KeywordProvider::GetTemplateURLService () const private
References model_.
Referenced by CreateAutocompleteMatch(), CreateVerbatimMatch(), DeleteMatch(), FillInURLAndContents(), GetKeywordForText(), and Start().
operator=()
KeywordProvider& KeywordProvider::operator= (const KeywordProvider &) delete
SplitKeywordFromInput()
std::u16string KeywordProvider::SplitKeywordFromInput (const std::u16string & input, bool trim_leading_whitespace, std::u16string * remaining_input) static
Referenced by ExtractKeywordFromInput(), GetKeywordForText(), and SplitReplacementStringFromInput().
SplitReplacementStringFromInput()
std::u16string KeywordProvider::SplitReplacementStringFromInput (const std::u16string & input, bool trim_leading_whitespace) static
References SplitKeywordFromInput().
Referenced by CreateVerbatimMatch(), OmniboxEditModel::MaybeStripKeyword(), and OmniboxEditModel::OnCurrentMatchChanged().
Start()
void KeywordProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References AutocompleteInput::allow_exact_keyword_match(), CreateAutocompleteMatch(), omnibox::DEFAULT, AutocompleteProvider::done_, extensions_delegate_, ExtractKeywordFromInput(), AutocompleteInput::focus_type(), GetTemplateURLService(), keyword_input_, AutocompleteProvider::matches(), AutocompleteProvider::matches_, model_, and AutocompleteProvider::provider_max_matches_.
Stop()
void KeywordProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::done_, and extensions_delegate_.
Friends And Related Function Documentation
KeywordExtensionsDelegateImpl
friend class KeywordExtensionsDelegateImpl friend
Member Data Documentation
extensions_delegate_
std::unique_ptr<KeywordExtensionsDelegate> KeywordProvider::extensions_delegate_ private
Referenced by DeleteMatch(), GetKeywordForText(), Start(), and Stop().
keyword_input_
AutocompleteInput KeywordProvider::keyword_input_ private
Referenced by DeleteMatch(), and Start().
listener_
AutocompleteProviderListener* KeywordProvider::listener_ private
model_
TemplateURLService* KeywordProvider::model_ private
Referenced by GetTemplateURLService(), and Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/keyword_provider.h
components/omnibox/browser/keyword_provider.cc