Chromium Omnibox: ZeroSuggestVerbatimMatchProvider Class Reference
ZeroSuggestVerbatimMatchProvider Class Reference
#include <zero_suggest_verbatim_match_provider.h>
Public Member Functions
ZeroSuggestVerbatimMatchProvider (AutocompleteProviderClient *client)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Member Functions
~ZeroSuggestVerbatimMatchProvider () override
Private Attributes
AutocompleteProviderClient *const client_ {nullptr}
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
ZeroSuggestVerbatimMatchProvider()
ZeroSuggestVerbatimMatchProvider::ZeroSuggestVerbatimMatchProvider (AutocompleteProviderClient * client) explicit
~ZeroSuggestVerbatimMatchProvider()
ZeroSuggestVerbatimMatchProvider::~ZeroSuggestVerbatimMatchProvider () override private default
Member Function Documentation
Start()
void ZeroSuggestVerbatimMatchProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References client_, AutocompleteMatch::contents, AutocompleteInput::current_page_classification(), AutocompleteInput::current_title(), AutocompleteInput::current_url(), omnibox::DEFAULT, AutocompleteMatch::destination_url, AutocompleteInput::focus_type(), AutocompleteProviderClient::GetEmbedderRepresentationOfAboutScheme(), AutocompleteMatch::GetFormatTypes(), AutocompleteProvider::matches_, AutocompleteMatch::provider, AutocompleteInput::set_allow_exact_keyword_match(), AutocompleteInput::set_prevent_inline_autocomplete(), Stop(), AutocompleteInput::type(), and VerbatimMatchForURL().
Stop()
void ZeroSuggestVerbatimMatchProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::matches_.
Referenced by Start().
Member Data Documentation
client_
AutocompleteProviderClient* const ZeroSuggestVerbatimMatchProvider::client_ {nullptr} private
Referenced by Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/zero_suggest_verbatim_match_provider.h
components/omnibox/browser/zero_suggest_verbatim_match_provider.cc