Chromium Omnibox: OmniboxPedal Class Reference
OmniboxPedal Class Reference
#include <omnibox_pedal.h>
Classes
class SynonymGroup
struct SynonymGroupSpec
struct Token
class TokenSequence
Public Member Functions
OmniboxPedal (OmniboxPedalId id, LabelStrings strings, GURL url)
void SetLabelStrings (const base::Value &ui_strings)
void SetNavigationUrl (const GURL &url)
void AddVerbatimSequence (TokenSequence sequence)
void AddSynonymGroup (SynonymGroup &&group)
virtual std::vector< SynonymGroupSpec > SpecifySynonymGroups () const
OmniboxPedalId id () const
virtual OmniboxPedalId GetMetricsId () const
bool IsConceptMatch (TokenSequence &match_sequence) const
void RecordActionShown (size_t position) const override
void RecordActionExecuted (size_t position) const override
const gfx::VectorIcon & GetVectorIcon () const override
size_t EstimateMemoryUsage () const override
int32_t GetID () const override
Public Member Functions inherited from OmniboxAction
OmniboxAction (LabelStrings strings, GURL url)
const LabelStrings & GetLabelStrings () const
virtual void Execute (ExecutionContext &context) const
virtual bool IsReadyToTrigger (const AutocompleteInput &input, const AutocompleteProviderClient &client) const
virtual SkColor GetVectorIconColor () const
Static Public Member Functions
static const gfx::VectorIcon & GetDefaultVectorIcon ()
Protected Member Functions
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest, SynonymGroupErasesFirstMatchOnly)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest, SynonymGroupsDriveConceptMatches)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest, VerbatimSynonymGroupDrivesConceptMatches)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest, UnorderedSynonymExpressionsAreConceptMatches)
~OmniboxPedal () override
Protected Member Functions inherited from OmniboxAction
virtual ~OmniboxAction ()
void OpenURL (ExecutionContext &context, const GURL &url) const
Protected Attributes
OmniboxPedalId id_
SynonymGroup verbatim_synonym_group_
std::vector< SynonymGroup > synonym_groups_
Protected Attributes inherited from OmniboxAction
LabelStrings strings_
GURL url_
Constructor & Destructor Documentation
OmniboxPedal()
OmniboxPedal::OmniboxPedal (OmniboxPedalId id, LabelStrings strings, GURL url)
~OmniboxPedal()
OmniboxPedal::~OmniboxPedal () override protected default
Member Function Documentation
AddSynonymGroup()
void OmniboxPedal::AddSynonymGroup (SynonymGroup && group)
References synonym_groups_.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
AddVerbatimSequence()
void OmniboxPedal::AddVerbatimSequence (TokenSequence sequence)
References OmniboxPedal::SynonymGroup::AddSynonym(), OmniboxPedal::TokenSequence::ResetLinks(), and verbatim_synonym_group_.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
EstimateMemoryUsage()
size_t OmniboxPedal::EstimateMemoryUsage () const override virtual
Reimplemented from OmniboxAction.
References OmniboxAction::EstimateMemoryUsage(), base::trace_event::EstimateMemoryUsage(), synonym_groups_, and verbatim_synonym_group_.
FRIEND_TEST_ALL_PREFIXES() [1/4]
OmniboxPedal::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest , UnorderedSynonymExpressionsAreConceptMatches) protected
FRIEND_TEST_ALL_PREFIXES() [2/4]
OmniboxPedal::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest , SynonymGroupErasesFirstMatchOnly) protected
FRIEND_TEST_ALL_PREFIXES() [3/4]
OmniboxPedal::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest , SynonymGroupsDriveConceptMatches) protected
FRIEND_TEST_ALL_PREFIXES() [4/4]
OmniboxPedal::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalTest , VerbatimSynonymGroupDrivesConceptMatches) protected
GetDefaultVectorIcon()
const gfx::VectorIcon & OmniboxPedal::GetDefaultVectorIcon () static
Referenced by GetVectorIcon(), and OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView().
GetID()
int32_t OmniboxPedal::GetID () const override virtual
Reimplemented from OmniboxAction.
References id().
GetMetricsId()
OmniboxPedalId OmniboxPedal::GetMetricsId () const virtual
Reimplemented in OmniboxPedalManageChromeOSAccessibility, and OmniboxPedalClearBrowsingData.
References id().
Referenced by RecordActionExecuted(), and RecordActionShown().
GetVectorIcon()
const gfx::VectorIcon & OmniboxPedal::GetVectorIcon () const override virtual
Reimplemented from OmniboxAction.
Reimplemented in OmniboxPedalManageChromeOSAccessibility, OmniboxPedalManageChromeAccessibility, OmniboxPedalShareThisPage, OmniboxPedalViewChromeHistory, OmniboxPedalManageChromeDownloads, OmniboxPedalManageChromeSettings, OmniboxPedalManageGooglePrivacy, OmniboxPedalFindMyPhone, OmniboxPedalPlayChromeDinoGame, OmniboxPedalCloseIncognitoWindows, OmniboxPedalChangeGooglePassword, OmniboxPedalManageGoogleAccount, OmniboxPedalCreateGoogleForm, OmniboxPedalCreateGoogleKeepNote, OmniboxPedalCreateGoogleSite, OmniboxPedalCreateGoogleCalendarEvent, OmniboxPedalCreateGoogleSlide, OmniboxPedalCreateGoogleSheet, and OmniboxPedalCreateGoogleDoc.
References GetDefaultVectorIcon().
id()
OmniboxPedalId OmniboxPedal::id () const inline
References id_.
Referenced by OmniboxPedal::TokenSequence::Add(), GetID(), GetMetricsId(), and OmniboxPedalClearBrowsingData::GetMetricsId().
IsConceptMatch()
bool OmniboxPedal::IsConceptMatch (TokenSequence & match_sequence) const
References OmniboxPedal::SynonymGroup::EraseMatchesIn(), OmniboxPedal::TokenSequence::IsFullyConsumed(), OmniboxPedal::TokenSequence::ResetLinks(), synonym_groups_, and verbatim_synonym_group_.
RecordActionExecuted()
void OmniboxPedal::RecordActionExecuted (size_t position) const override virtual
Reimplemented from OmniboxAction.
References GetMetricsId(), and TOTAL_COUNT.
RecordActionShown()
void OmniboxPedal::RecordActionShown (size_t position) const override virtual
Reimplemented from OmniboxAction.
References GetMetricsId(), and TOTAL_COUNT.
SetLabelStrings()
void OmniboxPedal::SetLabelStrings (const base::Value & ui_strings)
References OmniboxAction::LabelStrings::accessibility_hint, OmniboxAction::LabelStrings::accessibility_suffix, OmniboxAction::LabelStrings::hint, OmniboxAction::strings_, and OmniboxAction::LabelStrings::suggestion_contents.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
SetNavigationUrl()
void OmniboxPedal::SetNavigationUrl (const GURL & url)
References OmniboxAction::url_.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
SpecifySynonymGroups()
std::vector< OmniboxPedal::SynonymGroupSpec > OmniboxPedal::SpecifySynonymGroups () const virtual
Reimplemented in OmniboxPedalPlayChromeDinoGame, OmniboxPedalCloseIncognitoWindows, OmniboxPedalChangeGooglePassword, OmniboxPedalManageGoogleAccount, OmniboxPedalSeeChromeTips, OmniboxPedalCreateGoogleForm, OmniboxPedalCreateGoogleKeepNote, OmniboxPedalCreateGoogleSite, OmniboxPedalCreateGoogleCalendarEvent, OmniboxPedalCreateGoogleSlide, OmniboxPedalCreateGoogleSheet, OmniboxPedalCreateGoogleDoc, OmniboxPedalManageSiteSettings, OmniboxPedalManageSync, OmniboxPedalManageAddresses, OmniboxPedalManageCookies, OmniboxPedalManageSecuritySettings, OmniboxPedalRunChromeSafetyCheck, OmniboxPedalUpdateChrome, OmniboxPedalTranslate, OmniboxPedalLaunchIncognito, OmniboxPedalUpdateCreditCard, OmniboxPedalManagePasswords, and OmniboxPedalClearBrowsingData.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
Member Data Documentation
id_
OmniboxPedalId OmniboxPedal::id_ protected
Referenced by id().
synonym_groups_
std::vector<SynonymGroup> OmniboxPedal::synonym_groups_ protected
Referenced by AddSynonymGroup(), EstimateMemoryUsage(), and IsConceptMatch().
verbatim_synonym_group_
SynonymGroup OmniboxPedal::verbatim_synonym_group_ protected
Referenced by AddVerbatimSequence(), EstimateMemoryUsage(), and IsConceptMatch().
The documentation for this class was generated from the following files:
components/omnibox/browser/actions/omnibox_pedal.h
components/omnibox/browser/actions/omnibox_pedal.cc