Chromium Omnibox: ChromeOmniboxClient Class Reference
ChromeOmniboxClient Class Reference
#include <chrome_omnibox_client.h>
Public Member Functions
ChromeOmniboxClient (OmniboxEditController *controller, Profile *profile)
~ChromeOmniboxClient () override
std::unique_ptr< AutocompleteProviderClient > CreateAutocompleteProviderClient () override
std::unique_ptr< OmniboxNavigationObserver > CreateOmniboxNavigationObserver (const std::u16string &text, const AutocompleteMatch &match, const AutocompleteMatch &alternate_nav_match) override
bool CurrentPageExists () const override
const GURL & GetURL () const override
const std::u16string & GetTitle () const override
gfx::Image GetFavicon () const override
bool IsLoading () const override
bool IsPasteAndGoEnabled () const override
bool IsDefaultSearchProviderEnabled () const override
const SessionID & GetSessionID () const override
bookmarks::BookmarkModel * GetBookmarkModel () override
OmniboxControllerEmitter * GetOmniboxControllerEmitter () override
TemplateURLService * GetTemplateURLService () override
const AutocompleteSchemeClassifier & GetSchemeClassifier () const override
AutocompleteClassifier * GetAutocompleteClassifier () override
bool ShouldDefaultTypedNavigationsToHttps () const override
int GetHttpsPortForTesting () const override
gfx::Image GetIconIfExtensionMatch (const AutocompleteMatch &match) const override
gfx::Image GetSizedIcon (const gfx::VectorIcon &vector_icon_type, SkColor vector_icon_color) const override
gfx::Image GetSizedIcon (const gfx::Image &icon) const override
bool ProcessExtensionKeyword (const TemplateURL *template_url, const AutocompleteMatch &match, WindowOpenDisposition disposition, OmniboxNavigationObserver *observer) override
void OnInputStateChanged () override
void OnFocusChanged (OmniboxFocusState state, OmniboxFocusChangeReason reason) override
void OnResultChanged (const AutocompleteResult &result, bool default_match_changed, const BitmapFetchedCallback &on_bitmap_fetched) override
gfx::Image GetFaviconForPageUrl (const GURL &page_url, FaviconFetchedCallback on_favicon_fetched) override
gfx::Image GetFaviconForDefaultSearchProvider (FaviconFetchedCallback on_favicon_fetched) override
gfx::Image GetFaviconForKeywordSearchProvider (const TemplateURL *template_url, FaviconFetchedCallback on_favicon_fetched) override
void OnTextChanged (const AutocompleteMatch &current_match, bool user_input_in_progress, const std::u16string &user_text, const AutocompleteResult &result, bool has_focus) override
void OnRevert () override
void OnURLOpenedFromOmnibox (OmniboxLog *log) override
void OnBookmarkLaunched () override
void DiscardNonCommittedNavigations () override
void OpenUpdateChromeDialog () override
void NewIncognitoWindow () override
void OpenIncognitoClearBrowsingDataDialog () override
void CloseIncognitoWindows () override
void PromptPageTranslation () override
Public Member Functions inherited from OmniboxClient
virtual ~OmniboxClient ()
virtual void OnInputAccepted (const AutocompleteMatch &match)
void NewIncognitoWindow () override
void OpenIncognitoClearBrowsingDataDialog () override
void CloseIncognitoWindows () override
void PromptPageTranslation () override
Private Member Functions
void DoPrerender (const AutocompleteMatch &match)
void DoPreconnect (const AutocompleteMatch &match)
void OnBitmapFetched (const BitmapFetchedCallback &callback, int result_index, bool is_cached, base::TimeTicks start_time, const SkBitmap &bitmap)
DISALLOW_COPY_AND_ASSIGN (ChromeOmniboxClient)
Private Attributes
ChromeOmniboxEditController * controller_
Profile * profile_
ChromeAutocompleteSchemeClassifier scheme_classifier_
std::vector< BitmapFetcherService::RequestId > request_ids_
FaviconCache favicon_cache_
base::WeakPtrFactory< ChromeOmniboxClient > weak_factory_ {this}
Constructor & Destructor Documentation
ChromeOmniboxClient()
ChromeOmniboxClient::ChromeOmniboxClient (OmniboxEditController * controller, Profile * profile)
~ChromeOmniboxClient()
ChromeOmniboxClient::~ChromeOmniboxClient () override
References profile_, and request_ids_.
Member Function Documentation
CloseIncognitoWindows()
void ChromeOmniboxClient::CloseIncognitoWindows () override virtual
Implements OmniboxAction::Client.
References profile_.
CreateAutocompleteProviderClient()
std::unique_ptr< AutocompleteProviderClient > ChromeOmniboxClient::CreateAutocompleteProviderClient () override virtual
Implements OmniboxClient.
References profile_.
CreateOmniboxNavigationObserver()
std::unique_ptr< OmniboxNavigationObserver > ChromeOmniboxClient::CreateOmniboxNavigationObserver (const std::u16string & text, const AutocompleteMatch & match, const AutocompleteMatch & alternate_nav_match) override virtual
Reimplemented from OmniboxClient.
References ChromeOmniboxNavigationObserver::ChromeOmniboxNavigationObserver(), and profile_.
CurrentPageExists()
bool ChromeOmniboxClient::CurrentPageExists () const override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
Referenced by GetTitle(), GetURL(), and OnTextChanged().
DISALLOW_COPY_AND_ASSIGN()
ChromeOmniboxClient::DISALLOW_COPY_AND_ASSIGN (ChromeOmniboxClient) private
DiscardNonCommittedNavigations()
void ChromeOmniboxClient::DiscardNonCommittedNavigations () override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
DoPreconnect()
void ChromeOmniboxClient::DoPreconnect (const AutocompleteMatch & match) private
References AutocompleteMatch::destination_url, AutocompleteMatchType::NUM_TYPES, profile_, and AutocompleteMatch::type.
Referenced by OnTextChanged().
DoPrerender()
void ChromeOmniboxClient::DoPrerender (const AutocompleteMatch & match) private
References controller_, AutocompleteMatch::destination_url, ChromeOmniboxEditController::GetWebContents(), and profile_.
Referenced by OnTextChanged().
GetAutocompleteClassifier()
AutocompleteClassifier * ChromeOmniboxClient::GetAutocompleteClassifier () override virtual
Reimplemented from OmniboxClient.
References profile_.
GetBookmarkModel()
bookmarks::BookmarkModel * ChromeOmniboxClient::GetBookmarkModel () override virtual
Reimplemented from OmniboxClient.
References profile_.
GetFavicon()
gfx::Image ChromeOmniboxClient::GetFavicon () const override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
GetFaviconForDefaultSearchProvider()
gfx::Image ChromeOmniboxClient::GetFaviconForDefaultSearchProvider (FaviconFetchedCallback on_favicon_fetched) override virtual
Reimplemented from OmniboxClient.
References favicon_cache_, FaviconCache::GetFaviconForIconUrl(), and GetTemplateURLService().
GetFaviconForKeywordSearchProvider()
gfx::Image ChromeOmniboxClient::GetFaviconForKeywordSearchProvider (const TemplateURL * template_url, FaviconFetchedCallback on_favicon_fetched) override virtual
Reimplemented from OmniboxClient.
References favicon_cache_, and FaviconCache::GetFaviconForIconUrl().
GetFaviconForPageUrl()
gfx::Image ChromeOmniboxClient::GetFaviconForPageUrl (const GURL & page_url, FaviconFetchedCallback on_favicon_fetched) override virtual
Reimplemented from OmniboxClient.
References favicon_cache_, and FaviconCache::GetFaviconForPageUrl().
GetHttpsPortForTesting()
int ChromeOmniboxClient::GetHttpsPortForTesting () const override virtual
Implements OmniboxClient.
GetIconIfExtensionMatch()
gfx::Image ChromeOmniboxClient::GetIconIfExtensionMatch (const AutocompleteMatch & match) const override virtual
Reimplemented from OmniboxClient.
References AutocompleteMatch::GetTemplateURL(), and profile_.
GetOmniboxControllerEmitter()
OmniboxControllerEmitter * ChromeOmniboxClient::GetOmniboxControllerEmitter () override virtual
Reimplemented from OmniboxClient.
References OmniboxControllerEmitter::GetForBrowserContext(), and profile_.
GetSchemeClassifier()
const AutocompleteSchemeClassifier & ChromeOmniboxClient::GetSchemeClassifier () const override virtual
Implements OmniboxClient.
References scheme_classifier_.
GetSessionID()
const SessionID & ChromeOmniboxClient::GetSessionID () const override virtual
Implements OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
GetSizedIcon() [1/2]
gfx::Image ChromeOmniboxClient::GetSizedIcon (const gfx::Image & icon) const override virtual
Reimplemented from OmniboxClient.
GetSizedIcon() [2/2]
gfx::Image ChromeOmniboxClient::GetSizedIcon (const gfx::VectorIcon & vector_icon_type, SkColor vector_icon_color) const override virtual
Reimplemented from OmniboxClient.
GetTemplateURLService()
TemplateURLService * ChromeOmniboxClient::GetTemplateURLService () override virtual
Reimplemented from OmniboxClient.
References profile_.
Referenced by GetFaviconForDefaultSearchProvider().
GetTitle()
const std::u16string & ChromeOmniboxClient::GetTitle () const override virtual
Reimplemented from OmniboxClient.
References controller_, CurrentPageExists(), and ChromeOmniboxEditController::GetWebContents().
GetURL()
const GURL & ChromeOmniboxClient::GetURL () const override virtual
Reimplemented from OmniboxClient.
References controller_, CurrentPageExists(), and ChromeOmniboxEditController::GetWebContents().
Referenced by OnTextChanged().
IsDefaultSearchProviderEnabled()
bool ChromeOmniboxClient::IsDefaultSearchProviderEnabled () const override virtual
Reimplemented from OmniboxClient.
References profile_.
IsLoading()
bool ChromeOmniboxClient::IsLoading () const override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
IsPasteAndGoEnabled()
bool ChromeOmniboxClient::IsPasteAndGoEnabled () const override virtual
Reimplemented from OmniboxClient.
References ChromeOmniboxEditController::command_updater(), and controller_.
NewIncognitoWindow()
void ChromeOmniboxClient::NewIncognitoWindow () override virtual
Implements OmniboxAction::Client.
References profile_.
OnBitmapFetched()
void ChromeOmniboxClient::OnBitmapFetched (const BitmapFetchedCallback & callback, int result_index, bool is_cached, base::TimeTicks start_time, const SkBitmap & bitmap) private
Referenced by OnResultChanged().
OnBookmarkLaunched()
void ChromeOmniboxClient::OnBookmarkLaunched () override virtual
Reimplemented from OmniboxClient.
References profile_.
OnFocusChanged()
void ChromeOmniboxClient::OnFocusChanged (OmniboxFocusState state, OmniboxFocusChangeReason reason) override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
OnInputStateChanged()
void ChromeOmniboxClient::OnInputStateChanged () override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
OnResultChanged()
void ChromeOmniboxClient::OnResultChanged (const AutocompleteResult & result, bool default_match_changed, const BitmapFetchedCallback & on_bitmap_fetched) override virtual
Reimplemented from OmniboxClient.
References OnBitmapFetched(), profile_, request_ids_, and weak_factory_.
OnRevert()
void ChromeOmniboxClient::OnRevert () override virtual
Reimplemented from OmniboxClient.
References profile_.
OnTextChanged()
void ChromeOmniboxClient::OnTextChanged (const AutocompleteMatch & current_match, bool user_input_in_progress, const std::u16string & user_text, const AutocompleteResult & result, bool has_focus) override virtual
Reimplemented from OmniboxClient.
References CurrentPageExists(), AutocompleteMatch::destination_url, DoPreconnect(), DoPrerender(), GetURL(), and profile_.
OnURLOpenedFromOmnibox()
void ChromeOmniboxClient::OnURLOpenedFromOmnibox (OmniboxLog * log) override virtual
Reimplemented from OmniboxClient.
References profile_.
OpenIncognitoClearBrowsingDataDialog()
void ChromeOmniboxClient::OpenIncognitoClearBrowsingDataDialog () override virtual
Implements OmniboxAction::Client.
References controller_, and ChromeOmniboxEditController::GetWebContents().
OpenUpdateChromeDialog()
void ChromeOmniboxClient::OpenUpdateChromeDialog () override virtual
Reimplemented from OmniboxClient.
References controller_, and ChromeOmniboxEditController::GetWebContents().
ProcessExtensionKeyword()
bool ChromeOmniboxClient::ProcessExtensionKeyword (const TemplateURL * template_url, const AutocompleteMatch & match, WindowOpenDisposition disposition, OmniboxNavigationObserver * observer) override virtual
Reimplemented from OmniboxClient.
References controller_, AutocompleteMatch::fill_into_edit, ChromeOmniboxEditController::GetWebContents(), and AutocompleteMatch::keyword.
PromptPageTranslation()
void ChromeOmniboxClient::PromptPageTranslation () override virtual
Implements OmniboxAction::Client.
References controller_, and ChromeOmniboxEditController::GetWebContents().
ShouldDefaultTypedNavigationsToHttps()
bool ChromeOmniboxClient::ShouldDefaultTypedNavigationsToHttps () const override virtual
Implements OmniboxClient.
References omnibox::kDefaultTypedNavigationsToHttps.
Member Data Documentation
controller_
ChromeOmniboxEditController* ChromeOmniboxClient::controller_ private
Referenced by CurrentPageExists(), DiscardNonCommittedNavigations(), DoPrerender(), GetFavicon(), GetSessionID(), GetTitle(), GetURL(), IsLoading(), IsPasteAndGoEnabled(), OnFocusChanged(), OnInputStateChanged(), OpenIncognitoClearBrowsingDataDialog(), OpenUpdateChromeDialog(), ProcessExtensionKeyword(), and PromptPageTranslation().
favicon_cache_
FaviconCache ChromeOmniboxClient::favicon_cache_ private
Referenced by GetFaviconForDefaultSearchProvider(), GetFaviconForKeywordSearchProvider(), and GetFaviconForPageUrl().
profile_
Profile* ChromeOmniboxClient::profile_ private
Referenced by CloseIncognitoWindows(), CreateAutocompleteProviderClient(), CreateOmniboxNavigationObserver(), DoPreconnect(), DoPrerender(), GetAutocompleteClassifier(), GetBookmarkModel(), GetIconIfExtensionMatch(), GetOmniboxControllerEmitter(), GetTemplateURLService(), IsDefaultSearchProviderEnabled(), NewIncognitoWindow(), OnBookmarkLaunched(), OnResultChanged(), OnRevert(), OnTextChanged(), OnURLOpenedFromOmnibox(), and ~ChromeOmniboxClient().
request_ids_
std::vector<BitmapFetcherService::RequestId> ChromeOmniboxClient::request_ids_ private
Referenced by OnResultChanged(), and ~ChromeOmniboxClient().
scheme_classifier_
ChromeAutocompleteSchemeClassifier ChromeOmniboxClient::scheme_classifier_ private
Referenced by GetSchemeClassifier().
weak_factory_
base::WeakPtrFactory<ChromeOmniboxClient> ChromeOmniboxClient::weak_factory_ {this} private
Referenced by OnResultChanged().
The documentation for this class was generated from the following files:
chrome/browser/ui/omnibox/chrome_omnibox_client.h
chrome/browser/ui/omnibox/chrome_omnibox_client.cc