Chromium Omnibox: components/omnibox/browser/inline_autocompletion_util.cc File Reference
inline_autocompletion_util.cc File Reference
#include "inline_autocompletion_util.h"
Functions
size_t FindAtWordbreak (const std::u16string &text, const std::u16string &search, size_t search_start)
std::vector< std::pair< size_t, size_t > > FindWordsSequentiallyAtWordbreak (const std::u16string &text, const std::u16string &search)
std::vector< gfx::Range > TermMatchesToSelections (size_t length, std::vector< std::pair< size_t, size_t >> matches)
Function Documentation
FindAtWordbreak()
size_t FindAtWordbreak (const std::u16string & text, const std::u16string & search, size_t search_start)
References String16VectorFromString16().
Referenced by FindWordsSequentiallyAtWordbreak(), and AutocompleteMatch::TryRichAutocompletion().
FindWordsSequentiallyAtWordbreak()
std::vector<std::pair<size_t, size_t> > FindWordsSequentiallyAtWordbreak (const std::u16string & text, const std::u16string & search)
References FindAtWordbreak(), and String16VectorFromString16().
Referenced by AutocompleteMatch::TryRichAutocompletion().
TermMatchesToSelections()
std::vector<gfx::Range> TermMatchesToSelections (size_t length, std::vector< std::pair< size_t, size_t >> matches)
Referenced by AutocompleteMatch::TryRichAutocompletion().