Chromium Omnibox: AutocompleteInput Class Reference
AutocompleteInput Class Reference
#include <autocomplete_input.h>
Public Member Functions
AutocompleteInput ()
AutocompleteInput (const std::u16string &text, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier &scheme_classifier, bool should_use_https_as_default_scheme=false, int https_port_for_testing=0)
AutocompleteInput (const std::u16string &text, size_t cursor_position, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier &scheme_classifier, bool should_use_https_as_default_scheme=false, int https_port_for_testing=0)
AutocompleteInput (const std::u16string &text, size_t cursor_position, const std::string &desired_tld, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier &scheme_classifier, bool should_use_https_as_default_scheme=false, int https_port_for_testing=0)
AutocompleteInput (const AutocompleteInput &other)
~AutocompleteInput ()
const std::u16string & text () const
size_t cursor_position () const
void UpdateText (const std::u16string &text, size_t cursor_position, const url::Parsed &parts)
const GURL & current_url () const
void set_current_url (const GURL &current_url)
const std::u16string & current_title () const
void set_current_title (const std::u16string &title)
metrics::OmniboxEventProto::PageClassification current_page_classification () const
metrics::OmniboxInputType type () const
const url::Parsed & parts () const
const std::u16string & scheme () const
const GURL & canonicalized_url () const
const std::string & desired_tld () const
bool prevent_inline_autocomplete () const
void set_prevent_inline_autocomplete (bool prevent_inline_autocomplete)
bool prefer_keyword () const
void set_prefer_keyword (bool prefer_keyword)
bool allow_exact_keyword_match () const
void set_allow_exact_keyword_match (bool allow_exact_keyword_match)
metrics::OmniboxEventProto::KeywordModeEntryMethod keyword_mode_entry_method () const
void set_keyword_mode_entry_method (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method)
bool want_asynchronous_matches () const
void set_want_asynchronous_matches (bool want_asynchronous_matches)
OmniboxFocusType focus_type () const
void set_focus_type (OmniboxFocusType focus_type)
const std::vector< std::u16string > & terms_prefixed_by_http_or_https () const
const absl::optional< std::string > & query_tile_id () const
void set_query_tile_id (const std::string &tile_id)
void Clear ()
size_t EstimateMemoryUsage () const
void set_added_default_scheme_to_typed_url (bool added_default_scheme_to_typed_url)
bool added_default_scheme_to_typed_url () const
Static Public Member Functions
static std::string TypeToString (metrics::OmniboxInputType type)
static metrics::OmniboxInputType Parse (const std::u16string &text, const std::string &desired_tld, const AutocompleteSchemeClassifier &scheme_classifier, url::Parsed *parts, std::u16string *scheme, GURL *canonicalized_url)
static void ParseForEmphasizeComponents (const std::u16string &text, const AutocompleteSchemeClassifier &scheme_classifier, url::Component *scheme, url::Component *host)
static bool ShouldUpgradeToHttps (const std::u16string &text, const GURL &url, int https_port_for_testing, GURL *upgraded_url)
static std::u16string FormattedStringWithEquivalentMeaning (const GURL &url, const std::u16string &formatted_url, const AutocompleteSchemeClassifier &scheme_classifier, size_t *offset)
static int NumNonHostComponents (const url::Parsed &parts)
static bool HasHTTPScheme (const std::u16string &text)
static bool HasHTTPSScheme (const std::u16string &text)
Private Member Functions
void Init (const std::u16string &text, const AutocompleteSchemeClassifier &scheme_classifier)
Private Attributes
std::u16string text_
size_t cursor_position_
GURL current_url_
std::u16string current_title_
metrics::OmniboxEventProto::PageClassification current_page_classification_
metrics::OmniboxInputType type_
url::Parsed parts_
std::u16string scheme_
GURL canonicalized_url_
std::string desired_tld_
bool prevent_inline_autocomplete_
bool prefer_keyword_
bool allow_exact_keyword_match_
metrics::OmniboxEventProto::KeywordModeEntryMethod keyword_mode_entry_method_
bool want_asynchronous_matches_
OmniboxFocusType focus_type_ = OmniboxFocusType::DEFAULT
std::vector< std::u16string > terms_prefixed_by_http_or_https_
absl::optional< std::string > query_tile_id_
bool should_use_https_as_default_scheme_
bool added_default_scheme_to_typed_url_
int https_port_for_testing_
Friends
class AutocompleteProviderTest
Constructor & Destructor Documentation
AutocompleteInput() [1/5]
AutocompleteInput::AutocompleteInput ()
AutocompleteInput() [2/5]
AutocompleteInput::AutocompleteInput (const std::u16string & text, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier & scheme_classifier, bool should_use_https_as_default_scheme = false, int https_port_for_testing = 0)
AutocompleteInput() [3/5]
AutocompleteInput::AutocompleteInput (const std::u16string & text, size_t cursor_position, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier & scheme_classifier, bool should_use_https_as_default_scheme = false, int https_port_for_testing = 0)
AutocompleteInput() [4/5]
AutocompleteInput::AutocompleteInput (const std::u16string & text, size_t cursor_position, const std::string & desired_tld, metrics::OmniboxEventProto::PageClassification current_page_classification, const AutocompleteSchemeClassifier & scheme_classifier, bool should_use_https_as_default_scheme = false, int https_port_for_testing = 0)
References current_page_classification(), current_page_classification_, cursor_position(), cursor_position_, desired_tld(), desired_tld_, https_port_for_testing_, Init(), should_use_https_as_default_scheme_, and text().
AutocompleteInput() [5/5]
AutocompleteInput::AutocompleteInput (const AutocompleteInput & other) default
~AutocompleteInput()
AutocompleteInput::~AutocompleteInput ()
Member Function Documentation
added_default_scheme_to_typed_url()
bool AutocompleteInput::added_default_scheme_to_typed_url () const inline
References added_default_scheme_to_typed_url_.
Referenced by OmniboxEditModel::OpenMatch(), set_added_default_scheme_to_typed_url(), and VerbatimMatchForInput().
allow_exact_keyword_match()
bool AutocompleteInput::allow_exact_keyword_match () const inline
References allow_exact_keyword_match_.
Referenced by OmniboxEditModel::AcceptInput(), KeywordProvider::CreateAutocompleteMatch(), KeywordProvider::CreateVerbatimMatch(), KeywordProvider::GetSubstitutingTemplateURLForInput(), set_allow_exact_keyword_match(), AutocompleteController::Start(), and KeywordProvider::Start().
canonicalized_url()
const GURL& AutocompleteInput::canonicalized_url () const inline
References canonicalized_url_.
Referenced by OmniboxEditModel::AcceptInput(), HistoryURLProvider::AsKnownIntranetURL(), AutocompleteResult::ComputeAlternateNavUrl(), HistoryQuickProvider::FindMaxMatchScore(), Init(), Parse(), HistoryURLProvider::Start(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
Clear()
void AutocompleteInput::Clear ()
References allow_exact_keyword_match_, canonicalized_url_, current_page_classification_, current_title_, current_url_, cursor_position_, omnibox::DEFAULT, focus_type_, https_port_for_testing_, parts_, prefer_keyword_, prevent_inline_autocomplete_, query_tile_id_, scheme_, terms_prefixed_by_http_or_https_, text_, type_, and want_asynchronous_matches_.
Referenced by OmniboxEditModel::Revert(), and SearchProvider::Start().
current_page_classification()
metrics::OmniboxEventProto::PageClassification AutocompleteInput::current_page_classification () const inline
References current_page_classification_.
Referenced by OmniboxEditModel::AcceptInput(), MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), ZeroSuggestProvider::AllowZeroSuggestSuggestions(), AutocompleteInput(), SearchProvider::CreateSuggestLoader(), SearchProvider::DoHistoryQuery(), AutocompleteResult::FindTopMatch(), ShortcutsProvider::GetMatches(), SearchProvider::ScoreHistoryResultsHelper(), AutocompleteResult::SortAndCull(), LocalHistoryZeroSuggestProvider::Start(), MostVisitedSitesProvider::Start(), ZeroSuggestProvider::Start(), ZeroSuggestVerbatimMatchProvider::Start(), ZeroSuggestProvider::TypeOfResultToRun(), AutocompleteController::UpdateMatchDestinationURLWithQueryFormulationTime(), and VerbatimMatchForURL().
current_title()
const std::u16string& AutocompleteInput::current_title () const inline
References current_title_.
Referenced by ClipboardProvider::AddCreatedMatchWithTracking(), ZeroSuggestProvider::Start(), and ZeroSuggestVerbatimMatchProvider::Start().
current_url()
const GURL& AutocompleteInput::current_url () const inline
References current_url_.
Referenced by ClipboardProvider::AddCreatedMatchWithTracking(), MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), QueryTileProvider::AllowQueryTileSuggestions(), ZeroSuggestProvider::AllowZeroSuggestSuggestions(), SearchProvider::CreateSuggestLoader(), ClipboardProvider::CreateURLMatch(), OmniboxPedalTranslate::IsReadyToTrigger(), set_current_url(), ZeroSuggestProvider::Start(), ZeroSuggestVerbatimMatchProvider::Start(), and ZeroSuggestProvider::TypeOfResultToRun().
cursor_position()
size_t AutocompleteInput::cursor_position () const inline
References cursor_position_.
Referenced by OmniboxEditModel::AcceptInput(), AutocompleteInput(), SearchProvider::CreateSuggestLoader(), HistoryQuickProvider::DoAutocomplete(), KeywordProvider::GetSubstitutingTemplateURLForInput(), and UpdateText().
desired_tld()
const std::string& AutocompleteInput::desired_tld () const inline
References desired_tld_.
Referenced by AutocompleteInput(), Parse(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
EstimateMemoryUsage()
size_t AutocompleteInput::EstimateMemoryUsage () const
References canonicalized_url_, current_title_, current_url_, desired_tld_, base::trace_event::EstimateMemoryUsage(), query_tile_id_, scheme_, terms_prefixed_by_http_or_https_, and text_.
Referenced by AutocompleteController::OnMemoryDump().
focus_type()
OmniboxFocusType AutocompleteInput::focus_type () const inline
References focus_type_.
Referenced by OmniboxEditModel::AcceptInput(), MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), ZeroSuggestProvider::AllowZeroSuggestSuggestions(), SearchProvider::CreateSuggestLoader(), DocumentProvider::IsDocumentProviderAllowed(), OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed(), SearchProvider::OnURLLoadComplete(), OmniboxEditModel::OpenMatch(), set_focus_type(), AutocompleteResult::SortAndCull(), AutocompleteController::Start(), BookmarkProvider::Start(), BuiltinProvider::Start(), ClipboardProvider::Start(), HistoryQuickProvider::Start(), HistoryURLProvider::Start(), KeywordProvider::Start(), LocalHistoryZeroSuggestProvider::Start(), SearchProvider::Start(), ShortcutsProvider::Start(), ZeroSuggestProvider::Start(), ZeroSuggestVerbatimMatchProvider::Start(), ZeroSuggestProvider::TypeOfResultToRun(), and SearchProvider::UpdateMatches().
FormattedStringWithEquivalentMeaning()
std::u16string AutocompleteInput::FormattedStringWithEquivalentMeaning (const GURL & url, const std::u16string & formatted_url, const AutocompleteSchemeClassifier & scheme_classifier, size_t * offset) static
References Parse().
Referenced by HistoryURLProvider::HistoryMatchToACMatch(), SearchProvider::NavigationToMatch(), ZeroSuggestProvider::NavigationToMatch(), HistoryQuickProvider::QuickMatchToACMatch(), bookmarks::TitledUrlMatchToAutocompleteMatch(), ClipboardProvider::UpdateClipboardURLContent(), and VerbatimMatchForInput().
HasHTTPScheme()
bool AutocompleteInput::HasHTTPScheme (const std::u16string & text) static
Referenced by AutocompleteProvider::FixupUserInput(), SearchProvider::NavigationToMatch(), HistoryURLProvider::Start(), AutocompleteProvider::TrimSchemePrefix(), VerbatimMatchForInput(), and VerbatimMatchForURL().
HasHTTPSScheme()
bool AutocompleteInput::HasHTTPSScheme (const std::u16string & text) static
Referenced by AutocompleteProvider::TrimSchemePrefix(), and VerbatimMatchForInput().
Init()
void AutocompleteInput::Init (const std::u16string & text, const AutocompleteSchemeClassifier & scheme_classifier) private
References added_default_scheme_to_typed_url_, canonicalized_url(), canonicalized_url_, cursor_position_, desired_tld_, https_port_for_testing_, Parse(), parts_, scheme_, should_use_https_as_default_scheme_, ShouldUpgradeToHttps(), terms_prefixed_by_http_or_https_, text(), text_, and type_.
Referenced by AutocompleteInput().
keyword_mode_entry_method()
metrics::OmniboxEventProto::KeywordModeEntryMethod AutocompleteInput::keyword_mode_entry_method () const inline
References keyword_mode_entry_method_.
Referenced by OmniboxEditModel::AcceptInput(), and AutocompleteProvider::IsExplicitlyInKeywordMode().
NumNonHostComponents()
int AutocompleteInput::NumNonHostComponents (const url::Parsed & parts) static
References parts().
Referenced by HistoryURLProvider::DoAutocomplete(), and Parse().
Parse()
metrics::OmniboxInputType AutocompleteInput::Parse (const std::u16string & text, const std::string & desired_tld, const AutocompleteSchemeClassifier & scheme_classifier, url::Parsed * parts, std::u16string * scheme, GURL * canonicalized_url) static
References canonicalized_url(), desired_tld(), AutocompleteSchemeClassifier::GetInputTypeForScheme(), NumNonHostComponents(), parts(), scheme(), text(), and type().
Referenced by FormattedStringWithEquivalentMeaning(), Init(), and ParseForEmphasizeComponents().
ParseForEmphasizeComponents()
void AutocompleteInput::ParseForEmphasizeComponents (const std::u16string & text, const AutocompleteSchemeClassifier & scheme_classifier, url::Component * scheme, url::Component * host) static
References Parse(), parts(), scheme(), and text().
Referenced by JNI_OmniboxUrlEmphasizer_ParseForEmphasizeComponents(), and OmniboxView::UpdateTextStyle().
parts()
const url::Parsed& AutocompleteInput::parts () const inline
References parts_.
Referenced by HistoryURLProvider::AsKnownIntranetURL(), HistoryURLProvider::DoAutocomplete(), HistoryQuickProvider::FindMaxMatchScore(), AutocompleteProvider::FixupUserInput(), KeywordProvider::GetSubstitutingTemplateURLForInput(), AutocompleteMatch::GURLToStrippedGURL(), HistoryURLProvider::HistoryMatchToACMatch(), SearchProvider::IsQueryPotentiallyPrivate(), ZeroSuggestProvider::MatchForCurrentText(), NumNonHostComponents(), Parse(), ParseForEmphasizeComponents(), HistoryQuickProvider::QuickMatchToACMatch(), AutocompleteResult::SortAndCull(), bookmarks::TitledUrlMatchToAutocompleteMatch(), UpdateText(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
prefer_keyword()
bool AutocompleteInput::prefer_keyword () const inline
References prefer_keyword_.
Referenced by OmniboxEditModel::AcceptInput(), KeywordProvider::CreateAutocompleteMatch(), SearchProvider::GetKeywordVerbatimRelevance(), AutocompleteProvider::InExplicitExperimentalKeywordMode(), DocumentProvider::IsDocumentProviderAllowed(), set_prefer_keyword(), and ShortcutsProvider::ShortcutToACMatch().
prevent_inline_autocomplete()
bool AutocompleteInput::prevent_inline_autocomplete () const inline
References prevent_inline_autocomplete_.
Referenced by OmniboxEditModel::AcceptInput(), BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::GetKeywordVerbatimRelevance(), SearchProvider::GetVerbatimRelevance(), AutocompleteProvider::IsExplicitlyInKeywordMode(), SearchProvider::NavigationToMatch(), SearchProvider::ScoreHistoryResults(), set_prevent_inline_autocomplete(), AutocompleteMatch::SetAllowedToBeDefault(), ShortcutsProvider::ShortcutToACMatch(), BuiltinProvider::Start(), HistoryURLProvider::Start(), AutocompleteResult::TransferOldMatches(), and AutocompleteMatch::TryRichAutocompletion().
query_tile_id()
const absl::optional<std::string>& AutocompleteInput::query_tile_id () const inline
References query_tile_id_.
Referenced by QueryTileProvider::Start().
scheme()
const std::u16string& AutocompleteInput::scheme () const inline
References scheme_.
Referenced by HistoryURLProvider::AsKnownIntranetURL(), SearchProvider::IsQueryPotentiallyPrivate(), Parse(), ParseForEmphasizeComponents(), and AutocompleteResult::SortAndCull().
set_added_default_scheme_to_typed_url()
void AutocompleteInput::set_added_default_scheme_to_typed_url (bool added_default_scheme_to_typed_url) inline
References added_default_scheme_to_typed_url(), and added_default_scheme_to_typed_url_.
Referenced by OmniboxEditModel::PasteAndGo().
set_allow_exact_keyword_match()
void AutocompleteInput::set_allow_exact_keyword_match (bool allow_exact_keyword_match) inline
References allow_exact_keyword_match(), and allow_exact_keyword_match_.
Referenced by OmniboxEditModel::AcceptInput(), AutocompleteClassifier::Classify(), ZeroSuggestProvider::GetInput(), ZeroSuggestVerbatimMatchProvider::Start(), and OmniboxEditModel::StartAutocomplete().
set_current_title()
void AutocompleteInput::set_current_title (const std::u16string & title) inline
References current_title_.
Referenced by ZeroSuggestProvider::GetInput(), OmniboxEditModel::OpenMatch(), OmniboxEditModel::StartAutocomplete(), and OmniboxEditModel::StartZeroSuggestRequest().
set_current_url()
void AutocompleteInput::set_current_url (const GURL & current_url) inline
References current_url(), and current_url_.
Referenced by ZeroSuggestProvider::GetInput(), OmniboxEditModel::OpenMatch(), OmniboxEditModel::StartAutocomplete(), and OmniboxEditModel::StartZeroSuggestRequest().
set_focus_type()
void AutocompleteInput::set_focus_type (OmniboxFocusType focus_type) inline
References focus_type(), and focus_type_.
Referenced by OmniboxEditModel::AcceptInput(), and OmniboxEditModel::StartZeroSuggestRequest().
set_keyword_mode_entry_method()
void AutocompleteInput::set_keyword_mode_entry_method (metrics::OmniboxEventProto::KeywordModeEntryMethod entry_method) inline
References keyword_mode_entry_method_.
Referenced by OmniboxEditModel::AcceptInput(), and OmniboxEditModel::StartAutocomplete().
set_prefer_keyword()
void AutocompleteInput::set_prefer_keyword (bool prefer_keyword) inline
References prefer_keyword(), and prefer_keyword_.
Referenced by OmniboxEditModel::AcceptInput(), AutocompleteClassifier::Classify(), and OmniboxEditModel::StartAutocomplete().
set_prevent_inline_autocomplete()
void AutocompleteInput::set_prevent_inline_autocomplete (bool prevent_inline_autocomplete) inline
References prevent_inline_autocomplete(), and prevent_inline_autocomplete_.
Referenced by OmniboxEditModel::AcceptInput(), AutocompleteClassifier::Classify(), ZeroSuggestProvider::GetInput(), ZeroSuggestVerbatimMatchProvider::Start(), and OmniboxEditModel::StartAutocomplete().
set_query_tile_id()
void AutocompleteInput::set_query_tile_id (const std::string & tile_id) inline
References query_tile_id_.
set_want_asynchronous_matches()
void AutocompleteInput::set_want_asynchronous_matches (bool want_asynchronous_matches) inline
References want_asynchronous_matches(), and want_asynchronous_matches_.
Referenced by OmniboxEditModel::AcceptInput(), and AutocompleteClassifier::Classify().
ShouldUpgradeToHttps()
bool AutocompleteInput::ShouldUpgradeToHttps (const std::u16string & text, const GURL & url, int https_port_for_testing, GURL * upgraded_url) static
References text().
Referenced by Init(), and OmniboxEditModel::PasteAndGo().
terms_prefixed_by_http_or_https()
const std::vector<std::u16string>& AutocompleteInput::terms_prefixed_by_http_or_https () const inline
References terms_prefixed_by_http_or_https_.
Referenced by AutocompleteMatch::GURLToStrippedGURL().
text()
const std::u16string& AutocompleteInput::text () const inline
References text_.
Referenced by OmniboxEditModel::AcceptInput(), ClipboardProvider::AddCreatedMatchWithTracking(), HistoryURLProvider::AsKnownIntranetURL(), AutocompleteInput(), QueryTileProvider::BuildSuggestion(), SearchProvider::ConvertResultsToAutocompleteMatches(), BaseSearchProvider::CreateOnDeviceSearchSuggestion(), BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::CreateSuggestLoader(), HistoryQuickProvider::DoAutocomplete(), HistoryURLProvider::DoAutocomplete(), SearchProvider::DoHistoryQuery(), KeywordProvider::ExtractKeywordFromInput(), HistoryQuickProvider::FindMaxMatchScore(), HistoryURLProvider::FixupExactSuggestion(), AutocompleteProvider::FixupUserInput(), ShortcutsProvider::GetMatches(), BookmarkProvider::GetMatchesWithBookmarkPaths(), BookmarkProvider::GetMatchingAlgorithm(), KeywordProvider::GetSubstitutingTemplateURLForInput(), HistoryURLProvider::HistoryMatchToACMatch(), AutocompleteProvider::InExplicitExperimentalKeywordMode(), Init(), DocumentProvider::IsDocumentProviderAllowed(), AutocompleteProvider::IsExplicitlyInKeywordMode(), DocumentProvider::IsInputLikelyURL(), SearchProvider::IsQueryPotentiallyPrivate(), SearchProvider::NavigationToMatch(), OmniboxEditModel::OnPopupDataChanged(), Parse(), DocumentProvider::ParseDocumentSearchResults(), ParseForEmphasizeComponents(), SearchSuggestionParser::ParseSuggestResults(), HistoryURLProvider::PromoteOrCreateShorterSuggestion(), HistoryQuickProvider::QuickMatchToACMatch(), OmniboxEditModel::RevertTemporaryTextAndPopup(), DocumentProvider::Run(), SearchProvider::ScoreHistoryResults(), AutocompleteMatch::SetAllowedToBeDefault(), ShortcutsProvider::ShortcutToACMatch(), ShouldUpgradeToHttps(), AutocompleteResult::SortAndCull(), AutocompleteController::Start(), BookmarkProvider::Start(), BuiltinProvider::Start(), HistoryURLProvider::Start(), OnDeviceHeadProvider::Start(), SearchProvider::Start(), ShortcutsProvider::Start(), ZeroSuggestProvider::Start(), SearchProvider::StartOrStopSuggestQuery(), bookmarks::TitledUrlMatchToAutocompleteMatch(), AutocompleteMatch::TryRichAutocompletion(), SearchProvider::UpdateAllOldResults(), AutocompleteController::UpdateAssociatedKeywords(), UpdateText(), VerbatimMatchForInput(), VerbatimMatchForURL(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
type()
metrics::OmniboxInputType AutocompleteInput::type () const inline
References type_.
Referenced by MostVisitedSitesProvider::AllowMostVisitedSitesSuggestions(), QueryTileProvider::AllowQueryTileSuggestions(), ZeroSuggestProvider::AllowZeroSuggestSuggestions(), HistoryURLProvider::AsKnownIntranetURL(), QueryTileProvider::BuildSuggestion(), SearchSuggestionParser::SuggestResult::CalculateRelevance(), SearchProvider::CalculateRelevanceForHistory(), SearchProvider::CalculateRelevanceForVerbatimIgnoringKeywordModeState(), AutocompleteResult::ComputeAlternateNavUrl(), KeywordProvider::CreateAutocompleteMatch(), SearchProvider::CreateSuggestLoader(), HistoryURLProvider::DoAutocomplete(), KeywordProvider::ExtractKeywordFromInput(), HistoryQuickProvider::FindMaxMatchScore(), AutocompleteResult::FindTopMatch(), HistoryURLProvider::FixupExactSuggestion(), AutocompleteProvider::FixupUserInput(), SearchProvider::GetKeywordVerbatimRelevance(), DocumentProvider::IsDocumentProviderAllowed(), DocumentProvider::IsInputLikelyURL(), OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed(), SearchProvider::IsQueryPotentiallyPrivate(), SearchProvider::IsTopMatchSearchWithURLInput(), OmniboxEditModel::OpenMatch(), Parse(), SearchProvider::ScoreHistoryResults(), AutocompleteResult::SortAndCull(), AutocompleteController::Start(), BuiltinProvider::Start(), HistoryQuickProvider::Start(), HistoryURLProvider::Start(), LocalHistoryZeroSuggestProvider::Start(), ShortcutsProvider::Start(), ZeroSuggestVerbatimMatchProvider::Start(), TypeToString(), VerbatimMatchForInput(), and HistoryURLProvider::VisitClassifier::VisitClassifier().
TypeToString()
std::string AutocompleteInput::TypeToString (metrics::OmniboxInputType type) static
References type().
UpdateText()
void AutocompleteInput::UpdateText (const std::u16string & text, size_t cursor_position, const url::Parsed & parts)
References cursor_position(), cursor_position_, parts(), parts_, text(), and text_.
Referenced by KeywordProvider::GetSubstitutingTemplateURLForInput(), ZeroSuggestProvider::MatchForCurrentText(), and HistoryURLProvider::Start().
want_asynchronous_matches()
bool AutocompleteInput::want_asynchronous_matches () const inline
References want_asynchronous_matches_.
Referenced by OmniboxEditModel::AcceptInput(), OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed(), set_want_asynchronous_matches(), AutocompleteController::Start(), DocumentProvider::Start(), HistoryURLProvider::Start(), QueryTileProvider::Start(), and SearchProvider::StartOrStopSuggestQuery().
Friends And Related Function Documentation
AutocompleteProviderTest
friend class AutocompleteProviderTest friend
Member Data Documentation
added_default_scheme_to_typed_url_
bool AutocompleteInput::added_default_scheme_to_typed_url_ private
Referenced by added_default_scheme_to_typed_url(), Init(), and set_added_default_scheme_to_typed_url().
allow_exact_keyword_match_
bool AutocompleteInput::allow_exact_keyword_match_ private
Referenced by allow_exact_keyword_match(), Clear(), and set_allow_exact_keyword_match().
canonicalized_url_
GURL AutocompleteInput::canonicalized_url_ private
Referenced by canonicalized_url(), Clear(), EstimateMemoryUsage(), and Init().
current_page_classification_
metrics::OmniboxEventProto::PageClassification AutocompleteInput::current_page_classification_ private
Referenced by AutocompleteInput(), Clear(), and current_page_classification().
current_title_
std::u16string AutocompleteInput::current_title_ private
Referenced by Clear(), current_title(), EstimateMemoryUsage(), and set_current_title().
current_url_
GURL AutocompleteInput::current_url_ private
Referenced by Clear(), current_url(), EstimateMemoryUsage(), and set_current_url().
cursor_position_
size_t AutocompleteInput::cursor_position_ private
Referenced by AutocompleteInput(), Clear(), cursor_position(), Init(), and UpdateText().
desired_tld_
std::string AutocompleteInput::desired_tld_ private
Referenced by AutocompleteInput(), desired_tld(), EstimateMemoryUsage(), and Init().
focus_type_
OmniboxFocusType AutocompleteInput::focus_type_ = OmniboxFocusType::DEFAULT private
Referenced by Clear(), focus_type(), and set_focus_type().
https_port_for_testing_
int AutocompleteInput::https_port_for_testing_ private
Referenced by AutocompleteInput(), Clear(), and Init().
keyword_mode_entry_method_
metrics::OmniboxEventProto::KeywordModeEntryMethod AutocompleteInput::keyword_mode_entry_method_ private
Referenced by keyword_mode_entry_method(), and set_keyword_mode_entry_method().
parts_
url::Parsed AutocompleteInput::parts_ private
Referenced by Clear(), Init(), parts(), and UpdateText().
prefer_keyword_
bool AutocompleteInput::prefer_keyword_ private
Referenced by Clear(), prefer_keyword(), and set_prefer_keyword().
prevent_inline_autocomplete_
bool AutocompleteInput::prevent_inline_autocomplete_ private
Referenced by Clear(), prevent_inline_autocomplete(), and set_prevent_inline_autocomplete().
query_tile_id_
absl::optional<std::string> AutocompleteInput::query_tile_id_ private
Referenced by Clear(), EstimateMemoryUsage(), query_tile_id(), and set_query_tile_id().
scheme_
std::u16string AutocompleteInput::scheme_ private
Referenced by Clear(), EstimateMemoryUsage(), Init(), and scheme().
should_use_https_as_default_scheme_
bool AutocompleteInput::should_use_https_as_default_scheme_ private
Referenced by AutocompleteInput(), and Init().
terms_prefixed_by_http_or_https_
std::vector<std::u16string> AutocompleteInput::terms_prefixed_by_http_or_https_ private
Referenced by Clear(), EstimateMemoryUsage(), Init(), and terms_prefixed_by_http_or_https().
text_
std::u16string AutocompleteInput::text_ private
Referenced by Clear(), EstimateMemoryUsage(), Init(), text(), and UpdateText().
type_
metrics::OmniboxInputType AutocompleteInput::type_ private
Referenced by Clear(), Init(), and type().
want_asynchronous_matches_
bool AutocompleteInput::want_asynchronous_matches_ private
Referenced by Clear(), set_want_asynchronous_matches(), and want_asynchronous_matches().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_input.h
components/omnibox/browser/autocomplete_input.cc