Chromium Omnibox: AutocompleteProviderDebouncer Class Reference
AutocompleteProviderDebouncer Class Reference
#include <autocomplete_provider_debouncer.h>
Public Member Functions
AutocompleteProviderDebouncer (bool from_last_run, int delay_ms)
~AutocompleteProviderDebouncer ()
void RequestRun (base::OnceCallback< void()> callback)
void CancelRequest ()
Private Member Functions
void Run ()
Private Attributes
bool from_last_run_ = false
int delay_ms_ = 0
base::OneShotTimer timer_
base::TimeTicks time_last_run_
base::OnceCallback< void()> callback_
Constructor & Destructor Documentation
AutocompleteProviderDebouncer()
AutocompleteProviderDebouncer::AutocompleteProviderDebouncer (bool from_last_run, int delay_ms)
Referenced by DocumentProvider::DocumentProvider().
~AutocompleteProviderDebouncer()
AutocompleteProviderDebouncer::~AutocompleteProviderDebouncer () default
Member Function Documentation
CancelRequest()
void AutocompleteProviderDebouncer::CancelRequest ()
References timer_.
RequestRun()
void AutocompleteProviderDebouncer::RequestRun (base::OnceCallback< void()> callback)
References callback_, delay_ms_, from_last_run_, Run(), time_last_run_, and timer_.
Run()
void AutocompleteProviderDebouncer::Run () private
References callback_, and time_last_run_.
Referenced by RequestRun().
Member Data Documentation
callback_
base::OnceCallback<void()> AutocompleteProviderDebouncer::callback_ private
Referenced by RequestRun(), and Run().
delay_ms_
int AutocompleteProviderDebouncer::delay_ms_ = 0 private
Referenced by RequestRun().
from_last_run_
bool AutocompleteProviderDebouncer::from_last_run_ = false private
Referenced by RequestRun().
time_last_run_
base::TimeTicks AutocompleteProviderDebouncer::time_last_run_ private
Referenced by RequestRun(), and Run().
timer_
base::OneShotTimer AutocompleteProviderDebouncer::timer_ private
Referenced by CancelRequest(), and RequestRun().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_provider_debouncer.h
components/omnibox/browser/autocomplete_provider_debouncer.cc