Chromium Omnibox: components/omnibox/browser/autocomplete_match_type.cc File Reference
autocomplete_match_type.cc File Reference
#include "components/omnibox/browser/autocomplete_match_type.h"
#include "base/check.h"
#include "base/cxx17_backports.h"
#include "base/notreached.h"
#include "base/strings/string_number_conversions.h"
#include "base/strings/utf_string_conversions.h"
#include "components/omnibox/browser/autocomplete_match.h"
#include "components/omnibox/browser/omnibox_field_trial.h"
#include "components/omnibox/browser/omnibox_popup_model.h"
#include "components/omnibox/browser/suggestion_answer.h"
#include "components/strings/grit/components_strings.h"
#include "ui/base/l10n/l10n_util.h"
Functions
static int AccessibilityLabelPrefixLength (std::u16string accessibility_label)
std::u16string AddAdditionalMessaging (const std::u16string &format, const std::u16string &replacement, int *label_prefix_length)
std::u16string GetAccessibilityBaseLabel (const AutocompleteMatch &match, const std::u16string &match_text, int *label_prefix_length)
Variables
static constexpr char16_t kAccessibilityLabelPrefixEndSentinel []
Function Documentation
AccessibilityLabelPrefixLength()
static int AccessibilityLabelPrefixLength (std::u16string accessibility_label) static
References kAccessibilityLabelPrefixEndSentinel.
Referenced by AddAdditionalMessaging(), and GetAccessibilityBaseLabel().
AddAdditionalMessaging()
std::u16string AddAdditionalMessaging (const std::u16string & format, const std::u16string & replacement, int * label_prefix_length)
References AccessibilityLabelPrefixLength(), and kAccessibilityLabelPrefixEndSentinel.
Referenced by AutocompleteMatchType::ToAccessibilityLabel().
GetAccessibilityBaseLabel()
std::u16string GetAccessibilityBaseLabel (const AutocompleteMatch & match, const std::u16string & match_text, int * label_prefix_length)
References AccessibilityLabelPrefixLength(), AutocompleteMatch::answer, AutocompleteMatch::contents, AutocompleteMatch::description, AutocompleteMatchType::DOCUMENT_SUGGESTION, kAccessibilityLabelPrefixEndSentinel, AutocompleteMatchType::NUM_TYPES, and AutocompleteMatch::type.
Referenced by AutocompleteMatchType::ToAccessibilityLabel().
Variable Documentation
kAccessibilityLabelPrefixEndSentinel
constexpr char16_t kAccessibilityLabelPrefixEndSentinel[] static constexpr
Initial value:
=
    u"\uFFFC"
Referenced by AccessibilityLabelPrefixLength(), AddAdditionalMessaging(), and GetAccessibilityBaseLabel().