Chromium Omnibox: OmniboxEditController Class Reference
OmniboxEditController Class Reference abstract
#include <omnibox_edit_controller.h>
Public Member Functions
virtual void OnAutocompleteAccept (const GURL &destination_url, TemplateURLRef::PostContent *post_content, WindowOpenDisposition disposition, ui::PageTransition transition, AutocompleteMatchType::Type match_type, base::TimeTicks match_selection_timestamp, bool destination_url_entered_without_scheme, const std::u16string &text, const AutocompleteMatch &match, const AutocompleteMatch &alternative_nav_match)
virtual void OnInputInProgress (bool in_progress)
virtual void OnChanged ()
virtual void OnPopupVisibilityChanged ()
virtual LocationBarModel * GetLocationBarModel ()=0
virtual const LocationBarModel * GetLocationBarModel () const =0
Protected Member Functions
OmniboxEditController ()
virtual ~OmniboxEditController ()
OmniboxEditController (const OmniboxEditController &)=delete
OmniboxEditController & operator= (const OmniboxEditController &)=delete
GURL destination_url () const
TemplateURLRef::PostContent * post_content () const
WindowOpenDisposition disposition () const
ui::PageTransition transition () const
base::TimeTicks match_selection_timestamp () const
bool destination_url_entered_without_scheme () const
Private Attributes
GURL destination_url_
TemplateURLRef::PostContent * post_content_
WindowOpenDisposition disposition_
ui::PageTransition transition_
base::TimeTicks match_selection_timestamp_
bool destination_url_entered_without_scheme_
Constructor & Destructor Documentation
OmniboxEditController() [1/2]
OmniboxEditController::OmniboxEditController () protected
~OmniboxEditController()
OmniboxEditController::~OmniboxEditController () protected virtual
OmniboxEditController() [2/2]
OmniboxEditController::OmniboxEditController (const OmniboxEditController &) protected delete
Member Function Documentation
destination_url()
GURL OmniboxEditController::destination_url () const inline protected
References destination_url_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
destination_url_entered_without_scheme()
bool OmniboxEditController::destination_url_entered_without_scheme () const inline protected
References destination_url_entered_without_scheme_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
disposition()
WindowOpenDisposition OmniboxEditController::disposition () const inline protected
References disposition_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
GetLocationBarModel() [1/2]
virtual const LocationBarModel* OmniboxEditController::GetLocationBarModel () const pure virtual
GetLocationBarModel() [2/2]
virtual LocationBarModel* OmniboxEditController::GetLocationBarModel () pure virtual
Referenced by OmniboxEditModel::AdjustTextForCopy(), OmniboxView::GetIcon(), OmniboxEditModel::GetPageClassification(), OmniboxViewViews::OnMousePressed(), OmniboxEditModel::ResetDisplayTexts(), OmniboxEditModel::ShouldPreventElision(), OmniboxEditModel::Unelide(), and OmniboxViewViews::UpdateSchemeStyle().
match_selection_timestamp()
base::TimeTicks OmniboxEditController::match_selection_timestamp () const inline protected
References match_selection_timestamp_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
OnAutocompleteAccept()
void OmniboxEditController::OnAutocompleteAccept (const GURL & destination_url, TemplateURLRef::PostContent * post_content, WindowOpenDisposition disposition, ui::PageTransition transition, AutocompleteMatchType::Type match_type, base::TimeTicks match_selection_timestamp, bool destination_url_entered_without_scheme, const std::u16string & text, const AutocompleteMatch & match, const AutocompleteMatch & alternative_nav_match) virtual
Reimplemented in ChromeOmniboxEditController.
References destination_url(), destination_url_, destination_url_entered_without_scheme(), destination_url_entered_without_scheme_, disposition(), disposition_, match_selection_timestamp(), match_selection_timestamp_, post_content(), post_content_, transition(), and transition_.
Referenced by OmniboxEditModel::ExecuteAction(), ChromeOmniboxEditController::OnAutocompleteAccept(), and OmniboxEditModel::OpenMatch().
OnChanged()
void OmniboxEditController::OnChanged () virtual
Referenced by OmniboxEditModel::OnChanged().
OnInputInProgress()
void OmniboxEditController::OnInputInProgress (bool in_progress) virtual
Reimplemented in ChromeOmniboxEditController.
Referenced by OmniboxEditModel::NotifyObserversInputInProgress().
OnPopupVisibilityChanged()
void OmniboxEditController::OnPopupVisibilityChanged () virtual
Referenced by OmniboxEditModel::OnPopupResultChanged().
operator=()
OmniboxEditController& OmniboxEditController::operator= (const OmniboxEditController &) protected delete
post_content()
TemplateURLRef::PostContent* OmniboxEditController::post_content () const inline protected
References post_content_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
transition()
ui::PageTransition OmniboxEditController::transition () const inline protected
References transition_.
Referenced by OnAutocompleteAccept(), and ChromeOmniboxEditController::OnAutocompleteAccept().
Member Data Documentation
destination_url_
GURL OmniboxEditController::destination_url_ private
Referenced by destination_url(), and OnAutocompleteAccept().
destination_url_entered_without_scheme_
bool OmniboxEditController::destination_url_entered_without_scheme_ private
Referenced by destination_url_entered_without_scheme(), and OnAutocompleteAccept().
disposition_
WindowOpenDisposition OmniboxEditController::disposition_ private
Referenced by disposition(), and OnAutocompleteAccept().
match_selection_timestamp_
base::TimeTicks OmniboxEditController::match_selection_timestamp_ private
Referenced by match_selection_timestamp(), and OnAutocompleteAccept().
post_content_
TemplateURLRef::PostContent* OmniboxEditController::post_content_ private
Referenced by OnAutocompleteAccept(), and post_content().
transition_
ui::PageTransition OmniboxEditController::transition_ private
Referenced by OnAutocompleteAccept(), and transition().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_edit_controller.h
components/omnibox/browser/omnibox_edit_controller.cc