Chromium Omnibox: OmniboxRowView::HeaderView Class Reference
OmniboxRowView::HeaderView Class Reference
Public Member Functions
METADATA_HEADER (HeaderView)
HeaderView (OmniboxRowView *row_view)
void SetHeader (int suggestion_group_id, const std::u16string &header_text)
gfx::Insets GetInsets () const override
bool OnMousePressed (const ui::MouseEvent &event) override
void OnMouseReleased (const ui::MouseEvent &event) override
void OnMouseEntered (const ui::MouseEvent &event) override
void OnMouseExited (const ui::MouseEvent &event) override
void OnThemeChanged () override
void GetAccessibleNodeData (ui::AXNodeData *node_data) override
void UpdateUI ()
views::Button * header_toggle_button () const
Private Member Functions
void HeaderToggleButtonPressed ()
void OnPrefChanged ()
OmniboxPopupSelection GetHeaderSelection () const
Private Attributes
OmniboxRowView *const row_view_
views::Label * header_label_
views::ToggleImageButton * header_toggle_button_
int suggestion_group_id_ = 0
std::u16string header_text_
bool suggestion_group_hidden_ = false
PrefChangeRegistrar pref_change_registrar_
OmniboxMouseEnterExitHandler mouse_enter_exit_handler_
Constructor & Destructor Documentation
HeaderView()
OmniboxRowView::HeaderView::HeaderView (OmniboxRowView * row_view) inline explicit
References GetHeaderSelection(), OmniboxEditModel::GetPopupSelection(), header_label_, header_toggle_button_, HeaderToggleButtonPressed(), omnibox::kSuggestionGroupVisibility, OmniboxRowView::model_, mouse_enter_exit_handler_, OmniboxMouseEnterExitHandler::ObserveMouseEnterExitOn(), OnPrefChanged(), pref_change_registrar_, OmniboxRowView::pref_service_, and row_view_.
Referenced by OmniboxRowView::ShowHeader().
Member Function Documentation
GetAccessibleNodeData()
void OmniboxRowView::HeaderView::GetAccessibleNodeData (ui::AXNodeData * node_data) inline override
References suggestion_group_hidden_.
GetHeaderSelection()
OmniboxPopupSelection OmniboxRowView::HeaderView::GetHeaderSelection () const inline private
References OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, OmniboxRowView::line_, and row_view_.
Referenced by HeaderToggleButtonPressed(), HeaderView(), OnMouseReleased(), and UpdateUI().
GetInsets()
gfx::Insets OmniboxRowView::HeaderView::GetInsets () const inline override
References OmniboxMatchCellView::kImageBoundsWidth, OmniboxMatchCellView::kMarginLeft, and OmniboxMatchCellView::kMarginRight.
header_toggle_button()
views::Button* OmniboxRowView::HeaderView::header_toggle_button () const inline
References header_toggle_button_.
Referenced by OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility().
HeaderToggleButtonPressed()
void OmniboxRowView::HeaderView::HeaderToggleButtonPressed () inline private
References GetHeaderSelection(), OmniboxRowView::model_, row_view_, and OmniboxEditModel::TriggerPopupSelectionAction().
Referenced by HeaderView().
METADATA_HEADER()
OmniboxRowView::HeaderView::METADATA_HEADER (HeaderView)
OnMouseEntered()
void OmniboxRowView::HeaderView::OnMouseEntered (const ui::MouseEvent & event) inline override
References UpdateUI().
OnMouseExited()
void OmniboxRowView::HeaderView::OnMouseExited (const ui::MouseEvent & event) inline override
References UpdateUI().
OnMousePressed()
bool OmniboxRowView::HeaderView::OnMousePressed (const ui::MouseEvent & event) inline override
OnMouseReleased()
void OmniboxRowView::HeaderView::OnMouseReleased (const ui::MouseEvent & event) inline override
References GetHeaderSelection(), OmniboxRowView::model_, row_view_, and OmniboxEditModel::TriggerPopupSelectionAction().
OnPrefChanged()
void OmniboxRowView::HeaderView::OnPrefChanged () inline private
References header_text_, header_toggle_button_, AutocompleteResult::IsSuggestionGroupIdHidden(), OmniboxRowView::model_, OmniboxRowView::pref_service_, OmniboxEditModel::result(), row_view_, suggestion_group_hidden_, and suggestion_group_id_.
Referenced by HeaderView().
OnThemeChanged()
void OmniboxRowView::HeaderView::OnThemeChanged () inline override
References UpdateUI().
SetHeader()
void OmniboxRowView::HeaderView::SetHeader (int suggestion_group_id, const std::u16string & header_text) inline
References header_label_, header_text_, header_toggle_button_, AutocompleteResult::IsSuggestionGroupIdHidden(), OmniboxRowView::model_, OmniboxRowView::pref_service_, OmniboxEditModel::result(), row_view_, suggestion_group_hidden_, and suggestion_group_id_.
Referenced by OmniboxRowView::ShowHeader().
UpdateUI()
void OmniboxRowView::HeaderView::UpdateUI () inline
References GetHeaderSelection(), GetOmniboxColor(), OmniboxResultView::GetPopupCellBackground(), OmniboxEditModel::GetPopupSelection(), header_label_, header_text_, header_toggle_button_, HOVERED, OmniboxRowView::model_, NORMAL, RESULTS_ICON, RESULTS_TEXT_DIMMED, row_view_, and SELECTED.
Referenced by OnMouseEntered(), OnMouseExited(), OmniboxRowView::OnSelectionStateChanged(), and OnThemeChanged().
Member Data Documentation
header_label_
views::Label* OmniboxRowView::HeaderView::header_label_ private
Referenced by HeaderView(), SetHeader(), and UpdateUI().
header_text_
std::u16string OmniboxRowView::HeaderView::header_text_ private
Referenced by OnPrefChanged(), SetHeader(), and UpdateUI().
header_toggle_button_
views::ToggleImageButton* OmniboxRowView::HeaderView::header_toggle_button_ private
Referenced by header_toggle_button(), HeaderView(), OnPrefChanged(), SetHeader(), and UpdateUI().
mouse_enter_exit_handler_
OmniboxMouseEnterExitHandler OmniboxRowView::HeaderView::mouse_enter_exit_handler_ private
Referenced by HeaderView().
pref_change_registrar_
PrefChangeRegistrar OmniboxRowView::HeaderView::pref_change_registrar_ private
Referenced by HeaderView().
row_view_
OmniboxRowView* const OmniboxRowView::HeaderView::row_view_ private
Referenced by GetHeaderSelection(), HeaderToggleButtonPressed(), HeaderView(), OnMouseReleased(), OnPrefChanged(), SetHeader(), and UpdateUI().
suggestion_group_hidden_
bool OmniboxRowView::HeaderView::suggestion_group_hidden_ = false private
Referenced by GetAccessibleNodeData(), OnPrefChanged(), and SetHeader().
suggestion_group_id_
int OmniboxRowView::HeaderView::suggestion_group_id_ = 0 private
Referenced by OnPrefChanged(), and SetHeader().
The documentation for this class was generated from the following file:
chrome/browser/ui/views/omnibox/omnibox_row_view.cc