Chromium Omnibox: OmniboxResultSelectionIndicator Class Reference
OmniboxResultSelectionIndicator Class Reference
Public Member Functions
METADATA_HEADER (OmniboxResultSelectionIndicator)
OmniboxResultSelectionIndicator (OmniboxResultView *result_view)
void OnPaint (gfx::Canvas *canvas) override
void OnThemeChanged () override
Static Public Attributes
static constexpr int kStrokeThickness = 3
Private Member Functions
SkPath GetPath () const
Private Attributes
SkColor color_
OmniboxResultView *const result_view_
Constructor & Destructor Documentation
OmniboxResultSelectionIndicator()
OmniboxResultSelectionIndicator::OmniboxResultSelectionIndicator (OmniboxResultView * result_view) inline explicit
References kStrokeThickness.
Referenced by OmniboxResultView::OmniboxResultView().
Member Function Documentation
GetPath()
SkPath OmniboxResultSelectionIndicator::GetPath () const inline private
References kStrokeThickness.
Referenced by OnPaint().
METADATA_HEADER()
OmniboxResultSelectionIndicator::METADATA_HEADER (OmniboxResultSelectionIndicator)
OnPaint()
void OmniboxResultSelectionIndicator::OnPaint (gfx::Canvas * canvas) inline override
References color_, and GetPath().
OnThemeChanged()
void OmniboxResultSelectionIndicator::OnThemeChanged () inline override
References color_, and result_view_.
Member Data Documentation
color_
SkColor OmniboxResultSelectionIndicator::color_ private
Referenced by OnPaint(), and OnThemeChanged().
kStrokeThickness
constexpr int OmniboxResultSelectionIndicator::kStrokeThickness = 3 static constexpr
Referenced by GetPath(), and OmniboxResultSelectionIndicator().
result_view_
OmniboxResultView* const OmniboxResultSelectionIndicator::result_view_ private
Referenced by OnThemeChanged().
The documentation for this class was generated from the following file:
chrome/browser/ui/views/omnibox/omnibox_result_view.cc