Chromium Omnibox: OmniboxViewViews Class Reference
OmniboxViewViews Class Reference
#include <omnibox_view_views.h>
Public Member Functions
METADATA_HEADER (OmniboxViewViews)
OmniboxViewViews (OmniboxEditController *controller, std::unique_ptr< OmniboxClient > client, bool popup_window_mode, LocationBarView *location_bar, const gfx::FontList &font_list)
OmniboxViewViews (const OmniboxViewViews &)=delete
OmniboxViewViews & operator= (const OmniboxViewViews &)=delete
~OmniboxViewViews () override
void Init ()
void SaveStateToTab (content::WebContents *tab)
void OnTabChanged (content::WebContents *web_contents)
void ResetTabState (content::WebContents *web_contents)
void InstallPlaceholderText ()
bool GetSelectionAtEnd () const
int GetTextWidth () const
int GetUnelidedTextWidth () const
int GetWidth () const
void EmphasizeURLComponents () override
void Update () override
std::u16string GetText () const override
void SetUserText (const std::u16string &text, bool update_popup) override
void SetWindowTextAndCaretPos (const std::u16string &text, size_t caret_pos, bool update_popup, bool notify_text_changed) override
void SetAdditionalText (const std::u16string &additional_text) override
void EnterKeywordModeForDefaultSearchProvider () override
bool IsSelectAll () const override
void GetSelectionBounds (std::u16string::size_type *start, std::u16string::size_type *end) const override
size_t GetAllSelectionsLength () const override
void SelectAll (bool reversed) override
void RevertAll () override
void SetFocus (bool is_user_initiated) override
bool IsImeComposing () const override
gfx::NativeView GetRelativeWindowForPopup () const override
bool IsImeShowingPopup () const override
gfx::Size GetMinimumSize () const override
bool OnMousePressed (const ui::MouseEvent &event) override
bool OnMouseDragged (const ui::MouseEvent &event) override
void OnMouseReleased (const ui::MouseEvent &event) override
void OnPaint (gfx::Canvas *canvas) override
void ExecuteCommand (int command_id, int event_flags) override
void OnInputMethodChanged () override
void AddedToWidget () override
void RemovedFromWidget () override
std::u16string GetLabelForCommandId (int command_id) const override
bool IsCommandIdEnabled (int command_id) const override
OmniboxPopupContentsView * GetPopupContentsViewForTesting () const
void SetUserText (const std::u16string &text)
virtual void SetUserText (const std::u16string &text, bool update_popup)
Public Member Functions inherited from OmniboxView
virtual ~OmniboxView ()
OmniboxView (const OmniboxView &)=delete
OmniboxView & operator= (const OmniboxView &)=delete
OmniboxEditModel * model ()
const OmniboxEditModel * model () const
virtual void OpenMatch (const AutocompleteMatch &match, WindowOpenDisposition disposition, const GURL &alternate_nav_url, const std::u16string &pasted_text, size_t selected_line, base::TimeTicks match_selection_timestamp)
bool IsEditingOrEmpty () const
ui::ImageModel GetIcon (int dip_size, SkColor color, IconFetchedCallback on_icon_fetched) const
void SetUserText (const std::u16string &text)
virtual void GetSelectionBounds (size_t *start, size_t *end) const =0
virtual void CloseOmniboxPopup ()
virtual bool IsIndicatingQueryRefinement () const
Static Public Attributes
static const int kSmoothingGradientMaxWidth = 15
Protected Member Functions
void UpdateSchemeStyle (const gfx::Range &range) override
void OnThemeChanged () override
bool IsDropCursorForInsertion () const override
virtual void ApplyColor (SkColor color, const gfx::Range &range)
virtual void ApplyStyle (gfx::TextStyle style, bool value, const gfx::Range &range)
Protected Member Functions inherited from OmniboxView
OmniboxView (OmniboxEditController *controller, std::unique_ptr< OmniboxClient > client)
void GetState (State *state)
StateChanges GetStateChanges (const State &before, const State &after)
virtual void TextChanged ()
OmniboxEditController * controller ()
const OmniboxEditController * controller () const
void UpdateTextStyle (const std::u16string &display_text, const bool text_is_url, const AutocompleteSchemeClassifier &classifier)
Private Types
enum class UnelisionGesture { HOME_KEY_PRESSED , MOUSE_RELEASE , OTHER }
enum {
NOT_ACTIVE , CHAR_TYPED , ON_PAINT_CALLED , COMPOSITING_COMMIT ,
COMPOSITING_STARTED
}
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, RendererInitiatedFocusPreservesCursorWhenStartingFocused)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsRevealOnHoverTest, PrivateRegistry)
FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest, EmitAccessibilityEvents)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, CloseOmniboxPopupOnTextDrag)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, FriendlyAccessibleLabel)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, DoNotNavigateOnDrop)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, AyncDropCallback)
void SetTextAndSelectedRanges (const std::u16string &text, const std::vector< gfx::Range > &ranges)
void SetSelectedRanges (const std::vector< gfx::Range > &ranges)
std::u16string GetSelectedText () const
void OnOmniboxPaste ()
bool HandleEarlyTabActions (const ui::KeyEvent &event)
void ClearAccessibilityLabel ()
void SetAccessibilityLabel (const std::u16string &display_text, const AutocompleteMatch &match, bool notify_text_changed) override
bool UnapplySteadyStateElisions (UnelisionGesture gesture)
ui::TextInputType GetPreferredTextInputType () const
void SetCaretPos (size_t caret_pos) override
void UpdatePopup () override
void ApplyCaretVisibility () override
void OnTemporaryTextMaybeChanged (const std::u16string &display_text, const AutocompleteMatch &match, bool save_original_selection, bool notify_text_changed) override
void OnInlineAutocompleteTextMaybeChanged (const std::u16string &display_text, std::vector< gfx::Range > selections, const std::u16string &prefix_autocompletion, const std::u16string &inline_autocompletion) override
void OnInlineAutocompleteTextCleared () override
void OnRevertTemporaryText (const std::u16string &display_text, const AutocompleteMatch &match) override
void OnBeforePossibleChange () override
bool OnAfterPossibleChange (bool allow_keyword_ui_change) override
gfx::NativeView GetNativeView () const override
void ShowVirtualKeyboardIfEnabled () override
void HideImeIfNeeded () override
int GetOmniboxTextLength () const override
void SetEmphasis (bool emphasize, const gfx::Range &range) override
void OnMouseMoved (const ui::MouseEvent &event) override
void OnMouseExited (const ui::MouseEvent &event) override
bool IsItemForCommandIdDynamic (int command_id) const override
void OnGestureEvent (ui::GestureEvent *event) override
void AboutToRequestFocusFromTabTraversal (bool reverse) override
bool SkipDefaultKeyEventProcessing (const ui::KeyEvent &event) override
void GetAccessibleNodeData (ui::AXNodeData *node_data) override
bool HandleAccessibleAction (const ui::AXActionData &action_data) override
void OnFocus () override
void OnBlur () override
std::u16string GetSelectionClipboardText () const override
void DoInsertChar (char16_t ch) override
bool IsTextEditCommandEnabled (ui::TextEditCommand command) const override
void ExecuteTextEditCommand (ui::TextEditCommand command) override
bool ShouldShowPlaceholderText () const override
void ContentsChanged (views::Textfield *sender, const std::u16string &new_contents) override
bool HandleKeyEvent (views::Textfield *sender, const ui::KeyEvent &key_event) override
void OnBeforeUserAction (views::Textfield *sender) override
void OnAfterUserAction (views::Textfield *sender) override
void OnAfterCutOrCopy (ui::ClipboardBuffer clipboard_buffer) override
void OnWriteDragData (ui::OSExchangeData *data) override
void OnGetDragOperationsForTextfield (int *drag_operations) override
void AppendDropFormats (int *formats, std::set< ui::ClipboardFormatType > *format_types) override
ui::mojom::DragOperation OnDrop (const ui::DropTargetEvent &event) override
views::View::DropCallback GetDropCallback (const ui::DropTargetEvent &event) override
void UpdateContextMenu (ui::SimpleMenuModel *menu_contents) override
bool IsCommandIdChecked (int id) const override
void OnCompositingDidCommit (ui::Compositor *compositor) override
void OnCompositingStarted (ui::Compositor *compositor, base::TimeTicks start_time) override
void OnCompositingEnded (ui::Compositor *compositor) override
void OnCompositingShuttingDown (ui::Compositor *compositor) override
void OnTemplateURLServiceChanged () override
void PermitExternalProtocolHandler ()
void PerformDrop (const ui::DropTargetEvent &event, ui::mojom::DragOperation &output_drag_op)
Private Attributes
bool popup_window_mode_
std::unique_ptr< OmniboxPopupContentsView > popup_view_
std::vector< gfx::Range > saved_temporary_selection_
std::vector< gfx::Range > saved_selection_for_focus_change_
State state_before_change_
bool ime_composing_before_change_ = false
LocationBarView * location_bar_view_
bool is_mouse_pressed_ = false
bool filter_drag_events_for_unelision_ = false
bool select_all_on_mouse_release_ = false
bool select_all_on_gesture_tap_ = false
bool show_rejection_ui_if_any_ = false
size_t next_double_click_selection_len_ = 0
size_t next_double_click_selection_offset_ = 0
base::TimeTicks insert_char_time_
enum OmniboxViewViews:: { ... } latency_histogram_state_
std::u16string friendly_suggestion_text_
int friendly_suggestion_text_prefix_length_
base::ScopedObservation< ui::Compositor, ui::CompositorObserver > scoped_compositor_observation_ {this}
base::ScopedObservation< TemplateURLService, TemplateURLServiceObserver > scoped_template_url_service_observation_ {this}
std::unique_ptr< send_tab_to_self::SendTabToSelfSubMenuModel > send_tab_to_self_sub_menu_model_
PrefChangeRegistrar pref_change_registrar_
base::WeakPtrFactory< OmniboxViewViews > weak_factory_ {this}
Additional Inherited Members
Public Types inherited from OmniboxView
using IconFetchedCallback = base::OnceCallback< void(const gfx::Image &icon)>
Static Public Member Functions inherited from OmniboxView
static std::u16string StripJavascriptSchemas (const std::u16string &text)
static std::u16string SanitizeTextForPaste (const std::u16string &text)
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NOT_ACTIVE
CHAR_TYPED
ON_PAINT_CALLED
COMPOSITING_COMMIT
COMPOSITING_STARTED
UnelisionGesture
enum OmniboxViewViews::UnelisionGesture strong private
Enumerator
HOME_KEY_PRESSED
MOUSE_RELEASE
OTHER
Constructor & Destructor Documentation
OmniboxViewViews() [1/2]
OmniboxViewViews::OmniboxViewViews (OmniboxEditController * controller, std::unique_ptr< OmniboxClient > client, bool popup_window_mode, LocationBarView * location_bar, const gfx::FontList & font_list)
References omnibox::kPreventUrlElisionsInOmnibox, location_bar_view_, pref_change_registrar_, and Update().
OmniboxViewViews() [2/2]
OmniboxViewViews::OmniboxViewViews (const OmniboxViewViews &) delete
~OmniboxViewViews()
OmniboxViewViews::~OmniboxViewViews () override
References popup_view_.
Member Function Documentation
AboutToRequestFocusFromTabTraversal()
void OmniboxViewViews::AboutToRequestFocusFromTabTraversal (bool reverse) override private
AddedToWidget()
void OmniboxViewViews::AddedToWidget () override
References scoped_compositor_observation_.
AppendDropFormats()
void OmniboxViewViews::AppendDropFormats (int * formats, std::set< ui::ClipboardFormatType > * format_types) override private
ApplyCaretVisibility()
void OmniboxViewViews::ApplyCaretVisibility () override private virtual
Implements OmniboxView.
References location_bar_view_, and OmniboxView::model().
ApplyColor()
void OmniboxViewViews::ApplyColor (SkColor color, const gfx::Range & range) protected virtual
Referenced by SetEmphasis(), and UpdateSchemeStyle().
ApplyStyle()
void OmniboxViewViews::ApplyStyle (gfx::TextStyle style, bool value, const gfx::Range & range) protected virtual
Referenced by UpdateSchemeStyle().
ClearAccessibilityLabel()
void OmniboxViewViews::ClearAccessibilityLabel () private
References friendly_suggestion_text_, and friendly_suggestion_text_prefix_length_.
Referenced by OnBeforePossibleChange(), and OnBlur().
ContentsChanged()
void OmniboxViewViews::ContentsChanged (views::Textfield * sender, const std::u16string & new_contents) override private
DoInsertChar()
void OmniboxViewViews::DoInsertChar (char16_t ch) override private
References CHAR_TYPED, insert_char_time_, latency_histogram_state_, OmniboxView::model(), NOT_ACTIVE, and OMNIBOX_FOCUS_INVISIBLE.
EmphasizeURLComponents()
void OmniboxViewViews::EmphasizeURLComponents () override virtual
Implements OmniboxView.
References OmniboxEditModel::CurrentTextIsURL(), GetText(), OmniboxView::model(), and OmniboxView::UpdateTextStyle().
Referenced by OnAfterPossibleChange(), OnInlineAutocompleteTextMaybeChanged(), OnThemeChanged(), and Update().
EnterKeywordModeForDefaultSearchProvider()
void OmniboxViewViews::EnterKeywordModeForDefaultSearchProvider () override virtual
Implements OmniboxView.
References OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider(), and OmniboxView::model().
ExecuteCommand()
void OmniboxViewViews::ExecuteCommand (int command_id, int event_flags) override
References ExecuteTextEditCommand(), GetClipboardText(), location_bar_view_, OmniboxView::model(), OnAfterPossibleChange(), OnBeforePossibleChange(), and OmniboxEditModel::PasteAndGo().
ExecuteTextEditCommand()
void OmniboxViewViews::ExecuteTextEditCommand (ui::TextEditCommand command) override private
References IsTextEditCommandEnabled(), OmniboxView::model(), OnOmniboxPaste(), OmniboxEditModel::OnUpOrDownKeyPressed(), and show_rejection_ui_if_any_.
Referenced by ExecuteCommand(), and HandleKeyEvent().
FRIEND_TEST_ALL_PREFIXES() [1/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest , EmitAccessibilityEvents) private
FRIEND_TEST_ALL_PREFIXES() [2/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsRevealOnHoverTest , PrivateRegistry) private
FRIEND_TEST_ALL_PREFIXES() [3/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , AyncDropCallback) private
FRIEND_TEST_ALL_PREFIXES() [4/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , CloseOmniboxPopupOnTextDrag) private
FRIEND_TEST_ALL_PREFIXES() [5/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , DoNotNavigateOnDrop) private
FRIEND_TEST_ALL_PREFIXES() [6/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , FriendlyAccessibleLabel) private
FRIEND_TEST_ALL_PREFIXES() [7/7]
OmniboxViewViews::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , RendererInitiatedFocusPreservesCursorWhenStartingFocused) private
GetAccessibleNodeData()
void OmniboxViewViews::GetAccessibleNodeData (ui::AXNodeData * node_data) override private
References friendly_suggestion_text_, friendly_suggestion_text_prefix_length_, GetSelectionBounds(), GetText(), OmniboxView::model(), popup_view_, popup_window_mode_, and saved_selection_for_focus_change_.
GetAllSelectionsLength()
size_t OmniboxViewViews::GetAllSelectionsLength () const override virtual
Implements OmniboxView.
GetDropCallback()
views::View::DropCallback OmniboxViewViews::GetDropCallback (const ui::DropTargetEvent & event) override private
References PerformDrop(), and weak_factory_.
GetLabelForCommandId()
std::u16string OmniboxViewViews::GetLabelForCommandId (int command_id) const override
References OmniboxEditModel::ClassifyString(), AutocompleteMatch::destination_url, GetClipboardText(), AutocompleteMatch::IsSearchType(), OmniboxView::model(), and AutocompleteMatch::type.
GetMinimumSize()
gfx::Size OmniboxViewViews::GetMinimumSize () const override
GetNativeView()
gfx::NativeView OmniboxViewViews::GetNativeView () const override private virtual
Implements OmniboxView.
GetOmniboxTextLength()
int OmniboxViewViews::GetOmniboxTextLength () const override private virtual
Implements OmniboxView.
References GetText().
GetPopupContentsViewForTesting()
OmniboxPopupContentsView* OmniboxViewViews::GetPopupContentsViewForTesting () const inline
References popup_view_.
GetPreferredTextInputType()
ui::TextInputType OmniboxViewViews::GetPreferredTextInputType () const private
References location_bar_view_.
Referenced by Init(), and OnInputMethodChanged().
GetRelativeWindowForPopup()
gfx::NativeView OmniboxViewViews::GetRelativeWindowForPopup () const override virtual
Implements OmniboxView.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
GetSelectedText()
std::u16string OmniboxViewViews::GetSelectedText () const private
Referenced by IsSelectAll(), OnGetDragOperationsForTextfield(), OnMousePressed(), OnWriteDragData(), and UnapplySteadyStateElisions().
GetSelectionAtEnd()
bool OmniboxViewViews::GetSelectionAtEnd () const
References GetText().
Referenced by UpdatePopup().
GetSelectionBounds()
void OmniboxViewViews::GetSelectionBounds (std::u16string::size_type * start, std::u16string::size_type * end) const override
Referenced by GetAccessibleNodeData(), HandleKeyEvent(), and UnapplySteadyStateElisions().
GetSelectionClipboardText()
std::u16string OmniboxViewViews::GetSelectionClipboardText () const override private
References OmniboxView::SanitizeTextForPaste().
GetText()
std::u16string OmniboxViewViews::GetText () const override virtual
Implements OmniboxView.
Referenced by EmphasizeURLComponents(), GetAccessibleNodeData(), GetOmniboxTextLength(), GetSelectionAtEnd(), IsSelectAll(), OnBlur(), OnGestureEvent(), OnInlineAutocompleteTextMaybeChanged(), OnMousePressed(), and UnapplySteadyStateElisions().
GetTextWidth()
int OmniboxViewViews::GetTextWidth () const
Referenced by GetUnelidedTextWidth().
GetUnelidedTextWidth()
int OmniboxViewViews::GetUnelidedTextWidth () const
References GetTextWidth().
GetWidth()
int OmniboxViewViews::GetWidth () const
References location_bar_view_.
HandleAccessibleAction()
bool OmniboxViewViews::HandleAccessibleAction (const ui::AXActionData & action_data) override private
References friendly_suggestion_text_prefix_length_, OmniboxView::model(), saved_selection_for_focus_change_, OmniboxEditModel::SetInputInProgress(), SetSelectedRanges(), SetUserText(), and OmniboxView::TextChanged().
HandleEarlyTabActions()
bool OmniboxViewViews::HandleEarlyTabActions (const ui::KeyEvent & event) private
References OmniboxPopupModel::kBackward, OmniboxPopupModel::kForward, OmniboxPopupModel::kStateOrLine, OmniboxView::model(), OmniboxEditModel::popup_model(), and OmniboxPopupModel::StepSelection().
Referenced by HandleKeyEvent().
HandleKeyEvent()
bool OmniboxViewViews::HandleKeyEvent (views::Textfield * sender, const ui::KeyEvent & key_event) override private
References OmniboxEditModel::AcceptInput(), OmniboxEditModel::ClearKeyword(), ExecuteTextEditCommand(), GetSelectionBounds(), HandleEarlyTabActions(), HOME_KEY_PRESSED, is_mouse_pressed_, OmniboxPopupModel::Selection::IsButtonFocused(), IsTextEditCommandEnabled(), OmniboxPopupModel::kAllLines, OmniboxPopupModel::kBackward, OmniboxPopupModel::kForward, OmniboxView::model(), OmniboxEditModel::OnControlKeyChanged(), OmniboxEditModel::OnEscapeKeyPressed(), PermitExternalProtocolHandler(), OmniboxEditModel::popup_model(), select_all_on_mouse_release_, SelectAll(), OmniboxPopupModel::selection(), SetCaretPos(), show_rejection_ui_if_any_, OmniboxPopupModel::StepSelection(), OmniboxView::TextChanged(), OmniboxPopupModel::TriggerSelectionAction(), OmniboxPopupModel::TryDeletingLine(), and UnapplySteadyStateElisions().
HideImeIfNeeded()
void OmniboxViewViews::HideImeIfNeeded () override private virtual
Reimplemented from OmniboxView.
Init()
void OmniboxViewViews::Init ()
References GetPreferredTextInputType(), InstallPlaceholderText(), location_bar_view_, OmniboxView::model(), OmniboxPopupContentsView::OmniboxPopupContentsView(), popup_view_, popup_window_mode_, and scoped_template_url_service_observation_.
InstallPlaceholderText()
void OmniboxViewViews::InstallPlaceholderText ()
References OmniboxEditModel::client(), OmniboxClient::GetTemplateURLService(), and OmniboxView::model().
Referenced by Init(), and OnTemplateURLServiceChanged().
IsCommandIdChecked()
bool OmniboxViewViews::IsCommandIdChecked (int id) const override private
References omnibox::kPreventUrlElisionsInOmnibox, and location_bar_view_.
IsCommandIdEnabled()
bool OmniboxViewViews::IsCommandIdEnabled (int command_id) const override
References OmniboxEditModel::CanPasteAndGo(), GetClipboardText(), location_bar_view_, and OmniboxView::model().
IsDropCursorForInsertion()
bool OmniboxViewViews::IsDropCursorForInsertion () const override protected
IsImeComposing()
bool OmniboxViewViews::IsImeComposing () const override virtual
Implements OmniboxView.
IsImeShowingPopup()
bool OmniboxViewViews::IsImeShowingPopup () const override virtual
Reimplemented from OmniboxView.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
IsItemForCommandIdDynamic()
bool OmniboxViewViews::IsItemForCommandIdDynamic (int command_id) const override private
IsSelectAll()
bool OmniboxViewViews::IsSelectAll () const override virtual
Implements OmniboxView.
References GetSelectedText(), and GetText().
Referenced by OnAfterCutOrCopy(), OnMousePressed(), OnWriteDragData(), and UnapplySteadyStateElisions().
IsTextEditCommandEnabled()
bool OmniboxViewViews::IsTextEditCommandEnabled (ui::TextEditCommand command) const override private
References GetClipboardText(), and show_rejection_ui_if_any_.
Referenced by ExecuteTextEditCommand(), and HandleKeyEvent().
METADATA_HEADER()
OmniboxViewViews::METADATA_HEADER (OmniboxViewViews)
OnAfterCutOrCopy()
void OmniboxViewViews::OnAfterCutOrCopy (ui::ClipboardBuffer clipboard_buffer) override private
References OmniboxEditModel::AdjustTextForCopy(), IsSelectAll(), OmniboxEditModel::kCutOrCopyAllTextHistogram, location_bar_view_, and OmniboxView::model().
OnAfterPossibleChange()
bool OmniboxViewViews::OnAfterPossibleChange (bool allow_keyword_ui_change) override private virtual
Implements OmniboxView.
References EmphasizeURLComponents(), OmniboxView::GetState(), OmniboxView::GetStateChanges(), ime_composing_before_change_, is_mouse_pressed_, OmniboxView::StateChanges::keyword_differs, OmniboxView::model(), OmniboxEditModel::OnAfterPossibleChange(), OTHER, OmniboxView::StateChanges::selection_differs, state_before_change_, OmniboxView::StateChanges::text_differs, OmniboxView::TextChanged(), and UnapplySteadyStateElisions().
Referenced by ExecuteCommand(), OnAfterUserAction(), and OnOmniboxPaste().
OnAfterUserAction()
void OmniboxViewViews::OnAfterUserAction (views::Textfield * sender) override private
References OnAfterPossibleChange().
OnBeforePossibleChange()
void OmniboxViewViews::OnBeforePossibleChange () override private virtual
Implements OmniboxView.
References ClearAccessibilityLabel(), OmniboxView::GetState(), ime_composing_before_change_, and state_before_change_.
Referenced by ExecuteCommand(), OnBeforeUserAction(), and OnOmniboxPaste().
OnBeforeUserAction()
void OmniboxViewViews::OnBeforeUserAction (views::Textfield * sender) override private
References OnBeforePossibleChange().
OnBlur()
void OmniboxViewViews::OnBlur () override private
References ClearAccessibilityLabel(), OmniboxView::CloseOmniboxPopup(), GetText(), OmniboxPopupModel::IsOpen(), location_bar_view_, OmniboxView::model(), OmniboxEditModel::OnKillFocus(), OmniboxEditModel::OnWillKillFocus(), OmniboxEditModel::popup_model(), RevertAll(), and saved_selection_for_focus_change_.
OnCompositingDidCommit()
void OmniboxViewViews::OnCompositingDidCommit (ui::Compositor * compositor) override private
References COMPOSITING_COMMIT, insert_char_time_, latency_histogram_state_, NOT_ACTIVE, and ON_PAINT_CALLED.
OnCompositingEnded()
void OmniboxViewViews::OnCompositingEnded (ui::Compositor * compositor) override private
References COMPOSITING_STARTED, insert_char_time_, latency_histogram_state_, and NOT_ACTIVE.
OnCompositingShuttingDown()
void OmniboxViewViews::OnCompositingShuttingDown (ui::Compositor * compositor) override private
References scoped_compositor_observation_.
OnCompositingStarted()
void OmniboxViewViews::OnCompositingStarted (ui::Compositor * compositor, base::TimeTicks start_time) override private
References COMPOSITING_COMMIT, COMPOSITING_STARTED, and latency_histogram_state_.
OnDrop()
DragOperation OmniboxViewViews::OnDrop (const ui::DropTargetEvent & event) override private
References PerformDrop().
OnFocus()
void OmniboxViewViews::OnFocus () override private
References location_bar_view_, OmniboxView::model(), OmniboxEditModel::OnSetFocus(), OmniboxEditModel::ResetDisplayTexts(), saved_selection_for_focus_change_, and SetSelectedRanges().
OnGestureEvent()
void OmniboxViewViews::OnGestureEvent (ui::GestureEvent * event) override private
References GetText(), OmniboxView::model(), PermitExternalProtocolHandler(), saved_selection_for_focus_change_, select_all_on_gesture_tap_, SelectAll(), and OmniboxEditModel::StartZeroSuggestRequest().
OnGetDragOperationsForTextfield()
void OmniboxViewViews::OnGetDragOperationsForTextfield (int * drag_operations) override private
References OmniboxEditModel::AdjustTextForCopy(), GetSelectedText(), and OmniboxView::model().
OnInlineAutocompleteTextCleared()
void OmniboxViewViews::OnInlineAutocompleteTextCleared () override private virtual
Implements OmniboxView.
References location_bar_view_.
OnInlineAutocompleteTextMaybeChanged()
void OmniboxViewViews::OnInlineAutocompleteTextMaybeChanged (const std::u16string & display_text, std::vector< gfx::Range > selections, const std::u16string & prefix_autocompletion, const std::u16string & inline_autocompletion) override private virtual
Implements OmniboxView.
References EmphasizeURLComponents(), GetText(), location_bar_view_, and SetTextAndSelectedRanges().
OnInputMethodChanged()
void OmniboxViewViews::OnInputMethodChanged () override
References GetPreferredTextInputType().
OnMouseDragged()
bool OmniboxViewViews::OnMouseDragged (const ui::MouseEvent & event) override
References OmniboxView::CloseOmniboxPopup(), filter_drag_events_for_unelision_, and select_all_on_mouse_release_.
OnMouseExited()
void OmniboxViewViews::OnMouseExited (const ui::MouseEvent & event) override private
References location_bar_view_.
OnMouseMoved()
void OmniboxViewViews::OnMouseMoved (const ui::MouseEvent & event) override private
References location_bar_view_.
OnMousePressed()
bool OmniboxViewViews::OnMousePressed (const ui::MouseEvent & event) override
References OmniboxView::controller(), filter_drag_events_for_unelision_, OmniboxEditModel::focus_state(), LocationBarModel::GetFormattedFullURL(), OmniboxEditController::GetLocationBarModel(), GetSelectedText(), GetText(), is_mouse_pressed_, IsSelectAll(), OmniboxPopupModel::KEYWORD_MODE, OmniboxView::model(), next_double_click_selection_len_, next_double_click_selection_offset_, OmniboxPopupModel::NORMAL, OMNIBOX_FOCUS_INVISIBLE, OTHER, PermitExternalProtocolHandler(), OmniboxEditModel::popup_model(), saved_selection_for_focus_change_, select_all_on_mouse_release_, SelectAll(), OmniboxEditModel::SetCaretVisibility(), OmniboxPopupModel::SetSelectedLineState(), OmniboxEditModel::StartZeroSuggestRequest(), OmniboxView::TextChanged(), and UnapplySteadyStateElisions().
OnMouseReleased()
void OmniboxViewViews::OnMouseReleased (const ui::MouseEvent & event) override
References filter_drag_events_for_unelision_, is_mouse_pressed_, MOUSE_RELEASE, PermitExternalProtocolHandler(), select_all_on_mouse_release_, SelectAll(), OmniboxView::TextChanged(), and UnapplySteadyStateElisions().
OnOmniboxPaste()
void OmniboxViewViews::OnOmniboxPaste () private
References GetClipboardText(), OmniboxView::model(), OMNIBOX_FOCUS_INVISIBLE, OnAfterPossibleChange(), OnBeforePossibleChange(), OmniboxEditModel::OnPaste(), state_before_change_, and OmniboxView::State::text.
Referenced by ExecuteTextEditCommand().
OnPaint()
void OmniboxViewViews::OnPaint (gfx::Canvas * canvas) override
References CHAR_TYPED, insert_char_time_, latency_histogram_state_, and ON_PAINT_CALLED.
OnRevertTemporaryText()
void OmniboxViewViews::OnRevertTemporaryText (const std::u16string & display_text, const AutocompleteMatch & match) override private virtual
Implements OmniboxView.
References saved_temporary_selection_, SetAccessibilityLabel(), and SetSelectedRanges().
OnTabChanged()
void OmniboxViewViews::OnTabChanged (content::WebContents * web_contents)
References OmniboxView::model(), OmniboxEditModel::RestoreState(), saved_selection_for_focus_change_, SelectAll(), and SetSelectedRanges().
OnTemplateURLServiceChanged()
void OmniboxViewViews::OnTemplateURLServiceChanged () override private
References InstallPlaceholderText().
OnTemporaryTextMaybeChanged()
void OmniboxViewViews::OnTemporaryTextMaybeChanged (const std::u16string & display_text, const AutocompleteMatch & match, bool save_original_selection, bool notify_text_changed) override private virtual
Implements OmniboxView.
References saved_temporary_selection_, SetAccessibilityLabel(), and SetWindowTextAndCaretPos().
OnThemeChanged()
void OmniboxViewViews::OnThemeChanged () override protected
References EmphasizeURLComponents(), GetOmniboxColor(), and LOCATION_BAR_TEXT_DIMMED.
OnWriteDragData()
void OmniboxViewViews::OnWriteDragData (ui::OSExchangeData * data) override private
References OmniboxEditModel::AdjustTextForCopy(), OmniboxEditModel::GetDataForURLExport(), GetSelectedText(), IsSelectAll(), and OmniboxView::model().
operator=()
OmniboxViewViews& OmniboxViewViews::operator= (const OmniboxViewViews &) delete
PerformDrop()
void OmniboxViewViews::PerformDrop (const ui::DropTargetEvent & event, ui::mojom::DragOperation & output_drag_op) private
References SelectAll(), SetUserText(), and OmniboxView::StripJavascriptSchemas().
Referenced by GetDropCallback(), and OnDrop().
PermitExternalProtocolHandler()
void OmniboxViewViews::PermitExternalProtocolHandler () private
Referenced by HandleKeyEvent(), OnGestureEvent(), OnMousePressed(), and OnMouseReleased().
RemovedFromWidget()
void OmniboxViewViews::RemovedFromWidget () override
References scoped_compositor_observation_.
ResetTabState()
void OmniboxViewViews::ResetTabState (content::WebContents * web_contents)
RevertAll()
void OmniboxViewViews::RevertAll () override virtual
Reimplemented from OmniboxView.
References OmniboxView::RevertAll(), and saved_selection_for_focus_change_.
Referenced by OnBlur(), and Update().
SaveStateToTab()
void OmniboxViewViews::SaveStateToTab (content::WebContents * tab)
References OmniboxEditModel::GetStateForTabSwitch(), OmniboxView::model(), and saved_selection_for_focus_change_.
SelectAll()
void OmniboxViewViews::SelectAll (bool reversed) override virtual
Implements OmniboxView.
Referenced by HandleKeyEvent(), OnGestureEvent(), OnMousePressed(), OnMouseReleased(), OnTabChanged(), PerformDrop(), SetFocus(), and Update().
SetAccessibilityLabel()
void OmniboxViewViews::SetAccessibilityLabel (const std::u16string & display_text, const AutocompleteMatch & match, bool notify_text_changed) override private virtual
Reimplemented from OmniboxView.
References friendly_suggestion_text_, friendly_suggestion_text_prefix_length_, OmniboxPopupModel::GetAccessibilityLabelForCurrentSelection(), OmniboxPopupModel::kNoMatch, OmniboxView::model(), OmniboxEditModel::popup_model(), AutocompleteMatchType::ToAccessibilityLabel(), and weak_factory_.
Referenced by OnRevertTemporaryText(), and OnTemporaryTextMaybeChanged().
SetAdditionalText()
void OmniboxViewViews::SetAdditionalText (const std::u16string & additional_text) override virtual
Implements OmniboxView.
References location_bar_view_.
Referenced by SetTextAndSelectedRanges().
SetCaretPos()
void OmniboxViewViews::SetCaretPos (size_t caret_pos) override private virtual
Implements OmniboxView.
Referenced by HandleKeyEvent().
SetEmphasis()
void OmniboxViewViews::SetEmphasis (bool emphasize, const gfx::Range & range) override private virtual
Implements OmniboxView.
References ApplyColor(), GetOmniboxColor(), LOCATION_BAR_TEXT_DEFAULT, and LOCATION_BAR_TEXT_DIMMED.
SetFocus()
void OmniboxViewViews::SetFocus (bool is_user_initiated) override virtual
Implements OmniboxView.
References OmniboxEditModel::ClearKeyword(), OmniboxEditModel::ConsumeCtrlKey(), location_bar_view_, OmniboxView::model(), SelectAll(), OmniboxEditModel::SetCaretVisibility(), OmniboxEditModel::StartZeroSuggestRequest(), and OmniboxEditModel::Unelide().
SetSelectedRanges()
void OmniboxViewViews::SetSelectedRanges (const std::vector< gfx::Range > & ranges) private
Referenced by HandleAccessibleAction(), OnFocus(), OnRevertTemporaryText(), OnTabChanged(), and SetTextAndSelectedRanges().
SetTextAndSelectedRanges()
void OmniboxViewViews::SetTextAndSelectedRanges (const std::u16string & text, const std::vector< gfx::Range > & ranges) private
References SetAdditionalText(), and SetSelectedRanges().
Referenced by OnInlineAutocompleteTextMaybeChanged(), and SetWindowTextAndCaretPos().
SetUserText() [1/3]
void OmniboxView::SetUserText
Referenced by HandleAccessibleAction(), and PerformDrop().
SetUserText() [2/3]
void OmniboxView::SetUserText
SetUserText() [3/3]
void OmniboxViewViews::SetUserText (const std::u16string & text, bool update_popup) override virtual
Reimplemented from OmniboxView.
References saved_selection_for_focus_change_, and OmniboxView::SetUserText().
SetWindowTextAndCaretPos()
void OmniboxViewViews::SetWindowTextAndCaretPos (const std::u16string & text, size_t caret_pos, bool update_popup, bool notify_text_changed) override virtual
Implements OmniboxView.
References SetTextAndSelectedRanges(), OmniboxView::TextChanged(), and UpdatePopup().
Referenced by OnTemporaryTextMaybeChanged().
ShouldShowPlaceholderText()
bool OmniboxViewViews::ShouldShowPlaceholderText () const override private
References OmniboxEditModel::is_caret_visible(), OmniboxEditModel::is_keyword_selected(), and OmniboxView::model().
ShowVirtualKeyboardIfEnabled()
void OmniboxViewViews::ShowVirtualKeyboardIfEnabled () override private virtual
Reimplemented from OmniboxView.
SkipDefaultKeyEventProcessing()
bool OmniboxViewViews::SkipDefaultKeyEventProcessing (const ui::KeyEvent & event) override private
References OmniboxView::model(), and OmniboxEditModel::WillHandleEscapeKey().
UnapplySteadyStateElisions()
bool OmniboxViewViews::UnapplySteadyStateElisions (UnelisionGesture gesture) private
References OmniboxEditModel::ClassifyString(), GetSelectedText(), GetSelectionBounds(), GetText(), HOME_KEY_PRESSED, AutocompleteMatch::IsSearchType(), IsSelectAll(), OmniboxView::model(), MOUSE_RELEASE, and AutocompleteMatch::type.
Referenced by HandleKeyEvent(), OnAfterPossibleChange(), OnMousePressed(), and OnMouseReleased().
Update()
void OmniboxViewViews::Update () override virtual
Implements OmniboxView.
References EmphasizeURLComponents(), OmniboxView::model(), RevertAll(), and SelectAll().
Referenced by OmniboxViewViews().
UpdateContextMenu()
void OmniboxViewViews::UpdateContextMenu (ui::SimpleMenuModel * menu_contents) override private
References omnibox::kPreventUrlElisionsInOmnibox, location_bar_view_, and send_tab_to_self_sub_menu_model_.
UpdatePopup()
void OmniboxViewViews::UpdatePopup () override private virtual
Implements OmniboxView.
References GetSelectionAtEnd(), OmniboxView::model(), and OmniboxEditModel::UpdateInput().
Referenced by SetWindowTextAndCaretPos().
UpdateSchemeStyle()
void OmniboxViewViews::UpdateSchemeStyle (const gfx::Range & range) override protected virtual
Implements OmniboxView.
References ApplyColor(), ApplyStyle(), OmniboxView::controller(), OmniboxEditController::GetLocationBarModel(), location_bar_view_, and OmniboxView::model().
Member Data Documentation
filter_drag_events_for_unelision_
bool OmniboxViewViews::filter_drag_events_for_unelision_ = false private
Referenced by OnMouseDragged(), OnMousePressed(), and OnMouseReleased().
friendly_suggestion_text_
std::u16string OmniboxViewViews::friendly_suggestion_text_ private
Referenced by ClearAccessibilityLabel(), GetAccessibleNodeData(), and SetAccessibilityLabel().
friendly_suggestion_text_prefix_length_
int OmniboxViewViews::friendly_suggestion_text_prefix_length_ private
Referenced by ClearAccessibilityLabel(), GetAccessibleNodeData(), HandleAccessibleAction(), and SetAccessibilityLabel().
ime_composing_before_change_
bool OmniboxViewViews::ime_composing_before_change_ = false private
Referenced by OnAfterPossibleChange(), and OnBeforePossibleChange().
insert_char_time_
base::TimeTicks OmniboxViewViews::insert_char_time_ private
Referenced by DoInsertChar(), OnCompositingDidCommit(), OnCompositingEnded(), and OnPaint().
is_mouse_pressed_
bool OmniboxViewViews::is_mouse_pressed_ = false private
Referenced by HandleKeyEvent(), OnAfterPossibleChange(), OnMousePressed(), and OnMouseReleased().
kSmoothingGradientMaxWidth
const int OmniboxViewViews::kSmoothingGradientMaxWidth = 15 static
enum { ... } OmniboxViewViews::latency_histogram_state_
Referenced by DoInsertChar(), OnCompositingDidCommit(), OnCompositingEnded(), OnCompositingStarted(), and OnPaint().
location_bar_view_
LocationBarView* OmniboxViewViews::location_bar_view_ private
Referenced by ApplyCaretVisibility(), ExecuteCommand(), GetPreferredTextInputType(), GetWidth(), Init(), IsCommandIdChecked(), IsCommandIdEnabled(), OmniboxViewViews(), OnAfterCutOrCopy(), OnBlur(), OnFocus(), OnInlineAutocompleteTextCleared(), OnInlineAutocompleteTextMaybeChanged(), OnMouseExited(), OnMouseMoved(), SetAdditionalText(), SetFocus(), UpdateContextMenu(), and UpdateSchemeStyle().
next_double_click_selection_len_
size_t OmniboxViewViews::next_double_click_selection_len_ = 0 private
Referenced by OnMousePressed().
next_double_click_selection_offset_
size_t OmniboxViewViews::next_double_click_selection_offset_ = 0 private
Referenced by OnMousePressed().
popup_view_
std::unique_ptr<OmniboxPopupContentsView> OmniboxViewViews::popup_view_ private
Referenced by GetAccessibleNodeData(), GetPopupContentsViewForTesting(), Init(), and ~OmniboxViewViews().
popup_window_mode_
bool OmniboxViewViews::popup_window_mode_ private
Referenced by GetAccessibleNodeData(), and Init().
pref_change_registrar_
PrefChangeRegistrar OmniboxViewViews::pref_change_registrar_ private
Referenced by OmniboxViewViews().
saved_selection_for_focus_change_
std::vector<gfx::Range> OmniboxViewViews::saved_selection_for_focus_change_ private
Referenced by GetAccessibleNodeData(), HandleAccessibleAction(), OnBlur(), OnFocus(), OnGestureEvent(), OnMousePressed(), OnTabChanged(), RevertAll(), SaveStateToTab(), and SetUserText().
saved_temporary_selection_
std::vector<gfx::Range> OmniboxViewViews::saved_temporary_selection_ private
Referenced by OnRevertTemporaryText(), and OnTemporaryTextMaybeChanged().
scoped_compositor_observation_
base::ScopedObservation<ui::Compositor, ui::CompositorObserver> OmniboxViewViews::scoped_compositor_observation_ {this} private
Referenced by AddedToWidget(), OnCompositingShuttingDown(), and RemovedFromWidget().
scoped_template_url_service_observation_
base::ScopedObservation<TemplateURLService, TemplateURLServiceObserver> OmniboxViewViews::scoped_template_url_service_observation_ {this} private
Referenced by Init().
select_all_on_gesture_tap_
bool OmniboxViewViews::select_all_on_gesture_tap_ = false private
Referenced by OnGestureEvent().
select_all_on_mouse_release_
bool OmniboxViewViews::select_all_on_mouse_release_ = false private
Referenced by HandleKeyEvent(), OnMouseDragged(), OnMousePressed(), and OnMouseReleased().
send_tab_to_self_sub_menu_model_
std::unique_ptr<send_tab_to_self::SendTabToSelfSubMenuModel> OmniboxViewViews::send_tab_to_self_sub_menu_model_ private
Referenced by UpdateContextMenu().
show_rejection_ui_if_any_
bool OmniboxViewViews::show_rejection_ui_if_any_ = false private
Referenced by ExecuteTextEditCommand(), HandleKeyEvent(), and IsTextEditCommandEnabled().
state_before_change_
State OmniboxViewViews::state_before_change_ private
Referenced by OnAfterPossibleChange(), OnBeforePossibleChange(), and OnOmniboxPaste().
weak_factory_
base::WeakPtrFactory<OmniboxViewViews> OmniboxViewViews::weak_factory_ {this} private
Referenced by GetDropCallback(), and SetAccessibilityLabel().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_view_views.h
chrome/browser/ui/views/omnibox/omnibox_view_views.cc