Chromium Omnibox: VoiceSuggestProvider Class Reference
VoiceSuggestProvider Class Reference
#include <voice_suggest_provider.h>
Public Member Functions
VoiceSuggestProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
void AddVoiceSuggestion (std::u16string match_text, float match_score)
void ClearCache ()
Public Member Functions inherited from BaseSearchProvider
BaseSearchProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
BaseSearchProvider (const BaseSearchProvider &)=delete
BaseSearchProvider & operator= (const BaseSearchProvider &)=delete
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
bool field_trial_triggered_in_session () const
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Member Functions
~VoiceSuggestProvider () override
const TemplateURL * GetTemplateURL (bool is_keyword) const override
const AutocompleteInput GetInput (bool is_keyword) const override
bool ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult &result) const override
void RecordDeletionResult (bool success) override
Private Attributes
std::vector< std::pair< float, std::u16string > > voice_matches_
const AutocompleteInput * autocomplete_input_ {}
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from BaseSearchProvider
static bool ShouldPrefetch (const AutocompleteMatch &match)
static AutocompleteMatch CreateSearchSuggestion (const std::u16string &suggestion, AutocompleteMatchType::Type type, bool from_keyword_provider, const TemplateURL *template_url, const SearchTermsData &search_terms_data)
static AutocompleteMatch CreateSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const bool in_keyword_mode, const SearchSuggestionParser::SuggestResult &suggestion, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion, bool append_extra_query_params_from_command_line)
static AutocompleteMatch CreateOnDeviceSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const std::u16string &suggestion, int relevance, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion)
static void AppendSuggestClientToAdditionalQueryParams (const TemplateURL *template_url, const SearchTermsData &search_terms_data, metrics::OmniboxEventProto::PageClassification page_classification, TemplateURLRef::SearchTermsArgs *search_terms_args)
static bool IsNTPPage (metrics::OmniboxEventProto::PageClassification classification)
static bool IsSearchResultsPage (metrics::OmniboxEventProto::PageClassification classification)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from BaseSearchProvider
typedef std::pair< std::u16string, std::string > MatchKey
typedef std::map< MatchKey, AutocompleteMatch > MatchMap
typedef std::vector< std::unique_ptr< SuggestionDeletionHandler > > SuggestionDeletionHandlers
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from BaseSearchProvider
~BaseSearchProvider () override
void SetDeletionURL (const std::string &deletion_url, AutocompleteMatch *match)
void AddMatchToMap (const SearchSuggestionParser::SuggestResult &result, const std::string &metadata, int accepted_suggestion, bool mark_as_deletable, bool in_keyword_mode, MatchMap *map)
bool ParseSuggestResults (const base::Value &root_val, int default_result_relevance, bool is_keyword_result, SearchSuggestionParser::Results *results)
AutocompleteProviderClient * client ()
const AutocompleteProviderClient * client () const
bool field_trial_triggered () const
void set_field_trial_triggered (bool triggered)
void set_field_trial_triggered_in_session (bool triggered)
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from BaseSearchProvider
static std::u16string GetFillIntoEdit (const SearchSuggestionParser::SuggestResult &suggest_result, const TemplateURL *template_url)
static bool CanSendURL (const GURL &current_page_url, const GURL &suggest_url, const TemplateURL *template_url, metrics::OmniboxEventProto::PageClassification page_classification, const SearchTermsData &search_terms_data, AutocompleteProviderClient *client, bool sending_search_terms)
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Static Protected Attributes inherited from BaseSearchProvider
static const char kRelevanceFromServerKey []
static const char kShouldPrefetchKey [] = "should_prefetch"
static const char kSuggestMetadataKey [] = "suggest_metadata"
static const char kDeletionUrlKey [] = "deletion_url"
static const char kTrue [] = "true"
static const char kFalse [] = "false"
Constructor & Destructor Documentation
VoiceSuggestProvider()
VoiceSuggestProvider::VoiceSuggestProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener)
~VoiceSuggestProvider()
VoiceSuggestProvider::~VoiceSuggestProvider () override private default
Member Function Documentation
AddVoiceSuggestion()
void VoiceSuggestProvider::AddVoiceSuggestion (std::u16string match_text, float match_score)
References voice_matches_.
ClearCache()
void VoiceSuggestProvider::ClearCache ()
References voice_matches_.
Referenced by Stop().
GetInput()
const AutocompleteInput VoiceSuggestProvider::GetInput (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References autocomplete_input_.
GetTemplateURL()
const TemplateURL * VoiceSuggestProvider::GetTemplateURL (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References BaseSearchProvider::client(), and AutocompleteProviderClient::GetTemplateURLService().
RecordDeletionResult()
void VoiceSuggestProvider::RecordDeletionResult (bool success) override private virtual
Implements BaseSearchProvider.
ShouldAppendExtraParams()
bool VoiceSuggestProvider::ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult & result) const override private virtual
Implements BaseSearchProvider.
Start()
void VoiceSuggestProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References BaseSearchProvider::AddMatchToMap(), autocomplete_input_, AutocompleteProvider::matches_, voice_matches_, and AutocompleteMatchType::VOICE_SUGGEST.
Stop()
void VoiceSuggestProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References ClearCache(), and AutocompleteProvider::matches_.
Member Data Documentation
autocomplete_input_
const AutocompleteInput* VoiceSuggestProvider::autocomplete_input_ {} private
Referenced by GetInput(), and Start().
voice_matches_
std::vector<std::pair<float, std::u16string> > VoiceSuggestProvider::voice_matches_ private
Referenced by AddVoiceSuggestion(), ClearCache(), and Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/voice_suggest_provider.h
components/omnibox/browser/voice_suggest_provider.cc