Chromium Omnibox: SuggestionDeletionHandler Class Reference
SuggestionDeletionHandler Class Reference
Public Types
typedef base::OnceCallback< void(bool, SuggestionDeletionHandler *)> DeletionCompletedCallback
Public Member Functions
SuggestionDeletionHandler (AutocompleteProviderClient *client, const std::string &deletion_url, DeletionCompletedCallback callback)
~SuggestionDeletionHandler ()
SuggestionDeletionHandler (const SuggestionDeletionHandler &)=delete
SuggestionDeletionHandler & operator= (const SuggestionDeletionHandler &)=delete
Private Member Functions
void OnURLLoadComplete (const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)
Private Attributes
std::unique_ptr< network::SimpleURLLoader > deletion_fetcher_
DeletionCompletedCallback callback_
Member Typedef Documentation
DeletionCompletedCallback
typedef base::OnceCallback<void(bool, SuggestionDeletionHandler*)> SuggestionDeletionHandler::DeletionCompletedCallback
Constructor & Destructor Documentation
SuggestionDeletionHandler() [1/2]
SuggestionDeletionHandler::SuggestionDeletionHandler (AutocompleteProviderClient * client, const std::string & deletion_url, DeletionCompletedCallback callback)
References deletion_fetcher_, AutocompleteProviderClient::GetURLLoaderFactory(), AutocompleteProviderClient::IsOffTheRecord(), and OnURLLoadComplete().
Referenced by BaseSearchProvider::DeleteMatch().
~SuggestionDeletionHandler()
SuggestionDeletionHandler::~SuggestionDeletionHandler ()
SuggestionDeletionHandler() [2/2]
SuggestionDeletionHandler::SuggestionDeletionHandler (const SuggestionDeletionHandler &) delete
Member Function Documentation
OnURLLoadComplete()
void SuggestionDeletionHandler::OnURLLoadComplete (const network::SimpleURLLoader * source, std::unique_ptr< std::string > response_body) private
References callback_, and deletion_fetcher_.
Referenced by SuggestionDeletionHandler().
operator=()
SuggestionDeletionHandler& SuggestionDeletionHandler::operator= (const SuggestionDeletionHandler &) delete
Member Data Documentation
callback_
DeletionCompletedCallback SuggestionDeletionHandler::callback_ private
Referenced by OnURLLoadComplete().
deletion_fetcher_
std::unique_ptr<network::SimpleURLLoader> SuggestionDeletionHandler::deletion_fetcher_ private
Referenced by OnURLLoadComplete(), and SuggestionDeletionHandler().
The documentation for this class was generated from the following file:
components/omnibox/browser/base_search_provider.cc