Chromium Omnibox: OmniboxTextView Class Reference
OmniboxTextView Class Reference
#include <omnibox_text_view.h>
Public Member Functions
METADATA_HEADER (OmniboxTextView)
OmniboxTextView (OmniboxResultView *result_view)
OmniboxTextView (const OmniboxTextView &)=delete
OmniboxTextView & operator= (const OmniboxTextView &)=delete
~OmniboxTextView () override
gfx::Size CalculatePreferredSize () const override
bool GetCanProcessEventsWithinSubtree () const override
int GetHeightForWidth (int width) const override
void OnPaint (gfx::Canvas *canvas) override
void ApplyTextColor (OmniboxPart part)
const std::u16string & GetText () const
void SetText (const std::u16string &new_text)
void SetTextWithStyling (const std::u16string &new_text, const ACMatchClassifications &classifications, bool deemphasize=false)
void SetTextWithStyling (const SuggestionAnswer::ImageLine &line, bool deemphasize)
void AppendExtraText (const SuggestionAnswer::ImageLine &line)
int GetLineHeight () const
void ReapplyStyling ()
std::unique_ptr< gfx::RenderText > CreateRenderText (const std::u16string &text) const
Private Member Functions
void AppendText (const SuggestionAnswer::TextField &field, const std::u16string &prefix)
void OnStyleChanged ()
Private Attributes
OmniboxResultView * result_view_
int font_height_ = 0
bool use_deemphasized_font_ = false
bool wrap_text_lines_ = false
std::unique_ptr< gfx::RenderText > render_text_
std::unique_ptr< ACMatchClassifications > cached_classifications_
Constructor & Destructor Documentation
OmniboxTextView() [1/2]
OmniboxTextView::OmniboxTextView (OmniboxResultView * result_view) explicit
Referenced by OmniboxMatchCellView::OmniboxMatchCellView().
OmniboxTextView() [2/2]
OmniboxTextView::OmniboxTextView (const OmniboxTextView &) delete
~OmniboxTextView()
OmniboxTextView::~OmniboxTextView () override default
Member Function Documentation
AppendExtraText()
void OmniboxTextView::AppendExtraText (const SuggestionAnswer::ImageLine & line)
References SuggestionAnswer::ImageLine::additional_text(), AppendText(), CalculatePreferredSize(), and SuggestionAnswer::ImageLine::status_text().
Referenced by OmniboxResultView::SetMatch(), and SetTextWithStyling().
AppendText()
void OmniboxTextView::AppendText (const SuggestionAnswer::TextField & field, const std::u16string & prefix) private
References GetText(), render_text_, result_view_, SuggestionAnswer::TextField::style(), and SuggestionAnswer::TextField::text().
Referenced by AppendExtraText(), and SetTextWithStyling().
ApplyTextColor()
void OmniboxTextView::ApplyTextColor (OmniboxPart part)
References OmniboxResultView::GetColor(), GetText(), render_text_, and result_view_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons().
CalculatePreferredSize()
gfx::Size OmniboxTextView::CalculatePreferredSize () const override
References render_text_.
Referenced by AppendExtraText(), and OnStyleChanged().
CreateRenderText()
std::unique_ptr< gfx::RenderText > OmniboxTextView::CreateRenderText (const std::u16string & text) const
References use_deemphasized_font_.
Referenced by OmniboxMatchCellView::SetTailSuggestCommonPrefixWidth(), SetText(), and SetTextWithStyling().
GetCanProcessEventsWithinSubtree()
bool OmniboxTextView::GetCanProcessEventsWithinSubtree () const override
GetHeightForWidth()
int OmniboxTextView::GetHeightForWidth (int width) const override
References GetLineHeight(), render_text_, and wrap_text_lines_.
Referenced by OmniboxMatchCellView::CalculatePreferredSize(), and OmniboxMatchCellView::Layout().
GetLineHeight()
int OmniboxTextView::GetLineHeight () const
References font_height_.
Referenced by OmniboxMatchCellView::CalculatePreferredSize(), GetHeightForWidth(), and OmniboxMatchCellView::Layout().
GetText()
const std::u16string & OmniboxTextView::GetText () const
References render_text_.
Referenced by AppendText(), ApplyTextColor(), OmniboxMatchCellView::Layout(), ReapplyStyling(), SetText(), and SetTextWithStyling().
METADATA_HEADER()
OmniboxTextView::METADATA_HEADER (OmniboxTextView)
OnPaint()
void OmniboxTextView::OnPaint (gfx::Canvas * canvas) override
References render_text_.
OnStyleChanged()
void OmniboxTextView::OnStyleChanged () private
References CalculatePreferredSize(), font_height_, and render_text_.
Referenced by ReapplyStyling(), SetText(), and SetTextWithStyling().
operator=()
OmniboxTextView& OmniboxTextView::operator= (const OmniboxTextView &) delete
ReapplyStyling()
void OmniboxTextView::ReapplyStyling ()
References cached_classifications_, AutocompleteMatch::ACMatchClassification::DIM, OmniboxResultView::GetColor(), GetText(), AutocompleteMatch::ACMatchClassification::MATCH, OnStyleChanged(), render_text_, result_view_, RESULTS_TEXT_DEFAULT, RESULTS_TEXT_DIMMED, RESULTS_TEXT_URL, and AutocompleteMatch::ACMatchClassification::URL.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), and SetTextWithStyling().
SetText()
void OmniboxTextView::SetText (const std::u16string & new_text)
References cached_classifications_, CreateRenderText(), GetText(), OnStyleChanged(), render_text_, and use_deemphasized_font_.
Referenced by OmniboxMatchCellView::OmniboxMatchCellView().
SetTextWithStyling() [1/2]
void OmniboxTextView::SetTextWithStyling (const std::u16string & new_text, const ACMatchClassifications & classifications, bool deemphasize = false)
References cached_classifications_, CreateRenderText(), GetText(), ReapplyStyling(), render_text_, and use_deemphasized_font_.
Referenced by OmniboxResultView::SetMatch().
SetTextWithStyling() [2/2]
void OmniboxTextView::SetTextWithStyling (const SuggestionAnswer::ImageLine & line, bool deemphasize)
References AppendExtraText(), AppendText(), cached_classifications_, CreateRenderText(), SuggestionAnswer::TextField::has_num_lines(), SuggestionAnswer::TextField::num_lines(), SuggestionAnswer::ImageLine::num_text_lines(), OnStyleChanged(), render_text_, SuggestionAnswer::ImageLine::text_fields(), use_deemphasized_font_, and wrap_text_lines_.
Member Data Documentation
cached_classifications_
std::unique_ptr<ACMatchClassifications> OmniboxTextView::cached_classifications_ private
Referenced by ReapplyStyling(), SetText(), and SetTextWithStyling().
font_height_
int OmniboxTextView::font_height_ = 0 private
Referenced by GetLineHeight(), and OnStyleChanged().
render_text_
std::unique_ptr<gfx::RenderText> OmniboxTextView::render_text_ private
Referenced by AppendText(), ApplyTextColor(), CalculatePreferredSize(), GetHeightForWidth(), GetText(), OnPaint(), OnStyleChanged(), ReapplyStyling(), SetText(), and SetTextWithStyling().
result_view_
OmniboxResultView* OmniboxTextView::result_view_ private
Referenced by AppendText(), ApplyTextColor(), and ReapplyStyling().
use_deemphasized_font_
bool OmniboxTextView::use_deemphasized_font_ = false private
Referenced by CreateRenderText(), SetText(), and SetTextWithStyling().
wrap_text_lines_
bool OmniboxTextView::wrap_text_lines_ = false private
Referenced by GetHeightForWidth(), and SetTextWithStyling().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_text_view.h
chrome/browser/ui/views/omnibox/omnibox_text_view.cc