Chromium Omnibox: FakeAutocompleteProviderClient Class Reference
FakeAutocompleteProviderClient Class Reference
#include <fake_autocomplete_provider_client.h>
Public Member Functions
FakeAutocompleteProviderClient (bool create_history_db=true)
~FakeAutocompleteProviderClient () override
FakeAutocompleteProviderClient (const FakeAutocompleteProviderClient &)=delete
FakeAutocompleteProviderClient & operator= (const FakeAutocompleteProviderClient &)=delete
PrefService * GetPrefs () const override
PrefService * GetLocalState () override
const AutocompleteSchemeClassifier & GetSchemeClassifier () const override
history::HistoryService * GetHistoryService () override
bookmarks::BookmarkModel * GetBookmarkModel () override
InMemoryURLIndex * GetInMemoryURLIndex () override
scoped_refptr< ShortcutsBackend > GetShortcutsBackend () override
scoped_refptr< ShortcutsBackend > GetShortcutsBackendIfExists () override
query_tiles::TileService * GetQueryTileService () const override
void set_in_memory_url_index (std::unique_ptr< InMemoryURLIndex > index)
bool IsTabOpenWithURL (const GURL &url, const AutocompleteInput *input) override
void set_url_substring_match (const std::string &substr)
Public Member Functions inherited from MockAutocompleteProviderClient
MockAutocompleteProviderClient ()
~MockAutocompleteProviderClient ()
MockAutocompleteProviderClient (const MockAutocompleteProviderClient &)=delete
MockAutocompleteProviderClient & operator= (const MockAutocompleteProviderClient &)=delete
MOCK_CONST_METHOD0 (GetPrefs, PrefService *())
MOCK_METHOD0 (GetLocalState, PrefService *())
MOCK_CONST_METHOD0 (GetSchemeClassifier, const AutocompleteSchemeClassifier &())
MOCK_METHOD0 (GetAutocompleteClassifier, AutocompleteClassifier *())
MOCK_METHOD0 (GetHistoryService, history::HistoryService *())
scoped_refptr< network::SharedURLLoaderFactory > GetURLLoaderFactory () override
scoped_refptr< history::TopSites > GetTopSites () override
MOCK_METHOD0 (GetBookmarkModel, bookmarks::BookmarkModel *())
MOCK_METHOD0 (GetInMemoryDatabase, history::URLDatabase *())
MOCK_METHOD0 (GetInMemoryURLIndex, InMemoryURLIndex *())
TemplateURLService * GetTemplateURLService () override
const TemplateURLService * GetTemplateURLService () const override
RemoteSuggestionsService * GetRemoteSuggestionsService (bool create_if_necessary) const override
DocumentSuggestionsService * GetDocumentSuggestionsService (bool create_if_necessary) const override
OmniboxPedalProvider * GetPedalProvider () const override
scoped_refptr< ShortcutsBackend > GetShortcutsBackend () override
scoped_refptr< ShortcutsBackend > GetShortcutsBackendIfExists () override
std::unique_ptr< KeywordExtensionsDelegate > GetKeywordExtensionsDelegate (KeywordProvider *keyword_provider) override
query_tiles::TileService * GetQueryTileService () const override
OmniboxTriggeredFeatureService * GetOmniboxTriggeredFeatureService () const override
component_updater::ComponentUpdateService * GetComponentUpdateService () override
signin::IdentityManager * GetIdentityManager () const override
MOCK_CONST_METHOD0 (GetAcceptLanguages, std::string())
MOCK_CONST_METHOD0 (GetEmbedderRepresentationOfAboutScheme, std::string())
MOCK_METHOD0 (GetBuiltinURLs, std::vector< std::u16string >())
MOCK_METHOD0 (GetBuiltinsToProvideAsUserTypes, std::vector< std::u16string >())
MOCK_CONST_METHOD0 (IsOffTheRecord, bool())
MOCK_CONST_METHOD0 (SearchSuggestEnabled, bool())
MOCK_CONST_METHOD0 (IsPersonalizedUrlDataCollectionActive, bool())
MOCK_CONST_METHOD0 (IsAuthenticated, bool())
MOCK_CONST_METHOD0 (IsSyncActive, bool())
MOCK_METHOD6 (Classify, void(const std::u16string &text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch *match, GURL *alternate_nav_url))
MOCK_METHOD2 (DeleteMatchingURLsForKeywordFromHistory, void(history::KeywordID keyword_id, const std::u16string &term))
MOCK_METHOD1 (PrefetchImage, void(const GURL &url))
bool IsTabOpenWithURL (const GURL &url, const AutocompleteInput *input) override
void set_template_url_service (std::unique_ptr< TemplateURLService > service)
void set_identity_manager (signin::IdentityManager *identity_manager)
network::TestURLLoaderFactory * test_url_loader_factory ()
Private Attributes
base::ScopedTempDir history_dir_
std::unique_ptr< bookmarks::BookmarkModel > bookmark_model_
TestSchemeClassifier scheme_classifier_
std::unique_ptr< InMemoryURLIndex > in_memory_url_index_
std::unique_ptr< history::HistoryService > history_service_
std::unique_ptr< TestingPrefServiceSimple > local_state_
std::unique_ptr< TestingPrefServiceSimple > pref_service_
scoped_refptr< ShortcutsBackend > shortcuts_backend_
std::unique_ptr< query_tiles::TileService > tile_service_
std::string substring_to_match_
Constructor & Destructor Documentation
FakeAutocompleteProviderClient() [1/2]
FakeAutocompleteProviderClient::FakeAutocompleteProviderClient (bool create_history_db = true) explicit
References bookmark_model_, GetHistoryService(), MockAutocompleteProviderClient::GetTemplateURLService(), history_dir_, history_service_, in_memory_url_index_, InMemoryURLIndex::InMemoryURLIndex(), local_state_, pref_service_, MockAutocompleteProviderClient::set_template_url_service(), shortcuts_backend_, and tile_service_.
~FakeAutocompleteProviderClient()
FakeAutocompleteProviderClient::~FakeAutocompleteProviderClient () override
References GetHistoryService(), GetInMemoryURLIndex(), set_in_memory_url_index(), and InMemoryURLIndex::Shutdown().
FakeAutocompleteProviderClient() [2/2]
FakeAutocompleteProviderClient::FakeAutocompleteProviderClient (const FakeAutocompleteProviderClient &) delete
Member Function Documentation
GetBookmarkModel()
bookmarks::BookmarkModel * FakeAutocompleteProviderClient::GetBookmarkModel () override
References bookmark_model_.
GetHistoryService()
history::HistoryService * FakeAutocompleteProviderClient::GetHistoryService () override
References history_service_.
Referenced by FakeAutocompleteProviderClient(), and ~FakeAutocompleteProviderClient().
GetInMemoryURLIndex()
InMemoryURLIndex * FakeAutocompleteProviderClient::GetInMemoryURLIndex () override
References in_memory_url_index_.
Referenced by ~FakeAutocompleteProviderClient().
GetLocalState()
PrefService * FakeAutocompleteProviderClient::GetLocalState () override
References local_state_.
GetPrefs()
PrefService * FakeAutocompleteProviderClient::GetPrefs () const override
References pref_service_.
GetQueryTileService()
query_tiles::TileService * FakeAutocompleteProviderClient::GetQueryTileService () const override
References tile_service_.
GetSchemeClassifier()
const AutocompleteSchemeClassifier & FakeAutocompleteProviderClient::GetSchemeClassifier () const override
References scheme_classifier_.
GetShortcutsBackend()
scoped_refptr< ShortcutsBackend > FakeAutocompleteProviderClient::GetShortcutsBackend () override
References shortcuts_backend_.
GetShortcutsBackendIfExists()
scoped_refptr< ShortcutsBackend > FakeAutocompleteProviderClient::GetShortcutsBackendIfExists () override
References shortcuts_backend_.
IsTabOpenWithURL()
bool FakeAutocompleteProviderClient::IsTabOpenWithURL (const GURL & url, const AutocompleteInput * input) override
References substring_to_match_.
operator=()
FakeAutocompleteProviderClient& FakeAutocompleteProviderClient::operator= (const FakeAutocompleteProviderClient &) delete
set_in_memory_url_index()
void FakeAutocompleteProviderClient::set_in_memory_url_index (std::unique_ptr< InMemoryURLIndex > index) inline
References in_memory_url_index_.
Referenced by ~FakeAutocompleteProviderClient().
set_url_substring_match()
void FakeAutocompleteProviderClient::set_url_substring_match (const std::string & substr) inline
References substring_to_match_.
Member Data Documentation
bookmark_model_
std::unique_ptr<bookmarks::BookmarkModel> FakeAutocompleteProviderClient::bookmark_model_ private
Referenced by FakeAutocompleteProviderClient(), and GetBookmarkModel().
history_dir_
base::ScopedTempDir FakeAutocompleteProviderClient::history_dir_ private
Referenced by FakeAutocompleteProviderClient().
history_service_
std::unique_ptr<history::HistoryService> FakeAutocompleteProviderClient::history_service_ private
Referenced by FakeAutocompleteProviderClient(), and GetHistoryService().
in_memory_url_index_
std::unique_ptr<InMemoryURLIndex> FakeAutocompleteProviderClient::in_memory_url_index_ private
Referenced by FakeAutocompleteProviderClient(), GetInMemoryURLIndex(), and set_in_memory_url_index().
local_state_
std::unique_ptr<TestingPrefServiceSimple> FakeAutocompleteProviderClient::local_state_ private
Referenced by FakeAutocompleteProviderClient(), and GetLocalState().
pref_service_
std::unique_ptr<TestingPrefServiceSimple> FakeAutocompleteProviderClient::pref_service_ private
Referenced by FakeAutocompleteProviderClient(), and GetPrefs().
scheme_classifier_
TestSchemeClassifier FakeAutocompleteProviderClient::scheme_classifier_ private
Referenced by GetSchemeClassifier().
shortcuts_backend_
scoped_refptr<ShortcutsBackend> FakeAutocompleteProviderClient::shortcuts_backend_ private
Referenced by FakeAutocompleteProviderClient(), GetShortcutsBackend(), and GetShortcutsBackendIfExists().
substring_to_match_
std::string FakeAutocompleteProviderClient::substring_to_match_ private
Referenced by IsTabOpenWithURL(), and set_url_substring_match().
tile_service_
std::unique_ptr<query_tiles::TileService> FakeAutocompleteProviderClient::tile_service_ private
Referenced by FakeAutocompleteProviderClient(), and GetQueryTileService().
The documentation for this class was generated from the following files:
components/omnibox/browser/fake_autocomplete_provider_client.h
components/omnibox/browser/fake_autocomplete_provider_client.cc