Chromium Omnibox: OmniboxSuggestionButtonRowView Class Reference
OmniboxSuggestionButtonRowView Class Reference
#include <omnibox_suggestion_button_row_view.h>
Public Member Functions
METADATA_HEADER (OmniboxSuggestionButtonRowView)
OmniboxSuggestionButtonRowView (OmniboxPopupContentsView *view, int model_index)
OmniboxSuggestionButtonRowView (const OmniboxSuggestionButtonRowView &)=delete
OmniboxSuggestionButtonRowView & operator= (const OmniboxSuggestionButtonRowView &)=delete
~OmniboxSuggestionButtonRowView () override
void OnOmniboxBackgroundChange (SkColor omnibox_bg_color)
void UpdateFromModel ()
views::Button * GetActiveButton () const
Private Member Functions
const OmniboxPopupModel * model () const
const AutocompleteMatch & match () const
void SetPillButtonVisibility (OmniboxSuggestionRowButton *button, OmniboxPopupModel::LineState state)
void ButtonPressed (OmniboxPopupModel::LineState state, const ui::Event &event)
Private Attributes
OmniboxPopupContentsView *const popup_contents_view_
size_t const model_index_
OmniboxSuggestionRowButton * keyword_button_ = nullptr
OmniboxSuggestionRowButton * pedal_button_ = nullptr
OmniboxSuggestionRowButton * tab_switch_button_ = nullptr
Constructor & Destructor Documentation
OmniboxSuggestionButtonRowView() [1/2]
END_METADATA OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView (OmniboxPopupContentsView * view, int model_index) explicit
References ButtonPressed(), OmniboxPopupModel::FOCUSED_BUTTON_ACTION, OmniboxPopupModel::FOCUSED_BUTTON_TAB_SWITCH, OmniboxPedal::GetDefaultVectorIcon(), OmniboxMatchCellView::GetTextIndent(), keyword_button_, OmniboxPopupModel::KEYWORD_MODE, model_index_, OmniboxSuggestionRowButton::OmniboxSuggestionRowButton(), pedal_button_, popup_contents_view_, and tab_switch_button_.
Referenced by OmniboxResultView::OmniboxResultView().
OmniboxSuggestionButtonRowView() [2/2]
OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView (const OmniboxSuggestionButtonRowView &) delete
~OmniboxSuggestionButtonRowView()
OmniboxSuggestionButtonRowView::~OmniboxSuggestionButtonRowView () override default
Member Function Documentation
ButtonPressed()
void OmniboxSuggestionButtonRowView::ButtonPressed (OmniboxPopupModel::LineState state, const ui::Event & event) private
References OmniboxEditModel::AcceptKeyword(), OmniboxPopupModel::edit_model(), OmniboxPopupModel::KEYWORD_MODE, OmniboxPopupContentsView::model(), model(), model_index_, popup_contents_view_, OmniboxPopupModel::SetSelection(), and OmniboxPopupModel::TriggerSelectionAction().
Referenced by OmniboxSuggestionButtonRowView().
GetActiveButton()
views::Button * OmniboxSuggestionButtonRowView::GetActiveButton () const
References keyword_button_, pedal_button_, and tab_switch_button_.
Referenced by OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility().
match()
const AutocompleteMatch & OmniboxSuggestionButtonRowView::match () const private
References AutocompleteResult::match_at(), model(), model_index_, and OmniboxPopupModel::result().
Referenced by UpdateFromModel().
METADATA_HEADER()
OmniboxSuggestionButtonRowView::METADATA_HEADER (OmniboxSuggestionButtonRowView)
model()
const OmniboxPopupModel * OmniboxSuggestionButtonRowView::model () const private
References OmniboxPopupContentsView::model(), and popup_contents_view_.
Referenced by ButtonPressed(), match(), SetPillButtonVisibility(), and UpdateFromModel().
OnOmniboxBackgroundChange()
void OmniboxSuggestionButtonRowView::OnOmniboxBackgroundChange (SkColor omnibox_bg_color)
References keyword_button_, OmniboxSuggestionRowButton::OnOmniboxBackgroundChange(), pedal_button_, and tab_switch_button_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons().
operator=()
OmniboxSuggestionButtonRowView& OmniboxSuggestionButtonRowView::operator= (const OmniboxSuggestionButtonRowView &) delete
SetPillButtonVisibility()
void OmniboxSuggestionButtonRowView::SetPillButtonVisibility (OmniboxSuggestionRowButton * button, OmniboxPopupModel::LineState state) private
References OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), keyword_button_, model(), and model_index_.
Referenced by UpdateFromModel().
UpdateFromModel()
void OmniboxSuggestionButtonRowView::UpdateFromModel ()
References AutocompleteMatch::action, OmniboxEditModel::client(), OmniboxPopupModel::edit_model(), OmniboxPopupModel::FOCUSED_BUTTON_ACTION, OmniboxPopupModel::FOCUSED_BUTTON_TAB_SWITCH, AutocompleteMatch::GetKeywordUIState(), OmniboxClient::GetTemplateURLService(), AutocompleteMatch::GetVectorIcon(), keyword_button_, OmniboxPopupModel::KEYWORD_MODE, match(), model(), pedal_button_, OmniboxSuggestionRowButton::SetIcon(), SetPillButtonVisibility(), and tab_switch_button_.
Referenced by OmniboxResultView::SetMatch().
Member Data Documentation
keyword_button_
OmniboxSuggestionRowButton* OmniboxSuggestionButtonRowView::keyword_button_ = nullptr private
Referenced by GetActiveButton(), OmniboxSuggestionButtonRowView(), OnOmniboxBackgroundChange(), SetPillButtonVisibility(), and UpdateFromModel().
model_index_
size_t const OmniboxSuggestionButtonRowView::model_index_ private
Referenced by ButtonPressed(), match(), OmniboxSuggestionButtonRowView(), and SetPillButtonVisibility().
pedal_button_
OmniboxSuggestionRowButton* OmniboxSuggestionButtonRowView::pedal_button_ = nullptr private
Referenced by GetActiveButton(), OmniboxSuggestionButtonRowView(), OnOmniboxBackgroundChange(), and UpdateFromModel().
popup_contents_view_
OmniboxPopupContentsView* const OmniboxSuggestionButtonRowView::popup_contents_view_ private
Referenced by ButtonPressed(), model(), and OmniboxSuggestionButtonRowView().
tab_switch_button_
OmniboxSuggestionRowButton* OmniboxSuggestionButtonRowView::tab_switch_button_ = nullptr private
Referenced by GetActiveButton(), OmniboxSuggestionButtonRowView(), OnOmniboxBackgroundChange(), and UpdateFromModel().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_suggestion_button_row_view.h
chrome/browser/ui/views/omnibox/omnibox_suggestion_button_row_view.cc