Chromium Omnibox: HUPScoringParams::ScoreBuckets Class Reference
HUPScoringParams::ScoreBuckets Class Reference
#include <omnibox_field_trial.h>
Public Types
typedef std::pair< double, int > CountMaxRelevance
Public Member Functions
ScoreBuckets ()
ScoreBuckets (const ScoreBuckets &other)
~ScoreBuckets ()
double HalfLifeTimeDecay (const base::TimeDelta &elapsed_time) const
int relevance_cap () const
void set_relevance_cap (int relevance_cap)
int half_life_days () const
void set_half_life_days (int half_life_days)
bool use_decay_factor () const
void set_use_decay_factor (bool use_decay_factor)
std::vector< CountMaxRelevance > & buckets ()
const std::vector< CountMaxRelevance > & buckets () const
size_t EstimateMemoryUsage () const
Private Attributes
int relevance_cap_
int half_life_days_
std::vector< CountMaxRelevance > buckets_
bool use_decay_factor_
Member Typedef Documentation
CountMaxRelevance
typedef std::pair<double, int> HUPScoringParams::ScoreBuckets::CountMaxRelevance
Constructor & Destructor Documentation
ScoreBuckets() [1/2]
HUPScoringParams::ScoreBuckets::ScoreBuckets ()
ScoreBuckets() [2/2]
HUPScoringParams::ScoreBuckets::ScoreBuckets (const ScoreBuckets & other) default
~ScoreBuckets()
HUPScoringParams::ScoreBuckets::~ScoreBuckets ()
Member Function Documentation
buckets() [1/2]
std::vector<CountMaxRelevance>& HUPScoringParams::ScoreBuckets::buckets () inline
References buckets_.
buckets() [2/2]
const std::vector<CountMaxRelevance>& HUPScoringParams::ScoreBuckets::buckets () const inline
References buckets_.
EstimateMemoryUsage()
size_t HUPScoringParams::ScoreBuckets::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage().
half_life_days()
int HUPScoringParams::ScoreBuckets::half_life_days () const inline
References half_life_days_.
Referenced by set_half_life_days().
HalfLifeTimeDecay()
double HUPScoringParams::ScoreBuckets::HalfLifeTimeDecay (const base::TimeDelta & elapsed_time) const
relevance_cap()
int HUPScoringParams::ScoreBuckets::relevance_cap () const inline
References relevance_cap_.
Referenced by set_relevance_cap().
set_half_life_days()
void HUPScoringParams::ScoreBuckets::set_half_life_days (int half_life_days) inline
References half_life_days(), and half_life_days_.
Referenced by OmniboxFieldTrial::GetDefaultHUPScoringParams().
set_relevance_cap()
void HUPScoringParams::ScoreBuckets::set_relevance_cap (int relevance_cap) inline
References relevance_cap(), and relevance_cap_.
set_use_decay_factor()
void HUPScoringParams::ScoreBuckets::set_use_decay_factor (bool use_decay_factor) inline
References use_decay_factor(), and use_decay_factor_.
use_decay_factor()
bool HUPScoringParams::ScoreBuckets::use_decay_factor () const inline
References use_decay_factor_.
Referenced by set_use_decay_factor().
Member Data Documentation
buckets_
std::vector<CountMaxRelevance> HUPScoringParams::ScoreBuckets::buckets_ private
Referenced by buckets().
half_life_days_
int HUPScoringParams::ScoreBuckets::half_life_days_ private
Referenced by half_life_days(), and set_half_life_days().
relevance_cap_
int HUPScoringParams::ScoreBuckets::relevance_cap_ private
Referenced by relevance_cap(), and set_relevance_cap().
use_decay_factor_
bool HUPScoringParams::ScoreBuckets::use_decay_factor_ private
Referenced by set_use_decay_factor(), and use_decay_factor().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_field_trial.h
components/omnibox/browser/omnibox_field_trial.cc