var searchData=
[
  ['scored_5fhistory_5fmatch_2ecc_3068',['scored_history_match.cc',['../d2/d90/scored__history__match_8cc.html',1,'']]],
  ['scored_5fhistory_5fmatch_2eh_3069',['scored_history_match.h',['../da/d9b/scored__history__match_8h.html',1,'']]],
  ['search_5fprovider_2ecc_3070',['search_provider.cc',['../da/d9f/search__provider_8cc.html',1,'']]],
  ['search_5fprovider_2eh_3071',['search_provider.h',['../d5/dd0/search__provider_8h.html',1,'']]],
  ['search_5fsuggestion_5fparser_2ecc_3072',['search_suggestion_parser.cc',['../da/dac/search__suggestion__parser_8cc.html',1,'']]],
  ['search_5fsuggestion_5fparser_2eh_3073',['search_suggestion_parser.h',['../d5/d7d/search__suggestion__parser_8h.html',1,'']]],
  ['search_5fsuggestion_5fparser_5ffuzzer_2ecc_3074',['search_suggestion_parser_fuzzer.cc',['../d8/de9/search__suggestion__parser__fuzzer_8cc.html',1,'']]],
  ['shortcuts_5fbackend_2ecc_3075',['shortcuts_backend.cc',['../da/dce/shortcuts__backend_8cc.html',1,'']]],
  ['shortcuts_5fbackend_2eh_3076',['shortcuts_backend.h',['../d1/d64/shortcuts__backend_8h.html',1,'']]],
  ['shortcuts_5fconstants_2ecc_3077',['shortcuts_constants.cc',['../d3/d42/shortcuts__constants_8cc.html',1,'']]],
  ['shortcuts_5fconstants_2eh_3078',['shortcuts_constants.h',['../da/d26/shortcuts__constants_8h.html',1,'']]],
  ['shortcuts_5fdatabase_2ecc_3079',['shortcuts_database.cc',['../de/d0b/shortcuts__database_8cc.html',1,'']]],
  ['shortcuts_5fdatabase_2eh_3080',['shortcuts_database.h',['../df/d0f/shortcuts__database_8h.html',1,'']]],
  ['shortcuts_5fprovider_2ecc_3081',['shortcuts_provider.cc',['../db/d1c/shortcuts__provider_8cc.html',1,'']]],
  ['shortcuts_5fprovider_2eh_3082',['shortcuts_provider.h',['../d4/d55/shortcuts__provider_8h.html',1,'']]],
  ['suggestion_5fanswer_2ecc_3083',['suggestion_answer.cc',['../dd/db5/suggestion__answer_8cc.html',1,'']]],
  ['suggestion_5fanswer_2eh_3084',['suggestion_answer.h',['../dd/d32/suggestion__answer_8h.html',1,'']]]
];
