Chromium Omnibox: DocumentSuggestionsService Class Reference
DocumentSuggestionsService Class Reference
#include <document_suggestions_service.h>
Public Types
using StartCallback = base::OnceCallback< void(std::unique_ptr< network::SimpleURLLoader > loader)>
using CompletionCallback = base::OnceCallback< void(const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)>
Public Member Functions
DocumentSuggestionsService (signin::IdentityManager *identity_manager, scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory)
~DocumentSuggestionsService () override
DocumentSuggestionsService (const DocumentSuggestionsService &)=delete
DocumentSuggestionsService & operator= (const DocumentSuggestionsService &)=delete
void CreateDocumentSuggestionsRequest (const std::u16string &query, bool is_incognito, StartCallback start_callback, CompletionCallback completion_callback)
void StopCreatingDocumentSuggestionsRequest ()
Private Member Functions
void AccessTokenAvailable (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback, GoogleServiceAuthError error, signin::AccessTokenInfo access_token_info)
void StartDownloadAndTransferLoader (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback)
Private Attributes
scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory_
signin::IdentityManager * identity_manager_
std::unique_ptr< signin::PrimaryAccountAccessTokenFetcher > token_fetcher_
Member Typedef Documentation
CompletionCallback
using DocumentSuggestionsService::CompletionCallback = base::OnceCallback<void(const network::SimpleURLLoader* source, std::unique_ptr<std::string> response_body)>
StartCallback
using DocumentSuggestionsService::StartCallback = base::OnceCallback<void(std::unique_ptr<network::SimpleURLLoader> loader)>
Constructor & Destructor Documentation
DocumentSuggestionsService() [1/2]
DocumentSuggestionsService::DocumentSuggestionsService (signin::IdentityManager * identity_manager, scoped_refptr< network::SharedURLLoaderFactory > url_loader_factory)
Referenced by MockAutocompleteProviderClient::MockAutocompleteProviderClient().
~DocumentSuggestionsService()
DocumentSuggestionsService::~DocumentSuggestionsService () override
DocumentSuggestionsService() [2/2]
DocumentSuggestionsService::DocumentSuggestionsService (const DocumentSuggestionsService &) delete
Member Function Documentation
AccessTokenAvailable()
void DocumentSuggestionsService::AccessTokenAvailable (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback, GoogleServiceAuthError error, signin::AccessTokenInfo access_token_info) private
References StartDownloadAndTransferLoader(), and token_fetcher_.
Referenced by CreateDocumentSuggestionsRequest().
CreateDocumentSuggestionsRequest()
void DocumentSuggestionsService::CreateDocumentSuggestionsRequest (const std::u16string & query, bool is_incognito, StartCallback start_callback, CompletionCallback completion_callback)
References AccessTokenAvailable(), identity_manager_, omnibox::kDocumentProvider, omnibox::kDocumentProviderAso, and token_fetcher_.
Referenced by DocumentProvider::Run().
operator=()
DocumentSuggestionsService& DocumentSuggestionsService::operator= (const DocumentSuggestionsService &) delete
StartDownloadAndTransferLoader()
void DocumentSuggestionsService::StartDownloadAndTransferLoader (std::unique_ptr< network::ResourceRequest > request, std::string request_body, net::NetworkTrafficAnnotationTag traffic_annotation, StartCallback start_callback, CompletionCallback completion_callback) private
References url_loader_factory_.
Referenced by AccessTokenAvailable().
StopCreatingDocumentSuggestionsRequest()
void DocumentSuggestionsService::StopCreatingDocumentSuggestionsRequest ()
References token_fetcher_.
Referenced by DocumentProvider::Stop().
Member Data Documentation
identity_manager_
signin::IdentityManager* DocumentSuggestionsService::identity_manager_ private
Referenced by CreateDocumentSuggestionsRequest().
token_fetcher_
std::unique_ptr<signin::PrimaryAccountAccessTokenFetcher> DocumentSuggestionsService::token_fetcher_ private
Referenced by AccessTokenAvailable(), CreateDocumentSuggestionsRequest(), and StopCreatingDocumentSuggestionsRequest().
url_loader_factory_
scoped_refptr<network::SharedURLLoaderFactory> DocumentSuggestionsService::url_loader_factory_ private
Referenced by StartDownloadAndTransferLoader().
The documentation for this class was generated from the following files:
components/omnibox/browser/document_suggestions_service.h
components/omnibox/browser/document_suggestions_service.cc