Chromium Omnibox: OmniboxTriggeredFeatureService Class Reference
OmniboxTriggeredFeatureService Class Reference
#include <omnibox_triggered_feature_service.h>
Public Types
enum class Feature { kRichAutocompletion = 0 , kBookmarkPaths = 1 , kShortBookmarkSuggestionsByTotalInputLength = 2 , kMaxValue = kShortBookmarkSuggestionsByTotalInputLength }
using Features = std::set< Feature >
Public Member Functions
OmniboxTriggeredFeatureService ()
~OmniboxTriggeredFeatureService ()
void RecordToLogs (Features *feature_triggered_in_session) const
void TriggerFeature (Feature feature)
void ResetSession ()
Private Attributes
std::set< Feature > features_
Member Typedef Documentation
Features
using OmniboxTriggeredFeatureService::Features = std::set<Feature>
Member Enumeration Documentation
Feature
enum OmniboxTriggeredFeatureService::Feature strong
Enumerator
kRichAutocompletion
kBookmarkPaths
kShortBookmarkSuggestionsByTotalInputLength
kMaxValue
Constructor & Destructor Documentation
OmniboxTriggeredFeatureService()
OmniboxTriggeredFeatureService::OmniboxTriggeredFeatureService () default
Referenced by MockAutocompleteProviderClient::MockAutocompleteProviderClient().
~OmniboxTriggeredFeatureService()
OmniboxTriggeredFeatureService::~OmniboxTriggeredFeatureService () default
Member Function Documentation
RecordToLogs()
void OmniboxTriggeredFeatureService::RecordToLogs (Features * feature_triggered_in_session) const
References features_.
ResetSession()
void OmniboxTriggeredFeatureService::ResetSession ()
References features_.
TriggerFeature()
void OmniboxTriggeredFeatureService::TriggerFeature (Feature feature)
References features_.
Referenced by BookmarkProvider::GetMatchesWithBookmarkPaths(), and BookmarkProvider::GetMatchingAlgorithm().
Member Data Documentation
features_
std::set<Feature> OmniboxTriggeredFeatureService::features_ private
Referenced by RecordToLogs(), ResetSession(), and TriggerFeature().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_triggered_feature_service.h
components/omnibox/browser/omnibox_triggered_feature_service.cc