Chromium Omnibox: RoundedOmniboxResultsFrame Class Reference
RoundedOmniboxResultsFrame Class Reference
#include <rounded_omnibox_results_frame.h>
Public Member Functions
METADATA_HEADER (RoundedOmniboxResultsFrame)
RoundedOmniboxResultsFrame (views::View *contents, LocationBarView *location_bar)
RoundedOmniboxResultsFrame (const RoundedOmniboxResultsFrame &)=delete
RoundedOmniboxResultsFrame & operator= (const RoundedOmniboxResultsFrame &)=delete
~RoundedOmniboxResultsFrame () override
void Layout () override
void AddedToWidget () override
void OnMouseMoved (const ui::MouseEvent &event) override
void OnMouseEvent (ui::MouseEvent *event) override
Static Public Member Functions
static void OnBeforeWidgetInit (views::Widget::InitParams *params, views::Widget *widget)
static int GetNonResultSectionHeight ()
static gfx::Insets GetLocationBarAlignmentInsets ()
static gfx::Insets GetShadowInsets ()
Private Attributes
views::View * top_background_ = nullptr
views::View * contents_host_ = nullptr
views::View * contents_
Constructor & Destructor Documentation
RoundedOmniboxResultsFrame() [1/2]
RoundedOmniboxResultsFrame::RoundedOmniboxResultsFrame (views::View * contents, LocationBarView * location_bar)
References contents_, contents_host_, and top_background_.
Referenced by OmniboxPopupContentsView::AutocompletePopupWidget::SetPopupContentsView().
RoundedOmniboxResultsFrame() [2/2]
RoundedOmniboxResultsFrame::RoundedOmniboxResultsFrame (const RoundedOmniboxResultsFrame &) delete
~RoundedOmniboxResultsFrame()
RoundedOmniboxResultsFrame::~RoundedOmniboxResultsFrame () override default
Member Function Documentation
AddedToWidget()
void RoundedOmniboxResultsFrame::AddedToWidget () override
GetLocationBarAlignmentInsets()
gfx::Insets RoundedOmniboxResultsFrame::GetLocationBarAlignmentInsets () static
Referenced by GetNonResultSectionHeight(), OmniboxPopupContentsView::GetTargetBounds(), and Layout().
GetNonResultSectionHeight()
int RoundedOmniboxResultsFrame::GetNonResultSectionHeight () static
References GetLocationBarAlignmentInsets().
Referenced by OmniboxPopupContentsView::GetTargetBounds(), and Layout().
GetShadowInsets()
gfx::Insets RoundedOmniboxResultsFrame::GetShadowInsets () static
Referenced by OmniboxPopupContentsView::GetTargetBounds().
Layout()
void RoundedOmniboxResultsFrame::Layout () override
References contents_, contents_host_, GetLocationBarAlignmentInsets(), GetNonResultSectionHeight(), and top_background_.
METADATA_HEADER()
RoundedOmniboxResultsFrame::METADATA_HEADER (RoundedOmniboxResultsFrame)
OnBeforeWidgetInit()
void RoundedOmniboxResultsFrame::OnBeforeWidgetInit (views::Widget::InitParams * params, views::Widget * widget) static
Referenced by OmniboxPopupContentsView::AutocompletePopupWidget::InitOmniboxPopup().
OnMouseEvent()
void RoundedOmniboxResultsFrame::OnMouseEvent (ui::MouseEvent * event) override
OnMouseMoved()
void RoundedOmniboxResultsFrame::OnMouseMoved (const ui::MouseEvent & event) override
operator=()
RoundedOmniboxResultsFrame& RoundedOmniboxResultsFrame::operator= (const RoundedOmniboxResultsFrame &) delete
Member Data Documentation
contents_
views::View* RoundedOmniboxResultsFrame::contents_ private
Referenced by Layout(), and RoundedOmniboxResultsFrame().
contents_host_
views::View* RoundedOmniboxResultsFrame::contents_host_ = nullptr private
Referenced by Layout(), and RoundedOmniboxResultsFrame().
top_background_
views::View* RoundedOmniboxResultsFrame::top_background_ = nullptr private
Referenced by Layout(), and RoundedOmniboxResultsFrame().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/rounded_omnibox_results_frame.h
chrome/browser/ui/views/omnibox/rounded_omnibox_results_frame.cc