Chromium Omnibox: SearchProvider Class Reference
SearchProvider Class Reference
#include <search_provider.h>
Classes
class CompareScoredResults
class Providers
Public Member Functions
SearchProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
SearchProvider (const SearchProvider &)=delete
SearchProvider & operator= (const SearchProvider &)=delete
void RegisterDisplayedAnswers (const AutocompleteResult &result)
void ResetSession () override
Public Member Functions inherited from BaseSearchProvider
BaseSearchProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
BaseSearchProvider (const BaseSearchProvider &)=delete
BaseSearchProvider & operator= (const BaseSearchProvider &)=delete
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
bool field_trial_triggered_in_session () const
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static std::string GetSuggestMetadata (const AutocompleteMatch &match)
static int CalculateRelevanceForKeywordVerbatim (metrics::OmniboxInputType type, bool allow_exact_keyword_match, bool prefer_keyword)
Static Public Member Functions inherited from BaseSearchProvider
static bool ShouldPrefetch (const AutocompleteMatch &match)
static AutocompleteMatch CreateSearchSuggestion (const std::u16string &suggestion, AutocompleteMatchType::Type type, bool from_keyword_provider, const TemplateURL *template_url, const SearchTermsData &search_terms_data)
static AutocompleteMatch CreateSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const bool in_keyword_mode, const SearchSuggestionParser::SuggestResult &suggestion, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion, bool append_extra_query_params_from_command_line)
static AutocompleteMatch CreateOnDeviceSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const std::u16string &suggestion, int relevance, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion)
static void AppendSuggestClientToAdditionalQueryParams (const TemplateURL *template_url, const SearchTermsData &search_terms_data, metrics::OmniboxEventProto::PageClassification page_classification, TemplateURLRef::SearchTermsArgs *search_terms_args)
static bool IsNTPPage (metrics::OmniboxEventProto::PageClassification classification)
static bool IsSearchResultsPage (metrics::OmniboxEventProto::PageClassification classification)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Static Public Attributes
static const int kNonURLVerbatimRelevance = 1300
Protected Member Functions
~SearchProvider () override
Protected Member Functions inherited from BaseSearchProvider
~BaseSearchProvider () override
void SetDeletionURL (const std::string &deletion_url, AutocompleteMatch *match)
void AddMatchToMap (const SearchSuggestionParser::SuggestResult &result, const std::string &metadata, int accepted_suggestion, bool mark_as_deletable, bool in_keyword_mode, MatchMap *map)
bool ParseSuggestResults (const base::Value &root_val, int default_result_relevance, bool is_keyword_result, SearchSuggestionParser::Results *results)
AutocompleteProviderClient * client ()
const AutocompleteProviderClient * client () const
bool field_trial_triggered () const
void set_field_trial_triggered (bool triggered)
void set_field_trial_triggered_in_session (bool triggered)
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Private Types
typedef std::vector< history::KeywordSearchTermVisit > HistoryResults
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, CanSendURL)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DontInlineAutocompleteAsynchronously)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationInline)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationInlineDomainClassify)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationPrefixClassify)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationMidWordClassify)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationWordBreakClassify)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, NavigationInlineSchemeSubstring)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, SuggestRelevanceExperiment)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, TestDeleteMatch)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, SuggestQueryUsesToken)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, AnswersCache)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, RemoveExtraAnswers)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DoesNotProvideOnFocus)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, SendsWarmUpRequestOnFocus)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DoTrimHttpScheme)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DontTrimHttpSchemeIfInputHasScheme)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DontTrimHttpsSchemeIfInputHasScheme)
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, DoTrimHttpsScheme)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
const TemplateURL * GetTemplateURL (bool is_keyword) const override
const AutocompleteInput GetInput (bool is_keyword) const override
bool ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult &result) const override
void RecordDeletionResult (bool success) override
void OnTemplateURLServiceChanged () override
void OnURLLoadComplete (const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)
void StopSuggest ()
void ClearAllResults ()
void UpdateMatchContentsClass (const std::u16string &input_text, SearchSuggestionParser::Results *results)
void SortResults (bool is_keyword, SearchSuggestionParser::Results *results)
void LogLoadComplete (bool success, bool is_keyword)
void UpdateMatches ()
void EnforceConstraints ()
void RecordTopSuggestion ()
void Run (bool query_is_private)
void DoHistoryQuery (bool minimal_changes)
base::TimeDelta GetSuggestQueryDelay () const
void StartOrStopSuggestQuery (bool minimal_changes)
void CancelLoader (std::unique_ptr< network::SimpleURLLoader > *loader)
bool IsQuerySuitableForSuggest (bool *query_is_private) const
bool IsQueryPotentiallyPrivate () const
void UpdateAllOldResults (bool minimal_changes)
void PersistTopSuggestions (SearchSuggestionParser::Results *results)
void ApplyCalculatedSuggestRelevance (SearchSuggestionParser::SuggestResults *list)
void ApplyCalculatedNavigationRelevance (SearchSuggestionParser::NavigationResults *list)
std::unique_ptr< network::SimpleURLLoader > CreateSuggestLoader (const TemplateURL *template_url, const AutocompleteInput &input, const base::TimeDelta &timeout)
void ConvertResultsToAutocompleteMatches ()
bool IsTopMatchSearchWithURLInput () const
void AddNavigationResultsToMatches (const SearchSuggestionParser::NavigationResults &navigation_results, ACMatches *matches)
void AddRawHistoryResultsToMap (bool is_keyword, int did_not_accept_suggestion, MatchMap *map)
void AddTransformedHistoryResultsToMap (const SearchSuggestionParser::SuggestResults &results, int did_not_accept_suggestion, MatchMap *map)
SearchSuggestionParser::SuggestResults ScoreHistoryResultsHelper (const HistoryResults &results, bool base_prevent_inline_autocomplete, bool input_multiple_words, const std::u16string &input_text, bool is_keyword)
void ScoreHistoryResults (const HistoryResults &results, bool is_keyword, SearchSuggestionParser::SuggestResults *scored_results)
void AddSuggestResultsToMap (const SearchSuggestionParser::SuggestResults &results, const std::string &metadata, MatchMap *map)
int GetVerbatimRelevance (bool *relevance_from_server) const
bool ShouldCurbDefaultSuggestions () const
int CalculateRelevanceForVerbatim () const
int CalculateRelevanceForVerbatimIgnoringKeywordModeState () const
int GetKeywordVerbatimRelevance (bool *relevance_from_server) const
int CalculateRelevanceForHistory (const base::Time &time, bool is_keyword, bool use_aggressive_method, bool prevent_search_history_inlining) const
AutocompleteMatch NavigationToMatch (const SearchSuggestionParser::NavigationResult &navigation)
void UpdateDone ()
AnswersQueryData FindAnswersPrefetchData ()
void PrefetchImages (SearchSuggestionParser::Results *results)
Static Private Member Functions
static void UpdateOldResults (bool minimal_changes, SearchSuggestionParser::Results *results)
static void RemoveExtraAnswers (ACMatches *matches)
Private Attributes
AutocompleteProviderListener * listener_
Providers providers_
AutocompleteInput input_
AutocompleteInput keyword_input_
HistoryResults raw_keyword_history_results_
HistoryResults raw_default_history_results_
SearchSuggestionParser::SuggestResults transformed_keyword_history_results_
SearchSuggestionParser::SuggestResults transformed_default_history_results_
base::OneShotTimer timer_
base::TimeTicks time_suggest_request_sent_
std::unique_ptr< network::SimpleURLLoader > keyword_loader_
std::unique_ptr< network::SimpleURLLoader > default_loader_
SearchSuggestionParser::Results default_results_
SearchSuggestionParser::Results keyword_results_
std::u16string top_query_suggestion_fill_into_edit_
GURL top_navigation_suggestion_
AnswersCache answers_cache_
AnswersQueryData prefetch_data_
base::ScopedObservation< TemplateURLService, TemplateURLServiceObserver > observation_ {this}
Friends
class AutocompleteProviderTest
class BaseSearchProviderTest
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from BaseSearchProvider
typedef std::pair< std::u16string, std::string > MatchKey
typedef std::map< MatchKey, AutocompleteMatch > MatchMap
typedef std::vector< std::unique_ptr< SuggestionDeletionHandler > > SuggestionDeletionHandlers
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Static Protected Member Functions inherited from BaseSearchProvider
static std::u16string GetFillIntoEdit (const SearchSuggestionParser::SuggestResult &suggest_result, const TemplateURL *template_url)
static bool CanSendURL (const GURL &current_page_url, const GURL &suggest_url, const TemplateURL *template_url, metrics::OmniboxEventProto::PageClassification page_classification, const SearchTermsData &search_terms_data, AutocompleteProviderClient *client, bool sending_search_terms)
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Static Protected Attributes inherited from BaseSearchProvider
static const char kRelevanceFromServerKey []
static const char kShouldPrefetchKey [] = "should_prefetch"
static const char kSuggestMetadataKey [] = "suggest_metadata"
static const char kDeletionUrlKey [] = "deletion_url"
static const char kTrue [] = "true"
static const char kFalse [] = "false"
Member Typedef Documentation
HistoryResults
typedef std::vector<history::KeywordSearchTermVisit> SearchProvider::HistoryResults private
Constructor & Destructor Documentation
SearchProvider() [1/2]
SearchProvider::SearchProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener)
References BaseSearchProvider::client(), AutocompleteProviderClient::GetTemplateURLService(), and observation_.
SearchProvider() [2/2]
SearchProvider::SearchProvider (const SearchProvider &) delete
~SearchProvider()
SearchProvider::~SearchProvider () override protected
Member Function Documentation
AddNavigationResultsToMatches()
void SearchProvider::AddNavigationResultsToMatches (const SearchSuggestionParser::NavigationResults & navigation_results, ACMatches * matches) private
References AutocompleteProvider::matches(), and NavigationToMatch().
Referenced by ConvertResultsToAutocompleteMatches().
AddRawHistoryResultsToMap()
void SearchProvider::AddRawHistoryResultsToMap (bool is_keyword, int did_not_accept_suggestion, MatchMap * map) private
References AddTransformedHistoryResultsToMap(), transformed_default_history_results_, and transformed_keyword_history_results_.
Referenced by ConvertResultsToAutocompleteMatches().
AddSuggestResultsToMap()
void SearchProvider::AddSuggestResultsToMap (const SearchSuggestionParser::SuggestResults & results, const std::string & metadata, MatchMap * map) private
References BaseSearchProvider::AddMatchToMap(), SearchProvider::Providers::GetKeywordProviderURL(), and providers_.
Referenced by ConvertResultsToAutocompleteMatches().
AddTransformedHistoryResultsToMap()
void SearchProvider::AddTransformedHistoryResultsToMap (const SearchSuggestionParser::SuggestResults & results, int did_not_accept_suggestion, MatchMap * map) private
References BaseSearchProvider::AddMatchToMap(), SearchProvider::Providers::GetKeywordProviderURL(), and providers_.
Referenced by AddRawHistoryResultsToMap(), and FindAnswersPrefetchData().
ApplyCalculatedNavigationRelevance()
void SearchProvider::ApplyCalculatedNavigationRelevance (SearchSuggestionParser::NavigationResults * list) private
References SearchSuggestionParser::NavigationResult::CalculateRelevance(), SearchProvider::Providers::has_keyword_provider(), input_, providers_, SearchSuggestionParser::Result::set_relevance(), and SearchSuggestionParser::Result::set_relevance_from_server().
Referenced by SortResults().
ApplyCalculatedSuggestRelevance()
void SearchProvider::ApplyCalculatedSuggestRelevance (SearchSuggestionParser::SuggestResults * list) private
References SearchSuggestionParser::SuggestResult::CalculateRelevance(), SearchProvider::Providers::has_keyword_provider(), input_, providers_, SearchSuggestionParser::Result::set_relevance(), and SearchSuggestionParser::Result::set_relevance_from_server().
Referenced by EnforceConstraints(), and SortResults().
CalculateRelevanceForHistory()
int SearchProvider::CalculateRelevanceForHistory (const base::Time & time, bool is_keyword, bool use_aggressive_method, bool prevent_search_history_inlining) const private
References SearchProvider::Providers::has_keyword_provider(), input_, providers_, and AutocompleteInput::type().
Referenced by ScoreHistoryResultsHelper().
CalculateRelevanceForKeywordVerbatim()
int SearchProvider::CalculateRelevanceForKeywordVerbatim (metrics::OmniboxInputType type, bool allow_exact_keyword_match, bool prefer_keyword) static
References AutocompleteProvider::type().
Referenced by KeywordProvider::CalculateRelevance(), and GetKeywordVerbatimRelevance().
CalculateRelevanceForVerbatim()
int SearchProvider::CalculateRelevanceForVerbatim () const private
References CalculateRelevanceForVerbatimIgnoringKeywordModeState(), SearchProvider::Providers::keyword_provider(), and providers_.
Referenced by GetVerbatimRelevance(), and IsTopMatchSearchWithURLInput().
CalculateRelevanceForVerbatimIgnoringKeywordModeState()
int SearchProvider::CalculateRelevanceForVerbatimIgnoringKeywordModeState () const private
References input_, kNonURLVerbatimRelevance, and AutocompleteInput::type().
Referenced by CalculateRelevanceForVerbatim().
CancelLoader()
void SearchProvider::CancelLoader (std::unique_ptr< network::SimpleURLLoader > * loader) private
Referenced by OnTemplateURLServiceChanged(), and StopSuggest().
ClearAllResults()
void SearchProvider::ClearAllResults () private
References SearchSuggestionParser::Results::Clear(), default_results_, and keyword_results_.
Referenced by Start(), StartOrStopSuggestQuery(), and Stop().
ConvertResultsToAutocompleteMatches()
void SearchProvider::ConvertResultsToAutocompleteMatches () private
References BaseSearchProvider::AddMatchToMap(), AddNavigationResultsToMatches(), AddRawHistoryResultsToMap(), AddSuggestResultsToMap(), default_results_, AutocompleteResult::FindTopMatch(), AutocompleteResult::GetDynamicMaxMatches(), SearchProvider::Providers::GetKeywordProviderURL(), GetKeywordVerbatimRelevance(), GetVerbatimRelevance(), input_, keyword_input_, keyword_results_, BaseSearchProvider::kRelevanceFromServerKey, BaseSearchProvider::kTrue, AutocompleteProvider::matches(), AutocompleteProvider::matches_, SearchSuggestionParser::Results::metadata, AutocompleteMatch::MoreRelevant(), SearchSuggestionParser::Results::navigation_results, AutocompleteProvider::provider_max_matches_, providers_, RemoveExtraAnswers(), AutocompleteMatchType::SEARCH_OTHER_ENGINE, AutocompleteMatchType::SEARCH_WHAT_YOU_TYPED, SearchSuggestionParser::SuggestResult::SetAnswer(), ShouldCurbDefaultSuggestions(), SearchSuggestionParser::Results::suggest_results, and AutocompleteInput::text().
Referenced by EnforceConstraints(), and UpdateMatches().
CreateSuggestLoader()
std::unique_ptr< network::SimpleURLLoader > SearchProvider::CreateSuggestLoader (const TemplateURL * template_url, const AutocompleteInput & input, const base::TimeDelta & timeout) private
References BaseSearchProvider::AppendSuggestClientToAdditionalQueryParams(), BaseSearchProvider::CanSendURL(), BaseSearchProvider::client(), AutocompleteInput::current_page_classification(), AutocompleteInput::current_url(), AutocompleteInput::cursor_position(), omnibox::DEFAULT, AutocompleteInput::focus_type(), AnswersQueryData::full_query_text, AutocompleteProviderClient::GetTemplateURLService(), OnURLLoadComplete(), prefetch_data_, AnswersQueryData::query_type, AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by Run().
DoHistoryQuery()
void SearchProvider::DoHistoryQuery (bool minimal_changes) private
References BaseSearchProvider::client(), AutocompleteInput::current_page_classification(), SearchProvider::Providers::GetDefaultProviderURL(), AutocompleteProviderClient::GetInMemoryDatabase(), SearchProvider::Providers::GetKeywordProviderURL(), input_, keyword_input_, AutocompleteProvider::provider_max_matches_, providers_, raw_default_history_results_, raw_keyword_history_results_, OmniboxFieldTrial::SearchHistoryDisable(), and AutocompleteInput::text().
Referenced by Start().
EnforceConstraints()
void SearchProvider::EnforceConstraints () private
References ApplyCalculatedSuggestRelevance(), ConvertResultsToAutocompleteMatches(), default_results_, AutocompleteResult::FindTopMatch(), SearchProvider::Providers::GetKeywordProviderURL(), SearchSuggestionParser::Results::HasServerProvidedScores(), input_, IsTopMatchSearchWithURLInput(), keyword_results_, AutocompleteProvider::matches_, providers_, SearchSuggestionParser::Results::suggest_results, and SearchSuggestionParser::Results::verbatim_relevance.
Referenced by UpdateMatches().
FindAnswersPrefetchData()
AnswersQueryData SearchProvider::FindAnswersPrefetchData () private
References AddTransformedHistoryResultsToMap(), answers_cache_, AnswersCache::GetTopAnswerEntry(), AutocompleteProvider::matches(), AutocompleteMatch::MoreRelevant(), transformed_default_history_results_, and transformed_keyword_history_results_.
Referenced by Start().
FRIEND_TEST_ALL_PREFIXES() [1/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , AnswersCache) private
FRIEND_TEST_ALL_PREFIXES() [2/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , CanSendURL) private
FRIEND_TEST_ALL_PREFIXES() [3/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DoesNotProvideOnFocus) private
FRIEND_TEST_ALL_PREFIXES() [4/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DontInlineAutocompleteAsynchronously) private
FRIEND_TEST_ALL_PREFIXES() [5/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DontTrimHttpSchemeIfInputHasScheme) private
FRIEND_TEST_ALL_PREFIXES() [6/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DontTrimHttpsSchemeIfInputHasScheme) private
FRIEND_TEST_ALL_PREFIXES() [7/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DoTrimHttpScheme) private
FRIEND_TEST_ALL_PREFIXES() [8/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , DoTrimHttpsScheme) private
FRIEND_TEST_ALL_PREFIXES() [9/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationInline) private
FRIEND_TEST_ALL_PREFIXES() [10/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationInlineDomainClassify) private
FRIEND_TEST_ALL_PREFIXES() [11/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationInlineSchemeSubstring) private
FRIEND_TEST_ALL_PREFIXES() [12/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationMidWordClassify) private
FRIEND_TEST_ALL_PREFIXES() [13/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationPrefixClassify) private
FRIEND_TEST_ALL_PREFIXES() [14/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , NavigationWordBreakClassify) private
FRIEND_TEST_ALL_PREFIXES() [15/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , RemoveExtraAnswers) private
FRIEND_TEST_ALL_PREFIXES() [16/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , SendsWarmUpRequestOnFocus) private
FRIEND_TEST_ALL_PREFIXES() [17/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , SuggestQueryUsesToken) private
FRIEND_TEST_ALL_PREFIXES() [18/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , SuggestRelevanceExperiment) private
FRIEND_TEST_ALL_PREFIXES() [19/19]
SearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , TestDeleteMatch) private
GetInput()
const AutocompleteInput SearchProvider::GetInput (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References input_, and keyword_input_.
Referenced by ScoreHistoryResults().
GetKeywordVerbatimRelevance()
int SearchProvider::GetKeywordVerbatimRelevance (bool * relevance_from_server) const private
References CalculateRelevanceForKeywordVerbatim(), input_, keyword_input_, keyword_results_, SearchSuggestionParser::Results::navigation_results, AutocompleteInput::prefer_keyword(), AutocompleteInput::prevent_inline_autocomplete(), SearchSuggestionParser::Results::suggest_results, AutocompleteInput::type(), and SearchSuggestionParser::Results::verbatim_relevance.
Referenced by ConvertResultsToAutocompleteMatches().
GetSuggestMetadata()
std::string SearchProvider::GetSuggestMetadata (const AutocompleteMatch & match) static
References AutocompleteMatch::GetAdditionalInfo(), and BaseSearchProvider::kSuggestMetadataKey.
GetSuggestQueryDelay()
base::TimeDelta SearchProvider::GetSuggestQueryDelay () const private
References OmniboxFieldTrial::GetSuggestPollingStrategy(), and time_suggest_request_sent_.
Referenced by StartOrStopSuggestQuery().
GetTemplateURL()
const TemplateURL * SearchProvider::GetTemplateURL (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References SearchProvider::Providers::GetDefaultProviderURL(), SearchProvider::Providers::GetKeywordProviderURL(), and providers_.
Referenced by OnURLLoadComplete().
GetVerbatimRelevance()
int SearchProvider::GetVerbatimRelevance (bool * relevance_from_server) const private
References CalculateRelevanceForVerbatim(), default_results_, input_, SearchSuggestionParser::Results::navigation_results, AutocompleteInput::prevent_inline_autocomplete(), SearchSuggestionParser::Results::suggest_results, and SearchSuggestionParser::Results::verbatim_relevance.
Referenced by ConvertResultsToAutocompleteMatches().
IsQueryPotentiallyPrivate()
bool SearchProvider::IsQueryPotentiallyPrivate () const private
References input_, AutocompleteInput::parts(), AutocompleteInput::scheme(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by IsQuerySuitableForSuggest().
IsQuerySuitableForSuggest()
bool SearchProvider::IsQuerySuitableForSuggest (bool * query_is_private) const private
References BaseSearchProvider::client(), SearchProvider::Providers::GetDefaultProviderURL(), SearchProvider::Providers::GetKeywordProviderURL(), AutocompleteProviderClient::IsOffTheRecord(), IsQueryPotentiallyPrivate(), providers_, and AutocompleteProviderClient::SearchSuggestEnabled().
Referenced by StartOrStopSuggestQuery().
IsTopMatchSearchWithURLInput()
bool SearchProvider::IsTopMatchSearchWithURLInput () const private
References CalculateRelevanceForVerbatim(), AutocompleteResult::FindTopMatch(), input_, AutocompleteProvider::matches_, AutocompleteMatchType::NAVSUGGEST, AutocompleteMatchType::NAVSUGGEST_PERSONALIZED, and AutocompleteInput::type().
Referenced by EnforceConstraints().
LogLoadComplete()
void SearchProvider::LogLoadComplete (bool success, bool is_keyword) private
References BaseSearchProvider::client(), SearchProvider::Providers::GetDefaultProviderURL(), providers_, and time_suggest_request_sent_.
Referenced by OnURLLoadComplete().
NavigationToMatch()
AutocompleteMatch SearchProvider::NavigationToMatch (const SearchSuggestionParser::NavigationResult & navigation) private
References AutocompleteMatch::allowed_to_be_default_match, URLPrefix::BestURLPrefix(), BaseSearchProvider::client(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, SearchSuggestionParser::Result::deletion_url(), AutocompleteMatch::description, SearchSuggestionParser::NavigationResult::description(), AutocompleteMatch::description_class, SearchSuggestionParser::NavigationResult::description_class(), AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, SearchSuggestionParser::NavigationResult::formatted_url(), AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::from_keyword, SearchSuggestionParser::Result::from_keyword(), SearchProvider::Providers::GetKeywordProviderURL(), AutocompleteInput::HasHTTPScheme(), AutocompleteMatch::inline_autocompletion, input_, keyword_input_, BaseSearchProvider::kFalse, BaseSearchProvider::kRelevanceFromServerKey, BaseSearchProvider::kShouldPrefetchKey, BaseSearchProvider::kTrue, SearchSuggestionParser::Result::match_contents(), SearchSuggestionParser::Result::match_contents_class(), URLPrefix::prefix, AutocompleteInput::prevent_inline_autocomplete(), providers_, SearchSuggestionParser::Result::received_after_last_keystroke(), AutocompleteMatch::RecordAdditionalInfo(), SearchSuggestionParser::Result::relevance(), SearchSuggestionParser::Result::relevance_from_server(), BaseSearchProvider::SetDeletionURL(), AutocompleteMatch::subtypes, SearchSuggestionParser::Result::subtypes(), AutocompleteInput::text(), SearchSuggestionParser::Result::type(), and SearchSuggestionParser::NavigationResult::url().
Referenced by AddNavigationResultsToMatches().
OnTemplateURLServiceChanged()
void SearchProvider::OnTemplateURLServiceChanged () override private
References CancelLoader(), SearchSuggestionParser::Results::Clear(), BaseSearchProvider::client(), default_loader_, SearchProvider::Providers::default_provider(), default_results_, AutocompleteProvider::done_, SearchProvider::Providers::GetDefaultProviderURL(), SearchProvider::Providers::GetKeywordProviderURL(), AutocompleteProviderClient::GetTemplateURLService(), keyword_loader_, SearchProvider::Providers::keyword_provider(), keyword_results_, listener_, AutocompleteProviderListener::OnProviderUpdate(), providers_, SearchProvider::Providers::set(), and UpdateMatches().
OnURLLoadComplete()
void SearchProvider::OnURLLoadComplete (const network::SimpleURLLoader * source, std::unique_ptr< std::string > response_body) private
References omnibox::DEFAULT, default_loader_, default_results_, SearchSuggestionParser::DeserializeJsonData(), AutocompleteProvider::done_, SearchSuggestionParser::ExtractJsonData(), AutocompleteInput::focus_type(), GetTemplateURL(), input_, keyword_loader_, keyword_results_, listener_, LogLoadComplete(), AutocompleteProviderListener::OnProviderUpdate(), BaseSearchProvider::ParseSuggestResults(), PrefetchImages(), SortResults(), and UpdateMatches().
Referenced by CreateSuggestLoader().
operator=()
SearchProvider& SearchProvider::operator= (const SearchProvider &) delete
PersistTopSuggestions()
void SearchProvider::PersistTopSuggestions (SearchSuggestionParser::Results * results) private
References BaseSearchProvider::GetFillIntoEdit(), SearchProvider::Providers::GetKeywordProviderURL(), SearchSuggestionParser::Results::navigation_results, providers_, SearchSuggestionParser::Results::suggest_results, top_navigation_suggestion_, and top_query_suggestion_fill_into_edit_.
Referenced by UpdateMatches().
PrefetchImages()
void SearchProvider::PrefetchImages (SearchSuggestionParser::Results * results) private
References BaseSearchProvider::client(), AutocompleteResult::GetDynamicMaxMatches(), AutocompleteResult::kMaxAutocompletePositionValue, AutocompleteProviderClient::PrefetchImage(), and SearchSuggestionParser::Results::suggest_results.
Referenced by OnURLLoadComplete().
RecordDeletionResult()
void SearchProvider::RecordDeletionResult (bool success) override private virtual
Implements BaseSearchProvider.
RecordTopSuggestion()
void SearchProvider::RecordTopSuggestion () private
References AutocompleteResult::FindTopMatch(), input_, AutocompleteMatch::IsSearchType(), AutocompleteProvider::matches_, top_navigation_suggestion_, and top_query_suggestion_fill_into_edit_.
Referenced by UpdateMatches().
RegisterDisplayedAnswers()
void SearchProvider::RegisterDisplayedAnswers (const AutocompleteResult & result)
References answers_cache_, AutocompleteResult::begin(), AutocompleteResult::empty(), AutocompleteResult::size(), and AnswersCache::UpdateRecentAnswers().
Referenced by AutocompleteController::UpdateResult().
RemoveExtraAnswers()
void SearchProvider::RemoveExtraAnswers (ACMatches * matches) static private
References AutocompleteProvider::matches().
Referenced by ConvertResultsToAutocompleteMatches().
ResetSession()
void SearchProvider::ResetSession () override virtual
Reimplemented from AutocompleteProvider.
References BaseSearchProvider::set_field_trial_triggered(), and BaseSearchProvider::set_field_trial_triggered_in_session().
Run()
void SearchProvider::Run (bool query_is_private) private
References BaseSearchProvider::client(), CreateSuggestLoader(), default_loader_, AutocompleteProvider::done_, SearchProvider::Providers::GetDefaultProviderURL(), SearchProvider::Providers::GetKeywordProviderURL(), input_, keyword_input_, keyword_loader_, listener_, OmniboxFieldTrial::OnDeviceSearchProviderDefaultLoaderTimeoutMs(), AutocompleteProviderListener::OnProviderUpdate(), providers_, time_suggest_request_sent_, and UpdateDone().
Referenced by StartOrStopSuggestQuery().
ScoreHistoryResults()
void SearchProvider::ScoreHistoryResults (const HistoryResults & results, bool is_keyword, SearchSuggestionParser::SuggestResults * scored_results) private
References GetInput(), input_, AutocompleteInput::prevent_inline_autocomplete(), ScoreHistoryResultsHelper(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by Start().
ScoreHistoryResultsHelper()
SearchSuggestionParser::SuggestResults SearchProvider::ScoreHistoryResultsHelper (const HistoryResults & results, bool base_prevent_inline_autocomplete, bool input_multiple_words, const std::u16string & input_text, bool is_keyword) private
References CalculateRelevanceForHistory(), AutocompleteProviderClient::Classify(), BaseSearchProvider::client(), AutocompleteInput::current_page_classification(), input_, AutocompleteMatch::IsSearchType(), AutocompleteMatchType::SEARCH_HISTORY, OmniboxFieldTrial::SearchHistoryPreventInlining(), SearchSuggestionParser::Result::set_received_after_last_keystroke(), and AutocompleteMatch::type.
Referenced by ScoreHistoryResults().
ShouldAppendExtraParams()
bool SearchProvider::ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult & result) const override private virtual
Implements BaseSearchProvider.
References SearchProvider::Providers::default_provider(), SearchSuggestionParser::Result::from_keyword(), and providers_.
ShouldCurbDefaultSuggestions()
bool SearchProvider::ShouldCurbDefaultSuggestions () const private
References SearchProvider::Providers::has_keyword_provider(), AutocompleteProvider::InExplicitExperimentalKeywordMode(), input_, SearchProvider::Providers::keyword_provider(), and providers_.
Referenced by ConvertResultsToAutocompleteMatches().
SortResults()
void SearchProvider::SortResults (bool is_keyword, SearchSuggestionParser::Results * results) private
References ApplyCalculatedNavigationRelevance(), ApplyCalculatedSuggestRelevance(), SearchProvider::Providers::keyword_provider(), SearchSuggestionParser::Results::navigation_results, providers_, SearchSuggestionParser::Results::relevances_from_server, SearchSuggestionParser::Results::suggest_results, and SearchSuggestionParser::Results::verbatim_relevance.
Referenced by OnURLLoadComplete().
Start()
void SearchProvider::Start (const AutocompleteInput & input, bool minimal_changes) override private virtual
Implements AutocompleteProvider.
References AutocompleteMatch::allowed_to_be_default_match, AutocompleteInput::Clear(), ClearAllResults(), BaseSearchProvider::client(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, omnibox::DEFAULT, SearchProvider::Providers::default_provider(), DoHistoryQuery(), AutocompleteProvider::done_, SearchProvider::Providers::equal(), FindAnswersPrefetchData(), AutocompleteInput::focus_type(), KeywordProvider::GetSubstitutingTemplateURLForInput(), AutocompleteProviderClient::GetTemplateURLService(), input_, AutocompleteMatch::keyword, keyword_input_, AutocompleteProvider::matches_, AutocompleteMatch::ACMatchClassification::NONE, prefetch_data_, AutocompleteMatch::provider, providers_, raw_default_history_results_, raw_keyword_history_results_, ScoreHistoryResults(), SearchProvider::Providers::set(), BaseSearchProvider::set_field_trial_triggered(), StartOrStopSuggestQuery(), Stop(), AutocompleteInput::text(), transformed_default_history_results_, transformed_keyword_history_results_, and UpdateMatches().
StartOrStopSuggestQuery()
void SearchProvider::StartOrStopSuggestQuery (bool minimal_changes) private
References ClearAllResults(), default_results_, AutocompleteProvider::done_, GetSuggestQueryDelay(), input_, IsQuerySuitableForSuggest(), keyword_input_, keyword_results_, SearchSuggestionParser::Results::navigation_results, Run(), StopSuggest(), SearchSuggestionParser::Results::suggest_results, AutocompleteInput::text(), timer_, UpdateAllOldResults(), UpdateMatchContentsClass(), and AutocompleteInput::want_asynchronous_matches().
Referenced by Start().
Stop()
void SearchProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override private virtual
Reimplemented from AutocompleteProvider.
References ClearAllResults(), AutocompleteProvider::done_, and StopSuggest().
Referenced by Start().
StopSuggest()
void SearchProvider::StopSuggest () private
References CancelLoader(), default_loader_, keyword_loader_, and timer_.
Referenced by StartOrStopSuggestQuery(), and Stop().
UpdateAllOldResults()
void SearchProvider::UpdateAllOldResults (bool minimal_changes) private
References SearchSuggestionParser::Results::Clear(), default_results_, keyword_input_, keyword_results_, AutocompleteInput::text(), and UpdateOldResults().
Referenced by StartOrStopSuggestQuery().
UpdateDone()
void SearchProvider::UpdateDone () private
References default_loader_, AutocompleteProvider::done_, keyword_loader_, and timer_.
Referenced by Run(), and UpdateMatches().
UpdateMatchContentsClass()
void SearchProvider::UpdateMatchContentsClass (const std::u16string & input_text, SearchSuggestionParser::Results * results) private
References SearchSuggestionParser::Results::navigation_results, and SearchSuggestionParser::Results::suggest_results.
Referenced by StartOrStopSuggestQuery().
UpdateMatches()
void SearchProvider::UpdateMatches () private
References ConvertResultsToAutocompleteMatches(), omnibox::DEFAULT, default_results_, EnforceConstraints(), AutocompleteInput::focus_type(), input_, keyword_results_, AutocompleteProvider::matches_, PersistTopSuggestions(), RecordTopSuggestion(), and UpdateDone().
Referenced by OnTemplateURLServiceChanged(), OnURLLoadComplete(), and Start().
UpdateOldResults()
void SearchProvider::UpdateOldResults (bool minimal_changes, SearchSuggestionParser::Results * results) static private
References AutocompleteMatchType::CALCULATOR, SearchSuggestionParser::Results::navigation_results, and SearchSuggestionParser::Results::suggest_results.
Referenced by UpdateAllOldResults().
Friends And Related Function Documentation
AutocompleteProviderTest
friend class AutocompleteProviderTest friend
BaseSearchProviderTest
friend class BaseSearchProviderTest friend
Member Data Documentation
answers_cache_
AnswersCache SearchProvider::answers_cache_ private
Referenced by FindAnswersPrefetchData(), and RegisterDisplayedAnswers().
default_loader_
std::unique_ptr<network::SimpleURLLoader> SearchProvider::default_loader_ private
Referenced by OnTemplateURLServiceChanged(), OnURLLoadComplete(), Run(), StopSuggest(), and UpdateDone().
default_results_
SearchSuggestionParser::Results SearchProvider::default_results_ private
Referenced by ClearAllResults(), ConvertResultsToAutocompleteMatches(), EnforceConstraints(), GetVerbatimRelevance(), OnTemplateURLServiceChanged(), OnURLLoadComplete(), StartOrStopSuggestQuery(), UpdateAllOldResults(), and UpdateMatches().
input_
AutocompleteInput SearchProvider::input_ private
Referenced by ApplyCalculatedNavigationRelevance(), ApplyCalculatedSuggestRelevance(), CalculateRelevanceForHistory(), CalculateRelevanceForVerbatimIgnoringKeywordModeState(), ConvertResultsToAutocompleteMatches(), DoHistoryQuery(), EnforceConstraints(), GetInput(), GetKeywordVerbatimRelevance(), GetVerbatimRelevance(), IsQueryPotentiallyPrivate(), IsTopMatchSearchWithURLInput(), NavigationToMatch(), OnURLLoadComplete(), RecordTopSuggestion(), Run(), ScoreHistoryResults(), ScoreHistoryResultsHelper(), ShouldCurbDefaultSuggestions(), Start(), StartOrStopSuggestQuery(), and UpdateMatches().
keyword_input_
AutocompleteInput SearchProvider::keyword_input_ private
Referenced by ConvertResultsToAutocompleteMatches(), DoHistoryQuery(), GetInput(), GetKeywordVerbatimRelevance(), NavigationToMatch(), Run(), Start(), StartOrStopSuggestQuery(), and UpdateAllOldResults().
keyword_loader_
std::unique_ptr<network::SimpleURLLoader> SearchProvider::keyword_loader_ private
Referenced by OnTemplateURLServiceChanged(), OnURLLoadComplete(), Run(), StopSuggest(), and UpdateDone().
keyword_results_
SearchSuggestionParser::Results SearchProvider::keyword_results_ private
Referenced by ClearAllResults(), ConvertResultsToAutocompleteMatches(), EnforceConstraints(), GetKeywordVerbatimRelevance(), OnTemplateURLServiceChanged(), OnURLLoadComplete(), StartOrStopSuggestQuery(), UpdateAllOldResults(), and UpdateMatches().
kNonURLVerbatimRelevance
const int SearchProvider::kNonURLVerbatimRelevance = 1300 static
Referenced by CalculateRelevanceForVerbatimIgnoringKeywordModeState().
listener_
AutocompleteProviderListener* SearchProvider::listener_ private
Referenced by OnTemplateURLServiceChanged(), OnURLLoadComplete(), and Run().
observation_
base::ScopedObservation<TemplateURLService, TemplateURLServiceObserver> SearchProvider::observation_ {this} private
Referenced by SearchProvider().
prefetch_data_
AnswersQueryData SearchProvider::prefetch_data_ private
Referenced by CreateSuggestLoader(), and Start().
providers_
Providers SearchProvider::providers_ private
Referenced by AddSuggestResultsToMap(), AddTransformedHistoryResultsToMap(), ApplyCalculatedNavigationRelevance(), ApplyCalculatedSuggestRelevance(), CalculateRelevanceForHistory(), CalculateRelevanceForVerbatim(), ConvertResultsToAutocompleteMatches(), DoHistoryQuery(), EnforceConstraints(), GetTemplateURL(), IsQuerySuitableForSuggest(), LogLoadComplete(), NavigationToMatch(), OnTemplateURLServiceChanged(), PersistTopSuggestions(), Run(), ShouldAppendExtraParams(), ShouldCurbDefaultSuggestions(), SortResults(), and Start().
raw_default_history_results_
HistoryResults SearchProvider::raw_default_history_results_ private
Referenced by DoHistoryQuery(), and Start().
raw_keyword_history_results_
HistoryResults SearchProvider::raw_keyword_history_results_ private
Referenced by DoHistoryQuery(), and Start().
time_suggest_request_sent_
base::TimeTicks SearchProvider::time_suggest_request_sent_ private
Referenced by GetSuggestQueryDelay(), LogLoadComplete(), and Run().
timer_
base::OneShotTimer SearchProvider::timer_ private
Referenced by StartOrStopSuggestQuery(), StopSuggest(), and UpdateDone().
top_navigation_suggestion_
GURL SearchProvider::top_navigation_suggestion_ private
Referenced by PersistTopSuggestions(), and RecordTopSuggestion().
top_query_suggestion_fill_into_edit_
std::u16string SearchProvider::top_query_suggestion_fill_into_edit_ private
Referenced by PersistTopSuggestions(), and RecordTopSuggestion().
transformed_default_history_results_
SearchSuggestionParser::SuggestResults SearchProvider::transformed_default_history_results_ private
Referenced by AddRawHistoryResultsToMap(), FindAnswersPrefetchData(), and Start().
transformed_keyword_history_results_
SearchSuggestionParser::SuggestResults SearchProvider::transformed_keyword_history_results_ private
Referenced by AddRawHistoryResultsToMap(), FindAnswersPrefetchData(), and Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/search_provider.h
components/omnibox/browser/search_provider.cc