Chromium Omnibox: OmniboxController Class Reference
OmniboxController Class Reference
#include <omnibox_controller.h>
Public Member Functions
OmniboxController (OmniboxEditModel *omnibox_edit_model, OmniboxClient *client)
~OmniboxController () override
OmniboxController (const OmniboxController &)=delete
OmniboxController & operator= (const OmniboxController &)=delete
void StartAutocomplete (const AutocompleteInput &input) const
void OnResultChanged (AutocompleteController *controller, bool default_match_changed) override
AutocompleteController * autocomplete_controller ()
void InvalidateCurrentMatch ()
const AutocompleteMatch & current_match () const
void ClearPopupKeywordMode () const
const AutocompleteResult & result () const
Public Member Functions inherited from AutocompleteController::Observer
virtual void OnStart (AutocompleteController *controller, const AutocompleteInput &input)
Private Member Functions
void SetRichSuggestionBitmap (int result_index, const SkBitmap &bitmap)
Private Attributes
OmniboxEditModel * omnibox_edit_model_
OmniboxClient * client_
std::unique_ptr< AutocompleteController > autocomplete_controller_
AutocompleteMatch current_match_
base::WeakPtrFactory< OmniboxController > weak_ptr_factory_ {this}
Constructor & Destructor Documentation
OmniboxController() [1/2]
OmniboxController::OmniboxController (OmniboxEditModel * omnibox_edit_model, OmniboxClient * client)
References autocomplete_controller_, client_, and OmniboxClient::GetOmniboxControllerEmitter().
Referenced by OmniboxEditModel::OmniboxEditModel().
~OmniboxController()
OmniboxController::~OmniboxController () override
OmniboxController() [2/2]
OmniboxController::OmniboxController (const OmniboxController &) delete
Member Function Documentation
autocomplete_controller()
AutocompleteController* OmniboxController::autocomplete_controller () inline
References autocomplete_controller_.
ClearPopupKeywordMode()
void OmniboxController::ClearPopupKeywordMode () const
References OmniboxEditModel::GetPopupSelection(), OmniboxPopupSelection::KEYWORD_MODE, OmniboxPopupSelection::NORMAL, omnibox_edit_model_, OmniboxEditModel::PopupIsOpen(), OmniboxEditModel::SetPopupSelection(), and OmniboxPopupSelection::state.
Referenced by StartAutocomplete().
current_match()
const AutocompleteMatch& OmniboxController::current_match () const inline
References current_match_.
InvalidateCurrentMatch()
void OmniboxController::InvalidateCurrentMatch ()
References current_match_.
Referenced by OnResultChanged().
OnResultChanged()
void OmniboxController::OnResultChanged (AutocompleteController * controller, bool default_match_changed) override virtual
Reimplemented from AutocompleteController::Observer.
References OmniboxEditModel::AcceptTemporaryTextAsUserText(), autocomplete_controller_, OmniboxEditModel::ClearAdditionalText(), client_, current_match_, InvalidateCurrentMatch(), omnibox_edit_model_, OmniboxEditModel::OnCurrentMatchChanged(), OmniboxEditModel::OnPopupDataChanged(), OmniboxEditModel::OnPopupResultChanged(), OmniboxClient::OnResultChanged(), OmniboxEditModel::PopupIsOpen(), result(), SetRichSuggestionBitmap(), and weak_ptr_factory_.
operator=()
OmniboxController& OmniboxController::operator= (const OmniboxController &) delete
result()
const AutocompleteResult& OmniboxController::result () const inline
References autocomplete_controller_.
Referenced by OnResultChanged().
SetRichSuggestionBitmap()
void OmniboxController::SetRichSuggestionBitmap (int result_index, const SkBitmap & bitmap) private
References omnibox_edit_model_, and OmniboxEditModel::SetPopupRichSuggestionBitmap().
Referenced by OnResultChanged().
StartAutocomplete()
void OmniboxController::StartAutocomplete (const AutocompleteInput & input) const
References autocomplete_controller_, and ClearPopupKeywordMode().
Member Data Documentation
autocomplete_controller_
std::unique_ptr<AutocompleteController> OmniboxController::autocomplete_controller_ private
Referenced by autocomplete_controller(), OmniboxController(), OnResultChanged(), result(), and StartAutocomplete().
client_
OmniboxClient* OmniboxController::client_ private
Referenced by OmniboxController(), and OnResultChanged().
current_match_
AutocompleteMatch OmniboxController::current_match_ private
Referenced by current_match(), InvalidateCurrentMatch(), and OnResultChanged().
omnibox_edit_model_
OmniboxEditModel* OmniboxController::omnibox_edit_model_ private
Referenced by ClearPopupKeywordMode(), OnResultChanged(), and SetRichSuggestionBitmap().
weak_ptr_factory_
base::WeakPtrFactory<OmniboxController> OmniboxController::weak_ptr_factory_ {this} private
Referenced by OnResultChanged().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_controller.h
components/omnibox/browser/omnibox_controller.cc