Chromium Omnibox: OmniboxPedal::SynonymGroup Class Reference
OmniboxPedal::SynonymGroup Class Reference
#include <omnibox_pedal.h>
Public Member Functions
SynonymGroup (bool required, bool match_once, size_t reserve_size)
SynonymGroup (SynonymGroup &&)
~SynonymGroup ()
SynonymGroup (const SynonymGroup &)=delete
SynonymGroup & operator= (const SynonymGroup &)=delete
SynonymGroup & operator= (SynonymGroup &&)
bool EraseMatchesIn (TokenSequence &remaining, bool fully_erase) const
void AddSynonym (TokenSequence synonym)
void SortSynonyms ()
size_t EstimateMemoryUsage () const
void EraseIgnoreGroup (const SynonymGroup &ignore_group)
bool IsValid () const
Protected Attributes
bool required_
bool match_once_
std::vector< TokenSequence > synonyms_
Constructor & Destructor Documentation
SynonymGroup() [1/3]
OmniboxPedal::SynonymGroup::SynonymGroup (bool required, bool match_once, size_t reserve_size)
References synonyms_.
SynonymGroup() [2/3]
OmniboxPedal::SynonymGroup::SynonymGroup (SynonymGroup &&) default
~SynonymGroup()
OmniboxPedal::SynonymGroup::~SynonymGroup () default
SynonymGroup() [3/3]
OmniboxPedal::SynonymGroup::SynonymGroup (const SynonymGroup &) delete
Member Function Documentation
AddSynonym()
void OmniboxPedal::SynonymGroup::AddSynonym (OmniboxPedal::TokenSequence synonym)
References OmniboxFieldTrial::IsPedalsTranslationConsoleEnabled(), and OmniboxPedal::TokenSequence::Size().
Referenced by OmniboxPedal::AddVerbatimSequence(), OmniboxPedalProvider::LoadSynonymGroupString(), and OmniboxPedalProvider::LoadSynonymGroupValue().
EraseIgnoreGroup()
void OmniboxPedal::SynonymGroup::EraseIgnoreGroup (const SynonymGroup & ignore_group)
References EraseMatchesIn().
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
EraseMatchesIn()
bool OmniboxPedal::SynonymGroup::EraseMatchesIn (OmniboxPedal::TokenSequence & remaining, bool fully_erase) const
References OmniboxPedal::TokenSequence::Consume(), and OmniboxPedal::TokenSequence::Erase().
Referenced by EraseIgnoreGroup(), OmniboxPedalProvider::FindPedalMatch(), OmniboxPedal::IsConceptMatch(), and OmniboxPedalProvider::LoadPedalConcepts().
EstimateMemoryUsage()
size_t OmniboxPedal::SynonymGroup::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage().
IsValid()
bool OmniboxPedal::SynonymGroup::IsValid () const
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
operator=() [1/2]
SynonymGroup& OmniboxPedal::SynonymGroup::operator= (const SynonymGroup &) delete
operator=() [2/2]
OmniboxPedal::SynonymGroup & OmniboxPedal::SynonymGroup::operator= (SynonymGroup &&) default
SortSynonyms()
void OmniboxPedal::SynonymGroup::SortSynonyms ()
Referenced by OmniboxPedalProvider::LoadSynonymGroupString().
Member Data Documentation
match_once_
bool OmniboxPedal::SynonymGroup::match_once_ protected
required_
bool OmniboxPedal::SynonymGroup::required_ protected
synonyms_
std::vector<TokenSequence> OmniboxPedal::SynonymGroup::synonyms_ protected
Referenced by SynonymGroup().
The documentation for this class was generated from the following files:
components/omnibox/browser/actions/omnibox_pedal.h
components/omnibox/browser/actions/omnibox_pedal.cc