Chromium Omnibox: OmniboxResultView Class Reference
OmniboxResultView Class Reference
#include <omnibox_result_view.h>
Public Member Functions
METADATA_HEADER (OmniboxResultView)
OmniboxResultView (OmniboxPopupContentsView *popup_contents_view, OmniboxEditModel *model, size_t model_index)
OmniboxResultView (const OmniboxResultView &)=delete
OmniboxResultView & operator= (const OmniboxResultView &)=delete
~OmniboxResultView () override
SkColor GetColor (OmniboxPart part) const
void SetMatch (const AutocompleteMatch &match)
void ShowKeywordSlideAnimation (bool show_keyword)
void ApplyThemeAndRefreshIcons (bool force_reapply_styles=false)
void OnSelectionStateChanged ()
bool GetMatchSelected () const
views::Button * GetActiveAuxiliaryButtonForAccessibility ()
OmniboxPartState GetThemeState () const
void OnMatchIconUpdated ()
void SetRichSuggestionImage (const gfx::ImageSkia &image)
void ButtonPressed (OmniboxPopupSelection::LineState state, const ui::Event &event)
void EmitTextChangedAccessiblityEvent ()
bool OnMousePressed (const ui::MouseEvent &event) override
bool OnMouseDragged (const ui::MouseEvent &event) override
void OnMouseReleased (const ui::MouseEvent &event) override
void OnMouseEntered (const ui::MouseEvent &event) override
void OnMouseExited (const ui::MouseEvent &event) override
void GetAccessibleNodeData (ui::AXNodeData *node_data) override
void OnThemeChanged () override
Static Public Member Functions
static std::unique_ptr< views::Background > GetPopupCellBackground (views::View *view, OmniboxPartState part_state)
Private Member Functions
gfx::Image GetIcon () const
void UpdateHoverState ()
void UpdateRemoveSuggestionVisibility ()
void SetWidths ()
void OnBoundsChanged (const gfx::Rect &previous_bounds) override
void AnimationProgressed (const gfx::Animation *animation) override
Private Attributes
OmniboxPopupContentsView *const popup_contents_view_
OmniboxEditModel * model_
size_t model_index_
AutocompleteMatch match_
std::u16string accessible_name_
std::unique_ptr< gfx::SlideAnimation > keyword_slide_animation_
views::View * suggestion_container_
OmniboxMatchCellView * suggestion_view_
OmniboxMatchCellView * keyword_view_
OmniboxResultSelectionIndicator * selection_indicator_ = nullptr
views::ImageButton * remove_suggestion_button_
OmniboxSuggestionButtonRowView * button_row_ = nullptr
OmniboxMouseEnterExitHandler mouse_enter_exit_handler_
base::WeakPtrFactory< OmniboxResultView > weak_factory_ {this}
Constructor & Destructor Documentation
OmniboxResultView() [1/2]
END_METADATA OmniboxResultView::OmniboxResultView (OmniboxPopupContentsView * popup_contents_view, OmniboxEditModel * model, size_t model_index)
References button_row_, ButtonPressed(), OmniboxPopupSelection::FOCUSED_BUTTON_REMOVE_SUGGESTION, GetMatchSelected(), OmniboxPopupContentsView::GetSelection(), OmniboxMatchCellView::icon(), keyword_view_, OmniboxMatchCellView::kMarginRight, model_, mouse_enter_exit_handler_, OmniboxMouseEnterExitHandler::ObserveMouseEnterExitOn(), OmniboxMatchCellView::OmniboxMatchCellView(), OmniboxResultSelectionIndicator::OmniboxResultSelectionIndicator(), OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView(), popup_contents_view_, remove_suggestion_button_, selection_indicator_, OmniboxPopupSelection::state, suggestion_container_, and suggestion_view_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
OmniboxResultView() [2/2]
OmniboxResultView::OmniboxResultView (const OmniboxResultView &) delete
~OmniboxResultView()
OmniboxResultView::~OmniboxResultView () override
Member Function Documentation
AnimationProgressed()
void OmniboxResultView::AnimationProgressed (const gfx::Animation * animation) override private
References SetWidths().
ApplyThemeAndRefreshIcons()
void OmniboxResultView::ApplyThemeAndRefreshIcons (bool force_reapply_styles = false)
References AutocompleteMatch::answer, OmniboxTextView::ApplyTextColor(), button_row_, OmniboxMatchCellView::content(), OmniboxMatchCellView::description(), GetColor(), GetIcon(), GetMatchSelected(), GetOmniboxColor(), GetPopupCellBackground(), OmniboxPopupContentsView::GetSelection(), GetThemeState(), OmniboxMatchCellView::icon(), keyword_view_, match_, OmniboxPopupSelection::NORMAL, OmniboxSuggestionButtonRowView::OnOmniboxBackgroundChange(), popup_contents_view_, OmniboxTextView::ReapplyStyling(), remove_suggestion_button_, RESULTS_BACKGROUND, RESULTS_ICON, RESULTS_TEXT_DEFAULT, RESULTS_TEXT_DIMMED, AutocompleteMatchType::SEARCH_SUGGEST_ENTITY, selection_indicator_, OmniboxMatchCellView::separator(), OmniboxPopupSelection::state, suggestion_view_, and AutocompleteMatch::type.
Referenced by OnMatchIconUpdated(), OnSelectionStateChanged(), OnThemeChanged(), SetMatch(), and UpdateHoverState().
ButtonPressed()
void OmniboxResultView::ButtonPressed (OmniboxPopupSelection::LineState state, const ui::Event & event)
References model_, model_index_, and OmniboxEditModel::TriggerPopupSelectionAction().
Referenced by OmniboxResultView().
EmitTextChangedAccessiblityEvent()
void OmniboxResultView::EmitTextChangedAccessiblityEvent ()
References accessible_name_, GetAccessibleNodeData(), OmniboxPopupContentsView::IsOpen(), and popup_contents_view_.
Referenced by OnSelectionStateChanged().
GetAccessibleNodeData()
void OmniboxResultView::GetAccessibleNodeData (ui::AXNodeData * node_data) override
References AutocompleteMatch::contents, GetMatchSelected(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), AutocompleteResult::match_at(), model_, model_index_, OmniboxEditModel::result(), AutocompleteResult::size(), and AutocompleteMatchType::ToAccessibilityLabel().
Referenced by EmitTextChangedAccessiblityEvent().
GetActiveAuxiliaryButtonForAccessibility()
views::Button * OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility ()
References button_row_, OmniboxPopupSelection::FOCUSED_BUTTON_REMOVE_SUGGESTION, OmniboxSuggestionButtonRowView::GetActiveButton(), OmniboxPopupContentsView::GetSelection(), popup_contents_view_, remove_suggestion_button_, and OmniboxPopupSelection::state.
Referenced by OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility().
GetColor()
SkColor OmniboxResultView::GetColor (OmniboxPart part) const
References GetOmniboxColor(), and GetThemeState().
Referenced by OmniboxTextView::ApplyTextColor(), ApplyThemeAndRefreshIcons(), GetIcon(), OmniboxMatchCellView::OnMatchUpdate(), OnThemeChanged(), and OmniboxTextView::ReapplyStyling().
GetIcon()
gfx::Image OmniboxResultView::GetIcon () const private
References GetColor(), OmniboxPopupContentsView::GetMatchIcon(), match_, popup_contents_view_, and RESULTS_ICON.
Referenced by ApplyThemeAndRefreshIcons().
GetMatchSelected()
bool OmniboxResultView::GetMatchSelected () const
References OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, OmniboxPopupContentsView::GetSelection(), OmniboxPopupSelection::line, model_index_, popup_contents_view_, and OmniboxPopupSelection::state.
Referenced by ApplyThemeAndRefreshIcons(), GetAccessibleNodeData(), GetThemeState(), OmniboxResultView(), OnMouseDragged(), OnSelectionStateChanged(), and UpdateRemoveSuggestionVisibility().
GetPopupCellBackground()
std::unique_ptr< views::Background > OmniboxResultView::GetPopupCellBackground (views::View * view, OmniboxPartState part_state) static
References GetOmniboxColor(), NORMAL, and RESULTS_BACKGROUND.
Referenced by ApplyThemeAndRefreshIcons(), and OmniboxRowView::HeaderView::UpdateUI().
GetThemeState()
OmniboxPartState OmniboxResultView::GetThemeState () const
References GetMatchSelected(), HOVERED, NORMAL, and SELECTED.
Referenced by ApplyThemeAndRefreshIcons(), and GetColor().
METADATA_HEADER()
OmniboxResultView::METADATA_HEADER (OmniboxResultView)
OnBoundsChanged()
void OmniboxResultView::OnBoundsChanged (const gfx::Rect & previous_bounds) override private
References keyword_slide_animation_, and SetWidths().
OnMatchIconUpdated()
void OmniboxResultView::OnMatchIconUpdated ()
References ApplyThemeAndRefreshIcons().
Referenced by OmniboxPopupContentsView::OnMatchIconUpdated().
OnMouseDragged()
bool OmniboxResultView::OnMouseDragged (const ui::MouseEvent & event) override
References GetMatchSelected(), model_index_, popup_contents_view_, OmniboxPopupContentsView::SetSelectedIndex(), and UpdateHoverState().
OnMouseEntered()
void OmniboxResultView::OnMouseEntered (const ui::MouseEvent & event) override
References UpdateHoverState().
OnMouseExited()
void OmniboxResultView::OnMouseExited (const ui::MouseEvent & event) override
References UpdateHoverState().
OnMousePressed()
bool OmniboxResultView::OnMousePressed (const ui::MouseEvent & event) override
References model_index_, popup_contents_view_, and OmniboxPopupContentsView::SetSelectedIndex().
OnMouseReleased()
void OmniboxResultView::OnMouseReleased (const ui::MouseEvent & event) override
References model_index_, OmniboxPopupContentsView::OpenMatch(), and popup_contents_view_.
OnSelectionStateChanged()
void OmniboxResultView::OnSelectionStateChanged ()
References ApplyThemeAndRefreshIcons(), EmitTextChangedAccessiblityEvent(), OmniboxPopupContentsView::FireAXEventsForNewActiveDescendant(), OmniboxPopupSelection::FOCUSED_BUTTON_HEADER, GetMatchSelected(), OmniboxPopupContentsView::GetSelection(), OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), OmniboxPopupSelection::KEYWORD_MODE, OmniboxPopupSelection::NORMAL, popup_contents_view_, ShowKeywordSlideAnimation(), OmniboxPopupSelection::state, and UpdateRemoveSuggestionVisibility().
Referenced by OmniboxRowView::OnSelectionStateChanged().
OnThemeChanged()
void OmniboxResultView::OnThemeChanged () override
References ApplyThemeAndRefreshIcons(), GetColor(), remove_suggestion_button_, and RESULTS_ICON.
operator=()
OmniboxResultView& OmniboxResultView::operator= (const OmniboxResultView &) delete
SetMatch()
void OmniboxResultView::SetMatch (const AutocompleteMatch & match)
References AutocompleteMatch::answer, OmniboxTextView::AppendExtraText(), ApplyThemeAndRefreshIcons(), AutocompleteMatch::associated_keyword, button_row_, OmniboxMatchCellView::content(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, OmniboxMatchCellView::description(), AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::GetMatchWithContentsAndDescriptionPossiblySwapped(), OmniboxPopupContentsView::InExplicitExperimentalKeywordMode(), OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), keyword_slide_animation_, keyword_view_, match_, OmniboxMatchCellView::OnMatchUpdate(), popup_contents_view_, AutocompleteMatchType::SEARCH_SUGGEST_ENTITY, OmniboxTextView::SetTextWithStyling(), SetWidths(), suggestion_view_, AutocompleteMatch::type, OmniboxSuggestionButtonRowView::UpdateFromModel(), and UpdateRemoveSuggestionVisibility().
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
SetRichSuggestionImage()
void OmniboxResultView::SetRichSuggestionImage (const gfx::ImageSkia & image)
References OmniboxMatchCellView::SetImage(), and suggestion_view_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
SetWidths()
void OmniboxResultView::SetWidths () private
References OmniboxMatchCellView::CalculatePreferredSize(), OmniboxMatchCellView::GetTextIndent(), keyword_slide_animation_, and keyword_view_.
Referenced by AnimationProgressed(), OnBoundsChanged(), and SetMatch().
ShowKeywordSlideAnimation()
void OmniboxResultView::ShowKeywordSlideAnimation (bool show_keyword)
References keyword_slide_animation_.
Referenced by OnSelectionStateChanged().
UpdateHoverState()
void OmniboxResultView::UpdateHoverState () private
References ApplyThemeAndRefreshIcons(), and UpdateRemoveSuggestionVisibility().
Referenced by OnMouseDragged(), OnMouseEntered(), and OnMouseExited().
UpdateRemoveSuggestionVisibility()
void OmniboxResultView::UpdateRemoveSuggestionVisibility () private
References OmniboxPopupSelection::FOCUSED_BUTTON_REMOVE_SUGGESTION, GetMatchSelected(), OmniboxEditModel::IsPopupControlPresentOnMatch(), model_, model_index_, and remove_suggestion_button_.
Referenced by OnSelectionStateChanged(), SetMatch(), and UpdateHoverState().
Member Data Documentation
accessible_name_
std::u16string OmniboxResultView::accessible_name_ private
Referenced by EmitTextChangedAccessiblityEvent().
button_row_
OmniboxSuggestionButtonRowView* OmniboxResultView::button_row_ = nullptr private
Referenced by ApplyThemeAndRefreshIcons(), GetActiveAuxiliaryButtonForAccessibility(), OmniboxResultView(), and SetMatch().
keyword_slide_animation_
std::unique_ptr<gfx::SlideAnimation> OmniboxResultView::keyword_slide_animation_ private
Referenced by OnBoundsChanged(), SetMatch(), SetWidths(), and ShowKeywordSlideAnimation().
keyword_view_
OmniboxMatchCellView* OmniboxResultView::keyword_view_ private
Referenced by ApplyThemeAndRefreshIcons(), OmniboxResultView(), SetMatch(), and SetWidths().
match_
AutocompleteMatch OmniboxResultView::match_ private
Referenced by ApplyThemeAndRefreshIcons(), GetIcon(), and SetMatch().
model_
OmniboxEditModel* OmniboxResultView::model_ private
Referenced by ButtonPressed(), GetAccessibleNodeData(), OmniboxResultView(), and UpdateRemoveSuggestionVisibility().
model_index_
size_t OmniboxResultView::model_index_ private
Referenced by ButtonPressed(), GetAccessibleNodeData(), GetMatchSelected(), OnMouseDragged(), OnMousePressed(), OnMouseReleased(), and UpdateRemoveSuggestionVisibility().
mouse_enter_exit_handler_
OmniboxMouseEnterExitHandler OmniboxResultView::mouse_enter_exit_handler_ private
Referenced by OmniboxResultView().
popup_contents_view_
OmniboxPopupContentsView* const OmniboxResultView::popup_contents_view_ private
Referenced by ApplyThemeAndRefreshIcons(), EmitTextChangedAccessiblityEvent(), GetActiveAuxiliaryButtonForAccessibility(), GetIcon(), GetMatchSelected(), OmniboxResultView(), OnMouseDragged(), OnMousePressed(), OnMouseReleased(), OnSelectionStateChanged(), and SetMatch().
remove_suggestion_button_
views::ImageButton* OmniboxResultView::remove_suggestion_button_ private
Referenced by ApplyThemeAndRefreshIcons(), GetActiveAuxiliaryButtonForAccessibility(), OmniboxResultView(), OnThemeChanged(), and UpdateRemoveSuggestionVisibility().
selection_indicator_
OmniboxResultSelectionIndicator* OmniboxResultView::selection_indicator_ = nullptr private
Referenced by ApplyThemeAndRefreshIcons(), and OmniboxResultView().
suggestion_container_
views::View* OmniboxResultView::suggestion_container_ private
Referenced by OmniboxResultView().
suggestion_view_
OmniboxMatchCellView* OmniboxResultView::suggestion_view_ private
Referenced by ApplyThemeAndRefreshIcons(), OmniboxResultView(), SetMatch(), and SetRichSuggestionImage().
weak_factory_
base::WeakPtrFactory<OmniboxResultView> OmniboxResultView::weak_factory_ {this} private
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_result_view.h
chrome/browser/ui/views/omnibox/omnibox_result_view.cc