Chromium Omnibox: OmniboxPedalProvider Class Reference
OmniboxPedalProvider Class Reference
#include <omnibox_pedal_provider.h>
Public Member Functions
OmniboxPedalProvider (AutocompleteProviderClient &client, bool with_branding)
~OmniboxPedalProvider ()
OmniboxPedalProvider (const OmniboxPedalProvider &)=delete
OmniboxPedalProvider & operator= (const OmniboxPedalProvider &)=delete
OmniboxPedal * FindPedalMatch (const std::u16string &match_text)
OmniboxPedal * FindReadyPedalMatch (const AutocompleteInput &input, const std::u16string &match_text)
void AddProviderInfo (ProvidersInfo *provider_info) const
void ResetSession ()
void set_field_trial_triggered (bool triggered)
size_t EstimateMemoryUsage () const
Protected Member Functions
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest, ProviderFiltersPedalUpdateChrome)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsWithoutTranslationConsoleTest, ProviderFiltersPedalUpdateChrome)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest, UnorderedSynonymExpressionsAreConceptMatches)
FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsWithoutTranslationConsoleTest, UnorderedSynonymExpressionsAreConceptMatches)
void Tokenize (OmniboxPedal::TokenSequence &out_tokens, const std::u16string &text) const
void TokenizeAndExpandDictionary (OmniboxPedal::TokenSequence &out_tokens, const std::u16string &token_sequence_string)
void LoadPedalConcepts ()
OmniboxPedal::SynonymGroup LoadSynonymGroupValue (const base::Value &group_value) const
OmniboxPedal::SynonymGroup LoadSynonymGroupString (bool required, bool match_once, std::u16string synonyms_csv)
Protected Attributes
AutocompleteProviderClient & client_
std::unordered_map< OmniboxPedalId, scoped_refptr< OmniboxPedal > > pedals_
OmniboxPedal::SynonymGroup ignore_group_
std::unordered_map< std::u16string, int > dictionary_
std::u16string tokenize_characters_
OmniboxPedal::TokenSequence match_tokens_
size_t max_tokens_ = 0
bool field_trial_triggered_ = false
bool field_trial_triggered_in_session_ = false
Friends
class OmniboxPedalImplementationsTest
Constructor & Destructor Documentation
OmniboxPedalProvider() [1/2]
OmniboxPedalProvider::OmniboxPedalProvider (AutocompleteProviderClient & client, bool with_branding)
References OmniboxAction::LabelStrings::accessibility_hint, OmniboxAction::LabelStrings::accessibility_suffix, OmniboxAction::LabelStrings::hint, LoadPedalConcepts(), pedals_, and OmniboxAction::LabelStrings::suggestion_contents.
Referenced by MockAutocompleteProviderClient::MockAutocompleteProviderClient().
~OmniboxPedalProvider()
OmniboxPedalProvider::~OmniboxPedalProvider ()
OmniboxPedalProvider() [2/2]
OmniboxPedalProvider::OmniboxPedalProvider (const OmniboxPedalProvider &) delete
Member Function Documentation
AddProviderInfo()
void OmniboxPedalProvider::AddProviderInfo (ProvidersInfo * provider_info) const
References field_trial_triggered_, field_trial_triggered_in_session_, and OmniboxFieldTrial::GetActiveSuggestFieldTrialHashes().
EstimateMemoryUsage()
size_t OmniboxPedalProvider::EstimateMemoryUsage () const
References dictionary_, base::trace_event::EstimateMemoryUsage(), ignore_group_, pedals_, and tokenize_characters_.
FindPedalMatch()
OmniboxPedal * OmniboxPedalProvider::FindPedalMatch (const std::u16string & match_text)
References OmniboxPedal::SynonymGroup::EraseMatchesIn(), ignore_group_, match_tokens_, pedals_, OmniboxPedal::TokenSequence::ResetLinks(), OmniboxPedal::TokenSequence::Size(), and Tokenize().
Referenced by FindReadyPedalMatch().
FindReadyPedalMatch()
OmniboxPedal * OmniboxPedalProvider::FindReadyPedalMatch (const AutocompleteInput & input, const std::u16string & match_text)
References client_, field_trial_triggered_, field_trial_triggered_in_session_, FindPedalMatch(), and OmniboxAction::IsReadyToTrigger().
Referenced by AutocompleteResult::AttachPedalsToMatches().
FRIEND_TEST_ALL_PREFIXES() [1/4]
OmniboxPedalProvider::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest , ProviderFiltersPedalUpdateChrome) protected
FRIEND_TEST_ALL_PREFIXES() [2/4]
OmniboxPedalProvider::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsTest , UnorderedSynonymExpressionsAreConceptMatches) protected
FRIEND_TEST_ALL_PREFIXES() [3/4]
OmniboxPedalProvider::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsWithoutTranslationConsoleTest , ProviderFiltersPedalUpdateChrome) protected
FRIEND_TEST_ALL_PREFIXES() [4/4]
OmniboxPedalProvider::FRIEND_TEST_ALL_PREFIXES (OmniboxPedalImplementationsWithoutTranslationConsoleTest , UnorderedSynonymExpressionsAreConceptMatches) protected
LoadPedalConcepts()
void OmniboxPedalProvider::LoadPedalConcepts () protected
References OmniboxPedal::AddSynonymGroup(), OmniboxPedal::AddVerbatimSequence(), CHANGE_GOOGLE_PASSWORD, CLOSE_INCOGNITO_WINDOWS, dictionary_, OmniboxPedal::SynonymGroup::EraseIgnoreGroup(), OmniboxPedal::SynonymGroup::EraseMatchesIn(), OmniboxAction::GetLabelStrings(), OmniboxAction::LabelStrings::hint, ignore_group_, OmniboxFieldTrial::IsPedalsBatch2NonEnglishEnabled(), OmniboxFieldTrial::IsPedalsBatch3NonEnglishEnabled(), OmniboxFieldTrial::IsPedalsTranslationConsoleEnabled(), OmniboxPedal::SynonymGroup::IsValid(), LoadSynonymGroupString(), LoadSynonymGroupValue(), MANAGE_CHROMEOS_ACCESSIBILITY, max_tokens_, OMNIBOX_PEDAL_CONCEPTS_DATA_VERSION, pedals_, RUN_CHROME_SAFETY_CHECK, OmniboxPedal::SetLabelStrings(), OmniboxPedal::SetNavigationUrl(), OmniboxPedal::SpecifySynonymGroups(), tokenize_characters_, and TokenizeAndExpandDictionary().
Referenced by OmniboxPedalProvider().
LoadSynonymGroupString()
OmniboxPedal::SynonymGroup OmniboxPedalProvider::LoadSynonymGroupString (bool required, bool match_once, std::u16string synonyms_csv) protected
References OmniboxPedal::SynonymGroup::AddSynonym(), OmniboxPedal::SynonymGroup::SortSynonyms(), and TokenizeAndExpandDictionary().
Referenced by LoadPedalConcepts().
LoadSynonymGroupValue()
OmniboxPedal::SynonymGroup OmniboxPedalProvider::LoadSynonymGroupValue (const base::Value & group_value) const protected
References OmniboxPedal::TokenSequence::Add(), and OmniboxPedal::SynonymGroup::AddSynonym().
Referenced by LoadPedalConcepts().
operator=()
OmniboxPedalProvider& OmniboxPedalProvider::operator= (const OmniboxPedalProvider &) delete
ResetSession()
void OmniboxPedalProvider::ResetSession ()
References field_trial_triggered_, and field_trial_triggered_in_session_.
set_field_trial_triggered()
void OmniboxPedalProvider::set_field_trial_triggered (bool triggered) inline
References field_trial_triggered_.
Referenced by AutocompleteResult::AttachPedalsToMatches().
Tokenize()
void OmniboxPedalProvider::Tokenize (OmniboxPedal::TokenSequence & out_tokens, const std::u16string & text) const protected
References OmniboxPedal::TokenSequence::Add(), OmniboxPedal::TokenSequence::Clear(), dictionary_, max_tokens_, OmniboxPedal::TokenSequence::Size(), and tokenize_characters_.
Referenced by FindPedalMatch().
TokenizeAndExpandDictionary()
void OmniboxPedalProvider::TokenizeAndExpandDictionary (OmniboxPedal::TokenSequence & out_tokens, const std::u16string & token_sequence_string) protected
References OmniboxPedal::TokenSequence::Add(), OmniboxPedal::TokenSequence::Clear(), dictionary_, max_tokens_, OmniboxPedal::TokenSequence::Size(), and tokenize_characters_.
Referenced by LoadPedalConcepts(), and LoadSynonymGroupString().
Friends And Related Function Documentation
OmniboxPedalImplementationsTest
friend class OmniboxPedalImplementationsTest friend
Member Data Documentation
client_
AutocompleteProviderClient& OmniboxPedalProvider::client_ protected
Referenced by FindReadyPedalMatch().
dictionary_
std::unordered_map<std::u16string, int> OmniboxPedalProvider::dictionary_ protected
Referenced by EstimateMemoryUsage(), LoadPedalConcepts(), Tokenize(), and TokenizeAndExpandDictionary().
field_trial_triggered_
bool OmniboxPedalProvider::field_trial_triggered_ = false protected
Referenced by AddProviderInfo(), FindReadyPedalMatch(), ResetSession(), and set_field_trial_triggered().
field_trial_triggered_in_session_
bool OmniboxPedalProvider::field_trial_triggered_in_session_ = false protected
Referenced by AddProviderInfo(), FindReadyPedalMatch(), and ResetSession().
ignore_group_
OmniboxPedal::SynonymGroup OmniboxPedalProvider::ignore_group_ protected
Referenced by EstimateMemoryUsage(), FindPedalMatch(), and LoadPedalConcepts().
match_tokens_
OmniboxPedal::TokenSequence OmniboxPedalProvider::match_tokens_ protected
Referenced by FindPedalMatch().
max_tokens_
size_t OmniboxPedalProvider::max_tokens_ = 0 protected
Referenced by LoadPedalConcepts(), Tokenize(), and TokenizeAndExpandDictionary().
pedals_
std::unordered_map<OmniboxPedalId, scoped_refptr<OmniboxPedal> > OmniboxPedalProvider::pedals_ protected
Referenced by EstimateMemoryUsage(), FindPedalMatch(), LoadPedalConcepts(), and OmniboxPedalProvider().
tokenize_characters_
std::u16string OmniboxPedalProvider::tokenize_characters_ protected
Referenced by EstimateMemoryUsage(), LoadPedalConcepts(), Tokenize(), and TokenizeAndExpandDictionary().
The documentation for this class was generated from the following files:
components/omnibox/browser/actions/omnibox_pedal_provider.h
components/omnibox/browser/actions/omnibox_pedal_provider.cc