Chromium Omnibox: OmniboxSuggestionRowButton Class Reference
OmniboxSuggestionRowButton Class Reference
Public Member Functions
METADATA_HEADER (OmniboxSuggestionRowButton)
OmniboxSuggestionRowButton (PressedCallback callback, const std::u16string &text, const gfx::VectorIcon &icon, OmniboxPopupContentsView *popup_contents_view, OmniboxPopupSelection selection)
OmniboxSuggestionRowButton (const OmniboxSuggestionRowButton &)=delete
OmniboxSuggestionRowButton & operator= (const OmniboxSuggestionRowButton &)=delete
~OmniboxSuggestionRowButton () override=default
void OnOmniboxBackgroundChange (SkColor omnibox_bg_color)
OmniboxPopupSelection selection ()
void OnThemeChanged () override
void UpdateBackgroundColor () override
void GetAccessibleNodeData (ui::AXNodeData *node_data) override
void SetIcon (const gfx::VectorIcon &icon, SkColor icon_color=SK_ColorTRANSPARENT)
Private Attributes
const gfx::VectorIcon * icon_
OmniboxPopupContentsView * popup_contents_view_
OmniboxPopupSelection selection_
absl::optional< SkColor > omnibox_bg_color_
SkColor icon_color_
Constructor & Destructor Documentation
OmniboxSuggestionRowButton() [1/2]
OmniboxSuggestionRowButton::OmniboxSuggestionRowButton (PressedCallback callback, const std::u16string & text, const gfx::VectorIcon & icon, OmniboxPopupContentsView * popup_contents_view, OmniboxPopupSelection selection) inline
References GetOmniboxStateOpacity(), OmniboxPopupContentsView::GetSelection(), HOVERED, omnibox_bg_color_, popup_contents_view_, and selection_.
Referenced by OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView().
OmniboxSuggestionRowButton() [2/2]
OmniboxSuggestionRowButton::OmniboxSuggestionRowButton (const OmniboxSuggestionRowButton &) delete
~OmniboxSuggestionRowButton()
OmniboxSuggestionRowButton::~OmniboxSuggestionRowButton () override default
Member Function Documentation
GetAccessibleNodeData()
void OmniboxSuggestionRowButton::GetAccessibleNodeData (ui::AXNodeData * node_data) inline override
METADATA_HEADER()
OmniboxSuggestionRowButton::METADATA_HEADER (OmniboxSuggestionRowButton)
OnOmniboxBackgroundChange()
void OmniboxSuggestionRowButton::OnOmniboxBackgroundChange (SkColor omnibox_bg_color) inline
References omnibox_bg_color_, and UpdateBackgroundColor().
Referenced by OmniboxSuggestionButtonRowView::OnOmniboxBackgroundChange().
OnThemeChanged()
void OmniboxSuggestionRowButton::OnThemeChanged () inline override
References GetOmniboxColor(), icon_, icon_color_, NORMAL, RESULTS_ICON, and RESULTS_TEXT_DEFAULT.
Referenced by SetIcon().
operator=()
OmniboxSuggestionRowButton& OmniboxSuggestionRowButton::operator= (const OmniboxSuggestionRowButton &) delete
selection()
OmniboxPopupSelection OmniboxSuggestionRowButton::selection () inline
References selection_.
SetIcon()
void OmniboxSuggestionRowButton::SetIcon (const gfx::VectorIcon & icon, SkColor icon_color = SK_ColorTRANSPARENT) inline
References icon_, icon_color_, and OnThemeChanged().
Referenced by OmniboxSuggestionButtonRowView::UpdateFromModel().
UpdateBackgroundColor()
void OmniboxSuggestionRowButton::UpdateBackgroundColor () inline override
References GetOmniboxColor(), NORMAL, omnibox_bg_color_, and RESULTS_BUTTON_BORDER.
Referenced by OnOmniboxBackgroundChange().
Member Data Documentation
icon_
const gfx::VectorIcon* OmniboxSuggestionRowButton::icon_ private
Referenced by OnThemeChanged(), and SetIcon().
icon_color_
SkColor OmniboxSuggestionRowButton::icon_color_ private
Referenced by OnThemeChanged(), and SetIcon().
omnibox_bg_color_
absl::optional<SkColor> OmniboxSuggestionRowButton::omnibox_bg_color_ private
Referenced by OmniboxSuggestionRowButton(), OnOmniboxBackgroundChange(), and UpdateBackgroundColor().
popup_contents_view_
OmniboxPopupContentsView* OmniboxSuggestionRowButton::popup_contents_view_ private
Referenced by OmniboxSuggestionRowButton().
selection_
OmniboxPopupSelection OmniboxSuggestionRowButton::selection_ private
Referenced by OmniboxSuggestionRowButton(), and selection().
The documentation for this class was generated from the following file:
chrome/browser/ui/views/omnibox/omnibox_suggestion_button_row_view.cc