Chromium Omnibox: BuiltinProvider Class Reference
BuiltinProvider Class Reference
#include <builtin_provider.h>
Public Member Functions
BuiltinProvider (AutocompleteProviderClient *client)
BuiltinProvider (const BuiltinProvider &)=delete
BuiltinProvider & operator= (const BuiltinProvider &)=delete
void Start (const AutocompleteInput &input, bool minimal_changes) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Types
typedef std::vector< std::u16string > Builtins
Private Member Functions
~BuiltinProvider () override
void AddMatch (const std::u16string &match_string, const std::u16string &inline_completion, const ACMatchClassifications &styles)
bool HasMatchThatShouldBeDefault (size_t *index) const
Private Attributes
AutocompleteProviderClient * client_
Builtins builtins_
Static Private Attributes
static const int kRelevance = 860
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Member Typedef Documentation
Builtins
typedef std::vector<std::u16string> BuiltinProvider::Builtins private
Constructor & Destructor Documentation
BuiltinProvider() [1/2]
BuiltinProvider::BuiltinProvider (AutocompleteProviderClient * client) explicit
References builtins_, client_, and AutocompleteProviderClient::GetBuiltinURLs().
BuiltinProvider() [2/2]
BuiltinProvider::BuiltinProvider (const BuiltinProvider &) delete
~BuiltinProvider()
BuiltinProvider::~BuiltinProvider () override private
Member Function Documentation
AddMatch()
void BuiltinProvider::AddMatch (const std::u16string & match_string, const std::u16string & inline_completion, const ACMatchClassifications & styles) private
References AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteMatch::inline_autocompletion, kRelevance, AutocompleteProvider::matches_, and AutocompleteMatchType::NAVSUGGEST.
Referenced by Start().
HasMatchThatShouldBeDefault()
bool BuiltinProvider::HasMatchThatShouldBeDefault (size_t * index) const private
References AutocompleteProvider::matches_.
Referenced by Start().
operator=()
BuiltinProvider& BuiltinProvider::operator= (const BuiltinProvider &) delete
Start()
void BuiltinProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References AddMatch(), builtins_, ClassifyTermMatches(), client_, omnibox::DEFAULT, AutocompleteInput::focus_type(), AutocompleteProviderClient::GetBuiltinsToProvideAsUserTypes(), AutocompleteProviderClient::GetEmbedderRepresentationOfAboutScheme(), HasMatchThatShouldBeDefault(), kRelevance, AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteProvider::matches_, AutocompleteInput::prevent_inline_autocomplete(), AutocompleteProvider::provider_max_matches_, AutocompleteInput::text(), AutocompleteInput::type(), and AutocompleteMatch::ACMatchClassification::URL.
Member Data Documentation
builtins_
Builtins BuiltinProvider::builtins_ private
Referenced by BuiltinProvider(), and Start().
client_
AutocompleteProviderClient* BuiltinProvider::client_ private
Referenced by BuiltinProvider(), and Start().
kRelevance
const int BuiltinProvider::kRelevance = 860 static private
Referenced by AddMatch(), and Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/builtin_provider.h
components/omnibox/browser/builtin_provider.cc