Chromium Omnibox: components/omnibox/browser/verbatim_match.cc File Reference
verbatim_match.cc File Reference
#include "components/omnibox/browser/verbatim_match.h"
#include "components/omnibox/browser/autocomplete_classifier.h"
#include "components/omnibox/browser/autocomplete_input.h"
#include "components/omnibox/browser/autocomplete_match_classification.h"
#include "components/omnibox/browser/autocomplete_provider.h"
#include "components/omnibox/browser/autocomplete_provider_client.h"
#include "components/omnibox/browser/in_memory_url_index_types.h"
#include "components/search_engines/template_url_service.h"
#include "url/gurl.h"
Functions
AutocompleteMatch VerbatimMatchForURL (AutocompleteProvider *provider, AutocompleteProviderClient *client, const AutocompleteInput &input, const GURL &destination_url, const std::u16string &destination_description, int verbatim_relevance)
AutocompleteMatch VerbatimMatchForInput (AutocompleteProvider *provider, AutocompleteProviderClient *client, const AutocompleteInput &input, const GURL &destination_url, bool trim_default_scheme)
Function Documentation
VerbatimMatchForInput()
AutocompleteMatch VerbatimMatchForInput (AutocompleteProvider * provider, AutocompleteProviderClient * client, const AutocompleteInput & input, const GURL & destination_url, bool trim_default_scheme)
References AutocompleteInput::added_default_scheme_to_typed_url(), AutocompleteMatch::allowed_to_be_default_match, ClassifyTermMatches(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteProviderClient::GetSchemeClassifier(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteInput::HasHTTPScheme(), AutocompleteInput::HasHTTPSScheme(), AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteInput::text(), AutocompleteProvider::TrimSchemePrefix(), AutocompleteInput::type(), AutocompleteMatch::ACMatchClassification::URL, and AutocompleteMatchType::URL_WHAT_YOU_TYPED.
Referenced by OmniboxEditModel::AcceptInput(), OmniboxEditModel::OpenMatch(), HistoryURLProvider::Start(), and VerbatimMatchForURL().
VerbatimMatchForURL()
AutocompleteMatch VerbatimMatchForURL (AutocompleteProvider * provider, AutocompleteProviderClient * client, const AutocompleteInput & input, const GURL & destination_url, const std::u16string & destination_description, int verbatim_relevance)
References AutocompleteMatch::allowed_to_be_default_match, AutocompleteProviderClient::Classify(), AutocompleteInput::current_page_classification(), AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteInput::HasHTTPScheme(), AutocompleteMatch::ACMatchClassification::NONE, AutocompleteMatch::relevance, AutocompleteInput::text(), and VerbatimMatchForInput().
Referenced by ClipboardProvider::AddCreatedMatchWithTracking(), ZeroSuggestProvider::MatchForCurrentText(), and ZeroSuggestVerbatimMatchProvider::Start().