Chromium Omnibox: OmniboxEventGlobalTracker Class Reference
OmniboxEventGlobalTracker Class Reference
#include <omnibox_event_global_tracker.h>
Public Types
using OnURLOpenedCallbackList = base::RepeatingCallbackList< void(OmniboxLog *)>
using OnURLOpenedCallback = OnURLOpenedCallbackList::CallbackType
Public Member Functions
base::CallbackListSubscription RegisterCallback (const OnURLOpenedCallback &cb)
void OnURLOpened (OmniboxLog *log)
Static Public Member Functions
static OmniboxEventGlobalTracker * GetInstance ()
Private Member Functions
OmniboxEventGlobalTracker ()
~OmniboxEventGlobalTracker ()
OmniboxEventGlobalTracker (const OmniboxEventGlobalTracker &)=delete
OmniboxEventGlobalTracker & operator= (const OmniboxEventGlobalTracker &)=delete
Private Attributes
OnURLOpenedCallbackList on_url_opened_callback_list_
Friends
struct base::DefaultSingletonTraits< OmniboxEventGlobalTracker >
Member Typedef Documentation
OnURLOpenedCallback
using OmniboxEventGlobalTracker::OnURLOpenedCallback = OnURLOpenedCallbackList::CallbackType
OnURLOpenedCallbackList
using OmniboxEventGlobalTracker::OnURLOpenedCallbackList = base::RepeatingCallbackList<void(OmniboxLog*)>
Constructor & Destructor Documentation
OmniboxEventGlobalTracker() [1/2]
OmniboxEventGlobalTracker::OmniboxEventGlobalTracker () private
~OmniboxEventGlobalTracker()
OmniboxEventGlobalTracker::~OmniboxEventGlobalTracker () private
OmniboxEventGlobalTracker() [2/2]
OmniboxEventGlobalTracker::OmniboxEventGlobalTracker (const OmniboxEventGlobalTracker &) private delete
Member Function Documentation
GetInstance()
OmniboxEventGlobalTracker * OmniboxEventGlobalTracker::GetInstance () static
Referenced by OmniboxMetricsProvider::OnRecordingEnabled(), and OmniboxEditModel::OpenMatch().
OnURLOpened()
void OmniboxEventGlobalTracker::OnURLOpened (OmniboxLog * log)
References on_url_opened_callback_list_.
Referenced by OmniboxEditModel::OpenMatch().
operator=()
OmniboxEventGlobalTracker& OmniboxEventGlobalTracker::operator= (const OmniboxEventGlobalTracker &) private delete
RegisterCallback()
base::CallbackListSubscription OmniboxEventGlobalTracker::RegisterCallback (const OnURLOpenedCallback & cb)
References on_url_opened_callback_list_.
Referenced by OmniboxMetricsProvider::OnRecordingEnabled().
Friends And Related Function Documentation
base::DefaultSingletonTraits< OmniboxEventGlobalTracker >
friend struct base::DefaultSingletonTraits< OmniboxEventGlobalTracker > friend
Member Data Documentation
on_url_opened_callback_list_
OnURLOpenedCallbackList OmniboxEventGlobalTracker::on_url_opened_callback_list_ private
Referenced by OnURLOpened(), and RegisterCallback().
The documentation for this class was generated from the following files:
components/omnibox/browser/omnibox_event_global_tracker.h
components/omnibox/browser/omnibox_event_global_tracker.cc