Chromium Omnibox: ZeroSuggestProvider Class Reference
ZeroSuggestProvider Class Reference
#include <zero_suggest_provider.h>
Public Types
enum ResultType { NONE , REMOTE_NO_URL , REMOTE_SEND_URL }
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Public Member Functions
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
void ResetSession () override
const SearchSuggestionParser::ExperimentStats & experiment_stats () const
const SearchSuggestionParser::HeadersMap & headers_map () const
const std::vector< int > hidden_group_ids () const
ResultType GetResultTypeRunningForTesting () const
Public Member Functions inherited from BaseSearchProvider
BaseSearchProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
BaseSearchProvider (const BaseSearchProvider &)=delete
BaseSearchProvider & operator= (const BaseSearchProvider &)=delete
bool field_trial_triggered_in_session () const
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static ZeroSuggestProvider * Create (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
static void RegisterProfilePrefs (PrefRegistrySimple *registry)
Static Public Member Functions inherited from BaseSearchProvider
static bool ShouldPrefetch (const AutocompleteMatch &match)
static AutocompleteMatch CreateSearchSuggestion (const std::u16string &suggestion, AutocompleteMatchType::Type type, bool from_keyword_provider, const TemplateURL *template_url, const SearchTermsData &search_terms_data)
static AutocompleteMatch CreateSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const bool in_keyword_mode, const SearchSuggestionParser::SuggestResult &suggestion, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion, bool append_extra_query_params_from_command_line)
static AutocompleteMatch CreateOnDeviceSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const std::u16string &suggestion, int relevance, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion)
static void AppendSuggestClientToAdditionalQueryParams (const TemplateURL *template_url, const SearchTermsData &search_terms_data, metrics::OmniboxEventProto::PageClassification page_classification, TemplateURLRef::SearchTermsArgs *search_terms_args)
static bool IsNTPPage (metrics::OmniboxEventProto::PageClassification classification)
static bool IsSearchResultsPage (metrics::OmniboxEventProto::PageClassification classification)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest, AllowZeroSuggestSuggestions)
FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest, TypeOfResultToRun)
FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest, TypeOfResultToRunForContextualWeb)
FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest, TestStartWillStopForSomeInput)
ZeroSuggestProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
~ZeroSuggestProvider () override
ZeroSuggestProvider (const ZeroSuggestProvider &)=delete
ZeroSuggestProvider & operator= (const ZeroSuggestProvider &)=delete
const TemplateURL * GetTemplateURL (bool is_keyword) const override
const AutocompleteInput GetInput (bool is_keyword) const override
bool ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult &result) const override
void RecordDeletionResult (bool success) override
void OnURLLoadComplete (const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)
bool UpdateResults (const std::string &json_data)
AutocompleteMatch NavigationToMatch (const SearchSuggestionParser::NavigationResult &navigation)
void ConvertResultsToAutocompleteMatches ()
AutocompleteMatch MatchForCurrentText ()
void OnRemoteSuggestionsLoaderAvailable (std::unique_ptr< network::SimpleURLLoader > loader)
bool AllowZeroSuggestSuggestions (const AutocompleteInput &input) const
void MaybeUseCachedSuggestions ()
Static Private Member Functions
static ResultType TypeOfResultToRun (AutocompleteProviderClient *client, const AutocompleteInput &input, const GURL &suggest_url)
Private Attributes
AutocompleteProviderListener * listener_
ResultType result_type_running_
std::string current_query_
std::u16string current_title_
metrics::OmniboxEventProto::PageClassification current_page_classification_
std::u16string permanent_text_
std::unique_ptr< network::SimpleURLLoader > loader_
AutocompleteMatch current_text_match_
SearchSuggestionParser::Results results_
base::WeakPtrFactory< ZeroSuggestProvider > weak_ptr_factory_ {this}
Additional Inherited Members
Protected Types inherited from BaseSearchProvider
typedef std::pair< std::u16string, std::string > MatchKey
typedef std::map< MatchKey, AutocompleteMatch > MatchMap
typedef std::vector< std::unique_ptr< SuggestionDeletionHandler > > SuggestionDeletionHandlers
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from BaseSearchProvider
~BaseSearchProvider () override
void SetDeletionURL (const std::string &deletion_url, AutocompleteMatch *match)
void AddMatchToMap (const SearchSuggestionParser::SuggestResult &result, const std::string &metadata, int accepted_suggestion, bool mark_as_deletable, bool in_keyword_mode, MatchMap *map)
bool ParseSuggestResults (const base::Value &root_val, int default_result_relevance, bool is_keyword_result, SearchSuggestionParser::Results *results)
AutocompleteProviderClient * client ()
const AutocompleteProviderClient * client () const
bool field_trial_triggered () const
void set_field_trial_triggered (bool triggered)
void set_field_trial_triggered_in_session (bool triggered)
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from BaseSearchProvider
static std::u16string GetFillIntoEdit (const SearchSuggestionParser::SuggestResult &suggest_result, const TemplateURL *template_url)
static bool CanSendURL (const GURL &current_page_url, const GURL &suggest_url, const TemplateURL *template_url, metrics::OmniboxEventProto::PageClassification page_classification, const SearchTermsData &search_terms_data, AutocompleteProviderClient *client, bool sending_search_terms)
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Static Protected Attributes inherited from BaseSearchProvider
static const char kRelevanceFromServerKey []
static const char kShouldPrefetchKey [] = "should_prefetch"
static const char kSuggestMetadataKey [] = "suggest_metadata"
static const char kDeletionUrlKey [] = "deletion_url"
static const char kTrue [] = "true"
static const char kFalse [] = "false"
Member Enumeration Documentation
ResultType
enum ZeroSuggestProvider::ResultType
Enumerator
NONE
REMOTE_NO_URL
REMOTE_SEND_URL
Constructor & Destructor Documentation
ZeroSuggestProvider() [1/2]
ZeroSuggestProvider::ZeroSuggestProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) private
References BaseSearchProvider::CanSendURL(), BaseSearchProvider::client(), RemoteSuggestionsService::EndpointUrl(), AutocompleteProviderClient::GetTemplateURLService(), and NONE.
Referenced by Create().
~ZeroSuggestProvider()
ZeroSuggestProvider::~ZeroSuggestProvider () override private default
ZeroSuggestProvider() [2/2]
ZeroSuggestProvider::ZeroSuggestProvider (const ZeroSuggestProvider &) private delete
Member Function Documentation
AddProviderInfo()
void ZeroSuggestProvider::AddProviderInfo (ProvidersInfo * provider_info) const override virtual
Reimplemented from BaseSearchProvider.
References BaseSearchProvider::AddProviderInfo(), SearchSuggestionParser::Results::navigation_results, results_, and SearchSuggestionParser::Results::suggest_results.
AllowZeroSuggestSuggestions()
bool ZeroSuggestProvider::AllowZeroSuggestSuggestions (const AutocompleteInput & input) const private
References BaseSearchProvider::client(), AutocompleteInput::current_page_classification(), AutocompleteInput::current_url(), omnibox::DEFAULT, AutocompleteInput::focus_type(), BaseSearchProvider::IsNTPPage(), omnibox::kClobberTriggersContextualWebZeroSuggest, and AutocompleteInput::type().
Referenced by Start().
ConvertResultsToAutocompleteMatches()
void ZeroSuggestProvider::ConvertResultsToAutocompleteMatches () private
References BaseSearchProvider::AddMatchToMap(), BaseSearchProvider::client(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteProvider::matches_, SearchSuggestionParser::Results::navigation_results, NavigationToMatch(), results_, and SearchSuggestionParser::Results::suggest_results.
Referenced by MaybeUseCachedSuggestions(), and UpdateResults().
Create()
ZeroSuggestProvider * ZeroSuggestProvider::Create (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) static
References BaseSearchProvider::client(), and ZeroSuggestProvider().
Referenced by AutocompleteController::AutocompleteController().
DeleteMatch()
void ZeroSuggestProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from BaseSearchProvider.
References BaseSearchProvider::client(), BaseSearchProvider::DeleteMatch(), AutocompleteProviderClient::GetPrefs(), and omnibox::kZeroSuggestCachedResults.
experiment_stats()
const SearchSuggestionParser::ExperimentStats& ZeroSuggestProvider::experiment_stats () const inline
References SearchSuggestionParser::Results::experiment_stats, and results_.
Referenced by AutocompleteController::UpdateMatchDestinationURLWithQueryFormulationTime().
FRIEND_TEST_ALL_PREFIXES() [1/4]
ZeroSuggestProvider::FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest , AllowZeroSuggestSuggestions) private
FRIEND_TEST_ALL_PREFIXES() [2/4]
ZeroSuggestProvider::FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest , TestStartWillStopForSomeInput) private
FRIEND_TEST_ALL_PREFIXES() [3/4]
ZeroSuggestProvider::FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest , TypeOfResultToRun) private
FRIEND_TEST_ALL_PREFIXES() [4/4]
ZeroSuggestProvider::FRIEND_TEST_ALL_PREFIXES (ZeroSuggestProviderTest , TypeOfResultToRunForContextualWeb) private
GetInput()
const AutocompleteInput ZeroSuggestProvider::GetInput (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References BaseSearchProvider::client(), current_page_classification_, current_query_, current_title_, AutocompleteInput::set_allow_exact_keyword_match(), AutocompleteInput::set_current_title(), AutocompleteInput::set_current_url(), and AutocompleteInput::set_prevent_inline_autocomplete().
Referenced by MatchForCurrentText().
GetResultTypeRunningForTesting()
ResultType ZeroSuggestProvider::GetResultTypeRunningForTesting () const inline
References result_type_running_.
GetTemplateURL()
const TemplateURL * ZeroSuggestProvider::GetTemplateURL (bool is_keyword) const override private virtual
Implements BaseSearchProvider.
References BaseSearchProvider::client(), and AutocompleteProviderClient::GetTemplateURLService().
headers_map()
const SearchSuggestionParser::HeadersMap& ZeroSuggestProvider::headers_map () const inline
References SearchSuggestionParser::Results::headers_map, and results_.
Referenced by AutocompleteController::UpdateHeaderInfoFromZeroSuggestProvider().
hidden_group_ids()
const std::vector<int> ZeroSuggestProvider::hidden_group_ids () const inline
References SearchSuggestionParser::Results::hidden_group_ids, and results_.
Referenced by AutocompleteController::UpdateHeaderInfoFromZeroSuggestProvider().
MatchForCurrentText()
AutocompleteMatch ZeroSuggestProvider::MatchForCurrentText () private
References BaseSearchProvider::client(), current_query_, current_title_, GetInput(), omnibox::kDisplayTitleForCurrentUrl, AutocompleteInput::parts(), permanent_text_, AutocompleteMatch::provider, results_, AutocompleteInput::UpdateText(), SearchSuggestionParser::Results::verbatim_relevance, and VerbatimMatchForURL().
Referenced by Start().
MaybeUseCachedSuggestions()
void ZeroSuggestProvider::MaybeUseCachedSuggestions () private
References BaseSearchProvider::client(), ConvertResultsToAutocompleteMatches(), SearchSuggestionParser::DeserializeJsonData(), AutocompleteProviderClient::GetPrefs(), omnibox::kZeroSuggestCachedResults, BaseSearchProvider::ParseSuggestResults(), REMOTE_NO_URL, result_type_running_, and results_.
Referenced by Start().
NavigationToMatch()
AutocompleteMatch ZeroSuggestProvider::NavigationToMatch (const SearchSuggestionParser::NavigationResult & navigation) private
References ClassifyTermMatches(), BaseSearchProvider::client(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, SearchSuggestionParser::NavigationResult::description(), AutocompleteMatch::description_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::GetFormatTypes(), AutocompleteMatch::ACMatchClassification::NONE, SearchSuggestionParser::Result::relevance(), AutocompleteMatch::SanitizeString(), AutocompleteMatch::subtypes, SearchSuggestionParser::Result::subtypes(), SearchSuggestionParser::Result::type(), AutocompleteMatch::ACMatchClassification::URL, and SearchSuggestionParser::NavigationResult::url().
Referenced by ConvertResultsToAutocompleteMatches().
OnRemoteSuggestionsLoaderAvailable()
void ZeroSuggestProvider::OnRemoteSuggestionsLoaderAvailable (std::unique_ptr< network::SimpleURLLoader > loader) private
References loader_.
Referenced by Start().
OnURLLoadComplete()
void ZeroSuggestProvider::OnURLLoadComplete (const network::SimpleURLLoader * source, std::unique_ptr< std::string > response_body) private
References AutocompleteProvider::done_, SearchSuggestionParser::ExtractJsonData(), listener_, loader_, NONE, AutocompleteProviderListener::OnProviderUpdate(), result_type_running_, and UpdateResults().
Referenced by Start().
operator=()
ZeroSuggestProvider& ZeroSuggestProvider::operator= (const ZeroSuggestProvider &) private delete
RecordDeletionResult()
void ZeroSuggestProvider::RecordDeletionResult (bool success) override private virtual
Implements BaseSearchProvider.
RegisterProfilePrefs()
void ZeroSuggestProvider::RegisterProfilePrefs (PrefRegistrySimple * registry) static
References omnibox::kZeroSuggestCachedResults.
ResetSession()
void ZeroSuggestProvider::ResetSession () override virtual
Reimplemented from AutocompleteProvider.
References BaseSearchProvider::set_field_trial_triggered().
ShouldAppendExtraParams()
bool ZeroSuggestProvider::ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult & result) const override private virtual
Implements BaseSearchProvider.
Start()
void ZeroSuggestProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References AllowZeroSuggestSuggestions(), BaseSearchProvider::client(), RemoteSuggestionsService::CreateSuggestionsRequest(), AutocompleteInput::current_page_classification(), current_page_classification_, current_query_, current_text_match_, AutocompleteInput::current_title(), current_title_, AutocompleteInput::current_url(), AutocompleteProvider::done_, RemoteSuggestionsService::EndpointUrl(), AutocompleteInput::focus_type(), AutocompleteProviderClient::GetRemoteSuggestionsService(), AutocompleteProvider::matches_, MatchForCurrentText(), MaybeUseCachedSuggestions(), NONE, OnRemoteSuggestionsLoaderAvailable(), OnURLLoadComplete(), permanent_text_, REMOTE_SEND_URL, result_type_running_, BaseSearchProvider::set_field_trial_triggered(), BaseSearchProvider::set_field_trial_triggered_in_session(), Stop(), AutocompleteInput::text(), TypeOfResultToRun(), and weak_ptr_factory_.
Stop()
void ZeroSuggestProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References current_query_, current_title_, AutocompleteProvider::done_, SearchSuggestionParser::Results::experiment_stats, SearchSuggestionParser::Results::headers_map, loader_, SearchSuggestionParser::Results::navigation_results, NONE, result_type_running_, results_, and SearchSuggestionParser::Results::suggest_results.
Referenced by Start().
TypeOfResultToRun()
ZeroSuggestProvider::ResultType ZeroSuggestProvider::TypeOfResultToRun (AutocompleteProviderClient * client, const AutocompleteInput & input, const GURL & suggest_url) static private
References BaseSearchProvider::CanSendURL(), BaseSearchProvider::client(), AutocompleteInput::current_page_classification(), AutocompleteInput::current_url(), AutocompleteInput::focus_type(), AutocompleteProviderClient::GetTemplateURLService(), BaseSearchProvider::IsNTPPage(), omnibox::kClobberTriggersContextualWebZeroSuggest, omnibox::kOmniboxTrendingZeroPrefixSuggestionsOnNTP, omnibox::kOnFocusSuggestionsContextualWeb, omnibox::kOnFocusSuggestionsContextualWebAllowSRP, omnibox::kOnFocusSuggestionsContextualWebOnContent, NONE, REMOTE_NO_URL, and REMOTE_SEND_URL.
Referenced by Start().
UpdateResults()
bool ZeroSuggestProvider::UpdateResults (const std::string & json_data) private
References BaseSearchProvider::client(), ConvertResultsToAutocompleteMatches(), SearchSuggestionParser::DeserializeJsonData(), AutocompleteProviderClient::GetPrefs(), omnibox::kZeroSuggestCachedResults, SearchSuggestionParser::Results::navigation_results, BaseSearchProvider::ParseSuggestResults(), REMOTE_NO_URL, result_type_running_, results_, and SearchSuggestionParser::Results::suggest_results.
Referenced by OnURLLoadComplete().
Member Data Documentation
current_page_classification_
metrics::OmniboxEventProto::PageClassification ZeroSuggestProvider::current_page_classification_ private
Initial value:
=
      metrics::OmniboxEventProto::INVALID_SPEC
Referenced by GetInput(), and Start().
current_query_
std::string ZeroSuggestProvider::current_query_ private
Referenced by GetInput(), MatchForCurrentText(), Start(), and Stop().
current_text_match_
AutocompleteMatch ZeroSuggestProvider::current_text_match_ private
Referenced by Start().
current_title_
std::u16string ZeroSuggestProvider::current_title_ private
Referenced by GetInput(), MatchForCurrentText(), Start(), and Stop().
listener_
AutocompleteProviderListener* ZeroSuggestProvider::listener_ private
Referenced by OnURLLoadComplete().
loader_
std::unique_ptr<network::SimpleURLLoader> ZeroSuggestProvider::loader_ private
Referenced by OnRemoteSuggestionsLoaderAvailable(), OnURLLoadComplete(), and Stop().
permanent_text_
std::u16string ZeroSuggestProvider::permanent_text_ private
Referenced by MatchForCurrentText(), and Start().
result_type_running_
ResultType ZeroSuggestProvider::result_type_running_ private
Referenced by GetResultTypeRunningForTesting(), MaybeUseCachedSuggestions(), OnURLLoadComplete(), Start(), Stop(), and UpdateResults().
results_
SearchSuggestionParser::Results ZeroSuggestProvider::results_ private
Referenced by AddProviderInfo(), ConvertResultsToAutocompleteMatches(), experiment_stats(), headers_map(), hidden_group_ids(), MatchForCurrentText(), MaybeUseCachedSuggestions(), Stop(), and UpdateResults().
weak_ptr_factory_
base::WeakPtrFactory<ZeroSuggestProvider> ZeroSuggestProvider::weak_ptr_factory_ {this} private
Referenced by Start().
The documentation for this class was generated from the following files:
components/omnibox/browser/zero_suggest_provider.h
components/omnibox/browser/zero_suggest_provider.cc