Chromium Omnibox: LocalHistoryZeroSuggestProvider Class Reference
LocalHistoryZeroSuggestProvider Class Reference
#include <local_history_zero_suggest_provider.h>
Public Member Functions
void Start (const AutocompleteInput &input, bool minimal_changes) override
void DeleteMatch (const AutocompleteMatch &match) override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static LocalHistoryZeroSuggestProvider * Create (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (LocalHistoryZeroSuggestProviderTest, Input)
LocalHistoryZeroSuggestProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
~LocalHistoryZeroSuggestProvider () override
LocalHistoryZeroSuggestProvider (const LocalHistoryZeroSuggestProvider &)=delete
LocalHistoryZeroSuggestProvider & operator= (const LocalHistoryZeroSuggestProvider &)=delete
void QueryURLDatabase (const AutocompleteInput &input)
void OnHistoryQueryResults (const std::u16string &suggestion, const base::TimeTicks &query_time, history::QueryResults results)
Private Attributes
const size_t max_matches_
AutocompleteProviderClient *const client_
AutocompleteProviderListener *const listener_
base::CancelableTaskTracker history_task_tracker_
base::WeakPtrFactory< LocalHistoryZeroSuggestProvider > weak_ptr_factory_ {this}
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
LocalHistoryZeroSuggestProvider() [1/2]
LocalHistoryZeroSuggestProvider::LocalHistoryZeroSuggestProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) private
Referenced by Create().
~LocalHistoryZeroSuggestProvider()
LocalHistoryZeroSuggestProvider::~LocalHistoryZeroSuggestProvider () override private
LocalHistoryZeroSuggestProvider() [2/2]
LocalHistoryZeroSuggestProvider::LocalHistoryZeroSuggestProvider (const LocalHistoryZeroSuggestProvider &) private delete
Member Function Documentation
Create()
LocalHistoryZeroSuggestProvider * LocalHistoryZeroSuggestProvider::Create (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) static
References LocalHistoryZeroSuggestProvider().
Referenced by AutocompleteController::AutocompleteController().
DeleteMatch()
void LocalHistoryZeroSuggestProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
References client_, AutocompleteMatch::contents, AutocompleteProviderClient::GetHistoryService(), OmniboxFieldTrial::GetLocalHistoryZeroSuggestAgeThreshold(), AutocompleteProviderClient::GetTemplateURLService(), history_task_tracker_, AutocompleteProvider::matches_, OnHistoryQueryResults(), and weak_ptr_factory_.
FRIEND_TEST_ALL_PREFIXES()
LocalHistoryZeroSuggestProvider::FRIEND_TEST_ALL_PREFIXES (LocalHistoryZeroSuggestProviderTest , Input) private
OnHistoryQueryResults()
void LocalHistoryZeroSuggestProvider::OnHistoryQueryResults (const std::u16string & suggestion, const base::TimeTicks & query_time, history::QueryResults results) private
References client_, AutocompleteProviderClient::GetHistoryService(), and AutocompleteProviderClient::GetTemplateURLService().
Referenced by DeleteMatch().
operator=()
LocalHistoryZeroSuggestProvider& LocalHistoryZeroSuggestProvider::operator= (const LocalHistoryZeroSuggestProvider &) private delete
QueryURLDatabase()
void LocalHistoryZeroSuggestProvider::QueryURLDatabase (const AutocompleteInput & input) private
References AutocompleteProviderClient::AllowDeletingBrowserHistory(), client_, BaseSearchProvider::CreateSearchSuggestion(), AutocompleteMatch::deletable, AutocompleteProvider::done_, AutocompleteProviderClient::GetHistoryService(), OmniboxFieldTrial::GetLocalHistoryZeroSuggestAgeThreshold(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteProviderClient::IsAuthenticated(), kLocalHistoryZPSAuthenticatedRelevance, kLocalHistoryZPSUnauthenticatedRelevance, listener_, AutocompleteProvider::matches_, max_matches_, AutocompleteProviderListener::OnProviderUpdate(), and AutocompleteMatchType::SEARCH_HISTORY.
Referenced by Start().
Start()
void LocalHistoryZeroSuggestProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References client_, AutocompleteInput::current_page_classification(), omnibox::DEFAULT, AutocompleteProvider::done_, AutocompleteInput::focus_type(), AutocompleteProviderClient::GetTemplateURLService(), BaseSearchProvider::IsNTPPage(), AutocompleteProviderClient::IsOffTheRecord(), AutocompleteProvider::matches_, QueryURLDatabase(), and AutocompleteInput::type().
Member Data Documentation
client_
AutocompleteProviderClient* const LocalHistoryZeroSuggestProvider::client_ private
Referenced by DeleteMatch(), OnHistoryQueryResults(), QueryURLDatabase(), and Start().
history_task_tracker_
base::CancelableTaskTracker LocalHistoryZeroSuggestProvider::history_task_tracker_ private
Referenced by DeleteMatch().
listener_
AutocompleteProviderListener* const LocalHistoryZeroSuggestProvider::listener_ private
Referenced by QueryURLDatabase().
max_matches_
const size_t LocalHistoryZeroSuggestProvider::max_matches_ private
Referenced by QueryURLDatabase().
weak_ptr_factory_
base::WeakPtrFactory<LocalHistoryZeroSuggestProvider> LocalHistoryZeroSuggestProvider::weak_ptr_factory_ {this} private
Referenced by DeleteMatch().
The documentation for this class was generated from the following files:
components/omnibox/browser/local_history_zero_suggest_provider.h
components/omnibox/browser/local_history_zero_suggest_provider.cc