Chromium Omnibox: BaseSearchProvider Class Reference
BaseSearchProvider Class Reference abstract
#include <base_search_provider.h>
Public Member Functions
BaseSearchProvider (AutocompleteProvider::Type type, AutocompleteProviderClient *client)
BaseSearchProvider (const BaseSearchProvider &)=delete
BaseSearchProvider & operator= (const BaseSearchProvider &)=delete
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
bool field_trial_triggered_in_session () const
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Start (const AutocompleteInput &input, bool minimal_changes)=0
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static bool ShouldPrefetch (const AutocompleteMatch &match)
static AutocompleteMatch CreateSearchSuggestion (const std::u16string &suggestion, AutocompleteMatchType::Type type, bool from_keyword_provider, const TemplateURL *template_url, const SearchTermsData &search_terms_data)
static AutocompleteMatch CreateSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const bool in_keyword_mode, const SearchSuggestionParser::SuggestResult &suggestion, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion, bool append_extra_query_params_from_command_line)
static AutocompleteMatch CreateOnDeviceSearchSuggestion (AutocompleteProvider *autocomplete_provider, const AutocompleteInput &input, const std::u16string &suggestion, int relevance, const TemplateURL *template_url, const SearchTermsData &search_terms_data, int accepted_suggestion)
static void AppendSuggestClientToAdditionalQueryParams (const TemplateURL *template_url, const SearchTermsData &search_terms_data, metrics::OmniboxEventProto::PageClassification page_classification, TemplateURLRef::SearchTermsArgs *search_terms_args)
static bool IsNTPPage (metrics::OmniboxEventProto::PageClassification classification)
static bool IsSearchResultsPage (metrics::OmniboxEventProto::PageClassification classification)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types
typedef std::pair< std::u16string, std::string > MatchKey
typedef std::map< MatchKey, AutocompleteMatch > MatchMap
typedef std::vector< std::unique_ptr< SuggestionDeletionHandler > > SuggestionDeletionHandlers
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions
~BaseSearchProvider () override
void SetDeletionURL (const std::string &deletion_url, AutocompleteMatch *match)
void AddMatchToMap (const SearchSuggestionParser::SuggestResult &result, const std::string &metadata, int accepted_suggestion, bool mark_as_deletable, bool in_keyword_mode, MatchMap *map)
bool ParseSuggestResults (const base::Value &root_val, int default_result_relevance, bool is_keyword_result, SearchSuggestionParser::Results *results)
virtual const TemplateURL * GetTemplateURL (bool is_keyword) const =0
virtual const AutocompleteInput GetInput (bool is_keyword) const =0
virtual bool ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult &result) const =0
virtual void RecordDeletionResult (bool success)=0
AutocompleteProviderClient * client ()
const AutocompleteProviderClient * client () const
bool field_trial_triggered () const
void set_field_trial_triggered (bool triggered)
void set_field_trial_triggered_in_session (bool triggered)
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions
static std::u16string GetFillIntoEdit (const SearchSuggestionParser::SuggestResult &suggest_result, const TemplateURL *template_url)
static bool CanSendURL (const GURL &current_page_url, const GURL &suggest_url, const TemplateURL *template_url, metrics::OmniboxEventProto::PageClassification page_classification, const SearchTermsData &search_terms_data, AutocompleteProviderClient *client, bool sending_search_terms)
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Static Protected Attributes
static const char kRelevanceFromServerKey []
static const char kShouldPrefetchKey [] = "should_prefetch"
static const char kSuggestMetadataKey [] = "suggest_metadata"
static const char kDeletionUrlKey [] = "deletion_url"
static const char kTrue [] = "true"
static const char kFalse [] = "false"
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (SearchProviderTest, TestDeleteMatch)
void DeleteMatchFromMatches (const AutocompleteMatch &match)
void OnDeletionComplete (bool success, SuggestionDeletionHandler *handler)
Private Attributes
AutocompleteProviderClient * client_
bool field_trial_triggered_
bool field_trial_triggered_in_session_
SuggestionDeletionHandlers deletion_handlers_
Friends
class SearchProviderTest
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Member Typedef Documentation
MatchKey
typedef std::pair<std::u16string, std::string> BaseSearchProvider::MatchKey protected
MatchMap
typedef std::map<MatchKey, AutocompleteMatch> BaseSearchProvider::MatchMap protected
SuggestionDeletionHandlers
typedef std::vector<std::unique_ptr<SuggestionDeletionHandler> > BaseSearchProvider::SuggestionDeletionHandlers protected
Constructor & Destructor Documentation
BaseSearchProvider() [1/2]
BaseSearchProvider::BaseSearchProvider (AutocompleteProvider::Type type, AutocompleteProviderClient * client)
BaseSearchProvider() [2/2]
BaseSearchProvider::BaseSearchProvider (const BaseSearchProvider &) delete
~BaseSearchProvider()
BaseSearchProvider::~BaseSearchProvider () override protected
Member Function Documentation
AddMatchToMap()
void BaseSearchProvider::AddMatchToMap (const SearchSuggestionParser::SuggestResult & result, const std::string & metadata, int accepted_suggestion, bool mark_as_deletable, bool in_keyword_mode, MatchMap * map) protected
References AutocompleteMatch::answer, client_, CreateSearchSuggestion(), AutocompleteMatch::deletable, SearchSuggestionParser::Result::deletion_url(), AutocompleteMatch::destination_url, AutocompleteMatch::duplicate_matches, SearchSuggestionParser::Result::from_keyword(), GetInput(), GetTemplateURL(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteMatch::keyword, kFalse, kRelevanceFromServerKey, kShouldPrefetchKey, kSuggestMetadataKey, kTrue, AutocompleteMatch::RecordAdditionalInfo(), AutocompleteMatch::relevance, SearchSuggestionParser::Result::relevance_from_server(), AutocompleteMatch::search_terms_args, SetDeletionURL(), SearchSuggestionParser::SuggestResult::should_prefetch(), ShouldAppendExtraParams(), ShouldPrefetch(), and SearchSuggestionParser::SuggestResult::suggestion().
Referenced by SearchProvider::AddSuggestResultsToMap(), SearchProvider::AddTransformedHistoryResultsToMap(), SearchProvider::ConvertResultsToAutocompleteMatches(), ZeroSuggestProvider::ConvertResultsToAutocompleteMatches(), and VoiceSuggestProvider::Start().
AddProviderInfo()
void BaseSearchProvider::AddProviderInfo (ProvidersInfo * provider_info) const override virtual
Reimplemented from AutocompleteProvider.
Reimplemented in ZeroSuggestProvider.
References AutocompleteProvider::AsOmniboxEventProviderType(), AutocompleteProvider::done_, field_trial_triggered_, field_trial_triggered_in_session_, and OmniboxFieldTrial::GetActiveSuggestFieldTrialHashes().
Referenced by ZeroSuggestProvider::AddProviderInfo().
AppendSuggestClientToAdditionalQueryParams()
void BaseSearchProvider::AppendSuggestClientToAdditionalQueryParams (const TemplateURL * template_url, const SearchTermsData & search_terms_data, metrics::OmniboxEventProto::PageClassification page_classification, TemplateURLRef::SearchTermsArgs * search_terms_args) static
Referenced by SearchProvider::CreateSuggestLoader(), and RemoteSuggestionsService::EndpointUrl().
CanSendURL()
bool BaseSearchProvider::CanSendURL (const GURL & current_page_url, const GURL & suggest_url, const TemplateURL * template_url, metrics::OmniboxEventProto::PageClassification page_classification, const SearchTermsData & search_terms_data, AutocompleteProviderClient * client, bool sending_search_terms) static protected
References client(), IsNTPPage(), AutocompleteProviderClient::IsOffTheRecord(), AutocompleteProviderClient::IsPersonalizedUrlDataCollectionActive(), and AutocompleteProviderClient::SearchSuggestEnabled().
Referenced by SearchProvider::CreateSuggestLoader(), ZeroSuggestProvider::TypeOfResultToRun(), and ZeroSuggestProvider::ZeroSuggestProvider().
client() [1/2]
AutocompleteProviderClient* BaseSearchProvider::client () inline protected
References client_.
Referenced by ZeroSuggestProvider::AllowZeroSuggestSuggestions(), CanSendURL(), ZeroSuggestProvider::ConvertResultsToAutocompleteMatches(), ZeroSuggestProvider::Create(), SearchProvider::CreateSuggestLoader(), DeleteMatch(), ZeroSuggestProvider::DeleteMatch(), SearchProvider::DoHistoryQuery(), ZeroSuggestProvider::GetInput(), VoiceSuggestProvider::GetTemplateURL(), ZeroSuggestProvider::GetTemplateURL(), SearchProvider::IsQuerySuitableForSuggest(), SearchProvider::LogLoadComplete(), ZeroSuggestProvider::MatchForCurrentText(), ZeroSuggestProvider::MaybeUseCachedSuggestions(), SearchProvider::NavigationToMatch(), ZeroSuggestProvider::NavigationToMatch(), SearchProvider::OnTemplateURLServiceChanged(), SearchProvider::PrefetchImages(), SearchProvider::Run(), SearchProvider::ScoreHistoryResultsHelper(), SearchProvider::SearchProvider(), SearchProvider::Start(), ZeroSuggestProvider::Start(), ZeroSuggestProvider::TypeOfResultToRun(), ZeroSuggestProvider::UpdateResults(), and ZeroSuggestProvider::ZeroSuggestProvider().
client() [2/2]
const AutocompleteProviderClient* BaseSearchProvider::client () const inline protected
References client_.
CreateOnDeviceSearchSuggestion()
AutocompleteMatch BaseSearchProvider::CreateOnDeviceSearchSuggestion (AutocompleteProvider * autocomplete_provider, const AutocompleteInput & input, const std::u16string & suggestion, int relevance, const TemplateURL * template_url, const SearchTermsData & search_terms_data, int accepted_suggestion) static
References CreateSearchSuggestion(), AutocompleteMatchType::SEARCH_SUGGEST, SearchSuggestionParser::Result::set_received_after_last_keystroke(), and AutocompleteInput::text().
Referenced by OnDeviceHeadProvider::SearchDone().
CreateSearchSuggestion() [1/2]
AutocompleteMatch BaseSearchProvider::CreateSearchSuggestion (AutocompleteProvider * autocomplete_provider, const AutocompleteInput & input, const bool in_keyword_mode, const SearchSuggestionParser::SuggestResult & suggestion, const TemplateURL * template_url, const SearchTermsData & search_terms_data, int accepted_suggestion, bool append_extra_query_params_from_command_line) static
References SearchSuggestionParser::SuggestResult::additional_query_params(), AutocompleteMatch::AddLastClassificationIfNecessary(), AutocompleteMatch::allowed_to_be_default_match, SearchSuggestionParser::SuggestResult::annotation(), AutocompleteMatch::answer, SearchSuggestionParser::SuggestResult::answer(), AutocompleteMatchType::CALCULATOR, AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteMatch::from_keyword, SearchSuggestionParser::Result::from_keyword(), GetFillIntoEdit(), AutocompleteMatch::image_dominant_color, SearchSuggestionParser::SuggestResult::image_dominant_color(), AutocompleteMatch::image_url, SearchSuggestionParser::SuggestResult::image_url(), AutocompleteMatch::inline_autocompletion, kACMatchPropertyContentsPrefix, kACMatchPropertyContentsStartIndex, kACMatchPropertySuggestionText, AutocompleteMatch::keyword, SearchSuggestionParser::Result::match_contents(), SearchSuggestionParser::Result::match_contents_class(), SearchSuggestionParser::SuggestResult::match_contents_prefix(), AutocompleteMatch::ACMatchClassification::NONE, AutocompleteInput::prevent_inline_autocomplete(), SearchSuggestionParser::Result::received_after_last_keystroke(), AutocompleteMatch::RecordAdditionalInfo(), SearchSuggestionParser::Result::relevance(), AutocompleteMatchType::SEARCH_SUGGEST_TAIL, AutocompleteMatch::search_terms_args, AutocompleteMatch::subtypes, SearchSuggestionParser::Result::subtypes(), SearchSuggestionParser::SuggestResult::suggestion(), AutocompleteMatch::suggestion_group_id, SearchSuggestionParser::SuggestResult::suggestion_group_id(), AutocompleteInput::text(), AutocompleteMatch::transition, and SearchSuggestionParser::Result::type().
CreateSearchSuggestion() [2/2]
AutocompleteMatch BaseSearchProvider::CreateSearchSuggestion (const std::u16string & suggestion, AutocompleteMatchType::Type type, bool from_keyword_provider, const TemplateURL * template_url, const SearchTermsData & search_terms_data) static
References SearchSuggestionParser::Result::set_received_after_last_keystroke(), and AutocompleteProvider::type().
Referenced by AddMatchToMap(), CreateOnDeviceSearchSuggestion(), ShortcutsBackend::MatchToMatchCore(), and LocalHistoryZeroSuggestProvider::QueryURLDatabase().
DeleteMatch()
void BaseSearchProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
Reimplemented in ZeroSuggestProvider.
References client(), client_, AutocompleteMatch::contents, AutocompleteMatch::deletable, DeleteMatchFromMatches(), AutocompleteProviderClient::DeleteMatchingURLsForKeywordFromHistory(), deletion_handlers_, AutocompleteMatch::GetAdditionalInfo(), AutocompleteMatch::GetTemplateURL(), AutocompleteProviderClient::GetTemplateURLService(), kDeletionUrlKey, OnDeletionComplete(), and SuggestionDeletionHandler::SuggestionDeletionHandler().
Referenced by ZeroSuggestProvider::DeleteMatch().
DeleteMatchFromMatches()
void BaseSearchProvider::DeleteMatchFromMatches (const AutocompleteMatch & match) private
References AutocompleteProvider::matches_.
Referenced by DeleteMatch().
field_trial_triggered()
bool BaseSearchProvider::field_trial_triggered () const inline protected
References field_trial_triggered_.
field_trial_triggered_in_session()
bool BaseSearchProvider::field_trial_triggered_in_session () const inline
References field_trial_triggered_in_session_.
Referenced by AutocompleteController::UpdateMatchDestinationURLWithQueryFormulationTime().
FRIEND_TEST_ALL_PREFIXES()
BaseSearchProvider::FRIEND_TEST_ALL_PREFIXES (SearchProviderTest , TestDeleteMatch) private
GetFillIntoEdit()
std::u16string BaseSearchProvider::GetFillIntoEdit (const SearchSuggestionParser::SuggestResult & suggest_result, const TemplateURL * template_url) static protected
References SearchSuggestionParser::Result::from_keyword(), and SearchSuggestionParser::SuggestResult::suggestion().
Referenced by CreateSearchSuggestion(), and SearchProvider::PersistTopSuggestions().
GetInput()
virtual const AutocompleteInput BaseSearchProvider::GetInput (bool is_keyword) const protected pure virtual
Implemented in ZeroSuggestProvider, VoiceSuggestProvider, and SearchProvider.
Referenced by AddMatchToMap(), and ParseSuggestResults().
GetTemplateURL()
virtual const TemplateURL* BaseSearchProvider::GetTemplateURL (bool is_keyword) const protected pure virtual
Implemented in ZeroSuggestProvider, VoiceSuggestProvider, and SearchProvider.
Referenced by AddMatchToMap().
IsNTPPage()
bool BaseSearchProvider::IsNTPPage (metrics::OmniboxEventProto::PageClassification classification) static
Referenced by ZeroSuggestProvider::AllowZeroSuggestSuggestions(), CanSendURL(), LocalHistoryZeroSuggestProvider::Start(), and ZeroSuggestProvider::TypeOfResultToRun().
IsSearchResultsPage()
bool BaseSearchProvider::IsSearchResultsPage (metrics::OmniboxEventProto::PageClassification classification) static
OnDeletionComplete()
void BaseSearchProvider::OnDeletionComplete (bool success, SuggestionDeletionHandler * handler) private
References deletion_handlers_, and RecordDeletionResult().
Referenced by DeleteMatch().
operator=()
BaseSearchProvider& BaseSearchProvider::operator= (const BaseSearchProvider &) delete
ParseSuggestResults()
bool BaseSearchProvider::ParseSuggestResults (const base::Value & root_val, int default_result_relevance, bool is_keyword_result, SearchSuggestionParser::Results * results) protected
References client_, SearchSuggestionParser::Results::field_trial_triggered, field_trial_triggered_, field_trial_triggered_in_session_, GetInput(), AutocompleteProviderClient::GetSchemeClassifier(), and SearchSuggestionParser::ParseSuggestResults().
Referenced by ZeroSuggestProvider::MaybeUseCachedSuggestions(), SearchProvider::OnURLLoadComplete(), and ZeroSuggestProvider::UpdateResults().
RecordDeletionResult()
virtual void BaseSearchProvider::RecordDeletionResult (bool success) protected pure virtual
Implemented in ZeroSuggestProvider, VoiceSuggestProvider, and SearchProvider.
Referenced by OnDeletionComplete().
set_field_trial_triggered()
void BaseSearchProvider::set_field_trial_triggered (bool triggered) inline protected
References field_trial_triggered_.
Referenced by SearchProvider::ResetSession(), ZeroSuggestProvider::ResetSession(), SearchProvider::Start(), and ZeroSuggestProvider::Start().
set_field_trial_triggered_in_session()
void BaseSearchProvider::set_field_trial_triggered_in_session (bool triggered) inline protected
References field_trial_triggered_in_session_.
Referenced by SearchProvider::ResetSession(), and ZeroSuggestProvider::Start().
SetDeletionURL()
void BaseSearchProvider::SetDeletionURL (const std::string & deletion_url, AutocompleteMatch * match) protected
References client_, AutocompleteMatch::deletable, AutocompleteProviderClient::GetTemplateURLService(), kDeletionUrlKey, and AutocompleteMatch::RecordAdditionalInfo().
Referenced by AddMatchToMap(), and SearchProvider::NavigationToMatch().
ShouldAppendExtraParams()
virtual bool BaseSearchProvider::ShouldAppendExtraParams (const SearchSuggestionParser::SuggestResult & result) const protected pure virtual
Implemented in ZeroSuggestProvider, VoiceSuggestProvider, and SearchProvider.
Referenced by AddMatchToMap().
ShouldPrefetch()
bool BaseSearchProvider::ShouldPrefetch (const AutocompleteMatch & match) static
References AutocompleteMatch::GetAdditionalInfo(), kShouldPrefetchKey, and kTrue.
Referenced by AddMatchToMap().
Friends And Related Function Documentation
SearchProviderTest
friend class SearchProviderTest friend
Member Data Documentation
client_
AutocompleteProviderClient* BaseSearchProvider::client_ private
Referenced by AddMatchToMap(), client(), DeleteMatch(), ParseSuggestResults(), and SetDeletionURL().
deletion_handlers_
SuggestionDeletionHandlers BaseSearchProvider::deletion_handlers_ private
Referenced by DeleteMatch(), and OnDeletionComplete().
field_trial_triggered_
bool BaseSearchProvider::field_trial_triggered_ private
Referenced by AddProviderInfo(), field_trial_triggered(), ParseSuggestResults(), and set_field_trial_triggered().
field_trial_triggered_in_session_
bool BaseSearchProvider::field_trial_triggered_in_session_ private
Referenced by AddProviderInfo(), field_trial_triggered_in_session(), ParseSuggestResults(), and set_field_trial_triggered_in_session().
kDeletionUrlKey
const char BaseSearchProvider::kDeletionUrlKey = "deletion_url" static protected
Referenced by DeleteMatch(), and SetDeletionURL().
kFalse
const char BaseSearchProvider::kFalse = "false" static protected
Referenced by AddMatchToMap(), and SearchProvider::NavigationToMatch().
kRelevanceFromServerKey
const char BaseSearchProvider::kRelevanceFromServerKey static protected
Initial value:
=
    "relevance_from_server"
Referenced by AddMatchToMap(), SearchProvider::ConvertResultsToAutocompleteMatches(), and SearchProvider::NavigationToMatch().
kShouldPrefetchKey
const char BaseSearchProvider::kShouldPrefetchKey = "should_prefetch" static protected
Referenced by AddMatchToMap(), SearchProvider::NavigationToMatch(), and ShouldPrefetch().
kSuggestMetadataKey
const char BaseSearchProvider::kSuggestMetadataKey = "suggest_metadata" static protected
Referenced by AddMatchToMap(), and SearchProvider::GetSuggestMetadata().
kTrue
const char BaseSearchProvider::kTrue = "true" static protected
Referenced by AddMatchToMap(), SearchProvider::ConvertResultsToAutocompleteMatches(), SearchProvider::NavigationToMatch(), and ShouldPrefetch().
The documentation for this class was generated from the following files:
components/omnibox/browser/base_search_provider.h
components/omnibox/browser/base_search_provider.cc