Chromium Omnibox: OmniboxMatchCellView Class Reference
OmniboxMatchCellView Class Reference
#include <omnibox_match_cell_view.h>
Public Member Functions
METADATA_HEADER (OmniboxMatchCellView)
OmniboxMatchCellView (OmniboxResultView *result_view)
OmniboxMatchCellView (const OmniboxMatchCellView &)=delete
OmniboxMatchCellView & operator= (const OmniboxMatchCellView &)=delete
~OmniboxMatchCellView () override
views::ImageView * icon ()
OmniboxTextView * content ()
OmniboxTextView * description ()
OmniboxTextView * separator ()
void OnMatchUpdate (const OmniboxResultView *result_view, const AutocompleteMatch &match)
void SetImage (const gfx::ImageSkia &image)
gfx::Insets GetInsets () const override
void Layout () override
bool GetCanProcessEventsWithinSubtree () const override
gfx::Size CalculatePreferredSize () const override
Static Public Member Functions
static void ComputeMatchMaxWidths (int contents_width, int separator_width, int description_width, int available_width, bool description_on_separate_line, bool allow_shrinking_contents, int *contents_max_width, int *description_max_width)
static int GetTextIndent ()
Static Public Attributes
static constexpr int kMarginLeft = 4
static constexpr int kMarginRight = 8
static constexpr int kImageBoundsWidth = 40
Private Types
enum class LayoutStyle { ONE_LINE_SUGGESTION , TWO_LINE_SUGGESTION }
Private Member Functions
void SetTailSuggestCommonPrefixWidth (const std::u16string &common_prefix)
Private Attributes
bool is_rich_suggestion_ = false
bool is_search_type_ = false
LayoutStyle layout_style_ = LayoutStyle::ONE_LINE_SUGGESTION
views::ImageView * icon_view_
views::ImageView * answer_image_view_
OmniboxTextView * content_view_
OmniboxTextView * description_view_
OmniboxTextView * separator_view_
int ellipsis_width_ = 0
int tail_suggest_common_prefix_width_ = 0
Member Enumeration Documentation
LayoutStyle
enum OmniboxMatchCellView::LayoutStyle strong private
Enumerator
ONE_LINE_SUGGESTION
TWO_LINE_SUGGESTION
Constructor & Destructor Documentation
OmniboxMatchCellView() [1/2]
OmniboxMatchCellView::OmniboxMatchCellView (OmniboxResultView * result_view) explicit
References answer_image_view_, content_view_, description_view_, icon_view_, OmniboxTextView::OmniboxTextView(), separator_view_, and OmniboxTextView::SetText().
Referenced by OmniboxResultView::OmniboxResultView().
OmniboxMatchCellView() [2/2]
OmniboxMatchCellView::OmniboxMatchCellView (const OmniboxMatchCellView &) delete
~OmniboxMatchCellView()
OmniboxMatchCellView::~OmniboxMatchCellView () override default
Member Function Documentation
CalculatePreferredSize()
gfx::Size OmniboxMatchCellView::CalculatePreferredSize () const override
References content_view_, description_view_, OmniboxTextView::GetHeightForWidth(), GetInsets(), OmniboxTextView::GetLineHeight(), GetTextIndent(), layout_style_, and TWO_LINE_SUGGESTION.
Referenced by OmniboxResultView::SetWidths().
ComputeMatchMaxWidths()
void OmniboxMatchCellView::ComputeMatchMaxWidths (int contents_width, int separator_width, int description_width, int available_width, bool description_on_separate_line, bool allow_shrinking_contents, int * contents_max_width, int * description_max_width) static
Referenced by Layout().
content()
OmniboxTextView* OmniboxMatchCellView::content () inline
References content_view_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), and OmniboxResultView::SetMatch().
description()
OmniboxTextView* OmniboxMatchCellView::description () inline
References description_view_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), and OmniboxResultView::SetMatch().
GetCanProcessEventsWithinSubtree()
bool OmniboxMatchCellView::GetCanProcessEventsWithinSubtree () const override
GetInsets()
gfx::Insets OmniboxMatchCellView::GetInsets () const override
References kMarginLeft, kMarginRight, layout_style_, and ONE_LINE_SUGGESTION.
Referenced by CalculatePreferredSize().
GetTextIndent()
int OmniboxMatchCellView::GetTextIndent () static
Referenced by CalculatePreferredSize(), Layout(), OmniboxSuggestionButtonRowView::OmniboxSuggestionButtonRowView(), and OmniboxResultView::SetWidths().
icon()
views::ImageView* OmniboxMatchCellView::icon () inline
References icon_view_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxResultView::OmniboxResultView(), and OnMatchUpdate().
Layout()
void OmniboxMatchCellView::Layout () override
References answer_image_view_, ComputeMatchMaxWidths(), content_view_, description_view_, OmniboxTextView::GetHeightForWidth(), OmniboxTextView::GetLineHeight(), OmniboxTextView::GetText(), GetTextIndent(), icon_view_, is_rich_suggestion_, is_search_type_, kImageBoundsWidth, layout_style_, separator_view_, tail_suggest_common_prefix_width_, and TWO_LINE_SUGGESTION.
METADATA_HEADER()
OmniboxMatchCellView::METADATA_HEADER (OmniboxMatchCellView)
OnMatchUpdate()
void OmniboxMatchCellView::OnMatchUpdate (const OmniboxResultView * result_view, const AutocompleteMatch & match)
References AutocompleteMatch::answer, answer_image_view_, SuggestionAnswer::ANSWER_TYPE_WEATHER, AutocompleteMatch::AnswerTypeToAnswerIcon(), AutocompleteMatchType::CALCULATOR, OmniboxResultView::GetColor(), icon(), icon_view_, AutocompleteMatch::image_dominant_color, AutocompleteMatch::image_url, is_rich_suggestion_, is_search_type_, AutocompleteMatch::IsSearchType(), layout_style_, ONE_LINE_SUGGESTION, RESULTS_BACKGROUND, AutocompleteMatchType::SEARCH_SUGGEST_TAIL, separator_view_, SetTailSuggestCommonPrefixWidth(), AutocompleteMatch::tail_suggest_common_prefix, TWO_LINE_SUGGESTION, and AutocompleteMatch::type.
Referenced by OmniboxResultView::SetMatch().
operator=()
OmniboxMatchCellView& OmniboxMatchCellView::operator= (const OmniboxMatchCellView &) delete
separator()
OmniboxTextView* OmniboxMatchCellView::separator () inline
References separator_view_.
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons().
SetImage()
void OmniboxMatchCellView::SetImage (const gfx::ImageSkia & image)
References answer_image_view_.
Referenced by OmniboxResultView::SetRichSuggestionImage().
SetTailSuggestCommonPrefixWidth()
void OmniboxMatchCellView::SetTailSuggestCommonPrefixWidth (const std::u16string & common_prefix) private
References content_view_, OmniboxTextView::CreateRenderText(), ellipsis_width_, AutocompleteMatch::kEllipsis, and tail_suggest_common_prefix_width_.
Referenced by OnMatchUpdate().
Member Data Documentation
answer_image_view_
views::ImageView* OmniboxMatchCellView::answer_image_view_ private
Referenced by Layout(), OmniboxMatchCellView(), OnMatchUpdate(), and SetImage().
content_view_
OmniboxTextView* OmniboxMatchCellView::content_view_ private
Referenced by CalculatePreferredSize(), content(), Layout(), OmniboxMatchCellView(), and SetTailSuggestCommonPrefixWidth().
description_view_
OmniboxTextView* OmniboxMatchCellView::description_view_ private
Referenced by CalculatePreferredSize(), description(), Layout(), and OmniboxMatchCellView().
ellipsis_width_
int OmniboxMatchCellView::ellipsis_width_ = 0 private
Referenced by SetTailSuggestCommonPrefixWidth().
icon_view_
views::ImageView* OmniboxMatchCellView::icon_view_ private
Referenced by icon(), Layout(), OmniboxMatchCellView(), and OnMatchUpdate().
is_rich_suggestion_
bool OmniboxMatchCellView::is_rich_suggestion_ = false private
Referenced by Layout(), and OnMatchUpdate().
is_search_type_
bool OmniboxMatchCellView::is_search_type_ = false private
Referenced by Layout(), and OnMatchUpdate().
kImageBoundsWidth
constexpr int OmniboxMatchCellView::kImageBoundsWidth = 40 static constexpr
Referenced by OmniboxRowView::HeaderView::GetInsets(), and Layout().
kMarginLeft
constexpr int OmniboxMatchCellView::kMarginLeft = 4 static constexpr
Referenced by GetInsets(), and OmniboxRowView::HeaderView::GetInsets().
kMarginRight
constexpr int OmniboxMatchCellView::kMarginRight = 8 static constexpr
Referenced by GetInsets(), OmniboxRowView::HeaderView::GetInsets(), and OmniboxResultView::OmniboxResultView().
layout_style_
LayoutStyle OmniboxMatchCellView::layout_style_ = LayoutStyle::ONE_LINE_SUGGESTION private
Referenced by CalculatePreferredSize(), GetInsets(), Layout(), and OnMatchUpdate().
separator_view_
OmniboxTextView* OmniboxMatchCellView::separator_view_ private
Referenced by Layout(), OmniboxMatchCellView(), OnMatchUpdate(), and separator().
tail_suggest_common_prefix_width_
int OmniboxMatchCellView::tail_suggest_common_prefix_width_ = 0 private
Referenced by Layout(), and SetTailSuggestCommonPrefixWidth().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_match_cell_view.h
chrome/browser/ui/views/omnibox/omnibox_match_cell_view.cc