Chromium Omnibox: AutocompleteProvider Class Reference
AutocompleteProvider Class Reference abstract
#include <autocomplete_provider.h>
Public Types
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Public Member Functions
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
virtual void Start (const AutocompleteInput &input, bool minimal_changes)=0
virtual void Stop (bool clear_cached_results, bool due_to_user_inactivity)
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void AddProviderInfo (ProvidersInfo *provider_info) const
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Friends
class base::RefCountedThreadSafe< AutocompleteProvider >
Member Typedef Documentation
FixupReturn
typedef std::pair<bool, std::u16string> AutocompleteProvider::FixupReturn protected
WordMap
typedef std::multimap<char16_t, std::u16string> AutocompleteProvider::WordMap
Member Enumeration Documentation
Type
enum AutocompleteProvider::Type
Enumerator
TYPE_BOOKMARK
TYPE_BUILTIN
TYPE_HISTORY_QUICK
TYPE_HISTORY_URL
TYPE_KEYWORD
TYPE_SEARCH
TYPE_SHORTCUTS
TYPE_ZERO_SUGGEST
TYPE_CLIPBOARD
TYPE_DOCUMENT
TYPE_ON_DEVICE_HEAD
TYPE_ZERO_SUGGEST_LOCAL_HISTORY
TYPE_QUERY_TILE
TYPE_MOST_VISITED_SITES
TYPE_VERBATIM_MATCH
TYPE_VOICE_SUGGEST
Constructor & Destructor Documentation
AutocompleteProvider() [1/2]
AutocompleteProvider::AutocompleteProvider (Type type) explicit
AutocompleteProvider() [2/2]
AutocompleteProvider::AutocompleteProvider (const AutocompleteProvider &) delete
~AutocompleteProvider()
AutocompleteProvider::~AutocompleteProvider () protected virtual
References Stop().
Member Function Documentation
AddProviderInfo()
void AutocompleteProvider::AddProviderInfo (ProvidersInfo * provider_info) const virtual
Reimplemented in ZeroSuggestProvider, OnDeviceHeadProvider, DocumentProvider, ClipboardProvider, and BaseSearchProvider.
AsOmniboxEventProviderType()
metrics::OmniboxEventProto_ProviderType AutocompleteProvider::AsOmniboxEventProviderType () const
References type_, TYPE_BOOKMARK, TYPE_BUILTIN, TYPE_CLIPBOARD, TYPE_DOCUMENT, TYPE_HISTORY_QUICK, TYPE_HISTORY_URL, TYPE_KEYWORD, TYPE_MOST_VISITED_SITES, TYPE_ON_DEVICE_HEAD, TYPE_QUERY_TILE, TYPE_SEARCH, TYPE_SHORTCUTS, TYPE_VERBATIM_MATCH, TYPE_VOICE_SUGGEST, TYPE_ZERO_SUGGEST, and TYPE_ZERO_SUGGEST_LOCAL_HISTORY.
Referenced by BaseSearchProvider::AddProviderInfo(), ClipboardProvider::AddProviderInfo(), and AutocompleteController::DeleteMatch().
ClassifyAllMatchesInString()
ACMatchClassifications AutocompleteProvider::ClassifyAllMatchesInString (const std::u16string & find_text, const std::u16string & text, const bool text_is_search_query, const ACMatchClassifications & original_class = ACMatchClassifications()) static
References ClassifyTermMatches(), FindTermMatches(), AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteMatch::MergeClassifications(), and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by SearchSuggestionParser::SuggestResult::ClassifyMatchContents(), and ShortcutsProvider::ShortcutToACMatch().
DeleteMatch()
void AutocompleteProvider::DeleteMatch (const AutocompleteMatch & match) virtual
Reimplemented in ZeroSuggestProvider, ShortcutsProvider, LocalHistoryZeroSuggestProvider, KeywordProvider, HistoryProvider, DocumentProvider, ClipboardProvider, and BaseSearchProvider.
References GetName().
Referenced by AutocompleteController::DeleteMatch().
done()
bool AutocompleteProvider::done () const inline
References done_.
EstimateMemoryUsage()
size_t AutocompleteProvider::EstimateMemoryUsage () const virtual
Reimplemented in HistoryURLProvider, and HistoryQuickProvider.
References base::trace_event::EstimateMemoryUsage(), and matches_.
Referenced by HistoryQuickProvider::EstimateMemoryUsage(), and HistoryURLProvider::EstimateMemoryUsage().
FixupUserInput()
AutocompleteProvider::FixupReturn AutocompleteProvider::FixupUserInput (const AutocompleteInput & input) static protected
References AutocompleteInput::HasHTTPScheme(), AutocompleteInput::parts(), AutocompleteInput::text(), TrimSchemePrefix(), and AutocompleteInput::type().
Referenced by BookmarkProvider::DoAutocomplete(), ShortcutsProvider::GetMatches(), HistoryQuickProvider::QuickMatchToACMatch(), and HistoryURLProvider::Start().
FRIEND_TEST_ALL_PREFIXES() [1/2]
AutocompleteProvider::FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest , DemoteOnDeviceSearchSuggestions) protected
FRIEND_TEST_ALL_PREFIXES() [2/2]
AutocompleteProvider::FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest , InlineAutocompletion) protected
GetName()
const char * AutocompleteProvider::GetName () const
References type_, and TypeToString().
Referenced by DeleteMatch(), and AutocompleteResult::SortAndCull().
InExplicitExperimentalKeywordMode()
bool AutocompleteProvider::InExplicitExperimentalKeywordMode (const AutocompleteInput & input, const std::u16string & keyword) static
References OmniboxFieldTrial::IsExperimentalKeywordModeEnabled(), IsExplicitlyInKeywordMode(), AutocompleteInput::prefer_keyword(), and AutocompleteInput::text().
Referenced by OmniboxEditModel::InExplicitExperimentalKeywordMode(), SearchProvider::ShouldCurbDefaultSuggestions(), and AutocompleteController::ShouldCurbKeywordDescriptions().
IsExplicitlyInKeywordMode()
bool AutocompleteProvider::IsExplicitlyInKeywordMode (const AutocompleteInput & input, const std::u16string & keyword) static
References AutocompleteInput::keyword_mode_entry_method(), AutocompleteInput::prevent_inline_autocomplete(), and AutocompleteInput::text().
Referenced by InExplicitExperimentalKeywordMode(), and DocumentProvider::IsDocumentProviderAllowed().
matches()
const ACMatches& AutocompleteProvider::matches () const inline
References matches_.
Referenced by SearchProvider::AddNavigationResultsToMatches(), SearchProvider::ConvertResultsToAutocompleteMatches(), HistoryURLProvider::CullRedirects(), HistoryQuickProvider::DoAutocomplete(), BookmarkProvider::DoAutocomplete(), SearchProvider::FindAnswersPrefetchData(), HistoryQuickProvider::FindMaxMatchScore(), DocumentProvider::ParseDocumentSearchResults(), SearchProvider::RemoveExtraAnswers(), HistoryURLProvider::RemoveSubsequentMatchesOf(), HistoryProvider::SpansFromTermMatch(), and KeywordProvider::Start().
operator=()
AutocompleteProvider& AutocompleteProvider::operator= (const AutocompleteProvider &) delete
provider_max_matches()
size_t AutocompleteProvider::provider_max_matches () const inline
References provider_max_matches_.
Referenced by OnDeviceHeadProvider::GetSuggestionsFromModel().
ResetSession()
void AutocompleteProvider::ResetSession () virtual
Reimplemented in ZeroSuggestProvider, SearchProvider, DocumentProvider, and ClipboardProvider.
Start()
virtual void AutocompleteProvider::Start (const AutocompleteInput & input, bool minimal_changes) pure virtual
Implemented in ZeroSuggestVerbatimMatchProvider, ZeroSuggestProvider, VoiceSuggestProvider, ShortcutsProvider, SearchProvider, QueryTileProvider, OnDeviceHeadProvider, MostVisitedSitesProvider, LocalHistoryZeroSuggestProvider, KeywordProvider, HistoryURLProvider, HistoryQuickProvider, DocumentProvider, ClipboardProvider, BuiltinProvider, and BookmarkProvider.
Stop()
void AutocompleteProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) virtual
Reimplemented in ZeroSuggestVerbatimMatchProvider, ZeroSuggestProvider, VoiceSuggestProvider, SearchProvider, QueryTileProvider, OnDeviceHeadProvider, MostVisitedSitesProvider, KeywordProvider, HistoryURLProvider, DocumentProvider, and ClipboardProvider.
References done_.
Referenced by ClipboardProvider::Stop(), and ~AutocompleteProvider().
TrimSchemePrefix()
size_t AutocompleteProvider::TrimSchemePrefix (std::u16string * url, bool trim_https) static
References AutocompleteInput::HasHTTPScheme(), and AutocompleteInput::HasHTTPSScheme().
Referenced by FixupUserInput(), and VerbatimMatchForInput().
type()
Type AutocompleteProvider::type () const inline
References type_.
Referenced by AutocompleteMatch::BetterDuplicate(), KeywordProvider::CalculateRelevance(), SearchProvider::CalculateRelevanceForKeywordVerbatim(), BaseSearchProvider::CreateSearchSuggestion(), HistoryURLProvider::FixupExactSuggestion(), AutocompleteMatch::GetVectorIcon(), AutocompleteMatch::IsOnDeviceSearchSuggestion(), AutocompleteMatch::IsSearchProviderSearchSuggestion(), AutocompleteMatch::IsVerbatimType(), and TypeToString().
TypeToString()
const char * AutocompleteProvider::TypeToString (Type type) static
References type(), TYPE_BOOKMARK, TYPE_BUILTIN, TYPE_CLIPBOARD, TYPE_DOCUMENT, TYPE_HISTORY_QUICK, TYPE_HISTORY_URL, TYPE_KEYWORD, TYPE_MOST_VISITED_SITES, TYPE_ON_DEVICE_HEAD, TYPE_QUERY_TILE, TYPE_SEARCH, TYPE_SHORTCUTS, TYPE_VERBATIM_MATCH, TYPE_VOICE_SUGGEST, TYPE_ZERO_SUGGEST, and TYPE_ZERO_SUGGEST_LOCAL_HISTORY.
Referenced by GetName().
Friends And Related Function Documentation
base::RefCountedThreadSafe< AutocompleteProvider >
friend class base::RefCountedThreadSafe< AutocompleteProvider > friend
Member Data Documentation
done_
bool AutocompleteProvider::done_ protected
Referenced by ClipboardProvider::AddImageMatchCallback(), BaseSearchProvider::AddProviderInfo(), ClipboardProvider::AddProviderInfo(), DocumentProvider::AddProviderInfo(), OnDeviceHeadProvider::AddProviderInfo(), QueryTileProvider::BuildSuggestion(), ClipboardProvider::CreateImageMatch(), HistoryProvider::DeleteMatch(), done(), ClipboardProvider::OnReceiveClipboardContent(), SearchProvider::OnTemplateURLServiceChanged(), DocumentProvider::OnURLLoadComplete(), SearchProvider::OnURLLoadComplete(), ZeroSuggestProvider::OnURLLoadComplete(), HistoryURLProvider::QueryComplete(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), SearchProvider::Run(), OnDeviceHeadProvider::SearchDone(), ClipboardProvider::Start(), DocumentProvider::Start(), HistoryURLProvider::Start(), KeywordProvider::Start(), LocalHistoryZeroSuggestProvider::Start(), OnDeviceHeadProvider::Start(), QueryTileProvider::Start(), SearchProvider::Start(), ZeroSuggestProvider::Start(), SearchProvider::StartOrStopSuggestQuery(), Stop(), DocumentProvider::Stop(), HistoryURLProvider::Stop(), KeywordProvider::Stop(), OnDeviceHeadProvider::Stop(), QueryTileProvider::Stop(), SearchProvider::Stop(), ZeroSuggestProvider::Stop(), and SearchProvider::UpdateDone().
matches_
ACMatches AutocompleteProvider::matches_ protected
Referenced by ClipboardProvider::AddCreatedMatchWithTracking(), BuiltinProvider::AddMatch(), QueryTileProvider::BuildSuggestion(), SearchProvider::ConvertResultsToAutocompleteMatches(), ZeroSuggestProvider::ConvertResultsToAutocompleteMatches(), ClipboardProvider::DeleteMatch(), KeywordProvider::DeleteMatch(), LocalHistoryZeroSuggestProvider::DeleteMatch(), ShortcutsProvider::DeleteMatch(), BaseSearchProvider::DeleteMatchFromMatches(), HistoryProvider::DeleteMatchFromMatches(), DocumentProvider::DemoteMatchesBeyondMax(), HistoryQuickProvider::DoAutocomplete(), BookmarkProvider::DoAutocomplete(), SearchProvider::EnforceConstraints(), EstimateMemoryUsage(), ShortcutsProvider::GetMatches(), BuiltinProvider::HasMatchThatShouldBeDefault(), SearchProvider::IsTopMatchSearchWithURLInput(), matches(), MostVisitedSitesProvider::OnMostVisitedUrlsAvailable(), MostVisitedSitesProvider::OnURLsAvailable(), HistoryURLProvider::PromoteMatchesIfNecessary(), HistoryURLProvider::QueryComplete(), LocalHistoryZeroSuggestProvider::QueryURLDatabase(), SearchProvider::RecordTopSuggestion(), OnDeviceHeadProvider::SearchDone(), BookmarkProvider::Start(), BuiltinProvider::Start(), ClipboardProvider::Start(), HistoryQuickProvider::Start(), HistoryURLProvider::Start(), KeywordProvider::Start(), LocalHistoryZeroSuggestProvider::Start(), OnDeviceHeadProvider::Start(), QueryTileProvider::Start(), SearchProvider::Start(), ShortcutsProvider::Start(), VoiceSuggestProvider::Start(), ZeroSuggestProvider::Start(), ZeroSuggestVerbatimMatchProvider::Start(), DocumentProvider::Stop(), MostVisitedSitesProvider::Stop(), OnDeviceHeadProvider::Stop(), VoiceSuggestProvider::Stop(), ZeroSuggestVerbatimMatchProvider::Stop(), SearchProvider::UpdateMatches(), and DocumentProvider::UpdateResults().
provider_max_matches_
const size_t AutocompleteProvider::provider_max_matches_ protected
Referenced by SearchProvider::ConvertResultsToAutocompleteMatches(), DocumentProvider::DemoteMatchesBeyondMax(), HistoryQuickProvider::DoAutocomplete(), BookmarkProvider::DoAutocomplete(), HistoryURLProvider::DoAutocomplete(), SearchProvider::DoHistoryQuery(), OnDeviceHeadProvider::DoSearch(), ShortcutsProvider::GetMatches(), DocumentProvider::ParseDocumentSearchResults(), provider_max_matches(), BuiltinProvider::Start(), and KeywordProvider::Start().
type_
Type AutocompleteProvider::type_ protected
Referenced by AsOmniboxEventProviderType(), GetName(), and type().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_provider.h
components/omnibox/browser/autocomplete_provider.cc