Chromium Omnibox: AutocompleteMatchType Struct Reference
AutocompleteMatchType Struct Reference
#include <autocomplete_match_type.h>
Public Types
enum Type {
URL_WHAT_YOU_TYPED = 0 , HISTORY_URL = 1 , HISTORY_TITLE = 2 , HISTORY_BODY = 3 ,
HISTORY_KEYWORD = 4 , NAVSUGGEST = 5 , SEARCH_WHAT_YOU_TYPED = 6 , SEARCH_HISTORY = 7 ,
SEARCH_SUGGEST = 8 , SEARCH_SUGGEST_ENTITY = 9 , SEARCH_SUGGEST_TAIL = 10 , SEARCH_SUGGEST_PERSONALIZED = 11 ,
SEARCH_SUGGEST_PROFILE = 12 , SEARCH_OTHER_ENGINE = 13 , EXTENSION_APP_DEPRECATED = 14 , CONTACT_DEPRECATED = 15 ,
BOOKMARK_TITLE = 16 , NAVSUGGEST_PERSONALIZED = 17 , CALCULATOR = 18 , CLIPBOARD_URL = 19 ,
VOICE_SUGGEST = 20 , PHYSICAL_WEB_DEPRECATED = 21 , PHYSICAL_WEB_OVERFLOW_DEPRECATED = 22 , TAB_SEARCH_DEPRECATED = 23 ,
DOCUMENT_SUGGESTION = 24 , PEDAL_DEPRECATED = 25 , CLIPBOARD_TEXT = 26 , CLIPBOARD_IMAGE = 27 ,
TILE_SUGGESTION = 28 , TILE_NAVSUGGEST = 29 , NUM_TYPES
}
Static Public Member Functions
static std::string ToString (AutocompleteMatchType::Type type)
static bool FromInteger (int value, Type *result)
static std::u16string ToAccessibilityLabel (const AutocompleteMatch &match, const std::u16string &match_text, size_t match_index=0, size_t total_matches=0, const std::u16string &additional_message_format=std::u16string(), int *label_prefix_length=nullptr)
Member Enumeration Documentation
Type
enum AutocompleteMatchType::Type
Enumerator
URL_WHAT_YOU_TYPED
HISTORY_URL
HISTORY_TITLE
HISTORY_BODY
HISTORY_KEYWORD
NAVSUGGEST
SEARCH_WHAT_YOU_TYPED
SEARCH_HISTORY
SEARCH_SUGGEST
SEARCH_SUGGEST_ENTITY
SEARCH_SUGGEST_TAIL
SEARCH_SUGGEST_PERSONALIZED
SEARCH_SUGGEST_PROFILE
SEARCH_OTHER_ENGINE
EXTENSION_APP_DEPRECATED
CONTACT_DEPRECATED
BOOKMARK_TITLE
NAVSUGGEST_PERSONALIZED
CALCULATOR
CLIPBOARD_URL
VOICE_SUGGEST
PHYSICAL_WEB_DEPRECATED
PHYSICAL_WEB_OVERFLOW_DEPRECATED
TAB_SEARCH_DEPRECATED
DOCUMENT_SUGGESTION
PEDAL_DEPRECATED
CLIPBOARD_TEXT
CLIPBOARD_IMAGE
TILE_SUGGESTION
TILE_NAVSUGGEST
NUM_TYPES
Member Function Documentation
FromInteger()
bool AutocompleteMatchType::FromInteger (int value, Type * result) static
Referenced by ShortcutsDatabase::LoadShortcuts().
ToAccessibilityLabel()
std::u16string AutocompleteMatchType::ToAccessibilityLabel (const AutocompleteMatch & match, const std::u16string & match_text, size_t match_index = 0, size_t total_matches = 0, const std::u16string & additional_message_format = std::u16string(), int * label_prefix_length = nullptr) static
References AddAdditionalMessaging(), GetAccessibilityBaseLabel(), and OmniboxPopupSelection::kNoMatch.
Referenced by OmniboxResultView::GetAccessibleNodeData(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), and OmniboxViewViews::SetAccessibilityLabel().
ToString()
std::string AutocompleteMatchType::ToString (AutocompleteMatchType::Type type) static
References NUM_TYPES.
The documentation for this struct was generated from the following files:
components/omnibox/browser/autocomplete_match_type.h
components/omnibox/browser/autocomplete_match_type.cc