Chromium Omnibox: AlternateNavInfoBarDelegate Class Reference
AlternateNavInfoBarDelegate Class Reference
#include <alternate_nav_infobar_delegate.h>
Public Member Functions
AlternateNavInfoBarDelegate (const AlternateNavInfoBarDelegate &)=delete
AlternateNavInfoBarDelegate & operator= (const AlternateNavInfoBarDelegate &)=delete
~AlternateNavInfoBarDelegate () override
std::u16string GetMessageTextWithOffset (size_t *link_offset) const
infobars::InfoBarDelegate::InfoBarIdentifier GetIdentifier () const override
const gfx::VectorIcon & GetVectorIcon () const override
std::u16string GetLinkText () const override
GURL GetLinkURL () const override
bool LinkClicked (WindowOpenDisposition disposition) override
Static Public Member Functions
static void CreateForOmniboxNavigation (content::WebContents *web_contents, const std::u16string &text, const AutocompleteMatch &match, const GURL &search_url)
Private Member Functions
AlternateNavInfoBarDelegate (Profile *profile, const std::u16string &text, std::unique_ptr< AutocompleteMatch > match, const GURL &destination_url, const GURL &original_url)
Static Private Member Functions
static std::unique_ptr< infobars::InfoBar > CreateInfoBar (std::unique_ptr< AlternateNavInfoBarDelegate > delegate)
Private Attributes
Profile * profile_
const std::u16string text_
std::unique_ptr< AutocompleteMatch > match_
const GURL destination_url_
const GURL original_url_
Constructor & Destructor Documentation
AlternateNavInfoBarDelegate() [1/2]
AlternateNavInfoBarDelegate::AlternateNavInfoBarDelegate (const AlternateNavInfoBarDelegate &) delete
Referenced by CreateForOmniboxNavigation().
~AlternateNavInfoBarDelegate()
AlternateNavInfoBarDelegate::~AlternateNavInfoBarDelegate () override
AlternateNavInfoBarDelegate() [2/2]
AlternateNavInfoBarDelegate::AlternateNavInfoBarDelegate (Profile * profile, const std::u16string & text, std::unique_ptr< AutocompleteMatch > match, const GURL & destination_url, const GURL & original_url) private
References destination_url_, match_, and original_url_.
Member Function Documentation
CreateForOmniboxNavigation()
void AlternateNavInfoBarDelegate::CreateForOmniboxNavigation (content::WebContents * web_contents, const std::u16string & text, const AutocompleteMatch & match, const GURL & search_url) static
References AlternateNavInfoBarDelegate(), AutocompleteMatch::AutocompleteMatch(), CreateInfoBar(), and AutocompleteMatch::destination_url.
Referenced by ChromeOmniboxNavigationObserver::ShowAlternativeNavInfoBar().
CreateInfoBar()
static std::unique_ptr<infobars::InfoBar> AlternateNavInfoBarDelegate::CreateInfoBar (std::unique_ptr< AlternateNavInfoBarDelegate > delegate) static private
Referenced by CreateForOmniboxNavigation().
GetIdentifier()
infobars::InfoBarDelegate::InfoBarIdentifier AlternateNavInfoBarDelegate::GetIdentifier () const override
GetLinkText()
std::u16string AlternateNavInfoBarDelegate::GetLinkText () const override
References destination_url_.
GetLinkURL()
GURL AlternateNavInfoBarDelegate::GetLinkURL () const override
References destination_url_.
GetMessageTextWithOffset()
std::u16string AlternateNavInfoBarDelegate::GetMessageTextWithOffset (size_t * link_offset) const
GetVectorIcon()
const gfx::VectorIcon & AlternateNavInfoBarDelegate::GetVectorIcon () const override
LinkClicked()
bool AlternateNavInfoBarDelegate::LinkClicked (WindowOpenDisposition disposition) override
References destination_url_, match_, original_url_, profile_, and text_.
operator=()
AlternateNavInfoBarDelegate& AlternateNavInfoBarDelegate::operator= (const AlternateNavInfoBarDelegate &) delete
Member Data Documentation
destination_url_
const GURL AlternateNavInfoBarDelegate::destination_url_ private
Referenced by AlternateNavInfoBarDelegate(), GetLinkText(), GetLinkURL(), and LinkClicked().
match_
std::unique_ptr<AutocompleteMatch> AlternateNavInfoBarDelegate::match_ private
Referenced by AlternateNavInfoBarDelegate(), and LinkClicked().
original_url_
const GURL AlternateNavInfoBarDelegate::original_url_ private
Referenced by AlternateNavInfoBarDelegate(), and LinkClicked().
profile_
Profile* AlternateNavInfoBarDelegate::profile_ private
Referenced by LinkClicked().
text_
const std::u16string AlternateNavInfoBarDelegate::text_ private
Referenced by LinkClicked().
The documentation for this class was generated from the following files:
chrome/browser/ui/omnibox/alternate_nav_infobar_delegate.h
chrome/browser/ui/omnibox/alternate_nav_infobar_delegate.cc