Chromium Omnibox: OmniboxPopupContentsView Class Reference
OmniboxPopupContentsView Class Reference
#include <omnibox_popup_contents_view.h>
Classes
class AutocompletePopupWidget
Public Member Functions
METADATA_HEADER (OmniboxPopupContentsView)
OmniboxPopupContentsView (OmniboxViewViews *omnibox_view, OmniboxEditModel *edit_model, LocationBarView *location_bar_view)
OmniboxPopupContentsView (const OmniboxPopupContentsView &)=delete
OmniboxPopupContentsView & operator= (const OmniboxPopupContentsView &)=delete
~OmniboxPopupContentsView () override
void OpenMatch (WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp)
void OpenMatch (size_t index, WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp)
gfx::Image GetMatchIcon (const AutocompleteMatch &match, SkColor vector_icon_color) const
virtual void SetSelectedIndex (size_t index)
virtual size_t GetSelectedIndex () const
virtual OmniboxPopupSelection GetSelection () const
void UnselectButton ()
OmniboxResultView * result_view_at (size_t i)
OmniboxResultView * GetSelectedResultView ()
bool InExplicitExperimentalKeywordMode ()
bool IsOpen () const override
void InvalidateLine (size_t line) override
void OnSelectionChanged (OmniboxPopupSelection old_selection, OmniboxPopupSelection new_selection) override
void UpdatePopupAppearance () override
void ProvideButtonFocusHint (size_t line) override
void OnMatchIconUpdated (size_t match_index) override
void OnDragCanceled () override
bool OnMouseDragged (const ui::MouseEvent &event) override
void OnGestureEvent (ui::GestureEvent *event) override
void GetAccessibleNodeData (ui::AXNodeData *node_data) override
void OnWidgetBoundsChanged (views::Widget *widget, const gfx::Rect &new_bounds) override
void FireAXEventsForNewActiveDescendant (View *descendant_view)
Public Member Functions inherited from OmniboxPopupView
virtual ~OmniboxPopupView ()=default
Private Member Functions
gfx::Rect GetTargetBounds () const
bool HasMatchAt (size_t index) const
const AutocompleteMatch & GetMatchAtIndex (size_t index) const
size_t GetIndexForPoint (const gfx::Point &point)
void OnSuggestionGroupVisibilityUpdate ()
PrefService * GetPrefService () const
Private Attributes
base::WeakPtr< AutocompletePopupWidget > popup_
OmniboxViewViews * omnibox_view_
LocationBarView * location_bar_view_
WebUIOmniboxPopupView * webui_view_ = nullptr
PrefChangeRegistrar pref_change_registrar_
OmniboxEditModel * edit_model_
Friends
class OmniboxPopupContentsViewTest
class OmniboxSuggestionButtonRowBrowserTest
Constructor & Destructor Documentation
OmniboxPopupContentsView() [1/2]
OmniboxPopupContentsView::OmniboxPopupContentsView (OmniboxViewViews * omnibox_view, OmniboxEditModel * edit_model, LocationBarView * location_bar_view)
References edit_model_, GetPrefService(), omnibox::kSuggestionGroupVisibility, OnSuggestionGroupVisibilityUpdate(), pref_change_registrar_, and OmniboxEditModel::set_popup_view().
Referenced by OmniboxViewViews::Init().
OmniboxPopupContentsView() [2/2]
OmniboxPopupContentsView::OmniboxPopupContentsView (const OmniboxPopupContentsView &) delete
~OmniboxPopupContentsView()
OmniboxPopupContentsView::~OmniboxPopupContentsView () override
References edit_model_, popup_, and OmniboxEditModel::set_popup_view().
Member Function Documentation
FireAXEventsForNewActiveDescendant()
void OmniboxPopupContentsView::FireAXEventsForNewActiveDescendant (View * descendant_view)
References omnibox_view_.
Referenced by OmniboxResultView::OnSelectionStateChanged(), ProvideButtonFocusHint(), and UpdatePopupAppearance().
GetAccessibleNodeData()
void OmniboxPopupContentsView::GetAccessibleNodeData (ui::AXNodeData * node_data) override
References IsOpen(), and omnibox_view_.
GetIndexForPoint()
size_t OmniboxPopupContentsView::GetIndexForPoint (const gfx::Point & point) private
References edit_model_, OmniboxPopupSelection::kNoMatch, OmniboxEditModel::result(), and AutocompleteResult::size().
Referenced by OnGestureEvent(), and OnMouseDragged().
GetMatchAtIndex()
const AutocompleteMatch & OmniboxPopupContentsView::GetMatchAtIndex (size_t index) const private
References edit_model_, AutocompleteResult::match_at(), and OmniboxEditModel::result().
Referenced by UpdatePopupAppearance().
GetMatchIcon()
gfx::Image OmniboxPopupContentsView::GetMatchIcon (const AutocompleteMatch & match, SkColor vector_icon_color) const
References edit_model_, and OmniboxEditModel::GetMatchIcon().
Referenced by OmniboxResultView::GetIcon().
GetPrefService()
PrefService * OmniboxPopupContentsView::GetPrefService () const private
References location_bar_view_.
Referenced by OmniboxPopupContentsView(), OnSuggestionGroupVisibilityUpdate(), and UpdatePopupAppearance().
GetSelectedIndex()
size_t OmniboxPopupContentsView::GetSelectedIndex () const virtual
References GetSelection(), and OmniboxPopupSelection::line.
GetSelectedResultView()
OmniboxResultView * OmniboxPopupContentsView::GetSelectedResultView ()
References GetSelection(), OmniboxPopupSelection::kNoMatch, omnibox::kWebUIOmniboxPopup, OmniboxPopupSelection::line, and result_view_at().
GetSelection()
OmniboxPopupSelection OmniboxPopupContentsView::GetSelection () const virtual
References edit_model_, and OmniboxEditModel::GetPopupSelection().
Referenced by OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxResultView::GetMatchSelected(), GetSelectedIndex(), GetSelectedResultView(), OmniboxResultView::OmniboxResultView(), OmniboxSuggestionRowButton::OmniboxSuggestionRowButton(), OmniboxResultView::OnSelectionStateChanged(), OpenMatch(), and ProvideButtonFocusHint().
GetTargetBounds()
gfx::Rect OmniboxPopupContentsView::GetTargetBounds () const private
References edit_model_, RoundedOmniboxResultsFrame::GetLocationBarAlignmentInsets(), RoundedOmniboxResultsFrame::GetNonResultSectionHeight(), RoundedOmniboxResultsFrame::GetShadowInsets(), omnibox::kWebUIOmniboxPopup, location_bar_view_, OmniboxEditModel::result(), AutocompleteResult::size(), and webui_view_.
Referenced by OnSuggestionGroupVisibilityUpdate(), and UpdatePopupAppearance().
HasMatchAt()
bool OmniboxPopupContentsView::HasMatchAt (size_t index) const private
References edit_model_, OmniboxEditModel::result(), and AutocompleteResult::size().
Referenced by OnGestureEvent(), OnMouseDragged(), OpenMatch(), and SetSelectedIndex().
InExplicitExperimentalKeywordMode()
bool OmniboxPopupContentsView::InExplicitExperimentalKeywordMode ()
References edit_model_, and OmniboxEditModel::InExplicitExperimentalKeywordMode().
Referenced by OmniboxResultView::SetMatch().
InvalidateLine()
void OmniboxPopupContentsView::InvalidateLine (size_t line) override virtual
Implements OmniboxPopupView.
References WebUIOmniboxPopupView::GetWebUIHandler(), omnibox::kWebUIOmniboxPopup, and webui_view_.
Referenced by OnSelectionChanged().
IsOpen()
bool OmniboxPopupContentsView::IsOpen () const override virtual
Implements OmniboxPopupView.
References popup_.
Referenced by OmniboxResultView::EmitTextChangedAccessiblityEvent(), and GetAccessibleNodeData().
METADATA_HEADER()
OmniboxPopupContentsView::METADATA_HEADER (OmniboxPopupContentsView)
OnDragCanceled()
void OmniboxPopupContentsView::OnDragCanceled () override virtual
Implements OmniboxPopupView.
OnGestureEvent()
void OmniboxPopupContentsView::OnGestureEvent (ui::GestureEvent * event) override
References GetIndexForPoint(), HasMatchAt(), OpenMatch(), and SetSelectedIndex().
OnMatchIconUpdated()
void OmniboxPopupContentsView::OnMatchIconUpdated (size_t match_index) override virtual
Implements OmniboxPopupView.
References omnibox::kWebUIOmniboxPopup, OmniboxResultView::OnMatchIconUpdated(), and result_view_at().
OnMouseDragged()
bool OmniboxPopupContentsView::OnMouseDragged (const ui::MouseEvent & event) override
References GetIndexForPoint(), HasMatchAt(), omnibox::kWebUIOmniboxPopup, and result_view_at().
OnSelectionChanged()
void OmniboxPopupContentsView::OnSelectionChanged (OmniboxPopupSelection old_selection, OmniboxPopupSelection new_selection) override virtual
Reimplemented from OmniboxPopupView.
References WebUIOmniboxPopupView::GetWebUIHandler(), InvalidateLine(), OmniboxPopupSelection::kNoMatch, omnibox::kWebUIOmniboxPopup, OmniboxPopupSelection::line, and webui_view_.
OnSuggestionGroupVisibilityUpdate()
void OmniboxPopupContentsView::OnSuggestionGroupVisibilityUpdate () private
References edit_model_, GetPrefService(), GetTargetBounds(), AutocompleteResult::IsSuggestionGroupIdHidden(), AutocompleteResult::match_at(), popup_, OmniboxEditModel::result(), result_view_at(), and AutocompleteMatch::suggestion_group_id.
Referenced by OmniboxPopupContentsView().
OnWidgetBoundsChanged()
void OmniboxPopupContentsView::OnWidgetBoundsChanged (views::Widget * widget, const gfx::Rect & new_bounds) override
References popup_, and UpdatePopupAppearance().
OpenMatch() [1/2]
void OmniboxPopupContentsView::OpenMatch (size_t index, WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp)
References edit_model_, HasMatchAt(), AutocompleteResult::match_at(), omnibox_view_, OmniboxView::OpenMatch(), and OmniboxEditModel::result().
OpenMatch() [2/2]
void OmniboxPopupContentsView::OpenMatch (WindowOpenDisposition disposition, base::TimeTicks match_selection_timestamp)
References GetSelection().
Referenced by OnGestureEvent(), and OmniboxResultView::OnMouseReleased().
operator=()
OmniboxPopupContentsView& OmniboxPopupContentsView::operator= (const OmniboxPopupContentsView &) delete
ProvideButtonFocusHint()
void OmniboxPopupContentsView::ProvideButtonFocusHint (size_t line) override virtual
Implements OmniboxPopupView.
References FireAXEventsForNewActiveDescendant(), GetSelection(), and omnibox::kWebUIOmniboxPopup.
result_view_at()
OmniboxResultView * OmniboxPopupContentsView::result_view_at (size_t i)
References omnibox::kWebUIOmniboxPopup.
Referenced by GetSelectedResultView(), OnMatchIconUpdated(), OnMouseDragged(), OnSuggestionGroupVisibilityUpdate(), and UpdatePopupAppearance().
SetSelectedIndex()
void OmniboxPopupContentsView::SetSelectedIndex (size_t index) virtual
References edit_model_, HasMatchAt(), OmniboxPopupSelection::NORMAL, and OmniboxEditModel::SetPopupSelection().
Referenced by OnGestureEvent(), OmniboxResultView::OnMouseDragged(), and OmniboxResultView::OnMousePressed().
UnselectButton()
void OmniboxPopupContentsView::UnselectButton ()
References edit_model_, OmniboxEditModel::GetPopupSelection(), OmniboxPopupSelection::NORMAL, OmniboxEditModel::SetPopupSelection(), and OmniboxPopupSelection::state.
UpdatePopupAppearance()
void OmniboxPopupContentsView::UpdatePopupAppearance () override virtual
Implements OmniboxPopupView.
References OmniboxEditModel::autocomplete_controller(), edit_model_, AutocompleteResult::empty(), FireAXEventsForNewActiveDescendant(), AutocompleteResult::GetHeaderForGroupId(), GetMatchAtIndex(), OmniboxEditModel::GetPopupRichSuggestionBitmap(), GetPrefService(), OmniboxViewViews::GetRelativeWindowForPopup(), GetTargetBounds(), OmniboxRowView::HideHeader(), AutocompleteController::InlineTailPrefixes(), OmniboxViewViews::IsImeShowingPopup(), AutocompleteResult::IsSuggestionGroupIdHidden(), omnibox::kWebUIOmniboxPopup, location_bar_view_, omnibox_view_, OmniboxResultView::OmniboxResultView(), OmniboxRowView::OmniboxRowView(), popup_, OmniboxEditModel::result(), OmniboxRowView::result_view(), result_view_at(), OmniboxResultView::SetMatch(), OmniboxResultView::SetRichSuggestionImage(), OmniboxRowView::ShowHeader(), AutocompleteResult::size(), AutocompleteMatch::suggestion_group_id, webui_view_, and WebUIOmniboxPopupView::WebUIOmniboxPopupView().
Referenced by OnWidgetBoundsChanged().
Friends And Related Function Documentation
OmniboxPopupContentsViewTest
friend class OmniboxPopupContentsViewTest friend
OmniboxSuggestionButtonRowBrowserTest
friend class OmniboxSuggestionButtonRowBrowserTest friend
Member Data Documentation
edit_model_
OmniboxEditModel* OmniboxPopupContentsView::edit_model_ private
Referenced by GetIndexForPoint(), GetMatchAtIndex(), GetMatchIcon(), GetSelection(), GetTargetBounds(), HasMatchAt(), InExplicitExperimentalKeywordMode(), OmniboxPopupContentsView(), OnSuggestionGroupVisibilityUpdate(), OpenMatch(), SetSelectedIndex(), UnselectButton(), UpdatePopupAppearance(), and ~OmniboxPopupContentsView().
location_bar_view_
LocationBarView* OmniboxPopupContentsView::location_bar_view_ private
Referenced by GetPrefService(), GetTargetBounds(), OmniboxPopupContentsView::AutocompletePopupWidget::SetPopupContentsView(), and UpdatePopupAppearance().
omnibox_view_
OmniboxViewViews* OmniboxPopupContentsView::omnibox_view_ private
Referenced by FireAXEventsForNewActiveDescendant(), GetAccessibleNodeData(), OpenMatch(), and UpdatePopupAppearance().
popup_
base::WeakPtr<AutocompletePopupWidget> OmniboxPopupContentsView::popup_ private
Referenced by IsOpen(), OnSuggestionGroupVisibilityUpdate(), OnWidgetBoundsChanged(), UpdatePopupAppearance(), and ~OmniboxPopupContentsView().
pref_change_registrar_
PrefChangeRegistrar OmniboxPopupContentsView::pref_change_registrar_ private
Referenced by OmniboxPopupContentsView().
webui_view_
WebUIOmniboxPopupView* OmniboxPopupContentsView::webui_view_ = nullptr private
Referenced by GetTargetBounds(), InvalidateLine(), OnSelectionChanged(), and UpdatePopupAppearance().
The documentation for this class was generated from the following files:
chrome/browser/ui/views/omnibox/omnibox_popup_contents_view.h
chrome/browser/ui/views/omnibox/omnibox_popup_contents_view.cc