Chromium Omnibox: components/omnibox/browser/in_memory_url_index_types.cc File Reference
in_memory_url_index_types.cc File Reference
#include "components/omnibox/browser/in_memory_url_index_types.h"
#include <algorithm>
#include <functional>
#include <iterator>
#include <numeric>
#include <set>
#include "base/i18n/break_iterator.h"
#include "base/i18n/case_conversion.h"
#include "base/strings/string_util.h"
#include "base/trace_event/memory_usage_estimator.h"
#include "components/omnibox/browser/tailored_word_break_iterator.h"
#include "net/base/escape.h"
Functions
TermMatches MatchTermsInString (const String16Vector &terms, const std::u16string &cleaned_string)
TermMatches MatchTermInString (const std::u16string &term, const std::u16string &cleaned_string, int term_num)
bool SortMatchComparator (const TermMatch &m1, const TermMatch &m2)
TermMatches SortMatches (const TermMatches &matches)
TermMatches DeoverlapMatches (const TermMatches &sorted_matches)
std::vector< size_t > OffsetsFromTermMatches (const TermMatches &matches)
TermMatches ReplaceOffsetsInTermMatches (const TermMatches &matches, const std::vector< size_t > &offsets)
String16Set String16SetFromString16 (const std::u16string &cleaned_uni_string, WordStarts *word_starts)
String16Vector String16VectorFromString16 (const std::u16string &cleaned_uni_string, bool break_on_space, WordStarts *word_starts)
Char16Set Char16SetFromString16 (const std::u16string &term)
Function Documentation
Char16SetFromString16()
Char16Set Char16SetFromString16 (const std::u16string & term)
Referenced by URLIndexPrivateData::AddWordToIndex(), URLIndexPrivateData::HistoryIDsForTerm(), and URLIndexPrivateData::RemoveRowWordsFromIndex().
DeoverlapMatches()
TermMatches DeoverlapMatches (const TermMatches & sorted_matches)
Referenced by FindTermMatches(), and ScoredHistoryMatch::ScoredHistoryMatch().
MatchTermInString()
TermMatches MatchTermInString (const std::u16string & term, const std::u16string & cleaned_string, int term_num)
Referenced by MatchTermsInString(), and ScoredHistoryMatch::ScoredHistoryMatch().
MatchTermsInString()
TermMatches MatchTermsInString (const String16Vector & terms, const std::u16string & cleaned_string)
References MatchTermInString().
Referenced by FindTermMatches().
OffsetsFromTermMatches()
std::vector<size_t> OffsetsFromTermMatches (const TermMatches & matches)
Referenced by ScoredHistoryMatch::ScoredHistoryMatch().
ReplaceOffsetsInTermMatches()
TermMatches ReplaceOffsetsInTermMatches (const TermMatches & matches, const std::vector< size_t > & offsets)
References TermMatch::length, and TermMatch::offset.
Referenced by ScoredHistoryMatch::ScoredHistoryMatch().
SortMatchComparator()
bool SortMatchComparator (const TermMatch & m1, const TermMatch & m2)
References TermMatch::length, and TermMatch::offset.
Referenced by SortMatches().
SortMatches()
TermMatches SortMatches (const TermMatches & matches)
References SortMatchComparator().
Referenced by FindTermMatches(), and ScoredHistoryMatch::ScoredHistoryMatch().
String16SetFromString16()
String16Set String16SetFromString16 (const std::u16string & cleaned_uni_string, WordStarts * word_starts)
References String16VectorFromString16().
Referenced by URLIndexPrivateData::AddRowWordsToIndex().
String16VectorFromString16()
String16Vector String16VectorFromString16 (const std::u16string & cleaned_uni_string, bool break_on_space, WordStarts * word_starts)
References TailoredWordBreakIterator::Advance(), TailoredWordBreakIterator::GetString(), TailoredWordBreakIterator::IsWord(), and TailoredWordBreakIterator::prev().
Referenced by FindAtWordbreak(), FindTermMatches(), FindWordsSequentiallyAtWordbreak(), URLIndexPrivateData::HistoryItemsForTerms(), URLIndexPrivateData::RestoreWordStartsMap(), and String16SetFromString16().