Chromium Omnibox: AutocompleteController Class Reference
AutocompleteController Class Reference
#include <autocomplete_controller.h>
Classes
class Observer
Public Types
typedef std::vector< scoped_refptr< AutocompleteProvider > > Providers
Public Member Functions
AutocompleteController (std::unique_ptr< AutocompleteProviderClient > provider_client, int provider_types)
~AutocompleteController () override
AutocompleteController (const AutocompleteController &)=delete
AutocompleteController & operator= (const AutocompleteController &)=delete
void AddObserver (Observer *observer)
void Start (const AutocompleteInput &input)
void Stop (bool clear_result)
void DeleteMatch (const AutocompleteMatch &match)
void ExpireCopiedEntries ()
void OnProviderUpdate (bool updated_matches) override
void AddProviderAndTriggeringLogs (OmniboxLog *logs) const
void ResetSession ()
void UpdateMatchDestinationURLWithAdditionalAssistedQueryStats (base::TimeDelta query_formulation_time, AutocompleteMatch *match) const
void SetMatchDestinationURL (AutocompleteMatch *match) const
void InlineTailPrefixes ()
HistoryURLProvider * history_url_provider () const
KeywordProvider * keyword_provider () const
SearchProvider * search_provider () const
ClipboardProvider * clipboard_provider () const
VoiceSuggestProvider * voice_suggest_provider () const
const AutocompleteInput & input () const
const AutocompleteResult & result () const
bool done () const
const Providers & providers () const
const base::TimeTicks & last_time_default_match_changed () const
void SetStartStopTimerDurationForTesting (base::TimeDelta duration)
AutocompleteProviderClient * autocomplete_provider_client () const
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (AutocompleteProviderTest, RedundantKeywordsIgnoredInResult)
FRIEND_TEST_ALL_PREFIXES (AutocompleteProviderTest, UpdateAssistedQueryStats)
FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest, EmitAccessibilityEvents)
FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest, EmitAccessibilityEventsOnButtonFocusHint)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewTest, DoesNotUpdateAutocompleteOnBlur)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, CloseOmniboxPopupOnTextDrag)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, FriendlyAccessibleLabel)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, AccessiblePopup)
FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest, MaintainCursorAfterFocusCycle)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, SetSelectedLine)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, SetSelectedLineWithNoDefaultMatches)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, TestFocusFixing)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, PopupPositionChanging)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, PopupStepSelection)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, PopupStepSelectionWithHiddenGroupIds)
FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest, PopupInlineAutocompleteAndTemporaryText)
FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest, EmitSelectedChildrenChangedAccessibilityEvent)
void UpdateResult (bool regenerate_result, bool force_notify_default_match_changed)
void UpdateAssociatedKeywords (AutocompleteResult *result)
void UpdateHeaderInfoFromZeroSuggestProvider (AutocompleteResult *result)
void UpdateKeywordDescriptions (AutocompleteResult *result)
void UpdateAssistedQueryStats (AutocompleteResult *result)
void NotifyChanged (bool notify_default_match)
void CheckIfDone ()
void StartExpireTimer ()
void StartStopTimer ()
void StopHelper (bool clear_result, bool due_to_user_inactivity)
bool ShouldCurbKeywordDescriptions (const std::u16string &keyword)
bool OnMemoryDump (const base::trace_event::MemoryDumpArgs &args, base::trace_event::ProcessMemoryDump *process_memory_dump) override
Private Attributes
base::ObserverList< Observer > observers_
std::unique_ptr< AutocompleteProviderClient > provider_client_
Providers providers_
DocumentProvider * document_provider_
HistoryURLProvider * history_url_provider_
KeywordProvider * keyword_provider_
SearchProvider * search_provider_
ZeroSuggestProvider * zero_suggest_provider_
OnDeviceHeadProvider * on_device_head_provider_
ClipboardProvider * clipboard_provider_
VoiceSuggestProvider * voice_suggest_provider_
AutocompleteInput input_
AutocompleteResult result_
base::TimeTicks last_time_default_match_changed_
base::OneShotTimer expire_timer_
base::OneShotTimer stop_timer_
base::TimeDelta stop_timer_duration_
bool done_
bool in_start_
bool search_service_worker_signal_sent_
TemplateURLService * template_url_service_
Friends
class AutocompleteProviderTest
class OmniboxSuggestionButtonRowBrowserTest
Additional Inherited Members
Protected Member Functions inherited from AutocompleteProviderListener
virtual ~AutocompleteProviderListener ()
Member Typedef Documentation
Providers
typedef std::vector<scoped_refptr<AutocompleteProvider> > AutocompleteController::Providers
Constructor & Destructor Documentation
AutocompleteController() [1/2]
AutocompleteController::AutocompleteController (std::unique_ptr< AutocompleteProviderClient > provider_client, int provider_types)
References clipboard_provider_, LocalHistoryZeroSuggestProvider::Create(), OnDeviceHeadProvider::Create(), ZeroSuggestProvider::Create(), DocumentProvider::Create(), document_provider_, OmniboxFieldTrial::GetDisabledProviderTypes(), history_url_provider_, keyword_provider_, on_device_head_provider_, provider_client_, providers_, search_provider_, AutocompleteProvider::TYPE_BOOKMARK, AutocompleteProvider::TYPE_BUILTIN, AutocompleteProvider::TYPE_CLIPBOARD, AutocompleteProvider::TYPE_DOCUMENT, AutocompleteProvider::TYPE_HISTORY_QUICK, AutocompleteProvider::TYPE_HISTORY_URL, AutocompleteProvider::TYPE_KEYWORD, AutocompleteProvider::TYPE_MOST_VISITED_SITES, AutocompleteProvider::TYPE_ON_DEVICE_HEAD, AutocompleteProvider::TYPE_QUERY_TILE, AutocompleteProvider::TYPE_SEARCH, AutocompleteProvider::TYPE_SHORTCUTS, AutocompleteProvider::TYPE_VOICE_SUGGEST, AutocompleteProvider::TYPE_ZERO_SUGGEST, AutocompleteProvider::TYPE_ZERO_SUGGEST_LOCAL_HISTORY, voice_suggest_provider_, and zero_suggest_provider_.
~AutocompleteController()
AutocompleteController::~AutocompleteController () override
References AutocompleteResult::Reset(), result_, and Stop().
AutocompleteController() [2/2]
AutocompleteController::AutocompleteController (const AutocompleteController &) delete
Member Function Documentation
AddObserver()
void AutocompleteController::AddObserver (Observer * observer)
References observers_.
AddProviderAndTriggeringLogs()
void AutocompleteController::AddProviderAndTriggeringLogs (OmniboxLog * logs) const
References OmniboxLog::feature_triggered_in_session, provider_client_, providers_, and OmniboxLog::providers_info.
Referenced by OmniboxEditModel::OpenMatch().
autocomplete_provider_client()
AutocompleteProviderClient* AutocompleteController::autocomplete_provider_client () const inline
References provider_client_.
Referenced by OmniboxEditModel::GetPrefService().
CheckIfDone()
void AutocompleteController::CheckIfDone () private
References done_, and providers_.
Referenced by OnProviderUpdate(), and Start().
clipboard_provider()
ClipboardProvider* AutocompleteController::clipboard_provider () const inline
References clipboard_provider_.
DeleteMatch()
void AutocompleteController::DeleteMatch (const AutocompleteMatch & match)
References AutocompleteProvider::AsOmniboxEventProviderType(), AutocompleteMatch::AsOmniboxEventResultType(), AutocompleteMatch::deletable, AutocompleteProvider::DeleteMatch(), AutocompleteMatch::duplicate_matches, ExpireCopiedEntries(), OnProviderUpdate(), AutocompleteMatch::provider, and AutocompleteMatch::SupportsDeletion().
Referenced by OmniboxEditModel::TryDeletingPopupLine().
done()
bool AutocompleteController::done () const inline
References done_.
Referenced by OmniboxEditModel::query_in_progress().
ExpireCopiedEntries()
void AutocompleteController::ExpireCopiedEntries ()
References UpdateResult().
Referenced by DeleteMatch(), and StartExpireTimer().
FRIEND_TEST_ALL_PREFIXES() [1/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (AutocompleteProviderTest , RedundantKeywordsIgnoredInResult) private
FRIEND_TEST_ALL_PREFIXES() [2/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (AutocompleteProviderTest , UpdateAssistedQueryStats) private
FRIEND_TEST_ALL_PREFIXES() [3/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , PopupInlineAutocompleteAndTemporaryText) private
FRIEND_TEST_ALL_PREFIXES() [4/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , PopupPositionChanging) private
FRIEND_TEST_ALL_PREFIXES() [5/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , PopupStepSelection) private
FRIEND_TEST_ALL_PREFIXES() [6/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , PopupStepSelectionWithHiddenGroupIds) private
FRIEND_TEST_ALL_PREFIXES() [7/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , SetSelectedLine) private
FRIEND_TEST_ALL_PREFIXES() [8/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , SetSelectedLineWithNoDefaultMatches) private
FRIEND_TEST_ALL_PREFIXES() [9/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxEditModelPopupTest , TestFocusFixing) private
FRIEND_TEST_ALL_PREFIXES() [10/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest , EmitAccessibilityEvents) private
FRIEND_TEST_ALL_PREFIXES() [11/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest , EmitAccessibilityEventsOnButtonFocusHint) private
FRIEND_TEST_ALL_PREFIXES() [12/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxPopupContentsViewTest , EmitSelectedChildrenChangedAccessibilityEvent) private
FRIEND_TEST_ALL_PREFIXES() [13/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxViewTest , DoesNotUpdateAutocompleteOnBlur) private
FRIEND_TEST_ALL_PREFIXES() [14/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , AccessiblePopup) private
FRIEND_TEST_ALL_PREFIXES() [15/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , CloseOmniboxPopupOnTextDrag) private
FRIEND_TEST_ALL_PREFIXES() [16/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , FriendlyAccessibleLabel) private
FRIEND_TEST_ALL_PREFIXES() [17/17]
AutocompleteController::FRIEND_TEST_ALL_PREFIXES (OmniboxViewViewsTest , MaintainCursorAfterFocusCycle) private
history_url_provider()
HistoryURLProvider* AutocompleteController::history_url_provider () const inline
References history_url_provider_.
InlineTailPrefixes()
void AutocompleteController::InlineTailPrefixes ()
References AutocompleteResult::InlineTailPrefixes(), and result_.
Referenced by OmniboxPopupContentsView::UpdatePopupAppearance().
input()
const AutocompleteInput& AutocompleteController::input () const inline
References input_.
Referenced by Start().
keyword_provider()
KeywordProvider* AutocompleteController::keyword_provider () const inline
References keyword_provider_.
Referenced by OmniboxEditModel::CreatedKeywordSearchByInsertingSpaceInMiddle().
last_time_default_match_changed()
const base::TimeTicks& AutocompleteController::last_time_default_match_changed () const inline
References last_time_default_match_changed_.
NotifyChanged()
void AutocompleteController::NotifyChanged (bool notify_default_match) private
References done_, observers_, and provider_client_.
Referenced by StopHelper(), and UpdateResult().
OnMemoryDump()
bool AutocompleteController::OnMemoryDump (const base::trace_event::MemoryDumpArgs & args, base::trace_event::ProcessMemoryDump * process_memory_dump) override private
References AutocompleteInput::EstimateMemoryUsage(), AutocompleteResult::EstimateMemoryUsage(), input_, providers_, and result_.
OnProviderUpdate()
void AutocompleteController::OnProviderUpdate (bool updated_matches) override virtual
Implements AutocompleteProviderListener.
References CheckIfDone(), done_, in_start_, and UpdateResult().
Referenced by DeleteMatch().
operator=()
AutocompleteController& AutocompleteController::operator= (const AutocompleteController &) delete
providers()
const Providers& AutocompleteController::providers () const inline
References providers_.
ResetSession()
void AutocompleteController::ResetSession ()
References provider_client_, providers_, and search_service_worker_signal_sent_.
Referenced by OmniboxEditModel::SetInputInProgressNoNotify().
result()
const AutocompleteResult& AutocompleteController::result () const inline
References result_.
Referenced by UpdateAssistedQueryStats(), UpdateAssociatedKeywords(), UpdateHeaderInfoFromZeroSuggestProvider(), and UpdateKeywordDescriptions().
search_provider()
SearchProvider* AutocompleteController::search_provider () const inline
References search_provider_.
SetMatchDestinationURL()
void AutocompleteController::SetMatchDestinationURL (AutocompleteMatch * match) const
References AutocompleteMatch::destination_url, AutocompleteMatch::GetTemplateURL(), AutocompleteMatch::search_terms_args, and template_url_service_.
Referenced by UpdateMatchDestinationURLWithAdditionalAssistedQueryStats().
SetStartStopTimerDurationForTesting()
void AutocompleteController::SetStartStopTimerDurationForTesting (base::TimeDelta duration)
References stop_timer_duration_.
ShouldCurbKeywordDescriptions()
bool AutocompleteController::ShouldCurbKeywordDescriptions (const std::u16string & keyword) private
References AutocompleteProvider::InExplicitExperimentalKeywordMode(), and input_.
Referenced by UpdateKeywordDescriptions().
Start()
void AutocompleteController::Start (const AutocompleteInput & input)
References AutocompleteInput::allow_exact_keyword_match(), CheckIfDone(), AutocompleteResult::default_match(), AutocompleteMatch::destination_url, done_, expire_timer_, AutocompleteInput::focus_type(), in_start_, input(), input_, observers_, provider_client_, providers_, result_, search_service_worker_signal_sent_, StartExpireTimer(), StartStopTimer(), stop_timer_, AutocompleteInput::text(), AutocompleteInput::type(), UpdateResult(), and AutocompleteInput::want_asynchronous_matches().
Referenced by OmniboxEditModel::StartZeroSuggestRequest().
StartExpireTimer()
void AutocompleteController::StartExpireTimer () private
References expire_timer_, ExpireCopiedEntries(), AutocompleteResult::HasCopiedMatches(), and result_.
Referenced by Start().
StartStopTimer()
void AutocompleteController::StartStopTimer () private
References stop_timer_, stop_timer_duration_, and StopHelper().
Referenced by Start().
Stop()
void AutocompleteController::Stop (bool clear_result)
References StopHelper().
Referenced by OmniboxEditModel::AcceptKeyword(), OmniboxEditModel::ClearKeyword(), OmniboxEditModel::EnterKeywordModeForDefaultSearchProvider(), OmniboxEditModel::SetPopupSelection(), OmniboxEditModel::StopAutocomplete(), OmniboxEditModel::TryDeletingPopupLine(), and ~AutocompleteController().
StopHelper()
void AutocompleteController::StopHelper (bool clear_result, bool due_to_user_inactivity) private
References done_, AutocompleteResult::empty(), expire_timer_, NotifyChanged(), providers_, AutocompleteResult::Reset(), result_, and stop_timer_.
Referenced by StartStopTimer(), and Stop().
UpdateAssistedQueryStats()
void AutocompleteController::UpdateAssistedQueryStats (AutocompleteResult * result) private
References AutocompleteResult::empty(), AutocompleteMatch::GetTemplateURL(), AutocompleteMatch::IsTrivialAutocompletion(), AutocompleteResult::match_at(), result(), AutocompleteMatch::search_terms_args, AutocompleteResult::size(), AutocompleteMatch::subtypes, and template_url_service_.
Referenced by UpdateResult().
UpdateAssociatedKeywords()
void AutocompleteController::UpdateAssociatedKeywords (AutocompleteResult * result) private
References AutocompleteMatch::answer, AutocompleteMatch::associated_keyword, AutocompleteMatch::AutocompleteMatch(), AutocompleteResult::begin(), KeywordProvider::CreateVerbatimMatch(), AutocompleteResult::end(), AutocompleteMatch::fill_into_edit, KeywordProvider::GetKeywordForText(), AutocompleteMatch::GetSubstitutingExplicitlyInvokedKeyword(), input_, keyword_provider_, result(), template_url_service_, and AutocompleteInput::text().
Referenced by UpdateResult().
UpdateHeaderInfoFromZeroSuggestProvider()
void AutocompleteController::UpdateHeaderInfoFromZeroSuggestProvider (AutocompleteResult * result) private
References ZeroSuggestProvider::headers_map(), ZeroSuggestProvider::hidden_group_ids(), AutocompleteResult::MergeHeadersMap(), AutocompleteResult::MergeHiddenGroupIds(), result(), and zero_suggest_provider_.
Referenced by UpdateResult().
UpdateKeywordDescriptions()
void AutocompleteController::UpdateKeywordDescriptions (AutocompleteResult * result) private
References AutocompleteResult::begin(), AutocompleteMatch::ACMatchClassification::DIM, AutocompleteResult::end(), AutocompleteMatch::IsSearchType(), result(), ShouldCurbKeywordDescriptions(), and template_url_service_.
Referenced by UpdateResult().
UpdateMatchDestinationURLWithAdditionalAssistedQueryStats()
void AutocompleteController::UpdateMatchDestinationURLWithAdditionalAssistedQueryStats (base::TimeDelta query_formulation_time, AutocompleteMatch * match) const
References AutocompleteInput::current_page_classification(), ZeroSuggestProvider::experiment_stats(), BaseSearchProvider::field_trial_triggered_in_session(), input_, search_provider_, AutocompleteMatch::search_terms_args, SetMatchDestinationURL(), and zero_suggest_provider_.
Referenced by OmniboxEditModel::OpenMatch().
UpdateResult()
void AutocompleteController::UpdateResult (bool regenerate_result, bool force_notify_default_match_changed) private
References AutocompleteResult::AppendMatches(), AutocompleteMatch::associated_keyword, history_clusters::AttachHistoryClustersActions(), AutocompleteResult::AttachPedalsToMatches(), AutocompleteResult::ConvertOpenTabMatches(), AutocompleteResult::default_match(), done_, AutocompleteMatch::fill_into_edit, AutocompleteResult::GetMatchDedupComparators(), in_start_, input_, OmniboxFieldTrial::IsTabSwitchSuggestionsEnabled(), AutocompleteMatch::keyword, OmniboxTriggeredFeatureService::kRichAutocompletion, last_time_default_match_changed_, AutocompleteResult::LogAsynchronousUpdateMetrics(), NotifyChanged(), provider_client_, providers_, SearchProvider::RegisterDisplayedAnswers(), AutocompleteResult::Reset(), result_, search_provider_, AutocompleteResult::SortAndCull(), AutocompleteResult::Swap(), template_url_service_, AutocompleteResult::TransferOldMatches(), UpdateAssistedQueryStats(), UpdateAssociatedKeywords(), UpdateHeaderInfoFromZeroSuggestProvider(), and UpdateKeywordDescriptions().
Referenced by ExpireCopiedEntries(), OnProviderUpdate(), and Start().
voice_suggest_provider()
VoiceSuggestProvider* AutocompleteController::voice_suggest_provider () const inline
References voice_suggest_provider_.
Friends And Related Function Documentation
AutocompleteProviderTest
friend class AutocompleteProviderTest friend
OmniboxSuggestionButtonRowBrowserTest
friend class OmniboxSuggestionButtonRowBrowserTest friend
Member Data Documentation
clipboard_provider_
ClipboardProvider* AutocompleteController::clipboard_provider_ private
Referenced by AutocompleteController(), and clipboard_provider().
document_provider_
DocumentProvider* AutocompleteController::document_provider_ private
Referenced by AutocompleteController().
done_
bool AutocompleteController::done_ private
Referenced by CheckIfDone(), done(), NotifyChanged(), OnProviderUpdate(), Start(), StopHelper(), and UpdateResult().
expire_timer_
base::OneShotTimer AutocompleteController::expire_timer_ private
Referenced by Start(), StartExpireTimer(), and StopHelper().
history_url_provider_
HistoryURLProvider* AutocompleteController::history_url_provider_ private
Referenced by AutocompleteController(), and history_url_provider().
in_start_
bool AutocompleteController::in_start_ private
Referenced by OnProviderUpdate(), Start(), and UpdateResult().
input_
AutocompleteInput AutocompleteController::input_ private
Referenced by input(), OnMemoryDump(), ShouldCurbKeywordDescriptions(), Start(), UpdateAssociatedKeywords(), UpdateMatchDestinationURLWithAdditionalAssistedQueryStats(), and UpdateResult().
keyword_provider_
KeywordProvider* AutocompleteController::keyword_provider_ private
Referenced by AutocompleteController(), keyword_provider(), and UpdateAssociatedKeywords().
last_time_default_match_changed_
base::TimeTicks AutocompleteController::last_time_default_match_changed_ private
Referenced by last_time_default_match_changed(), and UpdateResult().
observers_
base::ObserverList<Observer> AutocompleteController::observers_ private
Referenced by AddObserver(), NotifyChanged(), and Start().
on_device_head_provider_
OnDeviceHeadProvider* AutocompleteController::on_device_head_provider_ private
Referenced by AutocompleteController().
provider_client_
std::unique_ptr<AutocompleteProviderClient> AutocompleteController::provider_client_ private
Referenced by AddProviderAndTriggeringLogs(), autocomplete_provider_client(), AutocompleteController(), NotifyChanged(), ResetSession(), Start(), and UpdateResult().
providers_
Providers AutocompleteController::providers_ private
Referenced by AddProviderAndTriggeringLogs(), AutocompleteController(), CheckIfDone(), OnMemoryDump(), providers(), ResetSession(), Start(), StopHelper(), and UpdateResult().
result_
AutocompleteResult AutocompleteController::result_ private
Referenced by InlineTailPrefixes(), OnMemoryDump(), result(), Start(), StartExpireTimer(), StopHelper(), UpdateResult(), and ~AutocompleteController().
search_provider_
SearchProvider* AutocompleteController::search_provider_ private
Referenced by AutocompleteController(), search_provider(), UpdateMatchDestinationURLWithAdditionalAssistedQueryStats(), and UpdateResult().
search_service_worker_signal_sent_
bool AutocompleteController::search_service_worker_signal_sent_ private
Referenced by ResetSession(), and Start().
stop_timer_
base::OneShotTimer AutocompleteController::stop_timer_ private
Referenced by Start(), StartStopTimer(), and StopHelper().
stop_timer_duration_
base::TimeDelta AutocompleteController::stop_timer_duration_ private
Referenced by SetStartStopTimerDurationForTesting(), and StartStopTimer().
template_url_service_
TemplateURLService* AutocompleteController::template_url_service_ private
Referenced by SetMatchDestinationURL(), UpdateAssistedQueryStats(), UpdateAssociatedKeywords(), UpdateKeywordDescriptions(), and UpdateResult().
voice_suggest_provider_
VoiceSuggestProvider* AutocompleteController::voice_suggest_provider_ private
Referenced by AutocompleteController(), and voice_suggest_provider().
zero_suggest_provider_
ZeroSuggestProvider* AutocompleteController::zero_suggest_provider_ private
Referenced by AutocompleteController(), UpdateHeaderInfoFromZeroSuggestProvider(), and UpdateMatchDestinationURLWithAdditionalAssistedQueryStats().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_controller.h
components/omnibox/browser/autocomplete_controller.cc