Chromium Omnibox: SearchSuggestionParser::NavigationResult Class Reference
SearchSuggestionParser::NavigationResult Class Reference
#include <search_suggestion_parser.h>
Public Member Functions
NavigationResult (const AutocompleteSchemeClassifier &scheme_classifier, const GURL &url, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::u16string &description, const std::string &deletion_url, bool from_keyword, int relevance, bool relevance_from_server, const std::u16string &input_text)
NavigationResult (const NavigationResult &other)
~NavigationResult () override
const GURL & url () const
const std::u16string & description () const
const ACMatchClassifications & description_class () const
const std::u16string & formatted_url () const
void CalculateAndClassifyMatchContents (const bool allow_bolding_nothing, const std::u16string &input_text)
int CalculateRelevance (const AutocompleteInput &input, bool keyword_provider_requested) const override
Public Member Functions inherited from SearchSuggestionParser::Result
Result (bool from_keyword, int relevance, bool relevance_from_server, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::string &deletion_url)
Result (const Result &other)
virtual ~Result ()
bool from_keyword () const
const std::u16string & match_contents () const
const ACMatchClassifications & match_contents_class () const
AutocompleteMatchType::Type type () const
const std::vector< int > & subtypes () const
int relevance () const
void set_relevance (int relevance)
bool received_after_last_keystroke () const
void set_received_after_last_keystroke (bool received_after_last_keystroke)
bool relevance_from_server () const
void set_relevance_from_server (bool relevance_from_server)
const std::string & deletion_url () const
Private Member Functions
void ClassifyDescription (const std::u16string &input_text)
Private Attributes
GURL url_
std::u16string formatted_url_
std::u16string description_
ACMatchClassifications description_class_
Additional Inherited Members
Protected Attributes inherited from SearchSuggestionParser::Result
std::u16string match_contents_
ACMatchClassifications match_contents_class_
bool from_keyword_
AutocompleteMatchType::Type type_
std::vector< int > subtypes_
int relevance_
Constructor & Destructor Documentation
NavigationResult() [1/2]
SearchSuggestionParser::NavigationResult::NavigationResult (const AutocompleteSchemeClassifier & scheme_classifier, const GURL & url, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::u16string & description, const std::string & deletion_url, bool from_keyword, int relevance, bool relevance_from_server, const std::u16string & input_text)
References CalculateAndClassifyMatchContents(), ClassifyDescription(), and url_.
NavigationResult() [2/2]
SearchSuggestionParser::NavigationResult::NavigationResult (const NavigationResult & other) default
~NavigationResult()
SearchSuggestionParser::NavigationResult::~NavigationResult () override
Member Function Documentation
CalculateAndClassifyMatchContents()
void SearchSuggestionParser::NavigationResult::CalculateAndClassifyMatchContents (const bool allow_bolding_nothing, const std::u16string & input_text)
References ClassifyTermMatches(), FindTermMatches(), AutocompleteMatch::GetFormatTypes(), AutocompleteMatch::GetMatchComponents(), AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatch::ACMatchClassification::URL.
Referenced by NavigationResult().
CalculateRelevance()
int SearchSuggestionParser::NavigationResult::CalculateRelevance (const AutocompleteInput & input, bool keyword_provider_requested) const override virtual
Implements SearchSuggestionParser::Result.
Referenced by SearchProvider::ApplyCalculatedNavigationRelevance().
ClassifyDescription()
void SearchSuggestionParser::NavigationResult::ClassifyDescription (const std::u16string & input_text) private
References ClassifyTermMatches(), FindTermMatches(), AutocompleteMatch::ACMatchClassification::MATCH, and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by NavigationResult().
description()
const std::u16string& SearchSuggestionParser::NavigationResult::description () const inline
References description_.
Referenced by SearchProvider::NavigationToMatch(), and ZeroSuggestProvider::NavigationToMatch().
description_class()
const ACMatchClassifications& SearchSuggestionParser::NavigationResult::description_class () const inline
References description_class_.
Referenced by SearchProvider::NavigationToMatch().
formatted_url()
const std::u16string& SearchSuggestionParser::NavigationResult::formatted_url () const inline
References formatted_url_.
Referenced by SearchProvider::NavigationToMatch().
url()
const GURL& SearchSuggestionParser::NavigationResult::url () const inline
References url_.
Referenced by SearchProvider::NavigationToMatch(), and ZeroSuggestProvider::NavigationToMatch().
Member Data Documentation
description_
std::u16string SearchSuggestionParser::NavigationResult::description_ private
Referenced by description().
description_class_
ACMatchClassifications SearchSuggestionParser::NavigationResult::description_class_ private
Referenced by description_class().
formatted_url_
std::u16string SearchSuggestionParser::NavigationResult::formatted_url_ private
Referenced by formatted_url().
url_
GURL SearchSuggestionParser::NavigationResult::url_ private
Referenced by NavigationResult(), and url().
The documentation for this class was generated from the following files:
components/omnibox/browser/search_suggestion_parser.h
components/omnibox/browser/search_suggestion_parser.cc