Chromium Omnibox: LocationBarModelDelegate Class Reference
LocationBarModelDelegate Class Reference abstract
#include <location_bar_model_delegate.h>
Public Member Functions
virtual std::u16string FormattedStringWithEquivalentMeaning (const GURL &url, const std::u16string &formatted_url) const =0
virtual bool GetURL (GURL *url) const =0
virtual bool ShouldPreventElision ()
virtual bool ShouldTrimDisplayUrlAfterHostName () const
virtual bool ShouldDisplayURL () const
virtual bool ShouldUseUpdatedConnectionSecurityIndicators () const
virtual security_state::SecurityLevel GetSecurityLevel () const
virtual net::CertStatus GetCertStatus () const
virtual std::unique_ptr< security_state::VisibleSecurityState > GetVisibleSecurityState () const
virtual scoped_refptr< net::X509Certificate > GetCertificate () const
virtual const gfx::VectorIcon * GetVectorIconOverride () const
virtual bool IsOfflinePage () const
virtual bool IsNewTabPage () const
virtual bool IsNewTabPageURL (const GURL &url) const
virtual bool IsHomePage (const GURL &url) const
virtual AutocompleteClassifier * GetAutocompleteClassifier ()
virtual TemplateURLService * GetTemplateURLService ()
Protected Member Functions
virtual ~LocationBarModelDelegate ()
Constructor & Destructor Documentation
~LocationBarModelDelegate()
virtual LocationBarModelDelegate::~LocationBarModelDelegate () inline protected virtual
Member Function Documentation
FormattedStringWithEquivalentMeaning()
virtual std::u16string LocationBarModelDelegate::FormattedStringWithEquivalentMeaning (const GURL & url, const std::u16string & formatted_url) const pure virtual
Referenced by LocationBarModelImpl::GetFormattedURL().
GetAutocompleteClassifier()
AutocompleteClassifier * LocationBarModelDelegate::GetAutocompleteClassifier () virtual
GetCertificate()
scoped_refptr< net::X509Certificate > LocationBarModelDelegate::GetCertificate () const virtual
GetCertStatus()
net::CertStatus LocationBarModelDelegate::GetCertStatus () const virtual
Referenced by LocationBarModelImpl::GetCertStatus().
GetSecurityLevel()
security_state::SecurityLevel LocationBarModelDelegate::GetSecurityLevel () const virtual
Referenced by LocationBarModelImpl::GetSecurityLevel().
GetTemplateURLService()
TemplateURLService * LocationBarModelDelegate::GetTemplateURLService () virtual
Referenced by LocationBarModelImpl::GetPageClassification().
GetURL()
virtual bool LocationBarModelDelegate::GetURL (GURL * url) const pure virtual
Referenced by LocationBarModelImpl::GetPageClassification(), and LocationBarModelImpl::GetURL().
GetVectorIconOverride()
const gfx::VectorIcon * LocationBarModelDelegate::GetVectorIconOverride () const virtual
Referenced by LocationBarModelImpl::GetVectorIcon().
GetVisibleSecurityState()
std::unique_ptr< security_state::VisibleSecurityState > LocationBarModelDelegate::GetVisibleSecurityState () const virtual
Referenced by LocationBarModelImpl::GetSecureDisplayText().
IsHomePage()
bool LocationBarModelDelegate::IsHomePage (const GURL & url) const virtual
Referenced by LocationBarModelImpl::GetPageClassification().
IsNewTabPage()
bool LocationBarModelDelegate::IsNewTabPage () const virtual
Referenced by LocationBarModelImpl::GetPageClassification().
IsNewTabPageURL()
bool LocationBarModelDelegate::IsNewTabPageURL (const GURL & url) const virtual
Referenced by LocationBarModelImpl::GetPageClassification().
IsOfflinePage()
bool LocationBarModelDelegate::IsOfflinePage () const virtual
Referenced by LocationBarModelImpl::IsOfflinePage().
ShouldDisplayURL()
bool LocationBarModelDelegate::ShouldDisplayURL () const virtual
Referenced by LocationBarModelImpl::ShouldDisplayURL().
ShouldPreventElision()
bool LocationBarModelDelegate::ShouldPreventElision () virtual
Referenced by LocationBarModelImpl::GetFormattedURL(), and LocationBarModelImpl::ShouldPreventElision().
ShouldTrimDisplayUrlAfterHostName()
bool LocationBarModelDelegate::ShouldTrimDisplayUrlAfterHostName () const virtual
Referenced by LocationBarModelImpl::GetURLForDisplay().
ShouldUseUpdatedConnectionSecurityIndicators()
bool LocationBarModelDelegate::ShouldUseUpdatedConnectionSecurityIndicators () const virtual
Referenced by LocationBarModelImpl::GetVectorIcon().
The documentation for this class was generated from the following files:
components/omnibox/browser/location_bar_model_delegate.h
components/omnibox/browser/location_bar_model_delegate.cc