Chromium Omnibox: OmniboxFieldTrial Namespace Reference
OmniboxFieldTrial Namespace Reference
Namespaces
internal
Typedefs
typedef std::map< AutocompleteMatchType::Type, float > DemotionMultipliers
typedef std::vector< std::pair< size_t, double > > NumMatchesScores
Functions
bool IsRichAutocompletionEnabled ()
bool RichAutocompletionShowAdditionalText ()
bool IsShortBookmarkSuggestionsEnabled ()
bool IsShortBookmarkSuggestionsByTotalInputLengthEnabled ()
size_t ShortBookmarkSuggestionsByTotalInputLengthThreshold ()
int GetDisabledProviderTypes ()
bool HasDynamicFieldTrialGroupPrefix (const char *group_prefix)
void GetActiveSuggestFieldTrialHashes (std::vector< uint32_t > *field_trial_hash)
base::TimeDelta StopTimerFieldTrialDuration ()
base::Time GetLocalHistoryZeroSuggestAgeThreshold ()
bool ShortcutsScoringMaxRelevance (metrics::OmniboxEventProto::PageClassification current_page_classification, int *max_relevance)
bool SearchHistoryPreventInlining (metrics::OmniboxEventProto::PageClassification current_page_classification)
bool SearchHistoryDisable (metrics::OmniboxEventProto::PageClassification current_page_classification)
void GetDemotionsByType (metrics::OmniboxEventProto::PageClassification current_page_classification, DemotionMultipliers *demotions_by_type)
size_t GetProviderMaxMatches (AutocompleteProvider::Type provider)
bool IsMaxURLMatchesFeatureEnabled ()
size_t GetMaxURLMatches ()
void GetDefaultHUPScoringParams (HUPScoringParams *scoring_params)
void GetExperimentalHUPScoringParams (HUPScoringParams *scoring_params)
float HQPBookmarkValue ()
bool HQPAllowMatchInTLDValue ()
bool HQPAllowMatchInSchemeValue ()
void GetSuggestPollingStrategy (bool *from_last_keystroke, int *polling_delay_ms)
std::string HQPExperimentalScoringBuckets ()
float HQPExperimentalTopicalityThreshold ()
int MaxNumHQPUrlsIndexedAtStartup ()
size_t HQPMaxVisitsToScore ()
float HQPTypedValue ()
NumMatchesScores HQPNumMatchesScores ()
size_t HQPNumTitleWordsToAllow ()
bool HQPAlsoDoHUPLikeScoring ()
bool HUPSearchDatabase ()
int KeywordScoreForSufficientlyCompleteMatch ()
bool IsTabSwitchSuggestionsEnabled ()
bool IsPedalsBatch2NonEnglishEnabled ()
bool IsPedalsBatch3Enabled ()
bool IsPedalsBatch3NonEnglishEnabled ()
bool IsPedalsTranslationConsoleEnabled ()
bool IsKeywordSearchButtonEnabled ()
bool IsExperimentalKeywordModeEnabled ()
bool IsOnDeviceHeadSuggestEnabledForIncognito ()
bool IsOnDeviceHeadSuggestEnabledForNonIncognito ()
bool IsOnDeviceHeadSuggestEnabledForAnyMode ()
std::string OnDeviceHeadModelLocaleConstraint (bool is_incognito)
int OnDeviceHeadSuggestMaxScoreForNonUrlInput (bool is_incognito)
int OnDeviceSearchProviderDefaultLoaderTimeoutMs (bool is_incognito)
int OnDeviceHeadSuggestDelaySuggestRequestMs (bool is_incognito)
std::string OnDeviceHeadSuggestDemoteMode ()
bool ShouldDisableCGIParamMatching ()
bool IsActiveSearchEnginesEnabled ()
Variables
const char kBundledExperimentFieldTrialName []
const char kDisableProvidersRule [] = "DisableProviders"
const char kShortcutsScoringMaxRelevanceRule []
const char kSearchHistoryRule [] = "SearchHistory"
const char kDemoteByTypeRule [] = "DemoteByType"
const char kHQPBookmarkValueRule [] = "HQPBookmarkValue"
const char kHQPTypedValueRule [] = "HQPTypedValue"
const char kHQPAllowMatchInTLDRule [] = "HQPAllowMatchInTLD"
const char kHQPAllowMatchInSchemeRule []
const char kMeasureSuggestPollingDelayFromLastKeystrokeRule []
const char kSuggestPollingDelayMsRule []
const char kHQPMaxVisitsToScoreRule []
const char kHQPNumMatchesScoresRule []
const char kHQPNumTitleWordsRule [] = "HQPNumTitleWords"
const char kHQPAlsoDoHUPLikeScoringRule []
const char kHUPSearchDatabaseRule [] = "HUPSearchDatabase"
const char kPreventUWYTDefaultForNonURLInputsRule []
const char kKeywordRequiresRegistryRule []
const char kKeywordScoreForSufficientlyCompleteMatchRule []
const char kHQPAllowDupMatchesForScoringRule []
const char kEmphasizeTitlesRule []
const char kHUPNewScoringTypedCountRelevanceCapParam []
const char kHUPNewScoringTypedCountHalfLifeTimeParam []
const char kHUPNewScoringTypedCountScoreBucketsParam []
const char kHUPNewScoringTypedCountUseDecayFactorParam []
const char kHUPNewScoringVisitedCountRelevanceCapParam []
const char kHUPNewScoringVisitedCountHalfLifeTimeParam []
const char kHUPNewScoringVisitedCountScoreBucketsParam []
const char kHUPNewScoringVisitedCountUseDecayFactorParam []
const char kHQPExperimentalScoringBucketsParam []
const char kHQPExperimentalScoringTopicalityThresholdParam []
const char kMaxNumHQPUrlsIndexedAtStartupOnLowEndDevicesParam []
const char kMaxNumHQPUrlsIndexedAtStartupOnNonLowEndDevicesParam []
const char kOmniboxLocalZeroSuggestAgeThresholdParam []
const char kMaxZeroSuggestMatchesParam []
const char kOmniboxMaxURLMatchesParam []
const char kUIMaxAutocompleteMatchesByProviderParam []
const char kUIMaxAutocompleteMatchesParam []
const char kDynamicMaxAutocompleteUrlCutoffParam []
const char kDynamicMaxAutocompleteIncreasedLimitParam []
const char kOnDeviceHeadModelLocaleConstraint []
const char kOnDeviceHeadSuggestMaxScoreForNonUrlInput []
const char kOnDeviceHeadSuggestDelaySuggestRequestMs []
const char kOnDeviceSearchProviderDefaultLoaderTimeoutMs []
const char kOnDeviceHeadSuggestDemoteMode []
int kDefaultMinimumTimeBetweenSuggestQueriesMs = 100
const char kOmniboxUIUnelideURLOnHoverThresholdMsParam []
const base::FeatureParam< bool > kRichAutocompletionAutocompleteTitles
const base::FeatureParam< bool > kRichAutocompletionAutocompleteTitlesShortcutProvider
const base::FeatureParam< bool > kRichAutocompletionAutocompleteTitlesNoInputsWithSpaces
const base::FeatureParam< int > kRichAutocompletionAutocompleteTitlesMinChar
const base::FeatureParam< bool > kRichAutocompletionAutocompleteNonPrefixAll
const base::FeatureParam< bool > kRichAutocompletionAutocompleteNonPrefixShortcutProvider
const base::FeatureParam< bool > kRichAutocompletionAutocompleteNonPrefixNoInputsWithSpaces
const base::FeatureParam< int > kRichAutocompletionAutocompleteNonPrefixMinChar
const base::FeatureParam< bool > kRichAutocompletionShowAdditionalText
const base::FeatureParam< bool > kRichAutocompletionSplitTitleCompletion
const base::FeatureParam< bool > kRichAutocompletionSplitUrlCompletion
const base::FeatureParam< int > kRichAutocompletionSplitCompletionMinChar
const base::FeatureParam< bool > kRichAutocompletionCounterfactual
const base::FeatureParam< bool > kRichAutocompletionAutocompletePreferUrlsOverPrefixes
const base::FeatureParam< std::string > kBookmarkPathsCounterfactual
const base::FeatureParam< bool > kBookmarkPathsUiReplaceTitle
const base::FeatureParam< bool > kBookmarkPathsUiReplaceUrl
const base::FeatureParam< bool > kBookmarkPathsUiAppendAfterTitle
const base::FeatureParam< bool > kBookmarkPathsUiDynamicReplaceUrl
const base::FeatureParam< bool > kShortBookmarkSuggestionsByTotalInputLengthCounterfactual
const base::FeatureParam< int > kShortBookmarkSuggestionsByTotalInputLengthThreshold
Typedef Documentation
DemotionMultipliers
typedef std::map<AutocompleteMatchType::Type, float> OmniboxFieldTrial::DemotionMultipliers
NumMatchesScores
typedef std::vector<std::pair<size_t, double> > OmniboxFieldTrial::NumMatchesScores
Function Documentation
GetActiveSuggestFieldTrialHashes()
void OmniboxFieldTrial::GetActiveSuggestFieldTrialHashes (std::vector< uint32_t > * field_trial_hash)
References kBundledExperimentFieldTrialName.
Referenced by OmniboxPedalProvider::AddProviderInfo(), BaseSearchProvider::AddProviderInfo(), ClipboardProvider::AddProviderInfo(), and DocumentProvider::AddProviderInfo().
GetDefaultHUPScoringParams()
void OmniboxFieldTrial::GetDefaultHUPScoringParams (HUPScoringParams * scoring_params)
References HUPScoringParams::ScoreBuckets::set_half_life_days(), HUPScoringParams::typed_count_buckets, and HUPScoringParams::visited_count_buckets.
Referenced by HistoryURLProvider::HistoryURLProvider().
GetDemotionsByType()
void OmniboxFieldTrial::GetDemotionsByType (metrics::OmniboxEventProto::PageClassification current_page_classification, DemotionMultipliers * demotions_by_type)
Referenced by CompareWithDemoteByType< Match >::CompareWithDemoteByType().
GetDisabledProviderTypes()
int OmniboxFieldTrial::GetDisabledProviderTypes ()
References kBundledExperimentFieldTrialName, and kDisableProvidersRule.
Referenced by AutocompleteController::AutocompleteController().
GetExperimentalHUPScoringParams()
void OmniboxFieldTrial::GetExperimentalHUPScoringParams (HUPScoringParams * scoring_params)
References kBundledExperimentFieldTrialName, kHUPNewScoringTypedCountHalfLifeTimeParam, kHUPNewScoringTypedCountRelevanceCapParam, kHUPNewScoringTypedCountScoreBucketsParam, kHUPNewScoringTypedCountUseDecayFactorParam, kHUPNewScoringVisitedCountHalfLifeTimeParam, kHUPNewScoringVisitedCountRelevanceCapParam, kHUPNewScoringVisitedCountScoreBucketsParam, kHUPNewScoringVisitedCountUseDecayFactorParam, HUPScoringParams::typed_count_buckets, and HUPScoringParams::visited_count_buckets.
Referenced by HistoryURLProvider::HistoryURLProvider().
GetLocalHistoryZeroSuggestAgeThreshold()
base::Time OmniboxFieldTrial::GetLocalHistoryZeroSuggestAgeThreshold ()
References omnibox::kOmniboxLocalZeroSuggestAgeThreshold, and kOmniboxLocalZeroSuggestAgeThresholdParam.
Referenced by LocalHistoryZeroSuggestProvider::DeleteMatch(), and LocalHistoryZeroSuggestProvider::QueryURLDatabase().
GetMaxURLMatches()
size_t OmniboxFieldTrial::GetMaxURLMatches ()
References omnibox::kOmniboxMaxURLMatches, and kOmniboxMaxURLMatchesParam.
Referenced by AutocompleteResult::SortAndCull().
GetProviderMaxMatches()
size_t OmniboxFieldTrial::GetProviderMaxMatches (AutocompleteProvider::Type provider)
References omnibox::kUIExperimentMaxAutocompleteMatches, and kUIMaxAutocompleteMatchesByProviderParam.
GetSuggestPollingStrategy()
void OmniboxFieldTrial::GetSuggestPollingStrategy (bool * from_last_keystroke, int * polling_delay_ms)
References kBundledExperimentFieldTrialName, kDefaultMinimumTimeBetweenSuggestQueriesMs, kMeasureSuggestPollingDelayFromLastKeystrokeRule, and kSuggestPollingDelayMsRule.
Referenced by SearchProvider::GetSuggestQueryDelay().
HasDynamicFieldTrialGroupPrefix()
bool OmniboxFieldTrial::HasDynamicFieldTrialGroupPrefix (const char * group_prefix)
HQPAllowMatchInSchemeValue()
bool OmniboxFieldTrial::HQPAllowMatchInSchemeValue ()
References kBundledExperimentFieldTrialName, and kHQPAllowMatchInSchemeRule.
Referenced by ScoredHistoryMatch::Init().
HQPAllowMatchInTLDValue()
bool OmniboxFieldTrial::HQPAllowMatchInTLDValue ()
References kBundledExperimentFieldTrialName, and kHQPAllowMatchInTLDRule.
Referenced by ScoredHistoryMatch::Init().
HQPAlsoDoHUPLikeScoring()
bool OmniboxFieldTrial::HQPAlsoDoHUPLikeScoring ()
References kBundledExperimentFieldTrialName, and kHQPAlsoDoHUPLikeScoringRule.
Referenced by ScoredHistoryMatch::Init().
HQPBookmarkValue()
float OmniboxFieldTrial::HQPBookmarkValue ()
References kBundledExperimentFieldTrialName, and kHQPBookmarkValueRule.
Referenced by ScoredHistoryMatch::Init().
HQPExperimentalScoringBuckets()
std::string OmniboxFieldTrial::HQPExperimentalScoringBuckets ()
References kBundledExperimentFieldTrialName, and kHQPExperimentalScoringBucketsParam.
Referenced by ScoredHistoryMatch::GetHQPBuckets().
HQPExperimentalTopicalityThreshold()
float OmniboxFieldTrial::HQPExperimentalTopicalityThreshold ()
References kBundledExperimentFieldTrialName, and kHQPExperimentalScoringTopicalityThresholdParam.
Referenced by ScoredHistoryMatch::Init().
HQPMaxVisitsToScore()
size_t OmniboxFieldTrial::HQPMaxVisitsToScore ()
References kBundledExperimentFieldTrialName, kHQPMaxVisitsToScoreRule, and URLIndexPrivateData::kMaxVisitsToStoreInCache.
Referenced by ScoredHistoryMatch::Init().
HQPNumMatchesScores()
OmniboxFieldTrial::NumMatchesScores OmniboxFieldTrial::HQPNumMatchesScores ()
References kBundledExperimentFieldTrialName, and kHQPNumMatchesScoresRule.
Referenced by ScoredHistoryMatch::GetDocumentSpecificityScore().
HQPNumTitleWordsToAllow()
size_t OmniboxFieldTrial::HQPNumTitleWordsToAllow ()
References kBundledExperimentFieldTrialName, and kHQPNumTitleWordsRule.
Referenced by ScoredHistoryMatch::Init().
HQPTypedValue()
float OmniboxFieldTrial::HQPTypedValue ()
References kBundledExperimentFieldTrialName, and kHQPTypedValueRule.
Referenced by ScoredHistoryMatch::Init().
HUPSearchDatabase()
bool OmniboxFieldTrial::HUPSearchDatabase ()
References kBundledExperimentFieldTrialName, and kHUPSearchDatabaseRule.
IsActiveSearchEnginesEnabled()
bool OmniboxFieldTrial::IsActiveSearchEnginesEnabled ()
References omnibox::kActiveSearchEngines.
Referenced by KeywordProvider::GetKeywordForText().
IsExperimentalKeywordModeEnabled()
bool OmniboxFieldTrial::IsExperimentalKeywordModeEnabled ()
References omnibox::kExperimentalKeywordMode.
Referenced by AutocompleteProvider::InExplicitExperimentalKeywordMode(), and DocumentProvider::IsDocumentProviderAllowed().
IsKeywordSearchButtonEnabled()
bool OmniboxFieldTrial::IsKeywordSearchButtonEnabled ()
References omnibox::kOmniboxKeywordSearchButton.
Referenced by OmniboxEditModel::AcceptKeyword(), OmniboxPopupSelection::GetAllAvailableSelectionsSorted(), KeywordProvider::GetKeywordForText(), OmniboxPopupSelection::IsControlPresentOnMatch(), OmniboxResultView::OnSelectionStateChanged(), OmniboxResultView::SetMatch(), and OmniboxSuggestionButtonRowView::SetPillButtonVisibility().
IsMaxURLMatchesFeatureEnabled()
bool OmniboxFieldTrial::IsMaxURLMatchesFeatureEnabled ()
References omnibox::kOmniboxMaxURLMatches.
Referenced by AutocompleteResult::SortAndCull().
IsOnDeviceHeadSuggestEnabledForAnyMode()
bool OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForAnyMode ()
References IsOnDeviceHeadSuggestEnabledForIncognito(), and IsOnDeviceHeadSuggestEnabledForNonIncognito().
Referenced by AutocompleteClassifier::DefaultOmniboxProviders().
IsOnDeviceHeadSuggestEnabledForIncognito()
bool OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForIncognito ()
References omnibox::kOnDeviceHeadProviderIncognito.
Referenced by OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed(), and IsOnDeviceHeadSuggestEnabledForAnyMode().
IsOnDeviceHeadSuggestEnabledForNonIncognito()
bool OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForNonIncognito ()
References omnibox::kOnDeviceHeadProviderNonIncognito.
Referenced by OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed(), and IsOnDeviceHeadSuggestEnabledForAnyMode().
IsPedalsBatch2NonEnglishEnabled()
bool OmniboxFieldTrial::IsPedalsBatch2NonEnglishEnabled ()
References omnibox::kOmniboxPedalsBatch2NonEnglish.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
IsPedalsBatch3Enabled()
bool OmniboxFieldTrial::IsPedalsBatch3Enabled ()
References omnibox::kOmniboxPedalsBatch3.
Referenced by GetPedalImplementations().
IsPedalsBatch3NonEnglishEnabled()
bool OmniboxFieldTrial::IsPedalsBatch3NonEnglishEnabled ()
References omnibox::kOmniboxPedalsBatch3NonEnglish.
Referenced by OmniboxPedalProvider::LoadPedalConcepts().
IsPedalsTranslationConsoleEnabled()
bool OmniboxFieldTrial::IsPedalsTranslationConsoleEnabled ()
References omnibox::kOmniboxPedalsTranslationConsole.
Referenced by OmniboxPedal::SynonymGroup::AddSynonym(), and OmniboxPedalProvider::LoadPedalConcepts().
IsRichAutocompletionEnabled()
bool OmniboxFieldTrial::IsRichAutocompletionEnabled ()
References omnibox::kRichAutocompletion.
Referenced by IsShortBookmarkSuggestionsByTotalInputLengthEnabled(), RichAutocompletionShowAdditionalText(), ShortBookmarkSuggestionsByTotalInputLengthThreshold(), and AutocompleteMatch::TryRichAutocompletion().
IsShortBookmarkSuggestionsByTotalInputLengthEnabled()
bool OmniboxFieldTrial::IsShortBookmarkSuggestionsByTotalInputLengthEnabled ()
References IsRichAutocompletionEnabled(), kRichAutocompletionAutocompleteNonPrefixAll, kRichAutocompletionAutocompleteTitles, and omnibox::kShortBookmarkSuggestionsByTotalInputLength.
Referenced by BookmarkProvider::GetMatchingAlgorithm().
IsShortBookmarkSuggestionsEnabled()
bool OmniboxFieldTrial::IsShortBookmarkSuggestionsEnabled ()
References omnibox::kShortBookmarkSuggestions.
Referenced by BookmarkProvider::GetMatchingAlgorithm().
IsTabSwitchSuggestionsEnabled()
bool OmniboxFieldTrial::IsTabSwitchSuggestionsEnabled ()
References omnibox::kOmniboxTabSwitchSuggestions.
Referenced by AutocompleteController::UpdateResult().
KeywordScoreForSufficientlyCompleteMatch()
int OmniboxFieldTrial::KeywordScoreForSufficientlyCompleteMatch ()
References kBundledExperimentFieldTrialName, and kKeywordScoreForSufficientlyCompleteMatchRule.
Referenced by KeywordProvider::CalculateRelevance().
MaxNumHQPUrlsIndexedAtStartup()
int OmniboxFieldTrial::MaxNumHQPUrlsIndexedAtStartup ()
References kBundledExperimentFieldTrialName, kMaxNumHQPUrlsIndexedAtStartupOnLowEndDevicesParam, and kMaxNumHQPUrlsIndexedAtStartupOnNonLowEndDevicesParam.
Referenced by URLIndexPrivateData::RebuildFromHistory().
OnDeviceHeadModelLocaleConstraint()
std::string OmniboxFieldTrial::OnDeviceHeadModelLocaleConstraint (bool is_incognito)
References kOnDeviceHeadModelLocaleConstraint, omnibox::kOnDeviceHeadProviderIncognito, and omnibox::kOnDeviceHeadProviderNonIncognito.
OnDeviceHeadSuggestDelaySuggestRequestMs()
int OmniboxFieldTrial::OnDeviceHeadSuggestDelaySuggestRequestMs (bool is_incognito)
References omnibox::kOnDeviceHeadProviderNonIncognito, and kOnDeviceHeadSuggestDelaySuggestRequestMs.
Referenced by OnDeviceHeadProvider::Start().
OnDeviceHeadSuggestDemoteMode()
std::string OmniboxFieldTrial::OnDeviceHeadSuggestDemoteMode ()
References omnibox::kOnDeviceHeadProviderNonIncognito, and kOnDeviceHeadSuggestDemoteMode.
Referenced by AutocompleteResult::DemoteOnDeviceSearchSuggestions().
OnDeviceHeadSuggestMaxScoreForNonUrlInput()
int OmniboxFieldTrial::OnDeviceHeadSuggestMaxScoreForNonUrlInput (bool is_incognito)
References omnibox::kOnDeviceHeadProviderNonIncognito, and kOnDeviceHeadSuggestMaxScoreForNonUrlInput.
Referenced by OnDeviceHeadProvider::SearchDone().
OnDeviceSearchProviderDefaultLoaderTimeoutMs()
int OmniboxFieldTrial::OnDeviceSearchProviderDefaultLoaderTimeoutMs (bool is_incognito)
References omnibox::kOnDeviceHeadProviderNonIncognito, and kOnDeviceSearchProviderDefaultLoaderTimeoutMs.
Referenced by SearchProvider::Run().
RichAutocompletionShowAdditionalText()
bool OmniboxFieldTrial::RichAutocompletionShowAdditionalText ()
References IsRichAutocompletionEnabled(), and kRichAutocompletionShowAdditionalText.
SearchHistoryDisable()
bool OmniboxFieldTrial::SearchHistoryDisable (metrics::OmniboxEventProto::PageClassification current_page_classification)
Referenced by SearchProvider::DoHistoryQuery().
SearchHistoryPreventInlining()
bool OmniboxFieldTrial::SearchHistoryPreventInlining (metrics::OmniboxEventProto::PageClassification current_page_classification)
Referenced by SearchProvider::ScoreHistoryResultsHelper().
ShortBookmarkSuggestionsByTotalInputLengthThreshold()
size_t OmniboxFieldTrial::ShortBookmarkSuggestionsByTotalInputLengthThreshold ()
References IsRichAutocompletionEnabled(), kRichAutocompletionAutocompleteNonPrefixAll, kRichAutocompletionAutocompleteNonPrefixMinChar, kRichAutocompletionAutocompleteTitles, kRichAutocompletionAutocompleteTitlesMinChar, omnibox::kShortBookmarkSuggestionsByTotalInputLength, and kShortBookmarkSuggestionsByTotalInputLengthThreshold.
Referenced by BookmarkProvider::GetMatchingAlgorithm().
ShortcutsScoringMaxRelevance()
bool OmniboxFieldTrial::ShortcutsScoringMaxRelevance (metrics::OmniboxEventProto::PageClassification current_page_classification, int * max_relevance)
Referenced by ShortcutsProvider::GetMatches().
ShouldDisableCGIParamMatching()
bool OmniboxFieldTrial::ShouldDisableCGIParamMatching ()
References omnibox::kDisableCGIParamMatching.
Referenced by BookmarkProvider::DoAutocomplete(), and ScoredHistoryMatch::GetTopicalityScore().
StopTimerFieldTrialDuration()
base::TimeDelta OmniboxFieldTrial::StopTimerFieldTrialDuration ()
Variable Documentation
kBookmarkPathsCounterfactual
const base::FeatureParam<std::string> OmniboxFieldTrial::kBookmarkPathsCounterfactual extern
Referenced by BookmarkProvider::GetMatchesWithBookmarkPaths().
kBookmarkPathsUiAppendAfterTitle
const base::FeatureParam<bool> OmniboxFieldTrial::kBookmarkPathsUiAppendAfterTitle extern
Referenced by bookmarks::TitledUrlMatchToAutocompleteMatch().
kBookmarkPathsUiDynamicReplaceUrl
const base::FeatureParam<bool> OmniboxFieldTrial::kBookmarkPathsUiDynamicReplaceUrl extern
Referenced by bookmarks::TitledUrlMatchToAutocompleteMatch().
kBookmarkPathsUiReplaceTitle
const base::FeatureParam<bool> OmniboxFieldTrial::kBookmarkPathsUiReplaceTitle extern
Referenced by bookmarks::TitledUrlMatchToAutocompleteMatch().
kBookmarkPathsUiReplaceUrl
const base::FeatureParam<bool> OmniboxFieldTrial::kBookmarkPathsUiReplaceUrl extern
Referenced by bookmarks::TitledUrlMatchToAutocompleteMatch().
kBundledExperimentFieldTrialName
const char OmniboxFieldTrial::kBundledExperimentFieldTrialName extern
Initial value:
=
    "OmniboxBundledExperimentV1"
Referenced by GetActiveSuggestFieldTrialHashes(), GetDisabledProviderTypes(), GetExperimentalHUPScoringParams(), GetSuggestPollingStrategy(), HQPAllowMatchInSchemeValue(), HQPAllowMatchInTLDValue(), HQPAlsoDoHUPLikeScoring(), HQPBookmarkValue(), HQPExperimentalScoringBuckets(), HQPExperimentalTopicalityThreshold(), HQPMaxVisitsToScore(), HQPNumMatchesScores(), HQPNumTitleWordsToAllow(), HQPTypedValue(), HUPSearchDatabase(), KeywordScoreForSufficientlyCompleteMatch(), and MaxNumHQPUrlsIndexedAtStartup().
kDefaultMinimumTimeBetweenSuggestQueriesMs
int OmniboxFieldTrial::kDefaultMinimumTimeBetweenSuggestQueriesMs = 100 extern
Referenced by GetSuggestPollingStrategy().
kDemoteByTypeRule
const char OmniboxFieldTrial::kDemoteByTypeRule = "DemoteByType" extern
kDisableProvidersRule
const char OmniboxFieldTrial::kDisableProvidersRule = "DisableProviders" extern
Referenced by GetDisabledProviderTypes().
kDynamicMaxAutocompleteIncreasedLimitParam
const char OmniboxFieldTrial::kDynamicMaxAutocompleteIncreasedLimitParam extern
Initial value:
=
    "OmniboxDynamicMaxAutocompleteIncreasedLimit"
Referenced by AutocompleteResult::GetDynamicMaxMatches().
kDynamicMaxAutocompleteUrlCutoffParam
const char OmniboxFieldTrial::kDynamicMaxAutocompleteUrlCutoffParam extern
Initial value:
=
    "OmniboxDynamicMaxAutocompleteUrlCutoff"
Referenced by AutocompleteResult::CalculateNumMatchesPerUrlCount().
kEmphasizeTitlesRule
const char OmniboxFieldTrial::kEmphasizeTitlesRule[] extern
kHQPAllowDupMatchesForScoringRule
const char OmniboxFieldTrial::kHQPAllowDupMatchesForScoringRule[] extern
kHQPAllowMatchInSchemeRule
const char OmniboxFieldTrial::kHQPAllowMatchInSchemeRule extern
Initial value:
=
    "HQPAllowMatchInScheme"
Referenced by HQPAllowMatchInSchemeValue().
kHQPAllowMatchInTLDRule
const char OmniboxFieldTrial::kHQPAllowMatchInTLDRule = "HQPAllowMatchInTLD" extern
Referenced by HQPAllowMatchInTLDValue().
kHQPAlsoDoHUPLikeScoringRule
const char OmniboxFieldTrial::kHQPAlsoDoHUPLikeScoringRule extern
Initial value:
=
    "HQPAlsoDoHUPLikeScoring"
Referenced by HQPAlsoDoHUPLikeScoring().
kHQPBookmarkValueRule
const char OmniboxFieldTrial::kHQPBookmarkValueRule = "HQPBookmarkValue" extern
Referenced by HQPBookmarkValue().
kHQPExperimentalScoringBucketsParam
const char OmniboxFieldTrial::kHQPExperimentalScoringBucketsParam extern
Initial value:
=
    "HQPExperimentalScoringBuckets"
Referenced by HQPExperimentalScoringBuckets().
kHQPExperimentalScoringTopicalityThresholdParam
const char OmniboxFieldTrial::kHQPExperimentalScoringTopicalityThresholdParam extern
Initial value:
=
        "HQPExperimentalScoringTopicalityThreshold"
Referenced by HQPExperimentalTopicalityThreshold().
kHQPMaxVisitsToScoreRule
const char OmniboxFieldTrial::kHQPMaxVisitsToScoreRule extern
Initial value:
=
    "HQPMaxVisitsToScoreRule"
Referenced by HQPMaxVisitsToScore().
kHQPNumMatchesScoresRule
const char OmniboxFieldTrial::kHQPNumMatchesScoresRule extern
Initial value:
=
    "HQPNumMatchesScores"
Referenced by HQPNumMatchesScores().
kHQPNumTitleWordsRule
const char OmniboxFieldTrial::kHQPNumTitleWordsRule = "HQPNumTitleWords" extern
Referenced by HQPNumTitleWordsToAllow().
kHQPTypedValueRule
const char OmniboxFieldTrial::kHQPTypedValueRule = "HQPTypedValue" extern
Referenced by HQPTypedValue().
kHUPNewScoringTypedCountHalfLifeTimeParam
const char OmniboxFieldTrial::kHUPNewScoringTypedCountHalfLifeTimeParam extern
Initial value:
=
    "TypedCountHalfLifeTime"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringTypedCountRelevanceCapParam
const char OmniboxFieldTrial::kHUPNewScoringTypedCountRelevanceCapParam extern
Initial value:
=
    "TypedCountRelevanceCap"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringTypedCountScoreBucketsParam
const char OmniboxFieldTrial::kHUPNewScoringTypedCountScoreBucketsParam extern
Initial value:
=
    "TypedCountScoreBuckets"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringTypedCountUseDecayFactorParam
const char OmniboxFieldTrial::kHUPNewScoringTypedCountUseDecayFactorParam extern
Initial value:
=
    "TypedCountUseDecayFactor"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringVisitedCountHalfLifeTimeParam
const char OmniboxFieldTrial::kHUPNewScoringVisitedCountHalfLifeTimeParam extern
Initial value:
=
    "VisitedCountHalfLifeTime"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringVisitedCountRelevanceCapParam
const char OmniboxFieldTrial::kHUPNewScoringVisitedCountRelevanceCapParam extern
Initial value:
=
    "VisitedCountRelevanceCap"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringVisitedCountScoreBucketsParam
const char OmniboxFieldTrial::kHUPNewScoringVisitedCountScoreBucketsParam extern
Initial value:
=
    "VisitedCountScoreBuckets"
Referenced by GetExperimentalHUPScoringParams().
kHUPNewScoringVisitedCountUseDecayFactorParam
const char OmniboxFieldTrial::kHUPNewScoringVisitedCountUseDecayFactorParam extern
Initial value:
=
    "VisitedCountUseDecayFactor"
Referenced by GetExperimentalHUPScoringParams().
kHUPSearchDatabaseRule
const char OmniboxFieldTrial::kHUPSearchDatabaseRule = "HUPSearchDatabase" extern
Referenced by HUPSearchDatabase().
kKeywordRequiresRegistryRule
const char OmniboxFieldTrial::kKeywordRequiresRegistryRule extern
Initial value:
=
    "KeywordRequiresRegistry"
kKeywordScoreForSufficientlyCompleteMatchRule
const char OmniboxFieldTrial::kKeywordScoreForSufficientlyCompleteMatchRule extern
Initial value:
=
    "KeywordScoreForSufficientlyCompleteMatch"
Referenced by KeywordScoreForSufficientlyCompleteMatch().
kMaxNumHQPUrlsIndexedAtStartupOnLowEndDevicesParam
const char OmniboxFieldTrial::kMaxNumHQPUrlsIndexedAtStartupOnLowEndDevicesParam extern
Initial value:
=
        "MaxNumHQPUrlsIndexedAtStartupOnLowEndDevices"
Referenced by MaxNumHQPUrlsIndexedAtStartup().
kMaxNumHQPUrlsIndexedAtStartupOnNonLowEndDevicesParam
const char OmniboxFieldTrial::kMaxNumHQPUrlsIndexedAtStartupOnNonLowEndDevicesParam extern
Initial value:
=
        "MaxNumHQPUrlsIndexedAtStartupOnNonLowEndDevices"
Referenced by MaxNumHQPUrlsIndexedAtStartup().
kMaxZeroSuggestMatchesParam
const char OmniboxFieldTrial::kMaxZeroSuggestMatchesParam extern
Initial value:
=
    "MaxZeroSuggestMatches"
Referenced by AutocompleteResult::GetMaxMatches().
kMeasureSuggestPollingDelayFromLastKeystrokeRule
const char OmniboxFieldTrial::kMeasureSuggestPollingDelayFromLastKeystrokeRule extern
Initial value:
=
        "MeasureSuggestPollingDelayFromLastKeystroke"
Referenced by GetSuggestPollingStrategy().
kOmniboxLocalZeroSuggestAgeThresholdParam
const char OmniboxFieldTrial::kOmniboxLocalZeroSuggestAgeThresholdParam extern
Initial value:
=
    "OmniboxLocalZeroSuggestAgeThreshold"
Referenced by GetLocalHistoryZeroSuggestAgeThreshold().
kOmniboxMaxURLMatchesParam
const char OmniboxFieldTrial::kOmniboxMaxURLMatchesParam extern
Initial value:
=
    "OmniboxMaxURLMatches"
Referenced by GetMaxURLMatches().
kOmniboxUIUnelideURLOnHoverThresholdMsParam
const char OmniboxFieldTrial::kOmniboxUIUnelideURLOnHoverThresholdMsParam[] extern
kOnDeviceHeadModelLocaleConstraint
const char OmniboxFieldTrial::kOnDeviceHeadModelLocaleConstraint extern
Initial value:
=
    "ForceModelLocaleConstraint"
Referenced by OnDeviceHeadModelLocaleConstraint().
kOnDeviceHeadSuggestDelaySuggestRequestMs
const char OmniboxFieldTrial::kOnDeviceHeadSuggestDelaySuggestRequestMs extern
Initial value:
=
    "DelayOnDeviceHeadSuggestRequestMs"
Referenced by OnDeviceHeadSuggestDelaySuggestRequestMs().
kOnDeviceHeadSuggestDemoteMode
const char OmniboxFieldTrial::kOnDeviceHeadSuggestDemoteMode extern
Initial value:
=
    "DemoteOnDeviceSearchSuggestionsMode"
Referenced by OnDeviceHeadSuggestDemoteMode().
kOnDeviceHeadSuggestMaxScoreForNonUrlInput
const char OmniboxFieldTrial::kOnDeviceHeadSuggestMaxScoreForNonUrlInput extern
Initial value:
=
    "OnDeviceSuggestMaxScoreForNonUrlInput"
Referenced by OnDeviceHeadSuggestMaxScoreForNonUrlInput().
kOnDeviceSearchProviderDefaultLoaderTimeoutMs
const char OmniboxFieldTrial::kOnDeviceSearchProviderDefaultLoaderTimeoutMs extern
Initial value:
=
    "SearchProviderDefaultLoaderTimeoutMs"
Referenced by OnDeviceSearchProviderDefaultLoaderTimeoutMs().
kPreventUWYTDefaultForNonURLInputsRule
const char OmniboxFieldTrial::kPreventUWYTDefaultForNonURLInputsRule[] extern
kRichAutocompletionAutocompleteNonPrefixAll
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteNonPrefixAll extern
Referenced by IsShortBookmarkSuggestionsByTotalInputLengthEnabled(), ShortBookmarkSuggestionsByTotalInputLengthThreshold(), and AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteNonPrefixMinChar
const base::FeatureParam<int> OmniboxFieldTrial::kRichAutocompletionAutocompleteNonPrefixMinChar extern
Referenced by ShortBookmarkSuggestionsByTotalInputLengthThreshold(), and AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteNonPrefixNoInputsWithSpaces
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteNonPrefixNoInputsWithSpaces extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteNonPrefixShortcutProvider
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteNonPrefixShortcutProvider extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompletePreferUrlsOverPrefixes
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompletePreferUrlsOverPrefixes extern
Referenced by AutocompleteMatch::BetterDuplicate(), and AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteTitles
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteTitles extern
Referenced by IsShortBookmarkSuggestionsByTotalInputLengthEnabled(), ShortBookmarkSuggestionsByTotalInputLengthThreshold(), and AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteTitlesMinChar
const base::FeatureParam<int> OmniboxFieldTrial::kRichAutocompletionAutocompleteTitlesMinChar extern
Referenced by ShortBookmarkSuggestionsByTotalInputLengthThreshold(), and AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteTitlesNoInputsWithSpaces
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteTitlesNoInputsWithSpaces extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionAutocompleteTitlesShortcutProvider
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionAutocompleteTitlesShortcutProvider extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionCounterfactual
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionCounterfactual extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionShowAdditionalText
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionShowAdditionalText extern
Referenced by RichAutocompletionShowAdditionalText().
kRichAutocompletionSplitCompletionMinChar
const base::FeatureParam<int> OmniboxFieldTrial::kRichAutocompletionSplitCompletionMinChar extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionSplitTitleCompletion
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionSplitTitleCompletion extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kRichAutocompletionSplitUrlCompletion
const base::FeatureParam<bool> OmniboxFieldTrial::kRichAutocompletionSplitUrlCompletion extern
Referenced by AutocompleteMatch::TryRichAutocompletion().
kSearchHistoryRule
const char OmniboxFieldTrial::kSearchHistoryRule = "SearchHistory" extern
kShortBookmarkSuggestionsByTotalInputLengthCounterfactual
const base::FeatureParam<bool> OmniboxFieldTrial::kShortBookmarkSuggestionsByTotalInputLengthCounterfactual extern
kShortBookmarkSuggestionsByTotalInputLengthThreshold
const base::FeatureParam<int> OmniboxFieldTrial::kShortBookmarkSuggestionsByTotalInputLengthThreshold extern
Referenced by ShortBookmarkSuggestionsByTotalInputLengthThreshold().
kShortcutsScoringMaxRelevanceRule
const char OmniboxFieldTrial::kShortcutsScoringMaxRelevanceRule extern
Initial value:
=
    "ShortcutsScoringMaxRelevance"
kSuggestPollingDelayMsRule
const char OmniboxFieldTrial::kSuggestPollingDelayMsRule extern
Initial value:
=
    "SuggestPollingDelayMs"
Referenced by GetSuggestPollingStrategy().
kUIMaxAutocompleteMatchesByProviderParam
const char OmniboxFieldTrial::kUIMaxAutocompleteMatchesByProviderParam extern
Initial value:
=
    "UIMaxAutocompleteMatchesByProvider"
Referenced by GetProviderMaxMatches().
kUIMaxAutocompleteMatchesParam
const char OmniboxFieldTrial::kUIMaxAutocompleteMatchesParam extern
Initial value:
=
    "UIMaxAutocompleteMatches"
Referenced by AutocompleteResult::GetMaxMatches().