Chromium Omnibox: HistoryURLProvider::VisitClassifier Class Reference
HistoryURLProvider::VisitClassifier Class Reference
Public Types
enum Type { INVALID , UNVISITED_INTRANET , VISITED }
Public Member Functions
VisitClassifier (HistoryURLProvider *provider, const AutocompleteInput &input, history::URLDatabase *db)
VisitClassifier (const VisitClassifier &)=delete
VisitClassifier & operator= (const VisitClassifier &)=delete
Type type () const
const history::URLRow & url_row () const
Private Attributes
HistoryURLProvider * provider_
history::URLDatabase * db_
Type type_
history::URLRow url_row_
Member Enumeration Documentation
Type
enum HistoryURLProvider::VisitClassifier::Type
Enumerator
INVALID
UNVISITED_INTRANET
VISITED
Constructor & Destructor Documentation
VisitClassifier() [1/2]
HistoryURLProvider::VisitClassifier::VisitClassifier (HistoryURLProvider * provider, const AutocompleteInput & input, history::URLDatabase * db)
References HistoryURLProvider::AsKnownIntranetURL(), AutocompleteInput::canonicalized_url(), db_, AutocompleteInput::desired_tld(), URLPrefix::GetURLPrefixes(), AutocompleteInput::parts(), provider_, AutocompleteInput::text(), AutocompleteInput::type(), type_, UNVISITED_INTRANET, url_row_, and VISITED.
VisitClassifier() [2/2]
HistoryURLProvider::VisitClassifier::VisitClassifier (const VisitClassifier &) delete
Member Function Documentation
operator=()
VisitClassifier& HistoryURLProvider::VisitClassifier::operator= (const VisitClassifier &) delete
type()
Type HistoryURLProvider::VisitClassifier::type () const inline
References type_.
Referenced by HistoryURLProvider::DoAutocomplete(), and HistoryURLProvider::FixupExactSuggestion().
url_row()
const history::URLRow& HistoryURLProvider::VisitClassifier::url_row () const inline
References url_row_.
Referenced by HistoryURLProvider::FixupExactSuggestion().
Member Data Documentation
db_
history::URLDatabase* HistoryURLProvider::VisitClassifier::db_ private
Referenced by VisitClassifier().
provider_
HistoryURLProvider* HistoryURLProvider::VisitClassifier::provider_ private
Referenced by VisitClassifier().
type_
Type HistoryURLProvider::VisitClassifier::type_ private
Referenced by type(), and VisitClassifier().
url_row_
history::URLRow HistoryURLProvider::VisitClassifier::url_row_ private
Referenced by url_row(), and VisitClassifier().
The documentation for this class was generated from the following file:
components/omnibox/browser/history_url_provider.cc