Chromium Omnibox: ClipboardProvider Class Reference
ClipboardProvider Class Reference
#include <clipboard_provider.h>
Public Types
using ClipboardImageMatchCallback = base::OnceCallback< void(absl::optional< AutocompleteMatch >)>
using ClipboardMatchCallback = base::OnceCallback< void()>
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Public Member Functions
ClipboardProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener, HistoryURLProvider *history_url_provider, ClipboardRecentContent *clipboard_content)
ClipboardProvider (const ClipboardProvider &)=delete
ClipboardProvider & operator= (const ClipboardProvider &)=delete
AutocompleteMatch NewClipboardURLMatch (GURL url)
absl::optional< AutocompleteMatch > NewClipboardTextMatch (std::u16string text)
void NewClipboardImageMatch (absl::optional< gfx::Image > optional_image, ClipboardImageMatchCallback callback)
void UpdateClipboardMatchWithContent (AutocompleteMatch *match, ClipboardMatchCallback callback)
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
void ResetSession () override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest, MatchesImage)
FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest, CreateURLMatchWithContent)
FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest, CreateTextMatchWithContent)
FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest, CreateImageMatchWithContent)
~ClipboardProvider () override
void AddCreatedMatchWithTracking (const AutocompleteInput &input, const AutocompleteMatch &match, const base::TimeDelta clipboard_contents_age)
void CheckClipboardContent (const AutocompleteInput &input)
void OnReceiveClipboardContent (const AutocompleteInput &input, base::TimeDelta clipboard_contents_age, std::set< ClipboardContentType > matched_types)
bool TemplateURLSupportsTextSearch ()
bool TemplateURLSupportsImageSearch ()
AutocompleteMatch NewBlankURLMatch ()
AutocompleteMatch NewBlankTextMatch ()
AutocompleteMatch NewBlankImageMatch ()
absl::optional< AutocompleteMatch > CreateURLMatch (const AutocompleteInput &input, bool *read_clipboard_content)
absl::optional< AutocompleteMatch > CreateTextMatch (const AutocompleteInput &input, bool *read_clipboard_content)
bool CreateImageMatch (const AutocompleteInput &input)
void CreateImageMatchCallback (const AutocompleteInput &input, const base::TimeDelta clipboard_contents_age, absl::optional< gfx::Image >)
void AddImageMatchCallback (const AutocompleteInput &input, const base::TimeDelta clipboard_contents_age, absl::optional< AutocompleteMatch > match)
void ConstructImageMatchCallback (ClipboardImageMatchCallback callback, scoped_refptr< base::RefCountedMemory > image_bytes)
void OnReceiveURLForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch *match, absl::optional< GURL > optional_gurl)
void OnReceiveTextForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch *match, absl::optional< std::u16string > optional_text)
void OnReceiveImageForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch *match, absl::optional< gfx::Image > optional_image)
void OnReceiveImageMatchForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch *match, absl::optional< AutocompleteMatch > optional_match)
void UpdateClipboardURLContent (const GURL &url, AutocompleteMatch *match)
bool UpdateClipboardTextContent (const std::u16string &text, AutocompleteMatch *match)
Static Private Member Functions
static scoped_refptr< base::RefCountedMemory > EncodeClipboardImage (gfx::ImageSkia image)
Private Attributes
AutocompleteProviderClient * client_
AutocompleteProviderListener * listener_
ClipboardRecentContent * clipboard_content_
HistoryURLProvider * history_url_provider_
GURL current_url_suggested_
size_t current_url_suggested_times_
bool field_trial_triggered_
bool field_trial_triggered_in_session_
base::WeakPtrFactory< ClipboardProvider > callback_weak_ptr_factory_ {this}
Additional Inherited Members
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Member Typedef Documentation
ClipboardImageMatchCallback
using ClipboardProvider::ClipboardImageMatchCallback = base::OnceCallback<void(absl::optional<AutocompleteMatch>)>
ClipboardMatchCallback
using ClipboardProvider::ClipboardMatchCallback = base::OnceCallback<void()>
Constructor & Destructor Documentation
ClipboardProvider() [1/2]
ClipboardProvider::ClipboardProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener, HistoryURLProvider * history_url_provider, ClipboardRecentContent * clipboard_content)
References clipboard_content_.
ClipboardProvider() [2/2]
ClipboardProvider::ClipboardProvider (const ClipboardProvider &) delete
~ClipboardProvider()
ClipboardProvider::~ClipboardProvider () override private
Member Function Documentation
AddCreatedMatchWithTracking()
void ClipboardProvider::AddCreatedMatchWithTracking (const AutocompleteInput & input, const AutocompleteMatch & match, const base::TimeDelta clipboard_contents_age) private
References client_, AutocompleteInput::current_title(), AutocompleteInput::current_url(), current_url_suggested_, current_url_suggested_times_, AutocompleteMatch::destination_url, omnibox::kDisplayTitleForCurrentUrl, AutocompleteProvider::matches_, AutocompleteInput::text(), AutocompleteMatch::type, and VerbatimMatchForURL().
Referenced by AddImageMatchCallback(), OnReceiveClipboardContent(), and Start().
AddImageMatchCallback()
void ClipboardProvider::AddImageMatchCallback (const AutocompleteInput & input, const base::TimeDelta clipboard_contents_age, absl::optional< AutocompleteMatch > match) private
References AddCreatedMatchWithTracking(), AutocompleteProvider::done_, listener_, and AutocompleteProviderListener::OnProviderUpdate().
Referenced by CreateImageMatchCallback().
AddProviderInfo()
void ClipboardProvider::AddProviderInfo (ProvidersInfo * provider_info) const override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::AsOmniboxEventProviderType(), current_url_suggested_times_, AutocompleteProvider::done_, field_trial_triggered_, field_trial_triggered_in_session_, and OmniboxFieldTrial::GetActiveSuggestFieldTrialHashes().
CheckClipboardContent()
void ClipboardProvider::CheckClipboardContent (const AutocompleteInput & input) private
References callback_weak_ptr_factory_, clipboard_content_, OnReceiveClipboardContent(), TemplateURLSupportsImageSearch(), and TemplateURLSupportsTextSearch().
Referenced by Start().
ConstructImageMatchCallback()
void ClipboardProvider::ConstructImageMatchCallback (ClipboardImageMatchCallback callback, scoped_refptr< base::RefCountedMemory > image_bytes) private
References client_, AutocompleteMatch::destination_url, AutocompleteProviderClient::GetTemplateURLService(), omnibox::kImageSearchSuggestionThumbnail, NewBlankImageMatch(), AutocompleteMatch::post_content, and AutocompleteMatch::search_terms_args.
Referenced by NewClipboardImageMatch().
CreateImageMatch()
bool ClipboardProvider::CreateImageMatch (const AutocompleteInput & input) private
References callback_weak_ptr_factory_, clipboard_content_, CreateImageMatchCallback(), AutocompleteProvider::done_, omnibox::kClipboardSuggestionContentHidden, and TemplateURLSupportsImageSearch().
Referenced by Start().
CreateImageMatchCallback()
void ClipboardProvider::CreateImageMatchCallback (const AutocompleteInput & input, const base::TimeDelta clipboard_contents_age, absl::optional< gfx::Image > optional_image) private
References AddImageMatchCallback(), callback_weak_ptr_factory_, and NewClipboardImageMatch().
Referenced by CreateImageMatch().
CreateTextMatch()
absl::optional< AutocompleteMatch > ClipboardProvider::CreateTextMatch (const AutocompleteInput & input, bool * read_clipboard_content) private
References clipboard_content_, omnibox::kClipboardSuggestionContentHidden, and NewClipboardTextMatch().
Referenced by Start().
CreateURLMatch()
absl::optional< AutocompleteMatch > ClipboardProvider::CreateURLMatch (const AutocompleteInput & input, bool * read_clipboard_content) private
References clipboard_content_, AutocompleteInput::current_url(), omnibox::kClipboardSuggestionContentHidden, and NewClipboardURLMatch().
Referenced by Start().
DeleteMatch()
void ClipboardProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
References clipboard_content_, AutocompleteMatch::contents, AutocompleteProvider::matches_, and AutocompleteMatch::type.
EncodeClipboardImage()
scoped_refptr< base::RefCountedMemory > ClipboardProvider::EncodeClipboardImage (gfx::ImageSkia image) static private
Referenced by NewClipboardImageMatch().
FRIEND_TEST_ALL_PREFIXES() [1/4]
ClipboardProvider::FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest , CreateImageMatchWithContent) private
FRIEND_TEST_ALL_PREFIXES() [2/4]
ClipboardProvider::FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest , CreateTextMatchWithContent) private
FRIEND_TEST_ALL_PREFIXES() [3/4]
ClipboardProvider::FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest , CreateURLMatchWithContent) private
FRIEND_TEST_ALL_PREFIXES() [4/4]
ClipboardProvider::FRIEND_TEST_ALL_PREFIXES (ClipboardProviderTest , MatchesImage) private
NewBlankImageMatch()
AutocompleteMatch ClipboardProvider::NewBlankImageMatch () private
References AutocompleteMatchType::CLIPBOARD_IMAGE, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::fill_into_edit, AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatch::transition.
Referenced by ConstructImageMatchCallback(), and OnReceiveClipboardContent().
NewBlankTextMatch()
AutocompleteMatch ClipboardProvider::NewBlankTextMatch () private
References AutocompleteMatchType::CLIPBOARD_TEXT, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatch::transition.
Referenced by NewClipboardTextMatch(), and OnReceiveClipboardContent().
NewBlankURLMatch()
AutocompleteMatch ClipboardProvider::NewBlankURLMatch () private
References AutocompleteMatchType::CLIPBOARD_URL, AutocompleteMatch::description, AutocompleteMatch::description_class, and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by NewClipboardURLMatch(), and OnReceiveClipboardContent().
NewClipboardImageMatch()
void ClipboardProvider::NewClipboardImageMatch (absl::optional< gfx::Image > optional_image, ClipboardImageMatchCallback callback)
References callback_weak_ptr_factory_, ConstructImageMatchCallback(), and EncodeClipboardImage().
Referenced by CreateImageMatchCallback(), and OnReceiveImageForMatchWithContent().
NewClipboardTextMatch()
absl::optional< AutocompleteMatch > ClipboardProvider::NewClipboardTextMatch (std::u16string text)
References NewBlankTextMatch(), and UpdateClipboardTextContent().
Referenced by CreateTextMatch().
NewClipboardURLMatch()
AutocompleteMatch ClipboardProvider::NewClipboardURLMatch (GURL url)
References NewBlankURLMatch(), and UpdateClipboardURLContent().
Referenced by CreateURLMatch().
OnReceiveClipboardContent()
void ClipboardProvider::OnReceiveClipboardContent (const AutocompleteInput & input, base::TimeDelta clipboard_contents_age, std::set< ClipboardContentType > matched_types) private
References AddCreatedMatchWithTracking(), AutocompleteProvider::done_, field_trial_triggered_, field_trial_triggered_in_session_, listener_, NewBlankImageMatch(), NewBlankTextMatch(), NewBlankURLMatch(), and AutocompleteProviderListener::OnProviderUpdate().
Referenced by CheckClipboardContent().
OnReceiveImageForMatchWithContent()
void ClipboardProvider::OnReceiveImageForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch * match, absl::optional< gfx::Image > optional_image) private
References callback_weak_ptr_factory_, NewClipboardImageMatch(), and OnReceiveImageMatchForMatchWithContent().
Referenced by UpdateClipboardMatchWithContent().
OnReceiveImageMatchForMatchWithContent()
void ClipboardProvider::OnReceiveImageMatchForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch * match, absl::optional< AutocompleteMatch > optional_match) private
References AutocompleteMatch::destination_url, AutocompleteMatch::post_content, and AutocompleteMatch::search_terms_args.
Referenced by OnReceiveImageForMatchWithContent().
OnReceiveTextForMatchWithContent()
void ClipboardProvider::OnReceiveTextForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch * match, absl::optional< std::u16string > optional_text) private
References UpdateClipboardTextContent().
Referenced by UpdateClipboardMatchWithContent().
OnReceiveURLForMatchWithContent()
void ClipboardProvider::OnReceiveURLForMatchWithContent (ClipboardMatchCallback callback, AutocompleteMatch * match, absl::optional< GURL > optional_gurl) private
References UpdateClipboardURLContent().
Referenced by UpdateClipboardMatchWithContent().
operator=()
ClipboardProvider& ClipboardProvider::operator= (const ClipboardProvider &) delete
ResetSession()
void ClipboardProvider::ResetSession () override virtual
Reimplemented from AutocompleteProvider.
References field_trial_triggered_, and field_trial_triggered_in_session_.
Start()
void ClipboardProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References AddCreatedMatchWithTracking(), CheckClipboardContent(), clipboard_content_, CreateImageMatch(), CreateTextMatch(), CreateURLMatch(), omnibox::DEFAULT, AutocompleteProvider::done_, field_trial_triggered_, AutocompleteInput::focus_type(), and AutocompleteProvider::matches_.
Stop()
void ClipboardProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References callback_weak_ptr_factory_, and AutocompleteProvider::Stop().
TemplateURLSupportsImageSearch()
bool ClipboardProvider::TemplateURLSupportsImageSearch () private
References client_, and AutocompleteProviderClient::GetTemplateURLService().
Referenced by CheckClipboardContent(), and CreateImageMatch().
TemplateURLSupportsTextSearch()
bool ClipboardProvider::TemplateURLSupportsTextSearch () private
References client_, and AutocompleteProviderClient::GetTemplateURLService().
Referenced by CheckClipboardContent().
UpdateClipboardMatchWithContent()
void ClipboardProvider::UpdateClipboardMatchWithContent (AutocompleteMatch * match, ClipboardMatchCallback callback)
References callback_weak_ptr_factory_, clipboard_content_, AutocompleteMatchType::CLIPBOARD_IMAGE, AutocompleteMatchType::CLIPBOARD_TEXT, AutocompleteMatchType::CLIPBOARD_URL, OnReceiveImageForMatchWithContent(), OnReceiveTextForMatchWithContent(), OnReceiveURLForMatchWithContent(), and AutocompleteMatch::type.
UpdateClipboardTextContent()
bool ClipboardProvider::UpdateClipboardTextContent (const std::u16string & text, AutocompleteMatch * match) private
References client_, AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteProviderClient::GetTemplateURLService(), AutocompleteMatch::keyword, AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatch::SanitizeString().
Referenced by NewClipboardTextMatch(), and OnReceiveTextForMatchWithContent().
UpdateClipboardURLContent()
void ClipboardProvider::UpdateClipboardURLContent (const GURL & url, AutocompleteMatch * match) private
References client_, AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::GetFormatTypes(), AutocompleteProviderClient::GetSchemeClassifier(), and AutocompleteMatch::ACMatchClassification::URL.
Referenced by NewClipboardURLMatch(), and OnReceiveURLForMatchWithContent().
Member Data Documentation
callback_weak_ptr_factory_
base::WeakPtrFactory<ClipboardProvider> ClipboardProvider::callback_weak_ptr_factory_ {this} private
Referenced by CheckClipboardContent(), CreateImageMatch(), CreateImageMatchCallback(), NewClipboardImageMatch(), OnReceiveImageForMatchWithContent(), Stop(), and UpdateClipboardMatchWithContent().
client_
AutocompleteProviderClient* ClipboardProvider::client_ private
Referenced by AddCreatedMatchWithTracking(), ConstructImageMatchCallback(), TemplateURLSupportsImageSearch(), TemplateURLSupportsTextSearch(), UpdateClipboardTextContent(), and UpdateClipboardURLContent().
clipboard_content_
ClipboardRecentContent* ClipboardProvider::clipboard_content_ private
Referenced by CheckClipboardContent(), ClipboardProvider(), CreateImageMatch(), CreateTextMatch(), CreateURLMatch(), DeleteMatch(), Start(), and UpdateClipboardMatchWithContent().
current_url_suggested_
GURL ClipboardProvider::current_url_suggested_ private
Referenced by AddCreatedMatchWithTracking().
current_url_suggested_times_
size_t ClipboardProvider::current_url_suggested_times_ private
Referenced by AddCreatedMatchWithTracking(), and AddProviderInfo().
field_trial_triggered_
bool ClipboardProvider::field_trial_triggered_ private
Referenced by AddProviderInfo(), OnReceiveClipboardContent(), ResetSession(), and Start().
field_trial_triggered_in_session_
bool ClipboardProvider::field_trial_triggered_in_session_ private
Referenced by AddProviderInfo(), OnReceiveClipboardContent(), and ResetSession().
history_url_provider_
HistoryURLProvider* ClipboardProvider::history_url_provider_ private
listener_
AutocompleteProviderListener* ClipboardProvider::listener_ private
Referenced by AddImageMatchCallback(), and OnReceiveClipboardContent().
The documentation for this class was generated from the following files:
components/omnibox/browser/clipboard_provider.h
components/omnibox/browser/clipboard_provider.cc