Chromium Omnibox: OnDeviceHeadProvider Class Reference
OnDeviceHeadProvider Class Reference
#include <on_device_head_provider.h>
Classes
struct OnDeviceHeadProviderParams
Public Member Functions
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
AutocompleteProviderClient * client ()
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual void DeleteMatch (const AutocompleteMatch &match)
virtual void ResetSession ()
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static OnDeviceHeadProvider * Create (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Member Functions
OnDeviceHeadProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener)
~OnDeviceHeadProvider () override
OnDeviceHeadProvider (const OnDeviceHeadProvider &)=delete
OnDeviceHeadProvider & operator= (const OnDeviceHeadProvider &)=delete
bool IsOnDeviceHeadProviderAllowed (const AutocompleteInput &input)
void DoSearch (std::unique_ptr< OnDeviceHeadProviderParams > params)
void SearchDone (std::unique_ptr< OnDeviceHeadProviderParams > params)
std::string GetOnDeviceHeadModelFilename () const
SEQUENCE_CHECKER (main_sequence_checker_)
Static Private Member Functions
static std::unique_ptr< OnDeviceHeadProviderParams > GetSuggestionsFromModel (const std::string &model_filename, const size_t provider_max_matches, std::unique_ptr< OnDeviceHeadProviderParams > params)
Private Attributes
AutocompleteProviderClient * client_
AutocompleteProviderListener * listener_
scoped_refptr< base::SequencedTaskRunner > worker_task_runner_
size_t on_device_search_request_id_
base::WeakPtrFactory< OnDeviceHeadProvider > weak_ptr_factory_ {this}
Friends
class OnDeviceHeadProviderTest
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Constructor & Destructor Documentation
OnDeviceHeadProvider() [1/2]
OnDeviceHeadProvider::OnDeviceHeadProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) private
Referenced by Create().
~OnDeviceHeadProvider()
OnDeviceHeadProvider::~OnDeviceHeadProvider () override private
OnDeviceHeadProvider() [2/2]
OnDeviceHeadProvider::OnDeviceHeadProvider (const OnDeviceHeadProvider &) private delete
Member Function Documentation
AddProviderInfo()
void OnDeviceHeadProvider::AddProviderInfo (ProvidersInfo * provider_info) const override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::done_.
client()
AutocompleteProviderClient* OnDeviceHeadProvider::client () inline
References client_.
Referenced by Create(), IsOnDeviceHeadProviderAllowed(), SearchDone(), and Start().
Create()
OnDeviceHeadProvider * OnDeviceHeadProvider::Create (AutocompleteProviderClient * client, AutocompleteProviderListener * listener) static
References client(), and OnDeviceHeadProvider().
Referenced by AutocompleteController::AutocompleteController().
DoSearch()
void OnDeviceHeadProvider::DoSearch (std::unique_ptr< OnDeviceHeadProviderParams > params) private
References GetOnDeviceHeadModelFilename(), GetSuggestionsFromModel(), on_device_search_request_id_, AutocompleteProvider::provider_max_matches_, SearchDone(), weak_ptr_factory_, and worker_task_runner_.
Referenced by Start().
GetOnDeviceHeadModelFilename()
std::string OnDeviceHeadProvider::GetOnDeviceHeadModelFilename () const private
References OnDeviceModelUpdateListener::GetInstance().
Referenced by DoSearch(), and Start().
GetSuggestionsFromModel()
std::unique_ptr< OnDeviceHeadProvider::OnDeviceHeadProviderParams > OnDeviceHeadProvider::GetSuggestionsFromModel (const std::string & model_filename, const size_t provider_max_matches, std::unique_ptr< OnDeviceHeadProviderParams > params) static private
References OnDeviceHeadModel::GetSuggestionsForPrefix(), and AutocompleteProvider::provider_max_matches().
Referenced by DoSearch().
IsOnDeviceHeadProviderAllowed()
bool OnDeviceHeadProvider::IsOnDeviceHeadProviderAllowed (const AutocompleteInput & input) private
References client(), omnibox::DEFAULT, AutocompleteInput::focus_type(), OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForIncognito(), OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForNonIncognito(), AutocompleteInput::type(), and AutocompleteInput::want_asynchronous_matches().
Referenced by Start().
operator=()
OnDeviceHeadProvider& OnDeviceHeadProvider::operator= (const OnDeviceHeadProvider &) private delete
SearchDone()
void OnDeviceHeadProvider::SearchDone (std::unique_ptr< OnDeviceHeadProviderParams > params) private
References client(), BaseSearchProvider::CreateOnDeviceSearchSuggestion(), AutocompleteProvider::done_, AutocompleteProviderClient::GetTemplateURLService(), listener_, AutocompleteProvider::matches_, on_device_search_request_id_, OmniboxFieldTrial::OnDeviceHeadSuggestMaxScoreForNonUrlInput(), and AutocompleteProviderListener::OnProviderUpdate().
Referenced by DoSearch().
SEQUENCE_CHECKER()
OnDeviceHeadProvider::SEQUENCE_CHECKER (main_sequence_checker_) private
Start()
void OnDeviceHeadProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References client(), AutocompleteProvider::done_, DoSearch(), GetOnDeviceHeadModelFilename(), IsOnDeviceHeadProviderAllowed(), AutocompleteProvider::matches_, on_device_search_request_id_, OmniboxFieldTrial::OnDeviceHeadSuggestDelaySuggestRequestMs(), Stop(), AutocompleteInput::text(), and weak_ptr_factory_.
Stop()
void OnDeviceHeadProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::done_, AutocompleteProvider::matches_, on_device_search_request_id_, and weak_ptr_factory_.
Referenced by Start().
Friends And Related Function Documentation
OnDeviceHeadProviderTest
friend class OnDeviceHeadProviderTest friend
Member Data Documentation
client_
AutocompleteProviderClient* OnDeviceHeadProvider::client_ private
Referenced by client().
listener_
AutocompleteProviderListener* OnDeviceHeadProvider::listener_ private
Referenced by SearchDone().
on_device_search_request_id_
size_t OnDeviceHeadProvider::on_device_search_request_id_ private
Referenced by DoSearch(), SearchDone(), Start(), and Stop().
weak_ptr_factory_
base::WeakPtrFactory<OnDeviceHeadProvider> OnDeviceHeadProvider::weak_ptr_factory_ {this} private
Referenced by DoSearch(), Start(), and Stop().
worker_task_runner_
scoped_refptr<base::SequencedTaskRunner> OnDeviceHeadProvider::worker_task_runner_ private
Referenced by DoSearch().
The documentation for this class was generated from the following files:
components/omnibox/browser/on_device_head_provider.h
components/omnibox/browser/on_device_head_provider.cc