Chromium Omnibox: ChromeOmniboxNavigationObserver Class Reference
ChromeOmniboxNavigationObserver Class Reference
#include <chrome_omnibox_navigation_observer.h>
Public Types
enum LoadState { LOAD_NOT_SEEN , LOAD_PENDING , LOAD_COMMITTED }
Public Member Functions
ChromeOmniboxNavigationObserver (Profile *profile, const std::u16string &text, const AutocompleteMatch &match, const AutocompleteMatch &alternate_nav_match)
~ChromeOmniboxNavigationObserver () override
LoadState load_state () const
void OnSuccessfulNavigation ()
void On404 ()
void SetURLLoaderFactoryForTesting (scoped_refptr< network::SharedURLLoaderFactory > testing_loader_factory)
Public Member Functions inherited from OmniboxNavigationObserver
virtual ~OmniboxNavigationObserver ()
Protected Member Functions
virtual void CreateAlternateNavInfoBar ()
Private Types
enum FetchState { FETCH_NOT_COMPLETE , FETCH_SUCCEEDED , FETCH_FAILED }
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ChromeOmniboxNavigationObserverTest, DeleteBrokenCustomSearchEngines)
FRIEND_TEST_ALL_PREFIXES (ChromeOmniboxNavigationObserverTest, AlternateNavInfoBar)
bool HasSeenPendingLoad () const override
void Observe (int type, const content::NotificationSource &source, const content::NotificationDetails &details) override
void DidFinishNavigation (content::NavigationHandle *navigation_handle) override
void NavigationEntryCommitted (const content::LoadCommittedDetails &load_details) override
void WebContentsDestroyed () override
void OnURLLoadComplete (std::unique_ptr< std::string > body)
void OnURLRedirect (const net::RedirectInfo &redirect_info, const network::mojom::URLResponseHead &response_head, std::vector< std::string > *to_be_removed_headers)
void OnDoneWithURL (bool success)
void OnAllLoadingFinished ()
void CreateLoader (const GURL &destination_url)
DISALLOW_COPY_AND_ASSIGN (ChromeOmniboxNavigationObserver)
Private Attributes
const std::u16string text_
const AutocompleteMatch match_
const AutocompleteMatch alternate_nav_match_
TemplateURLService * template_url_service_
scoped_refptr< ShortcutsBackend > shortcuts_backend_
std::unique_ptr< network::SimpleURLLoader > loader_
scoped_refptr< network::SharedURLLoaderFactory > loader_factory_for_testing_
LoadState load_state_
FetchState fetch_state_
content::NotificationRegistrar registrar_
Member Enumeration Documentation
FetchState
enum ChromeOmniboxNavigationObserver::FetchState private
Enumerator
FETCH_NOT_COMPLETE
FETCH_SUCCEEDED
FETCH_FAILED
LoadState
enum ChromeOmniboxNavigationObserver::LoadState
Enumerator
LOAD_NOT_SEEN
LOAD_PENDING
LOAD_COMMITTED
Constructor & Destructor Documentation
ChromeOmniboxNavigationObserver()
ChromeOmniboxNavigationObserver::ChromeOmniboxNavigationObserver (Profile * profile, const std::u16string & text, const AutocompleteMatch & match, const AutocompleteMatch & alternate_nav_match)
References alternate_nav_match_, CreateLoader(), AutocompleteMatch::destination_url, and registrar_.
Referenced by ChromeOmniboxClient::CreateOmniboxNavigationObserver().
~ChromeOmniboxNavigationObserver()
ChromeOmniboxNavigationObserver::~ChromeOmniboxNavigationObserver () override
Member Function Documentation
CreateAlternateNavInfoBar()
void ChromeOmniboxNavigationObserver::CreateAlternateNavInfoBar () protected virtual
References alternate_nav_match_, AlternateNavInfoBarDelegate::CreateForOmniboxNavigation(), AutocompleteMatch::destination_url, match_, and text_.
Referenced by OnAllLoadingFinished().
CreateLoader()
void ChromeOmniboxNavigationObserver::CreateLoader (const GURL & destination_url) private
References loader_, and OnURLRedirect().
Referenced by ChromeOmniboxNavigationObserver().
DidFinishNavigation()
void ChromeOmniboxNavigationObserver::DidFinishNavigation (content::NavigationHandle * navigation_handle) override private
References LOAD_COMMITTED, and load_state_.
DISALLOW_COPY_AND_ASSIGN()
ChromeOmniboxNavigationObserver::DISALLOW_COPY_AND_ASSIGN (ChromeOmniboxNavigationObserver) private
FRIEND_TEST_ALL_PREFIXES() [1/2]
ChromeOmniboxNavigationObserver::FRIEND_TEST_ALL_PREFIXES (ChromeOmniboxNavigationObserverTest , AlternateNavInfoBar) private
FRIEND_TEST_ALL_PREFIXES() [2/2]
ChromeOmniboxNavigationObserver::FRIEND_TEST_ALL_PREFIXES (ChromeOmniboxNavigationObserverTest , DeleteBrokenCustomSearchEngines) private
HasSeenPendingLoad()
bool ChromeOmniboxNavigationObserver::HasSeenPendingLoad () const override private virtual
Implements OmniboxNavigationObserver.
References LOAD_NOT_SEEN, and load_state_.
load_state()
LoadState ChromeOmniboxNavigationObserver::load_state () const inline
References load_state_.
NavigationEntryCommitted()
void ChromeOmniboxNavigationObserver::NavigationEntryCommitted (const content::LoadCommittedDetails & load_details) override private
References AutocompleteMatch::destination_url, FETCH_NOT_COMPLETE, fetch_state_, LOAD_COMMITTED, load_state_, loader_, match_, On404(), OnAllLoadingFinished(), and OnSuccessfulNavigation().
Observe()
void ChromeOmniboxNavigationObserver::Observe (int type, const content::NotificationSource & source, const content::NotificationDetails & details) override private
References AutocompleteMatch::destination_url, LOAD_NOT_SEEN, LOAD_PENDING, load_state_, loader_, loader_factory_for_testing_, match_, OnURLLoadComplete(), and registrar_.
On404()
void ChromeOmniboxNavigationObserver::On404 ()
References AutocompleteMatch::GetTemplateURL(), match_, and template_url_service_.
Referenced by NavigationEntryCommitted().
OnAllLoadingFinished()
void ChromeOmniboxNavigationObserver::OnAllLoadingFinished () private
References CreateAlternateNavInfoBar(), fetch_state_, and FETCH_SUCCEEDED.
Referenced by NavigationEntryCommitted(), and OnDoneWithURL().
OnDoneWithURL()
void ChromeOmniboxNavigationObserver::OnDoneWithURL (bool success) private
References FETCH_FAILED, fetch_state_, FETCH_SUCCEEDED, LOAD_COMMITTED, load_state_, loader_, and OnAllLoadingFinished().
Referenced by OnURLLoadComplete(), and OnURLRedirect().
OnSuccessfulNavigation()
void ChromeOmniboxNavigationObserver::OnSuccessfulNavigation ()
References match_, shortcuts_backend_, and text_.
Referenced by NavigationEntryCommitted().
OnURLLoadComplete()
void ChromeOmniboxNavigationObserver::OnURLLoadComplete (std::unique_ptr< std::string > body) private
References loader_, and OnDoneWithURL().
Referenced by Observe().
OnURLRedirect()
void ChromeOmniboxNavigationObserver::OnURLRedirect (const net::RedirectInfo & redirect_info, const network::mojom::URLResponseHead & response_head, std::vector< std::string > * to_be_removed_headers) private
References alternate_nav_match_, AutocompleteMatch::destination_url, and OnDoneWithURL().
Referenced by CreateLoader().
SetURLLoaderFactoryForTesting()
void ChromeOmniboxNavigationObserver::SetURLLoaderFactoryForTesting (scoped_refptr< network::SharedURLLoaderFactory > testing_loader_factory)
References loader_factory_for_testing_.
WebContentsDestroyed()
void ChromeOmniboxNavigationObserver::WebContentsDestroyed () override private
Member Data Documentation
alternate_nav_match_
const AutocompleteMatch ChromeOmniboxNavigationObserver::alternate_nav_match_ private
Referenced by ChromeOmniboxNavigationObserver(), CreateAlternateNavInfoBar(), and OnURLRedirect().
fetch_state_
FetchState ChromeOmniboxNavigationObserver::fetch_state_ private
Referenced by NavigationEntryCommitted(), OnAllLoadingFinished(), and OnDoneWithURL().
load_state_
LoadState ChromeOmniboxNavigationObserver::load_state_ private
Referenced by DidFinishNavigation(), HasSeenPendingLoad(), load_state(), NavigationEntryCommitted(), Observe(), and OnDoneWithURL().
loader_
std::unique_ptr<network::SimpleURLLoader> ChromeOmniboxNavigationObserver::loader_ private
Referenced by CreateLoader(), NavigationEntryCommitted(), Observe(), OnDoneWithURL(), and OnURLLoadComplete().
loader_factory_for_testing_
scoped_refptr<network::SharedURLLoaderFactory> ChromeOmniboxNavigationObserver::loader_factory_for_testing_ private
Referenced by Observe(), and SetURLLoaderFactoryForTesting().
match_
const AutocompleteMatch ChromeOmniboxNavigationObserver::match_ private
Referenced by CreateAlternateNavInfoBar(), NavigationEntryCommitted(), Observe(), On404(), and OnSuccessfulNavigation().
registrar_
content::NotificationRegistrar ChromeOmniboxNavigationObserver::registrar_ private
Referenced by ChromeOmniboxNavigationObserver(), and Observe().
shortcuts_backend_
scoped_refptr<ShortcutsBackend> ChromeOmniboxNavigationObserver::shortcuts_backend_ private
Referenced by OnSuccessfulNavigation().
template_url_service_
TemplateURLService* ChromeOmniboxNavigationObserver::template_url_service_ private
Referenced by On404().
text_
const std::u16string ChromeOmniboxNavigationObserver::text_ private
Referenced by CreateAlternateNavInfoBar(), and OnSuccessfulNavigation().
The documentation for this class was generated from the following files:
chrome/browser/ui/omnibox/chrome_omnibox_navigation_observer.h
chrome/browser/ui/omnibox/chrome_omnibox_navigation_observer.cc