Chromium Omnibox: SearchSuggestionParser::SuggestResult Class Reference
SearchSuggestionParser::SuggestResult Class Reference
#include <search_suggestion_parser.h>
Public Member Functions
SuggestResult (const std::u16string &suggestion, AutocompleteMatchType::Type type, std::vector< int > subtypes, bool from_keyword, int relevance, bool relevance_from_server, const std::u16string &input_text)
SuggestResult (const std::u16string &suggestion, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::u16string &match_contents, const std::u16string &match_contents_prefix, const std::u16string &annotation, const std::string &additional_query_params, const std::string &deletion_url, const std::string &image_dominant_color, const std::string &image_url, bool from_keyword, int relevance, bool relevance_from_server, bool should_prefetch, const std::u16string &input_text)
SuggestResult (const SuggestResult &result)
~SuggestResult () override
SuggestResult & operator= (const SuggestResult &rhs)
const std::u16string & suggestion () const
const std::u16string & match_contents_prefix () const
const std::u16string & annotation () const
const std::string & additional_query_params () const
void set_suggestion_group_id (int suggestion_group_id)
absl::optional< int > suggestion_group_id () const
void SetAnswer (const SuggestionAnswer &answer)
const absl::optional< SuggestionAnswer > & answer () const
const std::string & image_dominant_color () const
const GURL & image_url () const
bool should_prefetch () const
void ClassifyMatchContents (const bool allow_bolding_all, const std::u16string &input_text)
int CalculateRelevance (const AutocompleteInput &input, bool keyword_provider_requested) const override
Public Member Functions inherited from SearchSuggestionParser::Result
Result (bool from_keyword, int relevance, bool relevance_from_server, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::string &deletion_url)
Result (const Result &other)
virtual ~Result ()
bool from_keyword () const
const std::u16string & match_contents () const
const ACMatchClassifications & match_contents_class () const
AutocompleteMatchType::Type type () const
const std::vector< int > & subtypes () const
int relevance () const
void set_relevance (int relevance)
bool received_after_last_keystroke () const
void set_received_after_last_keystroke (bool received_after_last_keystroke)
bool relevance_from_server () const
void set_relevance_from_server (bool relevance_from_server)
const std::string & deletion_url () const
Private Attributes
std::u16string suggestion_
std::u16string match_contents_prefix_
std::u16string annotation_
std::string additional_query_params_
absl::optional< int > suggestion_group_id_
absl::optional< SuggestionAnswer > answer_
std::string image_dominant_color_
GURL image_url_
bool should_prefetch_
Additional Inherited Members
Protected Attributes inherited from SearchSuggestionParser::Result
std::u16string match_contents_
ACMatchClassifications match_contents_class_
bool from_keyword_
AutocompleteMatchType::Type type_
std::vector< int > subtypes_
int relevance_
Constructor & Destructor Documentation
SuggestResult() [1/3]
SearchSuggestionParser::SuggestResult::SuggestResult (const std::u16string & suggestion, AutocompleteMatchType::Type type, std::vector< int > subtypes, bool from_keyword, int relevance, bool relevance_from_server, const std::u16string & input_text)
SuggestResult() [2/3]
SearchSuggestionParser::SuggestResult::SuggestResult (const std::u16string & suggestion, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::u16string & match_contents, const std::u16string & match_contents_prefix, const std::u16string & annotation, const std::string & additional_query_params, const std::string & deletion_url, const std::string & image_dominant_color, const std::string & image_url, bool from_keyword, int relevance, bool relevance_from_server, bool should_prefetch, const std::u16string & input_text)
References ClassifyMatchContents(), SearchSuggestionParser::Result::match_contents(), and SearchSuggestionParser::Result::match_contents_.
SuggestResult() [3/3]
SearchSuggestionParser::SuggestResult::SuggestResult (const SuggestResult & result) default
~SuggestResult()
SearchSuggestionParser::SuggestResult::~SuggestResult () override
Member Function Documentation
additional_query_params()
const std::string& SearchSuggestionParser::SuggestResult::additional_query_params () const inline
References additional_query_params_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
annotation()
const std::u16string& SearchSuggestionParser::SuggestResult::annotation () const inline
References annotation_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
answer()
const absl::optional<SuggestionAnswer>& SearchSuggestionParser::SuggestResult::answer () const inline
References answer_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
CalculateRelevance()
int SearchSuggestionParser::SuggestResult::CalculateRelevance (const AutocompleteInput & input, bool keyword_provider_requested) const override virtual
Implements SearchSuggestionParser::Result.
References AutocompleteInput::type().
Referenced by SearchProvider::ApplyCalculatedSuggestRelevance().
ClassifyMatchContents()
void SearchSuggestionParser::SuggestResult::ClassifyMatchContents (const bool allow_bolding_all, const std::u16string & input_text)
References AutocompleteProvider::ClassifyAllMatchesInString(), AutocompleteMatch::ACMatchClassification::NONE, and AutocompleteMatchType::SEARCH_SUGGEST_TAIL.
Referenced by SuggestResult().
image_dominant_color()
const std::string& SearchSuggestionParser::SuggestResult::image_dominant_color () const inline
References image_dominant_color_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
image_url()
const GURL& SearchSuggestionParser::SuggestResult::image_url () const inline
References image_url_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
match_contents_prefix()
const std::u16string& SearchSuggestionParser::SuggestResult::match_contents_prefix () const inline
References match_contents_prefix_.
Referenced by BaseSearchProvider::CreateSearchSuggestion().
operator=()
SearchSuggestionParser::SuggestResult & SearchSuggestionParser::SuggestResult::operator= (const SuggestResult & rhs) default
set_suggestion_group_id()
void SearchSuggestionParser::SuggestResult::set_suggestion_group_id (int suggestion_group_id) inline
References suggestion_group_id(), and suggestion_group_id_.
SetAnswer()
void SearchSuggestionParser::SuggestResult::SetAnswer (const SuggestionAnswer & answer)
Referenced by SearchProvider::ConvertResultsToAutocompleteMatches().
should_prefetch()
bool SearchSuggestionParser::SuggestResult::should_prefetch () const inline
References should_prefetch_.
Referenced by BaseSearchProvider::AddMatchToMap().
suggestion()
const std::u16string& SearchSuggestionParser::SuggestResult::suggestion () const inline
References suggestion_.
Referenced by BaseSearchProvider::AddMatchToMap(), BaseSearchProvider::CreateSearchSuggestion(), and BaseSearchProvider::GetFillIntoEdit().
suggestion_group_id()
absl::optional<int> SearchSuggestionParser::SuggestResult::suggestion_group_id () const inline
References suggestion_group_id_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), and set_suggestion_group_id().
Member Data Documentation
additional_query_params_
std::string SearchSuggestionParser::SuggestResult::additional_query_params_ private
Referenced by additional_query_params().
annotation_
std::u16string SearchSuggestionParser::SuggestResult::annotation_ private
Referenced by annotation().
answer_
absl::optional<SuggestionAnswer> SearchSuggestionParser::SuggestResult::answer_ private
Referenced by answer().
image_dominant_color_
std::string SearchSuggestionParser::SuggestResult::image_dominant_color_ private
Referenced by image_dominant_color().
image_url_
GURL SearchSuggestionParser::SuggestResult::image_url_ private
Referenced by image_url().
match_contents_prefix_
std::u16string SearchSuggestionParser::SuggestResult::match_contents_prefix_ private
Referenced by match_contents_prefix().
should_prefetch_
bool SearchSuggestionParser::SuggestResult::should_prefetch_ private
Referenced by should_prefetch().
suggestion_
std::u16string SearchSuggestionParser::SuggestResult::suggestion_ private
Referenced by suggestion().
suggestion_group_id_
absl::optional<int> SearchSuggestionParser::SuggestResult::suggestion_group_id_ private
Referenced by set_suggestion_group_id(), and suggestion_group_id().
The documentation for this class was generated from the following files:
components/omnibox/browser/search_suggestion_parser.h
components/omnibox/browser/search_suggestion_parser.cc