Chromium Omnibox: OmniboxPedal::TokenSequence Class Reference
OmniboxPedal::TokenSequence Class Reference
#include <omnibox_pedal.h>
Public Member Functions
TokenSequence (size_t reserve_size)
TokenSequence (std::vector< int > token_ids)
TokenSequence (const TokenSequence &)=delete
TokenSequence & operator= (const TokenSequence &)=delete
TokenSequence (TokenSequence &&)
TokenSequence & operator= (TokenSequence &&)
~TokenSequence ()
bool IsFullyConsumed ()
size_t CountUnconsumed () const
void Add (int id)
void Clear ()
void ResetLinks ()
bool Erase (const TokenSequence &erase_sequence, bool erase_only_once)
bool Consume (const TokenSequence &consume_sequence, bool consume_only_once)
size_t Size () const
size_t EstimateMemoryUsage () const
Private Member Functions
bool MatchesAt (const TokenSequence &sequence, size_t index, size_t index_mask) const
size_t WalkToUnconsumedIndexFrom (size_t from_index)
Private Attributes
std::vector< Token > tokens_
Constructor & Destructor Documentation
TokenSequence() [1/4]
OmniboxPedal::TokenSequence::TokenSequence (size_t reserve_size) explicit
References tokens_.
TokenSequence() [2/4]
OmniboxPedal::TokenSequence::TokenSequence (std::vector< int > token_ids) explicit
TokenSequence() [3/4]
OmniboxPedal::TokenSequence::TokenSequence (const TokenSequence &) delete
TokenSequence() [4/4]
OmniboxPedal::TokenSequence::TokenSequence (TokenSequence &&) default
~TokenSequence()
OmniboxPedal::TokenSequence::~TokenSequence () default
Member Function Documentation
Add()
void OmniboxPedal::TokenSequence::Add (int id)
References OmniboxPedal::id().
Referenced by OmniboxPedalProvider::LoadSynonymGroupValue(), OmniboxPedalProvider::Tokenize(), and OmniboxPedalProvider::TokenizeAndExpandDictionary().
Clear()
void OmniboxPedal::TokenSequence::Clear () inline
References tokens_.
Referenced by OmniboxPedalProvider::Tokenize(), and OmniboxPedalProvider::TokenizeAndExpandDictionary().
Consume()
bool OmniboxPedal::TokenSequence::Consume (const TokenSequence & consume_sequence, bool consume_only_once)
References Size().
Referenced by OmniboxPedal::SynonymGroup::EraseMatchesIn().
CountUnconsumed()
size_t OmniboxPedal::TokenSequence::CountUnconsumed () const
Erase()
bool OmniboxPedal::TokenSequence::Erase (const TokenSequence & erase_sequence, bool erase_only_once)
References Size().
Referenced by OmniboxPedal::SynonymGroup::EraseMatchesIn().
EstimateMemoryUsage()
size_t OmniboxPedal::TokenSequence::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage().
IsFullyConsumed()
bool OmniboxPedal::TokenSequence::IsFullyConsumed ()
Referenced by OmniboxPedal::IsConceptMatch().
MatchesAt()
bool OmniboxPedal::TokenSequence::MatchesAt (const TokenSequence & sequence, size_t index, size_t index_mask) const private
References tokens_.
operator=() [1/2]
TokenSequence& OmniboxPedal::TokenSequence::operator= (const TokenSequence &) delete
operator=() [2/2]
OmniboxPedal::TokenSequence & OmniboxPedal::TokenSequence::operator= (TokenSequence &&) default
ResetLinks()
void OmniboxPedal::TokenSequence::ResetLinks ()
Referenced by OmniboxPedalProvider::FindPedalMatch().
Size()
size_t OmniboxPedal::TokenSequence::Size () const inline
References tokens_.
Referenced by OmniboxPedal::SynonymGroup::AddSynonym(), Consume(), Erase(), OmniboxPedalProvider::FindPedalMatch(), OmniboxPedalProvider::Tokenize(), and OmniboxPedalProvider::TokenizeAndExpandDictionary().
WalkToUnconsumedIndexFrom()
size_t OmniboxPedal::TokenSequence::WalkToUnconsumedIndexFrom (size_t from_index) private
Member Data Documentation
tokens_
std::vector<Token> OmniboxPedal::TokenSequence::tokens_ private
Referenced by Clear(), MatchesAt(), Size(), and TokenSequence().
The documentation for this class was generated from the following files:
components/omnibox/browser/actions/omnibox_pedal.h
components/omnibox/browser/actions/omnibox_pedal.cc