Chromium Omnibox: bookmarks Namespace Reference
bookmarks Namespace Reference
Functions
AutocompleteMatch TitledUrlMatchToAutocompleteMatch (const TitledUrlMatch &titled_url_match, AutocompleteMatchType::Type type, int relevance, AutocompleteProvider *provider, const AutocompleteSchemeClassifier &scheme_classifier, const AutocompleteInput &input, const std::u16string &fixed_up_input_text)
Function Documentation
TitledUrlMatchToAutocompleteMatch()
AutocompleteMatch bookmarks::TitledUrlMatchToAutocompleteMatch (const TitledUrlMatch & titled_url_match, AutocompleteMatchType::Type type, int relevance, AutocompleteProvider * provider, const AutocompleteSchemeClassifier & scheme_classifier, const AutocompleteInput & input, const std::u16string & fixed_up_input_text)
References ClassifyTermMatches(), AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::destination_url, AutocompleteMatch::fill_into_edit, FindTermMatches(), AutocompleteInput::FormattedStringWithEquivalentMeaning(), AutocompleteMatch::GetFormatTypes(), URLPrefix::GetInlineAutocompleteOffset(), AutocompleteMatch::GetMatchComponents(), AutocompleteMatch::inline_autocompletion, OmniboxFieldTrial::kBookmarkPathsUiAppendAfterTitle, OmniboxFieldTrial::kBookmarkPathsUiDynamicReplaceUrl, OmniboxFieldTrial::kBookmarkPathsUiReplaceTitle, OmniboxFieldTrial::kBookmarkPathsUiReplaceUrl, AutocompleteMatch::ACMatchClassification::MATCH, AutocompleteMatch::ACMatchClassification::NONE, AutocompleteInput::parts(), AutocompleteMatch::RecordAdditionalInfo(), AutocompleteMatch::SetAllowedToBeDefault(), AutocompleteInput::text(), AutocompleteMatch::TryRichAutocompletion(), and AutocompleteMatch::ACMatchClassification::URL.
Referenced by BookmarkProvider::DoAutocomplete().