Chromium Omnibox: ScoredHistoryMatch Struct Reference
ScoredHistoryMatch Struct Reference
#include <scored_history_match.h>
Public Types
using ScoreMaxRelevance = std::pair< double, int >
using ScoreMaxRelevances = std::vector< ScoreMaxRelevance >
Public Member Functions
ScoredHistoryMatch ()
ScoredHistoryMatch (const ScoredHistoryMatch &other)
ScoredHistoryMatch (ScoredHistoryMatch &&other)
ScoredHistoryMatch & operator= (const ScoredHistoryMatch &other)
ScoredHistoryMatch & operator= (ScoredHistoryMatch &&other)
ScoredHistoryMatch (const history::URLRow &row, const VisitInfoVector &visits, const std::u16string &lower_string, const String16Vector &terms_vector, const WordStarts &terms_to_word_starts_offsets, const RowWordStarts &word_starts, bool is_url_bookmarked, size_t num_matching_pages, base::Time now)
~ScoredHistoryMatch ()
Public Member Functions inherited from history::HistoryMatch
HistoryMatch ()
bool IsHostOnly () const
size_t EstimateMemoryUsage () const
Static Public Member Functions
static bool MatchScoreGreater (const ScoredHistoryMatch &m1, const ScoredHistoryMatch &m2)
static TermMatches FilterTermMatchesByWordStarts (const TermMatches &term_matches, const WordStarts &terms_to_word_starts_offsets, const WordStarts &word_starts, size_t start_pos, size_t end_pos, bool allow_midword_continuations=false)
Static Public Member Functions inherited from history::HistoryMatch
static bool EqualsGURL (const HistoryMatch &h, const GURL &url)
Public Attributes
int raw_score
TermMatches url_matches
TermMatches title_matches
Public Attributes inherited from history::HistoryMatch
URLRow url_info
size_t input_location
bool match_in_scheme
bool match_in_subdomain
bool innermost_match
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, GetDocumentSpecificityScore)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, GetFinalRelevancyScore)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, GetFrequency)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, GetHQPBucketsFromString)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, ScoringBookmarks)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, ScoringScheme)
FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest, ScoringTLD)
float GetTopicalityScore (const int num_terms, const GURL &url, const base::OffsetAdjuster::Adjustments &adjustments, const WordStarts &terms_to_word_starts_offsets, const RowWordStarts &word_starts)
float GetRecencyScore (int last_visit_days_ago) const
float GetFrequency (const base::Time &now, const bool bookmarked, const VisitInfoVector &visits) const
float GetDocumentSpecificityScore (size_t num_matching_pages) const
Static Private Member Functions
static void Init ()
static float GetFinalRelevancyScore (float topicality_score, float frequency_score, float specificity_score)
static ScoreMaxRelevances GetHQPBuckets ()
static ScoreMaxRelevances GetHQPBucketsFromString (const std::string &buckets_str)
Static Private Attributes
static bool also_do_hup_like_scoring_
static float bookmark_value_
static float typed_value_
static size_t max_visits_to_score_
static bool allow_tld_matches_
static bool allow_scheme_matches_
static size_t num_title_words_to_allow_
static float topicality_threshold_
static ScoreMaxRelevances * relevance_buckets_override_ = nullptr
static OmniboxFieldTrial::NumMatchesScores * matches_to_specificity_override_ = nullptr
Friends
class ScoredHistoryMatchTest
Member Typedef Documentation
ScoreMaxRelevance
using ScoredHistoryMatch::ScoreMaxRelevance = std::pair<double, int>
ScoreMaxRelevances
using ScoredHistoryMatch::ScoreMaxRelevances = std::vector<ScoreMaxRelevance>
Constructor & Destructor Documentation
ScoredHistoryMatch() [1/4]
ScoredHistoryMatch::ScoredHistoryMatch ()
ScoredHistoryMatch() [2/4]
ScoredHistoryMatch::ScoredHistoryMatch (const ScoredHistoryMatch & other) default
ScoredHistoryMatch() [3/4]
ScoredHistoryMatch::ScoredHistoryMatch (ScoredHistoryMatch && other) default
ScoredHistoryMatch() [4/4]
ScoredHistoryMatch::ScoredHistoryMatch (const history::URLRow & row, const VisitInfoVector & visits, const std::u16string & lower_string, const String16Vector & terms_vector, const WordStarts & terms_to_word_starts_offsets, const RowWordStarts & word_starts, bool is_url_bookmarked, size_t num_matching_pages, base::Time now)
References also_do_hup_like_scoring_, URLPrefix::BestURLPrefix(), DeoverlapMatches(), GetDocumentSpecificityScore(), GetFinalRelevancyScore(), GetFrequency(), AutocompleteMatch::GetMatchComponents(), GetTopicalityScore(), Init(), history::HistoryMatch::innermost_match, history::HistoryMatch::input_location, history::HistoryMatch::IsHostOnly(), HistoryURLProvider::kBaseScoreForNonInlineableResult, HistoryURLProvider::kScoreForBestInlineableResult, history::HistoryMatch::match_in_scheme, history::HistoryMatch::match_in_subdomain, MatchTermInString(), URLPrefix::num_components, OffsetsFromTermMatches(), URLPrefix::prefix, raw_score, ReplaceOffsetsInTermMatches(), SortMatches(), title_matches, history::HistoryMatch::url_info, and url_matches.
~ScoredHistoryMatch()
ScoredHistoryMatch::~ScoredHistoryMatch () default
Member Function Documentation
FilterTermMatchesByWordStarts()
TermMatches ScoredHistoryMatch::FilterTermMatchesByWordStarts (const TermMatches & term_matches, const WordStarts & terms_to_word_starts_offsets, const WordStarts & word_starts, size_t start_pos, size_t end_pos, bool allow_midword_continuations = false) static
Referenced by FindTermMatches(), and GetTopicalityScore().
FRIEND_TEST_ALL_PREFIXES() [1/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , GetDocumentSpecificityScore) private
FRIEND_TEST_ALL_PREFIXES() [2/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , GetFinalRelevancyScore) private
FRIEND_TEST_ALL_PREFIXES() [3/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , GetFrequency) private
FRIEND_TEST_ALL_PREFIXES() [4/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , GetHQPBucketsFromString) private
FRIEND_TEST_ALL_PREFIXES() [5/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , ScoringBookmarks) private
FRIEND_TEST_ALL_PREFIXES() [6/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , ScoringScheme) private
FRIEND_TEST_ALL_PREFIXES() [7/7]
ScoredHistoryMatch::FRIEND_TEST_ALL_PREFIXES (ScoredHistoryMatchTest , ScoringTLD) private
GetDocumentSpecificityScore()
float ScoredHistoryMatch::GetDocumentSpecificityScore (size_t num_matching_pages) const private
References OmniboxFieldTrial::HQPNumMatchesScores(), and matches_to_specificity_override_.
Referenced by ScoredHistoryMatch().
GetFinalRelevancyScore()
float ScoredHistoryMatch::GetFinalRelevancyScore (float topicality_score, float frequency_score, float specificity_score) static private
References GetHQPBuckets(), and relevance_buckets_override_.
Referenced by ScoredHistoryMatch().
GetFrequency()
float ScoredHistoryMatch::GetFrequency (const base::Time & now, const bool bookmarked, const VisitInfoVector & visits) const private
References bookmark_value_, GetRecencyScore(), max_visits_to_score_, and typed_value_.
Referenced by ScoredHistoryMatch().
GetHQPBuckets()
std::vector< ScoredHistoryMatch::ScoreMaxRelevance > ScoredHistoryMatch::GetHQPBuckets () static private
References GetHQPBucketsFromString(), and OmniboxFieldTrial::HQPExperimentalScoringBuckets().
Referenced by GetFinalRelevancyScore().
GetHQPBucketsFromString()
ScoredHistoryMatch::ScoreMaxRelevances ScoredHistoryMatch::GetHQPBucketsFromString (const std::string & buckets_str) static private
Referenced by GetHQPBuckets().
GetRecencyScore()
float ScoredHistoryMatch::GetRecencyScore (int last_visit_days_ago) const private
Referenced by GetFrequency().
GetTopicalityScore()
float ScoredHistoryMatch::GetTopicalityScore (const int num_terms, const GURL & url, const base::OffsetAdjuster::Adjustments & adjustments, const WordStarts & terms_to_word_starts_offsets, const RowWordStarts & word_starts) private
References allow_scheme_matches_, allow_tld_matches_, FilterTermMatchesByWordStarts(), num_title_words_to_allow_, OmniboxFieldTrial::ShouldDisableCGIParamMatching(), title_matches, RowWordStarts::title_word_starts_, topicality_threshold_, url_matches, and RowWordStarts::url_word_starts_.
Referenced by ScoredHistoryMatch().
Init()
void ScoredHistoryMatch::Init () static private
References allow_scheme_matches_, allow_tld_matches_, also_do_hup_like_scoring_, bookmark_value_, OmniboxFieldTrial::HQPAllowMatchInSchemeValue(), OmniboxFieldTrial::HQPAllowMatchInTLDValue(), OmniboxFieldTrial::HQPAlsoDoHUPLikeScoring(), OmniboxFieldTrial::HQPBookmarkValue(), OmniboxFieldTrial::HQPExperimentalTopicalityThreshold(), OmniboxFieldTrial::HQPMaxVisitsToScore(), OmniboxFieldTrial::HQPNumTitleWordsToAllow(), OmniboxFieldTrial::HQPTypedValue(), max_visits_to_score_, num_title_words_to_allow_, topicality_threshold_, and typed_value_.
Referenced by ScoredHistoryMatch().
MatchScoreGreater()
bool ScoredHistoryMatch::MatchScoreGreater (const ScoredHistoryMatch & m1, const ScoredHistoryMatch & m2) static
References history::HistoryMatch::innermost_match, history::HistoryMatch::IsHostOnly(), raw_score, and history::HistoryMatch::url_info.
Referenced by URLIndexPrivateData::HistoryItemsForTerms().
operator=() [1/2]
ScoredHistoryMatch & ScoredHistoryMatch::operator= (const ScoredHistoryMatch & other) default
operator=() [2/2]
ScoredHistoryMatch & ScoredHistoryMatch::operator= (ScoredHistoryMatch && other) default
Friends And Related Function Documentation
ScoredHistoryMatchTest
friend class ScoredHistoryMatchTest friend
Member Data Documentation
allow_scheme_matches_
bool ScoredHistoryMatch::allow_scheme_matches_ static private
Referenced by GetTopicalityScore(), and Init().
allow_tld_matches_
bool ScoredHistoryMatch::allow_tld_matches_ static private
Referenced by GetTopicalityScore(), and Init().
also_do_hup_like_scoring_
bool ScoredHistoryMatch::also_do_hup_like_scoring_ static private
Referenced by Init(), and ScoredHistoryMatch().
bookmark_value_
float ScoredHistoryMatch::bookmark_value_ static private
Referenced by GetFrequency(), and Init().
matches_to_specificity_override_
OmniboxFieldTrial::NumMatchesScores * ScoredHistoryMatch::matches_to_specificity_override_ = nullptr static private
Referenced by GetDocumentSpecificityScore().
max_visits_to_score_
size_t ScoredHistoryMatch::max_visits_to_score_ static private
Referenced by GetFrequency(), and Init().
num_title_words_to_allow_
size_t ScoredHistoryMatch::num_title_words_to_allow_ static private
Referenced by GetTopicalityScore(), and Init().
raw_score
int ScoredHistoryMatch::raw_score
Referenced by HistoryQuickProvider::DoAutocomplete(), URLIndexPrivateData::HistoryIdsToScoredMatches(), MatchScoreGreater(), and ScoredHistoryMatch().
relevance_buckets_override_
ScoredHistoryMatch::ScoreMaxRelevances * ScoredHistoryMatch::relevance_buckets_override_ = nullptr static private
Referenced by GetFinalRelevancyScore().
title_matches
TermMatches ScoredHistoryMatch::title_matches
Referenced by GetTopicalityScore(), and ScoredHistoryMatch().
topicality_threshold_
float ScoredHistoryMatch::topicality_threshold_ static private
Referenced by GetTopicalityScore(), and Init().
typed_value_
float ScoredHistoryMatch::typed_value_ static private
Referenced by GetFrequency(), and Init().
url_matches
TermMatches ScoredHistoryMatch::url_matches
Referenced by GetTopicalityScore(), HistoryQuickProvider::QuickMatchToACMatch(), and ScoredHistoryMatch().
The documentation for this struct was generated from the following files:
components/omnibox/browser/scored_history_match.h
components/omnibox/browser/scored_history_match.cc