Chromium Omnibox: OmniboxPopupSelection Struct Reference
OmniboxPopupSelection Struct Reference
#include <omnibox_popup_selection.h>
Public Types
enum Direction { kForward , kBackward }
enum Step { kWholeLine , kStateOrLine , kAllLines }
enum LineState {
FOCUSED_BUTTON_HEADER = 0 , NORMAL = 1 , KEYWORD_MODE = 2 , FOCUSED_BUTTON_TAB_SWITCH = 3 ,
FOCUSED_BUTTON_ACTION = 4 , FOCUSED_BUTTON_REMOVE_SUGGESTION = 5 , LINE_STATE_MAX_VALUE
}
Public Member Functions
OmniboxPopupSelection (size_t line, LineState state=NORMAL)
bool operator== (const OmniboxPopupSelection &) const
bool operator!= (const OmniboxPopupSelection &) const
bool operator< (const OmniboxPopupSelection &) const
bool IsChangeToKeyword (OmniboxPopupSelection from) const
bool IsButtonFocused () const
bool IsControlPresentOnMatch (const AutocompleteResult &result, PrefService *pref_service) const
OmniboxPopupSelection GetNextSelection (const AutocompleteResult &result, PrefService *pref_service, Direction direction, Step step) const
Public Attributes
size_t line
LineState state
Static Public Attributes
static const size_t kNoMatch = static_cast<size_t>(-1)
Static Private Member Functions
static std::vector< OmniboxPopupSelection > GetAllAvailableSelectionsSorted (const AutocompleteResult &result, PrefService *pref_service, Direction direction, Step step)
Member Enumeration Documentation
Direction
enum OmniboxPopupSelection::Direction
Enumerator
kForward
kBackward
LineState
enum OmniboxPopupSelection::LineState
Enumerator
FOCUSED_BUTTON_HEADER
NORMAL
KEYWORD_MODE
FOCUSED_BUTTON_TAB_SWITCH
FOCUSED_BUTTON_ACTION
FOCUSED_BUTTON_REMOVE_SUGGESTION
LINE_STATE_MAX_VALUE
Step
enum OmniboxPopupSelection::Step
Enumerator
kWholeLine
kStateOrLine
kAllLines
Constructor & Destructor Documentation
OmniboxPopupSelection()
OmniboxPopupSelection::OmniboxPopupSelection (size_t line, LineState state = NORMAL) inline explicit
Member Function Documentation
GetAllAvailableSelectionsSorted()
std::vector< OmniboxPopupSelection > OmniboxPopupSelection::GetAllAvailableSelectionsSorted (const AutocompleteResult & result, PrefService * pref_service, Direction direction, Step step) static private
References FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, IsControlPresentOnMatch(), OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), kAllLines, KEYWORD_MODE, kForward, kStateOrLine, kWholeLine, line, NORMAL, AutocompleteResult::size(), and state.
Referenced by GetNextSelection().
GetNextSelection()
OmniboxPopupSelection OmniboxPopupSelection::GetNextSelection (const AutocompleteResult & result, PrefService * pref_service, Direction direction, Step step) const
References AutocompleteResult::empty(), GetAllAvailableSelectionsSorted(), kAllLines, kBackward, and kForward.
Referenced by OmniboxEditModel::OnUpOrDownKeyPressed().
IsButtonFocused()
bool OmniboxPopupSelection::IsButtonFocused () const
References KEYWORD_MODE, NORMAL, and state.
Referenced by OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxViewViews::HandleKeyEvent(), and OmniboxEditModel::SetPopupSelection().
IsChangeToKeyword()
bool OmniboxPopupSelection::IsChangeToKeyword (OmniboxPopupSelection from) const
References KEYWORD_MODE, and state.
IsControlPresentOnMatch()
bool OmniboxPopupSelection::IsControlPresentOnMatch (const AutocompleteResult & result, PrefService * pref_service) const
References FOCUSED_BUTTON_ACTION, FOCUSED_BUTTON_HEADER, FOCUSED_BUTTON_REMOVE_SUGGESTION, FOCUSED_BUTTON_TAB_SWITCH, OmniboxFieldTrial::IsKeywordSearchButtonEnabled(), AutocompleteResult::IsSuggestionGroupIdHidden(), KEYWORD_MODE, line, AutocompleteResult::match_at(), NORMAL, AutocompleteResult::size(), state, and AutocompleteMatch::suggestion_group_id.
Referenced by GetAllAvailableSelectionsSorted(), and OmniboxEditModel::IsPopupControlPresentOnMatch().
operator!=()
bool OmniboxPopupSelection::operator!= (const OmniboxPopupSelection & b) const
References operator==().
operator<()
bool OmniboxPopupSelection::operator< (const OmniboxPopupSelection & b) const
References line, and state.
operator==()
bool OmniboxPopupSelection::operator== (const OmniboxPopupSelection & b) const
References line, and state.
Referenced by operator!=().
Member Data Documentation
kNoMatch
const size_t OmniboxPopupSelection::kNoMatch = static_cast<size_t>(-1) static
Referenced by OmniboxPopupContentsView::GetIndexForPoint(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupContentsView::GetSelectedResultView(), OmniboxEditModel::IsPopupSelectionOnInitialLine(), OmniboxEditModel::OnPopupResultChanged(), OmniboxPopupContentsView::OnSelectionChanged(), OmniboxEditModel::PasteAndGo(), OmniboxEditModel::ResetPopupToInitialState(), OmniboxEditModel::set_popup_view(), OmniboxViewViews::SetAccessibilityLabel(), OmniboxEditModel::SetPopupSelection(), AutocompleteMatchType::ToAccessibilityLabel(), and OmniboxEditModel::TryDeletingPopupLine().
line
size_t OmniboxPopupSelection::line
Referenced by GetAllAvailableSelectionsSorted(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxResultView::GetMatchSelected(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), OmniboxPopupContentsView::GetSelectedIndex(), OmniboxPopupContentsView::GetSelectedResultView(), IsControlPresentOnMatch(), OmniboxEditModel::IsPopupSelectionOnInitialLine(), OmniboxEditModel::OnPopupResultChanged(), OmniboxPopupContentsView::OnSelectionChanged(), OmniboxEditModel::OnUpOrDownKeyPressed(), operator<(), operator==(), OmniboxEditModel::SetPopupSelection(), OmniboxEditModel::TriggerPopupSelectionAction(), and OmniboxEditModel::TryDeletingPopupLine().
state
LineState OmniboxPopupSelection::state
Referenced by OmniboxEditModel::AcceptKeyword(), OmniboxResultView::ApplyThemeAndRefreshIcons(), OmniboxEditModel::ClearKeyword(), OmniboxController::ClearPopupKeywordMode(), OmniboxResultView::GetActiveAuxiliaryButtonForAccessibility(), OmniboxRowView::GetActiveAuxiliaryButtonForAccessibility(), GetAllAvailableSelectionsSorted(), OmniboxEditModel::GetInfoForCurrentText(), OmniboxResultView::GetMatchSelected(), OmniboxEditModel::GetPopupAccessibilityLabelForCurrentSelection(), IsButtonFocused(), IsChangeToKeyword(), IsControlPresentOnMatch(), OmniboxResultView::OmniboxResultView(), OmniboxViewViews::OnMousePressed(), OmniboxEditModel::OnPopupResultChanged(), OmniboxResultView::OnSelectionStateChanged(), operator<(), operator==(), OmniboxEditModel::SetPopupSelection(), OmniboxEditModel::TriggerPopupSelectionAction(), and OmniboxPopupContentsView::UnselectButton().
The documentation for this struct was generated from the following files:
components/omnibox/browser/omnibox_popup_selection.h
components/omnibox/browser/omnibox_popup_selection.cc