Chromium Omnibox: DocumentProvider Class Reference
DocumentProvider Class Reference
#include <document_provider.h>
Public Member Functions
void Start (const AutocompleteInput &input, bool minimal_changes) override
void Stop (bool clear_cached_results, bool due_to_user_inactivity) override
void DeleteMatch (const AutocompleteMatch &match) override
void AddProviderInfo (ProvidersInfo *provider_info) const override
void ResetSession () override
Public Member Functions inherited from AutocompleteProvider
AutocompleteProvider (Type type)
AutocompleteProvider (const AutocompleteProvider &)=delete
AutocompleteProvider & operator= (const AutocompleteProvider &)=delete
metrics::OmniboxEventProto_ProviderType AsOmniboxEventProviderType () const
virtual size_t EstimateMemoryUsage () const
size_t provider_max_matches () const
const ACMatches & matches () const
bool done () const
Type type () const
const char * GetName () const
Static Public Member Functions
static DocumentProvider * Create (AutocompleteProviderClient *client, AutocompleteProviderListener *listener, size_t cache_size=20)
static void RegisterProfilePrefs (user_prefs::PrefRegistrySyncable *registry)
static ACMatchClassifications Classify (const std::u16string &input_text, const std::u16string &text)
static const GURL GetURLForDeduping (const GURL &url)
Static Public Member Functions inherited from AutocompleteProvider
static const char * TypeToString (Type type)
static ACMatchClassifications ClassifyAllMatchesInString (const std::u16string &find_text, const std::u16string &text, const bool text_is_search_query, const ACMatchClassifications &original_class=ACMatchClassifications())
static bool InExplicitExperimentalKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static bool IsExplicitlyInKeywordMode (const AutocompleteInput &input, const std::u16string &keyword)
static size_t TrimSchemePrefix (std::u16string *url, bool trim_https)
Private Types
using MatchesCache = base::MRUCache< GURL, AutocompleteMatch >
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, IsDocumentProviderAllowed)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, IsInputLikelyURL)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ParseDocumentSearchResults)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ProductDescriptionStringsAndAccessibleLabels)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, MatchDescriptionString)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ParseDocumentSearchResultsBreakTies)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ParseDocumentSearchResultsBreakTiesCascade)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ParseDocumentSearchResultsBreakTiesZeroLimit)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, ParseDocumentSearchResultsWithBadResponse)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, GenerateLastModifiedString)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, Scoring)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, CachingForAsyncMatches)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, CachingForSyncMatches)
FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest, StartCallsStop)
DocumentProvider (AutocompleteProviderClient *client, AutocompleteProviderListener *listener, size_t cache_size)
~DocumentProvider () override
DocumentProvider (const DocumentProvider &)=delete
DocumentProvider & operator= (const DocumentProvider &)=delete
bool IsDocumentProviderAllowed (AutocompleteProviderClient *client, const AutocompleteInput &input)
void Run ()
void OnURLLoadComplete (const network::SimpleURLLoader *source, std::unique_ptr< std::string > response_body)
bool UpdateResults (const std::string &json_data)
void OnDocumentSuggestionsLoaderAvailable (std::unique_ptr< network::SimpleURLLoader > loader)
ACMatches ParseDocumentSearchResults (const base::Value &root_val)
void CopyCachedMatchesToMatches (size_t skip_n_most_recent_matches=0)
void SetCachedMatchesScoresTo0 ()
void DemoteMatchesBeyondMax ()
Static Private Member Functions
static bool IsInputLikelyURL (const AutocompleteInput &input)
static std::u16string GenerateLastModifiedString (const std::string &modified_timestamp_string, base::Time now)
static std::u16string GetProductDescriptionString (const std::string &mimetype)
static std::u16string GetMatchDescription (const std::string &update_time, const std::string &mimetype, const std::string &owner)
Private Attributes
bool field_trial_triggered_
bool field_trial_triggered_in_session_
bool backoff_for_session_
AutocompleteProviderClient * client_
AutocompleteProviderListener * listener_
AutocompleteInput input_
std::unique_ptr< network::SimpleURLLoader > loader_
const size_t cache_size_
MatchesCache matches_cache_
std::unique_ptr< AutocompleteProviderDebouncer > debouncer_
base::WeakPtrFactory< DocumentProvider > weak_ptr_factory_ {this}
Additional Inherited Members
Public Types inherited from AutocompleteProvider
enum Type {
TYPE_BOOKMARK = 1 << 0 , TYPE_BUILTIN = 1 << 1 , TYPE_HISTORY_QUICK = 1 << 2 , TYPE_HISTORY_URL = 1 << 3 ,
TYPE_KEYWORD = 1 << 4 , TYPE_SEARCH = 1 << 5 , TYPE_SHORTCUTS = 1 << 6 , TYPE_ZERO_SUGGEST = 1 << 7 ,
TYPE_CLIPBOARD = 1 << 8 , TYPE_DOCUMENT = 1 << 9 , TYPE_ON_DEVICE_HEAD = 1 << 10 , TYPE_ZERO_SUGGEST_LOCAL_HISTORY = 1 << 11 ,
TYPE_QUERY_TILE = 1 << 12 , TYPE_MOST_VISITED_SITES = 1 << 13 , TYPE_VERBATIM_MATCH = 1 << 14 , TYPE_VOICE_SUGGEST = 1 << 15
}
typedef std::multimap< char16_t, std::u16string > WordMap
Protected Types inherited from AutocompleteProvider
typedef std::pair< bool, std::u16string > FixupReturn
Protected Member Functions inherited from AutocompleteProvider
FRIEND_TEST_ALL_PREFIXES (BookmarkProviderTest, InlineAutocompletion)
FRIEND_TEST_ALL_PREFIXES (AutocompleteResultTest, DemoteOnDeviceSearchSuggestions)
virtual ~AutocompleteProvider ()
Static Protected Member Functions inherited from AutocompleteProvider
static FixupReturn FixupUserInput (const AutocompleteInput &input)
Protected Attributes inherited from AutocompleteProvider
const size_t provider_max_matches_
ACMatches matches_
bool done_
Type type_
Member Typedef Documentation
MatchesCache
using DocumentProvider::MatchesCache = base::MRUCache<GURL, AutocompleteMatch> private
Constructor & Destructor Documentation
DocumentProvider() [1/2]
DocumentProvider::DocumentProvider (AutocompleteProviderClient * client, AutocompleteProviderListener * listener, size_t cache_size) private
References AutocompleteProviderDebouncer::AutocompleteProviderDebouncer(), debouncer_, and omnibox::kDebounceDocumentProvider.
Referenced by Create().
~DocumentProvider()
DocumentProvider::~DocumentProvider () override private default
DocumentProvider() [2/2]
DocumentProvider::DocumentProvider (const DocumentProvider &) private delete
Member Function Documentation
AddProviderInfo()
void DocumentProvider::AddProviderInfo (ProvidersInfo * provider_info) const override virtual
Reimplemented from AutocompleteProvider.
References AutocompleteProvider::done_, field_trial_triggered_, field_trial_triggered_in_session_, and OmniboxFieldTrial::GetActiveSuggestFieldTrialHashes().
Classify()
ACMatchClassifications DocumentProvider::Classify (const std::u16string & input_text, const std::u16string & text) static
References ClassifyTermMatches(), FindTermMatches(), AutocompleteMatch::ACMatchClassification::MATCH, and AutocompleteMatch::ACMatchClassification::NONE.
Referenced by ParseDocumentSearchResults().
CopyCachedMatchesToMatches()
void DocumentProvider::CopyCachedMatchesToMatches (size_t skip_n_most_recent_matches = 0) private
References matches_cache_.
Referenced by Start(), and UpdateResults().
Create()
DocumentProvider * DocumentProvider::Create (AutocompleteProviderClient * client, AutocompleteProviderListener * listener, size_t cache_size = 20) static
References DocumentProvider().
Referenced by AutocompleteController::AutocompleteController().
DeleteMatch()
void DocumentProvider::DeleteMatch (const AutocompleteMatch & match) override virtual
Reimplemented from AutocompleteProvider.
DemoteMatchesBeyondMax()
void DocumentProvider::DemoteMatchesBeyondMax () private
References AutocompleteProvider::matches_, and AutocompleteProvider::provider_max_matches_.
Referenced by Start(), and UpdateResults().
FRIEND_TEST_ALL_PREFIXES() [1/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , CachingForAsyncMatches) private
FRIEND_TEST_ALL_PREFIXES() [2/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , CachingForSyncMatches) private
FRIEND_TEST_ALL_PREFIXES() [3/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , GenerateLastModifiedString) private
FRIEND_TEST_ALL_PREFIXES() [4/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , IsDocumentProviderAllowed) private
FRIEND_TEST_ALL_PREFIXES() [5/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , IsInputLikelyURL) private
FRIEND_TEST_ALL_PREFIXES() [6/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , MatchDescriptionString) private
FRIEND_TEST_ALL_PREFIXES() [7/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ParseDocumentSearchResults) private
FRIEND_TEST_ALL_PREFIXES() [8/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ParseDocumentSearchResultsBreakTies) private
FRIEND_TEST_ALL_PREFIXES() [9/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ParseDocumentSearchResultsBreakTiesCascade) private
FRIEND_TEST_ALL_PREFIXES() [10/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ParseDocumentSearchResultsBreakTiesZeroLimit) private
FRIEND_TEST_ALL_PREFIXES() [11/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ParseDocumentSearchResultsWithBadResponse) private
FRIEND_TEST_ALL_PREFIXES() [12/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , ProductDescriptionStringsAndAccessibleLabels) private
FRIEND_TEST_ALL_PREFIXES() [13/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , Scoring) private
FRIEND_TEST_ALL_PREFIXES() [14/14]
DocumentProvider::FRIEND_TEST_ALL_PREFIXES (DocumentProviderTest , StartCallsStop) private
GenerateLastModifiedString()
std::u16string DocumentProvider::GenerateLastModifiedString (const std::string & modified_timestamp_string, base::Time now) static private
Referenced by GetMatchDescription().
GetMatchDescription()
std::u16string DocumentProvider::GetMatchDescription (const std::string & update_time, const std::string & mimetype, const std::string & owner) static private
References GenerateLastModifiedString(), and GetProductDescriptionString().
Referenced by ParseDocumentSearchResults().
GetProductDescriptionString()
std::u16string DocumentProvider::GetProductDescriptionString (const std::string & mimetype) static private
Referenced by GetMatchDescription().
GetURLForDeduping()
const GURL DocumentProvider::GetURLForDeduping (const GURL & url) static
Referenced by AutocompleteMatch::GURLToStrippedGURL().
IsDocumentProviderAllowed()
bool DocumentProvider::IsDocumentProviderAllowed (AutocompleteProviderClient * client, const AutocompleteInput & input) private
References backoff_for_session_, omnibox::DEFAULT, AutocompleteInput::focus_type(), AutocompleteProviderClient::GetPrefs(), KeywordProvider::GetSubstitutingTemplateURLForInput(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteProviderClient::IsAuthenticated(), OmniboxFieldTrial::IsExperimentalKeywordModeEnabled(), AutocompleteProvider::IsExplicitlyInKeywordMode(), IsInputLikelyURL(), AutocompleteProviderClient::IsOffTheRecord(), AutocompleteProviderClient::IsSyncActive(), omnibox::kDocumentProvider, omnibox::kDocumentSuggestEnabled, AutocompleteInput::prefer_keyword(), AutocompleteProviderClient::SearchSuggestEnabled(), AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by Start().
IsInputLikelyURL()
bool DocumentProvider::IsInputLikelyURL (const AutocompleteInput & input) static private
References AutocompleteInput::text(), and AutocompleteInput::type().
Referenced by IsDocumentProviderAllowed().
OnDocumentSuggestionsLoaderAvailable()
void DocumentProvider::OnDocumentSuggestionsLoaderAvailable (std::unique_ptr< network::SimpleURLLoader > loader) private
References loader_.
Referenced by Run().
OnURLLoadComplete()
void DocumentProvider::OnURLLoadComplete (const network::SimpleURLLoader * source, std::unique_ptr< std::string > response_body) private
References backoff_for_session_, AutocompleteProvider::done_, SearchSuggestionParser::ExtractJsonData(), listener_, loader_, AutocompleteProviderListener::OnProviderUpdate(), and UpdateResults().
Referenced by Run().
operator=()
DocumentProvider& DocumentProvider::operator= (const DocumentProvider &) private delete
ParseDocumentSearchResults()
ACMatches DocumentProvider::ParseDocumentSearchResults (const base::Value & root_val) private
References AutocompleteMatch::AddLastClassificationIfNecessary(), Classify(), client_, AutocompleteMatch::contents, AutocompleteMatch::contents_class, AutocompleteMatch::description, AutocompleteMatch::description_class, AutocompleteMatch::description_class_for_shortcuts, AutocompleteMatch::description_for_shortcuts, AutocompleteMatch::destination_url, AutocompleteMatch::ACMatchClassification::DIM, AutocompleteMatchType::DOCUMENT_SUGGESTION, AutocompleteMatch::document_type, AutocompleteMatch::DocumentTypeString(), field_trial_triggered_, field_trial_triggered_in_session_, AutocompleteMatch::fill_into_edit, GetMatchDescription(), AutocompleteProviderClient::GetTemplateURLService(), AutocompleteMatch::GURLToStrippedGURL(), input_, omnibox::kDocumentProvider, AutocompleteProvider::matches(), AutocompleteProviderClient::ProfileUserName(), AutocompleteProvider::provider_max_matches_, AutocompleteMatch::RecordAdditionalInfo(), AutocompleteMatch::SanitizeString(), AutocompleteMatch::stripped_destination_url, AutocompleteInput::text(), AutocompleteMatch::transition, and AutocompleteMatch::TryRichAutocompletion().
Referenced by UpdateResults().
RegisterProfilePrefs()
void DocumentProvider::RegisterProfilePrefs (user_prefs::PrefRegistrySyncable * registry) static
References omnibox::kDocumentSuggestEnabled.
ResetSession()
void DocumentProvider::ResetSession () override virtual
Reimplemented from AutocompleteProvider.
References field_trial_triggered_, and field_trial_triggered_in_session_.
Run()
void DocumentProvider::Run () private
References client_, DocumentSuggestionsService::CreateDocumentSuggestionsRequest(), AutocompleteProviderClient::GetDocumentSuggestionsService(), input_, AutocompleteProviderClient::IsOffTheRecord(), OnDocumentSuggestionsLoaderAvailable(), OnURLLoadComplete(), AutocompleteInput::text(), and weak_ptr_factory_.
Referenced by Start().
SetCachedMatchesScoresTo0()
void DocumentProvider::SetCachedMatchesScoresTo0 () private
References matches_cache_.
Referenced by UpdateResults().
Start()
void DocumentProvider::Start (const AutocompleteInput & input, bool minimal_changes) override virtual
Implements AutocompleteProvider.
References client_, CopyCachedMatchesToMatches(), debouncer_, DemoteMatchesBeyondMax(), AutocompleteProvider::done_, field_trial_triggered_, input_, IsDocumentProviderAllowed(), Run(), Stop(), and AutocompleteInput::want_asynchronous_matches().
Stop()
void DocumentProvider::Stop (bool clear_cached_results, bool due_to_user_inactivity) override virtual
Reimplemented from AutocompleteProvider.
References client_, debouncer_, AutocompleteProvider::done_, AutocompleteProviderClient::GetDocumentSuggestionsService(), loader_, AutocompleteProvider::matches_, and DocumentSuggestionsService::StopCreatingDocumentSuggestionsRequest().
Referenced by Start().
UpdateResults()
bool DocumentProvider::UpdateResults (const std::string & json_data) private
References cache_size_, CopyCachedMatchesToMatches(), DemoteMatchesBeyondMax(), AutocompleteProvider::matches_, matches_cache_, ParseDocumentSearchResults(), and SetCachedMatchesScoresTo0().
Referenced by OnURLLoadComplete().
Member Data Documentation
backoff_for_session_
bool DocumentProvider::backoff_for_session_ private
Referenced by IsDocumentProviderAllowed(), and OnURLLoadComplete().
cache_size_
const size_t DocumentProvider::cache_size_ private
Referenced by UpdateResults().
client_
AutocompleteProviderClient* DocumentProvider::client_ private
Referenced by ParseDocumentSearchResults(), Run(), Start(), and Stop().
debouncer_
std::unique_ptr<AutocompleteProviderDebouncer> DocumentProvider::debouncer_ private
Referenced by DocumentProvider(), Start(), and Stop().
field_trial_triggered_
bool DocumentProvider::field_trial_triggered_ private
Referenced by AddProviderInfo(), ParseDocumentSearchResults(), ResetSession(), and Start().
field_trial_triggered_in_session_
bool DocumentProvider::field_trial_triggered_in_session_ private
Referenced by AddProviderInfo(), ParseDocumentSearchResults(), and ResetSession().
input_
AutocompleteInput DocumentProvider::input_ private
Referenced by ParseDocumentSearchResults(), Run(), and Start().
listener_
AutocompleteProviderListener* DocumentProvider::listener_ private
Referenced by OnURLLoadComplete().
loader_
std::unique_ptr<network::SimpleURLLoader> DocumentProvider::loader_ private
Referenced by OnDocumentSuggestionsLoaderAvailable(), OnURLLoadComplete(), and Stop().
matches_cache_
MatchesCache DocumentProvider::matches_cache_ private
Referenced by CopyCachedMatchesToMatches(), SetCachedMatchesScoresTo0(), and UpdateResults().
weak_ptr_factory_
base::WeakPtrFactory<DocumentProvider> DocumentProvider::weak_ptr_factory_ {this} private
Referenced by Run().
The documentation for this class was generated from the following files:
components/omnibox/browser/document_provider.h
components/omnibox/browser/document_provider.cc