Chromium Omnibox: ShortcutsDatabase Class Reference
ShortcutsDatabase Class Reference
#include <shortcuts_database.h>
Classes
struct Shortcut
Public Types
typedef std::vector< std::string > ShortcutIDs
typedef std::map< std::string, Shortcut > GuidToShortcutMap
Public Member Functions
ShortcutsDatabase (const base::FilePath &database_path)
ShortcutsDatabase (const ShortcutsDatabase &)=delete
ShortcutsDatabase & operator= (const ShortcutsDatabase &)=delete
bool Init ()
bool AddShortcut (const Shortcut &shortcut)
bool UpdateShortcut (const Shortcut &shortcut)
bool DeleteShortcutsWithIDs (const ShortcutIDs &shortcut_ids)
bool DeleteShortcutsWithURL (const std::string &shortcut_url_spec)
bool DeleteAllShortcuts ()
void LoadShortcuts (GuidToShortcutMap *shortcuts)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest, AddShortcut)
FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest, UpdateShortcut)
FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest, DeleteShortcutsWithIds)
FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest, DeleteShortcutsWithURL)
FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest, LoadShortcuts)
virtual ~ShortcutsDatabase ()
bool EnsureTable ()
bool DoMigration (int version)
Private Attributes
sql::Database db_
base::FilePath database_path_
sql::MetaTable meta_table_
Friends
class base::RefCountedThreadSafe< ShortcutsDatabase >
class ShortcutsDatabaseTest
Member Typedef Documentation
GuidToShortcutMap
typedef std::map<std::string, Shortcut> ShortcutsDatabase::GuidToShortcutMap
ShortcutIDs
typedef std::vector<std::string> ShortcutsDatabase::ShortcutIDs
Constructor & Destructor Documentation
ShortcutsDatabase() [1/2]
ShortcutsDatabase::ShortcutsDatabase (const base::FilePath & database_path) explicit
ShortcutsDatabase() [2/2]
ShortcutsDatabase::ShortcutsDatabase (const ShortcutsDatabase &) delete
Member Function Documentation
AddShortcut()
bool ShortcutsDatabase::AddShortcut (const Shortcut & shortcut)
References db_.
Referenced by ShortcutsBackend::AddShortcut().
DeleteAllShortcuts()
bool ShortcutsDatabase::DeleteAllShortcuts ()
References db_.
Referenced by ShortcutsBackend::DeleteAllShortcuts().
DeleteShortcutsWithIDs()
bool ShortcutsDatabase::DeleteShortcutsWithIDs (const ShortcutIDs & shortcut_ids)
References db_.
Referenced by ShortcutsBackend::DeleteShortcutsWithIDs().
DeleteShortcutsWithURL()
bool ShortcutsDatabase::DeleteShortcutsWithURL (const std::string & shortcut_url_spec)
References db_.
Referenced by ShortcutsBackend::DeleteShortcutsWithURL().
DoMigration()
bool ShortcutsDatabase::DoMigration (int version) private
References db_, AutocompleteMatchType::HISTORY_TITLE, and meta_table_.
Referenced by EnsureTable().
EnsureTable()
bool ShortcutsDatabase::EnsureTable () private
References db_, DoMigration(), and meta_table_.
Referenced by Init().
FRIEND_TEST_ALL_PREFIXES() [1/5]
ShortcutsDatabase::FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest , AddShortcut) private
FRIEND_TEST_ALL_PREFIXES() [2/5]
ShortcutsDatabase::FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest , DeleteShortcutsWithIds) private
FRIEND_TEST_ALL_PREFIXES() [3/5]
ShortcutsDatabase::FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest , DeleteShortcutsWithURL) private
FRIEND_TEST_ALL_PREFIXES() [4/5]
ShortcutsDatabase::FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest , LoadShortcuts) private
FRIEND_TEST_ALL_PREFIXES() [5/5]
ShortcutsDatabase::FRIEND_TEST_ALL_PREFIXES (ShortcutsDatabaseTest , UpdateShortcut) private
Init()
bool ShortcutsDatabase::Init ()
References database_path_, db_, and EnsureTable().
LoadShortcuts()
void ShortcutsDatabase::LoadShortcuts (GuidToShortcutMap * shortcuts)
References db_, AutocompleteMatch::DocumentTypeFromInteger(), and AutocompleteMatchType::FromInteger().
operator=()
ShortcutsDatabase& ShortcutsDatabase::operator= (const ShortcutsDatabase &) delete
UpdateShortcut()
bool ShortcutsDatabase::UpdateShortcut (const Shortcut & shortcut)
References db_, and ShortcutsDatabase::Shortcut::id.
Referenced by ShortcutsBackend::UpdateShortcut().
~ShortcutsDatabase()
ShortcutsDatabase::~ShortcutsDatabase () private virtual
Friends And Related Function Documentation
base::RefCountedThreadSafe< ShortcutsDatabase >
friend class base::RefCountedThreadSafe< ShortcutsDatabase > friend
ShortcutsDatabaseTest
friend class ShortcutsDatabaseTest friend
Member Data Documentation
database_path_
base::FilePath ShortcutsDatabase::database_path_ private
Referenced by Init().
db_
sql::Database ShortcutsDatabase::db_ private
Referenced by AddShortcut(), DeleteAllShortcuts(), DeleteShortcutsWithIDs(), DeleteShortcutsWithURL(), DoMigration(), EnsureTable(), Init(), LoadShortcuts(), and UpdateShortcut().
meta_table_
sql::MetaTable ShortcutsDatabase::meta_table_ private
Referenced by DoMigration(), and EnsureTable().
The documentation for this class was generated from the following files:
components/omnibox/browser/shortcuts_database.h
components/omnibox/browser/shortcuts_database.cc