Chromium Omnibox: OmniboxPopupView Class Reference
OmniboxPopupView Class Reference abstract
#include <omnibox_popup_view.h>
Public Member Functions
virtual ~OmniboxPopupView ()=default
virtual bool IsOpen () const =0
virtual void InvalidateLine (size_t line)=0
virtual void OnSelectionChanged (OmniboxPopupModel::Selection old_selection, OmniboxPopupModel::Selection new_selection)
virtual void UpdatePopupAppearance ()=0
virtual void ProvideButtonFocusHint (size_t line)=0
virtual void OnMatchIconUpdated (size_t match_index)=0
virtual void OnDragCanceled ()=0
Constructor & Destructor Documentation
~OmniboxPopupView()
virtual OmniboxPopupView::~OmniboxPopupView () virtual default
Member Function Documentation
InvalidateLine()
virtual void OmniboxPopupView::InvalidateLine (size_t line) pure virtual
Implemented in OmniboxPopupContentsView.
IsOpen()
virtual bool OmniboxPopupView::IsOpen () const pure virtual
Implemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::IsOpen(), OmniboxPopupModel::OnFaviconFetched(), and OmniboxPopupModel::OnResultChanged().
OnDragCanceled()
virtual void OmniboxPopupView::OnDragCanceled () pure virtual
Implemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::ResetToInitialState().
OnMatchIconUpdated()
virtual void OmniboxPopupView::OnMatchIconUpdated (size_t match_index) pure virtual
Implemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::OnFaviconFetched().
OnSelectionChanged()
virtual void OmniboxPopupView::OnSelectionChanged (OmniboxPopupModel::Selection old_selection, OmniboxPopupModel::Selection new_selection) inline virtual
Reimplemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::SetSelection().
ProvideButtonFocusHint()
virtual void OmniboxPopupView::ProvideButtonFocusHint (size_t line) pure virtual
Implemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::SetSelection().
UpdatePopupAppearance()
virtual void OmniboxPopupView::UpdatePopupAppearance () pure virtual
Implemented in OmniboxPopupContentsView.
Referenced by OmniboxPopupModel::OnResultChanged(), and OmniboxPopupModel::SetRichSuggestionBitmap().
The documentation for this class was generated from the following file:
components/omnibox/browser/omnibox_popup_view.h