Chromium Omnibox: LocationBarModel Class Reference
LocationBarModel Class Reference abstract
#include <location_bar_model.h>
Public Member Functions
virtual ~LocationBarModel ()=default
virtual std::u16string GetFormattedFullURL () const =0
virtual std::u16string GetURLForDisplay () const =0
virtual GURL GetURL () const =0
virtual security_state::SecurityLevel GetSecurityLevel () const =0
virtual net::CertStatus GetCertStatus () const =0
virtual metrics::OmniboxEventProto::PageClassification GetPageClassification (OmniboxFocusSource focus_source)=0
virtual const gfx::VectorIcon & GetVectorIcon () const =0
virtual std::u16string GetSecureDisplayText () const =0
virtual std::u16string GetSecureAccessibilityText () const =0
virtual bool ShouldDisplayURL () const =0
virtual bool IsOfflinePage () const =0
virtual bool ShouldPreventElision () const =0
Protected Member Functions
LocationBarModel ()=default
LocationBarModel (const LocationBarModel &)=delete
LocationBarModel & operator= (const LocationBarModel &)=delete
Constructor & Destructor Documentation
~LocationBarModel()
virtual LocationBarModel::~LocationBarModel () virtual default
LocationBarModel() [1/2]
LocationBarModel::LocationBarModel () protected default
LocationBarModel() [2/2]
LocationBarModel::LocationBarModel (const LocationBarModel &) protected delete
Member Function Documentation
GetCertStatus()
virtual net::CertStatus LocationBarModel::GetCertStatus () const pure virtual
Implemented in LocationBarModelImpl.
GetFormattedFullURL()
virtual std::u16string LocationBarModel::GetFormattedFullURL () const pure virtual
Implemented in LocationBarModelImpl.
Referenced by OmniboxViewViews::OnMousePressed().
GetPageClassification()
virtual metrics::OmniboxEventProto::PageClassification LocationBarModel::GetPageClassification (OmniboxFocusSource focus_source) pure virtual
Implemented in LocationBarModelImpl.
Referenced by OmniboxEditModel::GetPageClassification().
GetSecureAccessibilityText()
virtual std::u16string LocationBarModel::GetSecureAccessibilityText () const pure virtual
Implemented in LocationBarModelImpl.
GetSecureDisplayText()
virtual std::u16string LocationBarModel::GetSecureDisplayText () const pure virtual
Implemented in LocationBarModelImpl.
GetSecurityLevel()
virtual security_state::SecurityLevel LocationBarModel::GetSecurityLevel () const pure virtual
Implemented in LocationBarModelImpl.
GetURL()
virtual GURL LocationBarModel::GetURL () const pure virtual
Implemented in LocationBarModelImpl.
Referenced by OmniboxEditModel::AdjustTextForCopy().
GetURLForDisplay()
virtual std::u16string LocationBarModel::GetURLForDisplay () const pure virtual
Implemented in LocationBarModelImpl.
GetVectorIcon()
virtual const gfx::VectorIcon& LocationBarModel::GetVectorIcon () const pure virtual
Implemented in LocationBarModelImpl.
IsOfflinePage()
virtual bool LocationBarModel::IsOfflinePage () const pure virtual
Implemented in LocationBarModelImpl.
operator=()
LocationBarModel& LocationBarModel::operator= (const LocationBarModel &) protected delete
ShouldDisplayURL()
virtual bool LocationBarModel::ShouldDisplayURL () const pure virtual
Implemented in LocationBarModelImpl.
ShouldPreventElision()
virtual bool LocationBarModel::ShouldPreventElision () const pure virtual
Implemented in LocationBarModelImpl.
Referenced by OmniboxEditModel::ShouldPreventElision().
The documentation for this class was generated from the following file:
components/omnibox/browser/location_bar_model.h