Chromium Omnibox: SuggestionAnswer::ImageLine Class Reference
SuggestionAnswer::ImageLine Class Reference
#include <suggestion_answer.h>
Public Member Functions
ImageLine ()
ImageLine (const ImageLine &line)
ImageLine (ImageLine &&) noexcept
ImageLine & operator= (const ImageLine &line)
ImageLine & operator= (ImageLine &&) noexcept
~ImageLine ()
const TextFields & text_fields () const
int num_text_lines () const
const TextField * additional_text () const
const TextField * status_text () const
const GURL & image_url () const
bool Equals (const ImageLine &line) const
std::u16string AccessibleText () const
size_t EstimateMemoryUsage () const
void SetTextStyles (int from_type, TextStyle style)
Static Public Member Functions
static bool ParseImageLine (const base::Value &line_json, ImageLine *image_line)
Private Member Functions
FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest, DifferentValuesAreUnequal)
Private Attributes
TextFields text_fields_
int num_text_lines_
absl::optional< TextField > additional_text_
absl::optional< TextField > status_text_
GURL image_url_
Constructor & Destructor Documentation
ImageLine() [1/3]
SuggestionAnswer::ImageLine::ImageLine ()
ImageLine() [2/3]
SuggestionAnswer::ImageLine::ImageLine (const ImageLine & line) explicit default
ImageLine() [3/3]
SuggestionAnswer::ImageLine::ImageLine (ImageLine &&) default noexcept
~ImageLine()
SuggestionAnswer::ImageLine::~ImageLine ()
Member Function Documentation
AccessibleText()
std::u16string SuggestionAnswer::ImageLine::AccessibleText () const
additional_text()
const TextField* SuggestionAnswer::ImageLine::additional_text () const inline
References additional_text_.
Referenced by OmniboxTextView::AppendExtraText().
Equals()
bool SuggestionAnswer::ImageLine::Equals (const ImageLine & line) const
References additional_text_, SuggestionAnswer::Equals(), image_url_, SuggestionAnswer::image_url_, num_text_lines_, status_text_, and text_fields_.
Referenced by SuggestionAnswer::Equals().
EstimateMemoryUsage()
size_t SuggestionAnswer::ImageLine::EstimateMemoryUsage () const
References base::trace_event::EstimateMemoryUsage(), and SuggestionAnswer::image_url_.
FRIEND_TEST_ALL_PREFIXES()
SuggestionAnswer::ImageLine::FRIEND_TEST_ALL_PREFIXES (SuggestionAnswerTest , DifferentValuesAreUnequal) private
image_url()
const GURL& SuggestionAnswer::ImageLine::image_url () const inline
References image_url_.
Referenced by SuggestionAnswer::AddImageURLsTo().
num_text_lines()
int SuggestionAnswer::ImageLine::num_text_lines () const inline
References num_text_lines_.
Referenced by OmniboxTextView::SetTextWithStyling().
operator=() [1/2]
SuggestionAnswer::ImageLine & SuggestionAnswer::ImageLine::operator= (const ImageLine & line) default
operator=() [2/2]
SuggestionAnswer::ImageLine & SuggestionAnswer::ImageLine::operator= (ImageLine &&) default noexcept
ParseImageLine()
bool SuggestionAnswer::ImageLine::ParseImageLine (const base::Value & line_json, ImageLine * image_line) static
References additional_text_, SuggestionAnswer::TextField::has_num_lines(), image_url_, SuggestionAnswer::TextField::num_lines(), num_text_lines_, SuggestionAnswer::TextField::ParseTextField(), status_text_, and text_fields_.
Referenced by SuggestionAnswer::ParseAnswer().
SetTextStyles()
void SuggestionAnswer::ImageLine::SetTextStyles (int from_type, SuggestionAnswer::TextStyle style)
References SuggestionAnswer::NONE.
Referenced by SuggestionAnswer::InterpretTextTypes().
status_text()
const TextField* SuggestionAnswer::ImageLine::status_text () const inline
References status_text_.
Referenced by OmniboxTextView::AppendExtraText().
text_fields()
const TextFields& SuggestionAnswer::ImageLine::text_fields () const inline
References text_fields_.
Referenced by OmniboxTextView::SetTextWithStyling().
Member Data Documentation
additional_text_
absl::optional<TextField> SuggestionAnswer::ImageLine::additional_text_ private
Referenced by additional_text(), Equals(), and ParseImageLine().
image_url_
GURL SuggestionAnswer::ImageLine::image_url_ private
Referenced by Equals(), image_url(), and ParseImageLine().
num_text_lines_
int SuggestionAnswer::ImageLine::num_text_lines_ private
Referenced by Equals(), num_text_lines(), and ParseImageLine().
status_text_
absl::optional<TextField> SuggestionAnswer::ImageLine::status_text_ private
Referenced by Equals(), ParseImageLine(), and status_text().
text_fields_
TextFields SuggestionAnswer::ImageLine::text_fields_ private
Referenced by Equals(), ParseImageLine(), and text_fields().
The documentation for this class was generated from the following files:
components/omnibox/browser/suggestion_answer.h
components/omnibox/browser/suggestion_answer.cc