Chromium Omnibox: AutocompleteClassifier Class Reference
AutocompleteClassifier Class Reference
#include <autocomplete_classifier.h>
Public Member Functions
AutocompleteClassifier ()=delete
AutocompleteClassifier (std::unique_ptr< AutocompleteController > controller_, std::unique_ptr< AutocompleteSchemeClassifier > scheme_classifier)
AutocompleteClassifier (const AutocompleteClassifier &)=delete
AutocompleteClassifier & operator= (const AutocompleteClassifier &)=delete
~AutocompleteClassifier () override
void Shutdown () override
void Classify (const std::u16string &text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch *match, GURL *alternate_nav_url)
Static Public Member Functions
static int DefaultOmniboxProviders ()
Private Attributes
std::unique_ptr< AutocompleteController > controller_
std::unique_ptr< AutocompleteSchemeClassifier > scheme_classifier_
bool inside_classify_
Constructor & Destructor Documentation
AutocompleteClassifier() [1/3]
AutocompleteClassifier::AutocompleteClassifier () delete
AutocompleteClassifier() [2/3]
AutocompleteClassifier::AutocompleteClassifier (std::unique_ptr< AutocompleteController > controller_, std::unique_ptr< AutocompleteSchemeClassifier > scheme_classifier)
AutocompleteClassifier() [3/3]
AutocompleteClassifier::AutocompleteClassifier (const AutocompleteClassifier &) delete
~AutocompleteClassifier()
AutocompleteClassifier::~AutocompleteClassifier () override
References controller_.
Member Function Documentation
Classify()
void AutocompleteClassifier::Classify (const std::u16string & text, bool prefer_keyword, bool allow_exact_keyword_match, metrics::OmniboxEventProto::PageClassification page_classification, AutocompleteMatch * match, GURL * alternate_nav_url)
References AutocompleteResult::ComputeAlternateNavUrl(), controller_, inside_classify_, scheme_classifier_, AutocompleteInput::set_allow_exact_keyword_match(), AutocompleteInput::set_prefer_keyword(), AutocompleteInput::set_prevent_inline_autocomplete(), and AutocompleteInput::set_want_asynchronous_matches().
DefaultOmniboxProviders()
int AutocompleteClassifier::DefaultOmniboxProviders () static
References OmniboxFieldTrial::IsOnDeviceHeadSuggestEnabledForAnyMode(), omnibox::kDocumentProvider, AutocompleteProvider::TYPE_BOOKMARK, AutocompleteProvider::TYPE_BUILTIN, AutocompleteProvider::TYPE_CLIPBOARD, AutocompleteProvider::TYPE_DOCUMENT, AutocompleteProvider::TYPE_HISTORY_QUICK, AutocompleteProvider::TYPE_HISTORY_URL, AutocompleteProvider::TYPE_KEYWORD, AutocompleteProvider::TYPE_MOST_VISITED_SITES, AutocompleteProvider::TYPE_ON_DEVICE_HEAD, AutocompleteProvider::TYPE_QUERY_TILE, AutocompleteProvider::TYPE_SEARCH, AutocompleteProvider::TYPE_SHORTCUTS, AutocompleteProvider::TYPE_VERBATIM_MATCH, AutocompleteProvider::TYPE_VOICE_SUGGEST, AutocompleteProvider::TYPE_ZERO_SUGGEST, and AutocompleteProvider::TYPE_ZERO_SUGGEST_LOCAL_HISTORY.
operator=()
AutocompleteClassifier& AutocompleteClassifier::operator= (const AutocompleteClassifier &) delete
Shutdown()
void AutocompleteClassifier::Shutdown () override
References controller_.
Member Data Documentation
controller_
std::unique_ptr<AutocompleteController> AutocompleteClassifier::controller_ private
Referenced by Classify(), Shutdown(), and ~AutocompleteClassifier().
inside_classify_
bool AutocompleteClassifier::inside_classify_ private
Referenced by Classify().
scheme_classifier_
std::unique_ptr<AutocompleteSchemeClassifier> AutocompleteClassifier::scheme_classifier_ private
Referenced by Classify().
The documentation for this class was generated from the following files:
components/omnibox/browser/autocomplete_classifier.h
components/omnibox/browser/autocomplete_classifier.cc