Chromium Omnibox: SearchSuggestionParser::Result Class Reference
SearchSuggestionParser::Result Class Reference abstract
#include <search_suggestion_parser.h>
Public Member Functions
Result (bool from_keyword, int relevance, bool relevance_from_server, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::string &deletion_url)
Result (const Result &other)
virtual ~Result ()
bool from_keyword () const
const std::u16string & match_contents () const
const ACMatchClassifications & match_contents_class () const
AutocompleteMatchType::Type type () const
const std::vector< int > & subtypes () const
int relevance () const
void set_relevance (int relevance)
bool received_after_last_keystroke () const
void set_received_after_last_keystroke (bool received_after_last_keystroke)
bool relevance_from_server () const
void set_relevance_from_server (bool relevance_from_server)
const std::string & deletion_url () const
virtual int CalculateRelevance (const AutocompleteInput &input, bool keyword_provider_requested) const =0
Protected Attributes
std::u16string match_contents_
ACMatchClassifications match_contents_class_
bool from_keyword_
AutocompleteMatchType::Type type_
std::vector< int > subtypes_
int relevance_
Private Attributes
bool relevance_from_server_
bool received_after_last_keystroke_
std::string deletion_url_
Constructor & Destructor Documentation
Result() [1/2]
SearchSuggestionParser::Result::Result (bool from_keyword, int relevance, bool relevance_from_server, AutocompleteMatchType::Type type, std::vector< int > subtypes, const std::string & deletion_url)
Result() [2/2]
SearchSuggestionParser::Result::Result (const Result & other) default
~Result()
SearchSuggestionParser::Result::~Result () virtual
Member Function Documentation
CalculateRelevance()
virtual int SearchSuggestionParser::Result::CalculateRelevance (const AutocompleteInput & input, bool keyword_provider_requested) const pure virtual
Implemented in SearchSuggestionParser::NavigationResult, and SearchSuggestionParser::SuggestResult.
deletion_url()
const std::string& SearchSuggestionParser::Result::deletion_url () const inline
References deletion_url_.
Referenced by BaseSearchProvider::AddMatchToMap(), and SearchProvider::NavigationToMatch().
from_keyword()
bool SearchSuggestionParser::Result::from_keyword () const inline
References from_keyword_.
Referenced by BaseSearchProvider::AddMatchToMap(), BaseSearchProvider::CreateSearchSuggestion(), BaseSearchProvider::GetFillIntoEdit(), SearchProvider::NavigationToMatch(), and SearchProvider::ShouldAppendExtraParams().
match_contents()
const std::u16string& SearchSuggestionParser::Result::match_contents () const inline
References match_contents_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::NavigationToMatch(), and SearchSuggestionParser::SuggestResult::SuggestResult().
match_contents_class()
const ACMatchClassifications& SearchSuggestionParser::Result::match_contents_class () const inline
References match_contents_class_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), and SearchProvider::NavigationToMatch().
received_after_last_keystroke()
bool SearchSuggestionParser::Result::received_after_last_keystroke () const inline
References received_after_last_keystroke_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::NavigationToMatch(), and set_received_after_last_keystroke().
relevance()
int SearchSuggestionParser::Result::relevance () const inline
References relevance_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::NavigationToMatch(), ZeroSuggestProvider::NavigationToMatch(), SearchProvider::CompareScoredResults::operator()(), and set_relevance().
relevance_from_server()
bool SearchSuggestionParser::Result::relevance_from_server () const inline
References relevance_from_server_.
Referenced by BaseSearchProvider::AddMatchToMap(), SearchProvider::NavigationToMatch(), and set_relevance_from_server().
set_received_after_last_keystroke()
void SearchSuggestionParser::Result::set_received_after_last_keystroke (bool received_after_last_keystroke) inline
References received_after_last_keystroke(), and received_after_last_keystroke_.
Referenced by BaseSearchProvider::CreateOnDeviceSearchSuggestion(), BaseSearchProvider::CreateSearchSuggestion(), and SearchProvider::ScoreHistoryResultsHelper().
set_relevance()
void SearchSuggestionParser::Result::set_relevance (int relevance) inline
References relevance(), and relevance_.
Referenced by SearchProvider::ApplyCalculatedNavigationRelevance(), and SearchProvider::ApplyCalculatedSuggestRelevance().
set_relevance_from_server()
void SearchSuggestionParser::Result::set_relevance_from_server (bool relevance_from_server) inline
References relevance_from_server(), and relevance_from_server_.
Referenced by SearchProvider::ApplyCalculatedNavigationRelevance(), and SearchProvider::ApplyCalculatedSuggestRelevance().
subtypes()
const std::vector<int>& SearchSuggestionParser::Result::subtypes () const inline
References subtypes_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::NavigationToMatch(), and ZeroSuggestProvider::NavigationToMatch().
type()
AutocompleteMatchType::Type SearchSuggestionParser::Result::type () const inline
References type_.
Referenced by BaseSearchProvider::CreateSearchSuggestion(), SearchProvider::NavigationToMatch(), and ZeroSuggestProvider::NavigationToMatch().
Member Data Documentation
deletion_url_
std::string SearchSuggestionParser::Result::deletion_url_ private
Referenced by deletion_url().
from_keyword_
bool SearchSuggestionParser::Result::from_keyword_ protected
Referenced by from_keyword().
match_contents_
std::u16string SearchSuggestionParser::Result::match_contents_ protected
Referenced by match_contents(), and SearchSuggestionParser::SuggestResult::SuggestResult().
match_contents_class_
ACMatchClassifications SearchSuggestionParser::Result::match_contents_class_ protected
Referenced by match_contents_class().
received_after_last_keystroke_
bool SearchSuggestionParser::Result::received_after_last_keystroke_ private
Referenced by received_after_last_keystroke(), and set_received_after_last_keystroke().
relevance_
int SearchSuggestionParser::Result::relevance_ protected
Referenced by relevance(), and set_relevance().
relevance_from_server_
bool SearchSuggestionParser::Result::relevance_from_server_ private
Referenced by relevance_from_server(), and set_relevance_from_server().
subtypes_
std::vector<int> SearchSuggestionParser::Result::subtypes_ protected
Referenced by subtypes().
type_
AutocompleteMatchType::Type SearchSuggestionParser::Result::type_ protected
Referenced by type().
The documentation for this class was generated from the following files:
components/omnibox/browser/search_suggestion_parser.h
components/omnibox/browser/search_suggestion_parser.cc