Chromium Omnibox: chrome/browser/ui/omnibox/clipboard_utils.h File Reference
clipboard_utils.h File Reference
#include <string>
Functions
std::u16string GetClipboardText (bool notify_if_restricted)
Variables
static const size_t kMaxClipboardTextLength = 500 * 1024
Function Documentation
GetClipboardText()
std::u16string GetClipboardText (bool notify_if_restricted)
References kMaxClipboardTextLength, OmniboxView::SanitizeTextForPaste(), and OmniboxView::StripJavascriptSchemas().
Referenced by OmniboxViewViews::ExecuteCommand(), OmniboxViewViews::GetLabelForCommandId(), OmniboxViewViews::IsCommandIdEnabled(), OmniboxViewViews::IsTextEditCommandEnabled(), and OmniboxViewViews::OnOmniboxPaste().
Variable Documentation
kMaxClipboardTextLength
const size_t kMaxClipboardTextLength = 500 * 1024 static
Referenced by GetClipboardText().